### PR TITLE
Added: links from model docs to respective model checkpoints on Hub

### PR DESCRIPTION
**Pull request by MKhalusova**
To aid navigation and discoverability, this PR adds links to respective model checkpoints on Hub to model docs (one link per model, in a format `https://huggingface.co/models?sort=downloads&search=YOSO`).  
A couple of maintenance changes are also included (copyright update and removal of obsolete disclaimers). 
UPD: reverted copyright to the original date

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Note that we're not changing the copyright years of the files: they are copyrighted from the year they were created.

**Comment by MKhalusova** [comment]
> Note that we're not changing the copyright years of the files: they are copyrighted from the year they were created.

I can revert them back, but I'd love to know why?

**Comment by sgugger** [comment]
Because there are many many many files in the library ;-) I also think it is bad practice to remove the year of the creation of the file, so if update there was, it would need to be something like 2020-20203 (for a file created in 2020), but I don't think the update is necessary at all.

@CarlosMFerr might have more insight on this!

**Comment by MKhalusova** [comment]
Since model summary rework, this PR is no longer relevant.

**Pull request closed without merging**
