### PR TITLE
Workflow: Replace `actions/post-slack` with centrally defined workflow

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

Cleans up a bit our actions repo by replacing the `actions/post-slack` workflow with the centrally defined one in `huggingface/hf-workflows` repository 

cc @amyeroberts

### CODE REVIEW

**Comment by younesbelkada** [comment]
Actually i might just remove that workflow completely in favor of: https://github.com/huggingface/hf-workflows/pull/9

**Comment by amyeroberts** [comment]
> Actually i might just remove that workflow completely in favor of: [huggingface/hf-workflows#9](https://github.com/huggingface/hf-workflows/pull/9) and use that centrally on all our HF repos

OK, let me know what you decide and if you still want a review. My vote would be for a more central, unified workflow. FWIW, we shouldn't need to adapt ci runs here because of other libraries - it hints at unnecessary dependencies

**Comment by younesbelkada** [comment]
thanks, yes I agree, just waiting for @glegendre01 's review on that PR and I will modify this PR to use that centralized GHA instead 🙏 will ping you once all is set!

**Comment by younesbelkada** [comment]
cc @amyeroberts this is ready for review!

**Review by amyeroberts — APPROVED** [review]
Thanks! It's always nice to see lots of code deleted :D

**Comment by ArthurZucker** [comment]
https://github.com/huggingface/transformers/actions/runs/9062296650/job/24895867294 seems to have broken the slow ci tests

**Pull request merged**
