### PR TITLE
[Flax] token-classification model steps enumerate start from 1

### PR DESCRIPTION
**Pull request by kamalkraj**
# What does this PR do?

Model saving at the last step was skipped due to enumerate starting at 0. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger @patil-suraj

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Thanks for the PR. I think it makes more sense to adjust the computation of `cur_step` a few lines below instead, what do you think?

**Comment by kamalkraj** [comment]
You mean here
https://github.com/huggingface/transformers/blob/2b87fdac6c3ff6483eb4d8f98bbd4e1374ac4958/examples/flax/token-classification/run_flax_ner.py#L602

Like this `cur_step = (epoch * step_per_epoch) + (step + 1) `

**Comment by sgugger** [comment]
Yes, exactly!

**Review by patil-suraj — APPROVED** [review]
LGTM! Thanks for fixing

**Pull request merged**
