### PR TITLE
[testing] replace hardcoded paths to allow running tests from anywhere

### PR DESCRIPTION
**Pull request by stas00**
Currently, some tests can be run only from the root of the project, since they hardcode relative paths.

With this PR, it's now possible to run tests from the root of the project, from inside `tests`, or really anywhere.

the gist of the change:
```
- PATH_SAMPLE_TEXT = "./tests/fixtures/sample_text.txt"
+ PATH_SAMPLE_TEXT = f"{get_tests_dir()}/fixtures/sample_text.txt"
```
now can do:
```
pytest tests/test_trainer.py
```
and:
```
cd tests
pytest ./test_trainer.py
```
or even:
```
cd examples
pytest ../tests/test_trainer.py
```
i.e. you no longer need to go to the root of the project to run tests

(I'm trying to figure out the codecov issue, running multiple tests, so it's easier to run tests from within `tests` dir)

p.s. CI failures are unrelated.

### CODE REVIEW

**Review by JetRunner — APPROVED** [review]
LGTM!

**Comment by stas00** [comment]
CI failure is unrelated to this PR

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks!

**Comment by sshleifer** [comment]
so dope!

**Pull request merged**
