### PR TITLE
🚨 Fully revert atomic checkpointing 🚨

### LINKED ISSUE #28027: 4.36 transformers got wrong _save_checkpoint  with deepspeed. work with previous versions
### System Info

transformers: 4.36.0
python: 3.10
deepspeed:  0.9.4                   

Traceback (most recent call last):
  File "/home/xxxx/xxxx/src/./xxxx.py", line 363, in <module>
    main(args)
  File "/home/xxxx/xxxx/src/./xxxx.py", line 352, in main
    run_training(args, train_dataset, eval_dataset, len(tokenizer))
  File "/home/xxxx/xxxx/src/./xxxx.py", line 339, in run_training
    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 1914, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 2274, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/xxxx/miniconda3/envs/xxxx/lib/python3.10/site-packages/transformers/trainer.py", line 2383, in _save_checkpoint
    os.rename(staging_output_dir, output_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxx/tmp-checkpoint-100' -> '/home/xxxx/checkpoint-100'

**When Using deepspeed with Trainer, 4.36 just have the wrong code, see below:**

https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L2352C13-L2352C83

You may need a PR for this.

### Who can help?

@muellerzr @pacman100

Like below. 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

quite simple, just with the simplest code example.

trainer = Trainer(
      model=model,
      args=training_args,
      train_dataset=train_data,
      eval_dataset=val_data,
  )
  print("Training...")
  trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)

### Expected behavior

no error would be fine

### LINKED ISSUE #29382: Permission Denied Error When Saving Checkpoint During Training
### System Info

- `transformers` version: 4.37.1
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.11.1
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: 0.26.1
- PyTorch version (GPU?): 2.2.1+cpu (False)

### Who can help?

_No response_

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Follow exactly the Image Classification example in the HuggingFace docs: https://huggingface.co/docs/transformers/tasks/image_classification
2. Error thrown at `trainer.train()` 
TrainingError

### Expected behavior

Should train normally.

Issue and possible solution identified on forum earlier this year: https://discuss.huggingface.co/t/permission-issues-when-saving-model-checkpoint/70109/2

Removing (or commenting out, like pictured below) lines 2417-2420 of transformers/trainer.py resolves issue without further errors, but may have complications for other tasks.

TrainerCommentedOut

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

As discussed offline, while on paper having atomic checkpointing was a good idea, it's unmaintainable by the core maintainers and has resulted in an influx of issues from users considering the wide variety of storage options available to them. (and untestable)

As the feature request, while reasonable and from a good mindset, was not due to an outright bug, we are reverting it entirely. 

Related PRs:

https://github.com/huggingface/transformers/pull/27820, https://github.com/huggingface/transformers/pull/28364

Did revert based on this commit: https://github.com/huggingface/transformers/commit/fe8d1302c7d5852ef96a9fb0fdd2a81eb3e1bdc6

Related issues: 
* https://github.com/huggingface/transformers/issues/27925
* https://github.com/huggingface/transformers/issues/28027
* https://github.com/huggingface/transformers/issues/29382

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @LysandreJik

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Thank you. That's a good learning experience for me, saving files is tricky and a lot of users have a lot of different hardwares!

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing! Agreed removing this feature is a good idea.  

Let's add a 🚨 prefix to the PR title so we know this is a "breaking" change - i.e. behaviour is changing between releases

**Comment by Chandler-Bing** [comment]
wonderful PR! hope 4.38.3 version release soon

**Comment by shiningliang** [comment]
Will this change be included in 4.38.3? Thanks

**Comment by amyeroberts** [comment]
@Chandler-Bing @shiningliang 4.38.2 -> 4.38.3 would represent a patch release, these are reserved for fixing regressions or unintended breaking changes from a minor release i.e. 4.37 -> 4.38. 

We have minor releases roughly once a month, so the next release, 4.39.0 will be in a week or two.

**Comment by wxjiao** [comment]
Nice PR! Upgraded transformers to the latest version (i.e., main), now the checkpoints can be saved smoothly in mult-node setting.

**Pull request merged**
