### PR TITLE
Support PEFT models when saving the model using trainer

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

Currently if one calls `save_model` using the Trainer or `push_to_hub` with a PEFT model, it will push the base model instead of the adapters

to reproduce (after `pip install trl peft transformers`):
```python
from datasets import load_dataset
from trl import SFTTrainer
from peft import LoraConfig

dataset = load_dataset("imdb", split="train")

peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

trainer = SFTTrainer(
    "EleutherAI/gpt-neo-125m",
    train_dataset=dataset,
    dataset_text_field="text",
    peft_config=peft_config
)
trainer.save_model("test-sft")
```

cc @pacman100 @sgugger @amyeroberts

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Clean, LGTM!

**Review by pacman100 — APPROVED** [review]
Thank you @younesbelkada for clean support to save peft models, LGTM! 🤗

**Comment by zachschillaci27** [comment]
How do we make sure this is the behavior when checkpointing the model during training?

Thanks!

**Comment by younesbelkada** [comment]
hi @zachschillaci27 ,
you can check the folders that are produced by trainer during training and make sure they contain `adapter_model.safetensors` or `adapter_model.bin` files

**Comment by zachschillaci27** [comment]
> hi @zachschillaci27 , you can check the folders that are produced by trainer during training and make sure they contain `adapter_model.safetensors` or `adapter_model.bin` files

Thanks for the fast reply!

**Pull request merged**
