### PR TITLE
fix: when window_size is passes as array

### PR DESCRIPTION
**Pull request by dotneet**
# What does this PR do?

The window_size should have been implemented to allow separate values for height and width, but it was not working. This fixes that problem.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@amyeroberts @nandwalritik @SatyaJandhyalaAtMS

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! Thanks for opening a PR. When you say that it should have been this way, do you mean compared to the original code? 
Because I am not entirely sure there are general uses cases when we need this / checkpoints that need this! If it is for a custom usage we can't really add this IMO

**Comment by dotneet** [comment]
@ArthurZucker 
Thanks for the reply.

See the existing code here.
https://github.com/huggingface/transformers/blob/21dc5859421cf0d7d82d374b10f533611745a8c5/src/transformers/models/swinv2/modeling_swinv2.py#L437

Originally, window_size was obviously an implementation that could be passed as an array.
However, due to some code, it was not possible to actually pass the array. I fixed that.

I want to train optimized for horizontal images, not square images. To do this, I believe image_size, patch_size, and window_size would all need to be set to separate values for height and width. I don't think this is a rare case.

In fact, there are people who need it here in the repository.

https://github.com/microsoft/Swin-Transformer/issues/44
https://github.com/microsoft/Swin-Transformer/issues/141

**Review by ArthurZucker — APPROVED** [review]
Looks good to me, will ask @rafaelpadilla for a second look!

**Review by rafaelpadilla — APPROVED** [review]
Hey @ArthurZucker :)
Looks good to me as well.
Let's keep this solution in mind for other models that possibly only allow square images.

**Pull request merged**
