### PR TITLE
Model card: Literary German BERT

### PR DESCRIPTION
**Pull request by severinsimmler**
This PR adds a model card for [severinsimmler/literary-german-bert](https://huggingface.co/severinsimmler/literary-german-bert), a domain-adapted and fine-tuned BERT for named entity recognition in German literary texts.

### CODE REVIEW

**Comment by stefan-it** [comment]
Thanks for using our BERT model! Great to see that your fine-tuned model beats the CRF baseline :)

**Comment by severinsimmler** [comment]
Thanks for sharing your German BERT -- outperformed the multilingual one by the way.

**Comment by julien-c** [comment]
@severinsimmler Thank you! I tweaked the references to images (this should be documented at some point, but not sure where we can put it for now) + added tags

Also thank you @stefan-it

**Comment by severinsimmler** [comment]
Hi @julien-c, why is this page offline? https://huggingface.co/severinsimmler/literary-german-bert

The model is neither listed here anymore: https://huggingface.co/models

nor says my user page that there are any published models: https://huggingface.co/severinsimmler

But the CLI says it's still there:

```
$ transformers-cli s3 ls
Filename                                     LastModified             ETag                               Size      
-------------------------------------------- ------------------------ ---------------------------------- --------- 
literary-german-bert/config.json             2020-02-13T13:37:48.000Z "7e68409fc147acec10dadb06b33d0ba6"      1043 
literary-german-bert/eval_results.txt        2020-02-13T12:24:48.000Z "cda28cf0e39c7783bf8c8995ef940492"       147 
literary-german-bert/pytorch_model.bin       2020-02-13T12:25:18.000Z "27c22d3d221287715ca781d3939f9bb2" 439770223 
literary-german-bert/special_tokens_map.json 2020-02-13T12:24:50.000Z "8b3fb1023167bb4ab9d70708eb05f6ec"       112 
literary-german-bert/test_results.txt        2020-02-13T12:24:45.000Z "c5276b24e5788305862f5b7bc847fa95"       147 
literary-german-bert/tokenizer_config.json   2020-02-13T12:24:49.000Z "b2db3b45d8945539dab67f41f04101d7"       152 
literary-german-bert/training_args.bin       2020-02-13T12:24:44.000Z "ce5c09e8214e66daa6a97005f20e7300"      1309 
literary-german-bert/vocab.txt               2020-02-13T12:24:46.000Z "5787056a1ea58629b0c71cfc37728ce4"    239836 
```

And I am also able to download and use it. 🤔

**Comment by julien-c** [comment]
We had a small hiccup on the website (due to improperly sanitized user-input – a.k.a. developer error :)

Your model should be back up.

**Comment by severinsimmler** [comment]
Thanks for the quick response and fix! Keep up the great work :)

**Pull request merged**
