### PR TITLE
Fix CI after #30410

### PR DESCRIPTION
**Pull request by zucchini-nlp**
# What does this PR do?

As per title, the prev PR forgot to replace Embedding layer in one of the models which caused red CI. This PR fixes it :)

cc @ydshieh

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thanks a lot. And LGTM.

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by ydshieh** [comment]
@zucchini-nlp would you like to try the `run-slow` feature 😆 ?

**Comment by ydshieh** [comment]
Rebase on main to include #30540 (if not yet)

Push an empty commit with the message: `[run-slow] blenderbot`

**Comment by zucchini-nlp** [comment]
Yes, lets see the slow-tests in action 😄

**Comment by ydshieh** [comment]
```
========== 229 passed, 151 skipped, 73 warnings in 570.48s (0:09:30) ===========
```

**Pull request merged**
