### PR TITLE
Add Onnx Config for PoolFormer

### PR DESCRIPTION
**Pull request by BakingBrains**
# What does this PR do?

Fixes # (https://github.com/huggingface/transformers/issues/16308)

Add changes to make PoolFormer models available for Onnx conversion.

Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ChainYo

### CODE REVIEW

**Comment by BakingBrains** [comment]
@ChainYo @michaelbenayoun I have mistakenly closed that previous pull request. Create this with resolved conflicts.

**Review by michaelbenayoun — APPROVED** [review]
LGTM!
(You can go to the Optimum repo to add support there as well)

**Comment by BakingBrains** [comment]
Yeah I will do that

**Review by sgugger — APPROVED** [review]
Thanks for your contribution!

**Comment by BakingBrains** [comment]
Thank you

**Pull request merged**
