### PR TITLE
Pin maximum TF version

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

We now also depend on `tensorflow-text`, whose minor versions are typically released a few days after new `tensorflow` releases. From tests against the `tensorflow` release candidate, `tensorflow-text`-based functions fail when these two libraries do not have the same version.

This PR pins the maximum TF version so that our CI doesn't break with the upcoming `tensorflow` release. When the corresponding `tensorflow-text` library gets released we should be able to unpin it again.

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thanks @gante for taking care of upcoming TF release and tests.
LGTM - we just need to remember to remove this once `tensorflow-text` is ready.

**Review by LysandreJik — APPROVED** [review]
Looks good to me, let's not forget to unpin! (Great minds think alike, @ydshieh!)

**Comment by gante** [comment]
@ydshieh the CI fail seems unrelated 🤔 do you know potential causes?

**Comment by LysandreJik** [comment]
Yes I think that's an unrelated error linked to a new cache being made as the `setup.py` is updated. It's unrelated to the PR, but we need to have a look at what's going on.

Let's merge this PR!

Thanks for your contribution :)

**Pull request merged**
