### PR TITLE
Move weight initilization deformabledetr

### LINKED ISSUE #29818: Move weight initialization for DeformableDetr
### System Info

Not relevant

### Reproduction

See [Deformable Detr Modeling](https://github.com/huggingface/transformers/blob/main/src/transformers/models/deformable_detr/modeling_deformable_detr.py#L653). 

### Expected behavior

All weight initializations should be done in `_init_weights` of the `xxxPretrainedModel` class

### PR DESCRIPTION
**Pull request by g-prz**
# What does this PR do?

Moves the weight initialization of DeformableDetr, RtDetr and GroundingDino. 

Fixes #29818 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@amyeroberts 🤗

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Awesome - thanks for handling this! 

We'll need to run the slow model tests before merging, but all looks good to me. Could you push an empty commit with the message `[run-slow] deformable_detr, grounding_dino, rt_detr`? This should trigger the slow tests (I'll need to approve the workflow)

**Comment by g-prz** [comment]
Hey @amyeroberts 😁 
Is it all ok on your side?

**Comment by amyeroberts** [comment]
Hi @g-prz, apologies for the delay. It looks like there's one test which is failing for grounding dino. Do you have access to a GPU to be able to run, replicate and debug: 

```
tests/models/grounding_dino/test_modeling_grounding_dino.py::GroundingDinoModelIntegrationTests::test_inference_object_detection_head_equivalence_cpu_gpu
```

**Comment by g-prz** [comment]
Hey @amyeroberts, no problem 😊 
I have a Mac and ran locally with `mps` backend. I effectively find some differences in the output tensors. I don't have many leads on what to investigate 😅  I would be pleased for some support or any idea to start with?

**Comment by g-prz** [comment]
Hey @amyeroberts 🙋‍♂️ 
I spent a bit more time investigating trying to understand what is happening. Apparently the test also fails on main. To what I see, the error (1.6e-3) starts to happen in one of the `Swin` layers and propagates down the net.

**Review by amyeroberts — APPROVED** [review]
Thanks for updating these!

**Comment by amyeroberts** [comment]
@g-prz Thanks for investigating and for the update! OK, if it's also failing on main then we're good to merge :) I'm going to wait until Monday to save us a late-ish weekend merge so we can catch anything quickly

**Pull request merged**
