### PR TITLE
Translated version of model_sharing.mdx doc to spanish

### PR DESCRIPTION
**Pull request by Gerard-170**
# What does this PR do?
This PR is related to #15947  issue.

This PR translates the model_sharing.mdx file to a spanish version of it and save it into transformers\docs\source_es path. This translation tries to keep the structure and ideas behind each statement, adding some words and translation where there's not specific one-to-one translation in Spanish, in other cases it adds words for a better flow of ideas. 

Any comment with respect to this translation is welcome while we try to figure out the better way to give Spanish-speaker community the best documentation about HuggingFace. 

Thank you.

### CODE REVIEW

**Comment by omarespejel** [comment]
Thanks, @Gerard-170! I will review it during the week :)

**Comment by omarespejel** [comment]
Hola @Gerard-170! I just wanted to follow up with your PR 🤗! Please let me know if you need anything else.

**Comment by Gerard-170** [comment]
Hi! @omarespejel  Well I was waiting the review. whether you have some comments about the translation or not. Let me know what you think! and Happy to contribute!! Thank you! :D

**Review by omarespejel — CHANGES_REQUESTED** [review]
Sorry, @Gerard-170! I got confused and did not send my review. Here it is.

**Comment by Gerard-170** [comment]
Hi! Sorry for a late response, of course I will add model_sharing to [transformers/docs/source/es/_toctree.yml](https://github.com/huggingface/transformers/blob/main/docs/source/es/_toctree.yml).

**Comment by omarespejel** [comment]
Thank you @Gerard-170! Also please run `git pull upstream master` to merge all the changes made to `main` (note we recently went from `master` to `main`, and this is still not reflected in your fork).

**Comment by omarespejel** [comment]
Hola @Gerard-170! Muchas gracias. It looks great, there is a style error that we recently corrected in another file. Could you please run `git pull upstream main` again so this gets corrected? I think this will do the trick.

**Comment by omarespejel** [comment]
Hola @Gerard-170! Muchas gracias. It looks great, there is a style error that we recently corrected in another file. Could you please run `git pull upstream main` again so this gets corrected? I think this will do the trick.

**Comment by Gerard-170** [comment]
Hola @omarespejel Yes! I did again git pull and all checks have passed! :D Please let me know if you need something else. Gracias!

**Review by omarespejel — APPROVED** [review]

**Comment by omarespejel** [comment]
Thank you @Gerard-170! This is great 🤗.

@sgugger LGTM 👍

**Pull request merged**
