### PR TITLE
Fix typo in toctree

### PR DESCRIPTION
**Pull request by mishig25**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Great catch!

**Comment by mishig25** [comment]
regarding this conversation, every new doc page needs to be added in _toctree.yml (it serves the same purpose as this section of previous index.rst)
https://github.com/huggingface/transformers/blame/fc1d97f29d7b98e82ae17fc5ac49229e2859bcca/docs/source/index.rst#L603-L652
we can probably create some automatic script that adds a new model to toctree
@sgugger @LysandreJik

**Comment by LysandreJik** [comment]
Indeed, @sgugger was mentioning the same just yesterday :)

**Comment by sgugger** [comment]
Yes, I plan to add a failure to the doc-builder if there is a MDX generated that ends up not being in the index (like sphinx used to do). Finishing the conversion to notebook and will add that next :-)

**Pull request merged**
