### PR TITLE
Speed up `BeamScorer` by 1000%

### LINKED ISSUE #20820: (Will make a PR) `BeamScorer` is super slow and takes 2x time compared with model itself, and can speed up by 1000%
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.23
- Python version: 3.10.0
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@gante

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Run `.generate(num_beams=3)` thus use beam search.

### Expected behavior

Should be fast, but it is super slow.

I am working on a fix and will soon make a PR (today?). Just want to open this issue first so that I can get some early feedbacks (e.g. do you welcome PRs?).

One cause I realize is that, the BeamScorer.process etc is working on torch tensors on gpu, *one by one*. I refactored it so it works on numpy arrays on cpu, and it is 3x faster.

---

If you are interested, here are some *very early* results:

before (scorer takes 7.37s)

image

after (scorer 2.72s, still slow but better)

image

### PR DESCRIPTION
**Pull request by fzyzcjy**
# What does this PR do?

Fixes #20820

For reasons, explanations, benchmarks, etc, please have a look at the issue

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by fzyzcjy** [comment]
I am really unfamiliar with huggingface CI, it errors:

```
From github.com:huggingface/transformers
 * [new ref]             refs/pull/21234/head -> origin/pull/21234
Checking out branch
fatal: reference is not a tree: 9fb13c79a72d13cdf0dd59d48762cd7c95370b29

exit status 128
```

Do not think I can fix this :/

image

**Review by gante — COMMENTED** [review]
Before addressing the comments, let's first make sure this change is worth merging :) We won't accept PRs that make the code harder to read (as most vectorized versions of an algorithm are) unless there are clear benefits.

I will need execution time numbers of `.generate()` from a model at least as big as `gpt2`, before and after this change, for several number of beams (e.g. 2, 4, 8, and 16). Ideally with and without GPU.

**Comment by fzyzcjy** [comment]
> Before addressing the comments, let's first make sure this change is worth merging :) We won't accept PRs that make the code harder to read (as most vectorized versions of an algorithm are) unless there are clear benefits.
I will need execution time numbers of .generate() from a model at least as big as gpt2, before and after this change, for several number of beams (e.g. 2, 4, 8, and 16). Ideally with and without GPU.

Totally understand your concerns :) I do not have much time now (you know, doing research and maintaining [my open source libs](https://github.com/fzyzcjy)), but will try to squeeze out some time when possible. Anyway, the PR in its current status may already be somehow useful for users who finds out it is too slow, since they can manually copy and tweak the `generate` function to use a custom scorer.

**Comment by fzyzcjy** [comment]
@KexinFeng Thanks!

**Comment by gante** [comment]
FYI we will be introducing fixed-sized caches in text generation soon (akin to our TF and JAX implementations), which will also imply a refactor (vectorization) of beam methods :)

**Comment by fzyzcjy** [comment]
> @gante FYI we will be introducing fixed-sized caches in text generation soon (akin to our TF and JAX implementations), which will also imply a refactor (vectorization) of beam methods :)

Hi, is there any updates? I checked latest BeamScorer and the code does not look very different.

**Comment by fzyzcjy** [comment]
@gante I briefly tested using latest code on `gpt-2` with num_beams=2,4,8,16, and observe 2.25x - 3.31x speedup. Thus, shall I open a new PR for this?

Code (referencing my internal modified code, but it is just a migrated version of this PR and nothing new at all):

<details>

```python
import torch
import transformers
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig, BeamSearchScorer
import time
import polars as pl
import plotly.express as px
from research_mono.modified_third_party.transformers.generation.utils import generation_mixin_generate
from research_mono.modified_third_party.transformers.generation.beam_search import MyBeamSearchScorer

model = AutoModelForCausalLM.from_pretrained("gpt2")
tokenizer = AutoTokenizer.from_pretrained("gpt2")

model = model.to('cuda')

rows = []

dummy = 0.0

for num_beams in [16, 8, 4, 2]:
    times = {}
    
    for enable_fast in [True, False]:
        input_ids = torch.randint(1000, 2000, (2048 // num_beams, 8)).to(model.device)
        
        beam_search_scorer_cls = [BeamSearchScorer, MyBeamSearchScorer][enable_fast]
        
        generation_config = GenerationConfig(
            max_new_tokens=32,
            num_return_sequences=num_beams,
            pad_token_id=tokenizer.eos_token_id,
            num_beams=num_beams,
            do_sample=False,
        )

        t_start = time.time()
        with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
            for _ in range(10):
                gen_tokens = generation_mixin_generate(model, beam_search_scorer_cls, input_ids=input_ids, generation_config=generation_config)
                dummy += torch.max(gen_tokens).detach().cpu().item()
        t_end = time.time()

        t_delta = t_end - t_start
        times[['time_slow', 'time_fast'][int(enable_fast)]] = t_delta

        print(f'{gen_tokens.shape=} {t_delta=}')

    row = dict(
        num_beams=num_beams,
        time_ratio=times['time_slow'] / times['time_fast'],
        **times,
    )
    rows.append(row)

    print(row)

df_all = pl.DataFrame(rows)
display(df_all)

df = df_all.with_row_index()
px.line(df.to_pandas(), x='index', y='time_ratio')
```

</details>

Gives:

Pasted image 20240502194650

**Comment by fzyzcjy** [comment]
@gante I briefly tested using latest code on `gpt-2` with num_beams=2,4,8,16, and observe 2.25x - 3.31x speedup. Thus, shall I open a new PR for this?

Code (referencing my internal modified code, but it is just a migrated version of this PR and nothing new at all):

<details>

```python
import torch
import transformers
from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig, BeamSearchScorer
import time
import polars as pl
import plotly.express as px
from research_mono.modified_third_party.transformers.generation.utils import generation_mixin_generate
from research_mono.modified_third_party.transformers.generation.beam_search import MyBeamSearchScorer

model = AutoModelForCausalLM.from_pretrained("gpt2")
tokenizer = AutoTokenizer.from_pretrained("gpt2")

model = model.to('cuda')

rows = []

dummy = 0.0

for num_beams in [16, 8, 4, 2]:
    times = {}
    
    for enable_fast in [True, False]:
        input_ids = torch.randint(1000, 2000, (2048 // num_beams, 8)).to(model.device)
        
        beam_search_scorer_cls = [BeamSearchScorer, MyBeamSearchScorer][enable_fast]
        
        generation_config = GenerationConfig(
            max_new_tokens=32,
            num_return_sequences=num_beams,
            pad_token_id=tokenizer.eos_token_id,
            num_beams=num_beams,
            do_sample=False,
        )

        t_start = time.time()
        with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
            for _ in range(10):
                gen_tokens = generation_mixin_generate(model, beam_search_scorer_cls, input_ids=input_ids, generation_config=generation_config)
                dummy += torch.max(gen_tokens).detach().cpu().item()
        t_end = time.time()

        t_delta = t_end - t_start
        times[['time_slow', 'time_fast'][int(enable_fast)]] = t_delta

    row = dict(
        num_beams=num_beams,
        time_ratio=times['time_slow'] / times['time_fast'],
    )
    rows.append(row)

df_all = pl.DataFrame(rows)
display(df_all)

df = df_all.with_row_index()
px.line(df.to_pandas(), x='index', y='time_ratio')
```

</details>

Gives:

image

**Pull request closed without merging**
