### PR TITLE
Include tensorflow-aarch64 as a candidate

### PR DESCRIPTION
**Pull request by ankrgyl**
# Include tensorflow-aarch64 as a candidate

Fixes # 18323
@LysandreJik

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
This looks quite good! Thanks @ankrgyl :)

**Comment by LysandreJik** [comment]
(I'm waiting for the tests to pass before merging)

**Comment by ankrgyl** [comment]
Thank you! What is the next step -- do I close it or merge it somehow? Apologies for my unfamiliarity with the process.

**Comment by LysandreJik** [comment]
I'll merge it as soon as everything is green :)

**Comment by ankrgyl** [comment]
Okay great! Thank you for your responsiveness.

**Comment by LysandreJik** [comment]
Done! Thanks for your contribution @ankrgyl!

**Pull request merged**
