### PR TITLE
[Umberto] model shortcuts

### PR DESCRIPTION
**Pull request by julien-c**
cc @loretoparisi @simonefrancia

see #2485

### CODE REVIEW

**Comment by julien-c** [comment]
Failing test is Heisenbug

**Comment by loretoparisi** [comment]
@julien-c thank you we are looking at it right now.

**Comment by julien-c** [comment]
Model pages are at:

- https://huggingface.co/Musixmatch/umberto-commoncrawl-cased-v1
- https://huggingface.co/Musixmatch/umberto-wikipedia-uncased-v1

**Comment by loretoparisi** [comment]
@julien-c Thanks, very happy to contribute! Is it possibile to update the profile image [here](https://huggingface.co/Musixmatch) to the right one in the model's readme [here](https://huggingface.co/Musixmatch/umberto-commoncrawl-cased-v1)?
Thanks a lot again.

**Comment by julien-c** [comment]
Do you mean using this image: https://user-images.githubusercontent.com/163333/72244273-396aa380-35ee-11ea-894b-4ea48230c02b.png
?

We don't have a feature for this for now, but I will change it manually.

**Comment by loretoparisi** [comment]
@julien-c yep!

**Pull request merged**
