### PR TITLE
Make the TF dummies even smaller

### PR DESCRIPTION
**Pull request by Rocketknight1**
cc @ydshieh - this will probably break some things, but if I can make it work it should reduce the memory usage during building a lot

### CODE REVIEW

**Comment by Rocketknight1** [comment]
Adding @frostming's fix for Keras 2.13 to this PR as well

**Comment by Rocketknight1** [comment]
Tests are passing now, pinging @ydshieh and @amyeroberts for quick review! Unfortunately it's quite hard for me to test if this PR will fix the entire memory issue in the overnight CI, but we'll try this fix and if the memory issues remain then I'll try some other things too.

**Comment by ydshieh** [comment]
I can trigger a run.

**Review by amyeroberts — APPROVED** [review]
LGTM 👍  Thanks for iterating on this

For my own understanding: do we know why the new build logic is triggering the OOM issues (what's the difference from before)? Would these failures happen if just one model was being tested - or does it happen after N models being tested?

**Comment by ydshieh** [comment]
I also have the same question on why the memory usage increases that much. Previously, we don't really use batch size 1 in dummy if I remember correctly.

**Comment by ydshieh** [comment]
A run is triggered [here](https://app.circleci.com/pipelines/github/huggingface/transformers/65919/workflows/b0c80ba6-3278-47a0-87d9-228c402b35e9/jobs/819654).

If you need more changes and more runs to check, you can update the branch 

https://github.com/huggingface/transformers/tree/run_even_lower_tf_dummy_memory

on top of this PR branch.

**Comment by Rocketknight1** [comment]
@ydshieh the new run seems to be passing - there's an unrelated issue with one of the vit-mae tests that I can't reproduce locally and that doesn't seem related, but I think this PR resolves most of the problems!

**Comment by ydshieh** [comment]
Well, to be more sure, I can revert the PR #23234 on **another branch**, so would be `main` without that PR, and run the test. The goal is to make sure no other PRs contribute to the OOM issue.

Do you want me to do this?

**Comment by Rocketknight1** [comment]
No, I'm pretty confident that the change to the dummies is the cause!

**Review by ydshieh — APPROVED** [review]
OK

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
