### PR TITLE
Add "accelerate" to the list of required pacakges

### PR DESCRIPTION
**Pull request by correll**
# What does this PR do?

Added "accelerate" to the list of required packages

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! I don't think the trainer (only part of the code that could use it) requires accelerate, would you mind sharing the motivations behind this?

**Comment by correll** [comment]
I include the error message when running "train()". Apparently it is only needed when using torch. 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-11-6385862da3e9>](https://localhost:8080/#) in <cell line: 1>()
----> 1 training_args = TrainingArguments(
      2     output_dir="segformer-b0-scene-parse-150",
      3     learning_rate=6e-5,
      4     num_train_epochs=5,
      5     per_device_train_batch_size=2,

4 frames
[/usr/local/lib/python3.10/dist-packages/transformers/training_args.py](https://localhost:8080/#) in _setup_devices(self)
   1785         if not is_sagemaker_mp_enabled():
   1786             if not is_accelerate_available(min_version="0.20.1"):
-> 1787                 raise ImportError(
   1788                     "Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`"
   1789                 )

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`

**Comment by muellerzr** [comment]
Correct, which is why it's part of `transformers[torch]` (as it's only applicable to the torch backend). We should never always install accelerate with base transformers

**Comment by correll** [comment]
pip install transformers[torch] did not work  on my machine, but indeed does work on colab.

**Pull request closed without merging**
