### PR TITLE
[pipelines] Change summarization default to distilbart-cnn-12-6

### PR DESCRIPTION
**Pull request by sshleifer**
- Also adds an integration test that runs on GPU if available.
- Other pipelines could do the same if that would be helpful.

### CODE REVIEW

**Comment by sshleifer** [comment]
CI Failure is spurious.

**Review by LysandreJik — APPROVED** [review]
Cool! Fast!

**Review by patrickvonplaten — APPROVED** [review]

**Comment by ShoubhikBanerjee** [comment]
Could you please tell me in **distilbart-cnn-12-6** what does **12 & 6** stands for?

**Comment by patrickvonplaten** [comment]
12 Encoder layers and 6 decoder layers I would suggest

**Comment by ShoubhikBanerjee** [comment]
Thank you Sir, @patrickvonplaten

**Pull request merged**
