### PR TITLE
Fix overwrite_cache behaviour for pytorch lightning examples

### PR DESCRIPTION
**Pull request by simonepri**
cc: @nateraw

Ref: #3290

### CODE REVIEW

**Comment by nateraw** [comment]
Not sure when it got broken, but this looks ok at first glance to me. I'll pull it down tonight as a sanity check to run it. 

Thank you!

**Comment by simonepri** [comment]
> but this looks ok at first glance to me

What do you mean exactly?
The `overwrite_cache` argument is not even used at all in one of the two examples.

**Review by sshleifer — COMMENTED** [review]
LGTM! @LysandreJik

**Comment by nateraw** [comment]
LGTM too 😄 Thank you again, @simonepri

**Pull request merged**
