### PR TITLE
Loosen output shape restrictions on GPT-style models

### PR DESCRIPTION
**Pull request by calpt**
# What does this PR do?

This PR loosens checks in the model classes of a couple of GPT-style models that enforce the output shape of the model to be identical to the input shape. This aligns the changed model classes to most other model classes which don't enforce the shapes to be identical.

I might not be aware of some legitimate reasons why these restrictions are in place specifically for these models. Please let me know if there are any and I'll close this PR :) 

## Motivation

We're building a library on top of Transformers that leverages various model implementations. Among others, some features in our library will result in the batch size to change dynamically during one model forward pass. While implementing these features, we didn't find this to be an issue for most model classes as they don't require the input and output shapes to be identical. However, some GPT-style models do enforce this. To avoid copying and keeping in sync the full model classes, it would be super helpful to us if these restrictions could also be loosened for GPT models.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

- text models: @ArthurZucker and @younesbelkada

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
I do believe that there are cleaner ways to do the reshaping. The reason why you probably did not have any issue with other models is because they do not apply this final reshaping. It's old code (copy pasted of GPT2). Makes sense to change this for me as recent models don't use this. (we usually don't try to accommodate hard for other libraries 😅 ) but this piece of code is already not clean.   

WDYT @amyeroberts

**Comment by amyeroberts** [comment]
In principle, it should be OK to loosen this restriction as it doesn't introduce any breaking changes. However, it is making the code more likely to have a silent bug. Let's get a second opinion from @sgugger

With regard to the changes, I'd prefer that the instead of slicing, `input_shape[1:]`, we name each of the dimensions explicitly so it's clearer what `output_shape` is e.g. `output_shape = (-1, sequence_length, hidden_size)`.

**Review by sgugger — APPROVED** [review]
This works for me, I don't think it should have any negative impact. Good to go once Amy's comment is addressed.

**Review by sgugger — COMMENTED** [review]
Looks like this breaks some GPT2 tests though.

**Comment by calpt** [comment]
@sgugger Yes, I realized that `input_ids` can have varying number of dimensions, so naming all dimensions explicitly might get a bit more convoluted than the slicing approach.

**Comment by sgugger** [comment]
Ok for you @amyeroberts ?

**Review by amyeroberts — APPROVED** [review]
@calpt Thanks for adding this! 

Thanks for trying with the explicit names too :)

**Pull request merged**
