### PR TITLE
[Doctest] Add configuration_big_bird.py

### PR DESCRIPTION
**Pull request by lappemic**
1. Change the import order of the model and configuration classes
2. Add `configuration_big_bird.py` to `utils/documentation_tests.txt` for doctest.

Documentation edit according to #19487

@sgugger could you have a look on this?

### CODE REVIEW

**Comment by Xabilahu** [comment]
This is already being fixed in https://github.com/huggingface/transformers/pull/19606

**Comment by lappemic** [comment]
Hey @Xabilahu ok, i did not see this, sorry. I though do not understand fully, your pull request regards `configuration_bigbird_pegasus.py` and mine `configuration_big_bird.py`. How is it, that these are belong to the same?

**Comment by Xabilahu** [comment]
I address both models in my PR.

**Comment by lappemic** [comment]
just saw it. Sorry, did not pay enough attention!

**Comment by ydshieh** [comment]
Hi @lappemic 

Still thank you. If you want to contribute, you can check [documentation_tests.txt](https://github.com/huggingface/transformers/blob/main/utils/documentation_tests.txt) on the main branch and see which ones are still missing :-)

**Pull request closed without merging**
