### PR TITLE
WIP: Added basic eos token based pooling

### LINKED ISSUE #21029: Fix CLIP pooling for textual inversion so that eos tokens are taken
### Feature request

For textual inversion in diffusers, we are adding tokens that have a higher token id than the eos token. So when we get clip embeddings for textual inv tokens, we need to change the pooling so it gets the eos token and not the arg max token.

### Motivation

This is an issue that should be fixed as the clip embeddings won't work once we add more tokens to the tokenizer.

### Your contribution

I can make a pr for this. This is not an issue in the original implementation of the clip since they use pre-existing tokens in the embedding which has its own pro-cons.

### PR DESCRIPTION
**Pull request by isamu-isozaki**
# What does this PR do?
This PR is still a WIP. This is based on [this issue](https://github.com/huggingface/transformers/issues/21029). The main problem is that when new tokens are added to the tokenizer and text model and learned such as with [textual inversion](https://textual-inversion.github.io/) the clip text model pools at the wrong location as the pooling is not done at the new token location and not the eos token id location

Fixes #21029

## Before submitting
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

Models:

- text models: @ArthurZucker and @younesbelkada

### CODE REVIEW

**Comment by isamu-isozaki** [comment]
Current informal tests to confirm that behavior isn't changed: 

In original

```
from transformers import CLIPTokenizer, CLIPTextModel
tokenizer=CLIPTokenizer.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="tokenizer")
text_encoder=CLIPTextModel.from_pretrained("CompVis/stable-diffusion-v1-4", subfolder="text_encoder").to("cuda")
encoded = text_encoder(**tokenizer(["hi my name is bob"], padding=True, return_tensors="pt").to("cuda"))
encoded.pooler_output
```
gives
```
tensor([[ 4.5786e-01,  6.4382e-02,  6.3140e-01,  6.2113e-01,  9.6310e-01,
         -9.7793e-02, -7.2665e-01, -7.6867e-01,  6.6914e-02,  6.3608e-01,
          1.4786e+00, -1.9321e-01, -1.1228e+00,  1.8028e+00,  8.4215e-01,
         -5.4223e-01, -6.0589e-01,  1.1507e+00,  1.3731e-01,  8.6263e-01,
         -1.6030e+00, -3.4565e-01,  7.7863e-01,  1.1875e+00, -2.1012e-01,
         -8.6532e-01,  1.6825e+00, -1.7904e+00, -8.4568e-01,  1.1287e+00,
         -4.8089e-02,  8.3013e-02, -1.9632e-01, -1.1975e+00,  6.4901e-02,
         -5.0897e-01,  5.4249e-01, -1.5505e+00, -6.8680e-01, -2.3254e-01,
          4.4073e-02, -4.4828e-01,  5.9905e-02, -8.1572e-01, -4.3026e-01,
          2.2344e-01, -5.1814e-01, -1.2628e+00, -3.0142e-01, -8.3002e-01,
          1.3578e-01, -9.6522e-02,  9.6978e-01,  2.3212e-01, -1.9383e+00,
         -9.2921e-01, -3.4377e-01, -1.6675e+00, -7.7125e-03,  2.5390e-01,
          6.1878e-01, -9.8021e-01, -1.6899e+00, -2.1923e-01, -2.3697e-01,
         -6.2671e-01, -1.8506e+00, -3.5010e-01, -1.1009e+00,  5.0743e+00,
         -2.3503e-01,  2.4777e-01, -6.8930e-01, -2.3754e+00,  4.5873e-01,
          1.7357e+00,  1.3578e+00, -4.0870e-02, -2.4192e-01, -6.4952e-01,
          5.4749e-01,  1.7376e+00,  4.7829e-01,  5.9760e-01,  2.1821e+00,
         -1.6562e+00,  6.5091e-01, -5.1810e-01,  7.3831e-01, -5.7401e-01,
         -3.6747e-01,  6.6895e-01,  5.2488e-01,  8.9032e-01, -1.3523e-01,
         -2.4476e-02, -3.8042e-01,  1.1379e+00,  9.3095e-01, -5.9501e-01,
         -6.2792e-01,  7.1275e-01, -4.0629e-01, -1.6718e-01, -1.1235e+00,
         -1.5194e+00, -6.6100e-01,  1.7905e+00, -1.1815e+00, -1.7777e+00,
         -6.8219e-01, -5.0594e-01, -2.7447e-01,  3.7931e-01,  1.2671e+00,
          1.0875e+00,  6.6296e-02, -9.9758e-01, -1.1253e+00, -2.4456e-01,
          7.3202e-01,  3.3661e-01, -2.0981e-01, -2.8638e-01,  7.4086e-01,
          1.4134e-01, -4.0398e-01,  3.1088e-01,  1.4451e-01, -3.6309e-01,
          1.9107e+00,  4.7684e-01, -1.7292e+00,  4.2101e-01, -7.9601e-01,
         -2.0712e+00,  3.5417e-01,  1.1261e+00, -4.9925e-01, -1.2048e+00,
          6.2971e-01, -4.9064e-01, -4.1340e-01,  5.0209e-01, -1.1406e+00,
         -4.5984e-01,  6.1358e-01, -3.3617e-01,  7.8994e-01, -1.0948e+00,
          1.5418e+00, -5.1700e-01, -8.5594e-01, -1.0500e+00,  5.9088e-01,
          6.6151e+00, -1.0291e+00,  7.0874e-01, -1.3279e+00,  2.9844e-01,
         -2.0878e+00,  1.9078e-02,  8.2597e-01, -1.0857e+00,  5.7154e-01,
         -1.6912e+00, -1.5268e-01,  3.2646e-03,  1.1017e+00,  1.8643e-01,
         -5.0111e-02,  2.0220e-01, -1.0068e+00,  7.6542e-01, -6.8305e-01,
         -3.7132e-01, -1.6766e+00,  2.8852e-01,  4.5409e-01,  8.5059e-01,
          5.8104e-02, -5.2304e-01, -5.5152e-01, -2.4743e-01, -6.9191e-01,
         -6.5395e-01, -6.6235e-01, -9.9756e-01,  2.1992e-02,  1.0059e+00,
         -4.2863e-01,  1.1271e+00, -1.6288e-01,  7.6432e-01,  1.6953e-01,
         -1.3541e+00, -3.8888e-01, -2.1897e+00,  5.4665e-03, -1.1127e+00,
         -5.3548e-01,  9.3443e-01,  1.0568e+00, -9.8869e-01, -6.8864e-01,
          9.0348e-01, -1.3046e+00, -7.2760e-01,  1.1218e-01, -4.9551e-01,
         -5.8098e-01, -1.0873e-01,  6.7804e-01,  1.1425e+00, -1.2950e+00,
         -1.4347e-01, -1.6744e+00, -7.9355e-01, -2.9727e+00,  2.9547e+00,
         -1.1534e+00, -1.2233e+00, -1.4035e+00,  1.4516e+00, -4.1441e-01,
          1.8016e+00,  1.6865e-01,  1.6194e+00, -3.7809e-01, -1.5690e+00,
         -1.1830e+00, -2.8691e-01, -1.9318e+00,  1.0479e+00,  7.3603e-01,
          3.2965e-01,  1.2416e+00, -6.9886e-01, -2.2756e-01, -8.4166e-01,
         -1.4482e-01,  5.3792e-01,  6.2498e-02,  1.2761e+00, -8.9911e-01,
         -8.5319e-01,  3.2931e-01, -1.5201e+00, -8.4763e-01,  1.4125e+00,
          2.7163e-01,  7.1401e-01, -1.8386e-02, -5.1051e-01,  4.0887e-01,
          2.3136e-03, -1.9788e+00, -8.9940e-01, -1.1714e-02, -4.2033e-01,
         -1.2946e+00, -1.0016e-01,  7.8642e-01,  1.8272e+00,  5.3141e-01,
         -9.2647e-01, -2.7914e-01,  3.4341e-01,  4.7015e-02,  1.4710e-01,
          1.1645e+00, -1.1680e+00,  1.2952e+00,  2.3134e-01,  3.6665e-01,
          1.0199e+00, -7.9753e-01, -4.5629e-01,  5.3043e-01, -4.6265e-01,
          1.4913e-01, -7.8084e-01,  2.0387e-01, -1.3205e+00,  4.1117e-01,
         -9.5927e-01, -8.2948e-02, -4.5804e-01, -6.7618e-01,  1.0689e+00,
          1.0036e+00,  4.3845e-01, -3.6505e-02,  5.1214e-01, -2.2893e-01,
         -1.9595e+00,  1.5926e+00,  4.2975e-01, -9.6439e-02, -1.3377e+00,
         -4.2288e-01, -2.4405e-01,  2.7041e-01, -7.6672e-01,  9.2045e-01,
          3.9930e-01, -8.0345e-01, -1.7574e+00,  3.4504e-01, -2.7520e+00,
         -1.4927e+00, -2.8285e-01,  2.7561e-01, -1.3214e+00, -1.1066e+00,
         -7.7852e-01, -1.0090e+00,  8.4196e-02, -6.6897e-01, -1.3444e+00,
          7.6219e-01,  5.8891e-01, -9.4349e-02,  1.1243e+00,  5.0968e+00,
         -6.0938e-01,  2.5601e-01,  1.0198e+00, -6.8676e-01,  5.0365e-01,
         -5.2631e-01, -6.4417e-01, -4.5948e-01,  2.5439e-02,  7.5988e-01,
         -2.1452e-01, -1.0562e+00, -8.4247e-01, -5.6228e-01, -8.2308e-02,
         -1.1901e-01, -3.9724e-01, -1.0865e+00, -1.4123e+00,  1.7397e+00,
         -2.9295e-01,  1.5945e+00,  1.1660e-01,  9.4450e-01,  9.7163e-01,
          4.0327e-01,  3.8824e-01,  4.7527e-01, -2.0478e+00, -1.7153e+00,
          1.1172e-01, -5.2955e-01,  6.8878e-01,  4.5349e-01,  2.9825e-01,
          8.2533e-01,  7.8437e-01, -1.5015e+00, -6.3233e-01,  1.4036e+00,
          1.9146e-01, -3.2660e-01, -3.9889e-01, -7.6972e-01, -5.9573e-01,
          6.9137e-01,  1.5756e+00,  7.3886e-01,  6.8269e-01, -2.4577e-01,
         -2.6315e-01, -1.2010e+00, -1.4987e+00,  8.6165e-01,  2.1771e+00,
          6.4517e-01,  1.0626e+00, -1.2522e+00,  5.3146e-01,  5.2001e-01,
         -9.2367e-01, -1.2364e+00,  2.6629e-02, -8.1705e-01, -5.3096e-01,
          1.8082e+00, -3.9302e-03, -1.2875e+00,  1.2437e+00, -2.5373e-01,
         -1.7810e+00, -1.6756e+00, -1.9930e-01,  1.4367e+00,  2.8074e-01,
         -1.0394e+00,  2.4837e-01, -1.0728e+00,  6.7101e-01, -5.9425e-01,
         -7.9490e-01,  3.0291e-01, -1.1040e+00, -9.5833e-01, -2.9802e+00,
         -7.4362e-01, -3.0851e-02, -1.2373e+00,  4.3251e-01, -4.4356e+00,
         -2.0639e+00, -3.7690e-01,  2.4716e-01, -1.1107e+00, -7.8535e-01,
         -7.9182e-02,  9.0747e-01, -7.2225e-01, -1.8154e-01,  1.7283e+00,
          1.6882e-01,  4.0741e-01, -1.9131e-01,  1.3294e+00, -9.2930e-01,
         -1.0722e+00, -2.8494e-01,  1.1830e+00, -1.7126e+00,  6.0947e-01,
          2.9334e-01,  2.9048e-01, -1.0511e+00, -7.4809e-01,  1.1189e+00,
          3.0705e-01,  2.4187e-01,  3.0435e-01,  6.5107e+00, -8.9399e-01,
          1.5365e+00,  2.5103e-01, -9.0887e-01, -1.5284e+00, -6.2818e-01,
          4.9301e-02, -4.2096e-01, -8.1576e-01,  8.5437e-01,  4.9868e-01,
         -4.1285e-01, -1.0491e+00,  1.0585e+00, -9.5467e-01, -9.9450e-01,
          2.3073e-02, -3.0108e-01, -6.9903e-02,  9.0704e-01,  5.5401e-02,
         -5.3474e-01, -7.3332e-01,  9.0368e-01, -8.6492e-01, -1.0176e+00,
         -6.4708e-01, -5.6130e-01, -1.0935e+00, -1.7627e+00,  4.3366e-01,
         -2.6493e-01, -4.6694e-01, -1.0443e+00, -4.0278e-01, -2.0559e-03,
         -1.7940e+00,  5.3205e-01, -1.1559e+00, -2.8609e+00,  5.0704e-01,
          2.7783e-01,  2.6447e-01, -1.1514e+00,  6.9667e-01, -1.2418e+00,
         -9.9202e-01, -5.9107e-01,  2.8775e-01, -1.4259e+00,  7.1592e-01,
         -1.4235e-01,  7.4440e-01, -1.2752e+00, -1.9139e+00, -1.4881e+00,
          3.4485e-01,  7.7963e-01, -1.3253e+00, -9.1681e-02,  3.7662e-01,
          2.1060e+00, -1.9489e+00, -2.6904e-01, -3.5860e-01, -5.0947e-01,
         -5.3368e-02,  7.4614e-01, -8.4038e-01, -7.2819e-01, -7.1524e-01,
         -1.3892e+00, -3.5993e-01,  8.6196e-01, -7.8620e-01,  4.1005e-01,
         -4.3969e-01, -7.9892e-02, -8.0319e-01,  2.4821e-01, -3.7005e-01,
         -3.2183e-02, -1.1075e+00,  3.9463e-01,  7.6901e-01,  7.6469e-01,
          8.7991e-01, -1.1467e-01,  4.6518e-01,  3.5001e-01, -7.2703e-01,
          3.8190e-01,  8.7300e-01, -1.1456e+00, -3.5519e-02, -7.6693e-01,
         -9.0854e-01,  2.4917e-01,  4.9408e-01, -2.5278e-01, -2.7012e-01,
          1.9849e-01,  5.1349e-01,  2.0931e-01,  5.8051e-01, -1.4444e-01,
         -4.7235e-01, -3.5808e-01, -7.1085e-01, -1.5544e+00,  4.3237e-01,
         -3.1336e-01, -9.3003e-01, -9.7152e-01, -3.5961e-01, -6.3422e-01,
         -3.1349e-01, -5.2216e+00,  1.1437e+00, -4.4647e-01, -8.0848e-01,
         -1.1909e+00,  7.3764e-01, -3.3471e-01,  2.9759e-01,  1.5602e-01,
         -3.8097e-03, -2.6614e-01, -9.0699e-01, -3.3573e-01, -8.2002e-01,
          4.6096e-01,  1.3055e+00, -1.0948e+00,  2.0968e-02,  1.5985e-01,
          1.6812e-01, -7.4667e-01, -7.3932e-01, -1.9460e+00,  5.0919e-01,
         -8.9157e-02, -5.2443e-01, -5.6473e-01, -2.8025e-01,  3.3252e-01,
          1.5389e-01, -1.4834e+00,  9.3429e-01, -1.9820e+00, -5.5269e-01,
          1.0680e+00,  1.8675e+00,  2.3697e-01,  7.6316e-01,  4.0433e-01,
         -3.6500e-01, -1.8813e-01,  4.7360e-01,  8.3907e-01, -1.4762e+00,
         -8.1322e-01, -3.1375e-01, -1.4984e+00, -1.4712e+00, -9.9683e-01,
         -1.2343e-02, -1.7015e+00, -1.6480e+00, -4.6679e-01,  2.0482e+00,
         -1.3347e-01,  7.0482e-01, -4.9503e-01, -5.9515e-01,  1.8800e+00,
          7.3409e-01, -7.6007e-01,  2.8639e-01,  5.6394e-01, -4.5960e-02,
          1.4363e-01, -4.8770e-01, -8.7386e-01,  1.0334e+00, -6.7425e-01,
          8.0239e-01,  4.8187e-01,  9.3861e-01, -1.8599e-01, -1.5624e+00,
         -3.1563e-01, -7.8575e-02, -1.6492e+00, -8.9269e-01,  1.5859e+00,
         -6.8626e-02,  7.9312e-01,  3.4098e-03,  2.4446e-01, -2.9679e-01,
          2.1562e+00,  2.8128e-02,  5.4682e-01, -6.6953e-01,  2.4167e+00,
         -4.6049e-01, -4.3354e-01, -7.4269e-01,  5.6806e-01, -3.8373e-01,
          2.6450e-01,  1.3732e+00,  8.1186e-01,  1.2105e+00,  1.6925e-01,
         -9.4737e-02, -8.4474e-01,  4.5913e-01, -7.7279e-01, -4.7698e-01,
          5.1502e-02,  3.0764e+00, -1.0450e+00,  8.9097e-01, -1.6596e+00,
         -9.1564e-01,  3.1554e-01,  2.7136e-01, -1.3018e+00, -3.7862e-01,
          1.1926e+00, -4.5323e-01, -8.0916e-01, -2.1487e-02, -8.2258e-01,
         -7.5287e-01,  1.3985e+00,  6.9068e-01, -3.1799e-02,  6.4883e-01,
          1.7266e+00,  5.9010e-01,  7.8960e-01, -5.3539e-01, -7.8024e-01,
         -5.2768e-01, -7.2171e-02,  9.3496e-01, -5.2461e-01,  1.1310e+00,
         -1.8495e-01,  4.6232e-01, -1.3196e-01, -1.1320e+00,  3.7025e-01,
         -1.2958e-02,  5.8100e-01,  1.4498e+00, -4.9975e-01,  1.7994e+00,
          4.8361e-02, -1.5880e+00,  1.1432e-01,  7.2760e-01, -1.8913e-01,
          1.3934e-01,  6.8744e-01,  2.5113e-01,  1.2075e-01,  1.4847e+00,
          3.0606e-01,  1.8572e-01, -9.9935e-01, -5.7478e-02, -4.4528e-01,
          9.2192e-01, -6.5947e-01, -5.1781e-01,  1.1313e+00, -6.1353e-01,
         -5.2493e-01,  3.2543e-01, -1.5865e+00, -1.7018e+00,  1.0502e+00,
          9.1212e-01, -9.3331e-01, -5.7415e-02, -4.5121e-01, -4.6328e-01,
         -5.9554e-01, -8.5772e-01, -2.2799e+00,  7.2468e-02,  4.9749e-01,
          4.9262e-01, -1.4265e+00,  1.0043e-01, -4.6500e-01,  1.3149e+00,
          8.0694e-01,  1.9156e-01,  1.5808e-01]], device='cuda:0',
       grad_fn=<IndexBackward0>)
```

**Comment by ArthurZucker** [comment]
Hey, quick tip, you can also initialize a class variable `eos_token_id` for example, which can be fetch in the `config` at `__init__` time. 
Now regarding the issue, I have to ask why not use the same technique as in `CLIP`? You mention pros and cons, would you mind giving more details?

**Comment by isamu-isozaki** [comment]
@ArthurZucker Thanks for the tip! Will fix that asap.

And for the original implementation of CLIP, sorry let me clarify. I meant the original implementation of how CompVis/latent-diffusion trains on added tokens. In there, they force the placeholder token/added token to be a single token that is already within the embeddings during the textual inversion training. 
Pro: With this approach, it'll work for the current implementation of clip 
Con: It's a pretty strict requirement that the current textual inv script in diffusers doesn't have. 

But overall, I think this pr, once I fix things up, won't cause any problems to the existing implementations because we want to pool on the eos token anyway and it'll also end up working for the textual inversion scripts in diffusers which will be nice.

**Comment by isamu-isozaki** [comment]
@ArthurZucker Hi! In the config, I noticed that the eos_token_id for the clip text model can be different from the tokenizer as follows
```
CLIPTextConfig {
  "_name_or_path": "CompVis/stable-diffusion-v1-4",
  "architectures": [
    "CLIPTextModel"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "dropout": 0.0,
  "eos_token_id": 2,
  "hidden_act": "quick_gelu",
  "hidden_size": 768,
  "initializer_factor": 1.0,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 77,
  "model_type": "clip_text_model",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "projection_dim": 512,
  "torch_dtype": "float32",
  "transformers_version": "4.26.0.dev0",
  "vocab_size": 49408
}
```
is there some reason for this? I'll try testing out vocab_size-1 for now

**Comment by isamu-isozaki** [comment]
Will fix the checks.

**Comment by isamu-isozaki** [comment]
Pulled from upstream so that some tests can pass

**Comment by isamu-isozaki** [comment]
Actually, this made the code diff a bit messy so closing this now and will make a new pr.

**Comment by ArthurZucker** [comment]
Also the reason for the possible difference between the `model.config.xxx_token_id` and `tokenizer.config.xxx_token_id` is because they are not linked together. We usually make sure that they have the same value but nothing is forcing that. Biggest reason I see is dependency, and simplicity since you could use other tokenizer with the same model and vice versa. 😉

**Comment by isamu-isozaki** [comment]
Will post on new pr too just for other people who want to follow.

**Pull request closed without merging**
