### PR TITLE
[Longformer] longformer in question-answering pipeline

### PR DESCRIPTION
**Pull request by patil-suraj**
This PR adds `LongformerForQuestionAnswering` in `QuestionAnsweringPipeline`

@patrickvonplaten @ibeltagy

### CODE REVIEW

**Comment by patil-suraj** [comment]
This works well however I noticed some discrepancy in answers generated with pipeline and without  pipeline

for this example
```
question = 'Who was Jim Henson?'
text = 'Jim Henson was a nice puppet.'
```

pipeline produces `nice puppet.`
 without pipeline `a nice puppet`

@patrickvonplaten  is this expected or there's something wrong ?

**Comment by patrickvonplaten** [comment]
Thanks for the PR @patil-suraj. 

I will put this on hold for a week though since we will most likely do some major changes very soon here.

1) I think the squad preprocessing functions will probably be refactoring building on the new `nlp` library @thomwolf 

2) IMO, the function `squad_convert_examples_to_features` should in general not be used in the `QuestionAnsweringPipeline` since we only need `input_ids` and `attention_mask` for inference and some other values for the `score`. Also, we should also be able to use the pipeline for `TriviaQA` (with Longformer, we now have a pretrained model that works very well on TriviaQA). The pipeline should not be dataset specific. I think it might be a good idea to do a bigger refactoring of `QuestionAnsweringPipeline` and make it independent from the `squad_convert_examples_to_features` function. What do you think @julien-c @thomwolf @LysandreJik

**Comment by patil-suraj** [comment]
Hi @patrickvonplaten , I think we need should fix this now, as the newly launched model inference api uses qa pipeline its failing or giving weird answers for longformer qa models on model hub. This might discourage the users from using them.

**Comment by LysandreJik** [comment]
@patrickvonplaten I agree with you, especially because that method is made for heavy processing of large data, which is not the case with pipelines. It's slow to start, and uses multiprocessing by default, something we don't necessarily want with the pipelines.

**Comment by patrickvonplaten** [comment]
Also putting @mfuntowicz in cc here

**Comment by mfuntowicz** [comment]
Ok we'll have conflicts here (#5496), we need to handle with care.

**Comment by tholor** [comment]
I believe this issue with roberta models for QA never got fixed. Any plans to continue working here? 

> While this works for other BERT models, for roberta and and longformer tokenizer, the final
encoding results in this 
< s> Who was Jim Henson?</s></s>JimHensonwasanicepuppet</s>

As mentioned by @patil-suraj, we don't respect whitespace before words in the passage. Therefore, we currently use the input id for "ĠHenson" in the question, but the one for "Henson" in the passage.

The current implementation also leads to quite poor results of our QA models. For example, F1 of `deepset/roberta-base-squad2` on SQuAD 2 dev is down to 0.69 whereas it gets 0.81 with "whitespace preserving" tokenization.

A simple fix could be to add `add_prefix_space=True` here in the tokenizer call for Roberta tokenizers (or similar), but might not be the most elegant solution. 
https://github.com/huggingface/transformers/blob/28cf873036d078b47fb9dd38ac3421a7c874da44/src/transformers/data/processors/squad.py#L112

I can to do a PR for this, if that's how you want to fix it.

**Comment by patrickvonplaten** [comment]
A PR would be very welcome :-)

**Comment by tholor** [comment]
@patrickvonplaten Added a PR https://github.com/huggingface/transformers/pull/7387

**Pull request closed without merging**
