### PR TITLE
Make transformers-cli cross-platform

### PR DESCRIPTION
**Pull request by BramVanroy**
Using `scripts` is a useful option in `setup.py` particularly when you want to get access to non-python scripts. However, in this case we want to have an entry point into some of our own Python scripts. To do this in a concise, cross-platfom way, we can use `entry_points.console_scripts`. This change is necessary to provide the CLI on different platforms (particularly also including Windows), which "scripts" does not ensure.

Usage remains the same, but the "transformers-cli" script has to be moved (be part of the library) and renamed (underscore + extension). So even though the script itself has been renamed to `transformers_cli.py` and moved to `src/commands`, its usage is still the same: `transformers-cli <args>`.

Tested on Ubuntu and Windows.

### CODE REVIEW

**Comment by BramVanroy** [comment]
I am receiving email updates about "Run failed: Torch hub integration". Is this some automatic testing that is happening and failing?

**Comment by julien-c** [comment]
Thoughts @aaugustin?

**Comment by aaugustin** [comment]
Yes, this is the best way to provide a cross-platform command in a Python library.

See https://github.com/django/django/pull/2116 for another project making a similar change.

**Comment by julien-c** [comment]
Alright, good for you @LysandreJik @thomwolf?

**Review by thomwolf — APPROVED** [review]
Yes, I like this better as well

**Review by LysandreJik — APPROVED** [review]
Great, thanks @BramVanroy

**Pull request merged**
