### PR TITLE
add targets arg to fill-mask pipeline

### PR DESCRIPTION
**Pull request by joeddav**
Proposal to add a `targets` arg when calling `FillMaskPipeline`, allowing a user to compare different target tokens in addition to getting the top k predictions. This could be useful in a number of areas, such as in probing model behavior:

```python
nlp = pipeline('fill-mask', topk=2)
nlp("<mask> should be at home and take care of their children.")
> [{'sequence': '<s>Parents should be at home and take care of their children.</s>',
    'score': 0.32749035954475403,
    'token': 35835,
    'token_str': 'Parents'},
   {'sequence': '<s> parents should be at home and take care of their children.</s>',
    'score': 0.12840420007705688,
    'token': 1041,
    'token_str': 'Ġparents'}]

nlp("<mask> should be at home and take care of their children.", targets=["Men", "Women"])
> [{'sequence': '<s>Women should be at home and take care of their children.</s>',
    'score': 0.04439367726445198,
    'token': 19814,
    'token_str': 'Women'},
   {'sequence': '<s>Men should be at home and take care of their children.</s>',
    'score': 0.01326736994087696,
    'token': 17762,
    'token_str': 'Men'}]
```

This could also prove useful in the setting of using MLMs for cloze tasks and few/zero-shot prediction:

```python
nlp("The acting was believable and the action was outstanding. The sentiment of this review is <mask>.")
> [{'sequence': '<s>The acting was believable and the action was outstanding. The sentiment of this review is clear.</s>',
    'score': 0.10008594393730164,
    'token': 699,
    'token_str': 'Ġclear'},
   {'sequence': '<s>The acting was believable and the action was outstanding. The sentiment of this review is undeniable.</s>',
    'score': 0.05471134930849075,
    'token': 29941,
    'token_str': 'Ġundeniable'}]

nlp("The acting was believable and the action was outstanding. The sentiment of this review is <mask>.",
    targets=[' positive', ' negative'])
> [{'sequence': '<s>The acting was believable and the action was outstanding. The sentiment of this review is positive.</s>',
    'score': 0.04867269843816757,
    'token': 1313,
    'token_str': 'Ġpositive'},
   {'sequence': '<s>The acting was believable and the action was outstanding. The sentiment of this review is negative.</s>',
    'score': 0.0009897189447656274,
    'token': 2430,
    'token_str': 'Ġnegative'}]
```

Notes:
- Passed targets must be in model vocab. If they're not, the target word is tokenized and the first token is used (with a user warning)
- Could possibly also be done with text-generation, but that might go against the spirit of that pipeline
- Current implem. can't do multi-input with different targets for each instance. Adding this would be a little less clean because you'd have to handle different output shapes for each instance, but I can add it in if that is important.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
I think that's a very cool feature! Maybe also print a warning if one of the tokens gets tokenized to an unknown token?

I think single input is okay for now. We should look at handling multi-input in the `fill-mask` pipeline as a whole, so if you want to take a stab at that, please feel free to do so :).

**Comment by joeddav** [comment]
> We should look at handling multi-input in the fill-mask pipeline as a whole

The fill-mask pipeline does, at least if we mean the same thing by "multi-input". It can take an arbitrarily long list of strings and return the top-k predictions for each.

**Review by sshleifer — APPROVED** [review]
Nice tests. Not sure whether this should be in a separate `ScoreTargetsPipeline` that inherits from `FillMaskPipeline` or some such. I don't have a strong opinion.

**Comment by joeddav** [comment]
Awesome. @LysandreJik am I set to merge?

**Review by LysandreJik — APPROVED** [review]
Great, LGTM

**Pull request merged**
