### PR TITLE
rename prepare_translation_batch -> prepare_seq2seq_batch

### PR DESCRIPTION
**Pull request by sshleifer**
cc @patil-suraj 

Starts work on #6080 , which suggests that all seq2seq tokenizers expose a `prepare_seq2seq_batch` method.

TODO:
- add common test enforcing API consistency.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM, though @patrickvonplaten seems to have an opinion on this, so let's wait before merging.

**Comment by patrickvonplaten** [comment]
Didn't know that `prepare_translation_batch` was already in master. Guess I'm not a huge fan of such a helper function in general and for me, it's a pure convenience function that does not really add functionality to the lib.  Think we should lower maintenance costs and reduce the risk of future breaking backward compatibility by not adding such functions to the python tokenizers. But I don't have the best insight into the tokenizers. Maybe @LysandreJik and @thomwolf can have a better opinion here.

**Comment by sshleifer** [comment]
The better argument is not about convenience, but about managing special tokens when they are different on the encoder and decoder side.

**Comment by sshleifer** [comment]
same spurious pabee failure as #6421 , merging!

**Pull request merged**
