### PR TITLE
gpt2 typo

### PR DESCRIPTION
**Pull request by flozi00**
From #4572

### CODE REVIEW

**Comment by julien-c** [comment]
I think it's a bogus search and replace by @LysandreJik in #2532 but it applies for all models not just GPT2.

**Comment by julien-c** [comment]
can you fix in all files?

**Comment by flozi00** [comment]
Ups, I didn't saw this.
I will do this in a few minutes

**Comment by julien-c** [comment]
LGTM, thanks!

**Review by LysandreJik — APPROVED** [review]
Great, thanks for catching my mistake!!

**Pull request merged**
