### PR TITLE
[Trainer] Fix optimizer step on PyTorch TPU

### PR DESCRIPTION
**Pull request by cowanmeg**
# What does this PR do?
Update optimizer step for TPUs to user `self.optimizer.step()` instead of `xm.optimizer_step(self.optimizer)`. 
AcceleratedOptimizer properly calls `xm.optimizer_step` on the optimizer (https://github.com/huggingface/accelerate/blob/main/src/accelerate/optimizer.py#L129). 

This fixes a bug in transformers/trainer.py when using Pytorch on TPUs:
File "/usr/local/lib/python3.8/dist-packages/torch_xla/core/xla_model.py", line 471, in _fetch_gradients for param_group in optimizer.getstate()['param_groups']: KeyError: 'param_groups'

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger

### CODE REVIEW

**Comment by sgugger** [comment]
cc @muellerzr and @pacman100

**Review by muellerzr — APPROVED** [review]
Thanks! That is indeed the right solution

**Review by sgugger — APPROVED** [review]
Thanks for checking Zach. Note to your future self: I think there is a lot of dupe code now ;-)

Thanks for your contribution @cowanmeg !

**Comment by pacman100** [comment]
Thank you @cowanmeg for the fix!

**Pull request merged**
