### PR TITLE
Add multilingual documentation support

### PR DESCRIPTION
**Pull request by JetRunner**
This PR adds multilingual documentation support for incoming Chinese documentations.

### CODE REVIEW

**Comment by sgugger** [comment]
You will need to run `make style` on your branch to fix the quality check. I'm looking at the result [here](https://247866-155220641-gh.circle-artifacts.com/0/docs/_build/html/index.html) but don't see anything changed. Is it normal?

**Comment by JetRunner** [comment]
@sgugger Yes, it's normal. This is just a PR to support multilingual docs but they aren't there yet.

**Comment by sgugger** [comment]
Mmm, looks like you may have some wrong version on your side? A `pip install -e .[quality]` should fix this (but you will probably need to revert the changes in the pipeline tests as black doesn't undo the new lines it adds).

**Review by sgugger — APPROVED** [review]
Great!

**Pull request merged**
