### PR TITLE
🌐 [i18n-KO] Fixed `tasks/masked_language_modeling.mdx`

### PR DESCRIPTION
**Pull request by HanNayeoniee**
# What does this PR do?

Fixes #22838

image

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
Team PseudoLab, may you please review this PR?
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

May you please review this PR?
@sgugger, @ArthurZucker, @eunseojo

### CODE REVIEW

**Comment by wonhyeongseo** [comment]
LGTM. If you may, please:

1. provide relevant screenshots of your fixes and
2. amend your commit message to be more descriptive.

**Comment by HanNayeoniee** [comment]
> LGTM. If you may, please:
> 
> * **amend your commit message to be more descriptive than just `fixed`.**
>   (e.g. `fix: docs: missing newline before code block`)
> * (Optional) provide relevant screenshots of your fixes

Thanks for your review!
I amended the last commit message and added a screenshot in my first comment!

**Review by wonhyeongseo — APPROVED** [review]
Spot-on 🙌

**Review by ArthurZucker — APPROVED** [review]
Thanks for fixing! 🤗

**Pull request merged**
