### PR TITLE
Render chat template tojson filter as unicode

### PR DESCRIPTION
**Pull request by CISC**
# What does this PR do?

<details>
<summary>Rant about lack of special capabilties templates...</summary>

I wish more models that have extra capabilities like f.ex. function calling would start using the power available in chat templates instead of implementing their own inference mini-stacks (`Mistral`, `Berkeley`, et al.; I'm looking at you) that you would have to add as model-specific dependencies to use those features "as intended".

Shout out to `Cohere` for actually making an effort here, however it's a shame they did not follow it to completion to also include the final `tool` role to enable the full round-trip with natural language response to the function call (see my Mistral `GGUF` for a fully functional example of this).
</details>

I've been using the jinja2 `tojson` filter in a couple of chat templates to render function calling instructions, which is working very well, however sometimes this will introduce escaped unicode characters, which is undesirable.

I'm mainly using `GGUF`s, so have not used `tojson` with `transformers` yet, but I imagine this could be a useful feature for many recent models if only they started using chat templates properly (see rant).

This PR simply changes the default parameters of `tojson` so that the JSON is rendered in unicode.

Examples of (`GGUF`) models using `tojson`:
* [openfunctions-v2](https://huggingface.co/CISCai/gorilla-openfunctions-v2-SOTA-GGUF)
* [Mistral-7B-Instruct-v0.3](https://huggingface.co/CISCai/Mistral-7B-Instruct-v0.3-SOTA-GGUF)

Submitted similar PR to abetlen/llama-cpp-python#1486

## Who can review?

@ArthurZucker

### CODE REVIEW

**Comment by CISC** [comment]
The failing tests seem to be an unrelated issue in `master` branch, and not this PR.

**Review by Rocketknight1 — APPROVED** [review]
LGTM!

**Comment by CISC** [comment]
@Rocketknight1 Oh, hey, that might impact some of my ongoing work in `llama-cpp-python`, thanks for the heads up!

**Review by ArthurZucker — COMMENTED** [review]
Thanks and LGTM

**Pull request merged**
