### PR TITLE
Fixes for issue #33763 in idefics2 model

### LINKED ISSUE #33763: Idefics 2 fixed bug shown up again
### System Info

- `transformers` version: 4.45.1
- Platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.31
- Python version: 3.10.14
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.31.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.2.2+cu121 (True)
- Tensorflow version (GPU?): not installed
- Flax version (CPU?/GPU?/TPU?): not installed 
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: No
- Using GPU in script?: No
- GPU type: NVIDIA A100 80GB PCIe

### Who can help?

@amyeroberts @qubvel

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just run the official code from https://huggingface.co/HuggingFaceM4/idefics2-8b for idefics2-8b can reproduce the bug.

### Expected behavior

File ~/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/idefics2/modeling_idefics2.py:1296, in Idefics2Model.inputs_merger(self, input_ids, inputs_embeds, image_hidden_states)
   1294 new_inputs_embeds = inputs_embeds.clone()
   1295 reshaped_image_hidden_states = image_hidden_states.view(-1, vision_hidden_size)
-> 1296 new_inputs_embeds[special_image_token_mask] = reshaped_image_hidden_states
   1297 return new_inputs_embeds

RuntimeError: shape mismatch: value tensor of shape [640, 4096] cannot be broadcast to indexing result of shape [0, 4096]

The bug was first reported in https://github.com/huggingface/transformers/issues/31380. I can confirm it is fixed in `transformers` version: 4.45.0-dev. However, as I upgraded to 4.45.1, it shows up again.

### PR DESCRIPTION
**Pull request by aroun-coumar**
# What does this PR do?

Fixes #33763 #33752

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@zucchini-nlp

### CODE REVIEW

**Review by vignesh1507 — APPROVED** [review]
Works perfectly.

**Comment by aroun-coumar** [comment]
[#33776](https://github.com/huggingface/transformers/pull/33776)

I noticed another PR is raised on the very same issue later

For reference to avoid conflicts if any

**Comment by zucchini-nlp** [comment]
@aroun-coumar oh right, looks good to me whichever of the PRs is merged 🤗

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing! 

As the changes here are exactly the same as those in #33776 - there's no need to run the slow tests here as well.

**Review by Mellobrainbox — APPROVED** [review]

**Pull request merged**
