### PR TITLE
Swin2sr

### LINKED ISSUE #19568: Add Swin2SR
### Model description

Swin2SR is a Swinv2-based model for image super resolution and compression.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://github.com/mv-lab/swin2sr

### PR DESCRIPTION
**Pull request by venkat-natchi**
# What does this PR do?

Fixes #19568

## Who can review?
@NielsRogge

### CODE REVIEW

**Comment by NielsRogge** [comment]
Hi @venkat-natchi,

I actually played around with the Swin2SR model this weekend and got a [working implementation](https://github.com/NielsRogge/transformers/tree/add_swin2sr/src/transformers/models/swin2sr) already.

I see you're still at the start of the process, so would you be interested in working on another model [from this list](https://github.com/huggingface/transformers/issues?q=is%3Aissue+is%3Aopen+label%3A%22New+model%22)?

**Comment by venkat-natchi** [comment]
Sure, make sense. I was actually going through the papers in the weekend to get the high level understanding of it. 

I thought of picking [this](https://github.com/huggingface/transformers/issues/19631) one up now, but seems to be closed. Do you know why?

If possible could you point me to any one model, which was not taken up so far. Thanks.

**Comment by NielsRogge** [comment]
Do you have an email address? I'll set up a Slack channel so we can discuss :)

**Comment by IMvision12** [comment]
Hey, @venkat-natchi would you like to work on Adding EDSR to HuggingFace together? I closed that issuse as I thought it was not relevant.

**Comment by IMvision12** [comment]
@NielsRogge I am also adding a similar model as swim2sr, which is EDSR here [add_edsr](https://github.com/IMvision12/transformers/tree/add_EDSR/src/transformers/models/edsr)

**Comment by NielsRogge** [comment]
I'll close this PR as you'll work on a new model.

**Pull request closed without merging**
