### PR TITLE
Fix telemetry URL

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

I forgot the `api/` in the URL for the telemetry call. :grimacing:

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Perfect :)

**Comment by julien-c** [comment]
lolz

Did you still get a `200 OK` response?

**Comment by sgugger** [comment]
I don't look at the response since the function never errors out (it's not supposed to screw up the script ;-) )

**Comment by julien-c** [comment]
got it!

**Pull request merged**
