### PR TITLE
[Speech] Refactor Examples

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

This PR adapts all Wav2Vec2-like models to use the same examples and makes sure that `...ForCTC` and `...ForSequenceClassification` have exactly the same structure. HuBERT, SEW, SEW-D and soon UniSpeech and others that are based on Wav2Vec2 usually don't have any specific heads, but rather should just follow the Wav2Vec2 head design of CTC and the Superb head design for SequenceClassification (SpeakerVerification, ....). Therefore we should make it as easy as possible to add such heads to new Wav2Vec2 versions. 

This PR makes sure that a simple `#Copied from ...` command can be used for such heads which should allow us to work faster when adding new speech models while making sure the design is unified and correct.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Wait until https://github.com/huggingface/transformers/pull/14026#issuecomment-945201433 is fixed

**Review by LysandreJik — APPROVED** [review]
This is great! 100% agree that all models should have the SUPERB heads

**Review by sgugger — APPROVED** [review]
This is great! Thanks a lot for refactoring this.

**Review by anton-l — APPROVED** [review]
Looks very clean now :+1:

**Pull request merged**
