### PR TITLE
GPT2DoubleHeadsModel made parallelizable

### PR DESCRIPTION
**Pull request by ishalyminov**
# What does this PR do?

GPT2DoubleHeadsModel made parallelizable; it is also reflected in the test_modeling_gpt2.py suite

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Comment by ishalyminov** [comment]
@patrickvonplaten , @LysandreJik

**Comment by patrickvonplaten** [comment]
Also pinging @stas00 here - does it make sense to add parallelize ability to GPT2DoubleHeadsModel?

**Comment by stas00** [comment]
If it's being used then yes since `GPT2LMHeadModel` has it.

**Comment by LysandreJik** [comment]
@alexorona, do you want to take a look at this?

**Comment by ishalyminov** [comment]
@stas00 yeah, so I've been using the `GPT2DoubleHeadsModel` for my tasks since reading [this medium](https://medium.com/huggingface/how-to-build-a-state-of-the-art-conversational-ai-with-transfer-learning-2d818ac26313) (I guess a lot of people in the dialogue community also followed that tutorial).
And seeing `parallelize()` implemented with the `GPT2LMHeadModel` got me curious to have the double-headed one working like that as well :)

**Comment by stas00** [comment]
@LysandreJik, we parked any further activity on extending naive MP to other `transformers` models and its sub-classes because while it solved the immediate need it's not a good long term solution due to very inefficient gpu utilization.

We are working on integrating ZeRO-3 from DeepSpeed and fairscale which will automatically solve this scalability issue and will make the naive MP approach redundant and we can then decide whether it makes sense to keep it.

Until we sort it out and we can reliable know that ZeRO solves this problem and it's accessible to all users you can definitely merge this since @ishalyminov clearly has a good use for it.

**Review by stas00 — APPROVED** [review]
If it works for others, this is a good extension of the existing t5 naive MP to     `GPT2DoubleHeadsModel`

Thank you, @ishalyminov

**Review by LysandreJik — APPROVED** [review]
Thanks for your contribution @ishalyminov

**Comment by alexorona** [comment]
@ishalyminov Great work here! You're bringing up an important point. I've had this some question myself. @thomwolf It might be useful to add a few sentences to [this Medium article](https://medium.com/huggingface/how-to-build-a-state-of-the-art-conversational-ai-with-transfer-learning-2d818ac26313) clarifying whether distractors are likely to improve final performance in tasks that are ultimately concerned with generative text. It's not entirely clear if your approach using distractors and a double-headed model is an artifact of the competition setup or whether it's an approach you would recommend for anyone trying to fine-tune a transformer for chatbot-style tasks. If someone only cares about language modeling, do you think a double-headed approach with distractors and a classification task would usually produce a better chatbot than simply focusing on LM? Does it matter if the chatbot is attempting to model several discrete personalities present in the dataset?

**Comment by ishalyminov** [comment]
@alexorona thanks! Yeah it would be very interesting to hear more about @thomwolf's ConvAI experience:) As for me, I didn't conduct any evaluation of how the NSP task affects the resulting LM (and indeed, there are some works out there that don't use this secondary task at all).

But for what it's worth, we found the NSP head to be beneficial for hybrid [generative/retrieval](https://github.com/microsoft/GRTr) GPT-2 based dialogue architectures.
Also I guess the multi-task setup makes the model intuitively more versatile for a range of downstream tasks, as was originally proposed in the [BERT paper](https://arxiv.org/pdf/1810.04805.pdf) - would be really useful if there was an experimental evaluation proving or disproving this for the case of ConvAI GPT-2.

**Pull request merged**
