### PR TITLE
LLaVA-NeXT-Video: fix generation with cache

### PR DESCRIPTION
**Pull request by zucchini-nlp**
# What does this PR do?

Fixes generation for llava-next-video. Apparently started failing after we moved to cache class but some parts of the code were not modified. Checked all llava models, others are working since check is done on a different condition.

Yes, we can start using `cache_position` and rely on that, but we should note that `cache_position` for VLMs will not be correct and will contain positions only for text tokens. Adding support for cache position will come in the next PR, which is in progress. We;ll have to deprecate many things before we can get rid of the current checks to "merge or expand"

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Thanks! Do you mind adding a fast test that would catch this? 🤗

**Comment by zucchini-nlp** [comment]
Actually we should have VLM generation tests soon (not very soon), but for now maybe I'll try and make a very dummy test for all VLMs. It is annoying that fast tests for VLMs don't catch most basic bugs

**Review by ArthurZucker — APPROVED** [review]
LGTM, any reason why the check is different from #32836

**Comment by zucchini-nlp** [comment]
Nah, both are equally valid since current VLMs doesn't support speculative decoding. Let's use the PR from yesterday which has this and another fix, I'll close this one. The current state of main already has it fixed due to the recent refactor

**Pull request closed without merging**
