### PR TITLE
Marian docstring

### PR DESCRIPTION
**Pull request by traveler-pinkie**
# What does this PR do?
related to #16292

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
 @ydshieh, @patrickvonplaten 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by traveler-pinkie** [comment]
I need some help. This is my first time contributing to a project ever. I'm getting familiar with the process of git, and I've tried to follow the instructions layed out on the [Community Event] Doc Tests Sprint #16292. I ran the doc test locally and received to errors. But upon further inspection, I can seem to find what the issue is. Please if you can offer come guidance on what I'm doing wrong and how to progress. I'm working on modeling_tf_marian.py

**Comment by traveler-pinkie** [comment]
Screenshot 2022-10-13 223655

**Comment by ydshieh** [comment]
@traveler-pinkie sorry for being late here. Are you still interested in working on Marian config files?

**Comment by traveler-pinkie** [comment]
@ydshieh . Thanks for commenting back. But I think at the moment I should probably study a little bit more. It looks like I was having more difficulty then I should have. With my skills currently. I think it's best if someone else works on it. Sorry and thank you

**Pull request closed without merging**
