### PR TITLE
Fix tensor-parallelism link

### PR DESCRIPTION
**Pull request by steilgedacht**
# What does this PR do?

Replaces the old link in the llama configuration file to the new section on the website.
Clean PR of #27840

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

@stevhliu

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
LGTM

**Comment by ArthurZucker** [comment]
Can you run `make style`?

**Comment by steilgedacht** [comment]
running `make style` makes no changes, do you have any ideas on what to change?

**Comment by ArthurZucker** [comment]
Make sure you have `ruff==0.1.5`

**Comment by steilgedacht** [comment]
Okay, I have already `ruff=0.1.5` and rebased it, am I doing anything wrong here? 😅

image

**Comment by ArthurZucker** [comment]
Ah no I have a similar issue. just `make fixup` should help I think otherwise just reverting the changes

**Pull request closed without merging**
