### PR TITLE
Fix torch meshgrid warnings

### PR DESCRIPTION
**Pull request by fxmarty**
# What does this PR do?

This PR fixes unwanted warnings due in `torch.meshgrid`:

```
/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/functional.py:478:
UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing
argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  >>> ys = torch.linspace(-5, 5, steps=100)
```

Passing `indexing="ij"` is necessary to keep the current behavior, see https://pytorch.org/docs/stable/generated/torch.meshgrid.html and https://github.com/pytorch/pytorch/issues/50276

```python
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

grid_x, grid_y = torch.meshgrid(x, y, indexing="ij")  # vs indexing="xy"

print(grid_x)
print(grid_y)
```

## Before submitting
- [x] This PR fixes a typo

## Who can review?

any core maintainer to approve

### CODE REVIEW

**Comment by sgugger** [comment]
From a quick search in the PyTorch doc, this argument is only accepted starting in PyTorch 1.10, so this PR will break the corresponding models for older versions. You should add a `meshgrid` function the pytorch utils that passes the argument or not depending on the PyTorch version, then use this util in the modeling code.

**Comment by fxmarty** [comment]
@sgugger Thank you, hopefully fixed!

**Review by sgugger — APPROVED** [review]
Perfect, thanks! (Barring the CI :sweat_smile: )

**Comment by fxmarty** [comment]
@sgugger the CI is good at last!

**Review by sgugger — APPROVED** [review]
Thanks again!

**Comment by sgugger** [comment]
Arf my comment from yesterday never went through :sweat_smile:

**Pull request merged**
