### PR TITLE
check torch_dtype in config as well

### LINKED ISSUE #13195: 'torch_dtype' keyword not working with 'AutoModel'
## Environment info

transformers version: 4.9.2
Platform: Linux-4.18.0-25-generic-x86_64-with-glibc2.10
Python version: 3.8.5
PyTorch version (GPU?): 1.8.0a0+52ea372 (True)
Tensorflow version (GPU?): not installed (NA)
Flax version (CPU?/GPU?/TPU?): not installed (NA)
Jax version: not installed
JaxLib version: not installed
Using GPU in script?:
Using distributed or parallel set-up in script?: No

### Who can help
@stas00 as he is the writer of the [#12316](https://github.com/huggingface/transformers/pull/12316).

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ ] my own task or dataset: (give details below)

## To reproduce

1. Inspect the model weight data type.
```bash
wget --content-disposition  https://api.ngc.nvidia.com/v2/models/nvidia/megatron_lm_345m/versions/v0.0/zip -O checkpoint.zip
unzip checkpoint.zip
python -c "import torch; from pprint import pprint as print; sd=torch.load('./release/mp_rank_00/model_optim_rng.pt'); d= {d.dtype: 1 for d in sd['model']['language_model']['transformer'].values()}; print(d.keys())"
# dict_keys([torch.float16])
```

2. Try to load it with transformers in float16, which `torch_dtype` is supposed to be responsible for. But this only works with specific model classes and AutoModel blindly loads it into float32.
```bash
git clone https://github.com/huggingface/transformers.git
python3 transformers/src/transformers/models/megatron_bert/convert_megatron_gpt2_checkpoint.py checkpoint.zip

# load correctly with the specific model class
python -c "from transformers import GPT2LMHeadModel; print(GPT2LMHeadModel.from_pretrained('.', torch_dtype='auto').dtype)"
# torch.float16

# but fails to load it into float 16 with AutoModelForCausalLM
python -c "from transformers import AutoModelForCausalLM; print(AutoModelForCausalLM.from_pretrained('.', torch_dtype='auto').dtype)"
# torch.float32
```

3. This is because AutoModel [first puts `torch_dtype` argument passed to `AutoModel.from_pretrained` method into config](https://github.com/huggingface/transformers/blob/91ff480e2693f36b11aaebc4e9cc79e4e3c049da/src/transformers/configuration_utils.py#L576) and 
`PretrainedModel.from_config`, which is called by `AutoModel.from_pretrained`, checks for `torch_dtype` argument in [only in `kwargs` and not in config](https://github.com/huggingface/transformers/blob/91ff480e2693f36b11aaebc4e9cc79e4e3c049da/src/transformers/modeling_utils.py#L1297). 

## Expected behavior
Setting`torch_dtype` to `auto` works correctly as explained in [#12316](https://github.com/huggingface/transformers/pull/12316).

I will open a PR to address this issue :)

### PR DESCRIPTION
**Pull request by hwijeen**
# What does this PR do?

Fixes #13195. A detailed problem description and reproducer is in the issue!

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@stas00 as we discussed this issue in #13076 .
(As #13076 deals with a number of issues, I opened #13195 to focus on `torch_dtype` with AutoModel issue.)

### CODE REVIEW

**Comment by stas00** [comment]
to fix code quality issues please run: `make fixup` and push

**Comment by stas00** [comment]
As answered in the issue: https://github.com/huggingface/transformers/issues/13195#issuecomment-903009666
not using `config.torch_type` is by design for v4 and will likely to change in v5.

**Comment by stas00** [comment]
The original problem will be fixed by https://github.com/huggingface/transformers/pull/13209 - please don't hesitate to validate that it indeed solves it. Thank you!

**Comment by hwijeen** [comment]
> As answered in the issue: [#13195 (comment)](https://github.com/huggingface/transformers/issues/13195#issuecomment-903009666)
> not using `config.torch_type` is by design for v4 and will likely to change in v5.

I see. So should this PR be closed or left open for later reference? Thank you!

**Comment by stas00** [comment]
We can close it for now. It will still be here for reference in either form.

**Pull request closed without merging**
