### PR TITLE
Rename second input dimension for ONNX-supported CV models

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

The second input dimension of `pixel_values` for CV models with ONNX support is currently named "sequence". This PR renames it to "num_channels".

Also:
- MobileViT is added to the list of models to test in `tests/onnx/test_onnx_v2.py`
- for DETR, the second input dimension is removed for `pixel_masks` because there is actually no channel dimension (`batch` x `height` x `width`)
- for MobileViT, a second input dimension is added to `pixel_values` so that it follows the same pattern as other vision models

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by regisss** [comment]
I re-ran all slow tests and they all passed.

**Review by NielsRogge — APPROVED** [review]
Thanks for fixing!

**Review by sgugger — COMMENTED** [review]
I am not familiar enough with ONNX to evaluate if this breaks exiting code in any way, so could you please tell us whether a user will have to change anything in their code due to this change?

**Comment by NielsRogge** [comment]
Gently pinging @lewtun here

**Comment by LysandreJik** [comment]
Pinging @michaelbenayoun and @JingyaHuang as Lewis is off for a few weeks.

**Review by JingyaHuang — APPROVED** [review]
LGTM, and just to confirm that changing the axis name should not be a breaking change, I think that it is quite rare that users need to leverage the name of dynamic axes. 

P.S. I am not familiar with these vision models, out of curiosity, why do we set the number of channels as dynamic? Shouldn't it be something quite static as height and width?

**Comment by michaelbenayoun** [comment]
Yes, I do not think it is a breaking change either. Same question as @JingyaHuang : do we need dynamic axes for the channels?

**Comment by regisss** [comment]
@JingyaHuang @michaelbenayoun I guess some models can deal both with grayscale and RGB images. I let @NielsRogge confirm here.

**Comment by NielsRogge** [comment]
Yes technically the channel dimension can be 1 for greyscale images, 3 for RGB images, and 4 for RGBA images.

**Review by lewtun — APPROVED** [review]
Thanks a lot for fixing this poor name choice (which was entirely my fault with ViT setting the template for all other exports 🙈 )

The change LGTM and I agree it's not breaking for end users. ~Merging since it's been approved by a core maintainer as well~

Edit: I merged this too fast and missed that it hadn't actually been approved by a core maintainer 😬. Happy to revert if needed

**Review by LysandreJik — COMMENTED** [review]
LGTM :)

**Pull request merged**
