### PR TITLE
upgrade sentencepiece version

### LINKED ISSUE #13563: sentencepiece version need upgrade
## Environment info

- `transformers` version: 4.11.0.dev0
- Platform: Debian Gnu/Linux
- Python version: 3.9
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help

- setup: @LysandreJik may be ?

## Information

sentencepiece==0.1.91 does not exist anymore

pip install fails:

```
ERROR: Could not find a version that satisfies the requirement sentencepiece==0.1.91
ERROR: No matching distribution found for sentencepiece==0.1.91
```

## To reproduce

1. create a new venv
2. pip install -e .

## Expected behavior

- Need to bump to the latest but minor version change 0.1.96 for transformer's install to work

### PR DESCRIPTION
**Pull request by elishowk**
# What does this PR do?

Fixes #13563

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sgugger** [comment]
Just double-checked, it's a Python 3.9 problem for the previous version. No problem with upgrading as long as all tests pass, but we won't know that until I fix a bug in the tests_fetcher utils, so stay tuned :-)

**Comment by sgugger** [comment]
In the meantime, you can run `make style` on your branch to remove the error in code quality.

**Comment by sgugger** [comment]
Can you rebase to integrate #13566 in your branch? It should then run all tests so we can double-check this doesn't break anything/

**Comment by elishowk** [comment]
> Can you rebase to integrate #13566 in your branch? It should then run all tests so we can double-check this doesn't break anything.

Done 👍🏾

**Comment by sgugger** [comment]
Discussing a bit more with Lysandre, I think we actually want >=0.0.91 and != 0.0.92 (which was the problematic version that made us pin sentencepiece). Do you mind adapting the PR? Thanks!

**Comment by sgugger** [comment]
You'll need to run `make style` again to update the dependency table :-)

**Comment by elishowk** [comment]
> You'll need to run `make style` again to update the dependency table :-)

Oh ok, I was wondering where it comes from...

**Comment by elishowk** [comment]
With a fressh venv with python3 on debian 11, here what a fresh pip install -e '.[dev]' results:

```
Successfully installed APScheduler-3.7.0 Flask-1.1.4 GitPython-3.1.18 Jinja2-2.11.3 Mako-1.1.5 MarkupSafe-1.1.1 Pillow-8.3.2 PrettyTable-2.2.0 Pygments-2.10.0 absl-py-0.13.0 aiohttp-3.7.4.post0 alabaster-0.7.12 alembic-1.7.1 appdirs-1.4.4 arrow-1.1.1 astunparse-1.6.3 async-timeout-3.0.1 attrs-21.2.0 autopage-0.4.0 babel-2.9.1 binaryornot-0.4.4 black-21.4b0 brotli-1.0.9 cachetools-4.2.2 cffi-1.14.6 chardet-4.0.0 chex-0.0.8 clang-5.0 click-7.1.2 cliff-3.9.0 cmaes-0.8.2 cmd2-2.2.0 codecarbon-1.2.0 colorama-0.4.4 colorlog-6.4.1 commonmark-0.9.1 cookiecutter-1.7.2 cycler-0.10.0 dash-2.0.0 dash-bootstrap-components-0.13.0 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 datasets-1.12.0 dill-0.3.4 dm-tree-0.1.6 docutils-0.16 execnet-1.9.0 faiss-cpu-1.7.1.post2 fire-0.4.0 flake8-3.9.2 flask-compress-1.10.1 flatbuffers-1.12 flax-0.3.4 fsspec-2021.8.1 fugashi-1.1.1 gast-0.4.0 gitdb-4.0.7 google-auth-1.35.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 greenlet-1.1.1 grpcio-1.40.0 h5py-3.1.0 imagesize-1.2.0 iniconfig-1.1.1 ipadic-1.0.0 isort-5.9.3 itsdangerous-1.1.0 jax-0.2.20 jaxlib-0.1.71 jinja2-time-0.2.0 keras-2.6.0 keras-preprocessing-1.1.2 keras2onnx-1.7.0 kiwisolver-1.3.2 markdown-3.3.4 matplotlib-3.4.3 mccabe-0.6.1 msgpack-1.0.2 multidict-5.1.0 multiprocess-0.70.12.2 mypy-extensions-0.4.3 nltk-3.6.2 numpy-1.19.5 oauthlib-3.1.1 onnx-1.10.1 onnxconverter-common-1.8.1 opt-einsum-3.3.0 optax-0.0.9 optuna-2.9.1 pandas-1.3.3 parameterized-0.8.1 pathspec-0.9.0 pbr-5.6.0 plac-1.3.3 plotly-5.3.1 pluggy-1.0.0 portalocker-2.0.0 poyo-0.5.0 protobuf-3.17.3 psutil-5.8.0 py-1.10.0 py-cpuinfo-8.0.0 pyarrow-5.0.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycodestyle-2.7.0 pycparser-2.20 pyflakes-2.3.1 pynvml-11.0.0 pyperclip-1.8.2 pytest-6.2.5 pytest-forked-1.3.0 pytest-timeout-1.4.2 pytest-xdist-2.3.0 python-dateutil-2.8.2 python-slugify-5.0.2 pytz-2021.1 ray-1.6.0 recommonmark-0.7.1 redis-3.5.3 requests-oauthlib-1.3.0 rouge-score-0.0.4 rsa-4.7.2 sacrebleu-1.5.1 scikit-learn-0.24.2 scipy-1.7.1 sentencepiece-0.1.96 six-1.15.0 smmap-4.0.0 snowballstemmer-2.1.0 soundfile-0.10.3.post1 sphinx-3.2.1 sphinx-copybutton-0.4.0 sphinx-intl-2.0.1 sphinx-markdown-tables-0.0.15 sphinx-rtd-theme-0.4.3 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-2.0.0 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.5 sphinxext-opengraph-0.4.1 sqlalchemy-1.4.23 stevedore-3.4.0 tabulate-0.8.9 tenacity-8.0.1 tensorboard-2.6.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorboardX-2.4 tensorflow-2.6.0 tensorflow-estimator-2.6.0 termcolor-1.1.0 text-unidecode-1.3 threadpoolctl-2.2.0 timeout-decorator-0.5.0 timm-0.4.12 toml-0.10.2 toolz-0.11.1 torch-1.9.0 torchaudio-0.9.0 torchvision-0.10.0 transformers typing-extensions-3.7.4.3 tzlocal-2.1 unidic-1.0.3 unidic-lite-1.0.8 wasabi-0.8.2 wcwidth-0.2.5 werkzeug-1.0.1 wheel-0.37.0 wrapt-1.12.1 xxhash-2.0.2 yarl-1.6.3
```

**Review by LysandreJik — APPROVED** [review]
LGTM

**Pull request merged**
