### PR TITLE
phi3 chat_template does not support system role

### PR DESCRIPTION
**Pull request by amitportnoy**
# What does this PR do?

Removes misleading example which uses the system role

Phi3 chat_template does not use that role.
See https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/main/tokenizer_config.json#L119

- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@stevhliu @MKhalusova @ArthurZucker @younesbelkada

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
LGTM let's just make sure the CI is green 😉

**Comment by amitportnoy** [comment]
> LGTM let's just make sure the CI is green 😉

The test that fails doesn't make sense to me, as the model's output is not deterministic.

**Review by younesbelkada — COMMENTED** [review]
Thanks @amitportnoy !
Can you just update the old expected output:
```bash
>>> print(text)
<s><|system|> You are a helpful digital assistant. Please provide safe, ethical and accurate information to the user.<|end|><|user|> Can you provide ways to eat combinations of bananas and dragonfruits?<|end|><|assistant|> Absolutely! Bananas and dragonfruits are both delicious fruits that can be combined in various ways to create tasty and nutrit
```
With the new one in the docstring?

**Comment by younesbelkada** [comment]
The expected one should be (according to the CI failure trace):
```bash
    <s><|user|> 
    Can you provide ways to eat combinations of bananas and dragonfruits?<|end|> 
    <|assistant|> 
    Certainly! Bananas and dragonfruits can be combined in various delicious ways. Here are some ideas for eating combinations of bananas and
```

**Comment by amitportnoy** [comment]
(tests passed)

**Review by younesbelkada — APPROVED** [review]
Thanks !

**Review by ArthurZucker — APPROVED** [review]
Lgtm thanks

**Pull request merged**
