### PR TITLE
Replace 'decord' with 'av' in VideoClassificationPipeline

### PR DESCRIPTION
**Pull request by Tyx-main**
# What does this PR do?

As the [feature request](https://github.com/huggingface/transformers/issues/28880) shows, the dependency 'decord' can only be used in x86 instead of aarch. For those users who want to use VideoClassificationPipeline on aarch, we decide to replace 'decord' with 'av' which is a perfect  adaptation for the two above-mention architecture.

Fixes # (issue)
[feature request](https://github.com/huggingface/transformers/issues/28880)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@amyeroberts 

## Test on V100

To make sure the codes is correct, I test the VideoClassificationPipeline via [tests/pipelines/test_pipelines_video_classification.py](https://github.com/huggingface/transformers/blob/main/tests/pipelines/test_pipelines_video_classification.py) on V100

Here is my command(the current dir is the root dir of transformers):
```
TRANSFORMERS_TEST_BACKEND="torch" TRANSFORMERS_TEST_DEVICE="cuda:0" TRANSFORMERS_TEST_DEVICE_SPEC="spec.py" python -m pytest -v tests/pipelines/test_pipelines_video_classification.py
```
The codes of  spec.py:
```
import torch
DEVICE_NAME = "cuda:0"
MANUAL_SEED_FN = torch.cuda.manual_seed_all
EMPTY_CACHE_FN = torch.cuda.empty_cache
DEVICE_COUNT_FN = torch.cuda.device_count
```

And the version of 'av' is 11.0.0 which is the default version of 'pip install av'

Finaly we can get the 'pass' via testing [tests/pipelines/test_pipelines_video_classification.py](https://github.com/huggingface/transformers/blob/main/tests/pipelines/test_pipelines_video_classification.py):
test

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Awesome! Thanks for adding this and making our pipelines more accessible 🔥 

To resolve the failing quality checks: 
* Some are unrelated to this PR. A fix was pushed on main, could you rebase to include this? 
* Some are just linting checks - running `make fixup` and pushing the changes should resolve

**Comment by Tyx-main** [comment]
> Awesome! Thanks for adding this and making our pipelines more accessible 🔥
> 
> To resolve the failing quality checks:
> 
> * Some are unrelated to this PR. A fix was pushed on main, could you rebase to include this?
> * Some are just linting checks - running `make fixup` and pushing the changes should resolve

Thanks for your review！I will fix the remaining problems.

**Comment by Tyx-main** [comment]
make fixup

**Review by amyeroberts — APPROVED** [review]
Looks great - thanks!

**Pull request merged**
