### PR TITLE
[FuturWarning] Add futur warning for LEDForSequenceClassification

### LINKED ISSUE #19019: LEDForSequenceClassification fine-tuning model gives: IndexError: index out of range in self
### System Info

transformers - 4.21.1
Python - 3.8.13
torch - 1.12.0+cu113

### Who can help?

@patrickvonplaten

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I'm trying to fine-tune the LED model for the SequenceClassification task.

It works when I use max_sequence_length = 1024 but it doesn't when it goes beyond these numbers. D

After debugging, I found a similar issue #14312, and tried applying the proposed solution by adding decoder_input_ids even though it doesn't make sense to me that we really need this as an input.

To reproduce:
```
from transformers import LEDTokenizer, LEDForSequenceClassification
  
tokenizer = LEDTokenizer.from_pretrained("allenai/led-base-16384")
model = LEDForSequenceClassification.from_pretrained("allenai/led-base-16384")

# this works (tokens < 1024)
inputs = tokenizer("HuggingFace"*1000, return_tensors="pt")
with torch.no_grad():
      model(**input)

# this does not work! (tokens > 1024)
inputs = tokenizer("HuggingFace"*2048, return_tensors="pt")
with torch.no_grad():
      model(**input)

# this does not work as well! (tokens > 1024)
inputs = tokenizer("HuggingFace"*2048, return_tensors="pt")
inputs['decoder_input_ids'] = inputs['input_ids'][:512]
with torch.no_grad():
      model(**input)
```

_Without adding decoder_input_ids to tokenized inputs,_
It simply complains of Index out of range while calling torch.embedding.

_with decoder_input_ids as suggested in the reference issue above,_
It throws an **IndexError: The Shape of the mask [1, 1026] at index 1 does not match the shape of the indexed tensor  [1, 512, 768] at index 1**

### Expected behavior

As LEDForSequenceClassification should work for a sequence length of more than 1024 tokens.

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
fixes #19019 by replacing the construction of the `eos_mask` in the `SequenceClassification`. 
Also adds a test to make sure that long sequence are properly processed

### CODE REVIEW

**Comment by ArthurZucker** [comment]
I think deleting the class would be less confusing, we discussed this with Patrick, the original paper does not use the encoder decoder model for sequence classification. WDYT @LysandreJik

**Comment by LysandreJik** [comment]
Let's please do a deprecation cycle :pray:

**Comment by ArthurZucker** [comment]
Would love to learn about, what can I do?

**Comment by sgugger** [comment]
I think there is still work to do here?

**Comment by LysandreJik** [comment]
@ArthurZucker, instead of deleting the class, you would first start by adding a `FutureWarning` when it is instantiated or called, mentioning that it is deprecated and what is recommended instead. You would mention that the class will be deleted in version 5, and that such a code will error out then.

**Comment by ArthurZucker** [comment]
Oh it ! Thanks for the pointers

**Review by sgugger — APPROVED** [review]
One small nit but LGTM otherwise, thanks!

**Pull request merged**
