### PR TITLE
[`T5`] Adding model_parallel = False to `T5ForQuestionAnswering` and `MT5ForQuestionAnswering`

### LINKED ISSUE #24682: Unable to use Trainer with T5ForQuestionAnswering
### System Info

- `transformers` version: 4.31.0.dev0
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.9.17
- Huggingface_hub version: 0.16.2
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

Tagging @sgugger since this is related to the Trainer and @ArthurZucker and @younesbelkada since it is also related to the text model T5ForQuestionAnswering.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I first ran into this error when running the `examples/pytorch/question-answering/run_qa.py` script, but I am able to reproduce with the following minimal example:

```python
from transformers import AutoModelForQuestionAnswering, Trainer
model = AutoModelForQuestionAnswering.from_pretrained("sjrhuschlee/flan-t5-base-squad2")
trainer = Trainer(model=model)
```

This produces the error
```python
Traceback (most recent call last):
  File "/Users/sebastianlee/miniconda3/envs/sjrl_transformers/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-84527b5cd844>", line 3, in <module>
    trainer = Trainer(model=model)
  File "/Users/sebastianlee/Documents/code/sjrl_transformers/src/transformers/trainer.py", line 373, in __init__
    if hasattr(model, "is_parallelizable") and model.is_parallelizable and model.model_parallel:
  File "/Users/sebastianlee/miniconda3/envs/sjrl_transformers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'T5ForQuestionAnswering' object has no attribute 'model_parallel'
```

I believe this could be fixed by adding 
```python
self.model_parallel = False
```
to the init method of T5ForQuestionAnswering. However, this model does not support parallelization so I wonder if it would be better to somehow update the Trainer or possibly remove the `is_parallelizable` attribute from T5ForQuestionAnswering.

### Expected behavior

For the Trainer to work with T5ForQuestionAnswering.

### PR DESCRIPTION
**Pull request by sjrl**
# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/24682 by adding `self.model_parallel = False`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ArthurZucker and @younesbelkada

### CODE REVIEW

**Comment by sjrl** [comment]
Is there a good way to add a test for this? I wasn't sure where a test like this would be added.

**Comment by ydshieh** [comment]
> Is there a good way to add a test for this? I wasn't sure where a test like this would be added.

No need to add a test for this. We have `test_model_parallelization` which tests model parallelization (the opposite).
As we are dealing with some  deprecated thing, it doesn't worth much time on it.

**Review by younesbelkada — APPROVED** [review]
Thank you for this!

**Review by ArthurZucker — COMMENTED** [review]
LGTM thanks for the prompt fix!

**Comment by ydshieh** [comment]
Thanks! Would be nice if you can check this change works (i.e. fix the issue you opened in #24682) 🙏

**Comment by sjrl** [comment]
> Thanks! Would be nice if you can check this change works

Definitely! I just ran the code locally and it works.

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing! 

Just a question for my understanding (cc @ydshieh) - does this mean this class has `model_parallel = False` and `is_parallelizable = True`?

**Comment by ydshieh** [comment]
Yes. It seems a bit strange indeed. So far all `is_parallelizable` is set at the `XXXPreTrainedModel` level.

I think it's fine as the only usage of `is_parallelizable` is here

```python
        if hasattr(model, "is_parallelizable") and model.is_parallelizable and model.model_parallel:
            self.is_model_parallel = True
        else:
            self.is_model_parallel = False
```
There shouldn't bee too much confusing between `is_parallelizable = True` and `always model_parallel = False` for just this single (and new) model class.

**Pull request merged**
