### PR TITLE
Timm to ViT Model conversion fix #26219

### LINKED ISSUE #26219: Converting TIMM to HF Vision transformers
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-5.15.0-1040-aws-x86_64-with-glibc2.31
- Python version: 3.10.12
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.2
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@amyeroberts 

Thank you for the tool to convert timm weights to HF ViT implementation compatible ones!  I'm, however, facing issues with converting the `augreg` weights. Running 

`python -m transformers.models.vit.convert_vit_timm_to_pytorch --vit_name vit_base_patch16_224.augreg_in21k_ft_in1k --pytorch_dump_folder_path $MY_MODEL_PATH`

results in an error 

``` 
line 156, in convert_vit_checkpoint
    config.patch_size = int(vit_name[-6:-4])
ValueError: invalid literal for int() with base 10: 't_'
```

The issue stems from the code to infer the input image size and patch size configs which are currently hard coded to exist at specific indices (which doesn't always happen).  Can this be fixed? I have right now patched hacked a version locally that works for this specific `vit_name` example, but a more general fix would be great! 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Steps to reproduce the behaviour

1. `python -m transformers.models.vit.convert_vit_timm_to_pytorch --vit_name vit_base_patch16_224.augreg_in21k_ft_in1k --pytorch_dump_folder_path local_dump_folder`

### Expected behavior

A converted `pytorch_model.bin` and corresponding `config` in `local_dump_folder`.

### PR DESCRIPTION
**Pull request by prabhuteja12**
A problem with timm to Vit converter code was identified in #26219 

This is caused by a rather strict index based parsing of the timm model identifier which fails for several cases. This PR does two things:

1. Fixes that issue by using a regex parser for patch and image size. 
2. Fixes ViT configuration differences (ViT Small, missing Vit-Tiny, Vit-giant/gigantic). 

 @amyeroberts, @ArthurZucker

### CODE REVIEW

**Comment by LysandreJik** [comment]
@rwightman do you agree with this change?

**Comment by prabhuteja12** [comment]
Just wanted to check in if a review has been possible.

**Comment by rwightman** [comment]
It looks like an improvement on the original w/ better coverage, but there are less 'hard coded' ways of grabbing the needed dims and params from the timm model, avoiding model dependent ifs, etc

**Comment by prabhuteja12** [comment]
Can you please give me more details on the less hard coded ways? The simplest way I could think of was to use regex.

**Pull request closed without merging**
