### PR TITLE
german docs translation

### PR DESCRIPTION
**Pull request by flozi00**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger i am not sure about using "du / ihr" or "sie".
"Du" is more personal, while "sie" is more formal

### CODE REVIEW

**Comment by sgugger** [comment]
I think it's preferable to use the more formal option, but in most cases, I'd prefer to reformulate the sentences to use the first person plural (wir) unless the sentence actually describes an action the user has to take. We're using the same style for the French translation which also has two pronouns for "you".

**Comment by flozi00** [comment]
okay, then i will rewrite to "wir" and "sie"

At the moment its still mixed with du und sie

**Comment by sgugger** [comment]
Let me know when you're done and thanks a lot for diving into German translation! (Sorry should have begun with that!)

**Comment by omarespejel** [comment]
Thank you, @flozi00, for starting the German translation! 🤗 We created a new issue to track German translations (#18564).  

@sgugger LGTM.

**Review by omarespejel — APPROVED** [review]

**Comment by flozi00** [comment]
ready to review @sgugger

**Review by sgugger — APPROVED** [review]
Very nice, thanks a lot for your work on this!

**Pull request merged**
