### PR TITLE
[HybridCache] Fix `get_seq_length` method

### LINKED ISSUE #31664: Generation with HybridCache fails (affecting Gemma-2)
### System Info

 - `transformers` version: 4.43.0.dev0
- Platform: macOS-14.5-arm64-arm-64bit
- Python version: 3.11.6
- Huggingface_hub version: 0.23.3
- Safetensors version: 0.4.2
- Accelerate version: 0.27.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.3.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.8.1 (cpu)
- Jax version: 0.4.24
- JaxLib version: 0.4.24

### Who can help?

@sanchit-gandhi 

### Reproduction

Generation of Gemma-2 currently fails on `main`, e.g. with the following toy codesnippet:
```python
from transformers.models.gemma2 import Gemma2ForCausalLM, Gemma2Config
import torch

config = Gemma2Config(num_hidden_layers=1, vocab_size=128, hidden_size=16, intermediate_size=32, num_attention_heads=1, num_key_value_heads=1)
model = Gemma2ForCausalLM(config)

input_ids = torch.ones((1, 10), dtype=torch.int)
model.generate(input_ids)
```
Traceback:
```
Traceback (most recent call last):
  File "/Users/sanchitgandhi/transformers/debug_gemma2.py", line 8, in <module>
    model.generate(input_ids)
  File "/Users/sanchitgandhi/venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanchitgandhi/transformers/src/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/Users/sanchitgandhi/transformers/src/transformers/generation/utils.py", line 2644, in _sample
    model_kwargs = self._get_initial_cache_position(input_ids, model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sanchitgandhi/transformers/src/transformers/generation/utils.py", line 1409, in _get_initial_cache_position
    model_kwargs["cache_position"] = torch.arange(past_length, cur_len, device=input_ids.device)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arange() received an invalid combination of arguments - got (NoneType, int, device=torch.device), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, *, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 ```

### Expected behavior

This is fixed by by handling the exception in generate (PR #31661).

cc @ArthurZucker

### PR DESCRIPTION
**Pull request by sanchit-gandhi**
# What does this PR do?

Fixes #31664

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by LysandreJik** [comment]
Failures seem unrelated; I'll merge it and do a patch release

**Comment by LysandreJik** [comment]
Patch is up on pypi! Thanks both for the quick PR and review :)

**Comment by sanchit-gandhi** [comment]
Thanks @LysandreJik for the speedy patch!

**Pull request merged**
