### PR TITLE
Fix init

### PR DESCRIPTION
**Pull request by patelrajnath**
# What does this PR do?
"RobertaPreTrainedModel" is missing in models' __init__.py. It is needed, in case we need to create a subclass of the same like "RobertaForTokenClassification".

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Indeed, good idea! I think this may cause merge conflicts with https://github.com/huggingface/transformers/pull/9446, but this PR will be easier to rebase than #9446, let's wait for that one to be merged first if that's okay.

cc @sgugger

**Comment by sgugger** [comment]
Yes, let's wait for #9446 to be merged please :-)

**Review by LysandreJik — APPROVED** [review]
LGTM! I don't understand why the CI doesn't run on your branch though.

**Comment by patelrajnath** [comment]
@LysandreJik yes, I'm not sure regarding the CI errors, as I'm not that much into it. I ran the tests in Pycharm, they passed. Can we check the Logs if we could find some clue there?

**Pull request closed without merging**
