### PR TITLE
Fix typing about next_beam_tokens and next_beam_indices

### PR DESCRIPTION
**Pull request by fzyzcjy**
# What does this PR do?

Looking at source code they seem to be int not float?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
Please make sure to run `make style` on your branch so that the quality tests pass.
cc @gante for review.

**Review by gante — APPROVED** [review]
Thank you for the fix!

(as Sylvain wrote above, you need to run `make style`, commit, and push to the branch to make our CI green 🤗 )

**Comment by fzyzcjy** [comment]
Sure, I will do it soon together with another PR in https://github.com/huggingface/transformers/issues/20820

**Comment by sgugger** [comment]
Please have each of your PR focused on one thing. We don't want to group changes that are not linked to each other in the same PR :-)

**Comment by fzyzcjy** [comment]
Sure, I mean file two PRs but do the *work* in one single time slot of mine ;)

No worries, I am experienced to make PRs (e.g. to Google Flutter https://github.com/flutter/flutter/pulls?q=is%3Apr+author%3Afzyzcjy)

**Comment by fzyzcjy** [comment]
bump

**Comment by fzyzcjy** [comment]
Hi, I wonder what version of `black` is required? I have tried

```
(base) ➜  transformers git:(patch-1) python -m black -- examples tests src utils        
reformatted /Users/tom/RefCode/transformers/examples/flax/image-captioning/create_model_from_encoder_decoder_models.py
reformatted /Users/tom/RefCode/transformers/examples/flax/language-modeling/t5_tokenizer_model.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/pytorch-lightning/lightning_base.py
reformatted /Users/tom/RefCode/transformers/examples/flax/vision/run_image_classification.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/multiple_choice/utils_multiple_choice.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/run_camembert.py
reformatted /Users/tom/RefCode/transformers/examples/flax/text-classification/run_flax_glue.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/pytorch-lightning/run_glue.py
reformatted /Users/tom/RefCode/transformers/examples/flax/language-modeling/run_clm_flax.py
reformatted /Users/tom/RefCode/transformers/examples/flax/token-classification/run_flax_ner.py
reformatted /Users/tom/RefCode/transformers/examples/flax/language-modeling/run_mlm_flax.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/seq2seq/old_test_fsmt_bleu_score.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/run_language_modeling.py
reformatted /Users/tom/RefCode/transformers/examples/flax/language-modeling/run_t5_mlm_flax.py
reformatted /Users/tom/RefCode/transformers/examples/flax/language-modeling/run_bart_dlm_flax.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/run_openai_gpt.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/seq2seq/run_eval.py
reformatted /Users/tom/RefCode/transformers/examples/flax/question-answering/run_qa.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/seq2seq/old_test_datasets.py
reformatted /Users/tom/RefCode/transformers/examples/flax/summarization/run_summarization_flax.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/seq2seq/seq2seq_trainer.py
reformatted /Users/tom/RefCode/transformers/examples/pytorch/benchmarking/plot_csv_file.py
reformatted /Users/tom/RefCode/transformers/examples/legacy/token-classification/run_tf_ner.py
...
```

and so on. It is changing formats for almost every file, such as:

image

(P.S. I did not run `make style` but instead invoke that command directly because my `black` on PATH has a little conflict.)

**Comment by gante** [comment]
@fzyzcjy We use black 22.3 (see [here](https://github.com/huggingface/transformers/blob/e1cd78634ae4ba2b0a3d548bd6663c08765a8b4d/setup.py#L101))

**Comment by fzyzcjy** [comment]
Hmm it is the correct version

```
(dev-transformers) ➜  lean-gym git:(main) python -m black --version
python -m black, 22.3.0 (compiled: yes)
```

**Comment by gante** [comment]
@fzyzcjy Suggestion: revert to the first commit (which only touches 2 lines), run `make fixup` (which only touches modified files), then force commit the result :)

**Pull request closed without merging**
