### PR TITLE
chore: migrate coverage cfg to pyproject.toml

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
# What does this PR do?

Migrate coverage configuration to `pyproject.toml`

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request)

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @ydshieh

**Comment by ydshieh** [comment]
Hi @SauravMaheshkar Could you elaborate this a bit more? For example, where we can find the output coverage report file?

**Comment by SauravMaheshkar** [comment]
There should be no difference in where the output file is generated. It's just a simple change of where coverage is configured.

**Review by ydshieh — APPROVED** [review]
Thanks!

**Comment by ydshieh** [comment]
For the record:

https://coverage.readthedocs.io/en/latest/config.html

> Coverage.py will read from “pyproject.toml” if TOML support is available, either because you are running on Python 3.11 or later, or because you installed with the toml extra (pip install coverage[toml]

**Review by amyeroberts — APPROVED** [review]
Thanks!

**Review by LysandreJik — APPROVED** [review]

**Pull request merged**
