### PR TITLE
Pin huggingface_hub

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Currently tests are failing on `test_torch` CI run e.g. [this one](https://app.circleci.com/pipelines/github/huggingface/transformers/77707/workflows/ababd81d-2704-4b31-914d-15784acfad8e/jobs/989825).

The tests failing relating to the recent release of the hub are: 
```
FAILED tests/models/auto/test_modeling_auto.py::AutoModelTest::test_cached_model_has_minimum_calls_to_head - AssertionError: 0 != 1
FAILED tests/models/auto/test_tokenization_auto.py::AutoTokenizerTest::test_cached_tokenizer_has_minimum_calls_to_head - AssertionError: 0 != 1
``` 

Pinning until tests are resolved.

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
I think we will need to update `src/transformers/dependency_versions_table.py` too, you will see in the CI report :-)

**Comment by ydshieh** [comment]
Thanks a lot!

**Comment by ydshieh** [comment]
Looks like we still get 0.19 ...

**Comment by amyeroberts** [comment]
😫

**Comment by ydshieh** [comment]
`accelerate`!

```
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.17.3
    Uninstalling huggingface-hub-0.17.3:
      Successfully uninstalled huggingface-hub-0.17.3
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.24.1
    Uninstalling accelerate-0.24.1:
      Successfully uninstalled accelerate-0.24.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tokenizers 0.14.1 requires huggingface_hub<0.18,>=0.16.4, but you have huggingface-hub 0.19.0 which is incompatible.
transformers 4.36.0.dev0 requires huggingface-hub<=0.18.0,>=0.16.4, but you have huggingface-hub 0.19.0 which is incompatible.
Successfully installed accelerate-0.25.0.dev0 huggingface-hub-0.19.0 urllib3-2.0.7
```

**Comment by ydshieh** [comment]
I guess the quick but dirty way is to install huggingface_hub specific version in `.circleci/create_circleci_config.py` after the line 

pip install -U --upgrade-strategy eager git+https://github.com/huggingface/accelerate

(or ask @muellerzr to make change in `accelerate`)

**Comment by amyeroberts** [comment]
OK, shall we pin our accelerate version then to unblock and then make transformers accelerate compatible?

cc @muellerzr  and @ArthurZucker as it looks like it involves `tokenizers` as well

**Comment by amyeroberts** [comment]
The thing is, the hub version isn't pinned in accelerate: https://github.com/huggingface/accelerate/blob/main/setup.py. I might be misunderstanding pip, but I don't see why it couldn't downgrade?

**Comment by ydshieh** [comment]
In `accelerate`, no pin, so 

```
pip install -U --upgrade-strategy eager git+https://github.com/huggingface/accelerate
```
will upgrade to the latest available one, even the dependencies I believe.

**Comment by ydshieh** [comment]
Or I can try to remove `--upgrade-strategy eager`. Let me know.

**Comment by ydshieh** [comment]
But maybe 

> if there is only 2 failing tests due to huggingface_hub  0.19, let's skip them for nonw maybe and wait 
[@Lucain](https://huggingface.slack.com/team/U03QTE7PET0) ’s patch maybe?

**Comment by amyeroberts** [comment]
Opened a PR to skip the tests here: https://github.com/huggingface/transformers/pull/27393

**Pull request closed without merging**
