### PR TITLE
Upgrading sentencepiece modeling file (for proto > 4 support).

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

Upgrades the file.

Taken from `google/sentencepiece` directly.

Should prevent "Downgrade the protobuf package".

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by ArthurZucker** [comment]
I remember we said we should check if the protobuf version is installed somewhere, as we had some issues. Did it turn out to be ok?

**Comment by Narsil** [comment]
It turns out the file in https://github.com/google/sentencepiece is actually not even valid protobuf 4.x ...

**Comment by sgugger** [comment]
So this doesn't work with protobuf 4.x in the end?

**Comment by Narsil** [comment]
Nope. it passes with protobuf 3.20 in the tests, but not with 4.x.....

I think we should wait for them to upgrade before doing it ourselves (the .proto files are available so we could generate them with a 4.x compiler... but I don't like doing that.) As much as handling 4.x and 3.20 codebases is annoying I don't want to spend much time on this tbh.

I'll close this PR, we can resurrrect later maybe.

**Comment by sgugger** [comment]
Thanks for having tried!

**Pull request closed without merging**
