### PR TITLE
Fix RT-DETR weights initialization

### PR DESCRIPTION
**Pull request by qubvel**
# What does this PR do?

Fix RT-DETR bbox and class head weight initialization.

1. In`_init_weight` method bbox and class heads are not reachable for initialization. This sometimes leads to unstable training and lower results (see experiments below).
2. Added config parameter for bias initialization, in the [original code](https://github.com/lyuwenyu/RT-DETR/blob/5b628eaa0a2fc25bdafec7e6148d5296b144af85/rtdetr_paddle/ppdet/modeling/transformers/rtdetr_transformer.py#L325) biases of the head are initialized with `prior_prob=0.01` which is OK for training with 80 classes, however, while fine-tuning this value should be adjusted.

Results of the fine-tuning on `main` vs `fix` branches on CPPE-5 dataset (averaged for 6 runs each):

 - better convergence: +0.1-0.15 mAP50 on average on eval and test sets
 - lower dispersion of results

Screenshot 2024-07-01 at 09 42 12

Screenshot 2024-07-01 at 09 43 00

## Who can review?
@amyeroberts 

cc @SangbumChoi @NielsRogge

### CODE REVIEW

**Review by NielsRogge — APPROVED** [review]
Thanks for improving this! Does the model converge as fast as the original implementation?

**Comment by qubvel** [comment]
I didn't have a chance to run the fine-tuning with the original code, maybe @SangbumChoi has a fine-tuning script to compare. However, I would say that from my previous experiments with other detection models in `transformers`  RT-DTER with this fix is the best in terms of compute, convergence speed, and results achieved on `cppe-5` dataset.

**Comment by merveenoyan** [comment]
@qubvel is there anything else that needs to be done?

**Comment by qubvel** [comment]
@merve there is one more PR for generating anchors cache fix, but it's not that critical
https://github.com/huggingface/transformers/pull/31671

I also implemented `sdpa` attention, but didn't observe any speed-up in inference speed

**Comment by SangbumChoi** [comment]
@qubvel Isn't SDPA is default operation in [MDHA](https://pytorch.org/tutorials/intermediate/scaled_dot_product_attention_tutorial.html)? 
> This function has already been incorporated into torch.nn.MultiheadAttention and torch.nn.TransformerEncoderLayer.

Since there are many FLOPS in encoder (which is not related to Attention module) I guess speed-up with applying attention friendly library such as SDPA, xformers might be marginal.

@qubvel @NielsRogge Thanks for this PR. (Good to here that this is the best result by far) Unfortunately I don't have any results of finetuning raw RTDETR repo. (I have some test result in Transformers RTDETR).

**Comment by qubvel** [comment]
@SangbumChoi I'm talking about `RTDetrMultiheadAttention` [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/rt_detr/modeling_rt_detr.py#L917)

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
