### PR TITLE
Fix Base Model Name of LlamaForQuestionAnswering

### PR DESCRIPTION
**Pull request by lenglaender**
# What does this PR do?

The `LlamaForQuestionAnswering` currently has the `LlamaModel` in the `transformer` variable. This does not match the `base_model_prefix` set in `LlamaPreTrainedModel`, which is "model".

This Pull Request changes the name from `transformer` to `model` in `LlamaForQuestionAnswering`

## Who can review?
- text models: @ArthurZucker and @younesbelkada

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks for the PR ! Unfortunately this is a breakign change - you could overwrite the `base_model_prefix` only for that class though, what do you think?

**Comment by lenglaender** [comment]
True, I didn't think about whether renaming the variables would be a breaking change. In this case, setting `base_model_prefix` to the right value is sufficient. I changed it.

**Review by ArthurZucker — APPROVED** [review]
Might be "breaking" but since it was not reported it means it was not used as you mentioned you cannot save + load

**Comment by ArthurZucker** [comment]
@younesbelkada feel free to merge if it is alright with you

**Review by younesbelkada — APPROVED** [review]
Looks great, thanks !

**Pull request merged**
