### PR TITLE
Fixed gradient_checkpointing/use_cache bug in blenderbot

### LINKED ISSUE #21737: [`Generate`] Fix `gradient_checkpointing` and `use_cache` bug for generate-compatible models
## Feature request

When using a model that uses `gradient_checkpointing` and if a user wants to call `generate` with `use_cache`, it leads some models to bugs, such as the one described in https://github.com/huggingface/transformers/pull/21733

The fix should be to slightly refactor some models following the same procedure as in the aforementioned PR

### How to participate

1. If it is your first time here, have a quick look at our [contribution guidelines](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md) 🤗 
2. Pick a model from the list below. Check in the comments here if it hasn't been claimed yet.
3. Claim your models in the comments (e.g. "I want to work on GPT2")
4. Replicate the changes of [this PR](https://github.com/huggingface/transformers/pull/21733) to your model of choice. In other words, move the `if` block to the line above the `... if use_cache else None`, in the same `.forward()` function. Please note that some models may have more than one instance of this block!
5. Make sure you've run our automated code formatting tool (i.e. run `make fixup` in your shell -- also run `make fix-copies` if it requests you to do so)
6. Open a PR. Tag @younesbelkada or @gante (one of us is enough)

That's it! With each change, you'll be making `transformers` a little bit better for all of us 💛 

### Models to fix:
- [x] Bart | https://github.com/huggingface/transformers/pull/21866
- [x] Bert
- [x] BigBird | https://github.com/huggingface/transformers/pull/21882
- [x] BigBirdPegasus
- [x] BioGPT | https://github.com/huggingface/transformers/pull/21844
- [x] Blenderbot
- [x] BlenderbotSmall
- [x] BlipText
- [x] Bloom
- [x] CodeGen
- [x] Esm
- [x] Git | https://github.com/huggingface/transformers/pull/21818
- [x] GPT2 | https://github.com/huggingface/transformers/pull/21772
- [x] GptNeo | https://github.com/huggingface/transformers/pull/21733
- [x] GptNeoX | https://github.com/huggingface/transformers/pull/21815
- [x] GPT-J
- [x] ImageGPT | https://github.com/huggingface/transformers/pull/21816
- [x] LED | https://github.com/huggingface/transformers/pull/21840
- [x] LongT5
- [x] M2M100 | https://github.com/huggingface/transformers/pull/21841
- [x] Marian | https://github.com/huggingface/transformers/pull/21842
- [x] MBart | https://github.com/huggingface/transformers/pull/21918
- [x] MegratronBert | https://github.com/huggingface/transformers/pull/21921
- [x] MVP | https://github.com/huggingface/transformers/pull/21920
- [x] OPT
- [x] Pegasus
- [x] PegasusX
- [x] ProphetNet | https://github.com/huggingface/transformers/pull/21772
- [x] RemBert
- [x] RoFormer
- [x] Speech2Text
- [x] Speech2Text2
- [x] SpeechT5
- [x] SwitchTransformer
- [x] T5
- [ ] TimeSeriesTransformer
- [x] TrajectoryTransformer
- [x] TrOCR
- [x] Whisper
- [x] XGLM
- [x] XLMRobertaXL
- [x] Xmod

### PR DESCRIPTION
**Pull request by Batese2001**
# What does this PR do?

Fixes #21737 for blenderbot

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@younesbelkada

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Hello @Batese2001 
Thanks a lot for the PR! 💪 
There are some small conflicts on the PR, could you please resolve them? After that you should be good to go!

**Review by younesbelkada — COMMENTED** [review]
Thanks for iterating! Can you also remove [this block](https://github.com/Batese2001/transformers/blob/fixGrad/src/transformers/models/blenderbot/modeling_blenderbot.py#L1023-L1028)

**Comment by Batese2001** [comment]
@younesbelkada Thanks for your help! It should be all good

**Review by gante — APPROVED** [review]
Awesome, thank you for the fix 🔥

**Pull request merged**
