### PR TITLE
Trainer._load_from_checkpoint - support loading multiple Peft adapters

### LINKED ISSUE #30478: Trainer with resume_from_checkpoint does not work with multiple Peft Adapters
### System Info

Since it it possible to have multiple Peft adapters in the same model, it should also be possible to resume a training of such models from checkpoint with [transformers.Trainer.train(resume_from_checkpoint=True|"path")](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.Trainer.train)  
This is needed to resume e.g. DPO/KTO trainings loaded with 2 adapters, as in [load-the-adapter-twice](https://huggingface.co/docs/trl/dpo_trainer#using-option-3---load-the-adapter-twice).

This is due to the fact that if multiple adapters exist, their weights get saved in subdirectories of the checkpoint, not directly in there. So no `adapter_model.bin` or `adapter_model.safetensors` can be found.

Anyone working on this or should I come up with a solution?

### Who can help?

@ArthurZucker @younesbelkada @muellerzr 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

from https://huggingface.co/docs/trl/dpo_trainer#using-option-3---load-the-adapter-twice
``` python
# Load the base model.
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)
model = AutoModelForCausalLM.from_pretrained(
    "mistralai/mixtral-8x7b-v0.1",
    load_in_4bit=True,
    quantization_config=bnb_config,
    attn_implementation="flash_attention_2",
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
model.config.use_cache = False

# Load the adapter.
model = PeftModel.from_pretrained(
    model,
    "/path/to/peft",
    is_trainable=True,
    adapter_name="train",
)
# Load the adapter a second time, with a different name, which will be our reference model.
model.load_adapter("/path/to/peft", adapter_name="reference")

# Initialize the trainer, without a ref_model param.
dpo_trainer = DPOTrainer(
    model,
    ...
    model_adapter_name="train",
    ref_adapter_name="reference",
)
```
After a checkpoint is saved, interrupt the training and resume with:
`dpo_trainer.train(resume_from_checkpoint=True)`  

But this throws the following error: `ValueError(f"Can't find a valid checkpoint at {resume_from_checkpoint}")`   

### Expected behavior

the training should resume

### PR DESCRIPTION
**Pull request by claralp**
# What does this PR do?

Since it it possible to have multiple Peft adapters in the same model, it should also be possible to resume a training of such models from checkpoint with [transformers.Trainer.train(resume_from_checkpoint=True|"path")](https://huggingface.co/docs/transformers/main_classes/trainer#transformers.Trainer.train).  
No documentation changes because this is a fix of sth already existing, tested with DPO/KTO

Fixes #30478

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@lewtun @kashif @younesbelkada

### CODE REVIEW

**Comment by kashif** [comment]
nice @claralp would you mind also adding some tests?

**Comment by claralp** [comment]
@kashif will try. Guess I can use a similar model setup as here [test_trainer.py#L933](https://github.com/huggingface/transformers/blob/main/tests/trainer/test_trainer.py#L933)  

Another question: How is the checkpoint loading with DeepSpeed supposed to work with this [trainer.py#L1847](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L1847)?

**Review by younesbelkada — APPROVED** [review]
Thanks for adding the support for loading multiple adapters with `load_from_checkpoint`!

**Review by lewtun — COMMENTED** [review]
Very clean implementation @claralp ! 

> Guess I can use a similar model setup as here [test_trainer.py#L933](https://github.com/huggingface/transformers/blob/main/tests/trainer/test_trainer.py#L933)

Yeah this makes sense and I think you should be able to adapt the logic used for full training here: https://github.com/huggingface/transformers/blob/1e05671d213642a67dd418c13a18a17a18c25117/tests/trainer/test_trainer.py#L1787

**Review by kashif — APPROVED** [review]

**Comment by claralp** [comment]
@kashif @lewtun please check if this works now for you.

Note: Discovered another bug while implementing this.
While the `PeftAdapterMixin.set_adapter` function supports multiple active adapters, its internal logic for setting multiple adapters active is broken.  
But this needs to be fixed in the Peft library first

**Comment by kashif** [comment]
ok @claralp let's link the peft issue here too then?

**Review by younesbelkada — APPROVED** [review]
Thanks again ! seconded what @kashif said ! if you could have a small reproducer to repro the bug and file it on PEFT it would be really great 🙏

**Comment by claralp** [comment]
@kashif, @younesbelkada somehow the issue cannot be reproduced anymore.   

The idea: 
Since multiple adapters can be active at the same time I would have expected the same in [src/peft/utils/other.py#L272](https://github.com/huggingface/peft/blob/main/src/peft/utils/other.py#L272).
I had an error previously when calling this with a list of adapters in [src/transformers/integrations/peft.py#L311](https://github.com/huggingface/transformers/blob/main/src/transformers/integrations/peft.py#L311).  
This was before [commits/16bd0ef66f642ef4b69f4f21cfc368d548318672](https://github.com/huggingface/transformers/pull/30505/commits/16bd0ef66f642ef4b69f4f21cfc368d548318672) when I accessed the `active_adapters` property instead of `active_adapter`.  
But when I now run a test case with two active adapters, it works.  
So I would treat this as solved

**Comment by claralp** [comment]
@kashif @younesbelkada @lewtun is there any open point for me to fix now or is this ready?

**Comment by younesbelkada** [comment]
On my end looks great, just waiting for a final review cc @ArthurZucker @LysandreJik

**Review by LysandreJik — APPROVED** [review]
This looks good to me! cc @muellerzr if you're fine with the changes in `Trainer`, feel free to merge.

**Review by muellerzr — APPROVED** [review]
LG2M, thanks for also adding a test!

**Pull request merged**
