### PR TITLE
Fix whisper for `pipeline`

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
After the merge of #19378 , the feature extractor does not work with the `pipeline` function. This PR is the same as #19385.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Before we merge here, let's try to have the following tests working:

- Automatic pipeline tests for dummy whisper model (as discussed offline) 
- 2 slow pipeline tests (one for speech recognition, one for speech translation here: [https://github.com/huggingface/transformers/blob/10100979ed0594d4cfe1982cdfac9642a[…]/tests/pipelines/test_pipelines_automatic_speech_recognition.py](https://github.com/huggingface/transformers/blob/10100979ed0594d4cfe1982cdfac9642a68e473e/tests/pipelines/test_pipelines_automatic_speech_recognition.py#L54)

**Comment by ArthurZucker** [comment]
We were missing a `_CHECKPOINT_FOR_DOC`, so I added a warning when the tests are skipped. 
It seems a little bit problematic as if it is unused, `quality` will fail (and in our case, I had to change the code to use it 😃 ) 
Other models that are not tested : 
`SpeechEncoderDecoderModel, Speech2TextForConditionalGeneration`, which are also just missing the `_CHECKPOINT_FOR_DOC`(see [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/speech_to_text/modeling_speech_to_text.py#L41) )

**Review by patrickvonplaten — APPROVED** [review]
Thanks for adding the tests!

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
