### PR TITLE
 [BUG] Fix gemma 2 flash attention 2

### PR DESCRIPTION
**Pull request by ghost**
There was a bug *line 815*:

It was using the `version` library and, using the `version` function argument.

`AttributeError: 'str' object has no attribute 'parse'`

### CODE REVIEW

**Comment by tanliboy** [comment]
I got the same problem while trying to fine-tune Gemma 2 with the latest flash-attn. Thanks for fixing it!

**Comment by Boubou78000** [comment]
> I got the same problem while trying to fine-tune Gemma 2 with the latest flash-attn. Thanks for fixing it!

I just fixes **ONE** of the problem.
There are more 😭

**Comment by vanilladucky** [comment]
Hi, is this bug not going to get fixed? My implementation with flash attention for Gemma 2 is not working because of this problem.

**Comment by Boubou78000** [comment]
> Hi, I saw this case as being closed and was wondering if this bug not going to get fixed? My implementation with flash attention for Gemma 2 is not working because of this problem.
> 
> I was using the flash attention library v==2.6.1

1. Install the dev version from source
2. [No the end of the problems](https://github.com/huggingface/transformers/issues/31953)

**Comment by vanilladucky** [comment]
Ah yes, managed to get it fixed, thank you very much!

**Comment by thepowerfuldeez** [comment]
Hi everyone! Can't find the fix for that in the latest main, nor in the discussion from the link above. Why this PR is closed?

**Comment by thepowerfuldeez** [comment]
UPD: found update in main

**Pull request closed without merging**
