### PR TITLE
Fix typo in Llama docstrings

### PR DESCRIPTION
**Pull request by Kh4L**
# What does this PR do?
Fix typos in docs.

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Thanks for fixing! 

Have you run the doc examples locally to confirm they still work and the generated responses are still the same (with the typo fixed)? 

I don't think we can pass in the inputs directly like this, as `generate` expects a tensor as its first argument and `inputs` is a dictionary

**Comment by amyeroberts** [comment]
@Kh4L Out of interest - could you share the checkpoint being used? Could you also run this snippet with the checkpoint and share the output? 

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)
prompt = "Hey, are you conscious? Can you talk to me?"
inputs = tokenizer(prompt, return_tensors="pt")
print(inputs)
print(type(inputs))
print(type(tokenizer))
```

The current changes need to be checked with a standard checkpoint for all the models affected here. For instance, if I run the snippet with the OPT checkpoint in the example

`MODEL_CHECKPOINT = "facebook/opt-350m"`

I get the following output:
```
{'input_ids': tensor([[    2, 13368,     6,    32,    47, 13316,   116,  2615,    47,  1067,
             7,   162,   116]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
<class 'transformers.tokenization_utils_base.BatchEncoding'>
<class 'transformers.models.gpt2.tokenization_gpt2_fast.GPT2TokenizerFast'>
```

**Comment by Kh4L** [comment]
@amyeroberts  Checkpoint is the 7B LLama converted to HF, I get the same output!
Sorry for the confusion, I was using  `LlamaTokenizer`  and not `AutoTokenizer` in my code

**Review by amyeroberts — COMMENTED** [review]
When changing doc examples or tests, it's important to run them to make sure they still pass / the outputs are as expected.

Llama and Open Llama don't have default checkpoints, so can't be checked, but the output for the OPT model does change with the spelling fix so needs to be updated.

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing these! 

The style checks are currently failing - you'll need to run `make style` and push any changes made by the linter. Once the CI is green we can merge :)

**Comment by amyeroberts** [comment]
@Kh4L Github PRs were down for part of yesterday - I think it was just that. I can see the commit now and all tests are passing :)

**Pull request merged**
