### PR TITLE
Speedup torch summarization tests

### PR DESCRIPTION
**Pull request by sshleifer**
Speedup torch summarization tests  by using small models that are faster to download and instantiate.

### CODE REVIEW

**Comment by sshleifer** [comment]
Non slow test speed before change:
image

**Comment by patrickvonplaten** [comment]
There is a tiny TF T5 model now as well via: 
`model = TFAutoModelWithLMHead.from_pretrained("patrickvonplaten/t5-tiny-random")`

**Review by patrickvonplaten — APPROVED** [review]

**Comment by julien-c** [comment]
LGTM, but FYI for context, I think the reason we were using the real models was that we intended to do integration testing: in `_test_mono_column_pipeline` we only test equality of keys but we could have tested equality (or closeness) of values.

**Review by julien-c — APPROVED** [review]

**Comment by sshleifer** [comment]
Makes sense @julien-c .  I'd be happy to add some `@slow` integration tests and try to  fulfill the original intent

**Pull request merged**
