### PR TITLE
Insertion Constraint

### PR DESCRIPTION
**Pull request by massabaali7**
My contribution lies mainly in the constraints class, which is represented in the constrained beam search. It enables conditional token injection in the constrained beam search. The new constraint allows the insertion of one or more tokens from a list of words into the output. Also, you have the ability to not insert anything.  
Example: 
insertfromListOfWords = ["uh","um","exactly", "yes"] 
possible_outputs == [
   "The woman went exactly to school.",
   "um the woman went to um uh school",
 "The woman went to school",
 ]

### CODE REVIEW

**Comment by massabaali7** [comment]
Adding insertion constraint to the contraints class in the constrained beam search.

**Comment by amyeroberts** [comment]
cc @gante

**Comment by massabaali7** [comment]
@amyeroberts @gante did you get the chance to review my code?
Thanks in advance

**Comment by massabaali7** [comment]
I am doing a research and publishing a paper about this. Its a very important idea proposed for backchannel insertion.

**Comment by gante** [comment]
@massabaali7 and we'd be delighted to add it, if the published results show significant improvements. However, we do not add features while they are in a research phase -- that's why we made the whole codebase open to everyone, so you can freely experiment locally 🤗

**Pull request closed without merging**
