### PR TITLE
Add ONNX support for ResNet

### PR DESCRIPTION
**Pull request by regisss**
# What does this PR do?

This PR adds ONNX support for ResNet models. This will enable to export a ResNet to the ONNX format.

It deals with #16308 and continue the work done in #16948 (I didn't see this PR when I opened this one).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by lewtun — COMMENTED** [review]
Thanks for adding this model @regisss! For reference, this PR supersedes https://github.com/huggingface/transformers/pull/16948 which was closed by the author.

I think you just need to run

```
make style && make quality
```

to update the list of supported ONNX models in `serialization.mdx`.

Can you also add a ReNet model from the Hub to the tests and then check they pass with:

```
RUN_SLOW=1 pytest tests/onnx/test_onnx_v2.py -s -k "resnet"
```

If the tolerance isn't sufficient, you can increase `atol` to 1e-3

**Comment by regisss** [comment]
Ah sorry I didn't see this PR. I will refer to it in the description of this one.

Thanks for the review and what I forgot @lewtun, that's very helpful because that's the 1st model I add to our base of ONNX models :) 

I'll be off tomorrow but I'll do all this on Thursday.

**Review by lewtun — APPROVED** [review]
Thanks for iterating on this and adding the tests! LGTM 🚀 

Gently pinging @sgugger for final approval

**Review by sgugger — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
