### PR TITLE
Removed the use of deprecated Variable API in PPLM example

### PR DESCRIPTION
**Pull request by prajjwal1**

### CODE REVIEW

**Comment by prajjwal1** [comment]
Could you please tell what does this mean ?
```
#!/bin/bash -eo pipefail
black --check --line-length 119 --target-version py35 examples templates tests src utils

would reformat /home/circleci/transformers/examples/pplm/run_pplm.py
Oh no! 💥 💔 💥
1 file would be reformatted, 266 files would be left unchanged.

Exited with code exit status 1
```
Before committing, I ran black on this script.

**Comment by julien-c** [comment]
You need to run `make style` and `make quality` locally and push the resulting changes

**Comment by julien-c** [comment]
Also this file was moved around so you'll need to re-apply your changes to new location

**Comment by prajjwal1** [comment]
I ran both make commands as you said.
```
(base) u37216@s001-n007:~/transformers$ make style
black --line-length 119 --target-version py35 examples templates tests src utils
reformatted /home/u37216/transformers/src/transformers/__init__.py
reformatted /home/u37216/transformers/templates/adding_a_new_example_script/run_xxx.py
reformatted /home/u37216/transformers/templates/adding_a_new_example_script/utils_xxx.py
All done! ✨ 🍰 ✨
3 files reformatted, 272 files left unchanged.
isort --recursive examples templates tests src utils
Fixing /home/u37216/transformers/templates/adding_a_new_example_script/run_xxx.py
Fixing /home/u37216/transformers/templates/adding_a_new_example_script/utils_xxx.py
Fixing /home/u37216/transformers/src/transformers/__init__.py
(base) u37216@s001-n007:~/transformers$ make quality
black --check --line-length 119 --target-version py35 examples templates tests src utils
would reformat /home/u37216/transformers/src/transformers/__init__.py
would reformat /home/u37216/transformers/templates/adding_a_new_example_script/run_xxx.py
would reformat /home/u37216/transformers/templates/adding_a_new_example_script/utils_xxx.py
Oh no! 💥 💔 💥
3 files would be reformatted, 272 files would be left unchanged.
Makefile:6: recipe for target 'quality' failed
make: *** [quality] Error 1
```

**Comment by prajjwal1** [comment]
@julien-c Can you please see this ?

**Comment by prajjwal1** [comment]
@LysandreJik Can you please see this ?

**Pull request closed without merging**
