### PR TITLE
Rename test_feature_extraction files

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Renames the tests for image processors: `test_feature_extraction_xxx.py` -> `test_image_processing_xxx.py`

A follow up PR will change the feature extractor references to equivalent image processor ones in the files. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by ydshieh** [comment]
Thank you @amyeroberts !

I think there are a few lines in `tests/utils/test_add_new_model_like.py` to be changed, like

https://github.com/amyeroberts/transformers/blob/6b10c045e259a47f3786ceb11089fe418828346e/tests/utils/test_add_new_model_like.py#L62

**Comment by amyeroberts** [comment]
@ydshieh Done!

**Review by ydshieh — APPROVED** [review]
Thanks 💯

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Pull request merged**
