### PR TITLE
Add unpack_input decorator to ViT model

### PR DESCRIPTION
**Pull request by johnnv1**
# What does this PR do?
I added the unpack_input decorator for the ViT model as describe in #16051 

@gante 

Maybe can also delete the `**kwargs` from `call` parameters?  (tests seems unaffected)

### CODE REVIEW

**Review by gante — APPROVED** [review]
Fantastic, thank you so much for the contribution 👍

Can you confirm that you've run RUN_SLOW=1 py.test -vv tests/[model_name]/test_modeling_tf_[model_name].py? Will merge after your confirmation :)

**Comment by gante** [comment]
> Maybe can also delete the **kwargs from call parameters? (tests seems unaffected)

That's a good point. Actually, I think this will be true for all models after this change. Do you mind if I add it to my backlog, to confirm after this sprint? If we were to change this, I would have to bring in other Hugging Face members in (changing the signature of a public method is sensitive).

**Comment by debtriche** [comment]
STOP EMAILING ME!!!!!!!!!!!!!!!!!!!!!!

**Comment by gante** [comment]
Hi @debtriche 👋 GitHub doesn't send random emails, if you are receiving unwanted emails please check your subscription and emailing settings :)

**Comment by johnnv1** [comment]
> Fantastic, thank you so much for the contribution +1
> 
> Can you confirm that you've run RUN_SLOW=1 py.test -vv tests/[model_name]/test_modeling_tf_[model_name].py? Will merge after your confirmation :)

Yes, i run, but two test are skipped, all others pass

**Pull request merged**
