### PR TITLE
Add type hints for PyTorch UniSpeech, MPNet and Nystromformer

### PR DESCRIPTION
**Pull request by daspartho**
Based on the issue https://github.com/huggingface/transformers/issues/16059
@Rocketknight1 could you please take a look at it?
Thanks :)

### CODE REVIEW

**Comment by Rocketknight1** [comment]
Hi @daspartho, thanks for this! There's one problem, though - one of the functions you added type hints to was marked as `copied from` another function. This caused the `check_repository_consistency` test to fail. If you check the details on that test, the problem is that those functions were copied from `Wav2Vec2Encoder` and `Wav2Vec2EncoderStableLayerNorm`. If you add type hints to those `Wav2Vec2` functions and then finally run `make fix-copies` that should resolve this!

**Comment by daspartho** [comment]
Hello, @Rocketknight1
I did as you suggested but more copy inconsistencies arised, could you assist me with this?

**Comment by Rocketknight1** [comment]
Hi @daspartho, I think running `make fix-copies` in the root directory of the repo should fix this! If it's not working for you, let me know and I'll run it for you - just make sure the PR is set to allow commits from maintainers.

**Comment by daspartho** [comment]
Hi, @Rocketknight1. I tried running it but I'm not sure why it's not working; could you please run it for me?

**Comment by Rocketknight1** [comment]
@daspartho Done! Double-check the changes and make sure you're happy with them, and I'll merge once you are.

**Comment by daspartho** [comment]
@Rocketknight1 I've checked the changes and I'm happy with them. Thank you very much!

**Review by Rocketknight1 — APPROVED** [review]

**Pull request merged**
