### PR TITLE
Change ProgressCallback to use dynamic_ncols=True

### LINKED ISSUE #24100: [Trainer] Why not use tqdm's dynamic_ncols option?
### Feature request

# Problem

Tqdm progress bar is getting ugly when the width of the terminal is shrunk!

image

It progress bar makes the new line on every update! It is very ugly...

# Solution

Simply add the `dynamic_ncols=True` option to `tqdm`. It is located in `trainer_callbacks.ProgressCallback`.

image

You can check the progress bar is now dynamically resized when the terminal size is updated.

### Motivation

When I connect `tmux` session with different widths of the terminal, then the `tqdm` printing is getting ugly.

### Your contribution

I will make PR

### PR DESCRIPTION
**Pull request by gmlwns2000**
# What does this PR do?

Fixes #24100 

## Who can review?

This is about the trainer module, therefore I will tag,

@sgugger

Thank you

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for your contribution! Can you just run `make style` on your branch to fix the formatting?

**Comment by sgugger** [comment]
Mm the diff now shows 43 files. COuld you limit your changes to the file you are actually modifying?

**Comment by gmlwns2000** [comment]
@sgugger 

Sorry for the late reply, and it looks fine now!

**Comment by sgugger** [comment]
Thanks! Failures are unrelated and due to a down time on the Hub.

**Pull request merged**
