### PR TITLE
Fixes #1263, add tokenization_with_offsets, gets tokens with offsets in the original text

### LINKED ISSUE #1263: Offsets in original text from tokenizers
## 🚀 Feature

A new method for tokenizers: tokenize_with_offsets. In addition to returning the tokens, it returns the spans in the original text that the tokens correspond to.
After
tokens, offsets = tokenizer.tokenize_with_offsets(text)
then
tokens[i] maps to text[offsets[i, 0]:offsets[i, 1]]

## Motivation

I find it useful to be able to get the spans in the original text where the tokens come from. This is useful for example in extractive question answering, where the model predicts a sequence of tokens, but the user would like to see a highlighted passage.

## Additional context

I have a version of this in a fork: https://github.com/michaelrglass/pytorch-transformers
There is a test (regression_test_tokenization_with_offsets) that verifies the tokenization with offsets gives the same tokenization for many models - still working on XLM.
The test data I used is available from https://ibm.box.com/s/228183fe95ptn8eb9n0zq4i2y7picq4r

Since this touches several files, and works for the majority (but not all) of the tokenizers, I thought creating an issue for discussion would be better than an immediate pull request.

### PR DESCRIPTION
**Pull request by michaelrglass**
This is similar to the utils_squad approach to getting offsets for the tokens but can also be used in other places where the tokens should have a correspondence to the original text to fix #1263.

### CODE REVIEW

**Comment by thomwolf** [comment]
I think this is an interesting addition and I like the way the PR is structured in general.

Before I dive in could you want to lay down the status of the PR in terms of supported models, python version (we will still keep python 2 support for now), know issues and TO-DOs?

**Comment by michaelrglass** [comment]
The fully supported models are BERT, GPT2, XLNet, and RoBERTa. For these models tokenize_with_offsets always produces the same tokens as tokenize and the subword tokens are well-aligned to the original text, typically as well as possible.

XLM has a known issue with patterns like '... inc. reported ...'
tokxlm.tokenize_with_offsets('inc. reported')
['inc</w>', '.</w>', 'reported</w>']
tokxlm.tokenize('inc. reported')
['inc.</w>', 'reported</w>']
Because tokenize_with_offsets passes whitespace separated 'chunks' (utils_squad style) the xlm tokenizer doesn't get to look ahead to see that a lowercase word follows the period.

TransfoXL just needs the latest commit (not in this PR), while OpenAIGPT has an issue with '\n</w>' tokens, which tokenize_with_offsets never produces.

Everything works in Python 2 except GPT2 (and therefore RoBERTa) as well as XLNet. I think this is the case even without this PR. I'm not experienced with Python 2 though, so maybe I am just missing something.

**Comment by tomhosking** [comment]
Would love to see this feature available - what can I do to help get it merged in?

**Comment by thomwolf** [comment]
We are currently working on a larger project around this and should come to this PR pretty soon (next week I hope).

**Comment by tomhosking** [comment]
@michaelrglass How does this handle the destructive normalisation that occurs in eg BertTokenizer? Specifically, logic like [this](https://github.com/huggingface/transformers/blob/master/transformers/tokenization_bert.py#L330) means that the normalisation isn't length preserving, and it may not be possible to find the (normalised) token in the original input text.

**Comment by tavianator** [comment]
> @michaelrglass How does this handle the destructive normalisation that occurs in eg BertTokenizer? Specifically, logic like [this](https://github.com/huggingface/transformers/blob/master/transformers/tokenization_bert.py#L330) means that the normalisation isn't length preserving, and it may not be possible to find the (normalised) token in the original input text.

IMO it's too error-prone to run a destructive tokenizer and then try to align the sequences after the fact.  I wrote https://github.com/microsoft/bistring for this exact kind of problem.  Otherwise it's very tricky to align substrings of the modified text with the original text, as both NFD and filtering out nonspacing marks can shift the positions of chars significantly.

**Comment by eladsegal** [comment]
@michaelrglass can you please reupload the test data?
tokenize_offset_test_data.jsonl at https://ibm.box.com/s/228183fe95ptn8eb9n0zq4i2y7picq4r is not available

**Pull request closed without merging**
