### PR TITLE
cleanup torch unittests

### LINKED ISSUE #5973: [cleanup] much cruft in unittests
Anti patterns:
- making a result dict and then using each of it's keys. Why use the dict?
- delete all mentions of `check_loss_output`
- use tuple equality: `self.assertEqual(tensor.shape, (bs, seq_len)` instead of 
```python
self.assertListEqual(list(tensor.size()), [bs, seq_len])
```

This does not need to be done for all test files at once.

fix `templates/testing_xxx ` to reflect the new best practice.

### PR DESCRIPTION
**Pull request by stas00**
a large group of tests has been modified according to the request in https://github.com/huggingface/transformers/issues/5973

If this is what's needed then just running this magic perl sequence should take care of most of them:

```
perl -pi -e 's|^\s+self.check_loss_output\(result\)\n||' tests/test_modeling_bert.py

perl -0777 -pi -e 's|^\s+def check_loss_output\(self, result\):[\s\n]+       self.parent.assertListEqual\(list\(result\["loss"\].size\(\)\), \[]\)\s*\n|\n|msg' tests/test_modeling_bert.py

perl -0777 -pi -e 's#self.parent.assertListEqual\(
[\s\n]*
list\((result\w*)\[" ([^"]+) "\].(?:shape|size\(\))\),[\s\n]+\[ ( [^\]]* ) \],?
[\s\n]*
\)
#self.parent.assertEqual($1.$2.shape, ($3))#xmsg' tests/test_modeling_bert.py
```
(edit, adjusted for multiple various inputs)

well, add:
```
make style
```
to fix the style.

problem: not all results are objects, some are plain `dict` and can't be called with .key_name. See my comment below.

@sshleifer

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM, thanks @stas00 for the PERL magic!

**Comment by stas00** [comment]
I added one more `check_loss_output` that was missing, no changes otherwise.

CI is randomly failing again...

**Review by sshleifer — APPROVED** [review]
LGTM!

**Review by LysandreJik — APPROVED** [review]
Great, LGTM. Thanks for taking care of it @stas00!

**Comment by LysandreJik** [comment]
Re-ran the test suite and everything passes. The tests should be less flaky after merging https://github.com/huggingface/transformers/pull/6234.

**Pull request merged**
