### PR TITLE
fix wrong path in some doc

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

The examples use a path this is (likely) moved to the current one some time ago. Let's update those.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Do you want to remove them from  `no_doctest.txt`? 👀 to have a preview

**Comment by ydshieh** [comment]
can give it a try!

**Comment by ydshieh** [comment]
It passes, but doctest doesn't really run any test from that doc file. (nothing is collected)

**Review by ArthurZucker — APPROVED** [review]
Thanks for the fix, guessing no tests are run because there is no python code ? (If I remember correctly)

**Comment by ydshieh** [comment]
Most of them are `bash`. Some are `python`, but as `python no-style`. There is a single block with `python`, but that is not really to be tested as a doc string example.

I didn't check the regular expression to see why those python-related blocks are not tested.

**Comment by ydshieh** [comment]
It's probably that file has `cuda`, and for `md` file, if a `cuda` shows up, all the tests in that file won't be collected (by the new logic of doc test you and me implemented)

**Pull request merged**
