### PR TITLE
Remove unnecessary unsqueeze - squeeze in rotary positional embedding

### LINKED ISSUE #109292: aten::squeeze exported to ONNX as an `If` node
### 🐛 Describe the bug

Hi,

I am exporting to ONNX llama from transformers implementation, and don't understand why `If` nodes are inserted for the export of this `squeeze` operator, where the first dims are always of shape `1` and `1`: https://github.com/huggingface/transformers/blob/7c63e6fc8c34dcf8b0121eaee776f41ccf3b1137/src/transformers/models/llama/modeling_llama.py#L182

It appears we are going into this path: https://github.com/pytorch/pytorch/blob/b6a1d3fb97ca8eeccf15a4c495fdd1af4b197f88/torch/onnx/symbolic_opset11.py#L937

because the symbolic helper `_get_tensor_sizes` give us [here](https://github.com/pytorch/pytorch/blob/b6a1d3fb97ca8eeccf15a4c495fdd1af4b197f88/torch/onnx/symbolic_helper.py#L578) `x_type.varyingSizes() = [None, None, None, None]` .

Is there a way to hint that the shapes are constant hard-coded to `1`? The intermediate captured graph is (the aten::sub is not in the original code base - added for debugging):

```
  %4407 : Float(1, 1, 17, 4, strides=[68, 68, 4, 1], requires_grad=0, device=cpu) = aten::sub(%cos.1, %4405, %4406), scope: transformers.models.llama.modeling_llama.LlamaForCausalLM::/transformers.models.llama.modeling_llama.LlamaModel::model/transformers.models.llama.modeling_llama.LlamaDecoderLayer::layers.0/transformers.models.llama.modeling_llama.LlamaAttention::self_attn # /home/fxmarty/hf_internship/transformers/src/transformers/models/llama/modeling_llama.py:183:0
  %4408 : int = prim::Constant[value=1](), scope: transformers.models.llama.modeling_llama.LlamaForCausalLM::/transformers.models.llama.modeling_llama.LlamaModel::model/transformers.models.llama.modeling_llama.LlamaDecoderLayer::layers.0/transformers.models.llama.modeling_llama.LlamaAttention::self_attn # /home/fxmarty/hf_internship/transformers/src/transformers/models/llama/modeling_llama.py:185:0
  %4409 : Float(1, 17, 4, strides=[68, 4, 1], requires_grad=0, device=cpu) = aten::squeeze(%4407, %4408), scope: transformers.models.llama.modeling_llama.LlamaForCausalLM::/transformers.models.llama.modeling_llama.LlamaModel::model/transformers.models.llama.modeling_llama.LlamaDecoderLayer::layers.0/transformers.models.llama.modeling_llama.LlamaAttention::self_attn # /home/fxmarty/hf_internship/transformers/src/transformers/models/llama/modeling_llama.py:185:0
```

A workaround is to use `cos = cos[0, 0]` - wondering if there is anything better.

Thank you!

cc @justinchuby 

### Versions

torch 2.0.1, opset_version = 12

### PR DESCRIPTION
**Pull request by fxmarty**
As per title, removes unnecessary operations in the model initialization and forward.

Fixes https://github.com/pytorch/pytorch/issues/109292

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
LGTM - thanks for fixing!

**Review by ArthurZucker — APPROVED** [review]
Thanks, wondering why we have this in the first place now. 
Make sure to also apply this to GPTNeoX and anywhere that has the same logic but no copied from 😉

**Comment by ArthurZucker** [comment]
FYI @gante if there is anything we are missing here?

**Comment by fxmarty** [comment]
There's the same unsqueeze - squeeze in falcon. Maybe I am misunderstanding something in rotary positional embedding.

**Comment by ArthurZucker** [comment]
Yep it's unrelated, seen this failing, the `fast` tokenizer is not properly splitting

**Comment by fxmarty** [comment]
Updated other affected archs.

This PR https://github.com/huggingface/transformers/pull/22785 was great, but incomplete. cc @fpgaminer

**Review by ArthurZucker — APPROVED** [review]
Good for me but let's wait for #25830 to be merged first! Also `make fix-copies` and `make fixup` 😉

**Comment by fxmarty** [comment]
Do you think this can make it in the release?

**Comment by ArthurZucker** [comment]
If the checks are green yes 😓

**Review by ArthurZucker — COMMENTED** [review]
Make sure to rebase for the changes applied to GPTNeox and Idefics

**Comment by fxmarty** [comment]
sure

**Comment by fxmarty** [comment]
Should be in a good state now.

Summary of slow tests:

`RUN_SLOW=1 CUDA_VISIBLE_DEVICES=0 pytest tests/models/llama/ -s -vvvvv` errors on (same as main)

```
FAILED tests/models/llama/test_modeling_llama.py::CodeLlamaIntegrationTest::test_model_7b_logits
E       AssertionError: Lists differ: ['<s>▁<PRE> def remove_non_ascii(s: str) -> st[893 chars]ID>'] != ['<s> <PRE> def remove_non_ascii(s: str) -> st[893 chars]ID>']
```

`RUN_SLOW=1 CUDA_VISIBLE_DEVICES=0 pytest tests/models/idefics/ -s -vvvvv` errors on (same as main)

```
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsModelTest::test_cpu_offload - AssertionError: False is not true
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsModelTest::test_determinism - ValueError: zero-size array to reduction operation maximum which has no identity
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsModelTest::test_disk_offload - AssertionError: False is not true
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsModelTest::test_feed_forward_chunking - AssertionError: False is not true
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsForVisionText2TextTest::test_cpu_offload - AssertionError: False is not true
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsForVisionText2TextTest::test_determinism - ValueError: zero-size array to reduction operation maximum which has no identity
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsForVisionText2TextTest::test_disk_offload - AssertionError: False is not true
FAILED tests/models/idefics/test_modeling_idefics.py::IdeficsForVisionText2TextTest::test_feed_forward_chunking - AssertionError: False is not true
```

`RUN_SLOW=1 CUDA_VISIBLE_DEVICES=0 pytest tests/models/mistral/ -s -vvvvv` errors on (same as main)

```
FAILED tests/models/mistral/test_modeling_mistral.py::MistralIntegrationTest::test_model_7b_generation - AssertionError: 'My f[17 chars]t is mayonnaise. I love it on sandwiches, in s[13 chars]gers' != 'My f[17 chars]t is 100% ketchup. I love it on everythin...
FAILED tests/models/mistral/test_modeling_mistral.py::MistralIntegrationTest::test_model_7b_logits - RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index ...
```

`RUN_SLOW=1 CUDA_VISIBLE_DEVICES=0 pytest tests/models/falcon/ -s -vvvvv` errors on (same as main)

```
FAILED tests/models/falcon/test_modeling_falcon.py::FalconModelTest::test_left_padding_compatibility - AssertionError: False is not true
```

`RUN_SLOW=1 CUDA_VISIBLE_DEVICES=0 pytest tests/models/gpt_neox/ -s -vvvvv` pass.

**Comment by fxmarty** [comment]
This PR fixes `tests/models/mistral/test_modeling_mistral.py::MistralIntegrationTest::test_model_7b_logits` as well. 

`tests/models/mistral/test_modeling_mistral.py::MistralIntegrationTest::test_model_7b_logits` seem to have never worked (on 72958fcd3c98a7afdc61f953aa58c544ebda2f79) cc https://github.com/huggingface/transformers/pull/26447 (slow tokenizers) @Bam4d, so I will ignore it for now.

**Review by ArthurZucker — APPROVED** [review]
Thanks a lot! Good to go 😉

**Comment by gante** [comment]
@fxmarty thank you for the fix! 

I suppose this redundant pattern got in `gpt_neox`, and we were copying it over to other new models with RoPE :)

**Pull request merged**
