### PR TITLE
Remove deprecated

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR removes old deprecated arguments and adjust tests/examples accordingly.
Co-authored with @LysandreJik.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Great work guys

**Comment by Tomas0413** [comment]
Hi, I noticed that https://github.com/huggingface/transformers/blob/master/examples/token-classification/run_ner_old.py#L294 and https://github.com/huggingface/transformers/blob/master/examples/token-classification/run_ner_old.py#L302 are still referencing is_world_master() instead of using is_world_process_zero(). I have made a change to run_ner_old.py locally and running the process again to see if it fixes the issue for me (AttributeError: 'Trainer' object has no attribute 'is_world_master')

**Comment by sgugger** [comment]
We're not actively maintaining the old examples scripts anymore and they're still there for people using older versions of transformers. The good fix would be to add a minimum version to the README of that example.

**Comment by stas00** [comment]
I'm at loss here - which ones are old examples and which ones are new?

https://github.com/huggingface/transformers/issues/8792

**Comment by stas00** [comment]
If there should be an old version of something to be used with an old version of something - why not send users to the branch of that release that they want to use - they will end up with the version of examples that works for that release. and master examples should be working with master version of the code.  Does it make sense?

**Comment by sgugger** [comment]
Yes it all makes sense. Please be patient while I clean up the examples folder, as it's a long work. I promise this will all be clean when I'm done :-)

**Pull request merged**
