### PR TITLE
[Whisper] Remove embed_tokens from encoder docstring

### PR DESCRIPTION
**Pull request by sanchit-gandhi**
# What does this PR do?

`embed_tokens` is not an arg for the `WhisperEncoder`. It looks like it was copied from BART (where we do use it) and left in by mistake!
https://github.com/huggingface/transformers/blob/9402788b34fbc6581ae9d7d9d68612a96d9aa111/src/transformers/models/bart/modeling_bart.py#L708

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Review by ArthurZucker — APPROVED** [review]
LGTM

**Comment by ydshieh** [comment]
@sanchit-gandhi 

For trigger CI, you can do sth like `git commit --allow-empty -m "Empty commit to trigger CI"`
(in the future when you need it)

**Comment by sanchit-gandhi** [comment]
Thanks for the tip @ydshieh! Looks the CI is red on main due to a `500 Server Error` with the HF Hub, see https://github.com/huggingface/transformers/actions/runs/4392426382/jobs/7692183097.

**Comment by ydshieh** [comment]
I re-run that CI job and it is green now :-)

The failed test in the job `test_tf` is irrelevant to this PR I believe.

**Comment by sanchit-gandhi** [comment]
Amazing, thanks @ydshieh! 🙌

**Pull request merged**
