### PR TITLE
Add ProtBert model card

### PR DESCRIPTION
**Pull request by agemagician**
This is a model card for our ProtBert:
https://huggingface.co/Rostlab/prot_bert

### CODE REVIEW

**Comment by agemagician** [comment]
Any idea why there is one failed test case ?
I have checked the code on the notebook and it runs without any issue on Colab.

**Comment by LysandreJik** [comment]
This seems completely unrelated, just relaunched the failed test.

**Review by JetRunner — APPROVED** [review]

**Comment by julien-c** [comment]
Hi @agemagician, your model https://huggingface.co/Rostlab/prot_bert is not recognized by our Hosted inference API, probably because it doesn't have a `architectures` field in its config.json:

Screenshot 2020-10-21 at 21 52 57


Do you mind if we update the config.json on the model hub? Alternatively, do you prefer doing it yourself?

Thanks!

**Comment by agemagician** [comment]
Hi @julien-c  , No problem.
I already have seen you updated it.

However, it doesn't work properly because we don't lower case tokens:
https://huggingface.co/Rostlab/prot_bert?text=A+T+G+%5BMASK%5D+C

I have uploaded the "tokenizer_config.json" file which should fix it but, we have to wait until the model is no longer in memory.

I have also did the same for our better bert model "prot_bert_bfd", and it is working fine:
https://huggingface.co/Rostlab/prot_bert_bfd?text=A+T+G+%5BMASK%5D+C

Thanks for your help.

**Comment by julien-c** [comment]
Now properly loaded, and looks great!

https://huggingface.co/Rostlab/prot_bert?text=D+L+I+P+T+S+S+K+V+V+%5BMASK%5D+D+T+S+L+Q+V+K+K+A+F+F+A+L+V+T

Screenshot 2020-10-21 at 22 56 44

Thanks a lot @agemagician

**Pull request merged**
