### PR TITLE
[Doctest] - Fixing doctest `configuration_pegasus_x.py`

### LINKED ISSUE #19487: 🔥[Community Event] Doc Tests Sprint - Configuration files🔥
This sprint is similar to #16292 - but for model **configuration files**, i.e. `configuration_[model_name].py`.
For example, `src/transformers/models/bert/configuration_bert.py` 

# The expected changes

The changes we expect  could be find #19485:

  1. **Change the import order of the model and configuration classes**
  2. **Add `(with random weights)` in the  comment before model initialization line**
  3. **Add `configuration_[model_name].py` to `utils/documentation_tests.txt`** (respecting the order)

Please do step 3. only after **Running the doctest and make sure all tests pass** (see below) 🙏 

# How to run doctests

Suppose you are working on `src/transformers/models/bert/configuration_bert.py`. The steps to run the test are:

0. **Stage your changes**

    ```bash
    git add src/transformers/models/bert/configuration_bert.py
    ```
1. **Prepare the files to be tested**

    ```python
    python utils/prepare_for_doc_test.py src
    ```
    or if you prefer to be more specific 
    ```python
    python utils/prepare_for_doc_test.py src/transformers/models/bert/configuration_bert.py
    ```
    This will change some files (doc-testing needs to add additional lines that we don't include in the doc source files).
2. **Launch the test:**
    ```python
    python -m pytest --doctest-modules src/transformers/models/bert/configuration_bert.py -sv --doctest-continue-on-failure
    ```
3. **Cleanup git status**
    ```bash
    git checkout -- .
    ```
    to clean up the changes in step 1.

# Ready (or not)?

If all tests pass, you can commit, push and open a PR 🔥 🚀 , otherwise iterate the above steps 💯 !

### PR DESCRIPTION
**Pull request by mukesh663**
# What does this PR do?
Fixes #19487 
Added (with random weights) in `configuration_pegasus_x.py`.
Added `configuration_pegasus_x.py` in `documentation_tests.txt`.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@ydshieh

### CODE REVIEW

**Comment by ydshieh** [comment]
Hi @mukesh663 There seems to be some CI issue. Could you push again with an empty commit?

You can do `git commit --allow-empty` then push :pray.

**Review by ydshieh — APPROVED** [review]
Nice!

**Review by ydshieh — APPROVED** [review]

**Comment by ydshieh** [comment]
Hi, @mukesh663 I haven't merge your PR yet ...but you already closed the PR and delete the branch 😢

**Comment by ydshieh** [comment]
Are you able to restore the branch ?

**Comment by mukesh663** [comment]
> Are you able to restore the branch ?

@ydshieh Sorry for the mishap. I have restored the branch.

**Comment by ydshieh** [comment]
Merged, thank you again!

**Pull request merged**
