### PR TITLE
[`trainer`] fix the GA `model_accepts_loss_kwargs`

### LINKED ISSUE #34577: Mismatched keyword argument names of llama make GA fix invalid
### System Info

- Transformers 4.47.0.dev0 (latest commit 33868a057c02f0368ba63bd1edb746be38fe3d90)

### Who can help?

@ArthurZucker @muellerzr 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/pull/33932 may breaks the logic for the trainer's `model_accepts_loss_kwargs`. The llama model would not receive a `num_items_in_batch` argument, making the fix of https://github.com/huggingface/transformers/pull/34283 invalid again

https://github.com/huggingface/transformers/blob/33868a057c02f0368ba63bd1edb746be38fe3d90/src/transformers/trainer.py#L605

Moreover, the names of keyword arguments are different for llama and other models, we might expect the same keyword arguments for different models.

https://github.com/huggingface/transformers/blob/33868a057c02f0368ba63bd1edb746be38fe3d90/src/transformers/models/llama/modeling_llama.py#L1146-L1161

https://github.com/huggingface/transformers/blob/33868a057c02f0368ba63bd1edb746be38fe3d90/src/transformers/models/gemma/modeling_gemma.py#L1015-L1030

### Expected behavior

The models' forward functions should have a consistent keyword argument list.

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Fixes #34577
`model_accepts_loss_kwargs` was wrongly looking at kwarg names, while you should only need kwargs (since the name can vary for FlashAttentionKwargs, LossKwargs etc)

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
TIL! However, as you can see by the failing test, this doesn't always work 😅 (If we can get it to that's great, I think that's originally why I went with explicit rather than implicit)

**Comment by techkang** [comment]
I think this pr introduced a new bug that if user use user defined loss funcion and `model_accepts_loss_kwargs` is `False`, `compute_loss` function cannot get the `num_items_in_batch` argument. Finally, user defined compute_loss_func will not receive this argument either.

**Comment by ArthurZucker** [comment]
`model_accepts_loss_kwargs` is supposed to be determined at init time and only depends on the forward pass of the model

**Comment by techkang** [comment]
I understand now, I misinterpreted the if condition earlier. However, in this PR, when model_accepts_loss_kwargs is True, it won't pass the num_items_in_batch parameter, which would make the GA loss modification functionality ineffective. Why is that?

**Comment by techkang** [comment]
In newest code, run
```
export RUN_SLOW=True
pytest tests/trainer/test_trainer.py::TrainerIntegrationPrerunTest::test_gradient_accumulation_loss_alignment
```
will cause error:
```
======================================================= short test summary info =======================================================
FAILED tests/trainer/test_trainer.py::TrainerIntegrationPrerunTest::test_gradient_accumulation_loss_alignment - AssertionError: 0.9038000000000004 not less than 0.1 : Difference -0.9038000000000004 is not within 0.1
============================================== 1 failed, 2 warnings in 102.43s (0:01:42) ==============================================
```

**Comment by ArthurZucker** [comment]
Ah shit the if condition is reversed

**Comment by ArthurZucker** [comment]
Opened a PR for a fix, thanks!

**Pull request merged**
