### PR TITLE
Fix: Rename keyword argument in_channels to num_channels

### PR DESCRIPTION
**Pull request by ningyuv**
# What does this PR do?

Fixes keyword argument in_channels to num_channels

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @nielsrogge since (I think?) you worked on those models!

**Review by ningyuv — COMMENTED** [review]
keyword argument name in [SwinConfig](https://github.com/huggingface/transformers/blob/75be5a0a5b1898ee86e5e0c1f7b58b77bb105101/src/transformers/models/swin/configuration_swin.py#L115) is `num_channels`

**Review by NielsRogge — APPROVED** [review]
Thanks for fixing!

**Review by LysandreJik — APPROVED** [review]
Thank you!

**Pull request merged**
