### PR TITLE
Pin rouge_score

### PR DESCRIPTION
**Pull request by albertvillanova**
# What does this PR do?

Temporarily pin `rouge_score` (to avoid latest version 0.7.0) until the issue is fixed on their side:
- https://github.com/google-research/google-research/issues/1212

See:
- https://github.com/huggingface/datasets/issues/4734

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hey @albertvillanova, sorry for missing this! Should this be merged? Should we replace by `!=0.7.0` so that we're still compatible with newer versions?

**Comment by albertvillanova** [comment]
They made several failed releases until they got to fix the error... Let me update this PR with all the versions to be avoided.

**Review by LysandreJik — APPROVED** [review]
That's a lot of incompatibilities :sweat_smile: 

Feel free to merge when happy @albertvillanova, thanks for your PR!

**Comment by albertvillanova** [comment]
@LysandreJik there is a non-passing test though...

**Comment by LysandreJik** [comment]
Hmmm weird, it seems like it passed when it was <0.07 [here](https://github.com/huggingface/transformers/runs/7464301285?check_suite_focus=true) (installing version v0.0.4), but not after setting `rouge-score!=0.0.7,!=0.0.8,!=0.1,!=0.1.1` (installing version 1.2.0).

I see that when installing `rouge-score` version v1.2.0, it was installing `rouge-score` using a legacy approach:
```
Using legacy 'setup.py install' for rouge-score, since package 'wheel' is not installed.
```

Could this be the cause of the failure? If you put `<0.7` once again, does it pass the test?

**Comment by albertvillanova** [comment]
The test does not pass either with previous `rouge-score<0.0.7`, @LysandreJik.

**Review by LysandreJik — APPROVED** [review]
The error was fixed on `main`, so let's merge it like that!

**Pull request merged**
