### PR TITLE
Change JSON serialization to custom json.dumps

### PR DESCRIPTION
**Pull request by junrae6454**
# What does this PR do?
* This PR modifies the apply_chat_template function to improve handling of non-ASCII characters in JSON output by setting ensure_ascii to False. This change ensures that characters such as "안녕?" and emojis are correctly rendered in their original form rather than as escaped sequences.
* In the original tojson implementation of Jinja2, the characters "<", ">", "&", and "'" are escaped to ensure safe HTML output. However, in apply_chat_template, we use json.dumps directly to preserve the original content as much as possible.
[jinja2 default tojson](https://github.com/pallets/jinja/blob/8710cabd4fc58e38d1a83da3ed2d07e861d8bcdd/src/jinja2/utils.py#L657C12-L663)

# relative issue
https://github.com/huggingface/transformers/pull/31041
https://github.com/huggingface/transformers/pull/31079

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
- I think @Rocketknight1, @CISC would be a good choice for review.

### CODE REVIEW

**Comment by CISC** [comment]
Yes, this makes sense, didn't catch the escaping of HTML characters.

May I suggest also removing the `sort_keys` parameter so it goes back to the default of not sorting keys, this way the caller has control over the order, which can improve inference.

**Comment by junrae6454** [comment]
@Rocketknight1 
When you have a moment, could you please review my latest pull request? Your feedback would be greatly appreciated.

**Comment by Rocketknight1** [comment]
Sorry for the delay! This makes sense to me, however there is a risk of affecting other Jinja implementations. @xenova how does `huggingface/jinja` deal with `|tojson`?

**Comment by CISC** [comment]
@Rocketknight1 AFAICT `huggingface.js/jinja` doesn't support `tojson` filter.

**Comment by xenova** [comment]
No, not yet, but it should be really easy to implement!

**Comment by Rocketknight1** [comment]
Okay! In that case, pinging @amyeroberts for core maintainer review.

Brief summary: We often want to flatten lists/dicts into a string in a chat template, especially when it deals with tools. Jinja was originally designed for templating in webpages, and as a result it escapes special HTML characters by default, but this is not what we want in a chat template. This PR swaps the default `tojson` filter in Jinja for Python's `json.dumps()` function, which doesn't have this awkward feature.

**Review by Rocketknight1 — APPROVED** [review]

**Review by amyeroberts — APPROVED** [review]
SGTM - thanks for updating!

**Pull request merged**
