### PR TITLE
Remove assertion over possible activation functions in DistilBERT

### PR DESCRIPTION
**Pull request by mfuntowicz**
Remove old code remaining in DistilBERT preventing the use of alternative activation functions.

### CODE REVIEW

**Comment by mfuntowicz** [comment]
Failures look unrelated to this PR, let me know if there is anything to be done on my side 👍🏻

**Review by LysandreJik — COMMENTED** [review]
Looks good! Do similar changes need to happen in the TF/Flax versions?

**Comment by mfuntowicz** [comment]
Good point, updated both codebase.

**Review by sgugger — APPROVED** [review]
Thanks for working on this!

**Pull request merged**
