### PR TITLE
Fix translation no_trainer

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

This PR fixes the reason translation has been failing, by adding in the same `num_beams` that were found to be used in the test.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger, cc @ydshieh

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
The fix is in another test :thinking:

**Review by sgugger — COMMENTED** [review]
But what is this fixing now? If the test worked before...

**Comment by muellerzr** [comment]
@sgugger it hasn't and has been failing for some time, due to the fact `num_beams` was `None` (the default in the CLI), and we need to pass it in. When checking the diff/blame there was not anything explicitly that changed in this file to have this happen, however this is the fix that is needed for the test to pass.

**Comment by sgugger** [comment]
Ah ok, got confused because it's slow.

**Review by sgugger — APPROVED** [review]

**Pull request merged**
