### PR TITLE
Add community notebook for T5 sentiment span extraction

### PR DESCRIPTION
**Pull request by enzoampil**
This is an example notebook that aims to increase the coverage of T5 fine-tuning examples to address #4426 .

This notebook presents a high level overview of T5, its significance for the future of NLP in practice, and a thoroughly commented tutorial on how to fine-tune T5 for sentiment span extraction with an extractive Q&A format.

I recently presented this in a webinar published on [youtube](https://www.youtube.com/watch?v=4LYw_UIdd4A).

### CODE REVIEW

**Comment by LysandreJik** [comment]
Nice webinar, and cool notebook :)

@patrickvonplaten, do you want to take a look?

**Comment by enzoampil** [comment]
Thanks @LysandreJik ! :smile:

**Comment by patrickvonplaten** [comment]
Awesome notebook @enzoampil! 

LGTM for merge!

Which dataset do you use exactly to fine-tune T5 here?

**Comment by enzoampil** [comment]
Thanks @patrickvonplaten ! 😄 

For the dataset, I got it from an ongoing Kaggle competition called [Tweet Sentiment Extraction](https://www.kaggle.com/c/tweet-sentiment-extraction/data).

**The objective is to extract the span from a tweet that indicates its sentiment**

Example input:
```
sentiment: negative
tweet:  How did we just get paid and still be broke as hell?! No shopping spree for me today
```

Example output:
```
broke as hell?!
```

**Comment by enzoampil** [comment]
I was thinking about contributing this to the `nlp` library, but I'm not sure if Kaggle has policies regarding uploading their datasets to other public sources ...

**Comment by patrickvonplaten** [comment]
I see! Yeah no worries - I don't think we currently handle dataset processing from on-going kaggle competition links.

**Pull request merged**
