### PR TITLE
[WIP] Add Theseus Compression

### PR DESCRIPTION
**Pull request by JetRunner**
`transformers.theseus` provides the implementation for BERT-of-Theseus, LayerDrop and Mixout.

Original BERT-of-Theseus authors: @JetRunner @MichaelZhouwang

### CODE REVIEW

**Comment by sshleifer** [comment]
which examples have you tested this with?

**Comment by JetRunner** [comment]
> which examples have you tested this with?

run_glue and run_ner but more to come!

**Comment by JetRunner** [comment]
Want an early review for this? Would be wonderful! @sshleifer

**Comment by stefan-it** [comment]
> run_glue and run_ner but more to come! 

:heart_eyes: can't wait to re-fine-tune all my NER models :hugs:

**Comment by JetRunner** [comment]
Well I've been really busy recently but don't close it for me stalebot!

**Comment by JetRunner** [comment]
Thanks for reopening it @LysandreJik! I was stuck with some details and I'll probably get it done soon.

**Comment by LysandreJik** [comment]
Sounds great, looking forward to it!

**Comment by JetRunner** [comment]
Will move to an independent package. Closing this.

**Pull request closed without merging**
