### PR TITLE
Added Turkish README

### PR DESCRIPTION
**Pull request by KuzeyGorgulu**
**Added the Turkish version to the read.me files.**

- [✅ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [❌] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [❌] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [❌] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [❌] Did you write any new necessary tests?

Hello, @stevhliu @MKhalusova ;
- Can you review my translate document of read.me please? Thank you.

### CODE REVIEW

**Review by stevhliu — COMMENTED** [review]
Nice, thanks for the translation!

We recently moved translated README's to the `i18n` folder. Can you move this file there, and then update the other README's to include your Turkish version?

@merveenoyan, can you take a quick look at the translation please?

**Comment by KuzeyGorgulu** [comment]
Sure, with the last commit i made i updated the other languages for this translate and moved it to the i18n folder.

**Review by merveenoyan — CHANGES_REQUESTED** [review]
üzgünüm ama bizim dokümentasyona açılan çoğu PR machine translation'la açılıyor. bunu biz de yapabiliriz (günün sonunda AI şirketiyiz). kendiniz çevirmediğiniz sürece bu PR'a yorum bırakmayacağım, üzgünüm.

to be inclusive: I will not review any documentation PRs that are created using MT. at the end of the day we are an AI company and we can do this as well, we ask for contributions from humans because MT often doesn't work.

**Comment by KuzeyGorgulu** [comment]
Merhaba,

Geri bildiriminizi anlıyorum. Ancak, birkaç spesifik cümle haricinde (birden fazla kullanımı olabileceğini düşündüğüm noktalar hariç) makine çevirisi kullanmadım. Türkçe, sondan eklemeli bir dil olduğu için elbette kimi noktalarda (özellikle içinde link bulunan cümlelerde) anlam kaymaları olabilir. Ben de çeviriyi mümkün olduğunca doğru ve doğal yapmaya çalıştım.

Makine çevirisi kullanmış olsaydım, birçok farklı dil için bu çeviriyi yapardım ama sadece ana dilimde yapmak istedim. Elbette, bu sizin projeniz ve sizin şirketiniz. İstediğiniz PR'ı merge'lememe konusunda özgürsünüz. 

Teşekkürler,
Kuzey

to be inclusive: I understand, but except for a few specific sentences (where I thought multiple meanings could occur), I did not use machine translation (MT). Turkish is an agglutinative language, so there may be some semantic shifts in certain points (especially in sentences containing links), which I also noticed in other translations (German, French). If I had used MT, I would have translated it into many different languages, but I wanted to do it only in my native language. Of course, this is your project and your company. You are free to merge or not merge any PR you want.

**Comment by merveenoyan** [comment]
Here are some examples of machine-translated texts [here](https://github.com/huggingface/transformers/pull/31592/files#diff-6d094c665122ca4261762735db576ecc9a40fd459f59298fcdd635eb4042ec67R123), [here](https://github.com/huggingface/transformers/pull/31592/files#diff-6d094c665122ca4261762735db576ecc9a40fd459f59298fcdd635eb4042ec67R242) and [here](https://github.com/huggingface/transformers/pull/31592/files#diff-6d094c665122ca4261762735db576ecc9a40fd459f59298fcdd635eb4042ec67R305). The rest of this translation is hard to read. 
We care about readability in any text in the utmost manner, so again, please translate it yourself for future reference.

**Pull request closed without merging**
