### PR TITLE
Resubmit changes after rebase to master

### PR DESCRIPTION
**Pull request by kct22aws**
# What does this PR do?
This PR proposes to add a new section to TorchScript documentation "Deploying HuggingFace TorchScript models on AWS using the Neuron SDK". 

Fixes # issue [14425](https://github.com/huggingface/transformers/issues/14425)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@philschmid , @LysandreJik

### CODE REVIEW

**Comment by kct22aws** [comment]
@philschmid @LysandreJik  I carried over all my work from the previous rst to mdx files per rebase to master. Looking forward to the approval and merge to master branch.

**Comment by kct22aws** [comment]
Hi @LysandreJik @philschmid please review this PR and let me know of any suggestions. Thank you.

**Review by LysandreJik — APPROVED** [review]
Looks good to me, thanks @kct22aws

@philschmid feel free to merge when you approve

**Review by philschmid — APPROVED** [review]
Thank you @kct22aws

**Pull request merged**
