### PR TITLE
Update Bertabs example to work again

### PR DESCRIPTION
**Pull request by MichaelJanz**
Fix the bug 'Attempted relative import with no known parent package' when using the bertabs example. Also change the used model from bertabs-finetuned-cnndm, since it seems not be accessible anymore

### CODE REVIEW

**Review by julien-c — APPROVED** [review]

**Comment by JetRunner** [comment]
There are `remi/bertabs-finetuned-cnndm-extractive-abstractive-summarization` and also `remi/bertabs-finetuned-extractive-abstractive-summarization`. Which should be used here? @sshleifer

**Comment by JetRunner** [comment]
Also #5234

**Comment by MichaelJanz** [comment]
Model remi/bertabs-finetuned-cnndm-extractive-abstractive-summarization did not provide GPU support, which I (newbie) would expect from cnndm prefix.
I had to use remi/bertabs-finetuned-extractive-abstractive-summarization for GPU support.

**Comment by sshleifer** [comment]
Thanks! Circleci wants you to run `make style` I believe.

**Comment by MichaelJanz** [comment]
Ty, will do the next time. Is there a guideline for how to properly set up pull requests? I was not able to find one

**Comment by sshleifer** [comment]
Yes: https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests

**Pull request merged**
