### PR TITLE
Update to include example of LM

### PR DESCRIPTION
**Pull request by iliaschalkidis**
The model files have been updated in order to include the classification layers, based on https://github.com/huggingface/transformers/issues/2901, and now can be also used as a LM.

### CODE REVIEW

**Comment by julien-c** [comment]
[Looks good!](https://huggingface.co/nlpaueb/bert-base-greek-uncased-v1)

**Comment by BramVanroy** [comment]
@julien-c Could you perhaps shed some light on how the TF checkpoints should be uploaded? @iliaschalkidis asked about it here https://github.com/huggingface/transformers/issues/2901#issuecomment-588163505

**Comment by iliaschalkidis** [comment]
In the past for another project, this (`from_pt=True`) did the dirty trick for me:

```python
bert = BERT.from_pretrained(model_path+'pytorch_model.bin',
                                               from_pt=True,
                                               config=BertConfig().from_pretrained(model_path+'config.json'))
```
but I definitely not recommend this...

I have already uploaded the TF checkpoint files (`model_ckpt.data-00000-of-00001`, `model_ckpt.index`, `model_ckpt.meta`) in model's folder, so please feel free to troubleshoot.

**Comment by julien-c** [comment]
see https://github.com/huggingface/transformers/issues/2901#issuecomment-591710959

**Pull request merged**
