### PR TITLE
Fixing class embedding selection in owl-vit

### PR DESCRIPTION
**Pull request by orrzohar**
# What does this PR do?

Fixes # For OWL-ViT image-guided object detection, there is a mistake in selecting the best embedding (the most distinct one with high IoU). Specifically;
selected_inds is a [num_inds, 1] dimensional tensor, where the indexes indicate which queries had a high IoU with target object bbox. But, as selected_inds[0] was selected, only the first of all the possible queries is selected. Specifically, instead of selected_embeddings being a [num_inds, D] dimensional tensor, it is a [1, D] dimensional tensor. This led ultimately to the first query always being selected, not the most unique one as required. 

An error is not raised. To see this is the case, just add a print statement of 'torch.argmin(mean_sim)' here:
https://github.com/huggingface/transformers/blob/01734dba842c29408c96caa5c345c9e415c7569b/src/transformers/models/owlvit/modeling_owlvit.py#L1505

& you will see it is always 0. 

- `transformers` version: 4.28.1
- Platform: Linux-5.4.0-109-generic-x86_64-with-glibc2.31
- Python version: 3.11.3
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- 
## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger
@NielsRogge
@alaradirik 
@amyeroberts

### CODE REVIEW

**Comment by alaradirik** [comment]
@orrzohar thank you for opening the PR! I'll take double check the original code and the forward pass shortly.

**Review by alaradirik — APPROVED** [review]
Thank you for catching this and opening the PR! I double checked the [corresponding part](https://github.com/google-research/scenic/blob/main/scenic/projects/owl_vit/notebooks/inference.py#L151) in the original repo and the change indeed fixes the issue (as documented in issue #21206).

Adding @amyeroberts for the final approval.

**Review by sgugger — APPROVED** [review]

**Comment by MaslikovEgor** [comment]
After this fix I have problem with predictions.

I Use collab demo [Colab demo]([Colab demo](https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/zeroshot_object_detection_with_owlvit.ipynb))
And on example photo with cats I have only one prediction. Looks suspicious and not the same as original repo

Screenshot 2023-05-09 at 16 13 13

@alaradirik

**Comment by MaslikovEgor** [comment]
> Hi @MaslikovEgor, Hub demos are deployed once and not updated unless triggered. I'm rebooting the demo to reflect the changes.

Nice to meet you!

Yeah, I understand this. But in google colab demo we install fresh transformers from source:

`!pip install git+https://github.com/huggingface/transformers.git`

So this is the problem with this changes

@alaradirik

**Pull request merged**
