### PR TITLE
pipelines: Tentative fix for AutoModel for PegasusConfig.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

Original error lies in `pipeline(task='summarization',
model='google/pegasus-xsum')`.
 - Code fails while trying to infer framework from model_name (str).
 - It attempts to determine framework by running `AutoModel.from_pretrained(..)` then  `TFAutoModel.from_pretrained(...)` and decides by seeing whichever works first.

Proposed fix by:
-  implementing `AutoModel.from_pretrained('google/pegasus-xsum')` that is a
`PegasusConfig`. and returning a `PegasusForConditionalGeneration`.

Not sure if that's desirable as we are loading a
`ForConditionalGeneration` model by default (but it's the only available
anyway).

Other options that are available:

- load `BartModel` (Pegasus inherits from BartForConditionalGeneration)
from `PegasusConfig`, but unsure about side effects and odd to load
`Bart` from `Pegasus`.
- Change `get_framework` function from pipeline. That was my initial
choice but it seems understanding if a config is for a TF or Pytorch
model would require replicating some of `AutoModel` logic anyway
so doing that would lead to a discrepancy between the 2 code paths just
for Pegasus (and maybe BartConfig which also suffers some issues, but
that will be in a follow-up PR).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to the it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@LysandreJik
@sshleifer

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Review by sshleifer — APPROVED** [review]
LGTM, way to keep it small!

**Comment by LysandreJik** [comment]
After thinking about it a bit, I don't think the `PegasusForConditionalGeneration` should be going there. The `MODEL_MAPPING` is a mapping to all the headless models, i.e., the models that output hidden states without processing them in a head.

Introducing `PegasusForConditionalGeneration` would result in a mismatch between every single other models defined in that mapping and this newly added model. 

Adding `BartModel` would fail because of the configuration, as you've said, so imo the best thing to do here is to create a `PegasusModel` that inherits from `BartModel`, and use this in the `AutoModel`.

**Comment by sshleifer** [comment]
Why is summarization pipeline using AutoModel?  Shouldn't it require a model with a head?

**Comment by LysandreJik** [comment]
The pipeline is using `AutoModel` to load the weights to see if they load. It follows the current installed platform (PT or TF), but if both are installed, it first tries to load the checkpoint in `AutoModel`, and if it fails (wrongly formatted weights), it tries to load it in `TFAutoModel`.

This does mean that the model is loaded twice (once in `AutoModel` and another time in the appropriate auto model), which may not be the best performance-wise.

The easy fix here is to add a base model for Pegasus (and all models should have base models imo), the somewhat more robust fix is to load the checkpoint directly in the appropriate auto model.

**Comment by Narsil** [comment]
> This does mean that the model is loaded twice (once in AutoModel and another time in the appropriate auto model), which may not be the best performance-wise.

Yes this is not ideal. If there was simpler way do determine appropriate framework from config that would be much better. Or attempt the AutoModel way but without going the full way (stopping at checking filenames).

> The easy fix here is to add a base model for Pegasus (and all models should have base models imo), the somewhat more robust fix is to load the checkpoint directly in the appropriate auto model.

That seems probably like the best solution.

**Comment by sshleifer** [comment]
> and all models should have base models imo

MarianMT, Pegasus, Blenderbot are all only used for one task, why should they have base models?

**Comment by Narsil** [comment]
Some models don't have `architectures` defined.

**Comment by julien-c** [comment]
> The pipeline is using `AutoModel` to load the weights to see if they load. It follows the current installed platform (PT or TF), but if both are installed, it first tries to load the checkpoint in `AutoModel`, and if it fails (wrongly formatted weights), it tries to load it in `TFAutoModel`.

Just a note that I'm not 100% sure that our design goal with Pipelines is to be able to load a model automatically in PT/TF without any user input (e.g. in case the model is only TF)

Besides, in most cases you would have access to the huggingface.co model list API so you would know if model has PT/TF files.

**Comment by julien-c** [comment]
> Some configs (old ones maybe) don't have `architectures` defined.

Just a note that we can always backport architectures into the hosted config files

**Comment by Narsil** [comment]
Obsolete.

**Pull request closed without merging**
