### PR TITLE
Add OFA configuration, tokenizer and modeling

### LINKED ISSUE #15813: Add OFA to transformers
# 🌟 New model addition
We recently proposed OFA, a unified model for multimodal pretraining, which achieves multiple SoTAs on downstream tasks, including image captioning, text-to-image generation, referring expression comprehension, etc. We would like to implement OFA on transformers if it is possible.

## Model description
OFA is a unified multimodal pretrained model that unifies modalities (i.e., cross-modality, vision, language) and tasks (e.g., image generation, visual grounding, image captioning, image classification, text generation, etc.) to a simple sequence-to-sequence learning framework. For more information, please refer to our paper: [Unifying Architectures, Tasks, and Modalities Through a Simple Sequence-to-Sequence Learning Framework](http://arxiv.org/abs/2202.03052).

Our code base is Fairseq. We wonder if there is any simpler solution for the transfer from Fairseq to transformers. To email us, please contact zheluo.wp@alibaba-inc.com or junyang.ljy@alibaba-inc.com.

## Open source status

* [x] the model implementation is available: ([OFA official repo](https://github.com/OFA-Sys/OFA))
* [x] the model weights are available: ([OFA checkpoints](https://github.com/OFA-Sys/OFA/blob/main/checkpoints.md))
* [x] who are the authors: (Peng Wang @[logicwong](https://github.com/logicwong), An Yang @[yangapku](https://github.com/yangapku), Rui Men @[jxst539246](https://github.com/jxst539246), Junyang Lin @[JustinLin610](https://github.com/JustinLin610), Shuai Bai, Zhikang Li, Jianxin Ma, Chang Zhou, Jingren Zhou, Hongxia Yangf)

### PR DESCRIPTION
**Pull request by JustinLin610**
# What does this PR do?

Fixes #15813 and #16265. Added OFA configuartion, tokenizer and Modeling. 

## Who can Review? 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @patil-suraj @gchhablani

### CODE REVIEW

**Comment by gchhablani** [comment]
Thank you so much @JustinLin610 for adding this PR. Sorry I haven't had the chance to work on it so far.

@patil-suraj If anything is needed from my end please let me know.

**Comment by gchhablani** [comment]
I can address the failing tests.

**Comment by JustinLin610** [comment]
> I can address the failing tests. Please give me until today.

Thanks very much for your help! That would be very nice for me cuz I'm not familiar with these things...

**Comment by JustinLin610** [comment]
> I can address the failing tests. Please give me until today.

I just passed the tests (mainly making the test case simpler), but I am not sure if there is any other things that I should do. If you have time, feel free to shoot me some advice on how to improve the code:)

**Comment by patil-suraj** [comment]
Thanks a lot for the PR @JustinLin610 ! I will review this PR either today or tomorrow. LMK if you have any questions, happy to help :)

**Comment by JustinLin610** [comment]
> Thanks a lot for the PR @JustinLin610 ! I will review this PR either today or tomorrow. LMK if you have any questions, happy to help :)

Great! Looking forward to your reply!

**Comment by JustinLin610** [comment]
> Thanks a lot for the PR @JustinLin610 ! I will review this PR either today or tomorrow. LMK if you have any questions, happy to help :)

I have just sync my branch with main. Any ideas or comments for my PR?  btw it seems that the testing of big bird flax causes the breakdown of the whole testing...

**Comment by acul3** [comment]
pinging @gchhablani @patil-suraj 
@LysandreJik 

really want this cool model, merge in huggingface :)

**Comment by gchhablani** [comment]
@LysandreJik @patil-suraj Please let me know if anyone else is working on this, otherwise I can give it another attempt.

**Comment by xvjiarui** [comment]
This is a nice feature. Looking forward to it.

**Comment by JustinLin610** [comment]
> @LysandreJik @patil-suraj Please let me know if anyone else is working on this, otherwise I can give it another attempt.

Still on this..., and also one of my colleagues will participate in this. Would you mind if you and Patil check the code and give me some feedback?

**Comment by xvjiarui** [comment]
Is it possible to re-open this PR so it may get attention?

**Comment by JustinLin610** [comment]
> Is it possible to re-open this PR so it may get attention?

Good suggestion. Maybe I should delete the branch and open a new PR, as my branch has a lot of diffs with the main branch as time passed, and thus I have to merge a lot of PRs for synchronization... I'll update to our latest version first and add more test cases for merging... 

If you are interested, you can check our official repo and the specific branch for transformers. We have confirmed that this version can reach the same performance as the official code based on Fairseq. https://github.com/OFA-Sys/OFA/tree/feature/add_transformers

**Comment by jmhessel** [comment]
gently tagging the great @NielsRogge in case they might have a chance to look at this one :-) OFA is quite strong and it would be amazing to have first-party huggingface support for it

**Pull request closed without merging**
