### PR TITLE
Replaces xxx_required with requires_backends

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Removes `torch_required` and `tf_required` decorators and replaces with more generic `requires_backends`.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for tidying!

**Review by ydshieh — APPROVED** [review]
Cool 😎

**Comment by xkszltl** [comment]
Why do we remove instead of keeping them for backward compatibility?
They can simply be implemented still as a decorator using require_backend, without breaking existing code.

**Comment by ydshieh** [comment]
@xkszltl 

Could you open an issue with more details. Thank you in advance.

**Comment by xkszltl** [comment]
Issue filed:
- https://github.com/huggingface/transformers/issues/25948

**Pull request merged**
