### PR TITLE
Allowing users to use the latest `tokenizers` release !

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

- Allow users to use the most recent `tokenizers` version.
- Should be 100% backward compatible, but there were quite large changes to the actual codebase.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
You need to run `make style` when changing the setup.

**Review by SaulLu — APPROVED** [review]
Look good to me! Thank you :confetti_ball: 

I guess that the first user of this feature will be MarkupLM :smile:

**Comment by sgugger** [comment]
Failure seem unrelated. Yet rebasing on main to remove the failure linked to the Datasets release and re-laucnhing spurious tests would be helpful to ease everyone's mind :-)

**Review by sgugger — APPROVED** [review]

**Comment by Narsil** [comment]
@sgugger Should I wait for a second core maintainer's opinion on this ?

**Comment by sgugger** [comment]
Nope, you can go ahead and merge :-)

**Comment by Smaug123** [comment]
I couldn't immediately find the release process for this repository - when will this make it into a release? `tokenizers` (for versions earlier than 0.13.0) had no wheel available for Apple silicon, so I believe until this PR is released we're stuck with source builds for that dependency.

**Comment by sgugger** [comment]
The next release of Transformers will be in a month roughly. In the meantime, you can install it from source.

**Pull request merged**
