### PR TITLE
[logging] implement warning_advice / TRANSFORMERS_NO_ADVISORY_WARNINGS

### LINKED ISSUE #14455: The multi-node / multi-gpu training and repeat logging on each process
How do we deal with repetitive warnings that can't be shut off on a multi-node/multi-gpu environment?

e.g. at BigScience we started using HF Tokenizer and now **this gets repeated hundreds of times**:
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
```

It comes from:
https://github.com/huggingface/transformers/blob/efea0f868bd381244e3cef51b388293e41a36d1e/src/transformers/tokenization_utils_base.py#L1934-L1936

The only way for me to fix this is to push the logging level to ERROR on the replicas:
```
        if args.rank == 0:
            transformers.utils.logging.set_verbosity(logging.INFO)
        else:
            transformers.utils.logging.set_verbosity(logging.ERROR)
```
but then if there is actually a real warning in some process, then I won't see it.

Any good suggestions here?

Thank you!

p.s. As a background story: I have each component we use in Megatron-DeepSpeed spitting just a few dozens of these which then get multiplied by say 512 or 1024 times. And the log file becomes unusable and makes the troubleshooting when things crash a very difficult experience. Hence I really need to find a way not to log anything that is not really pertinent to a specific replica process. Moreover many processes aren't replicas of rank 0 process and do unique things, e.g. in the pipeline setup. But in the case of tokenizer it is the same on all processes.

@sgugger, @LysandreJik

### PR DESCRIPTION
**Pull request by stas00**
This PR implements the idea of advisory logger warnings as discussed at https://github.com/huggingface/transformers/issues/14455

The main ideas is to enable users to turn some logger warnings off when they re-run the same program again and again and either don't care or can't do something about those warnings. Additionally, this is essential for multi-node setups where the same warning gets replicated for each process and with 512 processes it's a lot of identical warnings.

This PR:

- adds a new logger method `logger.warning_advice` which works just like `logger.warning` but which is a no-op if the env var `TRANSFORMERS_NO_ADVISORY_WARNINGS=1` is set
- adds tests
- updates docs
- replaces one warning for now - need to replace more.

TODO:

- decide which warnings should always remain warnings and which can be switched to advisory ones, this can also be a gradual process. We can also invite input from the community.

- Once completed I'd also propose to replicate this to `datasets` as most of the time repeat uses and the warnings are just as non-informative and ignored there as in `transformers`.

Fixes: https://github.com/huggingface/transformers/issues/14455

@sgugger, @LysandreJik, @patrickvonplaten, @patil-suraj

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
LGTM, thanks for working on the general architecture for this!

**Review by sgugger — APPROVED** [review]

**Review by LysandreJik — APPROVED** [review]
This looks good to me! 

Also cc @NielsRogge for knowledge, who was mentioning some annoying warnings at other places in the library.

**Comment by patrickvonplaten** [comment]
Looks good to me! I'm wondering whether we actually need a new logger function `logger.warning_advice` or whether it might make sense to simply overwrite `logger.warning` since 100% backward compatibility is kept

**Comment by stas00** [comment]
> Looks good to me! I'm wondering whether we actually need a new logger function `logger.warning_advice` or whether it might make sense to simply overwrite `logger.warning` since 100% backward compatibility is kept

You're thinking about having a mechanism of turning all warnings off, aren't you?

If so this is already available via logger's set verbosity.

If we are going to change all warnings to advisory warnings then this feature is pointless. 

My thinking was that some warnings are a must whereas others are either border-line `info`-level or they are not close to `error` level.

Perhaps we need to have a closer look at the types of warnings we have right now. If there no clear sub-division of which warnings are essential and which aren't, then this feature won't help.

**Comment by LysandreJik** [comment]
I'm personally ok with the `warning_advice` which is supposed to be different to `warning` - for me it's good to merge

**Comment by patrickvonplaten** [comment]
Ok for me!

**Pull request merged**
