### PR TITLE
TF: TF 2.10 unpin + related onnx test skips

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

Unpins TF, but adds the appropriate test skips.

Should remove the tensorflow probability CI problem.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for working on this!

**Review by ydshieh — APPROVED** [review]
Thanks, @gante .

I see you also added 2 `CMD ["/bin/bash"]`. I think it will be fine - some commands may or may not work on different shells though. I personally would prefer to work with `bash` too.

**Comment by gante** [comment]
@ydshieh -- no command was added there, but rather a newline at the end of the file (automatic vscode settings). They already exist in some of the docker files (e.g [here](https://github.com/huggingface/transformers/blob/main/docker/transformers-cpu/Dockerfile#L26)). Happy to revert!

**Comment by ydshieh** [comment]
Oh, it's fine. No need to revert. (The consequence of getting up at 5AM ...)

**Pull request merged**
