### PR TITLE
is_batched fix for remaining 2-D numpy arrays

### PR DESCRIPTION
**Pull request by LWprogramming**
# What does this PR do?

Fix `is_batched` logic for 2-D numpy arrays, as described in https://github.com/huggingface/transformers/pull/23223#pullrequestreview-1423033751

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sanchit-gandhi

### CODE REVIEW

**Comment by LWprogramming** [comment]
Hmm, this is odd-- I just noticed manually running `pytest` on the tests fixed here just shows they're all automatically skipped. Looking into configuration now...

**Comment by sanchit-gandhi** [comment]
Thanks for the quick changes @LWprogramming! Let's wait until #23223 is finalised before getting this merged so that we can update this PR with any amendments from there

**Comment by LWprogramming** [comment]
> Thanks for the quick changes @LWprogramming! Let's wait until #23223 is finalised before getting this merged so that we can update this PR with any amendments from there

Ok, updated the code with comments from that PR, and ran tests + linters

**Review by sanchit-gandhi — APPROVED** [review]
Thanks for propagating these changes on @LWprogramming! This PR LGTM 👍 See #23223 as the PR this follows on from

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
