### PR TITLE
duplicated line for repeating_words_penalty_for_language_generation

### PR DESCRIPTION
**Pull request by patrickvonplaten**
length_penalty has a duplicated wrong documentation for language generation -> delete two lines

### CODE REVIEW

**Comment by thomwolf** [comment]
Yes, actually the doc is still not complete for this new feature.

We should add some examples and double-check all. Feel free to clean this up if you feel like it.

**Comment by patrickvonplaten** [comment]
clean up documentation, add examples for documentation and rename some variables

**Comment by patrickvonplaten** [comment]
checked example generation for openai-gpt, gpt2, xlnet and xlm in combination with #2289.

**Comment by patrickvonplaten** [comment]
Also checked for ctrl

**Comment by patrickvonplaten** [comment]
also checked for transfo-xl

**Comment by thomwolf** [comment]
Awesome, merging!

**Pull request merged**
