### PR TITLE
rembert/splinter (torch) type annotations

### PR DESCRIPTION
**Pull request by jacobdineen**
#16059

Type annotations for Rembert & Splinter (Torch) and copies

### CODE REVIEW

**Comment by jacobdineen** [comment]
@Rocketknight1 this passed tests - Think I was missing an Optional typing import on Splinter.
No build on PR though

**Comment by jacobdineen** [comment]
@Rocketknight1 Rembert and Splinter done, as well as copies from Bert.
Tests failing on flax, which wasn't modified.

**Comment by jacobdineen** [comment]
@Rocketknight1 The auxiliary files that were updated were results of running make fix-copies, and then make fixup. I tried several different things, but the build always failed in a single place that I wasn't able to trackdown. Something about an Optional call not defined in the model template file, which was not something that was modified.

**Comment by Rocketknight1** [comment]
Hi @jacobdineen, that's weird. Can you make a new PR (make sure to fork/branch from the most recent version of the library!) and just make the type hint changes to Rembert + Splinter, without any formatting changes or things like `make fixup` or `make fix-copies`? Tests will fail, but I'll review it and run the fixup myself here, and I should be able to resolve any problems at my end.

Thanks for your patience here - hopefully we can figure this one out!

**Pull request closed without merging**
