### PR TITLE
Correct @is_flaky test decoration

### PR DESCRIPTION
**Pull request by qubvel**
# What does this PR do?

Some tests are marked with `@is_flaky` decorator without brackets, which leads to always passing the test even if an exception is always raised in the test.

For example:
```python
@is_flaky  # <------ should be @is_flaky()
def test_flash_attn_2_equivalence(self):
    ...
```

P.S. Fixing this may lead to failing flaky tests, but now these tests are just broken.

## Who can review?

@ydshieh

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thank you for identifying this!

**Comment by ydshieh** [comment]
Let's trigger a CI that runs slow tests for a few models involved.

I have put a label `run_slow`, could you push an empty commit with `[run_slow] gemma, xxx, yyy`, where `xxx`, `yyy` are some model names that you can think of relevant.

**Comment by ydshieh** [comment]
oh, right. Those flash attn tests will only run with `.github/workflows/push-important-models.yml` which is triggered when a PR being merged to `main`.

One last thing could try is to use

https://github.com/huggingface/transformers/actions/workflows/ssh-runner.yml

Internal notion doc: https://www.notion.so/huggingface2/SSH-into-our-runners-d9c24de77d0843b2a308f28171106001

It's more a good chance to learn how to use this. Would you like to give it a try even it's somehow manual?

For docker image, you will have to fill `huggingface/transformers-all-latest-gpu`


You will have to do

```
          apt install sudo
          sudo -H pip install --upgrade pip
          sudo -H pip uninstall -y transformers 
          sudo -H pip install -U -e ".[testing]" 
          MAX_JOBS=4 pip install flash-attn --no-build-isolation
```

**Comment by ydshieh** [comment]
will merge after an approve from @amyeroberts  (as a manual run inside the runner is done .)

**Comment by qubvel** [comment]
Gemma FA2 tests 
Screenshot 2024-06-19 at 15 10 25

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing and running tests!

**Pull request merged**
