### PR TITLE
[`Llava`] Fix convert_llava_weights_to_hf.py script

### PR DESCRIPTION
**Pull request by isaac-vidas**
Fix call to `tokenizer.add_tokens` in `convert_llava_weights_to_hf.py` and `convert_vipllava_weights_to_hf.py` scripts.

# What does this PR do?

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@younesbelkada if you can review

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
LGTM after an offline discussion with @ArthurZucker thanks for fixing

**Comment by younesbelkada** [comment]
@isaac-vidas would you be happy to address the same fix for Vip-Llava? https://github.com/huggingface/transformers/blob/main/src/transformers/models/vipllava/convert_vipllava_weights_to_hf.py#L61

**Comment by isaac-vidas** [comment]
Thanks for the review @younesbelkada!
I added the fix you mentioned, if you can review again please 😄

**Review by younesbelkada — APPROVED** [review]
Thanks again for fixing the Llava conversion script !

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
