### PR TITLE
Fix serialization for offloaded model

### LINKED ISSUE #31685: NameError: free variable 'state_dict' referenced before assignment in enclosing scope
### System Info

- `transformers` version: 4.42.1
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.10.10
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.2
- Accelerate version: 0.31.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.2+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: <fill in>
- Using GPU in script?: <fill in>
- GPU type: NVIDIA A100-SXM4-80GB

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

shard = {tensor: state_dict[tensor] for tensor in tensors}
NameError: free variable 'state_dict' referenced before assignment in enclosing scope
```python
model_path = 'liuhaotian/llava-v1.5-7b'
dst_path = 'llava-v1.5-7b-test'

import torch
from transformers import AutoModelForCausalLM

from llava.model.language_model.llava_llama import LlavaConfig
config = LlavaConfig.from_pretrained(model_path, trust_remote_code=True)

model = AutoModelForCausalLM.from_config(config,
                                            trust_remote_code=True)
from accelerate import load_checkpoint_and_dispatch
load_checkpoint_and_dispatch(
    model=model,
    checkpoint=model_path,
    device_map={'': 'cpu'},
    no_split_module_classes=['CLIPEncoderLayer'],
    dtype=torch.half)

model.save_pretrained(dst_path,
                      max_shard_size='2GB',
                      safe_serialization=True)

```
Seems the latest transformers cannot work with accelerate properly.

### Expected behavior

It worked fine with previous versions of transformers.

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR do ? 

This PR fixes the serialization of offloaded model. With this PR, the logic behind saving offloaded model is triggered only when we use more than one device that contain either "cpu" or "disk" device. Moreover, we fix a small bug that was introduced with this [PR](https://github.com/huggingface/transformers/pull/31091). We rename the `state_dict` variable to `shard_state_dict`. I also fixed the test `test_save_offloaded_model`.

### Example: 

```python 
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-hf", device_map={"":"cpu"})
model.save_pretrained("llama")
```

Fixes https://github.com/huggingface/transformers/issues/31685

### CODE REVIEW

**Comment by LysandreJik** [comment]
Could you implement a test that ensures that the previous faulty behavior has been fixed? :)

**Comment by SunMarc** [comment]
> Could you implement a test that ensures that the previous faulty behavior has been fixed? :)

Done ! 

Do you know where I can see the results of the test for test_modeling_utils.py file @ydshieh ? I didn't see the following test `test_save_offloaded_model` in the daily report. On my local machine, it was failing so I was expecting to see it in the report.

**Comment by ydshieh** [comment]
Hi @SunMarc Let me check, but we might have a problem of some test files not included 😭

**Comment by ydshieh** [comment]
I confirmed that we have some tests not running on daily CI.
(We also have push-ci where we try to collect the impacted files, but for daily CI, tests are collected from the subfolders of `tests`)

> Maybe we can put all the utils python file into a separate folder to not have them mixed with the common test files.

Sound a quick solution. It's just we have to make sure there is not subclass of `TestCase` in other files under `tests`. But for now let's do what you suggested above.

**Comment by SunMarc** [comment]
> Sound a quick solution. It's just we have to make sure there is not subclass of TestCase in other files under tests. But for now let's do what you suggested above.

Great !

**Comment by ydshieh** [comment]
Here it is #31730  but I have to see how CI is going.

**Review by LysandreJik — APPROVED** [review]
Looks good, thanks for the changes @SunMarc

**Pull request merged**
