### PR TITLE
Fix gradient checkpointing bug in Speech2Text

### PR DESCRIPTION
**Pull request by KMFODA**
This PR fixes a bug that a user can encounter while using generate and models that use gradient_checkpointing.

Fixes Issue https://github.com/huggingface/transformers/issues/21737

cc @younesbelkada or @gante

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for your great work! 
Can you use `warning_once` instead? 🙏

**Comment by KMFODA** [comment]
Sorry fixed that

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for this!

**Comment by gante** [comment]
@KMFODA your fork probably needs to pull from `main` :p

**Review by gante — APPROVED** [review]
Thank you for the contribution 🙏

**Pull request merged**
