### PR TITLE
Move tests/utils.py -> transformers/testing_utils.py

### LINKED ISSUE #5261: [proposal] Move tests/utils.py to src/transformers/testing_utils.py so that examples can import
for both groups of tests, the import would be
```python
from transformers.testing_utils import slow
```

Motivation: I was about to rewrite the @slow decorator today and felt that this was cleaner.

Any objections? @julien-c @LysandreJik @thomwolf @sgugger @patrickvonplaten @mfuntowicz 
@anyoneelseimforgetting

### PR DESCRIPTION
**Pull request by sshleifer**
Fixes #5350 
The motivation is to allow examples/ tests to use these utilities.

for both groups of tests, the import is
```python
from transformers.testing_utils import slow
```

Motivation: I was about to rewrite the @slow decorator today and felt that this was cleaner.

### CODE REVIEW

**Comment by sshleifer** [comment]
CI failure is spurious

**Review by LysandreJik — APPROVED** [review]
This is a welcome change!

**Review by patrickvonplaten — APPROVED** [review]

**Review by sgugger — APPROVED** [review]
LGTM

**Comment by julien-c** [comment]
no objection

**Pull request merged**
