### PR TITLE
Add SeamlessM4T v2

### PR DESCRIPTION
**Pull request by ylacombe**
# What does this PR do?

Meta just released [Seamless M4T v2](https://ai.meta.com/resources/models-and-libraries/seamless-communication-models/#seamlessm4t), this model has enough difference to justify a new version: differences listed [here](https://github.com/ylacombe/transformers/blob/add-S2S-2/docs/source/en/model_doc/seamless_m4t_v2.md#difference-with-seamlessm4t-v1) in the .md

@ArthurZucker reviewed most of the files internally but a few last changes might require a final approval!

cc @ArthurZucker @LysandreJik @sanchit-gandhi

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Let’s go time sensitive! 🤗🤗

**Comment by yclicc** [comment]
I'm astonished you got this added so quickly! Do you have plans to support seamless streaming as well?

**Comment by ArthurZucker** [comment]
We'll do a release this week and it will be part of it! You have to install from source for now `pip install -e git+https://github.com/huggingface/transformers`

**Comment by sanchit-gandhi** [comment]
No plans yet for seamless streaming since the architecture diverges somewhat from Seamless M4T. The license is non-commercial unfortunately, which is also a barrier to usage. But if anyone in the community is interested in adding the model I'd sure be happy to lend a hand with the integration by answering any questions/queries and reviewing PRs! WDYT @ylacombe @yclicc - should we open a feature request up to the community for this?

**Pull request merged**
