### PR TITLE
Fix Wav2Vec2 Fairseq conversion (weight norm state dict keys)

### LINKED ISSUE #31633: `convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py` does not work due to weight norm key
### System Info

NA

### Who can help?

@sanchit-gandhi

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Fairseq uses `nn.utils.weight_norm()`, which produces `weight_g` and `weight_v` keys

https://github.com/facebookresearch/fairseq/blob/d9a627082fd03ec72a27a31a4e56289bfcb2e4e4/fairseq/models/wav2vec/wav2vec2.py#L939

The weight conversion script assumes this old-style weight norm

https://github.com/huggingface/transformers/blob/2daf2c3eaa2992018b8d1ceb3421f5baa649bad5/src/transformers/models/wav2vec2/convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py#L118-L121

Thus, the weight conversion script will fail since `transformers` has switched to `nn.utils.parametrizations.weight_norm` for quite some time, which produces `parametrizations.weight.original0` and `parametrizations.weight.original1` keys instead.

https://github.com/huggingface/transformers/blob/1218e439b5fe05423693407653a1fb064263fef4/src/transformers/models/wav2vec2/modeling_wav2vec2.py#L392-L394

Thus the weight conversion script should be updated accordingly.

### Expected behavior

Weight conversion script works.

### PR DESCRIPTION
**Pull request by gau-nernst**
# What does this PR do?

Close #31633

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sanchit-gandhi @amyeroberts

## To test

```bash
wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_small.pt  # wav2vec2-base checkpoint from facebook
pip install git+https://github.com/facebookresearch/fairseq.git  # install fairseq

python src/transformers/models/wav2vec2/convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py \
    --pytorch_dump_folder wav2vec2-base \
    --checkpoint_path wav2vec_small.pt \
    --config_path facebook/wav2vec2-base \
    --not_finetuned
```

I only checked for Wav2Vec2 base. Other checkpoints should work too. See other checkpoints from fairseq here: https://github.com/facebookresearch/fairseq/tree/main/examples/wav2vec

e.g. https://dl.fbaipublicfiles.com/fairseq/wav2vec/libri960_big.pt corresponds to https://huggingface.co/facebook/wav2vec2-large

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @kamilakesbi

**Comment by gau-nernst** [comment]
gentle ping @amyeroberts @kamilakesbi

**Review by kamilakesbi — COMMENTED** [review]
Hi @gau-nernst, thanks for working on this!

It LGTM! failing tests seem to be unrelated to this PR.

cc @amyeroberts for final review :)

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
