### PR TITLE
[`Llama2`]  Add support for Llama 2: Fix convert_llama_weights_to_hf.…

### PR DESCRIPTION
**Pull request by linggong2023**
…py support 7Bf

# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by fahadh4ilyas** [comment]
What does `f` mean in model size? Does it mean `fine-tuned`?

**Comment by linggong2023** [comment]
I understand that "f" should be modified to "-CHAT" to support the CHAT
model. I have made further modifications to the relevant code, replacing
all instances of "f" with "-CHAT". Could you please reload the same commit
for me?

**Comment by sgugger** [comment]
cc @ArthurZucker

**Review by ArthurZucker — DISMISSED** [review]
Hey, not really sure if it's better than just removing this if else (since it works well without) but ok

**Comment by linggong2023** [comment]
I also think the same way. At first, I couldn't understand 7Bf, but now it seems that these things are useless. I just deleted 7Bf, 13Bf, and 70Bf.

**Comment by linggong2023** [comment]
@sgugger I have finished the modifications, ready for merging.

**Comment by ArthurZucker** [comment]
No no, why would you remove the `70Bf`? All the `f` are for the finetuned/chat checkpoints

**Pull request closed without merging**
