### PR TITLE
[WIP]-Add Fast Pitch 1.1

### PR DESCRIPTION
**Pull request by ArEnSc**
# What does this PR do?

Adds FastPitch 1.1# (issue)[https://github.com/huggingface/transformers/issues/16349]

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by LysandreJik** [comment]
Thanks for the PR @ArEnSc!

Let us know if you need assistance at any point!

**Comment by ArEnSc** [comment]
> Thanks for the PR @ArEnSc!
> 
> Let us know if you need assistance at any point!

Will do! have been lagging on this due to family and my day job =)

**Comment by ArEnSc** [comment]
update: going to continue to work on this soon

**Comment by ArEnSc** [comment]
Still working on this, just doing some reading and enjoying some time away from the other job.

**Comment by ArEnSc** [comment]
closing for now while I deal with covid =(

**Pull request closed without merging**
