### PR TITLE
[Whisper test] Fix some failing tests

### PR DESCRIPTION
**Pull request by ylacombe**
# What does this PR do?

This PR proposes multiple simple fix to some Whisper failing tests:
1. Fix failing tensor device
2. Fix long-form integration tests that weren't using `return_timestamps=True`

UPDATE: ready for review, I'll correct more tests in the coming days 

cc @LysandreJik and @ydshieh

### CODE REVIEW

**Comment by ydshieh** [comment]
It would be a good opportunity to use the `run-slow` in this PR

**Comment by ylacombe** [comment]
There'll be failing tests though FYI, there's a lot of work to do around Whisper!

**Comment by ydshieh** [comment]
Yeah I understand. (just want to make sure the tests fixed in this PR are passing).

The core maintainers could still merge in that case.

**Review by LysandreJik — APPROVED** [review]
Thanks for the fixes @ylacombe!

**Review by ArthurZucker — APPROVED** [review]

**Comment by ylacombe** [comment]
@ydshieh, do you know why this error happens ?
`Bus error (core dumped)`

**Comment by ydshieh** [comment]
No, it happens in some models and runs. It's more a infra issue I think.

**Comment by ydshieh** [comment]
I re-triggered it. Let's see

**Comment by ydshieh** [comment]
Let me see what I can do manually.

**Comment by ydshieh** [comment]
Could you check if the fixed tests are passing in the following run ?


> https://github.com/huggingface/transformers/actions/runs/10885416563/job/30203010247?pr=33450

**Comment by ylacombe** [comment]
Hey @ydshieh, they passed indeed ! Thanks for helping me on this,
I'll merge once you revert the commit!

**Pull request merged**
