### PR TITLE
Fix broken links to distillation on index page of documentation

### PR DESCRIPTION
**Pull request by amitness**
# What does this PR do?

Fixes broken links to DistilGPT2, DistilRoberta, and DistilmBERT on the homepage of documentation.

image

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?

## Who can review?
@sgugger

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing! Could you run `make fix-copies` to fix the CI checks?

**Comment by amitness** [comment]
@sgugger Running that command modifies `index.mdx` and resets the links back to the broken link. I'm not sure why that's the case.

image

**Comment by sgugger** [comment]
Ah you need to fix them in the main README, the rest is updated from it.

**Comment by amitness** [comment]
@sgugger Right, that makes sense. Do I need to apply these also to the language-specific READMEs or are those auto-generated?
image

**Comment by sgugger** [comment]
If you run `make fix-copies`, all your changes should be propagated.

**Comment by LysandreJik** [comment]
Hello @amitness, let us know if you'd like for us to run `make fix-copies` on your fork (and if so, please invite us as contributors so that we may push to it!)

Thanks!

**Comment by amitness** [comment]
@LysandreJik I have already run `make fix-copies` and there are no changes to any file after running it. The CI is still failing due to some other reason.

image

**Comment by LysandreJik** [comment]
Ah, indeed the error says  the following:
```
Traceback (most recent call last):
  File "utils/style_doc.py", line 550, in <module>
    main(*args.files, max_len=args.max_len, check_only=args.check_only)
  File "utils/style_doc.py", line 538, in main
    raise ValueError(f"{len(changed)} files should be restyled!")
ValueError: 1 files should be restyled!

Exited with code exit status 1

```

Can you run `make fixup`, which should take care of everything style-related?

**Comment by amitness** [comment]
@LysandreJik Thank you. That worked and I have pushed all changes.

**Comment by sgugger** [comment]
Thanks again for fixing!

**Pull request merged**
