### PR TITLE
fix text summarization evaluation bugs when calculate rouge

### PR DESCRIPTION
**Pull request by ShichaoSun**
# What does this PR do?

fix text summarization evaluation bugs when calculate rouge

It is important for calculating rouge

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
@patil-suraj @sshleifer @patrickvonplaten

### CODE REVIEW

**Comment by ShichaoSun** [comment]
just fix a typo but i donnot know how to pass the test

**Comment by ShichaoSun** [comment]
only two lines changed but it take much effort to pass the check!
I think it may be important for the evaluation result.
They are simple but true bugs

**Comment by patil-suraj** [comment]
Great catch @ShichaoSun  and thank you for working on this!
We are in the process of finishing the [new standalone seq2seq script](https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_seq2seq.py) with the same functionality but without depending on the utils or other helpers. The utils and other helpers will probably be removed once we completely test the new script.

**Comment by ShichaoSun** [comment]
Great job!  Looking forward to seeing that.

**Pull request closed without merging**
