### PR TITLE
feat: Upgrade Weights & Biases callback

### PR DESCRIPTION
**Pull request by parambharat**
# What does this PR do?

- Continuation of old PR #29125

This PR adds a few new functionalities to the Weights & Biases Callback

- Logs Peft and Lora Config to wandb if present
- Adds model parameter counts to wandb config and artifact metadata
- Adds on_predict methods to log prediction metrics
- Prints the model architecture to a file alongside the wandb artifact
- Logs initial and final models to the wandb artifact to full reproducibility
- Adds steps and epoch aliases to checkpoint artifacts

- Here's a [link](https://wandb.ai/parambharat/test-transformers/artifacts/model/model-rg4pcjcv/v3) to the what the logged artifacts look like
- Here's a run [overview page](https://wandb.ai/parambharat/test-transformers/runs/rg4pcjcv/overview?workspace=user-parambharat) with added config and metadata for the run with peft configs logged

## Before submitting
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?

## Who can review?

- @muellerzr
- @pacman100
- @amyeroberts

### CODE REVIEW

**Comment by parambharat** [comment]
@amyeroberts: I think I was finally able to get all ci checks to pass. The issues were related to type annotations and lazy imports. I have fixed these. Can you please take a look ?

**Review by amyeroberts — APPROVED** [review]
Thanks for all of the work adding this!

**Comment by morganmcg1** [comment]
Hey @amyeroberts  , do you know if this PR is going into the next release?

**Comment by amyeroberts** [comment]
@morganmcg1 Yes, all commits merged into main will be part of the next minor release - v4.41. If there are patch releases before this e.g. 4.40.2, then it won't be part of that release. 

If you want to use this immediately, you can install from source, getting all the most recent commits from main: `pip install git+https://github.com/huggingface/transformers`

**Comment by jonghwanhyeon** [comment]
This PR causes an error when a custom model with no `save_pretrained()` method uses `Trainer` class.

**Comment by amyeroberts** [comment]
@jonghwanhyeon Could you open an issue, detailing the errors and linking to this PR for reference? This way we'll be able to properly track if/when it's resolved

**Comment by mgerstgrasser** [comment]
@amyeroberts @parambharat It seems that this _always_ logs the initial model checkpoint to wandb, with no way of turning it off, and uploads the _entire_ model when doing a full fine-tune. This is not intended, is it?

**Comment by tomaarsen** [comment]
@ArthurZucker I appreciate you reverting this; my W&B storage was immediately full and now I can't access my W&B logs anymore without being immediately redirected to the billing page :/ 

- Tom Aarasen

**Pull request merged**
