### PR TITLE
Fix low cpu mem usage tests

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR do ? 
This PR fixes the common tests about `low_cpu_mem_usage` (covered in accelerate_tests). The issue that we had was that we moved one of the model to cuda while the other was on cpu. Hence, we get an error while trying to compare those two models. After fixing the issue on the tests, the only failing model is UdopModel that I fixed (we need to tie the weights in `_tie_weights`. Otherwise, it won't work with `low_cpu_mem_usage`) 

See the run [here](https://github.com/huggingface/transformers/actions/runs/9116151177) with most of the tests passing

Furthermore, I'm running accelerate tests on every model to see if we still have failing tests + check if there are any failing tests for model parallelism, cpu_offload, disk_offload.
The other failing tests are fixed [here](https://github.com/huggingface/transformers/pull/30836). @ydshieh for viz

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Thanks for fixing ! 🤗

**Review by NielsRogge — APPROVED** [review]
Thanks!

**Review by ydshieh — APPROVED** [review]
Thanks!

Would be nice if an explanation about what happens. Like, if it's a change in `accelerate` caused this test starting to fail, and if this is the case, a link to a commit in `accelerate` could be provided.

**Comment by SunMarc** [comment]
> Would be nice if an explanation about what happens. Like, if it's a change in accelerate caused this test starting to fail, and if this is the case, a link to a commit in accelerate could be provided.

In this PR, I fixed the common tests. The issue was that the tests were not designed correctly ( device placement issue ). As for the failing test on UdopModel, this is an issue on the modeling code. With my fix, we can load UdopModel with low_cpu_mem_usage=True. So it's more an issue on transformers.

**Pull request merged**
