### PR TITLE
Tf trainer cleanup

### PR DESCRIPTION
**Pull request by sgugger**
This follows up from #5982 and does the same thing for `TFTrainer`.
Basically no code is changed, just moved around and the customization points are made public and explicit to the user. Starting to make the docs better but I will do it properly (for both Trainer and TFTrainer) after this PR is merged.

### CODE REVIEW

**Review by jplu — APPROVED** [review]
Very cool!! May I ask you a favor? Can you wait a bit before to merge this one? I'm currently fully reworking the TF Trainer and multiple things will change. A PR is coming this weekend.

**Comment by sgugger** [comment]
As long as you don't create too many merge conflicts, I can wait ;-)

**Comment by jplu** [comment]
PR available #6038

**Comment by sgugger** [comment]
Merge conflicts were a mess so opened a new version.

**Pull request closed without merging**
