### PR TITLE
Fix UDOP dtype issue

### PR DESCRIPTION
**Pull request by Rocketknight1**
The UDOP processor uses the LayoutLMV3 image processor, but this results in dtype errors in the CI. Trying to fix it in this PR!

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @NielsRogge UDOP seems to be failing in the CI because the image type is `uint8`, which causes an overflow error when it's scaled by a negative number during normalization. I'm guessing this means we need to set the dtype to be `float32` there, but I'm not sure exactly where to make the change.

**Comment by Rocketknight1** [comment]
cc @NielsRogge @LysandreJik for review!

**Comment by LysandreJik** [comment]
cc @qubvel or @molbap for CV review as well

**Comment by Rocketknight1** [comment]
I'd appreciate a quick review on this one, since it's blocking other PRs!

**Comment by molbap** [comment]
Hey @Rocketknight1, sorry about that, quick review to unblock: I'd be more pro-having the modification within the definition of `self.resize`, in order to keep the pattern consistent with the other classes. 
You could even catch the PIL version causing issues, parse it with `packaging.version`, and if it's above/below the version causing issues do the dtype switch in that case, right? + commenting on why this is needed!

**Comment by Rocketknight1** [comment]
@molbap I think it's simpler to just do `.astype(np.float32)`, firstly because I can't figure out exactly which version in the CI triggers this issue, and secondly because `.astype(np.float32)` on a `float32` array [does not copy or modify the array](https://numpy.org/devdocs/reference/generated/numpy.ndarray.astype.html) if we use `copy=False`, so there's no performance penalty to just calling it anyway.

Still, I'll move it inside `self.resize()`!

**Comment by Rocketknight1** [comment]
Investigated further, and the issue is not where I thought! The cause is actually this PR to Numpy, which changes type promotion rules: https://github.com/numpy/numpy/issues/25639

In fact, `uint8` is the expected dtype and this hasn't changed. What **has** changed is that this line:

`rescaled_image = image * scale`

fails in cases where `image` is `uint8` and `scale` is a negative integer, which occurs in the UDOP tests. Previously, this would silently promote the dtype to `np.int16`, but this is no longer the case. The reason we don't see more problems is that multiplying a `uint8` array by a positive/negative **float** still silently promotes the array, and this is much more common. Only UDOP uses a negative **integer** scale in its tests.

This means the fix actually needs to go in `image_transforms.py`, one sec!

**Comment by Rocketknight1** [comment]
Pushed the fix - now we always manually upcast to `np.float64`. This was what happens silently 99% of the time anyway, but now we make it explicit, which also fixes the cases where promotion doesn't silently happen anymore.

**Review by ArthurZucker — APPROVED** [review]
Thanks, our ci has been red because of this for quite a while!

**Comment by molbap** [comment]
Thanks @Rocketknight1 ! cc @yonigozlan here, on the negative scale x uint8 issue I mentioned last time (just FYI)

**Comment by yonigozlan** [comment]
Thanks for flagging this! I'll also change the ProcessorMixin tests to make the type promotion more explicit in case they change it again :)

**Pull request merged**
