### PR TITLE
[WIP] Add CLIPViP

### LINKED ISSUE #22829: Add CLIP-ViP
### Model description

[CLIP-ViP](https://github.com/microsoft/XPretrain/tree/main/CLIP-ViP) is a video-language model which is based on a pre-trained image-text model [CLIP](https://openai.com/blog/clip/) then further pre-trained (post-pretraining) on a large-scale video-text dataset [HD-VILA-100M](https://github.com/microsoft/XPretrain/tree/main/hd-vila-100m). This work is accepted by ICLR 2023.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

[The official implementation](https://github.com/microsoft/XPretrain/tree/main/CLIP-ViP)
This repo has model implementation and pre-trained weights.
@hellwayxue

### PR DESCRIPTION
**Pull request by tensorpro**
# What does this PR do?

Fixes #22829 

## Before submitting
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
https://github.com/huggingface/transformers/issues/22829

- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
Docs are WIP

I haven't updated the docstrings yet. 
- [X] Did you write any new necessary tests? 
Integration test still needs some work. It's basically just the CLIP integration test, it doesn't test how video retrieval would work
## Who can review?

@NielsRogge 

maybe others?

### CODE REVIEW

**Comment by sgugger** [comment]
cc @amyeroberts

**Comment by amyeroberts** [comment]
@tensorpro  Thank you very much for this PR and adding this great model!
Let us know when this is ready for review and feel free to ping me if you have any issues or questions about the implementation in the meantime.

**Comment by tensorpro** [comment]
Thanks @amyeroberts!
This PR should be pretty close. I need to add a custom processor for CLIPViP to setup the preprocessing for videos and improve documentation. But after that, it should be ready to review.

**Comment by tensorpro** [comment]
2 questions:




Is there a way to run the CI checks with a local command? I've been pushing commits to see the CI testing runner outputs from GitHub, which has been littering the commit history and been a bit slow


Are there bugs in [modeling_outputs'](https://github.com/huggingface/transformers/blob/17a55534f5e5df10ac4804d4270bf6b8cc24998d/src/transformers/modeling_outputs.py#L46-L47) type hints for attentions/hidden outputs? It seems like we want `Tuple[FloatTensor,...]` instead of the`Tuple[FloatTensor]`? 
The current type hint makes it seem like we should return a tuple with a single`FloatTensor` instead of a tuple with an arbitrary number of float tensors.

**Comment by amyeroberts** [comment]
@tensorpro Good spot - yes, the returned tuples can have a variable number of items. In practice, we're not running e.g. mypy against the repo so shouldn't break things but, as you point out, could be misleading. Would you like to open an issue or PR addressing this?

**Comment by tensorpro** [comment]
Sorry about the delay, but I got around to adding a CLIPViPProcessor + improving some of the docs.

Merging with the recent changes in [24306](https://github.com/huggingface/transformers/pull/24306) was a bit confusing, since it wasn't clear from the error messages I was getting that we need to add `_set_token_in_kwargs` to the config from the error messages that come up. Would it make sense to identify these errors and include "you may need to add _set_token_in_kwargs" for these kinds of cases?

Also, I think the PR is ready for review though I will be refining the docs a bit more.

**Comment by tensorpro** [comment]
I need to update the of the docstring examples that use images as examples to use videos instead, it should be ready for review after that though.

**Comment by amyeroberts** [comment]
@tensorpro Great :) Ping me when that's done and I'll review 👍

**Comment by dipta007** [comment]
Any update on this?

**Pull request closed without merging**
