### PR TITLE
Phi-2 requires a disabled autocast in attention layer

### PR DESCRIPTION
**Pull request by gugarosa**
# What does this PR do?

Phi-2 has an attention overflow issue, and since the model weights were released with a MIT license, there is no short-term solution in replacing them (re-training the model). Therefore, the only solution we could find to cover all corner cases regarding the overflow, is to also disable the autocast in the attention layer.

This update follows the current [model file](https://huggingface.co/microsoft/phi-2/blob/main/modeling_phi.py) we have on `microsoft/phi-2` repository. Additionally, it follows the [previous solution](https://huggingface.co/microsoft/phi-2/blob/834565c23f9b28b96ccbeabe614dd906b6db551a/modeling_phi.py#L347) we had done before the Phi integration.

Please let me know if we can think of any different solutions, or if there is anything else we can do.

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

@susnato @ArthurZucker

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Thanks for the PR! We are not super super fans of context managers for such things. TBH it's not that bad! cc @amyeroberts what's your take?

**Comment by amyeroberts** [comment]
Thanks for adding this fix @gugarosa! 

I don't mind this too much, it's pretty clean and simple :) Let's get @younesbelkada's opinion on whether this will break any other assumptions about weight loading in the library and possible alternatives

**Comment by gugarosa** [comment]
No problems, thanks everyone for looking at it! Hopefully this is a one-time behavior and we will never see it again on future models 🙏

**Review by younesbelkada — COMMENTED** [review]
Hi @gugarosa - thanks a lot for your work on this! 
I am afraid here it might create some unexpected behaviour for users that use `Trainer` with `fp16=True` or `bf16=True` (which turns on autocast) --> by force-setting these to false in the forward method of `PhiAttention` we silently disable autocast for those users. 
E.g. for correctly training with PEFT / QLoRA using autocast is crucial, so this PR might break QLoRA / PEFT convergence silently 
What about educating users on this fix in the documentation? Do you think we can reasonably convert this PR to adding an appropriate section on Phi docs about educating users on how to fix the issue you mentioned on the PR?

**Comment by akjindal53244** [comment]
Hi @gugarosa , seems like we are still having loss issue: https://github.com/huggingface/transformers/issues/28488#issuecomment-1940449050

**Comment by gugarosa** [comment]
Sorry for the extremely delayed response.

Sounds good, I will update the documentation.

**Pull request closed without merging**
