### PR TITLE
Clean imports to fix test_fetcher

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

We noticed that a lot of tests are being picked from some modeling files, there are two reasons for that.

1. The circular import being `modeling_tf_utils` and `modelcard` makes `modeling_tf_utils` be a file impacted by `modelcard`. `modeling_tf_utils` triggers pretty much all tests as it's tightly linked to `modeling_utils` via `modeling_tf_pytorch_utils`.
2. ONNX also has some circular thing going on as:
    - it's imported in models that define an ONNX Config
    - and in return the module imports all models having an ONNX Config in `onnx.features`

This was discovered by developing a tool that prints the tree of depending modules for a given module/test which is incuded in this PR. To use it, in the root of the repo, just do:
```
python utils/tests_fetcher.py --print_dependencies_of src/transformers/models/bert/modeling_bert.py
```

The fix for 1 is to use the special comment that will make the `test_fetcher` ignore the circular import.

The fix for 2 is to remove all configs imports in `onnx.feaures` but rely on the config names, then import them dynamically at the creation of `FeaturesManager` (in a 100% backward compatible manner).

cc @ydshieh since you reported the slowdown.

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Thanks a lot for the clean-up of these circular imports! I can also confirm that that ONNX slow test all pass with this change :)

**Review by patrickvonplaten — APPROVED** [review]
Very nice! Thanks for fixing it

**Review by LysandreJik — APPROVED** [review]
Smart approach! Glad to hear it resolves the testing issues.

**Comment by sgugger** [comment]
Failure is flaky, so merging :-)

**Pull request merged**
