### PR TITLE
Remove `pos` from _build_network_inputs

### PR DESCRIPTION
**Pull request by tanmoyio**
@NielsRogge 
https://github.com/huggingface/transformers/issues/15971

### CODE REVIEW

**Comment by tanmoyio** [comment]
@Rocketknight1 is it mergeable ?

**Comment by Rocketknight1** [comment]
Hi, I don't know much about this issue unfortunately. Does it relate to the issue from @NielsRogge ?

**Review by NielsRogge — APPROVED** [review]
Thanks for fixing!

**Review by NielsRogge — COMMENTED** [review]
Hi,

Sorry after looking into the code, it doesn't seem like this is mergeable. The reason is that the `PerceiverAudioPreprocessor` class is used in the `PerceiverMultimodalPreprocessor` class. The latter takes a bunch of modality-specific preprocessors as input, and passes `pos=pos `to each of those preprocessors. However, if we drop the "pos" for the audio preprocessor, but keep it for the others, the code will fail.

So to make it work, one should remove the pos argument from all preprocessors; meaning `PerceiverImagePreprocessor`, `PerceiverOneHotPreprocessor` and `PerceiverAudioPreprocessor`.

Next, in the `PerceiverMultimodalPreprocessor` class, passing the `pos` argument can be dropped.

**Pull request closed without merging**
