### PR TITLE
Patch GPU failures

### LINKED ISSUE #6182: Failing XLMModelTest
https://github.com/huggingface/transformers/runs/929962952?check_suite_focus=true

FAILED tests/test_modeling_xlm.py::XLMModelTest::test_inputs_embeds - RuntimeError

Failure introduced somewhere in here:
```
* d951c14a Sylvain Gugger: Model output test (#6155) -   (8 hours ago)
* 86caab1e Sylvain Gugger: Harmonize both Trainers API (#6157) -   (8 hours ago)
* 603cd81a Mehrdad Farahani: readme m3hrdadfi/albert-fa-base-v2 (#6153) -   (11 hours ago)
* 838dc06f Suraj Patil: parse arguments from dict (#4869) -   (13 hours ago)
* cf3cf304 Paul O'Leary McCann: Replace mecab-python3 with fugashi for Japanese tokenization (#6086) -   (13 hours ago)
* f250beb8 Stas Bekman: enable easy checkout switch (#5645) -   (13 hours ago)
* 7d50af4b kolk: Create README.md (#6169) -   (13 hours ago)
* 0034a1d2 Prajjwal Bhargava: Add Pytorch Native AMP support in Trainer (#6151) -   (13 hours ago)
* 7231f7b5 Funtowicz Morgan: Enable ONNX/ONNXRuntime optimizations through converter script (#6131) -   (14 hours ago)
* c0b93a1c Stas Bekman: correct the correction (#6163) -   (23 hours ago)
* a2f6d521 Stas Bekman: typos (#6162) -   (24 hours ago)
* f3065abd Sylvain Gugger: Doc tokenizer (#6110) -   (26 hours ago)
* e642c789 guillaume-be: Addition of a DialoguePipeline (#5516) -   (27 hours ago)
* ec026747 Lysandre Debut: Fix FlauBERT GPU test (#6142) -   (30 hours ago)
* 91cb9546 Sylvain Gugger: Switch from return_tuple to return_dict (#6138) -   (32 hours ago)
* 562b6369 Sylvain Gugger: Tf trainer cleanup (#6143) -   (32 hours ago)
* c127d055 Oren Amsalem: add another e.g. to avoid confusion (#6055) -   (32 hours ago)
* d24ea708 Oren Amsalem: Actually the extra_id are from 0-99 and not from 1-100 (#5967) -   (35 hours ago)
* 3212b885 Stas Bekman: [s2s] add support for overriding config params (#6149) -   (2 days ago)
* 54f9fbef Julien Plu: Rework TF trainer (#6038) -   (2 days ago)
* 3f94170a Lysandre Debut: [WIP] Test TF Flaubert + Add {XLM, Flaubert}{TokenClassification, MultipleC… (#5614) -   (2 days ago)
* 8a8ae276 Sylvain Gugger: Use google style to document properties (#6130) -   (2 days ago)
* fc64559c Julien Plu: Fix TF CTRL model naming (#6134) -   (2 days ago)
* 641b873c Lysandre Debut: XLNet PLM Readme (#6121) -   (2 days ago)
* 8d157c93 Timo Moeller: add deepset/xlm-roberta-large-squad2 model card (#6128) -   (2 days ago)
* 6c002853 Funtowicz Morgan: Added capability to quantize a model while exporting through ONNX. (#6089) -   (2 days ago)
* 25de74cc Sylvain Gugger: Use FutureWarning to deprecate (#6111) -   (3 days ago)
* 640550fc Funtowicz Morgan: ONNX documentation (#5992) -   (3 days ago)
```

Any idea on this @sgugger or @LysandreJik  ? Otherwise I'll dig in.

### PR DESCRIPTION
**Pull request by LysandreJik**
Pins torch != 1.6.0 as this version fails with random CUDA errors.

Fixes XLM when no `lengths` are specified.

Fix https://github.com/huggingface/transformers/issues/6182

### CODE REVIEW

**Review by sshleifer — APPROVED** [review]

**Comment by sgugger** [comment]
As mentioned in #6277, this will be problematic since Reformer fails on pytorch < 1.6.0.

**Comment by LysandreJik** [comment]
Indeed, this will be a problem. The issue with keeping torch 1.6.0 for these tests is that the error is indecipherable. It can't be reproduced on CPU, and on GPU fails 1/4 times when only a few tests are selected, with untrackable CUDA errors. Pinging @patrickvonplaten for discussion.

**Comment by patrickvonplaten** [comment]
> Indeed, this will be a problem. The issue with keeping torch 1.6.0 for these tests is that the error is indecipherable. It can't be reproduced on CPU, and on GPU fails 1/4 times when only a few tests are selected, with untrackable CUDA errors. Pinging @patrickvonplaten for discussion.

As discussed internally, I guess we can revert the PR causing #6277

**Comment by patrickvonplaten** [comment]
> As mentioned in #6277, this will be problematic since Reformer fails on pytorch < 1.6.0.

https://github.com/huggingface/transformers/pull/6300 This should fix it. Wolud be great if you can review and merge if OK.

**Comment by LysandreJik** [comment]
Great, thanks a lot @patrickvonplaten !

**Pull request merged**
