### PR TITLE
[WIP] Add VGCN-BERT model

### LINKED ISSUE #24038: Add VGCN-BERT model
### Model description

HI, I am the author of [VGCN-BERT paper](https://arxiv.org/abs/2004.05707), the original implementation is in my gitlab [vgcn-bert repo](https://github.com/Louis-udm/VGCN-BERT), but recently I updated the algorithm and implemented a new version for integrating in Transformer.

> Much progress has been made recently on text classification with methods based on neural networks. In particular, models using attention mechanism such as BERT have shown to have the capability of capturing the contextual information within a sentence or document. However, their ability of capturing the global information about the vocabulary of a language is more limited. This latter is the strength of Graph Convolutional Networks (GCN). In this paper, we propose VGCN-BERT model which combines the capability of BERT with a Vocabulary Graph Convolutional Network (VGCN). Local information and global information interact through different layers of BERT, allowing them to influence mutually and to build together a final representation for classification. In our experiments on several text classification datasets, our approach outperforms BERT and GCN alone, and achieve higher effectiveness than that reported in previous studies.

I actually finished the integration of my new version and opened the PR. This new VGCN-BERT algorithm has the following improvements:
- Greatly speeds up the calculation speed of embedding vocabulary graph convolutinal network (or Word Graph embedding). Taking CoLa as an example, the new model only increases the training time by 11% compared with the base model
- Updated subgraph selection algorithm.
- Currently using DistilBert as the base model, but it is easy to migrate to other models.
- Provide two graph construction methods in vgcn_bert/modeling_graph.py (the same NPMI statistical method as the paper, and the predefined entity-relationship mapping method)

I hope that after integrating into transformers, someone can discover some more practical use case. I am ashamed to say that I have not discovered too much real use cases myself, mainly because the word-grounded graph obtained through statistical methods has limited improvement on the LLM model. I think its potential application should be when there are specific/customized graphs that need to be integrated into LLM.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

https://arxiv.org/abs/2004.05707
https://github.com/Louis-udm/VGCN-BERT

### PR DESCRIPTION
**Pull request by Louis-udm**
# What does this PR do?
Adds the VGCN-BERT model from [VGCN-BERT: Augmenting BERT with Graph Embedding for Text Classification](https://arxiv.org/abs/2004.05707) paper.

Fixes #24038 (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. [24038](https://github.com/huggingface/transformers/issues/24038)
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @ArthurZucker @younesbelkada

**Comment by ArthurZucker** [comment]
Hey! Thanks a lot for opening this PR 🔥 
We have been pushing a lot for models to be on the hub, as it is a lot easier to implement ! What do you think about trying [this tutorial out](https://huggingface.co/docs/transformers/custom_models)!

**Comment by Louis-udm** [comment]
> Hey! Thanks a lot for opening this PR 🔥 We have been pushing a lot for models to be on the hub, as it is a lot easier to implement ! What do you think about trying [this tutorial out](https://huggingface.co/docs/transformers/custom_models)!

Thanks for your reply @ArthurZucker . I am trying with the new way and put model with code to [here in hub](https://huggingface.co/zhibinlu/vgcn-bert-distilbert-base-uncased)
but I found I can not put my `modeling_graph.py` in my upload script with this function `model.push_to_hub`, also,
how to put model.safetensors instead of moel.bin
how to put other files like README.md (I create manually in the hub UI), tokenizer.json etc

```
from vgcn_bert.configuration_vgcn_bert import VGCNBertConfig
from vgcn_bert.modeling_vgcn_bert import VGCNBertModel, VGCNBertForMaskedLM, VGCNBertForMultipleChoice, VGCNBertForQuestionAnswering, VGCNBertForSequenceClassification, VGCNBertForTokenClassification

import transformers as tfr
from vgcn_bert.modeling_graph import WordGraph

VGCNBertConfig.register_for_auto_class()
VGCNBertModel.register_for_auto_class("AutoModel")
VGCNBertForMaskedLM.register_for_auto_class("AutoModelForMaskedLM")
VGCNBertForMultipleChoice.register_for_auto_class("AutoModelForMultipleChoice")
VGCNBertForQuestionAnswering.register_for_auto_class("AutoModelForQuestionAnswering")
VGCNBertForSequenceClassification.register_for_auto_class("AutoModelForSequenceClassification")
VGCNBertForTokenClassification.register_for_auto_class("AutoModelForTokenClassification")

tokenizer = tfr.AutoTokenizer.from_pretrained(
    "zhibinlu/vgcn-distilbert-base-uncased"
)

model = VGCNBertModel.from_pretrained(
    "zhibinlu/vgcn-distilbert-base-uncased",
)

from huggingface_hub import notebook_login

notebook_login()
model.push_to_hub("vgcn-bert-distilbert-base-uncased")
```

**Comment by ArthurZucker** [comment]
Oups your question slipped through the cracks, let me answers to the best of my knowledge

**Comment by Louis-udm** [comment]
> > 1. I found I can not put my modeling_graph.py in my upload script with this function model.push_to_hub.
> > 2. Also, people need import it using from transformers.models.vgcn_bert.modeling_graph import WordGraph in this PR, but do you have a suggestion when I put it in hub?
> > 3. And, how to put model.safetensors instead of model.bin;
> > 4. how to put other files like README.md (I create manually in the hub UI), tokenizer.json etc.
> 
> 1. That is expected, if you have a look at this [doc page](https://huggingface.co/docs/hub/models-uploading#using-the-huggingfacehub-client-library), it will help you upload the actual code. `push_to_hub` is not made for this!
> 2. When you put the code on the hub (using `upload` or equivalent), then you simply need to create a `config.json`. If you want an example, here is [one](https://huggingface.co/tiiuae/falcon-7b/blob/main/config.json). Falcon is hosted on the hub.
> 3. You should be able to save the safetensors weights using `use_safetensors=True` option when pushing to the hub/saving the model.
> 4. The readme can also be uploaded on the hub like any other files. You can push the tokenizer using `tokenizer.push_to_hub("path")`
> 
> hope this helps you

@ArthurZucker Ok, these answers will help me, after getting rid of all the problems, I will cancel this PR.

**Comment by Louis-udm** [comment]
The new implement is here:
https://huggingface.co/zhibinlu/vgcn-bert-distilbert-base-uncased

**Comment by ArthurZucker** [comment]
Thanks a lot for sharing this and adding this model! 🔥

**Pull request closed without merging**
