### PR TITLE
[examples/language-modeling] Add dataset download instructions

### PR DESCRIPTION
**Pull request by stas00**
I had to hunt for instructions to get the dataset used in this set of examples, so this PR proposes to add them to README.md.

@patrickvonplaten

### CODE REVIEW

**Comment by thomwolf** [comment]
Isn’t this one simply on the [HuggingFace datasets hub](
https://huggingface.co/datasets) by the way?

Op wo 30 dec. 2020 om 07:50 schreef Stas Bekman <notifications@github.com>

**Comment by stas00** [comment]
Sure, let's have the equivalent instructions to retrieve that from HF dataset. It doesn't really matter where it comes from as long as it doesn't require the user to go and search for it.

**Comment by sgugger** [comment]
There is no need to download the data manually with the new scripts, it is done automatically by the datasets library. So this should not be added in my opinion.

**Comment by stas00** [comment]
oh, ok, I guess I didn't pay attention to the command line being changed and assumed that I needed to get the dataset first.

I stand corrected. Thank you for your feedback.

**Pull request closed without merging**
