### PR TITLE
fix: sampling in flax keeps EOS

### LINKED ISSUE #28377: Flax generate sampling does not return EOS
### System Info

When calling `flax_model.generate(do_sample=True)`, we can notice that the EOS token has been replaced with PAD token.

Configuration:
```
- `transformers` version: 4.37.0.dev0
- Platform: Linux-5.4.0-1043-gcp-x86_64-with-glibc2.31
- Python version: 3.10.12
- Huggingface_hub version: 0.20.1
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.1+cu121 (False)
- Tensorflow version (GPU?): 2.12.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.7.4 (tpu)
- Jax version: 0.4.14
- JaxLib version: 0.4.14
- Using GPU in script?: Noe
- Using distributed or parallel set-up in script?: No
```

### Who can help?

@sanchit-gandhi @gante 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Use `FlaxBartForConditionalGeneration`
2. Change generate method to `do_sample=True, num_beams=1`
3. When decoding, display all special tokens

Here is adapted script:
```
from transformers import AutoTokenizer, FlaxBartForConditionalGeneration

model = FlaxBartForConditionalGeneration.from_pretrained("facebook/bart-large-cnn")
tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")

ARTICLE_TO_SUMMARIZE = "My friends are cool but they eat too many carbs."
inputs = tokenizer([ARTICLE_TO_SUMMARIZE], max_length=1024, return_tensors="np")

# Generate Summary
summary_ids = model.generate(inputs["input_ids"], do_sample=True, num_beams=1).sequences
print(tokenizer.batch_decode(summary_ids, skip_special_tokens=False, clean_up_tokenization_spaces=False))
```

The output does not contain EOS `</s>` at the end before PAD tokens `<pad>`:
`["</s><s><s>My friends are cool but they eat too many carbs. I love carbs. The carb-averse among us have a love for dessert on this one. I've got some amazing desserts. I've been a junkie for 10 years. I can't go straight after dinner, I've been eating for 4. I love it. That's why I made the TV show.<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"]`

The same issue happens with any decoder model.

### Expected behavior

EOS token should appear before the sequence of PAD tokens.

### PR DESCRIPTION
**Pull request by borisdayma**
# What does this PR do?

Fixes #28377

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. @sanchit-gandhi

### CODE REVIEW

**Comment by borisdayma** [comment]
Running the same example listed in #28377, we get the correct output with EOS token present before the PAD tokens:
`["</s><s><s>My friends are cool but they eat too many carbs. I love carbs. The carb-averse among us have a love for dessert on this one. I've got some amazing desserts. I've been a junkie for 10 years. I can't go straight after dinner, I've been eating for 4. I love it. That's why I made the TV show.</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>"]`

**Review by gante — APPROVED** [review]
LGTM, thank you for the fix!

**Review by ArthurZucker — APPROVED** [review]
Thanks! Not generation tests were failing? 🤗 would expect some to include testing against decoded version. Could you run for Llama for example?

**Review by sanchit-gandhi — APPROVED** [review]
Thanks for the fix @borisdayma!

**Pull request merged**
