### PR TITLE
[TENTATIVE] Updating variable names HUGGINGFACE_CO_RESOLVE_ENDPOINT into HF_ENDPOINT.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

`HUGGINGFACE_CO_RESOLVE_ENDPOINT` is deprecated and will go away in favor
of `HF_ENDPOINT`.

In order to maximize consistency, this PR renames the variable name itself.

This is tentative, since there might have been reasons to keep the old name for
the variable.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@LysandreJik @sgugger

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
This is purely cosmetic and internal, so I don't really see the point. We usually don't bother with renaming in those situations.

**Comment by Narsil** [comment]
> This is purely cosmetic and internal, so I don't really see the point. We usually don't bother with renaming in those situations.

Is there any downsides to making the modifications ?

Consistency in naming has a lot of merits, especially within HF ecosystem where the name is used in many different places and different repos. Here for instance, it took me several tries to find all variables that needed to be overridden in `datasets`, `transformers` and `huggingface_hub`. Changing the name increases the chances that new code respects that convention.

**Comment by LysandreJik** [comment]
I think the renaming here makes sense as that's the variable name in other repositories; since there are no downsides, ok for me!

**Review by LysandreJik — APPROVED** [review]
Good change for me for consistency!

**Pull request merged**
