### PR TITLE
remove failing tests and clean FE files

### PR DESCRIPTION
**Pull request by ylacombe**
# What does this PR do?

Fixes [this](https://app.circleci.com/pipelines/github/huggingface/transformers/77846/workflows/8ed051fc-a105-462e-9097-91e919374c6e/jobs/992100), which was introduced by #26339.

To explain a bit, in #26339 I've mutualised an overriding of `to_dict` which deleted `mel_filters` and `windows`. The failing test was testing to retrieve those parameters to assert equality.

I've also cleaned a bit feature extractors that overrode `to_dict`.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for updating!

**Comment by amyeroberts** [comment]
Could you run the feature extraction tests for all the audio models to double check they're passing before merging please!

**Comment by ylacombe** [comment]
Sure thing!

**Comment by ylacombe** [comment]
I've double check every audio models! Everything passes

**Comment by ylacombe** [comment]
I do, it's merged!

**Pull request merged**
