### PR TITLE
Fix a few typos in `GenerationMixin`'s docstring

### PR DESCRIPTION
**Pull request by sadra-barikbin**
Hi there!

To fix a few typos in `GenerationMixin`'s docstring.

@gante

### CODE REVIEW

**Comment by sadra-barikbin** [comment]
Shouldn't we change the parameter shape in 

https://github.com/huggingface/transformers/blob/c8d98405a8f7b0e5d07391b671dcc61bb9d7bad5/src/transformers/generation/utils.py#L146

to `(batch_size*num_return_sequences, sequence_length)` to account for `SampleOutput` and its variants which have `do_sample=True, num_return_sequences>1`?

**Review by gante — APPROVED** [review]
Thank you for the fixes 💛

**Comment by gante** [comment]
> Shouldn't we change the parameter shape in
> 
> https://github.com/huggingface/transformers/blob/c8d98405a8f7b0e5d07391b671dcc61bb9d7bad5/src/transformers/generation/utils.py#L146
> 
> to `(batch_size*num_return_sequences, sequence_length)` to account for `SampleOutput` and its variants which have `do_sample=True, num_return_sequences>1`?

yes, absolutely!

**Review by ArthurZucker — APPROVED** [review]
🧼 good typo catches !

**Pull request merged**
