### PR TITLE
Fix the structure of images in PixtralProcessor

### PR DESCRIPTION
**Pull request by Rocketknight1**
The `PixtralProcessor` has some issues regarding correct nesting depth of inputs. If we are fully explicit about input nesting, then `text` should be `List[str]` and `images` should be `List[List[Image]]`. This is because each sample only has one text, but can have multiple images.

The start of the Pixtral processor code handles cases when users don't supply fully nested inputs. However, it uses the heuristic that if the user passes `List[str]` for `text` and `List[Image]` for `images`, then this indicates **one image per sample**. This is [very confusing](https://github.com/huggingface/transformers/pull/34332#issuecomment-2519369424) for users, especially because it means output changes when `batch_size==1`, depending on whether that single input is passed as `str` or `[str]`.

With this PR, we avoid that assumption. If the user supplies a single image or flat list of images, then we assign them all to the first sample in the event that `batch_size==1`. If `batch_size>1` then we throw an error, asking them to supply an explicit list of lists instead. This seems much safer!

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @yurkoff-mv, can you try out this PR and confirm it resolves the issues you were having?

**Comment by Rocketknight1** [comment]
also cc @zucchini-nlp and @arthurzucker / @LysandreJik for core maintainer review

**Review by ArthurZucker — COMMENTED** [review]
Cool, the new errors have to be tested and the doc should mention this to remove confusion!

**Review by zucchini-nlp — COMMENTED** [review]
i am wondering, is there any specific reason to support such a complex processing if at the end we end up flattening it in the modeling code. I think we should support both flat list/batch list as inputs similar to most other VLMs without trying to batch-list inputs before passing them to processors

 It can help us in the long run to get standardized processors

**Comment by Rocketknight1** [comment]
Hi @zucchini-nlp, how do the inputs differ here compared to most other processors? I thought `text = List[str]` and `images = List[List[Image]]` was pretty normal!

**Comment by zucchini-nlp** [comment]
@Rocketknight1 usually we support both formats, as `List[List[image]]` and simply `List[image]`, except for some cases like in Idefics where the cross attention module needs to know how many images each prompt should attend to. Maybe we can also ask @yonigozlan, he's working on standardizing processor input/output format for VLMs

**Comment by Rocketknight1** [comment]
Closing because this has been included in #34801 instead

**Pull request closed without merging**
