### PR TITLE
Use CircleCI `store_test_results`

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

@ArthurZucker loves it.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
More than me loving it, it gives us [access to the slow tests, the flaky tests, the tests that usually fail](https://app.circleci.com/insights/github/huggingface/transformers/workflows/run_tests/tests?branch=make_arthur_eye_happy) etc. Let's add this to all CI jobs!

**Comment by LysandreJik** [comment]
Very cool! Thanks @ydshieh and @ArthurZucker, this looks cool!

**Comment by ydshieh** [comment]
> More than me loving it, it gives us [access to the slow tests, the flaky tests, the tests that usually fail](https://app.circleci.com/insights/github/huggingface/transformers/workflows/run_tests/tests?branch=make_arthur_eye_happy) etc. Let's add this to all CI jobs!

OK!

**Comment by ydshieh** [comment]
@ArthurZucker I think all pytest jobs have this feature enabled. `.circleci/config.yml` doesn't have pytest but just some usual python scripts. Could you elaborate a bit more what you suggest? Thanks!

**Comment by ArthurZucker** [comment]
I mean `check_repository_consistency`, `check_code_quality`, `pr_documentation_test` if possible!

**Comment by ydshieh** [comment]
`pr_documentation_test` is already included in the current change.
The other 2 jobs are not `pytest`, and I am not sure if there is anything we can do similar to `pytest --junitxml=test-results/junit.xml`

**Comment by ArthurZucker** [comment]
We could make them use pytest, but only if you think it’s relevant!

**Comment by ydshieh** [comment]
IMO, those are not really tests but checks of formatting :-). There won't be flaky, and those could not be splitted into individual test **methods** but each script as a whole.

I would rather move forward and take the new feature already available (with this PR) for us even only for the pytest jobs.

Thank you for asking to add this, Sir!

**Review by ArthurZucker — APPROVED** [review]
🚀

**Pull request merged**
