### PR TITLE
link for optimizer names

### PR DESCRIPTION
**Pull request by nbroad1881**
Add a note and link to where the user can find more optimizer names easily because there are many more optimizers than are mentioned in the docstring.

@muellerzr @SunMarc

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Cool! Can you run make fixup to fix cis!

**Review by SunMarc — APPROVED** [review]
Nice ! Thanks for adding @nbroad1881 !

**Comment by nbroad1881** [comment]
How is it now?

**Comment by nbroad1881** [comment]
Did I mess up the rebase?

**Comment by muellerzr** [comment]
@nbroad1881 probably 😓 those are always fun. You can either reset hard or open a PR

**Comment by amyeroberts** [comment]
@nbroad1881 From the commit history, it looks like you pushed after rebase but didn't push force (I know because I've done this myself... ). You should be able to force push again to resolve

**Comment by nbroad1881** [comment]
Ok I think I fixed it :sweat_smile:

**Pull request merged**
