### PR TITLE
fix typos in FSDP config parsing logic in `TrainingArguments`

### PR DESCRIPTION
**Pull request by yundai424**
# What does this PR do?

There're 2 typos in how `TrainingArguments` is parsing the provided FSDP config.
1. We should not expect a leading `fsdp_` in user-provided config as 1) this is not how the docstring suggests, 2) other fields don't expect this
2. `prefect` should be `prefetch`

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
- trainer: @muellerzr and @pacman100

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
LGTM

**Comment by ArthurZucker** [comment]
Might need to add a test!

**Review by muellerzr — COMMENTED** [review]
LG2M as well, I'd like @pacman100 to have a final review though

**Review by pacman100 — APPROVED** [review]
oops, thank you @yundai424!

**Pull request merged**
