### PR TITLE
Separate implementation for Torch-Scriptable BERT model

### LINKED ISSUE #5067: Modify BERT/BERT-descendants to be TorchScript-able (not just traceable)
# 🚀 Feature request

Modify BERT models (src/transformers/modeling_bert.py) to conform to TorchScript requirements, so they can be ``jit.script()``-ed, not just ``jit.trace()``-ed (as is [currently the only supported option](https://huggingface.co/transformers/torchscript.html))

*Note:* I have a working version implementing this, which I would like to contribute.
See below.

## Motivation
A scriptable model would allow for variable-length input, offering big speedup gains and simplification (no need to create different models for different input lengths).

In addition, it would avoid other potential pitfalls with tracing (e.g., code paths that are input dependent and not covered by the tracing example input).

Related issues:
https://github.com/huggingface/transformers/issues/2417
https://github.com/huggingface/transformers/issues/1204
possibly also
https://github.com/huggingface/transformers/issues/1477
https://github.com/huggingface/transformers/issues/902

## Your contribution
I have a working PR that modifies all the models in src/transformers/modeling_bert.py and makes them TorchScript-able. I have not tested it on other models that use BERT components (e.g., albert), but it should be possible to expand the capability to those, as well.

However, it would require some significant work to make it ready for submission: besides formatting, documentation, testing etc., my current version changes the method signatures, and I would need to avoid that to maintain backward-compatibility.

Before putting in that work, I'd like to make sure that such a PR is something you'd be interested in and would be willing to merge in, assuming it meets the requirements.

### PR DESCRIPTION
**Pull request by sbrody18**
Fixes #5067 

Separate (re-)implementation of BERT such that it can be used with TorchScript's script() method (not just trace). This allows for better/more reliable handling of internal model logic and removes the requirement for fixed input size, resulting in large speedups when average input size is << than max input size.

Tests duplicate all the ones on the original BERT model, with the only fundamental difference being the test_torchscript* tests, which now use script() rather than trace().

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks a lot for doing this! It's a great way for us to realize the needed changes to get fully torch-scriptable models. Aside from the tests (we can help fix them once the design is approved), I'd love to see what parts we can reuse from bert (with potential non-harmful modifications) and what parts need to be rewritten because they're not compatible with the rest of our API.

For instance, the change in the embeddings layer is just a type annotation which we could do in bert (it would be a nice addition) and then import that layer. On the other hand, the whole parts with `return_dict` are probably fully incompatible with scripting.

I guess in an ideal world, we would reuse the same internal layers from bert and only change the full models if that is possible.

**Comment by sbrody18** [comment]
As you can see in a [previous comment on the thread](https://github.com/huggingface/transformers/issues/5067#issuecomment-662586999) my initial implementation tried to go the minimal-duplication route. I modified the original models to be scriptable, and then had a thin wrapper around them to transform the output into dictionary form.
So basically, you had BertScriptableModel returning a tuple of fixed size, and BertModel who's forward just ran BertScriptableModel and put the output in a dictionary, to keep the interface.
The main issue with that was that the code kept changing. Other than that, it should be doable.

**Comment by sbrody18** [comment]
90% of the changes were type annotations, and assertions about Nullity (which would improve the code quality regardless).
The added bonus of the minimal duplication route is that it makes it easier to convert other models that use BERT components, e.g., Albert.

**Comment by sgugger** [comment]
Yes, I can see that clearly now. Sorry for going back and forth with you on this. We definitely want the type annotations in the main bert file, and I think the first implementation is better on that regard. It just misses the `return_dict` argument, which is easy to add with the way you designed things (happy to do it myself if you give me access to a branch).

**Comment by sbrody18** [comment]
The previous implementation is at https://github.com/sbrody18/transformers/tree/scripting
As mentioned, it is a behind head, and still needs some work.
I sent an invite for access to my repo. Let me know if there's a better way to share the branch.

**Comment by sgugger** [comment]
Yes, saw the invite and accepted it. I have some stuff to finish but it's on my TODO and I hope to be able to add the missing stuff before the end of the week. Do you prefer a PR or can I directly commit on this branch?

**Comment by sbrody18** [comment]
No rush on my side.
A PR might be better, to make it easier to comment, but direct is fine if that's too much trouble.

**Comment by patrickvonplaten** [comment]
Super cool PR!
I can tweak our benchmarking tools a bit to get some numbers on speed improvements using your scriptable Bert model tomorrow

**Comment by sbrody18** [comment]
@patrickvonplaten That would be great!
The major improvement is expected when running a large set of inputs with varying lengths, individually or in small batches (that's where not having to pad to max_length would come into play)

**Comment by patrickvonplaten** [comment]
> @patrickvonplaten That would be great!
> The major improvement is expected when running a large set of inputs with varying lengths, individually or in small batches (that's where not having to pad to max_length would come into play)

Got it!

**Comment by LysandreJik** [comment]
This is great, looking forward to this PR!

**Comment by patrickvonplaten** [comment]
Okey I did some benchmarking, which can be seen here: https://github.com/huggingface/transformers/pull/6907. 

@sbrody18 - it would be awesome if you could take a look if I am using the function correctly.

**Comment by sgugger** [comment]
Ok, after reviewing this PR and the other design in [this diff](https://github.com/huggingface/transformers/compare/clean_scripting?expand=1), along with @patrickvonplaten benchmark results in #6907 we've come to the conclusion that adding scriptable layers is a bit too much for almost no gain, since `script` and `trace` now have the same speed in PyTorch.

All type annotations and asserts are welcome additions on the other hand, if you want to suggest a PR with just those changes.

**Comment by sbrody18** [comment]
Sure. Makes sense. I'll see if I can put one together, but other things might take priority.
Thanks for all the work you've put in to look into this.

**Comment by patrickvonplaten** [comment]
@sbrody18 - Thanks a lot for making us aware of this issue! I learned a lot about the differences between `torch.jit.trace` and `torch.jit.script` thanks to you!

**Comment by sgugger** [comment]
Yes thanks a lot for all your work on this, I learned a lot on scriptable pytorch modules thanks to the PR!

**Comment by adampauls** [comment]
I just wanted to point out that, IIUC, a big benefit of making everything scriptable is free reuse from languages other than Python (for example, from the C++ frontend). I know that the prescribed setup is to train in python, trace, then deploy at runtime with a traced TorchScript, but the freedom to train from C++, or even the JVM with a few extra bindings, is a pretty big win.

**Pull request closed without merging**
