### PR TITLE
[wip: testing doc-builder]

### PR DESCRIPTION
**Pull request by mishig25**
testing https://github.com/huggingface/doc-builder/pull/373

### CODE REVIEW

**Comment by xenova** [comment]
@mishig25 Should be fixed by [this](https://github.com/huggingface/doc-builder/pull/373/commits/4895cfbf332994c5c5d73e83f990fe017184ecc5)

**Comment by mishig25** [comment]
Rerunning the doc-build https://github.com/huggingface/transformers/actions/runs/5036878423

**Comment by mishig25** [comment]
Re running the doc-build: https://github.com/huggingface/transformers/actions/runs/5036878423

**Comment by xenova** [comment]
Latest error message is:
```
<img> is a void element and cannot have children, or a closing tag
```
which appears to be an error by the person who made the docs? In the original version, did you attempt to fix those for the user?

**Comment by xenova** [comment]
Confirmed (https://huggingface.co/docs/transformers/v4.29.1/pt/index):
image

**Comment by xenova** [comment]
I made a PR to fix the closing tag https://github.com/huggingface/transformers/pull/23646

**Comment by xenova** [comment]
Well yes since `</img>` is invalid, svelte complains.

Previously, the error was not being detected because </img> was being encoded

**Pull request closed without merging**
