### PR TITLE
vectorize PrefixConstrainedLogitsProcessor

### LINKED ISSUE #25217: Scoring translations is unacceptably slow
### System Info

- `transformers` version: 4.29.0
- Platform: Linux-3.10.0-862.11.6.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.16
- Huggingface_hub version: 0.12.1
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker and @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Install transformers, pytorch, tqdm
2. Create `forced_decode.py` [^1] 
3. Create `repro.sh` [^2]
4. Run `bash repro.sh` and observe extremely slow scoring speeds.

[^1]: 
    ```python
    #!/usr/bin/env python3
    
    import itertools
    from argparse import ArgumentParser, FileType
    from tqdm import tqdm
    
    import torch
    
    from transformers import PrefixConstrainedLogitsProcessor, AutoTokenizer, AutoModelForSeq2SeqLM
    
    def setup_argparse():
        parser = ArgumentParser()
        parser.add_argument("-t", "--tokenizer", type=str, required=True)
        parser.add_argument("-m", "--model", type=str, required=True)
        parser.add_argument("-bs", "--batch-size", type=int, default=16)
        parser.add_argument("-i", "--input", type=FileType("r"), default="-")
        parser.add_argument("-o", "--output", type=FileType("w"), default="-")
        parser.add_argument("-d", "--delimiter", type=str, default="\t")
        parser.add_argument("--device", type=str, default="cpu")
        return parser
    
    
    def create_processor_fn(ref_tokens_by_segment):
        def inner(batch_id, _):
            return ref_tokens_by_segment[batch_id]
        return inner
    
    def tokenize(src, tgt, tokenizer):
        inputs = tokenizer(src, text_target=tgt, padding=True, return_tensors="pt")
        return inputs
    
    def forced_decode(inputs, model, num_beams=5):
        inputs = inputs.to(model.device)
        logit_processor = PrefixConstrainedLogitsProcessor(create_processor_fn(inputs["labels"]), num_beams=num_beams)
        output = model.generate(**inputs, num_beams=num_beams, logits_processor=[logit_processor], return_dict_in_generate=True, output_scores=True)
        return output.sequences_scores.tolist()
    
    def batch_lines(it, batch_size):
        it = iter(it)
        item = list(itertools.islice(it, batch_size))
        while item:
            yield item
            item = list(itertools.islice(it, batch_size))
    
    if __name__ == "__main__":
        args = setup_argparse().parse_args()
        f_tokenizer = AutoTokenizer.from_pretrained(args.tokenizer)
        f_model = torch.compile(AutoModelForSeq2SeqLM.from_pretrained(args.model).to(args.device))
    
        with args.input as fin:
            inputs = list(batch_lines(map(str.strip, fin), args.batch_size))
    
        inputs_logits = []
        for batch in tqdm(inputs):
            src, tgt = zip(*[line.split(args.delimiter) for line in batch])
            inputs_logits.append(tokenize(src, tgt, f_tokenizer))
    
        with args.output as fout, torch.no_grad():
            for input in tqdm(inputs_logits):
                scores = forced_decode(input, f_model)
                print(*scores, sep="\n", file=fout)
    ```

[^2]:

    ```bash
    #!/usr/bin/env bash
    
    function get_input {
      curl -s https://gist.githubusercontent.com/erip/e37283b8f51d4e2c16996fc8a6a01aa7/raw/f5a3daffb04dad76464188c2a6949649f5cf3f9c/en-de.tsv
    }
    
    python forced_decode.py \
       -t Helsinki-NLP/opus-mt-en-de -m Helsinki-NLP/opus-mt-en-de \
       -i <(get_input) \
       --device cuda:0 \
       -bs 16
    ```

### Expected behavior

Scoring should be _very fast_ since the beam doesn't actually need to be searched, but I'm finding speeds on the order of seconds per batch which is far slower than generating.

### PR DESCRIPTION
**Pull request by erip**
# What does this PR do?

Fixes #25217 (in part).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@gante

### CODE REVIEW

**Comment by erip** [comment]
There's a silly shape thing happening here which I'll try to debug ASAP (unless others are interested). Unfortunately testing locally is not working since I'm on Silicon and some dependencies for dev aren't available ☹️  but this looks close. I'll want to think hard about the vectorization of the function (which is slightly different and hopefully not breaking).

**Comment by gante** [comment]
@erip thank you for jumping into the issue 💪  LMK when it is ready for review (assuming it yields speedups)

**Comment by erip** [comment]
cc @gante I think this is ready for review. Nothing too controversial here, but I can add a fallback to original behavior in case the fn doesn't support vectorization.

**Comment by erip** [comment]
Hmm, I just tested this hoping to benchmark against the original unvectorized impl and it seems like it's not quite ready.

**Pull request closed without merging**
