### PR TITLE
Fix torch.onnx.export of Qwen2-VL vision encoder

### PR DESCRIPTION
**Pull request by xenova**
# What does this PR do?

This PR fixes onnx export support for the vision encoder of Qwen2-VL, which converts the `cu_seqlens` to `torch.int32`, leading to errors later on when using the values for slicing.

Error message:

```
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Slice, node name: /blocks.0/attn/Slice_4): axes has inconsistent type tensor(int64)
```
See https://github.com/microsoft/onnxruntime/issues/13497 for more information.

Since `torch.cumsum` will automatically convert both `torch.int32` and `torch.int64` tensors to `torch.int64` output, I propose we convert it back to the dtype of the inputs.
```py
>>> import torch
>>> torch.tensor([1,2,3], dtype=torch.int32).cumsum(0).dtype
torch.int64
>>> torch.tensor([1,2,3], dtype=torch.int64).cumsum(0).dtype
torch.int64
```

The location of the issues:

https://github.com/huggingface/transformers/blob/c57eafdaa119eecae8557be4c626629bc1adc0fd/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1044-L1046

Code to reproduce the issue:

```py

import requests
from PIL import Image
import torch
from transformers import (
    AutoProcessor,
    Qwen2VLForConditionalGeneration,
)

# Constants
VISION_MODEL_NAME = "vision_encoder.onnx"

# Load model and processor
model_id = "hf-internal-testing/tiny-random-Qwen2VLForConditionalGeneration"
model = Qwen2VLForConditionalGeneration.from_pretrained(model_id).eval()
processor = AutoProcessor.from_pretrained(model_id)

# Prepare inputs
url = "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg"
image = Image.open(requests.get(url, stream=True).raw)
conversation = [
    {
        "role": "user",
        "content": [
            { "type": "image" },
            { "type": "text", "text": "Describe this image."},
        ],
    },
]
images = [image]
text_prompt = processor.apply_chat_template(conversation, add_generation_prompt=True)
inputs = processor(text=[text_prompt], images=images, padding=True, return_tensors="pt")

## Vision model
vision_inputs = dict(
    pixel_values=inputs["pixel_values"],
    grid_thw=inputs["image_grid_thw"],
)
vision_inputs_positional = tuple(vision_inputs.values())
vision_outputs = model.visual.forward(*vision_inputs_positional)  # Test forward pass
torch.onnx.export(
    model.visual,
    args=vision_inputs_positional,
    f=VISION_MODEL_NAME,
    export_params=True,
    opset_version=14,
    do_constant_folding=True,
    input_names=list(vision_inputs.keys()),
    output_names=["image_features"],
    dynamic_axes={
        "pixel_values": {
            0: "batch_size * grid_t * grid_h * grid_w",
            1: "channel * temporal_patch_size * patch_size * patch_size",
        },
        "grid_thw": {0: "batch_size"},
        "image_features": {0: "batch_size * grid_t * grid_h * grid_w"},
    },
)

# Load and check the exported model model
import onnx
model = onnx.load(VISION_MODEL_NAME)
onnx.checker.check_model(model, full_check=True)
inferred = onnx.shape_inference.infer_shapes(model, check_type=True)
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@amyeroberts, @qubvel, @simonJJJ (original PR)

### CODE REVIEW

**Comment by xenova** [comment]
Failing tests seem unrelated to PR, but important to fix

**Comment by qubvel** [comment]
Hi @xenova, thanks for the fix and detailed report! looks good to me!
Can you please push an empty commit with `[run-slow] qwen2_vl` to trigger slow tests as well?

cc @zucchini-nlp for vlms

**Review by zucchini-nlp — APPROVED** [review]
Cool, thanks for enabling onnx in more VLMs! The failing test is flaky so feel free to re-trigger it until it turns green

**Comment by xenova** [comment]
Not sure if caused by this PR, but there is a minor difference in slow test. Other failing slow tests seem unrelated to this PR (torch dynamo).

Is there a way to test whether this was also the case previously?

image

**Comment by qubvel** [comment]
Hi @xenova! You can search in #transformers-ci-daily-models slack channel with the failed test name to see if a target is already there (or with the model name)

**Comment by xenova** [comment]
Got it 👌 Indeed, they seem to have been failing already.

**Review by ArthurZucker — APPROVED** [review]
Nice, a good catch! 🫡

**Comment by zucchini-nlp** [comment]
Qwen2-VL generation seems broken now for FA2 👀  (`RuntimeError: cu_seqlens_q must have dtype int32`)

**Comment by xenova** [comment]
> Qwen2-VL generation seems broken now for FA2 👀 (`RuntimeError: cu_seqlens_q must have dtype int32`)

I'll open a PR to only do the cast when tracing 🫡

**Comment by xenova** [comment]
Update: https://github.com/huggingface/transformers/pull/35016
I added a note to why this is necessary. Hopefully it isn't too verbose :)

**Pull request merged**
