### PR TITLE
update black target version

### PR DESCRIPTION
**Pull request by BramVanroy**
Considering that setup.yp requires Python 3.7 or higher:

https://github.com/huggingface/transformers/blob/22f72185601d5167a747104b4aca102d0e92524c/setup.py#L417

it might make sense to also have black target only Python 3.7. Just a suggestion though.

Unsurprisingly, this PR may trigger quality check errors.

Note sure who to tag, so assuming for general repo things: @sgugger and @LysandreJik

### CODE REVIEW

**Comment by sgugger** [comment]
Looks like it wants to change a looooot of files. This usually creates a hell of merge conflicts in PRs so I would really like to avoid doing it too much. We will switch to black 2023 in January, so how about we change the target at that point too? We can change your PR to leave a comment for now so we don't forget.

**Comment by BramVanroy** [comment]
> Looks like it wants to change a looooot of files. This usually creates a hell of merge conflicts in PRs so I would really like to avoid doing it too much. We will switch to black 2023 in January, so how about we change the target at that point too? We can change your PR to leave a comment for now so we don't forget.

Sure! 

I doidn't quite understand what you mean with the last sentence though. Do you mean closing this PR and opening an issue instead? That works, whatever is best.

**Comment by sgugger** [comment]
Just putting a comment next to the black version pinned in the setup, so that we know to update this at the next version change.

**Comment by BramVanroy** [comment]
> Just putting a comment next to the black version pinned in the setup, so that we know to update this at the next version change.

Alright. Done.

**Review by sgugger — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
