### PR TITLE
build: add poetry, an alternative to setup.py with dependency versions tracked

### PR DESCRIPTION
**Pull request by aurelien-clu**
Hello,
I have written a `pyproject.toml` so your project can be setup using [poetry](https://github.com/python-poetry/poetry) .

That way requirements versions can easily be tracked for people wanting to use **poetry** (it is optional).

# Example

```bash
# first setup your virtual environment, then:
pip install poetry
poetry install  # this is equivalent to 'pip install .' but with versions tracked
poetry install --extras testing # pip install -e ".[testing]"
poetry install --extras examples # pip install -r examples/requirements.txt
poetry install --extras torch  # pip install -e ".[torch]"
poetry install --extras tf  # pip install -e ".[tf]"

# edit: updating dependencies to the latest possible:
poetry update

# adding new dependencies
poetry add MyPyModule
```

# Notes

This does not change any python code, i.e. everything still works :)

### CODE REVIEW

**Comment by julien-c** [comment]
Not sure why this breaks the CI?

Shouldn't we _not_ version control the .lock file?

**Comment by aurelien-clu** [comment]
To me one interesing is to track `.lock` that way you are always certain to have a working versions, i.e. dependencies version that match together.

Indeed I am not sure why the CI fails :/

**Comment by julien-c** [comment]
Pinging @aaugustin our Python-ecosystem/packaging expert on this, but I don’t think we want to commit to maintaining multiple different install systems

**Comment by aurelien-clu** [comment]
```
builder = WheelBuilder(poetry, SystemEnv(Path(sys.prefix)), NullIO())
```

The CI now uses `poetry` for `wheels` which was unexpected to me :/


`poetry build -f wheel` broken for C extensions
#1332 : https://github.com/python-poetry/poetry/issues/1332

I am not for changing the way you build, but only give the option to users to be able to manage dependencies using `poetry` :wink:

**Comment by aurelien-clu** [comment]
I have rebased (sorry for the multiple CI runs)

Some issues where:

- `python 3.5` is needed (I used 3.6 so it complies with `black`), so its matches your `setup.py`
- email address of one authors was not compliant (needs to be: `"author <email>"`)

New error:

```
The following workers failed to return coverage data, ensure that pytest-cov is installed on these workers.
```

I am investigating.

**Comment by aaugustin** [comment]
Like @julien-c said, we don't want to maintain both poetry and setuptools configurations, because this is likely to create confusion and waste everyone's time (which already started with CI in this PR).

Switching to poetry could be a good move, but then we should ditch `setup.py` entirely and make sure all workflows are still operational.

**Comment by aurelien-clu** [comment]
> Like @julien-c said, we don't want to maintain both poetry and setuptools configurations, because this is likely to create confusion and waste everyone's time (which already started with CI in this PR).
> 
> Switching to poetry could be a good move, but then we should ditch `setup.py` entirely and make sure all workflows are still operational.

I am not against you ditch `setup.py` but that's your call :wink: 

As for not wanting to maintain both `poetry` and `setuptools`, maybe there will be people wanting to use `poetry` and will maintain it themselves. This would not mean any extra work for people not wanting to update `poetry` (even if I think maintaining `poetry` does not require much effort, there was some at the beginning and it has been done :wink: )

**Comment by BramVanroy** [comment]
Replying to the discussion about the lock file: in pipenv projects I never share the lock file. Yes, you get better (locked) version control but in practice this does not work cross platform at all. Hashes for slightly more complex packages are mostly platform dependent. Installations between colleagues failed because of this. The lock file is a good idea in practice or for in-house deployment but is not useful in the real world, I think.

**Comment by bryant1410** [comment]
On the lock file discussion, I think it's not worth it to version it in git for libraries, in general. The pro is an almost reproducible environment. Then con is having to constantly keep it up-to-date for new versions of all the dependencies (including the transitive ones), even for little changes (e.g., tqdm from 4.36.0 to 4.36.1). You could also avoid updating it, but then you'd never catch bugs on new versions. So I think it's good to keep reproducibility on python projects that are not libraries, especially when you want to make sure your code works on production as similar to your env as possible.

As an outsider, I see moving to poetry as a good idea. Pros: it works well and fast, specifying the test/dev/docs dependencies, simpler and fewer package configuration files (in theory, only `pyproject.toml`), can check if your env complies with the config file, can specify Python versions, can publish the package easily, more flexibility when specifying the dependencies' versions. The only con I see, apart from learning the tool which should be fast, is that `pip install --editable` wouldn't work as of today for the users.

**Comment by aurelien-clu** [comment]
> in practice this does not work cross platform at all

I agree that's an argument against it.

> Then con is having to constantly keep it up-to-date for new versions of all the dependencies (including the transitive ones), even for little changes (e.g., tqdm from 4.36.0 to 4.36.1).

I see no reason why you would need to keep it up-to-date. To me it is simply a (near) guarantee to be able to have a working environment to develop on the project. No matter if you don't have all the latest updates. Most little changes from dependencies have little to no impact on your own development. (library or project)

Anyhow, feel free to tell me to remove the `.lock` or to close this issue & PR 😉

**Comment by bryant1410** [comment]
> I see no reason why you would need to keep it up-to-date. To me it is simply a (near) guarantee to be able to have a working environment to develop on the project. No matter if you don't have all the latest updates. Most little changes from dependencies have little to no impact on your own development. (library or project)

The problem I see is that some dependency versions are gonna stall forever, while actually the latest ones haven't been tried and are more likely to break the codebase.

**Comment by aurelien-clu** [comment]
> The problem I see is that some dependency versions are gonna stall forever, while actually the latest ones haven't been tried and are more likely to break the codebase.

It does not seem to be a good behavior to add breaking new dependencies 🤔 (especially in a `lib` with 22k ⭐️ )

As for stalling ones, `poetry update` most of the time will do the trick (updating your state to a newer working state) and I suppose there should be 1 or several people interested with having a most up to date setup and could contribute it though I may be naive 😇

**Comment by bryant1410** [comment]
> It does not seem to be a good behavior to add breaking new dependencies  (especially in a `lib` with 22k  )

Not breaking dependencies, but a dependency version update makes your codebase to break, especially when you have an old version because the one in the codebase is quite old.

> As for stalling ones, `poetry update` most of the time will do the trick (updating your state to a newer working state) and I suppose there should be 1 or several people interested with having a most up to date setup and could contribute it though I may be naive

There's dependabot. But I think it's not worth it, that's my point.

**Comment by bryant1410** [comment]
A compromise could be that dependabot sends PRs monthly so it's less overwhelming. But I still don't see keeping the test env reproducible as an advantage (it doesn't reflect users' env).

**Pull request closed without merging**
