### PR TITLE
fix(wandb): pass fake dataset to avoid exception in trainer (see #34455)

### PR DESCRIPTION
**Pull request by cezanne-pascal-aracom**
# What does this PR do?
This PR passes a fake evaluation dataset for the initialisation of the `fake_trainer` of WandB.
This is necessary, since the init of the `Trainer` checks if an `eval_strategy` is set and raises an error if the `eval_dataset` is missing.
This issue is documented in #34701.
The fix here is similar to the one in #34455.

Fixes # (issue)
- Pass `["fake"]` as `eval_dataset` during initialisation of `fake_trainer` for saving purposes of WandB.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@SunMarc

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hello @CezaPasc, I believe this should have been fixed with https://github.com/huggingface/transformers/pull/34455

**Comment by LysandreJik** [comment]
Ah, my bad, I see where this one is different. There are a few files which are changed which shouldn't be; do you mind keeping the diff only to the fix here? Thank you!

**Comment by CezaPasc** [comment]
@LysandreJik 
It seems like I got the other diffs from rebasing with the upstream.
I reverted them so that the diff should now only be about the changes in this PR again.

**Review by LysandreJik — APPROVED** [review]
Cool, thank you!

**Pull request merged**
