### PR TITLE
CircleCI stores cleaner output at test_outputs.txt

### PR DESCRIPTION
**Pull request by sshleifer**
Changes:

- Don't run pytest with `-v` or `--cov`. I left run_tests_torch_and_tf using `--cov` but would love to delete that. I have never used circleci to determine code coverage.

- the run* jobs create artifact files called test_output.txt that are easier to read than scrolling in the circleci gui

- self scheduled runner also attempts to make a test_output.txt

Before:
image

After:

[artifact](https://53278-155220641-gh.circle-artifacts.com/0/test_output.txt) is very manageable

and [ui](https://app.circleci.com/pipelines/github/huggingface/transformers/8144/workflows/816b1f60-bda9-4456-9f51-92d6cff7b266/jobs/53278/steps) is less noisy.

### CODE REVIEW

**Comment by LysandreJik** [comment]
I wonder how it looks when it fails. Is it the same output you would usually see? If  that's the case, I'm all for that change!

**Comment by sshleifer** [comment]
Yes the tracebacks are completely unchanged. You just only see a `.` if the tests passes. And you don't have to scroll through `logger.info` (if you don't want to, it's still in the default circleci page).

**Review by sgugger — APPROVED** [review]
LGTM

**Comment by sshleifer** [comment]
Merging. Tag me if any issues.

**Pull request merged**
