### PR TITLE
Enable multi-device for some models

### LINKED ISSUE #29786: Community contribution: enabling `device_map="auto"` support for more vision and multimodal models
### Feature request

# Feature Request 

`transformers` models can be easily loaded across multiple devices using `device_map="auto"`. This will automatically allocate weights across available devices e.g. GPUs and offload any weights onto CPU, then disk as necessary. This is useful when doing inference with large models. 

To enable this, `_no_split_modules` has to be defined in the model's pretrained model class e.g. [like here for LLaMa](https://github.com/huggingface/transformers/blob/fadb053379b3ef24c4ec8e6d7d58555af21f58db/src/transformers/models/llama/modeling_llama.py#L793). This defines layers which should not be split across devices, and should contain as few layers as possible.

### Steps to add
* Pick a model to work on and open a PR - comment on this issue to say which model you're working on
* Define `_no_split_modules` in the PreTrainedModel subclass. Try with `_no_split_modules = []` first
* Enable testing
    * Ensure the following tests are not skipped for the model: `test_disk_offload_bin`, `test_disk_offload_safetensors`, `test_cpu_offload`, `test_model_parallelism`, `test_model_parallel_beam_search`
    * Run the tests in a multi-gpu environment `pytest tests/models/{MODEL_NAME}/test_modeling_{MODEL_NAME}.py -vv -k "offload or parallelism"`

## Models
- [ ] [Align](https://github.com/huggingface/transformers/blob/main/src/transformers/models/align/modeling_align.py)
- [ ] [Altclip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/altclip/modeling_altclip.py)
- [x] [Beit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/beit/modeling_beit.py) #30379
- [ ] [Bit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bit/modeling_bit.py)
- [ ] [Blip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/blip/modeling_blip.py)
- [ ] [Chinese_clip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/chinese_clip/modeling_chinese_clip.py)
- [x] [Convnext](https://github.com/huggingface/transformers/blob/main/src/transformers/models/convnext/modeling_convnext.py) #30207
- [x] [Convnextv2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/convnextv2/modeling_convnextv2.py) #30207
- [x] [Cvt](https://github.com/huggingface/transformers/blob/main/src/transformers/models/cvt/modeling_cvt.py) #30207
- [ ] [Data2vec](https://github.com/huggingface/transformers/blob/main/src/transformers/models/data2vec/modeling_data2vec_vision.py)
- [ ] [Depth_anything](https://github.com/huggingface/transformers/blob/main/src/transformers/models/depth_anything/modeling_depth_anything.py)
- [ ] [Dinat](https://github.com/huggingface/transformers/blob/main/src/transformers/models/dinat/modeling_dinat.py)
- [ ] [Dinov2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/dinov2/modeling_dinov2.py)
- [ ] [Donut](https://github.com/huggingface/transformers/blob/main/src/transformers/models/donut/modeling_donut_swin.py)
- [ ] [Dpt](https://github.com/huggingface/transformers/blob/main/src/transformers/models/dpt/modeling_dpt.py)
- [ ] [Efficientformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/efficientformer/modeling_efficientformer.py)
- [x] [Efficientnet](https://github.com/huggingface/transformers/blob/main/src/transformers/models/efficientnet/modeling_efficientnet.py) #29989
- [ ] [Flava](https://github.com/huggingface/transformers/blob/main/src/transformers/models/flava/modeling_flava.py)
- [ ] [Focalnet](https://github.com/huggingface/transformers/blob/main/src/transformers/models/focalnet/modeling_focalnet.py) #30207
- [ ] [Git](https://github.com/huggingface/transformers/blob/main/src/transformers/models/git/modeling_git.py)
- [x] [Glpn](https://github.com/huggingface/transformers/blob/main/src/transformers/models/glpn/modeling_glpn.py) #30207
- [ ] [Groupvit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/groupvit/modeling_groupvit.py)
- [x] [Imagegpt](https://github.com/huggingface/transformers/blob/main/src/transformers/models/imagegpt/modeling_imagegpt.py) #30207
- [ ] [Layoutlmv3](https://github.com/huggingface/transformers/blob/main/src/transformers/models/layoutlmv3/modeling_layoutlmv3.py)
- [x] [Levit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/levit/modeling_levit.py) #30207
- [ ] [Mask2former](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mask2former/modeling_mask2former.py)
- [ ] [Maskformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/maskformer/modeling_maskformer.py)
- [ ] [Maskformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/maskformer/modeling_maskformer_swin.py)
- [x] [Mgp_str](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mgp_str/modeling_mgp_str.py) #30207
- [x] [Mobilenet_v1](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mobilenet_v1/modeling_mobilenet_v1.py) #30207
- [x] [Mobilenet_v2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mobilenet_v2/modeling_mobilenet_v2.py) #30207
- [x] [Mobilevit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mobilevit/modeling_mobilevit.py) #30207
- [ ] [Mobilevitv2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mobilevitv2/modeling_mobilevitv2.py)
- [ ] [Nat](https://github.com/huggingface/transformers/blob/main/src/transformers/models/nat/modeling_nat.py)
- [ ] [Oneformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/oneformer/modeling_oneformer.py)
- [ ] [Perceiver](https://github.com/huggingface/transformers/blob/main/src/transformers/models/perceiver/modeling_perceiver.py)
- [x] [Poolformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/poolformer/modeling_poolformer.py) #30207
- [ ] [Pvt](https://github.com/huggingface/transformers/blob/main/src/transformers/models/pvt/modeling_pvt.py)
- [x] [Regnet](https://github.com/huggingface/transformers/blob/main/src/transformers/models/regnet/modeling_regnet.py) #30207
- [ ] [Resnet](https://github.com/huggingface/transformers/blob/main/src/transformers/models/resnet/modeling_resnet.py) #30207
- [x] [Sam](https://github.com/huggingface/transformers/blob/main/src/transformers/models/sam/modeling_sam.py) #30207
- [ ] [Segformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/segformer/modeling_segformer.py)
- [x] [Swiftformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/swiftformer/modeling_swiftformer.py) #30207
- [x] [Swin](https://github.com/huggingface/transformers/blob/main/src/transformers/models/swin/modeling_swin.py) #30207
- [ ] [Swin2sr](https://github.com/huggingface/transformers/blob/main/src/transformers/models/swin2sr/modeling_swin2sr.py)
- [x] [Swinv2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/swinv2/modeling_swinv2.py) #30207
- [ ] [Timesformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/timesformer/modeling_timesformer.py)
- [ ] [Timm_backbone](https://github.com/huggingface/transformers/blob/main/src/transformers/models/timm_backbone/modeling_timm_backbone.py)
- [x] [Trocr](https://github.com/huggingface/transformers/blob/main/src/transformers/models/trocr/modeling_trocr.py) #30207
- [ ] [Tvlt](https://github.com/huggingface/transformers/blob/main/src/transformers/models/tvlt/modeling_tvlt.py)
- [ ] [Tvp](https://github.com/huggingface/transformers/blob/main/src/transformers/models/tvp/modeling_tvp.py)
- [x] [Upernet](https://github.com/huggingface/transformers/blob/main/src/transformers/models/upernet/modeling_upernet.py) #30207
- [ ] [Videomae](https://github.com/huggingface/transformers/blob/main/src/transformers/models/videomae/modeling_videomae.py)
- [ ] [Vision_encoder_decoder](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py)
- [ ] [Vision_text_dual_encoder](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vision_text_dual_encoder/modeling_vision_text_dual_encoder.py)
- [ ] [Vit_mae](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vit_mae/modeling_vit_mae.py)
- [ ] [Vit_msn](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vit_msn/modeling_vit_msn.py)
- [x] [Vitmatte](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vitmatte/modeling_vitmatte.py) #30379
- [x] [Vivit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vivit/modeling_vivit.py) #30379
- [ ] [X_clip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/x_clip/modeling_x_clip.py)
- [x] [Yolos](https://github.com/huggingface/transformers/blob/main/src/transformers/models/yolos/modeling_yolos.py) #30207

### Motivation

Enable a powerful HF feature for all of our vision models

### Your contribution

Ping me for review 🤗

### PR DESCRIPTION
**Pull request by jla524**
# What does this PR do?

Fixes #29786 (issue)

Includes a fix for unit tests on Backbone models, where `base_output[0]` and `new_output[0]` [are tuples](https://github.com/huggingface/transformers/blob/0bd58f1ce0573c0e3269de4215a17d318add49b9/src/transformers/modeling_outputs.py#L1459)

Tested on a system with 2x RTX A4000

```
$ pytest tests/models/convnext/test_modeling_convnext.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 117 items / 110 deselected / 7 selected                                                                                                                                                                 

tests/models/convnext/test_modeling_convnext.py .......                                                                                                                                                     [100%]

<warnings redacted>
================================================================================== 7 passed, 110 deselected, 2 warnings in 8.95s ==================================================================================
```

```
$ pytest tests/models/convnextv2/test_modeling_convnextv2.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 108 items / 101 deselected / 7 selected                                                                                                                                                                 

tests/models/convnextv2/test_modeling_convnextv2.py .......                                                                                                                                                 [100%]

<warnings redacted>
================================================================================== 7 passed, 101 deselected, 2 warnings in 8.30s ==================================================================================

```

```
$ pytest tests/models/cvt/test_modeling_cvt.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 108 items / 101 deselected / 7 selected                                                                                                                                                                 

tests/models/cvt/test_modeling_cvt.py .......                                                                                                                                                               [100%]

<warnings redacted>
================================================================================= 7 passed, 101 deselected, 2 warnings in 16.37s ==================================================================================
```

```
$ pytest tests/models/focalnet/test_modeling_focalnet.py -k "offload or parallel"
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 119 items / 112 deselected / 7 selected                                                                                                                                                               

tests/models/focalnet/test_modeling_focalnet.py .......                                                                                                                                                   [100%]

<warnings redacted>
================================================================================ 7 passed, 112 deselected, 2 warnings in 15.75s =================================================================================
```

```
$ pytest tests/models/glpn/test_modeling_glpn.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 108 items / 101 deselected / 7 selected                                                                                                                                                                 

tests/models/glpn/test_modeling_glpn.py .......                                                                                                                                                             [100%]

<warnings redacted>
================================================================================== 7 passed, 101 deselected, 2 warnings in 9.81s ==================================================================================
```

```
$ pytest tests/models/imagegpt/test_modeling_imagegpt.py -k "offload or parallel"                                                                                                    
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0                                                                                                                                                       
rootdir: /root/transformers                                                                                                                                                                                        
configfile: pyproject.toml                                                                                                                                                                                         
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0                                                                                                                                               
collected 140 items / 132 deselected / 8 selected                                                                                                                                                                  
                                                                                                                                                                                                                   
tests/models/imagegpt/test_modeling_imagegpt.py ........                                                                                                                                                    [100%] 
                                                                                                                                                                                                                   
<warnings redacted>                                                                                                          
================================================================================= 8 passed, 132 deselected, 29 warnings in 10.51s =================================================================================
```

```
$ pytest tests/models/levit/test_modeling_levit.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 108 items / 101 deselected / 7 selected                                                                                                                                                                 

tests/models/levit/test_modeling_levit.py .......                                                                                                                                                           [100%]

<warnings redacted>
================================================================================= 7 passed, 101 deselected, 2 warnings in 13.72s ==================================================================================
```

```
$ pytest tests/models/mgp_str/test_modeling_mgp_str.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 105 items / 98 deselected / 7 selected                                                                                                                                                                  

tests/models/mgp_str/test_modeling_mgp_str.py .......                                                                                                                                                       [100%]

<warnings redacted>
================================================================================== 7 passed, 98 deselected, 2 warnings in 4.03s ===================================================================================
```

```
$ pytest tests/models/mobilenet_v1/test_modeling_mobilenet_v1.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 108 items / 101 deselected / 7 selected                                                                                                                                                                 

tests/models/mobilenet_v1/test_modeling_mobilenet_v1.py .......                                                                                                                                             [100%]

<warnings redacted>
================================================================================== 7 passed, 101 deselected, 3 warnings in 5.93s ==================================================================================
```

```
$ pytest tests/models/mobilenet_v2/test_modeling_mobilenet_v2.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 110 items / 103 deselected / 7 selected                                                                                                                                                                 

tests/models/mobilenet_v2/test_modeling_mobilenet_v2.py .......                                                                                                                                             [100%]

<warnings redacted>
================================================================================= 7 passed, 103 deselected, 13 warnings in 10.57s =================================================================================
```

```
$ pytest tests/models/mobilevit/test_modeling_mobilevit.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 111 items / 104 deselected / 7 selected                                                                                                                                                                 

tests/models/mobilevit/test_modeling_mobilevit.py .......                                                                                                                                                   [100%]

<warnings redacted>
================================================================================= 7 passed, 104 deselected, 3 warnings in 15.42s ==================================================================================
```

```
$ pytest tests/models/poolformer/test_modeling_poolformer.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 107 items / 100 deselected / 7 selected                                                                                                                                                                 

tests/models/poolformer/test_modeling_poolformer.py .......                                                                                                                                                 [100%]

<warnings redacted>
================================================================================== 7 passed, 100 deselected, 2 warnings in 6.10s ==================================================================================

```

```
$ pytest tests/models/regnet/test_modeling_regnet.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 108 items / 101 deselected / 7 selected                                                                                                                                                                 

tests/models/regnet/test_modeling_regnet.py .......                                                                                                                                                         [100%]

<warnings redacted>
================================================================================== 7 passed, 101 deselected, 2 warnings in 7.05s ==================================================================================
```

```
$ pytest tests/models/resnet/test_modeling_resnet.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 117 items / 110 deselected / 7 selected                                                                                                                                                                 

tests/models/resnet/test_modeling_resnet.py .......                                                                                                                                                         [100%]

<warnings redacted>
================================================================================== 7 passed, 110 deselected, 5 warnings in 9.31s ==================================================================================
```

```
$ pytest tests/models/sam/test_modeling_sam.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 122 items / 115 deselected / 7 selected                                                                                                                                                                 

tests/models/sam/test_modeling_sam.py .......                                                                                                                                                               [100%]

<warnings redacted>
================================================================================== 7 passed, 115 deselected, 2 warnings in 4.14s ==================================================================================
```

```
$ pytest tests/models/swiftformer/test_modeling_swiftformer.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 110 items / 103 deselected / 7 selected                                                                                                                                                                 

tests/models/swiftformer/test_modeling_swiftformer.py .......                                                                                                                                               [100%]

<warnings redacted>
================================================================================== 7 passed, 103 deselected, 2 warnings in 8.28s ==================================================================================
```

```
$ pytest tests/models/swin/test_modeling_swin.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 121 items / 114 deselected / 7 selected                                                                                                                                                                 

tests/models/swin/test_modeling_swin.py ......s                                                                                                                                                             [100%]

<warnings redacted>
============================================================================ 6 passed, 1 skipped, 114 deselected, 3 warnings in 8.37s =============================================================================
```

^ test skipped due to `CUDA error: misaligned address` with PyTorch 2.0.0. which occurs when running on single GPU too

```
$ pytest tests/models/swinv2/test_modeling_swinv2.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 121 items / 114 deselected / 7 selected                                                                                                                                                                 

tests/models/swinv2/test_modeling_swinv2.py ......s                                                                                                                                                         [100%]

<warnings redacted>
============================================================================ 6 passed, 1 skipped, 114 deselected, 2 warnings in 7.05s =============================================================================
```

```
$ pytest tests/models/trocr/test_modeling_trocr.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 138 items / 130 deselected / 8 selected                                                                                                                                                                 

tests/models/trocr/test_modeling_trocr.py ........                                                                                                                                                          [100%]

<warnings redacted>
================================================================================== 8 passed, 130 deselected, 2 warnings in 5.55s ==================================================================================

```

```
$ pytest tests/models/upernet/test_modeling_upernet.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 111 items / 104 deselected / 7 selected                                                                                                                                                                 

tests/models/upernet/test_modeling_upernet.py ......s                                                                                                                                                       [100%]

<warnings redacted>
============================================================================ 6 passed, 1 skipped, 104 deselected, 3 warnings in 4.41s =============================================================================
```

```
$ pytest tests/models/yolos/test_modeling_yolos.py -k "offload or parallel"
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.4.4, pluggy-1.4.0
rootdir: /root/transformers
configfile: pyproject.toml
plugins: hypothesis-6.98.10, xdist-3.5.0, timeout-2.3.1, anyio-4.3.0
collected 108 items / 101 deselected / 7 selected                                                                                                                                                                 

tests/models/yolos/test_modeling_yolos.py .......                                                                                                                                                           [100%]

<warnings redacted>
================================================================================== 7 passed, 101 deselected, 2 warnings in 8.97s ==================================================================================
```

## Who can review?

@amyeroberts

### CODE REVIEW

**Comment by jla524** [comment]
Hey @amyeroberts! We have added support for 10 models now. Can I get a review for this PR?

**Review by amyeroberts — APPROVED** [review]
Amazing piece of work - thanks for adding this feature for all these models! ❤️ 

For the quality checks, running `make fix-copies` and pushing the changes should resolve this. 

Could you update the issue to mark all of these models as done once merged in?

**Comment by jla524** [comment]
Thanks Amy! I ran `make fix-copies` and pushed the changes. Interestingly, it updated some of the `_no_split_modules` code, but the tests are still passing.

**Comment by amyeroberts** [comment]
@jackylee328 Ah yes - that's what `make fix-copies` should do! Because of the one file per model policy, it can end up with a lot of repeated code. The way we get around this is using `# Copied from` comments, which enable us to reuse code without forcing a modular design. `make fix-copies` ensures all the places where `# Copied from` occurs the code it correctly updated if the source has changed. 

Thanks for running tests for the new models too ❤️ 

Re the failing checks at the moment: 
* The copy checks are failing because there's some unrelated diff changes in the PR. Doing `git checkout upstream/main -- src/transformers/models/bigbird_pegasus/modeling_bigbird_pegasus.py src/transformers/models/cohere/modeling_cohere.py tests/models/roc_bert/test_tokenization_roc_bert.py` should remove the diff and fix the break copies test. 
* For the quality check, running `make fixup` should resolve

**Comment by jla524** [comment]
Finally passing now! I had to merge all the changes from main.

**Comment by jla524** [comment]
Hmm I'm not sure why the torch tests are failing. I'm not able to reproduce the errors on my machines

**Comment by amyeroberts** [comment]
@jackylee328 Unfortunately sometimes our test suite will fail for reasons unrelated to the PR e.g. timeouts. If this happens, feel free to ping on the PR and I can restart the runs for you, without you needing to push lots of commits! 

Thank you for all the efforts adding this across our library - it's a mammoth addition! 🔥

**Comment by jla524** [comment]
Thank you @amyeroberts. I don't have permission to update the tracking issue, but I can make a list of the models that are now supported.

**Comment by amyeroberts** [comment]
@jla524 Ah, sorry, I didn't realise. No worries - I can update!

**Pull request merged**
