### PR TITLE
Fix sagemaker DP/MP

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

Fixes the broken sagemaker tests, proved it works. 

Solves https://github.com/huggingface/transformers/issues/23390

Needs to be coordinated with the Accelerate pr as well

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for the fix!

**Comment by mocobeta** [comment]
Hello, devs. I encountered this error on Google Colab (Python 3.10) and transformers 4.30.1.

```
❱ 3386 │   │   │   self.args.distributed_state is None and self.local_rank ! 

AttributeError: 'CLTrainer' object has no attribute 'local_rank'
```

It looks like the line was added by this change.

By looking through the code, I suspect `self.local_rank` should be `self.args.local_rank`. I'm fairly new to this library, so apologies if my guess is wrong.

**Comment by sgugger** [comment]
Indeed. Would you like to open a PR with the fix?

**Comment by mocobeta** [comment]
Hi. I just opened #24297.

**Pull request merged**
