### PR TITLE
Flaubert

### PR DESCRIPTION
**Pull request by LysandreJik**
From PR #2632 by [formiel](https://github.com/formiel).

This PR adds [FlauBERT](https://github.com/getalp/Flaubert). Most of the code is derived from XLM (there are some new features in FlauBERT such as pre_norm and layerdrop).

The failing tests were fixed.

### CODE REVIEW

**Comment by LysandreJik** [comment]
Is the `layerdrop` configuration argument used anywhere? I don't see any usage in the modeling file.

**Comment by formiel** [comment]
Hi @LysandreJik, 

Thanks a lot for working on my PR!

Good catch on layerdrop! It is currently not used for inference (it might be in a future version), so I decided to remove it from the code. As it may be useful for fine-tuning, let me add it and create a new PR. Sorry for the inconvenience!

**Comment by LysandreJik** [comment]
Alright, I've completely updated the documentation as well as the tests. I'm merging this PR, feel free to open a new one concerning the `layerdrop`.

**Comment by formiel** [comment]
I've just opened a new PR for `layerdrop`. Thank you so much for your kind support to the integration of our model into your library!

**Comment by LysandreJik** [comment]
A pleasure!

**Pull request merged**
