### PR TITLE
Remove ConversationalPipeline and Conversation object

### LINKED ISSUE #31158: Conversation pipeline example doesn't work
### System Info

- `transformers` version: 4.40.2
- Platform: Linux-5.15.0-1048-aws-x86_64-with-glibc2.31
- Python version: 3.10.14
- Huggingface_hub version: 0.23.0
- Safetensors version: 0.4.3
- Accelerate version: 0.30.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@stevhliu

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/transformers/blob/f3f640dce14bee3b3930a774c3dfac92977eee7f/src/transformers/pipelines/conversational.py#L208-L214

```
Traceback (most recent call last):
  File "/fsx/qgallouedec/trl/conv.py", line 6, in <module>
    conversation = chatbot(conversation)
  File "/fsx/qgallouedec/miniconda3/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text2text_generation.py", line 167, in __call__
    result = super().__call__(*args, **kwargs)
  File "/fsx/qgallouedec/miniconda3/envs/trl/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1242, in __call__
    return self.run_single(inputs, preprocess_params, forward_params, postprocess_params)
  File "/fsx/qgallouedec/miniconda3/envs/trl/lib/python3.10/site-packages/transformers/pipelines/base.py", line 1248, in run_single
    model_inputs = self.preprocess(inputs, **preprocess_params)
  File "/fsx/qgallouedec/miniconda3/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text2text_generation.py", line 177, in preprocess
    inputs = self._parse_and_tokenize(inputs, truncation=truncation, **kwargs)
  File "/fsx/qgallouedec/miniconda3/envs/trl/lib/python3.10/site-packages/transformers/pipelines/text2text_generation.py", line 129, in _parse_and_tokenize
    raise ValueError(
ValueError:  `args[0]`: Conversation id: 44b49edc-7f94-45fc-ac5c-9166b7fb7b1e
user: I'm looking for a movie - what's your favourite one?
 have the wrong format. The should be either of type `str` or type `list`
```

### Expected behavior

The example to work.

It's probably linked to the fact that the pipeline has the wrong type. When you do 

```python
chatbot = pipeline(model="facebook/blenderbot-400M-distill", task="conversational")
```

it works.

### PR DESCRIPTION
**Pull request by Rocketknight1**
Both the `ConversationalPipeline` and the `Conversation` object have been deprecated for a while, and are due for removal in `4.42`, which is the upcoming version. This PR removes them and every reference to them that I could find.

Fixes #31158

### CODE REVIEW

**Comment by LysandreJik** [comment]
Please make sure there are very solid examples of how to do conversational from now on!

**Review by amyeroberts — APPROVED** [review]
Thanks for tidying this up! 

+1 on @LysandreJik's comment

**Comment by Rocketknight1** [comment]
@osanseviero has been updating some docs in model repos, and I added the [sidebar tutorial](https://huggingface.co/docs/transformers/conversations) as well. If there's anywhere else you think it would make sense to add these examples, let me know!

**Comment by Rocketknight1** [comment]
Merging this - I think it's reasonably safe, but let's see if any more issues turn up before the next release.

**Pull request merged**
