### PR TITLE
fix speecht5 failure issue in test_peft_gradient_checkpointing_enable…

### PR DESCRIPTION
**Pull request by sywangyi**
…_disable

# What does this PR do?

Fixes # (issue)
https://github.com/huggingface/transformers/issues/33527

- speech models: @ylacombe, @eustlb

### CODE REVIEW

**Comment by sywangyi** [comment]
@amyeroberts

**Comment by Rocketknight1** [comment]
gentle ping @ylacombe @eustlb

**Comment by yao-matrix** [comment]
@Rocketknight1  gentle ping.

**Review by Rocketknight1 — APPROVED** [review]
This looks clean, and I'm sorry the review took so long! I should have just approved it the first time around, given that it clearly fixes the problem.

**Pull request merged**
