### PR TITLE
Fix the example command for SQuAD

### PR DESCRIPTION
**Pull request by kaniblu**
Issue #4549: added the missing argument `--do_lower_case` for reproducing the intended results.

### CODE REVIEW

**Comment by BramVanroy** [comment]
Can you add the do_lower_case flag for all other instances in that README that use bert uncased? Thanks!

**Comment by kaniblu** [comment]
Sure. Presumably for the tf version, the script will handle the casings automatically.

**Comment by BramVanroy** [comment]
From the code it would seem that way, but I am not sure actually. 

cc @thomwolf @LysandreJik: `do_lower_case` was missing in the commands to run squad with bert-base-uncased. Is this flag also necessary in the Tensorflow version? It's not present in the code, so I would assume not.

The other changes LGTM!

**Comment by julien-c** [comment]
Closed by #4245 (we still need to investigate why the lowercasing is not properly populated by the model's config)

**Pull request closed without merging**
