### PR TITLE
Don't discard entity_group when token is the last in the sequence.

### PR DESCRIPTION
**Pull request by mfuntowicz**
Signed-off-by: Morgan Funtowicz <funtowiczmo@gmail.com>

### CODE REVIEW

**Comment by stefan-it** [comment]
LGTM!

Thanks @mfuntowicz !

Before:

```bash
In [6]: nlp("My name is Wolfgang and I live in Berlin")                                                                                                                                           
Out[6]: [{'entity_group': 'I-PER', 'score': 0.9991481900215149, 'word': 'Wolfgang'}]
````

With this PR:

```bash
In [5]: nlp("My name is Wolfgang and I live in Berlin")                                                                                                                                           
Out[5]: 
[{'entity_group': 'I-PER', 'score': 0.9991481900215149, 'word': 'Wolfgang'},
 {'entity_group': 'I-LOC', 'score': 0.9983668327331543, 'word': 'Berlin'}]
```

**Review by stefan-it — APPROVED** [review]

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Comment by mfuntowicz** [comment]
@LysandreJik CI error seems unrelated, is it ok for you if I merge?

**Comment by julien-c** [comment]
Did you check this, @enzoampil? Just making sure to ping you as you contributed #3957 🤗

**Comment by enzoampil** [comment]
Did a few checks as well and looks great! Was planning to include this in this PR #4987 (2nd point), but this seems to solve it cleanly already, so will focus on the 1st point with that PR :smile:

**Pull request merged**
