### PR TITLE
BartTokenizerFast

### PR DESCRIPTION
**Pull request by patil-suraj**
This PR adds `BartTokenizerFast` by subclassing `RobertaTokenizerFast`

@sshleifer @mfuntowicz

### CODE REVIEW

**Review by sshleifer — APPROVED** [review]
LGTM. Do we need extra test coverage? is RobertaTokenizerFast well tested?

**Comment by patil-suraj** [comment]
I think we will need a test, there are no tests for `RobertaTokenizerFast` in `test_tokenization_roberta.py` file.

**Comment by sshleifer** [comment]
The test is in `test_tokenization_fast`, so I think we're OK on that front.
Going to wait for @n1t0 or @mfuntowicz to approve and merge, because they are working on this concurrently.

**Review by mfuntowicz — APPROVED** [review]
LGTM 👍

**Pull request merged**
