### PR TITLE
Nystromformer ONNX export 

### PR DESCRIPTION
**Pull request by whr778**
# This PR implements ONNX export functionality for Nystromformer models.
In addition to running the test cases, I exported a locally built Nystromformer 2048 input sequence model to ONNX and ran prediction.  
I verified the prediction output.

Fixes # (https://github.com/huggingface/transformers/issues/21339)

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
Hi there. The ONNX integration has moved to the [optimum library](https://github.com/huggingface/optimum) so you should open your pull request there :-)

**Comment by whr778** [comment]
Hi,  okay.  Should I delete this PR or fix the error and submit another PR to optimum??

**Comment by sgugger** [comment]
Yes, you can cloes this PR. We don' accept new PRs as all the support is in optimum now.

**Comment by whr778** [comment]
Moving code to optimum

**Pull request closed without merging**
