### PR TITLE
dependencies: `keras-nlp<0.14` pin

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

On the latest `keras-nlp` [release](https://github.com/keras-team/keras-nlp/releases/tag/v0.14.0) -- "KerasNLP no longer supports Keras 2.". This means we don't support this version, as we only support Keras 2

### CODE REVIEW

**Comment by amyeroberts** [comment]
Fine with pinning to keep things working for now, but would be good to have a plan for future keras updates. @Rocketknight1  could we remove keras-nlp? 

also cc @ydshieh for reference

**Comment by gante** [comment]
hehe this is not how we update versions anymore

**Comment by gante** [comment]
@amyeroberts I followed [our docs](https://www.notion.so/Circle-Ci-Docker-images-3bedc8bc602e4ca88c34c6c194accd74?pvs=4) for version updates, but the [resulting PR](https://github.com/huggingface/transformers/pull/31687) doesn't look right.

What's the expected procedure to update breaking versions? 🤔

**Comment by ArthurZucker** [comment]
Let's go on slack @gante !

**Comment by gante** [comment]
@amyeroberts the `dev-ci` commit ran against the `:dev` docker images, which stem from the latest commit [here](https://github.com/huggingface/transformers/pull/31687). The failed test is unrelated and reported on slack, the TF issues are fixed as it can be seen :)

If you approve these changes, after the hub failures are resolved
1. I will add a commit `[push-ci-image]` to the other PR, which will push the updated docker image
2. merge this PR
3. Update the CI docker docs with the learnings in this process, to make them more clear to everyone :)

**Review by amyeroberts — COMMENTED** [review]
Thanks!

**Review by amyeroberts — APPROVED** [review]

**Review by Rocketknight1 — APPROVED** [review]
Hey @amyeroberts, we currently don't have a transition plan to move Transformers to Keras 3 because of how disruptive it would be to backwards compatibility. A lot of our TF/Keras usage is users who use it for production workflows with older software versions, so we think it'll be quite a while before we're ready to deprecate all of that and migrate to Keras 3.

For the forseeable future, we're going to keep Transformers on Keras 2, and support Keras 3 by having libraries like KerasNLP and KerasCV pick up the slack and save/load safetensors checkpoints that Transformers can read. This has already started thanks to @ariG23498's work, and more architectures will be supported very soon.

Therefore, it's totally okay to pin Keras and Keras-associated libraries on the last version that supported Keras 2, and that pin will probably be maintained indefinitely.

**Comment by julien-c** [comment]
(btw cc @Wauplin for viz)

**Comment by amyeroberts** [comment]
Thanks for the detailed explanation @Rocketknight1 !

**Comment by Wauplin** [comment]
Thanks for the ping, good to keep in mind. And thanks @Rocketknight1 for the full context!

**Review by fxmarty — APPROVED** [review]
LGTM

**Comment by gante** [comment]
Docker image pushed in #31687 -- merging 🤞

**Pull request merged**
