### PR TITLE
TorchDynamo related cleanup

### PR DESCRIPTION
**Pull request by anijain2305**
Related to https://github.com/huggingface/transformers/issues/18127

cc @ydshieh @stas00

### CODE REVIEW

**Comment by stas00** [comment]
Thank you for fixing, @anijain2305 

@ydshieh, perhaps let's use this PR to add the CI bits?

**Comment by ydshieh** [comment]
> Thank you for fixing, @anijain2305
> 
> @ydshieh, perhaps let's use this PR to add the CI bits?

OK. I will push my work (on CI) to this PR.

Before I would have to push to HF's transformers repo to test everything is fine.

**Comment by anijain2305** [comment]
@ydshieh Please feel free to take over this PR. Do not hesitate to reach out to me if you see more Dynamo related errors.

I will open a tracker in Dynamo repo to avoid such failures in future.

**Comment by ydshieh** [comment]
@anijain2305 I rebase my branch on this PR

https://github.com/huggingface/transformers/commits/to_run_torchdynamo_tests

and it still has an error (for `test_torchdynamo_full_eval`)

```
    def on_enter():
        global most_recent_backend
        if (
            most_recent_backend is not None
            and most_recent_backend is not compiler_fn
        ):
>           raise ResetRequired()
E           torchdynamo.exc.ResetRequired: 
E           Must call `torchdynamo.reset()` before changing backends.  Detected two calls to
E           `torchdynamo.optimize(...)` with a different backend compiler arguments.
```
See this [run page](https://github.com/huggingface/transformers/runs/7914698826?check_suite_focus=true)

Add `torchdynamo.reset()` to some places in `test_torchdynamo_full_eval` should work I guess. But I prefer for you to push the change (to your PR), thank you.

**Comment by anijain2305** [comment]
Oh, that test was getting skipped for me. I am gonna send a patch.

**Comment by ydshieh** [comment]
@anijain2305 Ping me once it's ready on your side :-).

**Comment by stas00** [comment]
@anijain2305, @Chillee - we are excited to integrate your amazing work in our software and make it available to users. But please commit to support it. Otherwise we are spinning wheels waiting and waiting and things continue to remain broken meanwhile.

If you don't feel this is desirable any longer or if the situations has changed and you don't have the resources we can discuss removing what we has been added altogether and only re-add it once you officially release these new features as part of pytorch.

Thank you!

**Comment by anijain2305** [comment]
@ydshieh @anijain2305 Sorry about the long wait. I spent some time to setup trt earlier but was stuck, so this got delayed.

We are committed, and we still believe this is the right approach. Let me prioritize it this week. If I am still stuck with TRT install, I will ping.

**Comment by stas00** [comment]
Thank you for the follow up, @anijain2305! Please keep us posted on the progress.

**Comment by anijain2305** [comment]
@ydshieh Can you restart the CI on your branch when you get a chance with my latest changes?

**Comment by ydshieh** [comment]
> @ydshieh Can you restart the CI on your branch when you get a chance with my latest changes?

Sure. Will let you know

**Comment by ydshieh** [comment]
@anijain2305 The tests now pass. I will incorporate your changes into my PR :-) Thanks a lot for the fix!

**Comment by stas00** [comment]
Thank you for the fix, @anijain2305!

**Pull request closed without merging**
