### PR TITLE
[WIP] Update model addition guide

### PR DESCRIPTION
**Pull request by stevhliu**
This PR updates the contribution guide for how to add a model since I don't think we do the *call-for-model-addition* thing anymore. Also reworked the section headers a bit so certain steps like "write a conversion script" can actually be linked to, and also made some edits for clarity. Please let me know if any of the other content is outdated (also cc @NielsRogge since you've added many models before!).

The last thing I need to do is update the `transformers_overview.png` to be less dense :)

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks for your PR. It's going to take me too long to check step by step that the actual technical content is unchanged, and I don't think this is a crucial part of our docs to update as not that many users contribute new models, and no one reported they had trouble understanding this guide. So I'd just leave the current version as is or focus on one/two fixes you feel are really important.

**Comment by stevhliu** [comment]
Sounds good! The fixes I'll target are:

1. Update the intro to remove the _call-for-model-addition`_.
2. Update that `cookiecutter` generates a `.mdx` file instead of a `.rst` file.
3. Fix the checklist so it doesn't have bullets and numbers.

What do you think about creating a new PR with these fixes and leaving this one here in case we come back to it in the future?

**Comment by sgugger** [comment]
Sure!

**Comment by stevhliu** [comment]
Closing for now, saving larger changes for later in the future :)

**Pull request closed without merging**
