### PR TITLE
Add Translate docs into Arabic - section files CONCEPTUAL GUIDES

### PR DESCRIPTION
**Pull request by AhmedAlmaghz**
Add Translate docs into Arabic - section files CONCEPTUAL GUIDES 

---------------------------------------------------------------------------------------
# CONCEPTUAL GUIDES

- [x]  Philosophy #33064
- [x]  Glossary #33038
- [x]  What 🤗 Transformers can do #33073
- [x]  How 🤗 Transformers solve tasks #33074
- [x]  The Transformer model family #33047
- [x]  Summary of the tokenizers #33078
- [x]  Attention #33021
- [x]  Padding and truncation #33050
- [x]  BERTology #33024
- [x]  Perplexity of fixed-length models #33063
- [x]  Pipelines for webserver inference #33066
- [x]  Model training anatomy #33045
- [x] Getting the most out of LLMs #33043

### CODE REVIEW

**Comment by AhmedAlmaghz** [comment]
مرحبا أخي عبدالله @abodacs 
لقد حللت التعارض بطلب السحب هذا
ارجو عمل approval لطلب السحب فقد جمعت طلبات السحب السابقة هنا وقمت بإغلاقها جميعا
تحياتي

**Comment by AhmedAlmaghz** [comment]
وهذا هي المهام التالية للمراجعة

# DEVELOPER GUIDES

- [ ]  Use fast tokenizers from 🤗 Tokenizers #33034
- [ ]  Run inference with multilingual models #33048
- [ ]  Use model-specific APIs #33030
- [ ]  Share a custom model #33031
- [ ]  Templates for chat models #33026
- [ ]  Trainer #33080
- [ ]  Run training on Amazon SageMaker #33071
- [ ]  Export to ONNX #33072
- [ ]  Export to TFLite #33077
- [ ]  Export to TorchScript #33079
- [ ]  Benchmarks #33023
- [ ]  Notebooks with examples #33049
- [ ]  Community resources #33027
- [ ]  Troubleshoot #33017
- [ ]  Interoperability with GGUF files #33037


تحياتي وتقديري لك أخي @abodacs

**Review by abodacs — APPROVED** [review]

**Comment by AhmedAlmaghz** [comment]
@stevhliu Could you please review and merge this PR?

**Review by stevhliu — APPROVED** [review]
Nice work all around!

**Comment by AhmedAlmaghz** [comment]
Thank you, @stevhliu and @abodacs! 
Excellent work!

**Pull request merged**
