### PR TITLE
add a configuration option in llama architecture

### PR DESCRIPTION
**Pull request by likenneth**
# What does this PR do?

I add a configuration option in llama to switch on the bias in output projection in MHA, which is critical for incorporating a new line of alignment research called [inference-time intervention](https://arxiv.org/pdf/2306.03341.pdf) into huggingface hub. 

Basically the inference-time-intervention found specific vectors to be added into the residual stream of the forwarding process that can significantly boost the truthfulness of the LLaMA family, including Alpaca and Vicuna. However, it requires a slight architecture change to the original architecture, the bias term needs to be activated in the output projection in the MHA. 

By merging this PR, I can push [honest llama](https://github.com/likenneth/honest_llama) onto huggingface hub and entertain all huggingface users with a more truthful LLaMA model, and its friends, honest Alpaca and honest Vicuna. 

This PR contains only 3 lines of new code and is completely backward-compatible. 

Fixes # (issue)
N/A

## Before submitting
- :x: This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- :white_check_mark: Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
-  :x: Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- :white_check_mark: Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- :x: Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. @ArthurZucker and @younesbelkada

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks for your PR! I think this is more suited to our code on the Hub API as it doesn't apply to the base LLaMA checkpoints. cc @ArthurZucker if you have a different opinion.

**Comment by likenneth** [comment]
Hi @sgugger, 

Appreciate your prompt reply. However I think I missed something. What do you mean by it doesn't apply to the base LLaMA? 

I can run these code without problems;

```
import llama
model_name = 'decapoda-research/llama-7b-hf'
tokenizer = llama.LLaMATokenizer.from_pretrained(model_name)
model = llama.LLaMAForCausalLM.from_pretrained(model_name, low_cpu_mem_usage = True, torch_dtype=torch.float16)
```

And what is the Hub API? My understanding was, any model on HF Hub has to be an instantiation of the transformers library, then since honest llama requires a bias term and this cannot be achieved by existing flexibility of the configuration, I made this PR that flex up the HF LLaMA model. 

Thanks!

**Comment by sgugger** [comment]
You are requesting to make some changes to a model to accommodate your custom versions of it, the original LLaMA checkpoints do not need this config flag. So that's why this should be done via the [code on the Hub API](https://huggingface.co/docs/transformers/custom_models) which allows you to share your code along with the model weights on the Hub.

**Review by ArthurZucker — COMMENTED** [review]
Thanks a lot for opening a PR! I am in line with what @sgugger said, this was not in the original llama and could bring confusion. 
Would love to hear how this worked out with the code on the hub once you have done the experiments! 🤗

**Comment by likenneth** [comment]
I see, let me have a look at the link @sgugger shared to see how to upload customized model to HF!

**Comment by likenneth** [comment]
Thanks for your help! I baked the inference-time intervention into a LLaMA-2-7B. The process is done offline and the edited model can work independently, as fast as the original LLaMA-2. Link: https://huggingface.co/likenneth/honest_llama2_chat_7B

**Pull request closed without merging**
