### PR TITLE
Superpoint imports fix

### PR DESCRIPTION
**Pull request by zucchini-nlp**
# What does this PR do?

I have been seeing this errors for a few days (when `make quality`) and seems like there is no PR fixing it. I decided to make it a separate PR, to merge quickly independently of other changes.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
That's a bit weird, ci's are green on main. Locally I don't have an issue so most probably a version of ruff?

**Comment by zucchini-nlp** [comment]
I noticed now that it does not fail in every `make quality`. Guess that depends on what local changes were made 🤔 

The bug here is that the import is done from incorrect place, because the `requires_backend` should be imported from `utils`. It is already done so for all image processors in library. I am not sure how the Superpoint model tests passed when adding the model, but currently trying to get the processor as below fails in `main`

`processor = AutoImageProcessor.from_pretrained("magic-leap-community/superpoint")`

**Review by ArthurZucker — APPROVED** [review]
Thanks for explaining!

**Comment by zucchini-nlp** [comment]
@gante this can be merged

**Pull request merged**
