### PR TITLE
fix HF conversion for older Llama versions

### LINKED ISSUE #30734: Meet problems when I use the file src/transformers/models/llama/convert_llama_weights_to_hf.py to transfer LlaMa-7B
### System Info

image
When I use the file convert_llama_weights_to_hf.py to converted LlaMa-7B weights to the Hugging Face Transformers format, an error raised for the line 154 and said "RuntimeError: shape '[32, 2, 2, 4096]' is invalid for input of size 16777216".

My command
python convert_llama_weights_to_hf.py     --input_dir ./ --model_size 7B --output_dir ./7B_hf

Here is my environments,
cuda-11.7, gcc-10.2.0, torch==2.0.0+cu117 torchvision==0.15.1+cu117, openai==0.27.8, transformers==4.41.0.dev0

Thank you very much!!

### Who can help?

@ArthurZucker @pcuenca @xe

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just use this code to convert the model. The model size (consolidated.00.pth file) is 13G.

python convert_llama_weights_to_hf.py     --input_dir ./ --model_size 7B --output_dir ./7B_hf

### Expected behavior

Could you give me some suggestions?

### PR DESCRIPTION
**Pull request by crackalamoo**
# What does this PR do?

Fixes #30734 and #30723. Also fixes an additional error I was having on Linux, `OSError: [Errno 39] Directory not empty: 'llama-3-8b-hf/tmp'`.

An update adding Llama 3 to the file `convert_llama_weights_to_hf.py` involved a change in the dimension passed to the `permute` function. The new dimension (`dim1=dim // num_local_key_value_heads`) works for Llama 3, but breaks for older versions, which had simply used `dim1=dim`. Therefore this PR checks the version and passes the appropriate paramter.

Additionally, this PR ignores errors when deleting the `tmp_model_path` directory in case the directory is not empty, since it is temporary anyways and should still be deleted.

Tagging @ArthurZucker: I saw you were mentioned on some issues related to this, so let me know if this is a good fix. Thanks!

### CODE REVIEW

**Comment by yweihpu** [comment]
> # What does this PR do?
> Fixes #30734 and #30723. Also fixes an additional error I was having on Linux, `OSError: [Errno 39] Directory not empty: 'llama-3-8b-hf/tmp'`.
> 
> An update adding Llama 3 to the file `convert_llama_weights_to_hf.py` involved a change in the dimension passed to the `permute` function. The new dimension (`dim1=dim // num_local_key_value_heads`) works for Llama 3, but breaks for older versions, which had simply used `dim1=dim`. Therefore this PR checks the version and passes the appropriate paramter.
> 
> Additionally, this PR ignores errors when deleting the `tmp_model_path` directory in case the directory is not empty, since it is temporary anyways and should still be deleted.
> 
> Tagging @ArthurZucker: I saw you were mentioned on some issues related to this, so let me know if this is a good fix. Thanks!

Hello: When I tried to convert from llama-1 to hf, I encountered the following problems: in permute
    return w.view(n_heads, dim1 // n_heads // 2, 2, dim2).transpose(1, 2).reshape(dim1, dim2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[32, 2, 2, 4096]' is invalid for input of size 16777216

I think some other people also encountered the same problem. 

Could you please tell me where to download the updated "convert_llama_weights_to_hf.py" that fixes the problem?

Thanks!

**Comment by crackalamoo** [comment]
Hi yweihpu,

I received an email from you but can't find a comment. Were you able to
figure this out?

**Review by ArthurZucker — COMMENTED** [review]
Hey! I open this: #31591 for simplifcations, but will include your changes and add you as co author!

**Comment by ArthurZucker** [comment]
The PR I link should help you, it also supports older version

**Pull request closed without merging**
