### PR TITLE
fix bf16 issue in text classification pipeline

### PR DESCRIPTION
**Pull request by chujiezheng**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by chujiezheng** [comment]
@amyeroberts Hi, this is the new PR I mentioned in https://github.com/huggingface/transformers/pull/30518

**Review by amyeroberts — COMMENTED** [review]
Thanks for fixing and adding tests! 

Some of the CI tests failing are unrelated, and I've triggered re-runs which should hopefully resolve these. 

Some are related to this PR. For the quality checks, running `make fixup` should resolve. For the others, specifically:
```
FAILED tests/test_pipeline_mixin.py::TextClassificationPipelineTests::test_accepts_torch_bf16 - TypeError: '<' not supported between instances of 'torch.dtype' and 'int'
FAILED tests/test_pipeline_mixin.py::TextClassificationPipelineTests::test_accepts_torch_fp16 - TypeError: '<' not supported between instances of 'torch.dtype' and 'int'
``` 
you'll need to debug :)

**Comment by chujiezheng** [comment]
@amyeroberts Hello, I have fixed the bugs. The failing CI tests seem about tf or flax, but I guess they are unrelated to this PR?

**Review by amyeroberts — APPROVED** [review]
Thanks for adding! 

For the failing tests - could you rebase on main to include the most recent upstream changes?

**Comment by chujiezheng** [comment]
@amyeroberts Hi, could you help check the PR? I think this PR is quite simple. It can also facilitate many use cases as the bf16-based classifiers are becoming popular.

**Comment by amyeroberts** [comment]
Hi @chujiezheng, 

the PR itself all looks good, but there's some outstanding tests which are still failing which need to be resolved before we can merge. When you're merging in `main`, is your `main` branch in-sync with the upstream?

**Comment by chujiezheng** [comment]
Yes, I did it just a few hours ago. You can notice the sync in the commits.

**Comment by amyeroberts** [comment]
@chujiezheng It's very odd. The tests are failing are ones which were failing about two weeks ago and have been resolved. I can see that there's merge commits in the history, although from this I'm not sure if it's possible to tell from which commit in `main` that the merge is happening. 

Could you try a rebase: 
* Pulling the latest changes from the hugging face `main` branch: `git fetch upstream main`
* Go onto the feature branch on your fork `git checkout main`
* Rebase the changes `git rebase upstream/main`
* Force push the changes `git push -f`

**Comment by chujiezheng** [comment]
The issue still exists...

**Comment by amyeroberts** [comment]
@chujiezheng Hmm, how odd 🤔 Thanks for trying the rebase. OK, as these tests aren't related to the pipeline, I'm going to forcibly merge. Thanks for your patience and for adding this!

**Pull request merged**
