### PR TITLE
Added Luke Doctests

### PR DESCRIPTION
**Pull request by Tegzes**
# What does this PR do?

Adds improved Doctests for LUKE

Issue: https://github.com/huggingface/transformers/issues/16292

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@ydshieh @patrickvonplaten @patil-suraj

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@ydshieh maybe  :-)

**Comment by sgugger** [comment]
The checkpoints in hf-internal-testing are only there for our tests, they shouldn't be used. Please use real checkpoints in the doc examples.

**Comment by ydshieh** [comment]
@Tegzes You can search on the Hub to find if there are luke based models for the corresponding tasks. If most tasks lack such a checkpoint, we will have to skip Luke for doctest unfortunately.

**Comment by Tegzes** [comment]
> The checkpoints in hf-internal-testing are only there for our tests, they shouldn't be used. Please use real checkpoints in the doc examples.

I only used the hf-internal-testing checkpoint because these were mentioned in the comment section of the issue. But I will change them accordingly.

**Comment by Tegzes** [comment]
@ydshieh I've tried most of the luke model checkpoints and unfortunately the only ones that exhibit a fully reproducible behavior are the ones from hf-internal-testing. 

If it would be acceptable to you, I would propose the merge as it is, backed by the fact that these internal types of checkpoints were used in the past for multiple such doctests improvements, as suggested in the comments from the issue (https://github.com/huggingface/transformers/issues/16292).

**Comment by ydshieh** [comment]
@Tegzes Thank you for the effort to check the checkpoints.

We have an internal discussion, and @sgugger strongly suggests we should not have used those tiny checkpoints in the first places, and we will try to figure out what changes we should proceed.

So unfortunately, we won't merge this PR. Sorry about this.  It's possible to rework on the Luke docstrings in the future after some decision is made regarding the doctest + missing checkpoints.

However, thank you again for the contribution!

**Comment by Tegzes** [comment]
@ydshieh Thank you for the response. The situation is much clearer now

**Comment by ydshieh** [comment]
Close as we have to decide what to do with doctest when a real checkpoint is missing

**Pull request closed without merging**
