### PR TITLE
Line endings should be LF across repo and not CRLF

### PR DESCRIPTION
**Pull request by LysandreJik**
Up to now we've had quite a few issues with users on Windows having their line endings be "CRLF" by default, while Linux users have "LF" line endings by default.

### Problem

This can be problematic in the following scenarios where no handling of the issue has been done on the user's side:
- When a user runs `make style`, their line endings will switch from LF to CRLF in *all* files, essentially rewriting the entire file
- When a user adds a new file to the repository, it will be in the "CRLF" format and will be committed as such.

### Resolution

The resolution is either to have the user handle that, or to handle that ourselves. Handling it ourselves is simple as it only requires adding a `.gitattributes` file at the root of the repository which will specify the line endings we're looking for, thus this is what this PR is proposing. On the other hand, we had issues handling it on the user side with the proposed `git core.autocrlf` as it seemed to have different results according to the setup.

Additionally, if users already have files in `CRLF` mode, then an additional command is required to convert these files to `LF`: `git add --renormalize .`. I believe this only impacts users that created files previous to this PR, as newly created files will already benefit from the `.gitattributes` file.

---

This PR completely reformats two files: `examples/research_projects/bertology/run_prune_gpt.py` and `tests/test_modeling_deberta.py`. These files had CRLF line endings, and will now have LF line endings.

---

Further readings:
- [🙏 Please Add .gitattributes To Your Git Repository](https://dev.to/deadlybyte/please-add-gitattributes-to-your-git-repository-1jld)
- [Why should I use core.autocrlf=true in Git?](https://stackoverflow.com/questions/2825428/why-should-i-use-core-autocrlf-true-in-git)
- [git replacing LF with CRLF](https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf?noredirect=1&lq=1)

cc @NielsRogge

### CODE REVIEW

**Review by jplu — APPROVED** [review]
LGTM! Super cool that we can now handle EOL that easily!

**Comment by NielsRogge** [comment]
Thank you @LysandreJik, this will alleviate much of the pain Windows users had with git in the past!

**Review by patrickvonplaten — APPROVED** [review]

**Comment by julien-c** [comment]
To hack my way up the contributors list, can I change all line endings to CRLF then revert? 😂

**Review by sgugger — APPROVED** [review]
Thanks for diving into this!

**Pull request merged**
