### PR TITLE
Embed circle packing chart for model summary

### PR DESCRIPTION
**Pull request by stevhliu**
This PR embeds an interactive chart of the most popular models by modality so users have a nice high-level visual overview of the 🤗 Transformers modelscape.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Nice to have this! Is there a way to have the image have the three regions be more of the same size at first before any zoom?

**Comment by LysandreJik** [comment]
I think the number of downloads dictates the size, right?

Impressive! I like how visual it is. Makes it understandable straight away. I guess a potential improvement would be to be able to read the subcategories without first clicking on a major category, but I don't know how feasible that is. Thanks for working on this! Really cool.

**Comment by stevhliu** [comment]
Thanks for the feedback!

I think it might make the visual more difficult to read if we also included the subcategories (modality) in addition to the main category. For example, the decoders bubble is already quite small, and adding more text might make it more cluttered (same for some of the smaller encoder-decoder bubbles).

**Review by LysandreJik — APPROVED** [review]
Let's go with it! Thanks for your work @stevhliu

**Pull request merged**
