### PR TITLE
Fix add-new-model-like

### PR DESCRIPTION
**Pull request by molbap**
Better version of #31753 that was actually due to the `image_processor_class` attribute being now a tuple with (slow, fast). All the addition logic relies on having one class only there, so we return only the first element.

### CODE REVIEW

**Comment by molbap** [comment]
Test errors are hub read timeouts.

**Review by amyeroberts — APPROVED** [review]
Thanks for updating!

**Comment by ArthurZucker** [comment]
cc @molbap we'll need a rebase here before anything!

**Comment by molbap** [comment]
Forgot to merge this - @ArthurZucker should be good to go

**Review by ArthurZucker — APPROVED** [review]
thanks

**Pull request merged**
