### PR TITLE
Move the TF NER example

### PR DESCRIPTION
**Pull request by jplu**
# What does this PR do?

This PR moves the `run_tf_ner.py` example into the legacy folder because it uses the "legacy" way to train a model with the `utils_ner.py` file.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM! We should hopefully have a TF script using the same way of training very soon.

**Comment by jplu** [comment]
Nice! What means "same way of training", same way than what?

**Comment by sgugger** [comment]
Same way as the current `run_ner` script.

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Pull request merged**
