### PR TITLE
Fix the value error typo of AdamW's betas' valid values checking

### PR DESCRIPTION
**Pull request by dourgey**
# What does this PR do?

Fixes the value error typo of AdamW's betas' valid values checking(`raise ValueError()`)
`"should be in  [0.0, 1.0["` -> `"should be in  [0.0, 1.0]"`

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
The test asserts that betas[0] < 1.0 so it seems like the current error is correct.

**Comment by dourgey** [comment]
> The test asserts that betas[0] < 1.0 so it seems like the current error is correct.

Thanks for your reply. 
 I mean, that there is a incorrect format of the interval indicates, as shown below:
> if I initialize a AdamW optimizer with error betas' values like [0.1, 2], there would raise a ValueError like this:
> image

It seems like a incorrect format of the interval indicates.  The correct format may should be `Invalid beta parameter: 2 - should be in [0.0, 1.0]`, but the current version is `Invalid beta parameter: 2 - should be in [0.0, 1.0[`. Is my understanding correct?

And after fixed, the error is shown as follows:
> image

**Comment by sgugger** [comment]
No, both beta1 and beta2 are tests to be `< 1.0`, not `<= 1.0`, so the upper bound needs to be excluded. If you put 1.0 as a value, you will get the error.

**Comment by dourgey** [comment]
> No, both beta1 and beta2 are tests to be `< 1.0`, not `<= 1.0`, so the upper bound needs to be excluded. If you put 1.0 as a value, you will get the error.

Yeah you are right. I made a mistake on this. Besides, my question is the error message `should be in [0.0, 1.0[` is a correct expression form of `[0.0, 1.0)` or a spelling mistake? I see that the expression form in original paper of Adam is:

image

If it's a spelling mistake, I submit a new commit, please have a look, thanks a lot.

**Comment by sgugger** [comment]
It's the European (or at least French, not sure about all the neighbors!) way of writing an interval without the upper bound, yours is the American way ;-) 

It's more inline with the paper so let's take yours.

**Review by sgugger — APPROVED** [review]

**Pull request merged**
