### PR TITLE
Add ONNX support for YOLOS

### PR DESCRIPTION
**Pull request by NielsRogge**
# What does this PR do?

Make it possible to export the YOLOS model to ONNX format. 

Linked to https://github.com/huggingface/transformers/issues/16308

### CODE REVIEW

**Review by regisss — COMMENTED** [review]
Thanks @NielsRogge! It all looks good to me except the `model.onnx` file that should not be part of this PR I think

**Comment by NielsRogge** [comment]
Thanks, I've removed the file and squashed the commits.

**Review by regisss — APPROVED** [review]
Thanks!

**Review by lewtun — APPROVED** [review]
Thanks for adding this ONNX export @NielsRogge !

The PR looks great to me - gently pinging @sgugger for final approval :)

**Review by sgugger — APPROVED** [review]
Thanks for adding this!

**Pull request merged**
