### PR TITLE
fix: data2vec-vision Onnx ready-made configuration.

### PR DESCRIPTION
**Pull request by NikeNano**
# What does this PR do?

This PR adds the missing config for the ONNX data2vec  config for images. It is stated in the [docs](https://huggingface.co/docs/transformers/serialization) that there is a default config for the facebook/data2vec-vision-base but this is currently not working and gives 

```
...
 File "/transformers/src/transformers/onnx/features.py", line 486, in get_supported_features_for_model_type
    raise KeyError(
KeyError: "data2vec-vision is not supported yet. Only ['albert', 'bart', 'beit', 'bert', 'big-bird', 'bigbird-pegasus', 'blenderbot', 'blenderbot-small', 'bloom', 'camembert', 'codegen', 'convbert', 'convnext', 'data2vec-text', 'deberta', 'deberta-v2', 'deit', 'detr', 'distilbert', 'electra', 'flaubert', 'gpt2', 'gptj', 'gpt-neo', 'ibert', 'layoutlm', 'layoutlmv3', 'levit', 'longt5', 'marian', 'mbart', 'mobilebert', 'mobilevit', 'm2m-100', 'perceiver', 'resnet', 'roberta', 'roformer', 'squeezebert', 't5', 'vit', 'xlm', 'xlm-roberta', 'yolos'] are supported. If you want to support data2vec-vision please propose a PR or open up an issue."
```

to recreate using docker: 

```bash
docker run -it huggingface/transformers-all-latest-gpu /bin/bash
```

```python
python3 -m transformers.onnx --model=facebook/data2vec-vision-base  onnx/
```

Should I create an issue for this and link to it?

Thanks for the help!

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by NikeNano** [comment]
@lewtun @LysandreJik  maybe you could take a look or point me to the correct person. Thanks!

**Comment by LysandreJik** [comment]
cc @michaelbenayoun @JingyaHuang as Lewis is off for a few weeks :)

**Review by JingyaHuang — APPROVED** [review]
LGTM, thanks for contributing!

**Comment by NikeNano** [comment]
What is the best practice in this case for the test that failed? As far as I an see it is not related to the changes? How do I rerun it? @JingyaHuang thanks!

**Comment by JingyaHuang** [comment]
> What is the best practice in this case for the test that failed? As far as I an see it is not related to the changes? How do I rerun it? @JingyaHuang thanks!

Can you rebase your branch with the main branch of transformers and re-launch the failed test?

**Comment by michaelbenayoun** [comment]
LGTM!
Have you ran this command?
```
RUN_SLOW=1 pytest tests/onnx/test_onnx_v2.py 
```
I was able to export the model on your branch, with your command, but I want to make sure all the tests pass before merging.

**Comment by NikeNano** [comment]
> LGTM! Have you ran this command?
> 
> ```
> RUN_SLOW=1 pytest tests/onnx/test_onnx_v2.py 
> ```
> 
> I was able to export the model on your branch, with your command, but I want to make sure all the tests pass before merging.

I missed this but will run this tomorrow and fix it if it needs to!

**Review by LysandreJik — APPROVED** [review]
Let's merge it! Thanks @NikeNano

**Pull request merged**
