### PR TITLE
Update modeling_gpt2.py

### PR DESCRIPTION
**Pull request by nikitakapitan**
Changed the declaration order in __ init __ so it is aligned with operational order.

As consequence, __ repr __ method is now also aligned with operational order

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
cc @ArthurZucker

**Review by ArthurZucker — APPROVED** [review]
I mean sure why not? 😄

**Comment by ArthurZucker** [comment]
Can you just run `make style`, maybe it will put it back?

**Comment by nikitakapitan** [comment]
Is there anything I can do to help merging it?

**Comment by sgugger** [comment]
You will need to fix the tests. As you can see from the failing check, the models that copy GPT-2 need to be updated with this change, so you need to run `make fix-copies`.

**Pull request closed without merging**
