### PR TITLE
Update `EncodecIntegrationTest`

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Some test fail since the addition of this model. This PR just updates the expect output values.

### CODE REVIEW

**Review by sanchit-gandhi — COMMENTED** [review]
Thanks @ydshieh - just to confirm, these updated values come from running the model on CUDA? (versus the original values, which were obtained on CPU)

**Review by sgugger — APPROVED** [review]
Thanks for the fix!

**Comment by ydshieh** [comment]
> Thanks @ydshieh - just to confirm, these updated values come from running the model on CUDA? (versus the original values, which were obtained on CPU)

Yes, it's on GPU. More specifically, on our CI runner's T4 GPU.

**Review by ArthurZucker — COMMENTED** [review]
Thanks! I ran them on my M1 cpu so they are close but still different

**Pull request merged**
