### PR TITLE
Fix circle ci flaky fail of wmt example 

### PR DESCRIPTION
**Pull request by patrickvonplaten**
Weird bug which might be fixed by forcing bleu scorer. 

Test pass locally, but seem to fail on circle ci.

### CODE REVIEW

**Comment by srush** [comment]
This is from this right? https://circleci.com/gh/huggingface/transformers/26455?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by patrickvonplaten** [comment]
Yeah exactly - it should be fixed now. 
I will push a slightly cleaner version in a second :-)

**Comment by patrickvonplaten** [comment]
In general, every example test that creates folder or files should deleted them afterwards to avoid same file naming collisions. Will open a PR about this. @julien-c @sshleifer @LysandreJik

**Review by LysandreJik — APPROVED** [review]
Great, thanks for the quick changes!

**Pull request merged**
