### PR TITLE
Italian translation of run_scripts.mdx gh-17459

### PR DESCRIPTION
**Pull request by lorenzobalzani**
# What does this PR do?

Italian translation of run_scripts.mdx
See issue: gh-17459

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@mfumanelli

### CODE REVIEW

**Review by nickprock — COMMENTED** [review]
Hi @lorenzobalzani weel done! Just a few points to make the reading more fluent:
* e [precedenti esempi](https://github.com/huggingface/transformers/tree/main/examples/legacy) cui contribuisce per lo più la comunità --> e [precedenti esempi](https://github.com/huggingface/transformers/tree/main/examples/legacy) a cui contribuisce per lo più la comunità

* senza apportare modifiche ad ogni problema --> senza apportare modifiche per ogni problema

* Dopo che hai configurato --> Dopo aver configurato

* Questo garantirò --> Questo garantirà

**Comment by lorenzobalzani** [comment]
Thanks, @nickprock 😉. 
I fixed all the wrong parts.

**Comment by mfumanelli** [comment]
Hi @lorenzobalzani!! Your translation looks perfect to me! I'm just asking if you could change "assicurati di esserti autenticato su Hugging Face" to be more gender-neutral, e.g. to: "assicurati di aver effettuato l'accesso su Hugging Face". Thank you very much for your contribution 🚀🚀

**Comment by lorenzobalzani** [comment]
@mfumanelli thanks for the tips ;) Next time I'll be more careful!

**Comment by mfumanelli** [comment]
Thanks @lorenzobalzani 🌈🌈 Look perfect to me @omarespejel 🚀

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Pull request merged**
