### PR TITLE
Add Italian translation of sharing_custom_models.mdx

### PR DESCRIPTION
**Pull request by Xpiri**
# What does this PR do?

Italian translation of sharing_custom_models.mdx
See issue: https://github.com/huggingface/transformers/issues/17459

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
https://github.com/huggingface/transformers/issues/17459

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@mfumanelli

### CODE REVIEW

**Comment by mfumanelli** [comment]
Hi @Xpiri! I think you are missing the title at the end of the section in the _toctree file:
**title: How-to guides**

**Comment by mfumanelli** [comment]
@Xpiri ! I also ask if you can edit a couple of things:
- "così che tutti possano usarlo" I know it's usual to speak in the masculine when referring to the masses whose gender you don't know, however, I'm asking if you can change it to "così che tutte le persone possano usarlo", so that it's more neutral. Thank you
- "la tua config" sometimes you write config in masculine and sometimes in feminine, I would always write "il tuo config" what do you think?
- here "e chiamiamo l'inizializzazione della superclasse con il metodoconfig(un po' come quando scrivi un normale" from the doc preview I notice that there are random highlights. I think there are some wrong quotes
- "Se il to modello" -> "Se il tuo modello"
- "Se stai copiando i file un modello dalla libreria" -> "Se stai copiando i file relativi alla modellizzazione dalla libreria"
- "e registrare in modo corretto" -> "e registrarli in modo corretto"
- "assicurati che di essere loggato. Lancia dal tuo terminal" -> "assicurati di aver effettuato l'accesso. Lancia dal tuo terminale"
- "che l'autore del modello non abbiano aggiornato il codice" -> "che le autrici o gli autori del modello non abbiano aggiornato il codice"
- "non ti fidi completamente degli autori del modello" -> "non ti fidi completamente della fonte"

Thank you!! 🌈🌈

**Comment by Xpiri** [comment]
Hi @mfumanelli, thank you very much for catching several typos. I also tried while I was writing to keep everything as gender neutral as possible, but seems like I still managed to make a couple of mistakes here and there! 

Lastly, I ended up using "la config" instead of "il config" as the feminine version is more coherent with the expression "la configurazione". I noticed that I was using the masculine version whenever I was refering to "il file config" and using the feminine version whenever I was refering to "la configurazione". Now it should always be written in the feminine version.

I hope I did everything right with the toctree file so I can get started with the next translation 😄

**Comment by mfumanelli** [comment]
Thanks @Xpiri!! Looks perfect to me @omarespejel 🚀🚀

**Comment by sgugger** [comment]
@Xpiri Sorry for the wait. The table of content has a little problem with the merge I had to do, could you just move the `-sections` on line 31 just below the `  title: How-to-guides` line?

**Comment by Xpiri** [comment]
@sgugger I should have fixed the table of contents. Let me know if everything is correct! 😄

**Review by sgugger — APPROVED** [review]
LGTM! Just renamed How-to-guides while solving the last merge conflict.
Thanks a lot for your PR!

**Pull request merged**
