### PR TITLE
Prevent `TextGenerationPipeline._sanitize_parameters` from overriding previously provided parameters

### PR DESCRIPTION
**Pull request by yting27**
# What does this PR do?

Below is the code example I used. The `max_length` and `truncation` (as well as `padding` and `add_special_tokens`) parameters passed to the `pipeline` method are overridden when generating output.
```
from transformers import pipeline


template_inst = "Instruct: {prompt}\nOutput:"
max_length = 25

text_generator = pipeline("text-generation", model="openai-gpt", max_length=max_length, max_new_tokens=30, truncation=True)
results = text_generator(template_inst.format(prompt="The personal life of William Shakespeare is somewhat of a mystery. There are two primary sources that provide historians with an outline of his life. One is his work, and the other is official documentation such as church and court records. However, these provide only brief sketches of specific events in his life and yield little insight into the man himself. When Was Shakespeare Born?"))

print(results)
```

Print out `preprocess_params` variables in `Pipeline.__call__()` method:
image
```
Kwargs: {}
self._preprocess_params: {'add_special_tokens': False, 'truncation': True, 'padding': False, 'max_length': 25, 'max_new_tokens': 30}
preprocess_params: {'add_special_tokens': False, 'truncation': None, 'padding': False, 'max_length': None}
preprocess_params (after): {'add_special_tokens': False, 'truncation': None, 'padding': False, 'max_length': None, 'max_new_tokens': 30}
```
As shown in the output, after `self._sanitize_parameters()` is called, both `truncation` and `max_length` are set to `None`.

I know we can pass the preprocess parameters when calling `text_generator` method (see code above). However, it just doesn't make sense to me that the previous parameters provided should be overridden. Hence I made the change. Feel free to improve if needed 😃 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
- pipelines: @Narsil

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @gante @zucchini-nlp

**Comment by zucchini-nlp** [comment]
I think it makes sense and the changes are consistent with the text2text pipeline, where "truncation" is handled similarly

**Review by gante — APPROVED** [review]
LGTM, thank you for making `transformers` better @yting27  💛  

Context for @amyeroberts [not sure what's your pipeline expertise, so I'm going with None]: when we init a pipeline, we store kwargs such as tokenizer options to act as default values. Before this PR, `preprocess_params` (which would hold some of the `__call__`-time kwargs) was being initialized with a set of default values, and those default values would override the kwargs set at `__init__` time. By initializing `preprocess_params` as an empty dict we avoid that, fixing the issue. 

🔍 I've checked the other pipelines: this is the only pipeline that is NOT following the correct pattern on `main`.

**Review by LysandreJik — APPROVED** [review]
This looks fair to me as well! Thanks for your contribution @yting27

**Pull request merged**
