### PR TITLE
Support gradient checkpointing in Qwen2VL ViT

### PR DESCRIPTION
**Pull request by li-plus**
# What does this PR do?

Support gradient checkpointing for Qwen2VL ViT part. The current implementation in main branch only supports gradient checkpointing in language part. This PR further supports checkpointing vision encoder.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @ArthurZucker, @amyeroberts, @qubvel

### CODE REVIEW

**Comment by qubvel** [comment]
Hi @li-plus! Thanks for your contribution! Can you please enable gradient checkpointing tests for this model to make sure it works properly?

**Comment by li-plus** [comment]
> Hi @li-plus! Thanks for your contribution!
> 
> Can you please enable gradient checkpointing tests for this model to make sure it works properly? I see [these](https://github.com/huggingface/transformers/blob/main/tests/models/qwen2_vl/test_modeling_qwen2_vl.py#L288-L304) tests are skipped on `main`, however, I was able to run them without issues locally.

@qubvel Thanks for advice. I've re-enable these gradient checkpointing tests for Qwen2VL in the latest commit. They run just fine on my machine.

**Comment by qubvel** [comment]
Thanks! Can you please also push an empty commit with message `[run-slow] qwen2_vl` to trigger all model tests? We should be fine here, cause `test_training_gradient_checkpointing` is not a `slow` test, however just to double check everything else is fine 🙂

**Comment by li-plus** [comment]
Thanks. Just pushed!

**Comment by li-plus** [comment]
@qubvel It seems those failures are not related to this PR. Any idea?

**Review by qubvel — APPROVED** [review]
No worries, I checked, the same tests fail on main. Thanks for triggering slow tests!

**Review by ArthurZucker — APPROVED** [review]
Thanks indeed there is `supports_gradient_checkpointing`set to `True` good catch

**Comment by ShuaibinQi** [comment]
@li-plus 

Thanks your commit!
when I use gradient_checkpointing for Qwen2VisionTransformerPretrainedModel, I meet this Error:


AttributeError: 'Qwen2VisionTransformerPretrainedModel' object has no attribute '_gradient_checkpointing_func'. Did you mean: 'gradient_checkpointing'?


Is it necessary to implement this '_gradient_checkpointing_func' in  'Qwen2VisionTransformerPretrainedModel' ?

**Comment by li-plus** [comment]
@ShuaibinQi Hi, I did not reproduce this error using transformers 4.47.0 using this demo code:

```python
import torch
from transformers import Qwen2VLForConditionalGeneration, AutoProcessor
from qwen_vl_utils import process_vision_info


processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-7B-Instruct")

model = Qwen2VLForConditionalGeneration.from_pretrained(
    "Qwen/Qwen2-VL-7B-Instruct",
    torch_dtype=torch.bfloat16,
    attn_implementation="flash_attention_2",
    device_map="cuda",
).eval()

model.gradient_checkpointing_enable()

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": "https://qianwen-res.oss-cn-beijing.aliyuncs.com/Qwen-VL/assets/demo.jpeg",
            },
            {"type": "text", "text": "Describe this image."},
        ],
    }
]

text = processor.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
image_inputs, video_inputs = process_vision_info(messages)
inputs = processor(
    text=[text],
    images=image_inputs,
    videos=video_inputs,
    padding=True,
    return_tensors="pt",
).to("cuda")

output_ids = model.generate(**inputs, use_cache=False)
input_len = inputs['input_ids'].shape[1]
output = processor.tokenizer.batch_decode(output_ids[:, input_len:])
print(output)
```

Did you use `gradient_checkpointing_enable` to enable gradient checkpointing?

**Pull request merged**
