### PR TITLE
Fix a bug in object_detection.md

### PR DESCRIPTION
**Pull request by jajupmochi**
Modify the `size` argument of the `AutoImageProcessor.from_pretrained`function.

# What does this PR do?

Original codes are as following:
```
image_processor = AutoImageProcessor.from_pretrained(
    MODEL_NAME,
    do_resize=True,
    size={"max_height": MAX_SIZE, "max_width": MAX_SIZE},
    do_pad=True,
    pad_size={"height": MAX_SIZE, "width": MAX_SIZE},
)
```
It causes the following error:
```
Traceback (most recent call last):
  File "lib/python3.12/site-packages/transformers/models/auto/image_processing_auto.py", line 406, in from_pretrained
    return image_processor_class.from_dict(config_dict, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/transformers/models/conditional_detr/image_processing_conditional_detr.py", line 883, in from_dict
    return super().from_dict(image_processor_dict, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/transformers/image_processing_utils.py", line 413, in from_dict
    image_processor = cls(**image_processor_dict)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/transformers/models/conditional_detr/image_processing_conditional_detr.py", line 831, in __init__
    size = get_size_dict(size, max_size=max_size, default_to_square=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.12/site-packages/transformers/image_processing_utils.py", line 745, in get_size_dict
    raise ValueError(
ValueError: size must have one of the following set of keys: ({'width', 'height'}, {'shortest_edge'}, {'longest_edge', 'shortest_edge'}, {'longest_edge'}), got dict_keys(['max_height', 'max_width'])
```
I assume `size={"height": MAX_SIZE, "width": MAX_SIZE}` should be used.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Hi @jajupmochi, thanks for opening this PR! 

The correct fix is to update `get_size_dict` so that it accepts a `size` dict with the values `max_height, max_width` as keys

**Comment by qubvel** [comment]
Hi @jajupmochi, can you please provide the `transformers` version you use? 'max_height', 'max_width' were recently added.

**Comment by jajupmochi** [comment]
> Hi @jajupmochi, can you please provide the `transformers` version you use? 'max_height', 'max_width' were recently added.

Hi @qubvel it is 4.41.2. 

One more thing, the guide https://huggingface.co/docs/transformers/tasks/object_detection and its GitHub source are not exact matches: https://github.com/huggingface/transformers/blob/main/docs/source/en/tasks/object_detection.md.

I noticed that the resizing are omitted in the latter, which leads to a less accurate detection:
tmpp1900awa

**Comment by jajupmochi** [comment]
> Hi @jajupmochi, can you please provide the `transformers` version you use? 'max_height', 'max_width' were recently added.

I have solved this bug by upgrading to version 4.42.0.dev0 by installing from the source:
```
python3 -m pip install git+https://github.com/huggingface/transformers
```
I am using this script instead: https://github.com/huggingface/transformers/blob/main/examples/pytorch/object-detection/run_object_detection.py

**Comment by qubvel** [comment]
@jajupmochi thanks, we should probably add a check to the guide about the minimum version required, similar to those in the script you mentioned https://github.com/huggingface/transformers/blob/35b112d3442e4a9f3873191dcde7d1235b6c72eb/examples/pytorch/object-detection/run_object_detection.py#L51 

Would you like to make a PR?

**Pull request closed without merging**
