### PR TITLE
Add XLA test

### PR DESCRIPTION
**Pull request by jplu**
# What does this PR do?

In the same spirit than for the mixed precision test, this PR adds one for XLA compliancy.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Yes, LGTM!

**Comment by LysandreJik** [comment]
Out of curiosity, how long are those tests for the models that have them?

**Comment by jplu** [comment]
few milliseconds, XLA is really fast :)

**Review by sgugger — APPROVED** [review]
Thanks for putting this in the roadmap!

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
