### PR TITLE
Add BartForTokenClassification

### PR DESCRIPTION
**Pull request by ZIZUN**
# What does this PR do?
+ Add BartForTokenClassification class for NER task

## Before submitting
- [x] Did you read the [contributor guideline]
- [x] Did you make sure to update the documentation with your changes?
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten, @patil-suraj @sgugger

### CODE REVIEW

**Comment by ZIZUN** [comment]
Finished ci test and passed all.

**Comment by patrickvonplaten** [comment]
Hey @ZIZUN, 

Thanks for the PR! Do we have a fine-tuned checkpoint for `BartForTokenClassification`? I'm wondering how useful this architecture is

**Comment by ZIZUN** [comment]
Hello @patrickvonplaten 
Yes, I tried to finetune this architecture for the Korean NER dataset. The results are as follows.
|                                                                  | Slot F1 (%) |
| ---------------------------------------------------- | ----------- |
| [CNN-BiLSTM-CRF](https://github.com/monologg/korean-ner-pytorch)           | 74.57       |
| **KoBART(ours)**                                                 | **83.36** |
| Bert-Multilingual                                                 | 84.20       |
| [KoBERT](https://github.com/monologg/KoBERT-NER)                         | 86.11       |
|  RoBERTa                                                             | 87.58       |
This structure is an auto-regressive architecture, so the score is lower than bi-directional model such as BERT.
But the score is resonable, so I think this architecture is a valueable thing for research.

**Review by sgugger — COMMENTED** [review]
The PR in itself looks very good to me, it's clean. I'm more concerned about whether the architecture should be added or not. Saying it has results similar to BERT on some datasets is not enough IMO, since BERT is the SOTA from 2018-2019 on token classification and there are better models now.

Curious to see what @LysandreJik thinks.

**Review by patil-suraj — COMMENTED** [review]
Thanks for the PR @ZIZUN!
I agree with Sylvain about the results. Also, note that Bart is quite bigger than BERT or encoder-only models, so one would expect better results with it. IMO we could instead add this as a community notebook or as a hub model to showcase how BART (or seq2seq models) can be used for token classification.

**Comment by ZIZUN** [comment]
Thank you for leaving comments! @sgugger @patil-suraj 
I think you are all right. It's sad but the results are a little disappointing. If I make a notebook, I will share it with you.
Have a nice day.

**Pull request closed without merging**
