### PR TITLE
[tests] make test_sdpa_equivalence device-agnostic

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?
This unit test should not only work on GPU, e.g. below is an evidence on XPU:
```bash
==================================================== PASSES =====================================================
_____________________________________ GemmaModelTest.test_sdpa_equivalence ______________________________________
--------------------------------------------- Captured stderr call ----------------------------------------------
`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.
============================================ short test summary info ============================================
PASSED tests/models/gemma/test_modeling_gemma.py::GemmaModelTest::test_sdpa_equivalence
```

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
LGTM - thanks! 

Two things for us to be able to merge: 
* Move the PR out of drafts 
* A run on slow tests. Could you push a commit with the message `[run_all]`?

**Comment by faaany** [comment]
> LGTM - thanks!
> 
> Two things for us to be able to merge:
> 
> * Move the PR out of drafts
> * A run on slow tests. Could you push a commit with the message `[run_all]`?

Hi amy, I am not sure what I should do with the second point. Do you mean that I should add a RUN-ALL Message in our chat here?

**Comment by amyeroberts** [comment]
@faaany Sorry, I wasn't clear. I meant you should push a commit with this message i.e. `git commit --allow-empty -m [run_all]`

**Comment by faaany** [comment]
> @faaany Sorry, I wasn't clear. I meant you should push a commit with this message i.e. `git commit --allow-empty -m [run_all]`

thx! done with empty commit.

**Comment by amyeroberts** [comment]
Thanks for running with the commit! As Yih-Dar pointed out in the other PR, the tests are essentially skipped. However, since  this isn't changing any logic I think it's fine, so merging. Thanks again for working on this!

**Pull request merged**
