### PR TITLE
feat: add trainer label to wandb run upon initialization

### PR DESCRIPTION
**Pull request by parambharat**
# What does this PR do?
This PR adds a telemetry label to the wandb run making it possible to identify W&B usage from the trainer class.
 
ref: https://github.com/huggingface/transformers/pull/25590

## Before submitting
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?

## Who can review?
@LysandreJik

### CODE REVIEW

**Comment by LysandreJik** [comment]
Thanks for your PR @parambharat!

**Comment by parambharat** [comment]
Hi @LysandreJik , just checking in here. Can this be merged now ?

**Comment by LysandreJik** [comment]
Hey @parambharat, I'd like either @muellerzr or @pacman100 to give it a look :)

**Review by muellerzr — APPROVED** [review]
Thanks for your contribution!

**Review by LysandreJik — APPROVED** [review]

**Pull request merged**
