### PR TITLE
fix zoedepth initialization error under deepspeed zero3

### PR DESCRIPTION
**Pull request by Tavish9**
# What does this PR do?

This PR addresses an issue with the initialization of tensor shapes in the `ZoeDepth` model when using the DeepSpeed framework with ZeRO-3 optimization.

Under DeepSpeed ZeRO-3, model parameters are partitioned, and the torch.Tensor class’s initialization behavior is overridden (details can be found in [here](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/partition_parameters.py#L593)). This override alters the behavior of tensor initialization, causing the error of the following line:

```python
self.register_buffer("k_minus_1", torch.Tensor([self.k - 1]).view(1, -1, 1, 1), persistent=False)
print(self.k_minus_1.shape)  # torch.Size([1, 63, 1, 1]) wrong!
```

To resolve this, the initialization has been updated to use torch.tensor instead of torch.Tensor, which preserves the intended shape under DeepSpeed ZeRO-3.
```python
self.register_buffer("k_minus_1", torch.tensor([self.k - 1]).view(1, -1, 1, 1), persistent=False)
print(self.k_minus_1.shape)  # torch.Size([1, 1, 1, 1]) correct!
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by qubvel — APPROVED** [review]
Looks good to me, thanks!

cc @muellerzr

**Review by ruidazeng — APPROVED** [review]
LGTM

**Comment by Tavish9** [comment]
hi, @qubvel and @muellerzr, just a quick reminder to check if everything is good to go. Look forward to new `ZoeDepth` in these days. Thanks again for your approval.

**Comment by Tavish9** [comment]
Hi @muellerzr, just checking in to see if this PR has gotten lost in your inbox or if it’s just having a little vacation! 😄 It’s been a couple of weeks, and we’re all eagerly waiting to see it merged. 

Also, @qubvel  why not merge without code review to get "YOLO" badge. 🤪 Just kidding 

Thanks a lot! 🙏

**Comment by qubvel** [comment]
Ok, I'm going to merge this, the change is minimal and it should not affect anything else

**Pull request merged**
