### PR TITLE
fix bug of CLAP dataloader 

### PR DESCRIPTION
**Pull request by lukewys**
Fix the bug of the CLAP data loader (https://github.com/LAION-AI/CLAP/issues/62)

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
cc @younesbelkada and @ArthurZucker

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for fixing! Ran the slow tests and they all pass!
Would love to hear @ArthurZucker 's thoughts just to make sure that I didn't missed anything

**Comment by hollance** [comment]
Just an FYI that the slow tests aren't actually being run for CLAP. See also https://github.com/huggingface/transformers/pull/22834

**Review by ArthurZucker — APPROVED** [review]
LGTM, l ran the slow tests and they all pass

**Pull request merged**
