### PR TITLE
Fix: update ltp word segmentation call in mlm_wwm

### PR DESCRIPTION
**Pull request by xyh1756**
# What does this PR do?

The method 'seg' has been removed in ltp 4.2.10, so the script is currently not runnable. We can use method 'pipeline' instead.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@VictorSanh

### CODE REVIEW

**Comment by xyh1756** [comment]
@VictorSanh 
please take a look

**Comment by xyh1756** [comment]
@sgugger

**Comment by sgugger** [comment]
Thanks but we're not actively maintaining those research projects. You'll need a review of the original author to get this merged, or just use the old versions of the libraries :-)

**Comment by xyh1756** [comment]
> Thanks but we're not actively maintaining those research projects. You'll need a review of the original author to get this merged, or just use the old versions of the libraries :-)

@wlhgtc please take a look :-)

**Comment by wlhgtc** [comment]
@xyh1756  This changes is fine. 
But you have to make sure all checks pass~

**Comment by xyh1756** [comment]
@sgugger @wlhgtc 
seems all checks pass :-)

**Comment by wlhgtc** [comment]
> @sgugger @wlhgtc seems all checks pass :-)

LGTM ,  @sgugger   can you help me merge it~

**Review by sgugger — APPROVED** [review]

**Pull request merged**
