### PR TITLE
[WIP]Add ViTPose to Transformers

### LINKED ISSUE #24915: ViTPose: Simple Vision Transformer Baselines for Human Pose Estimation
### Model description

ViTPose is used in 2D human pose estimation, a subset of the keypoint detection task #24044

It provides a simple baseline for vision transformer-based human pose estimation. It utilises a pretrained vision transformer backbone to extract features and a simple decoder head to process the extracted features. Despite no elaborate designs in the model, ViTPose obtained state-of-the-art (SOTA) performance of 80.9 AP on the MS COCO Keypoint test-dev set.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Code and weights: https://github.com/ViTAE-Transformer/ViTPose
Paper: https://arxiv.org/abs/2204.12484

@Annbless

### PR DESCRIPTION
**Pull request by shauray8**
# What does this PR do?
Adds ViTPose to Huggingface/Transformers

Code and weights: https://github.com/ViTAE-Transformer/ViTPose
Paper: https://arxiv.org/abs/2204.12484

Fixes #24915 

## Before submitting
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@amyeroberts

### CODE REVIEW

**Comment by shauray8** [comment]
@amyeroberts weights for ViTPose are in PyTorch checkpoint files, should I convert them into .bin or something else?

**Comment by amyeroberts** [comment]
@shauray8 You will want to write a conversion script, which translates the names of the weights in the state dict to their equivalent in transformers. These weights will then be loaded into the transformers model. Then we save the transformers model using `model.save_pretrained(...)` which will save out the weights in the desired format (safetensors) as well as all other necessary files such as the model config. 

For this model, because the encoder is ViT, the translation of these weights will follow a similar pattern to the conversion script here: https://github.com/huggingface/transformers/blob/main/src/transformers/models/vit/convert_vit_timm_to_pytorch.py

Similarly, the encoder structure can be implemented directly by using `#Copied from` statements to copy the ViT architecture in the modeling file. 

If you haven't seen it already, I'd also suggest looking through [this doc](https://huggingface.co/docs/transformers/add_new_model) as it covers in detail all the steps for adding a model to transformers.

**Comment by shauray8** [comment]
Thank you for the information and the link to the conversion script for ViT.

**Comment by amyeroberts** [comment]
@shauray8 Are you still actively working on this model addition? If you don't have the capacity to address it at the moment, we could open up to someone else in the community to take over. Let us know if you have any questions about the implementation.

**Comment by shauray8** [comment]
Hi, @amyeroberts I'm sorry for not keeping you informed on this, it was a little time-consuming transferring everything from mmcv especially, I think I've done most of it correctly, But it does not work as it should, the only thing I can think of is I have not transferred the weights correctly (I might be totally wrong though), If that's the case maybe I can still find some time and fix it.

**Comment by amyeroberts** [comment]
@shauray8 Let us know if you need help in getting it across the line. 

When you say that it's not working well - what tests are you running to confirm this? If you pass the same image to the mmcv implementation and this one, do you get the same outputs? If not, how about the same activations in the first layer? Debugging like this will help you pinpoint where the issue might be.

**Comment by shauray8** [comment]
Yes, I did compare to the results from the original code, that's the only test I did, I'll try debugging it step by step as you said and let you know If I need any help, maybe I'll try doing at faster this time

**Comment by shauray8** [comment]
@amyeroberts While debugging I couldn't find any non-trivial differences, opening it for the community again.

**Pull request closed without merging**
