### PR TITLE
[whisper] Clarify error message when setting max_new_tokens

### PR DESCRIPTION
**Pull request by benniekiss**
# What does this PR do?

This PR clarifies the error message returned when the length of the prompt tokens + `max_new_tokens` exceeds the  `max_target_positions` of the whisper model.

Addresses the discussion in #32571 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ylacombe

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]

**Comment by ylacombe** [comment]
Thanks for opening this PR @benniekiss !
There's weirdly a Whisper failing test. Would you like to first rebase the PR, and then we'll see what we can do if it's still there ?

**Comment by benniekiss** [comment]
the failing test is [here](https://github.com/huggingface/transformers/blob/8f8af0fb38baa851f3fd69f564fbf91b5af78332/tests/models/whisper/test_modeling_whisper.py#L1340-L1361)

It seems that the old error message is hardcoded in the test. Should I go ahead and update it to the new message so they are in sync?

**Comment by ylacombe** [comment]
Oh right, let's do this! It's a bit weird indeed, but let's just correct the test

**Review by ylacombe — APPROVED** [review]
Will merge once it's all green ! Thanks for iterating !

**Comment by benniekiss** [comment]
ofc! pleasure working with yall

**Pull request merged**
