### PR TITLE
Quantization / TST: Fix remaining quantization tests

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

This PR fixes the [remaining quantization tests](https://github.com/huggingface/transformers/actions/runs/9217736706/job/25360291113)( quanto quantized cache) + makes sure the GGUF tests are run (they all pass on the T4 VM) by removing it from the transformers-all-latest-gpu docker image to the quantization docker image

```bash
========================================================================================================= 11 passed, 3 warnings in 506.17s (0:08:26) ==========================================================================================================
```

cc @SunMarc @ydshieh @zucchini-nlp

### CODE REVIEW

**Review by zucchini-nlp — APPROVED** [review]
Oh, for quanto it's hardware differences I guess 🥲 
Thanks for fixing!

**Review by ydshieh — APPROVED** [review]
Thanks. BTW, what's the role of gguf here? 

I mean shouldn't we have some extra `require_xxx` for `class QuantoKVCacheQuantizationTest(unittest.TestCase):` ?

**Comment by younesbelkada** [comment]
For GGUF it is just that the tests were currently compltely skipped, these tests are independent from the quanto cache tests !

**Comment by ydshieh** [comment]
OK. But my question is still there: we don't need any `require_xxx` for `QuantoKVCacheQuantizationTest`? It looks like it requires some quantize libraries being installed, no?

**Review by SunMarc — APPROVED** [review]
LGTM ! +1 for @ydshieh comments. Let's add a `@require_quanto` for the kv-cache quantization tests

**Pull request merged**
