### PR TITLE
Skip some fuyu tests

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

The old story of offload tests for tiny models ...

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Thanks for handling!

**Review by amyeroberts — APPROVED** [review]
Sorry - I meant to approve!

**Comment by ydshieh** [comment]
The code assistant model will soon learn thanks == approve 😄

**Comment by amyeroberts** [comment]
@ydshieh I hope not! Often I say thanks for the work so far + requests for change 😆

**Pull request merged**
