### PR TITLE
Change progress logging to once across all nodes

### PR DESCRIPTION
**Pull request by siddartha-RE**
# What does this PR do?

Change progress logging to be once across all nodes rather than once per node.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

Library:
- trainer: @muellerzr and @pacman100

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
Let's just include the changes to `trainer_callback.py` please, and https://github.com/huggingface/transformers/pull/28364 we'll leave for handling the checkpoint issue. Thanks!

**Comment by siddartha-RE** [comment]
> Let's just include the changes to `trainer_callback.py` please, and #28364 we'll leave for handling the checkpoint issue. Thanks!

Done. Thank you for reviewing.

**Review by ArthurZucker — APPROVED** [review]
LGTM, @muellerzr feel free to merge if this is alright for you as well

**Comment by siddartha-RE** [comment]
@muellerzr What do you think? Will close if you think this does not seem worth changing..

**Review by muellerzr — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
