### PR TITLE
Update torch_extension.cpp

### PR DESCRIPTION
**Pull request by akshit397a**
few changes for better efficiency

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
@SunMarc  @ArthurZucker 
@dsikka  @dtlzhuangz nm @andyehrenberg 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by akshit397a** [comment]
kindly Reviw this PR

**Comment by akshit397a** [comment]
So will this PR be merged for correction or any other changes required 
@SunMarc @HuggingFaceDocBuilderDev @dsikka @vanpelt

**Review by SunMarc — COMMENTED** [review]
Hey @akshit397a, I'm not sure how this make it more efficient. The function are already declared in the header file, so this is just deduplication.

**Comment by akshit397a** [comment]
Hey, @SunMarc 
It was made more understandable and some minor fixes.
I will look into it and check what more could be done.
Can you suggest some where the issues are yet to be fixed

**Pull request closed without merging**
