### PR TITLE
Remove deprecated properties in tokenization_nllb.py and tokenization_nllb_fast.py

### PR DESCRIPTION
**Pull request by ymoslem**
# What does this PR do?

This PR fixes a typo in a warning in two tokenization files for the NLLB model. It changes `adder_tokens_decoder` into `added_tokens_decoder` and improves the warning's readability.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

- tokenizers: @ArthurZucker

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Hi @ymoslem, thanks for opening this PR!

What I would suggest is actually just removing these properties altogether, as they're deprecated and we're now on v4.39

**Comment by ymoslem** [comment]
Thanks @amyeroberts! Okay, I removed the deprecated properties, but some tests failed like this one. Should I edit it too?

https://github.com/huggingface/transformers/blob/76a33a10923ccc1074917f6b6a1e719e626b7dc9/tests/models/nllb/test_tokenization_nllb.py#L370-L373

**Comment by amyeroberts** [comment]
@ymoslem Yep - if we've deprecated a method, it's OK to remove from the tests here

**Review by ArthurZucker — COMMENTED** [review]
Hey! Thanks, are you still working on this? Could you rebase and fix the test so we can merge! 🤗

**Comment by ymoslem** [comment]
Hi @ArthurZucker I think it is fixed now. Please let me know if I should do something else. Thanks!

**Review by ArthurZucker — APPROVED** [review]
Thanks for updating!

**Comment by ArthurZucker** [comment]
COuld you rebase your branch to make sure we don't have any issues? 🤗

**Comment by ymoslem** [comment]
Now, it is synched with the latest repository. @ArthurZucker

**Comment by ArthurZucker** [comment]
can you push the merge here? 😉

**Pull request merged**
