### PR TITLE
Add `finetuned_from` property in the autogenerated model card

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

We already extract the info but it wasn't properly put in the metadata. This PR adds it.
cc @julien-c @osanseviero for the exact name of the tag to use.

### CODE REVIEW

**Review by julien-c — COMMENTED** [review]
conceptual LGTM!

**Review by osanseviero — APPROVED** [review]
Thanks a lot!

**Review by julien-c — COMMENTED** [review]
but for consistency we should also rename the other uses of this variable to base_model no?

i.e. in the model card text etc

basically grep/replace finetuned_from => base_model

**Comment by sgugger** [comment]
What did you have in mind exactly? The only text added is 
```
"This model is a fine-tuned version of f" [{self.finetuned_from}](https://huggingface.co/{self.finetuned_from}) on "
```
which doesn't contain the `finetuned_from` tag.

**Review by LysandreJik — APPROVED** [review]

**Comment by julien-c** [comment]
@sgugger i would rename the variable everywhere

**Comment by sgugger** [comment]
That's a breaking change in Transformers for cosmetic reasons only, so a big no no from my side.

**Comment by osanseviero** [comment]
I would go ahead with this PR as-is :fire:

**Review by julien-c — APPROVED** [review]
ok then

**Pull request merged**
