### PR TITLE
Optimize 1st token for beam_search

### PR DESCRIPTION
**Pull request by jiqing-feng**
We can repeat the outputs after the first token instead of repeating the first token inputs. The outputs are identical because the 1st token inputs are the same in each beam.

It could avoid extra computation.

I will update the rest of the generation methods once we agree on this change.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @gante @zucchini-nlp

**Comment by jiqing-feng** [comment]
Hi @gante @zucchini-nlp . Could you please take a review? Thx!

**Comment by gante** [comment]
Hi @jiqing-feng 👋 

The PR moves in the right direction, but we will want a different interface for it -- see "prefill" in [this tracker](https://github.com/huggingface/transformers/issues/30810). The prefill change is quite sensible with respect to interface, so we'll want to work on it ourselves. However, we'll be open to contributions after we add the prefill stage 🤗

**Comment by jiqing-feng** [comment]
> Hi @jiqing-feng 👋
> 
> The PR moves in the right direction, but we will want a different interface for it -- see "prefill" in [this tracker](https://github.com/huggingface/transformers/issues/30810). The prefill change is quite sensible with respect to interface, so we'll want to work on it ourselves. However, we'll be open to contributions after we add the prefill stage 🤗

Thx! Please let me know when the PR is ready :)

**Pull request closed without merging**
