### PR TITLE
[WIP] CLIP

### PR DESCRIPTION
**Pull request by patil-suraj**
# What does this PR do?

This PR adds OpenAI's CLIP model.
original repo: https://github.com/openai/CLIP
initial demo: https://colab.research.google.com/drive/1hwiCuKvw7hwSlE8yv7J1dh280PlYgPef?usp=sharing

### CODE REVIEW

**Comment by dribnet** [comment]
Awesome effort. Is the current version already compatible with (now merged) #10594 ?

**Comment by patil-suraj** [comment]
Thanks @dribnet 

I haven't added a feature extractor class for CLIP yet. We first need to finish the `ImageFeatureExtractor` (#01608)
Then the `ClipFeatureExtractor` can inherit from that. This PR will be ready to merge by the end of next week.

**Comment by LysandreJik** [comment]
Unstale

**Comment by patil-suraj** [comment]
continuing this in #11445

**Pull request closed without merging**
