### PR TITLE
Fix doc examples: ... takes no keyword arguments

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

In some doc examples, there are

```
          >>> y = XSoftmax.apply(x, mask, dim=-1)
```

which gives `TypeError: apply() takes no keyword arguments`.

This PR fixes it by

```
          >>> # Specify the dimension to apply softmax
          >>> dim = -1

          >>> y = XSoftmax.apply(x, mask, dim)
```

## Who can review?

@LysandreJik

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Thank you, @ydshieh !

**Comment by LysandreJik** [comment]
I tried to solve the merge conflicts but I ended up with code quality issues - do you mind taking a look when you have a minute? Sorry about that!

**Comment by ydshieh** [comment]
> I tried to solve the merge conflicts but I ended up with code quality issues - do you mind taking a look when you have a minute? Sorry about that!

Looks fine now :)

**Comment by LysandreJik** [comment]
This is perfect, thanks @ydshieh!

**Pull request merged**
