### PR TITLE
[Flax][WIP] added Flax Pegasus Models

### PR DESCRIPTION
**Pull request by bhadreshpsavani**
# What does this PR do?

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
@patil-suraj @patrickvonplaten

### CODE REVIEW

**Comment by patil-suraj** [comment]
Hi @bhadreshpsavani thanks for the PR, let us know if you want to continue working on this :)

**Comment by bhadreshpsavani** [comment]
Sure @patil-suraj,
I want to continue on it but I will need some help from you I think!
Shall I contact you slack If I need any guidance from you?
I will update this PR today with latest changes!

**Comment by patil-suraj** [comment]
Sounds good, happy to help :)

**Comment by patrickvonplaten** [comment]
Given that we have a cookie-cutter example now, it might be worth actually starting from scratch using the cookie-cutter that is based on BART - will probably be more efficient

**Comment by bhadreshpsavani** [comment]
Hi @patrickvonplaten 
I will start from scratch! That would be better.
I Will another PR, that will be fine right?

**Comment by bhadreshpsavani** [comment]
This one is being handled by above mentioned PR

**Pull request closed without merging**
