### PR TITLE
fix arg name in BLOOM testing and remove unused arg document

### PR DESCRIPTION
**Pull request by shijie-wu**
# What does this PR do?

* Fix argument name in BLOOM testing (`hidden_dropout` and `attention_dropout`)
* Remove document of unused arguments (`skip_bias_add`, `skip_bias_add_qkv` and `attn_pdrop`)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@thomasw21 @stas00 @TevenLeScao

### CODE REVIEW

**Comment by stas00** [comment]
Thank you for the fix, @shijie-wu 

Wrt `use_cache` won't it be better to actually set it to `True` - most models have it set to `True` and most users will get bad peformance out of the box with the default during `generate` with it being `False`.

I'm aware that the cat is out of the box, but there have been a lot of tweaks to the model post its release so perhaps such change would still be in the grace period of backward compatibility.

**Comment by stas00** [comment]
actually, looking at `generate` it says:

https://github.com/huggingface/transformers/blob/4157e3cd7e2bb5a7be6dc065a3e20c49cc1300ab/src/transformers/generation_utils.py#L1037-L1039

but it doesn't appear to be so, as the default it uses is `None`:

https://github.com/huggingface/transformers/blob/4157e3cd7e2bb5a7be6dc065a3e20c49cc1300ab/src/transformers/generation_utils.py#L919

but since most models have `use_cache == True` it's sometimes true.

tagging @patrickvonplaten - should the `generate` doc be updated to say that the default is `None` to match the code? and say that unless set explicitly the model's config sets it?

**Comment by shijie-wu** [comment]
I missed that `use_cache = True` for most models by default. If that's the case, I could update the default instead and revert the change to the doc.

**Comment by stas00** [comment]
So it's pretty clear it's a bug as all but 2 models have it set to `True`:

```
$ grep -Ir 'use_cache=True' src/transformers/models/*/config* |wc -l
45
$ grep -Ir  'use_cache=False' src/transformers/models/*/config* |wc -l
2
$ grep -Ir  'use_cache=False' src/transformers/models/*/config*
src/transformers/models/bloom/configuration_bloom.py:        use_cache=False,
src/transformers/models/trocr/configuration_trocr.py:        use_cache=False,
```

**Comment by shijie-wu** [comment]
If all models set `use_cache=True` shouldn't `.generate` also have `use_cache=True` by default?

**Comment by stas00** [comment]
Please let's wait for others to chime in. Perhaps setting it to `False` was not an omission but intentional.

**Comment by patrickvonplaten** [comment]
The `use_cache` interior mechanisms are indeed a bit hard to understand. Think we haven't done a good job here. Thanks for pointing this out. 

IMO, `use_cache` should be set to `True` for all models and IMO it was probably a mistake to not set it to `True` for BLOOM.
Or is there a maybe a reason behind it (cc @thomasw21 @younesbelkada ?). If `use_cache=False` it means that no tensors containing past generated keys are moved around - was this maybe done on purpose given the size of the model?

 Regarding the generate docs we decided with @gante  to write the defaults to how the default to depending on what's set in the config, so I think the docstring is ok/correct there. Also note that `generate` will soon go through a major refactor regarding the configuration.

Regarding whether we should change the default to True  - I actually don't know really. If it would have been for a small model I would have said definitely yes, but for BLOOM which requires multi-gpu for inference I'm not 100% sure how much the memory consumption goes up when enabling it and running generate with `accelerate` - could we try it out ? cc @younesbelkada

**Comment by stas00** [comment]
Thank you for this great feedback, Patrick.

In addition as I have just discovered there are many models that don't set `use_cache` in their config at all. And I don't think there is a super-class default that is inherited. Perhaps there should be one?

Also it appears that `use_cache` is often a tri-state:

https://github.com/huggingface/transformers/blob/4157e3cd7e2bb5a7be6dc065a3e20c49cc1300ab/src/transformers/models/t5/modeling_t5.py#L918

so perhaps `generate` could reflect that - or if things change with refactor then I trust the new way will take care of this.

wrt memory usage in Bloom - recalculating say 100 tokens for each new token would be quite slow. So it's a question of whether `use_cache=False` + large BS gives better throughput than `use_cache=True`+small BS - probably can measure empirically? though the outcome would be highly hardware dependent.

**Review by thomasw21 — APPROVED** [review]
Thanks for the changes! All make sense to me.

Concerning the usage of `use_cache=True` I think the original reason was the masking was not effectively causal, ie you replace pre softmax values with 1e-5 which in most case gets converted to 0 after softmax but you get some weird edge cases where it doesn't https://github.com/younesbelkada/transformers/blob/3a59eb3ffce941403ff5145decb5214978edd390/src/transformers/models/bloom/modeling_bloom.py#L89 My intuition is that it got to the point where generation actually changed due to this edge case.  I think probably @younesbelkada knows more about it.

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for fixing @shijie-wu !
Can confirm the slow tests pass with your changes 💪 
Also I can confirm that the default `use_cache` should be set to `True` (I think that we expect most of the users to use `use_cache=True` as explained by @stas00 ).  I have pushed a commit to fix this mistake. 
Note that for the main BLOOM models, the `use_cache` parameter is set to `True` from the config file so it won't affect current users' performance. Also, FYI, it appears that for large-scale models (specifically BLOOM-176) `use_cache=False` seems to be slightly faster than `use_cache=True` (from discussing with @Narsil), probably due to the reasons described by @patrickvonplaten.
Thanks!  

EDIT: In the newest BLOOM version `use_cache=True` is faster than `use_cache=False` for BLOOM-176

**Review by stas00 — APPROVED** [review]

**Comment by stas00** [comment]
@LysandreJik, could we please make a note in the next release that 

* BLOOM's `use_cache`'s original default value was incorrectly set to `False` and this release it has been corrected to `use_cache=True` - as this is somewhat backward compatibility breakage. and we hope our users will forgive us as this is still a new model that is going through minor fixes. `use_cache=True` leads to a much faster generation at the cost of larger memory requirements to store the cached values.

Thank you!

**Comment by younesbelkada** [comment]
@stas00 I was thinking that we should probably also change it for tcocr model for consistency with other models on the library as suggested by @shijie-wu ?

**Comment by stas00** [comment]
I thought so too, but perhaps let's check in with the porter of that model to see if perhaps it was by design?

Would you like to do that? and perhaps in a separate PR so that it's loud and clear in the history of the project? with reference to this PR for context.

Thank you!

**Comment by younesbelkada** [comment]
Sure, happy to take care of that! 
Will tag also the porter of the model and double check 
Thanks again!

**Pull request merged**
