### PR TITLE
enable xla fsdp

### PR DESCRIPTION
**Pull request by hanwen-sun**
# What does this PR do?

We have supported xla fsdp in accelerator, so we should enable xla fsdp in transformers.
the support of xla fsdp in accelerate: https://github.com/huggingface/accelerate/pull/2176  and  https://github.com/huggingface/accelerate/pull/2941

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @muellerzr @SunMarc

**Review by muellerzr — APPROVED** [review]
Much appreciated for the enable!

**Review by amyeroberts — COMMENTED** [review]
I don't think we can do this directly. AFAICT this was enabled in 0.28 but the required version in our setup.py for accelerate is 0.21. Instead we'll need to add a condition checking the accelerate version is >= 0.28

**Comment by hanwen-sun** [comment]
> I don't think we can do this directly. AFAICT this was enabled in 0.28 but the required version in our setup.py for accelerate is 0.21. Instead we'll need to add a condition checking the accelerate version is >= 0.28

So I need to add a condition checking that accelerate version is >= 0.28?

**Comment by amyeroberts** [comment]
@hanwen-sun Yes - you should add `is_accelerate_available("0.28.0")` to the if statement

**Comment by hanwen-sun** [comment]
> @hanwen-sun Yes - you should add `is_accelerate_available("0.28.0")` to the if statement

thank you, I have updated.

**Review by SunMarc — APPROVED** [review]
Nice !

**Review by amyeroberts — APPROVED** [review]
Thanks!

**Comment by steveepreston** [comment]
Created #34197 to revert this change due to #34176 issue.

**Pull request merged**
