### PR TITLE
Translating agents_advanced.md to Chinese

### PR DESCRIPTION
**Pull request by HMJ0628**
# What does this PR do?
I have translated agents_advanced.md to Chinese. Please let me know if there are any corrections. Thank you very much!

Fixes # (issue)

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @stevhliu

**Review by stevhliu — APPROVED** [review]
Thanks for your translation! Remember to request a review from another contributor who can read the translated content!

**Comment by HMJ0628** [comment]
OK，I will find another contributor to review.

**Comment by asdkfjsd** [comment]
Your translation is simple and easy to understand for me.

**Pull request merged**
