### PR TITLE
Map `RealmBertModel` for `AutoModel`

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

This PR maps `RealmModel` to be able to use it with `AutoModel` - for consistency with `BertModel` 

Why this PR? I wanted to automate tests for `BetterTransformers` integration in `optimum` without having to import manually the class, see here: https://github.com/younesbelkada/optimum/blob/49575c5b016392383f0c2ebc1565ef56747b87e6/tests/bettertransformers/test_bettertransformers.py#L68 
Since `Realm` should be supported by `BetterTransformers`, this PR would help me design easier-to-implement tests

cc @sgugger @ydshieh 

https://github.com/huggingface/optimum/pull/423

### CODE REVIEW

**Comment by ydshieh** [comment]
Hi @younesbelkada 
We should also work on `src/transformers/__init__.py`, but otherwise LGTM, thanks!

**Comment by younesbelkada** [comment]
Ah yes, great catch! Will add it now

**Review by sgugger — COMMENTED** [review]
I'm not really sure this should be added. `RealmBertModel` is a building block for the other Realm models, not something that should be public or in one of the auto-mappings.

Also I just looked at the use on the Hub, and Realm is far from being a priority in terms of use for BetterTransformers ;-)

**Comment by younesbelkada** [comment]
Thanks a lot for the explanation!
Yes let's stay pragmatic, I will probably just remove it from the `BetterTransformers` test

**Comment by ydshieh** [comment]
@sgugger But we usually expose the base model, no, like `BertModel`?

**Comment by sgugger** [comment]
Yes, but I'm very unsure that this is the base REALM model. It's more of a building block towards it.

**Pull request closed without merging**
