### PR TITLE
Use the new hub ci

### PR DESCRIPTION
**Pull request by XciD**
Uses the new CI environment for tests, which uses Gitaly and is automatically updated to the latest version of the Hub.

### CODE REVIEW

**Comment by julien-c** [comment]
Yay!

**Comment by XciD** [comment]
> Yay!

Blocked by https://github.com/huggingface/huggingface_hub/pull/898 :)

**Comment by julien-c** [comment]
Done in #17716, @XciD lost a contribution to the codebase =) =)  cc @sgugger @LysandreJik

**Comment by sgugger** [comment]
If you don't ping us for reviews, your PR doesn't exist :-p

**Pull request closed without merging**
