### PR TITLE
Fix tokenizer saving/loading with custom token objects

### PR DESCRIPTION
**Pull request by mozharovsky**
## Summary

This PR fixes issue #5571. 

Pre-trained tokenizers might wrap tokens around custom types (e.g. `AddedToken` from **🤗/tokenizers**) which makes (de)serialization without additional meta information difficult. This PR uses `jsonpickle` library which particularly solves  objects (de)serialization problem.

A little drawback of this approach is that type information is a subject of change and such changes will break back-compatibility once happened. But this seems just like an agreement for making careful back-compatible changes.

### CODE REVIEW

**Comment by mozharovsky** [comment]
Investigating the issues 🤓

**Comment by mozharovsky** [comment]
Looks much better now 🎉

@n1t0 @thomwolf could you please take a glance? :)

**Comment by mozharovsky** [comment]
I did a bit of refactoring to have load/dump methods reusable across the library. 


These changes introduce a new scope for the common File IO methods (like json pickle load/dump). Although there is an already existing `file_utils` scope, I believe it's not supposed to contain the common IO operations as the docs say (`Utilities for working with the local dataset cache.`).

@LysandreJik, could you please review the changes? :)

**Comment by mozharovsky** [comment]
It looks like #6026 fixed the issue. But nevertheless this PR is still relevant since it guarantees tokenizers saving/loading with objects of arbitrary types.

**Comment by LysandreJik** [comment]
Hi, thanks a lot for your contribution! Unfortunately we're very strict about adding new dependencies, and this doesn't really change the existing behavior. I'm not sure I see the pros of introducing this new scope vs the cons of integrating a new dependencies + updating existing code.

**Comment by mozharovsky** [comment]
Hi, thanks for replying! I respect your policy regarding the third-party dependencies, this makes sense. Anyway, the current approaches compromise tokenizers (de)serialization with introducing new objects to include (besides `AddedToken` instances).

This might be a subject of future improvements once new types are introduced into the tokenizer configs, but I think it makes sense to consider generalizing the behavior.

If it makes sense, I could wrap saving/loading configs into the new scope, though it's far from generalizing, at least adding new cases to handle will be easier. What do you think? :)

**Pull request closed without merging**
