### PR TITLE
I added new doc string into the MusicGenAttention class.

### PR DESCRIPTION
**Pull request by hisushanta**
I added a comprehensive and informative docstring to the MusicGenAttention class. It describes each of the parameters in the class in detail.

And now see what looks like my doc-string.
Screenshot from 2023-10-23 07-03-02

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by kiranaayar** [comment]
i m ok

**Review by ArthurZucker — COMMENTED** [review]
Hey! Thanks for the contribution, this class is not part of the public api so the dosctring will not appear on the MusicGen documentation + it's a copied from so this is breaking the consistency! Let's just keep what we already have 🤗

**Comment by hi-sushanta** [comment]
Hey! Thanks for the feedback. But the docstring is not copied content.

**Comment by ArthurZucker** [comment]
What I mean is that the reason why the CI are broken is because the module to which you are adding docstring uses the `# Copied from` statement, which enforces that the entire module is copied from the source!

**Comment by hi-sushanta** [comment]
Would it be okay to close this pull request now?

**Comment by ArthurZucker** [comment]
Of course! 🤗

**Pull request closed without merging**
