### PR TITLE
fix blip2config int8 error to serialize json

### PR DESCRIPTION
**Pull request by Andrechang**
# What does this PR do?

Running the following using transformers=4.30.0.dev0
```
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
model = AutoModelForVision2Seq.from_pretrained("Salesforce/blip2-opt-2.7b", quantization_config=bnb_config, device_map='auto')
print(model.config)
```
Will give the following error:
```
TypeError: Object of type BitsAndBytesConfig is not JSON serializable
```
Solution add convert BitsAndBytesConfig to json in Blip2Config

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@amyeroberts
@NielsRogge

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @younesbelkada

**Review by younesbelkada — COMMENTED** [review]
Hi @Andrechang 
Thanks for the PR
interestingly I couldn't reproduce on my side with the `main` branch of transformers. Could you double check by using the main branch of transformers? Or maybe the reproducible snippet needs to be updated. What I ran is:
```python
import torch
from transformers import AutoModelForCausalLM, BitsAndBytesConfig, AutoModelForVision2Seq

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
model = AutoModelForVision2Seq.from_pretrained("Salesforce/blip2-opt-2.7b", quantization_config=bnb_config, device_map='auto')
print(model.config)
```
Thanks

**Review by younesbelkada — COMMENTED** [review]
Hi @Andrechang 
Thanks for the PR
interestingly I couldn't reproduce on my side with the `main` branch of transformers. Could you double check by using the main branch of transformers? Or maybe the reproducible snippet needs to be updated. What I ran is:
```python
import torch
from transformers import AutoModelForCausalLM, BitsAndBytesConfig, AutoModelForVision2Seq

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)
model = AutoModelForVision2Seq.from_pretrained("Salesforce/blip2-opt-2.7b", quantization_config=bnb_config, device_map='auto')
print(model.config)
```
Thanks

**Comment by Andrechang** [comment]
I ran `pip install -e .` on transformer main branch 8b169142f8b5735f25ad81313ee382350161d993
Then ran the code snippet and gave the error: 
`TypeError: Object of type BitsAndBytesConfig is not JSON serializable`

Adding my commit will fix this

print screen attached
install0

error0

**Review by younesbelkada — COMMENTED** [review]
Thanks! 
I have finally managed to reproduce by calling `model.config.to_json_string()`,  see related: https://github.com/huggingface/transformers/issues/24131 
I think the fix should go in `transformers/configuration_utils.py` to support all models and not only Blip2, and add [this block](https://github.com/huggingface/transformers/blob/main/src/transformers/configuration_utils.py#L809-813) , in this line: https://github.com/huggingface/transformers/blob/535542d38d7f19c6347ad684347737a38107f148/src/transformers/configuration_utils.py#L787 (before the call to that method)
Let me know if you want to address this change, as it will also fix the issue: #24131 - otherwise happy to do it!

**Comment by younesbelkada** [comment]
Hi @Andrechang 
Again thanks very much for flagging the issue, I realized that you have flagged an issue that is quite important to fix, therefore I made https://github.com/huggingface/transformers/pull/24137 and added you as a co-author, will merge that PR and I will close this one. Feel free to re-open it if you think that the issue is not resolved. Again thanks a lot!

**Comment by Andrechang** [comment]
Thank you for checking and for fix

**Pull request closed without merging**
