### PR TITLE
Fix cache for GPT-Neo-X

### LINKED ISSUE #17745: GPT-NEOX RuntimeError
Hi, when I ran the model GPT-NEOX, I got the "RuntimeError: batch1 dim 2 must match batch2 dim1" in modeling_gpt_neox.py, line 212. 
So I tried to debugg and fix this problem, I found the code "present = None if use_cache else (key, value)" in modeling_gpt_neox.py, line 146. 
Is that logical wrong? and the correct coding should be "present = None if not use_cache else (key, value)" ?

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

As pointed out on #17745, there is a problem with the logic in the cache for GPT-Neo-X. Can confirm I can use it for generation after this PR, but not before.

Fixes #17745

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Thanks a lot! If it's not too much work could you maybe try running this test: https://github.com/huggingface/transformers/blob/522a9ece4baeb5abfec8953ef76469a530e987d5/tests/models/gpt_neox/test_modeling_gpt_neox.py#L144 

I think right now it's not run (seems like the test function was removed)

**Review by patrickvonplaten — APPROVED** [review]

**Comment by patrickvonplaten** [comment]
I can also do it also otherwise :-)

**Comment by sgugger** [comment]
Added tests that were removed and had a corresponding `check` function. Thanks for flagging this!

**Review by patrickvonplaten — COMMENTED** [review]
Looks good to me!

**Pull request merged**
