### PR TITLE
[DOCS] add example NoBadWordsLogitsProcessor

### PR DESCRIPTION
**Pull request by SoyGema**
# What does this PR do?

See #24783 .
Add example to NoBadWordsLogitsProcessor.
Some analysis [here](https://github.com/SoyGema/contrib_schema) .
Kudos to @nablabits 

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@gante

### CODE REVIEW

**Review by SoyGema — COMMENTED** [review]
Fix L764 : 
- add >>> and remove one #

Fix L767 :
- remove empty line

**Review by gante — APPROVED** [review]
Thank you for the clean example @SoyGema 🔥

**Comment by gante** [comment]
(@SoyGema did a minor edit on the PR header: the word "fixes" before an issue number on a PR automatically closes the issue when the PR is merged)

**Review by sgugger — APPROVED** [review]
Thanks for adding this!

**Pull request merged**
