### PR TITLE
Add CrystalCoder Model

### PR DESCRIPTION
**Pull request by TianhuaTao**
# What does this PR do?

This is the implementation for [CrystalCoder](https://huggingface.co/LLM360/CrystalCoder) and [CrystalChat](https://huggingface.co/LLM360/CrystalChat) model by LLM360. 

There is an additional example script on running the model at `src/transformers/models/crystalcoder/crystalchat_example.py`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Hi @TianhuaTao, thanks for opening this PR! 

The easiest and recommended way to make a model available in `transformers` is to add the modeling code directly on the hub: https://huggingface.co/docs/transformers/custom_models. We have as much support there as we can (let us know if anything isn't working 🤗 !)

This means, once working, the model can be found and used immediately without having to go through the PR process. We find this is a lot quicker as the bar for adding code into the library is high due to the maintenance cost of every new model, and so reviews take quite a while.

**Comment by TianhuaTao** [comment]
Hi @amyeroberts , thanks for your prompt reply! 
We already implemented CrystalCoder as a custom model which is published here (https://huggingface.co/LLM360/CrystalCoder). However, we also want to submit CrystalCoder to the HF leaderboard which requires CrystalCoder to live natively in the transformers library --- thus this PR is created.
Help and guidance would be much appreciated

**Comment by amyeroberts** [comment]
@TianhuaTao OK, understood! Happy to hear you were able to add the remote code for the model. Let us know when this PR is ready for review 🤗

**Comment by amyeroberts** [comment]
Hi @TianhuaTao, 

Re my previous comment, I didn't know about [lighteval](https://github.com/huggingface/lighteval). This library will enable you to evaluate your model on the same benchmarks used for the leaderboard, without having to merge in a model PR. 

What I suggest is running the benchmarks using lighteval. If the model performs significantly well, then we can consider adding it into the transformers library.

**Pull request closed without merging**
