### PR TITLE
BatchFeature.to() supports non-tensor keys

### PR DESCRIPTION
**Pull request by Rocketknight1**
This PR fixes a bug in the preprocessing for several pipelines. The pipelines were calling `.to()` on a `BatchFeature` which had a string feature, which caused an error. This update was also requested internally in Slack!

cc @ydshieh

### CODE REVIEW

**Comment by ydshieh** [comment]
Thank you @Rocketknight1 .

2 questions:

- Is this the only one to change? I see 3 failed tests (in torch pipeline CI reports).
- Do you think it makes sense to have this implemented directly in `BatchFeature` instead of outside it?

**Comment by Rocketknight1** [comment]
@ydshieh good spot, I fixed it for all three! We could consider rewriting `BatchFeature.to()` like you suggested though, let me ask people

**Review by LysandreJik — APPROVED** [review]
Thanks @Rocketknight1!

**Comment by LysandreJik** [comment]
Are there other areas that should be updated? Arthur tells me about Pixtral as an example

**Comment by Rocketknight1** [comment]
@LysandreJik I checked the codebase for methods overriding `to()`. Mostly this was in modeling code to create objects like `NestedTensor` - these are safe because their contents should always be `torch.Tensor`.

The exceptions were:
- Pixtral
- `BatchEncoding` (the tokenizer output class)

In both cases, I updated their methods to make sure they only call `to()` on `torch.Tensor`!

**Review by LysandreJik — APPROVED** [review]
perfect, thanks!

**Pull request merged**
