### PR TITLE
[`MobileNet-v2`] Fix ONNX typo 

### LINKED ISSUE #20856: transformers.onnx mobilenet_v2 not supported but exists in supported list
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-6.0.6-76060006-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Huggingface_hub version: 0.10.1
- PyTorch version (GPU?): 1.13.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes (using notebooks for training)
- Using distributed or parallel set-up in script?: no

`KeyError: "mobilenet-v2 is not supported yet. Only ['albert', 'bart', 'beit', 'bert', 'big-bird', 'bigbird-pegasus', 'blenderbot', 'blenderbot-small', 'bloom', 'camembert', 'clip', 'codegen', 'convbert', 'convnext', 'data2vec-text', 'data2vec-vision', 'deberta', 'deberta-v2', 'deit', 'detr', 'distilbert', 'electra', 'flaubert', 'gpt2', 'gptj', 'gpt-neo', 'groupvit', 'ibert', 'imagegpt', 'layoutlm', 'layoutlmv3', 'levit', 'longt5', 'longformer', 'marian', 'mbart', 'mobilebert', 'mobilenet_v1', 'mobilenet_v2', 'mobilevit', 'mt5', 'm2m-100', 'owlvit', 'perceiver', 'resnet', 'roberta', 'roformer', 'segformer', 'squeezebert', 'swin', 't5', 'vision-encoder-decoder', 'vit', 'whisper', 'xlm', 'xlm-roberta', 'yolos'] are supported. If you want to support mobilenet-v2 please propose a PR or open up an issue."`

### Who can help?

@amyeroberts @NielsRogge 

### Information

- [X] My own modified scripts

### Tasks

- [x] My own task or dataset (give details below)

### Reproduction

```
from transformers import  AutoModelForImageClassification
from transformers.onnx import FeaturesManager

model = AutoModelForImageClassification.from_pretrained("google/mobilenet_v2_1.0_224")
model_kind, model_onnx_config = FeaturesManager.check_supported_model_or_raise(model)
```

### Expected behavior

Should be able to get model_onnx_config for export.

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/20856

In order to get which model is exportable with ONNX, we need first to pre-process the model type before checking with `FeaturesManager` by replacing the `_` with `-`. 

This has been forgotten for `mobilenet` family models which leads to errors such as the one described in #20856 

It seems that the proper way to call the method `get_supported_features_for_model_type`, is to first apply some pre-preprocessing as it is done [here](https://github.com/huggingface/transformers/blob/d87e381f9303c7d6a8aa7333dc09ed767de7395f/src/transformers/onnx/features.py#L723). This patch has been added to `tests/onnx/test_onnx_v2.py` too

This PR fixes these issues.

Also I would like to hear from @lewtun as it's my first ONNX-related PR.

cc @sgugger @ArthurZucker

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM, did you test the export on mobilenet models in this branch just to be sure it fixes the issue?

**Comment by younesbelkada** [comment]
I can confirm the script below works:
```
from transformers import  AutoModelForImageClassification
from transformers.onnx import FeaturesManager

model = AutoModelForImageClassification.from_pretrained("google/mobilenet_v2_1.0_224")
model_kind, model_onnx_config = FeaturesManager.check_supported_model_or_raise(model)
```
which yields to successfully retrieving the MobileNet ONNX config, however running `optimum-cli export onnx --model google/mobilenet_v2_1.0_224 onnx/` gives an error 
```
KeyError: "mobilenet-v2 is not supported yet. Only {'xlm', 'deberta', 'distilbert', 'electra', 'mobilebert', 'm2m-100', 'segformer', 'convbert', 'longt5', 'data2vec-text', 'flaubert', 'gptj', 'detr', 'layoutlmv3', 'mobilevit', 'groupvit', 'levit', 'mbart', 'big-bird', 'albert', 'bloom', 't5', 'swin', 'roberta', 'blenderbot', 'bert', 'yolos', 'marian', 'deit', 'layoutlm', 'perceiver', 'xlm-roberta', 'vit', 'gpt-neo', 'mt5', 'bigbird-pegasus', 'codegen', 'clip', 'whisper', 'data2vec-vision', 'squeezebert', 'convnext', 'deberta-v2', 'ibert', 'roformer', 'blenderbot-small', 'bart', 'beit', 'resnet', 'camembert', 'gpt2'} are supported. If you want to support mobilenet-v2 please propose a PR or open up an issue."
```
Mobilenet is not listed in `optimum.exporters.tasks`, probably by mistake or for some other reason. Opened a PR to support `Mobilenet` in optimum, https://github.com/huggingface/optimum/pull/633 I can confirm the model can be safely exported after checking out this PR!

**Review by ArthurZucker — APPROVED** [review]
Thanks for the fix 😄

**Comment by younesbelkada** [comment]
Now the PR https://github.com/huggingface/optimum/pull/633 being merged the export works as expected, merging

**Pull request merged**
