### PR TITLE
# Fix an error of 'ValueError: mean must have 1 elements if it is an iterable, got 3' for method 'infer_channel_dimension_format' in 'image_utils.py'

### PR DESCRIPTION
**Pull request by davychxn**
Background:
If we use 'sentence-transformers/clip-ViT-B-32' with Transformers, which has an image Tokenizer. The Tokenizer would convert Image to Numpy array first, then infer from its shape to decide if it's ChannelDimension.FIRST or ChannelDimension.LAST.

For example, we have an image, whose shape is (512, 512, 3). For a common image, the shape means that the size is 512 * 512 pixels, and it has RBG, 3 color channels.

When setting 'input_data_format',
The infer algorithm(in 'image_utils.py', 'infer_channel_dimension_format' method) would check the first and third element of the image's shape. If it's 1(Gray channel only) or 3(RBG channels), it decides from the content of the element, and set 'input_data_format' to be ChannelDimension.FIRST(the first element is 1 or 3) or ChannelDimension.LAST(the third element is 1 or 3).

But the problem is, if we have a narrow image whose shape is (1, 1000, 3), the infer algorithm would report and raise an error: 'The channel dimension is ambiguous. Got image shape (1, 1000, 3). Assuming channels are the first dimension.' 'ValueError: mean must have 1 elements if it is an iterable, got 3'

My fix is to set 'input_data_format' before the image being converted to Numpy array. If it's a PIL image, the third element of its shape must give its color channels, and 'input_data_format' must be 'ChannelDimension.LAST'.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by davychxn** [comment]
header-separator
This is an error generating image, which has a shape of (1, 1000, 3)

**Comment by davychxn** [comment]
@amyeroberts @gante 
Would you help to review my change? Thank you.

**Comment by amyeroberts** [comment]
Hi @davychxn, thanks for opening this PR! 

Have you tried calling the image_processor with `input_data_format` set e.g.: 

```py
inputs = image_processor(images, input_data_format="channels_last")
```

The `input_data_format` argument was added for cases when there might be ambiguity and to avoid inferring

**Comment by davychxn** [comment]
@amyeroberts 
Thank you for your opinion.
Yes, I can use the way you mentioned in sentence-transformers' code to avoid the issue.

But it's still a defect in inferring algorithm. If we have an image with the shape of (1, xxx, 3) or (3, xxx, 1), it would raise an exception.

So, you would prefer me to fix it in sentence-transformers?

**Comment by davychxn** [comment]
Sometimes the exception could break your training process and waste you a lot of time, could be annoying.

**Comment by amyeroberts** [comment]
@davychxn 

> But it's still a defect in inferring algorithm. If we have an image with the shape of (1, xxx, 3) or (3, xxx, 1), it would raise an exception.

Yes, unfortunately this is very hard to get around. This is in part why the functional is called "infer" rather than "get". It would be better to pass in `input_data_format="channels_last" as this avoids doing this type inference every time the image processor is called.

**Comment by davychxn** [comment]
OK, @amyeroberts ,

I've submitted another PR at sentence-transformers.
I'll wait for their reply and close this PR a bit later. Thank you.

**Pull request closed without merging**
