### PR TITLE
Add timeout parameter to load_image function

### LINKED ISSUE #25168: Add support for timeout parameter for load_image
### Feature request

Add a parameter timeout to the `image_utils.py:load_image` function, which would enable setting the timeout for the requests call. This parameter should be plumbed in through all the ways to call that function (so add support for it in all the image related pipelines).

Alternatively, you should add a `requests_params` parameter, which should be a dictionary, to enable passing any parameters to requests.get. 

### Motivation

When using requests, the default timeout is None, which means that the request will wait (hang) until the connection is closed. Some servers for whatever reason don't return anything, but also don't close the connection. It would be useful to be able to set a timeout for these cases. 

### Your contribution

I can contribute a PR for this.

### PR DESCRIPTION
**Pull request by rolisz**
# What does this PR do?

This PR adds a timeout parameter to all pipelines that can fetch images from remote URLs. Without a timeout, the request can hang indefinitely. 

Fixes #25168

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x ] Did you write any new necessary tests?

## Who can review?

@amyeroberts

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for adding this! 

Just two small nits - otherwise looks good to me! 

cc @Narsil  for the changes in image pipelines

**Review by Narsil — APPROVED** [review]
LGTM !

**Comment by rolisz** [comment]
@amyeroberts I've done the requested changes

**Review by amyeroberts — APPROVED** [review]
Thanks for iterating!

**Pull request merged**
