### PR TITLE
[s2s] add support for overriding config params

### PR DESCRIPTION
**Pull request by stas00**
add support for overriding model params:
```
python finetune.py --encoder_layerdrop 0.1 --decoder_layerdrop 0.1 --dropout 0.1 --attention_dropout 0.1
```
as requested at  https://github.com/huggingface/transformers/issues/6018

`README.md` seems to be mostly the editor removing superfluous whitespace - not sure why github shows it - normally it doesn't. The only added doc section is https://github.com/stas00/transformers/blob/seq2seq-train_params-1/examples/seq2seq/README.md#finetuning-training-params

### CODE REVIEW

**Review by sshleifer — COMMENTED** [review]
Can you add test cases:
- good case where model.config has the new value
- case (T5) that hits your assert. its called `dropout_rate` in t5. We can expose that or leave it for future work.

I'm surprised you didn't need to change the `CHEAP_ARGS` constant in the tests.

**Comment by sshleifer** [comment]
The code looks perfect.

**Comment by stas00** [comment]
> I'm surprised you didn't need to change the `CHEAP_ARGS` constant in the tests.

because the new args are optional? Unless you mean something else.

...Working on the tests.

**Comment by stas00** [comment]
Added tests as suggested. 

Is it the case that the tests shouldn't be refactored either?

**Comment by stas00** [comment]
Here is a possible merged 2 tests into one - had to create a new output dir - or need to rewrite to use context manager... let me know if this looks better:

```
def test_finetune_extra_model_args():
    # test models whose config includes the extra_model_args
    model = BART_TINY
    args_d: dict = CHEAP_ARGS.copy()

    task = "summarization"
    tmp_dir = make_test_data_dir()
    output_dir = tempfile.mkdtemp(prefix="output_")

    args_d.update(
        data_dir=tmp_dir,
        model_name_or_path=model,
        tokenizer_name=None,
        train_batch_size=2,
        eval_batch_size=2,
        output_dir=output_dir,
        do_predict=False,
        task=task,
        src_lang="en_XX",
        tgt_lang="ro_RO",
        freeze_encoder=True,
        freeze_embeds=True,
    )

    args_d1 = args_d.copy()
    args_d1["output_dir"]=tempfile.mkdtemp(prefix="output_2_")
    extra_model_params = ("encoder_layerdrop", "decoder_layerdrop", "dropout", "attention_dropout")
    for p in extra_model_params:
        args_d1[p] = 0.5
    args = argparse.Namespace(**args_d1)
    model = main(args)
    for p in extra_model_params:
        assert getattr(model.config, p) == 0.5, f"failed to override the model config for param {p}"

    ### test models whose config doesn't include the extra_model_args
    model = T5_TINY
    output_dir = tempfile.mkdtemp(prefix="output_")
    args_d2 = args_d.copy()
    args_d2.update(
        model_name_or_path=model,
    )

    unsupported_param = "encoder_layerdrop"
    args_d2[unsupported_param] = 0.5
    args = argparse.Namespace(**args_d2)
    with pytest.raises(Exception) as excinfo:
        model = main(args)
    assert str(excinfo.value) == f"model config doesn't have a `{unsupported_param}` attribute"


```

**Comment by sshleifer** [comment]
good alias
```bash
sty () {
	make style
	flake8 --ignore=P,E501,E203,W503,E741 examples templates tests src utils
}
```

**Pull request merged**
