### PR TITLE
Make fsdp ram efficient loading optional

### LINKED ISSUE #1948: Error downloading wav2vec2 model when using accelerate launch with FSDP
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 125.55 GB
- GPU type: NVIDIA TITAN V
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - fsdp_config: {'fsdp_auto_wrap_policy': 'NO_WRAP', 'fsdp_backward_prefetch_policy': 'NO_PREFETCH', 'fsdp_forward_prefetch': False, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': False}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

download_wav2vec2.py
```python
from transformers import Wav2Vec2Model

model_url = 'facebook/wav2vec2-base-960h'
model = Wav2Vec2Model.from_pretrained(model_url)
```
If I run `python download_wav2vec2.py` in CLI it downloads the model as expected, but if I run `accelerate launch download_wav2vec2.py` I get a `NotImplentedError`. If I disable FSDP it works fine. This is the stack trace I get with FSDP enabled:
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/cube/home/AD/mjsimmons/zugubul/src/zugubul/models/cache/try_download_wav2vec2.py", line 5, in <module>
    model = Wav2Vec2Model.from_pretrained(model_url)
  File "/mnt/cube/home/AD/mjsimmons/zugubul/.venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2876, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/mnt/cube/home/AD/mjsimmons/zugubul/.venv/lib/python3.8/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 1470, in __init__
    self.encoder = Wav2Vec2Encoder(config)
  File "/mnt/cube/home/AD/mjsimmons/zugubul/.venv/lib/python3.8/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 759, in __init__
    self.pos_conv_embed = Wav2Vec2PositionalConvEmbedding(config)
  File "/mnt/cube/home/AD/mjsimmons/zugubul/.venv/lib/python3.8/site-packages/transformers/models/wav2vec2/modeling_wav2vec2.py", line 391, in __init__
    self.conv = weight_norm(self.conv, name="weight", dim=2)
  File "/mnt/cube/home/AD/mjsimmons/zugubul/.venv/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py", line 109, in weight_norm
    WeightNorm.apply(module, name, dim)
  File "/mnt/cube/home/AD/mjsimmons/zugubul/.venv/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py", line 50, in apply
    setattr(module, name, fn.compute_weight(module))
  File "/mnt/cube/home/AD/mjsimmons/zugubul/.venv/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py", line 25, in compute_weight
    return _weight_norm(v, g, self.dim)
NotImplementedError: Could not run 'aten::_weight_norm_interface' with arguments from the 'Meta' backend. This could be 
because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom 
build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 
'aten::_weight_norm_interface' is only available for these backends: [CPU, CUDA, BackendSelect, Python, 
FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, 
AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, 
AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, 
AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, 
FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].
```

### Expected behavior

Downloads dataset without error when running `accelerate launch download_wav2vec2.py`.

### PR DESCRIPTION
**Pull request by pacman100**
# What does this PR do?
1. Make fsdp ram efficient loading optional. Certain models are having issues when handling meta devices during pre-trained model loading. Fixes https://github.com/huggingface/accelerate/issues/1948 and https://github.com/huggingface/accelerate/issues/2031 by making the ram efficient loading optional.
2. This PR should be merged after PR https://github.com/huggingface/accelerate/pull/2037 is merged.

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks! LG2M after the related PR is merged :)

**Review by ArthurZucker — COMMENTED** [review]
Waiting for the other pr to be merged to approve!

**Comment by pacman100** [comment]
That PR is merged @ArthurZucker, Thank you!

**Review by ArthurZucker — APPROVED** [review]
Thanks

**Pull request merged**
