### PR TITLE
Proposal: saner num_labels in configs.

### PR DESCRIPTION
**Pull request by julien-c**
See https://github.com/guillaume-be/rust-bert/pull/21 for more context

### CODE REVIEW

**Comment by LysandreJik** [comment]
I like this better as well. Probably won't be backwards compatible with users that have their config with `_num_labels` though.

**Comment by patrickvonplaten** [comment]
Like it better as well! Agree with @LysandreJik that some configs might need to be fixed manually

**Review by patrickvonplaten — APPROVED** [review]

**Comment by julien-c** [comment]
Well, `_num_labels` (if present) should always be consistent with the length of `id2label`, no?

**Comment by LysandreJik** [comment]
You're right, it should!

**Review by LysandreJik — APPROVED** [review]

**Comment by julien-c** [comment]
All right, merging this. @patrickvonplaten if you want to re-run your cleaning script at some point feel free to do it :) (let me know before)

**Pull request merged**
