### PR TITLE
Vit deit fixes

### PR DESCRIPTION
**Pull request by NielsRogge**
# What does this PR do?

* Some small documentation improvements of ViT + DeiT.
* Adds a cats image to the `fixtures/test_samples` folder, which is used in the integration tests of both ViT and DeiT. 
* Adds a community notebook, illustrating how to fine-tune the Vision Transformer on CIFAR-10.

(there's something weird going on with the .gitignore within the test_samples folder , see files changed).

### CODE REVIEW

**Review by patil-suraj — APPROVED** [review]
LGTM, thanks for fixing this!

Not sure whats happening with `gitignore` maybe @LysandreJik  knows :)

**Comment by patil-suraj** [comment]
The notebook looks amazing!

Out of curiosity, is not possible to use `Trainer` to fine-tune `ViT`?

**Comment by NielsRogge** [comment]
Added a notebook that uses the Trainer. Includes a nice confusion matrix at the end :)

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Pull request merged**
