### PR TITLE
Add argument "cache_dir" for transformers.onnx

### PR DESCRIPTION
**Pull request by happyXia**
# What does this PR do?

Add argument "cache_dir" for transformer.onnx ,to enables the user to select the cache path when exporting large ONNX model. Because the default cache directory may run out of space.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Review by lewtun — APPROVED** [review]
Thank you for this improvement @happyXia - LGTM too 🚀 !

**Comment by lewtun** [comment]
Looking at the CI, it seems you need to format your files @happyXia - can you please run:

```
make style && make quality
```

and commit / push the formatted files?

**Comment by lewtun** [comment]
I checked that the slow tests pass with

```
RUN_SLOW=1 python -m pytest -x tests/onnx/test_onnx_v2.py
```

so this all looks good to me - merging now. Thank you @happyXia 🚀 !

**Pull request merged**
