### PR TITLE
Return tokens from tokenizer.__call__()

### PR DESCRIPTION
**Pull request by jarednielsen**
Currently, pre-tokenizing (not encode tokens to ids, just generating the tokens) a batch of strings requires a manual for-loop. I'm adding a method to call the underlying Rust batch_encode implementation, which runs about 2x faster than a Python for-loop. I was expecting an even greater speedup, so if there's any way this could be made more efficient I would love to hear it.

Before:
```python
batch = ["Sentence 1", "Sentence 2"]
tokenized_batch = [tokenizer.tokenize(ex) for ex in batch]
# [["Sen", "##tence", "1"], ["Sen", "##tence", "2"]
```

Now:
```python
tokenized_batch = tokenizer.tokenize_batch(batch)
# [["Sen", "##tence", "1"], ["Sen", "##tence", "2"]
```

### CODE REVIEW

**Comment by thomwolf** [comment]
Hi Jared,

We are currently trying to reduce the number of user-facing methods in the tokenizer so I would be in favor of extending `tokenize` to accept batches as well. This can be done by having `tokenize` call `__call__` which accept both single examples and batches and extracting the tokens from the results.

It's already what happening in `encode` if you dive in the code (`encode` is calling the full tokenization pipeline in `encode_plus` and filtering the output to keep only the tokens).

**Comment by jarednielsen** [comment]
Thanks for explaining your thinking! What about adding a `return_tokens` argument to `tokenizer.__call__`? `encoding.tokens` is the only attribute in an `Encoding` that can't be accessed directly from that method.

**Comment by thomwolf** [comment]
Oh yes, actually you can already do `.tokens(index_in_the_batch)` on the output of `__call__` but I see this was missed and is not in the doc, we will add it (and the similar method `.words(index_in_the_batch)`).

It's here in the `BatchEncoding` class (which is the output of the encoding methods): https://github.com/huggingface/transformers/blob/master/src/transformers/tokenization_utils_base.py#L221

So you can do:
```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')
batch = ['hello how are you?', 'good morning everyone']
encodings = tokenizer(batch)
>>> encodings.tokens(1)
['[CLS]', 'good', 'morning', 'everyone', '[SEP]']
>>> encodings.tokens(0)
['[CLS]', 'hello', 'how', 'are', 'you', '?', '[SEP]']
```

Is it what you were looking for?

**Comment by jarednielsen** [comment]
Somewhat. I still have to do `[encodings.tokens(i) for i in range(len(encodings))]`, but that's fine. I also got direct access to the underlying Rust tokenizer via `tokenizer._tokenizer.encode_batch(batch["sentences"])`, so that will do. Thanks!

**Pull request closed without merging**
