### PR TITLE
[`chore`] Update warning text, a word was missing

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

# What does this PR do?

* Updates a warning text: "lead" was missing.

I missed this in the original PR, apologies.

## Before submitting
- [x] This PR fixes a typo or improves the docs

## Who can review?

@ArthurZucker

cc: @stas00 Thanks for pointing this out here: https://github.com/huggingface/transformers/pull/26681#discussion_r1425760204

- Tom Aarsen

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
thanks

**Comment by tomaarsen** [comment]
@amyeroberts This should be a simple merge; but I'd like to leave it to a core maintainer as I'm not 100% sure whether non-core maintainers should be merging on `transformers`.

**Comment by ArthurZucker** [comment]
We usually let HF people merge their own PRs 😉 Merging

**Comment by tomaarsen** [comment]
Good to know!

Rebased & force pushed :)

**Pull request merged**
