### PR TITLE
Region error

### PR DESCRIPTION
**Pull request by Aniketsingh12**
Endregion was not causing error as region was not recognizing.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
The right fix would be to properly open that region, cc @Rocketknight1

**Comment by Aniketsingh12** [comment]
Thanks for suggestion

**Comment by Rocketknight1** [comment]
Yes, if you could replace `# Metrics` with `# region Metrics` instead that would be great!

Alternatively I could just ditch all of these region tags, since I think I'm the only person who likes them.

**Comment by Aniketsingh12** [comment]
@Rocketknight1 It will be done

**Comment by Aniketsingh12** [comment]
@Rocketknight1 I will definitely replace all the metrics with region metrics but any reasons of doing that ?? I am a Beginner so just wanted to understand .

**Comment by Rocketknight1** [comment]
@Aniketsingh12 Using region tags allows IDEs like PyCharm and VS Code ([with an addon](https://marketplace.visualstudio.com/items?itemName=maptz.regionfolder)) to fold the areas of code inside the `# region` and `# endregion`, which can make the code easier to read in a long script. They don't serve any function other than that!

**Pull request closed without merging**
