### PR TITLE
Fix `use_parallel_residual` and `qkv_bias` for StableLM GGUF config extraction

### LINKED ISSUE #34426: Stablelm-2-1_6b-chat config extracted from GGUF file differs from source model config
### System Info

- `transformers` version: 4.46.0
- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.24.7
- Safetensors version: 0.4.5
- Accelerate version: 0.34.2
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.5.0+cu121 (False)
- Tensorflow version (GPU?): 2.17.0 (False)
- Flax version (CPU?/GPU?/TPU?): 0.8.5 (cpu)
- Jax version: 0.4.33
- JaxLib version: 0.4.33
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@SunMarc 
Also cc @VladOS95-cyber since you added GGUF support for StableLM :)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoConfig

config_hf = AutoConfig.from_pretrained("stabilityai/stablelm-2-1_6b-chat")
config_gguf = AutoConfig.from_pretrained("Crataco/stablelm-2-1_6b-chat-imatrix-GGUF", gguf_file="stablelm-2-1_6b-chat.IQ4_XS.imx.gguf")
print(config_hf)
print(config_gguf)
```

**Outputs**
```text
StableLmConfig {
  ...
  "use_qkv_bias": true,
  "vocab_size": 100352
}

StableLmConfig {
  ...
  "use_qkv_bias": false,
  "vocab_size": 100352
}
```

### Expected behavior

The `stabilityai/stablelm-2-1_6b-chat"` model has `use_qkv_bias=True`. However, the config extracted from `stablelm-2-1_6b-chat` GGUF file has `use_qkv_bias=False`, causing model failed to initialize with qkv_proj bias.

### PR DESCRIPTION
**Pull request by Isotr0py**
# What does this PR do?

Fixes #34426 (issue)
- #34426

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@VladOS95-cyber @SunMarc

### CODE REVIEW

**Review by SunMarc — APPROVED** [review]
Thanks for fixing this @Isotr0py !

**Comment by VladOS95-cyber** [comment]
Hey @Isotr0py! These changes are good to me. Thank you! Please, fix test_stablelm_weights_conversion_fp16 and test_stablelm_fp16 in test_ggml.py as well to get rid of config=original_model.config as we do not need it anymore

**Review by VladOS95-cyber — APPROVED** [review]

**Review by LysandreJik — APPROVED** [review]
Thank you!

**Comment by SunMarc** [comment]
Can you try to rebase your PR in order to pass the CI @Isotr0py ?

**Comment by Isotr0py** [comment]
@SunMarc I have merged the main branch but seems that the test CI is still failing in unrelated tests:
https://app.circleci.com/pipelines/github/huggingface/transformers/110104/workflows/8e77c517-3ae4-4cad-ac75-c4ba5616e9d6/jobs/1464043/tests

**Comment by VladOS95-cyber** [comment]
> @SunMarc I have merged the main branch but seems that the test CI is still failing in unrelated tests: https://app.circleci.com/pipelines/github/huggingface/transformers/110104/workflows/8e77c517-3ae4-4cad-ac75-c4ba5616e9d6/jobs/1464043/tests

Hey, try to do rebase. First of all, in command line, `git fetch upstream`
`git rebase upstream/main` and then `git push -u origin a-descriptive-name-for-my-changes --force`

**Comment by SunMarc** [comment]
The problematic test should have been fixed by https://github.com/huggingface/transformers/pull/34605. Can you try to rebase on that ?

**Comment by Isotr0py** [comment]
@SunMarc All tests passed now!

**Comment by SunMarc** [comment]
Niceee !

**Pull request merged**
