### PR TITLE
Tentative workflow improvement

### PR DESCRIPTION
**Pull request by LysandreJik**
This improves the workflow of the doc-builder bot by adding a single comment when the PR is opened.

When the PR is closed or merged, it edits that comment. If the PR is reopened, it re-edits that comment.

### CODE REVIEW

**Comment by LysandreJik** [comment]
See the edits of the comment above.

**Review by sgugger — APPROVED** [review]
LGTM, thanks for working on this!

**Review by stas00 — APPROVED** [review]
That's definitely a better UX. Thank you for improving it, @LysandreJik 

As I shared on slack, here are other possible solutions for once the PR has been merged if any resonate with you:

1. update the doc link in the comment to point to the master docs - why waste the comment
2. delete the comment (but it may appear odd to the user that some comments get deleted all the time)
3. hide the comment, which is more transparent and I found you can use https://docs.github.com/en/graphql/reference/mutations#minimizecomment or https://github.com/int128/hide-comment-action to do that.

I think your currently proposed solution + hide/delete of that comment or the solution (1) on the list above will offer the best UX, IMHO.

**Comment by LysandreJik** [comment]
I'm ok with both solutions 1 and 3 - I agree that it might be odd for the comment to be deleted, and hiding the comment removes that peculiarity.

If it's ok with you, I'll merge this PR as it is, as it is already an improvement of the workflow. I'm very open to any PR you offer regarding 1 or 3.

**Comment by ydshieh** [comment]
off topic - but today when I checked the link, I always get 
```
404

Sorry, we can’t find the page you are looking for.
```

Yesterday, I saw it worked. (Maybe @LysandreJik you are already aware of this fact?)

**Comment by LysandreJik** [comment]
Hey @ydshieh, I believe these are due to errors on our backend; we're currently setting up a system that would make for a better way to share that info with the contributors. In the meantime, please do not hesitate to ping us on the PRs themselves with the commit that failed to be deployed. Thank you!

**Pull request merged**
