### PR TITLE
Fix bnb training test failure

### PR DESCRIPTION
**Pull request by matthewdouglas**
# What does this PR do?

Fixes a test failure that resulted from the introduction of `OPTSdpaAttention` as the default implementation in #33298. Discussed internally on Slack.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@BenjaminBossan @SunMarc

### CODE REVIEW

**Review by BenjaminBossan — APPROVED** [review]
Thanks for identifying the issue and providing a fix. I tested the change locally and the tests now pass for me.

**Comment by SunMarc** [comment]
I saw that the issue was with the `OPTSdpaAttention` but why it doesn't work with it ? Any ideas ? cc @matthewdouglas

**Comment by BenjaminBossan** [comment]
The issue was that the old check `"OPTAttention" in repr(type(module))` didn't match any layer anymore, hence no LoRA layers were added, hence no trainable parameters were found, resulting in the error.

**Comment by SunMarc** [comment]
Oh, I read the PR too fast. Thanks ! It makes sense now

**Pull request merged**
