### PR TITLE
fix get past_length

### PR DESCRIPTION
**Pull request by jiqing-feng**
Hi @gante . Multi-query models like gpt_bigcode have a different kv-cache layout; use .shape[-2] can handle it.

### CODE REVIEW

**Comment by jiqing-feng** [comment]
Hi @gante . Have you been able to see it yet? I just found that this function is only used at the beginning of the generation, which means no pkv when calling it, so deleting it or just setting pkv=0 is also a choice. Would like to hear your opinion. Thx!

**Review by zucchini-nlp — COMMENTED** [review]
@jiqing-feng hey! Multi-query gpt-bigcode is indeed a special case and it has `_get_initial_cache_position` overriden [here](https://github.com/huggingface/transformers/blob/9ef93fccade1f2b6349c2eec2188d0ea54329f84/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L1215-L1231).

We need this part of code in case some users pass in past key values from prev generations to continue generating. The `shape[-2]` gets past seq length to get correct cache-position for all models, and special cases like bigcode (afaik bigcode is the only one) are overriden in modeling. Also, "cache_position" currently is not used in relatively older models, which includes GPTBigCode, so there should be no failures 😄

**Comment by jiqing-feng** [comment]
> @jiqing-feng hey! Multi-query gpt-bigcode is indeed a special case and it has `_get_initial_cache_position` overriden [here](https://github.com/huggingface/transformers/blob/9ef93fccade1f2b6349c2eec2188d0ea54329f84/src/transformers/models/gpt_bigcode/modeling_gpt_bigcode.py#L1215-L1231).
> 
> We need this part of code in case some users pass in past key values from prev generations to continue generating. The `shape[-2]` gets past seq length to get correct cache-position for all models, and special cases like bigcode (afaik bigcode is the only one) are overriden in modeling. Also, "cache_position" currently is not used in relatively older models, which includes GPTBigCode, so there should be no failures 😄

Do you mean `shape[2]` can handle all models? If so, I could close this PR, WDYT?

**Comment by zucchini-nlp** [comment]
@jiqing-feng yes, all cases should be handled by `shape[2]` and the PR can be closed

**Pull request closed without merging**
