### PR TITLE
:rotating_light: :rotating_light: :rotating_light: Fixing BPE spm converter.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

The spm BPE converter seemed to have been wrong (for quite a while if true).
The merges are recreated from the vocab, but where ordered by their vocab id instead
of the score within spm vocab. It seems to be wrong for Llama.

This PR fixes it.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Narsil** [comment]
@sgugger 

At least reformer and camembert are concerned (some test failed when writing bogus code here.)

**Review by ArthurZucker — COMMENTED** [review]
Looks good to me, as we saw offline! The biggest issue will be to fix the tests!

**Review by sgugger — APPROVED** [review]
Thanks for the fix! Please put three 🚨 in the PR title so that we know there is a breaking change we can highlight in the next release notes :-)

**Comment by Narsil** [comment]
IT's breaking and breaking reformer and xlnet, I removed the breaking part of it for Llama.

**Pull request closed without merging**
