### PR TITLE
Fix excessive CPU memory usage with FSDP and cpu_ram_efficient_loading

### LINKED ISSUE #31721: Model loading OOM when using FSDP + QLoRA
### System Info

**Base line**. For single instance of p4de.24xlarge (640GB GPU, 1000 GB CPU), i am able to use Q(4-bit)LoRA to train a large model wit size close to 300B. `Device_map` is set as `auto` with code as below.

```
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    attn_implementation="flash_attention_2",
    torch_dtype=torch.bfloat16,
    quantization_config=bnb_config
)
```

However, when I use FSDP + QLoRA with 2 p4de.24xlarge instances. Model loading went OOM on CPU. 

* The script is based on this [blog](https://www.philschmid.de/sagemaker-train-deploy-llama3) and [run_fsdp_qlora.py](https://github.com/philschmid/llm-sagemaker-sample/blob/main/scripts/fsdp/run_fsdp_qlora.py).  
 

Can anyone please share some insights? Looking at the `from_pretained` method's code [here](https://github.com/huggingface/transformers/blob/dd4654eab7593be34294dc16279f52e4efa8869e/src/transformers/modeling_utils.py#L4217-L4232) and [here](https://github.com/huggingface/transformers/blob/dd4654eab7593be34294dc16279f52e4efa8869e/src/transformers/modeling_utils.py#L890). Can I get clarification on the following questions? Many thanks.

1. For FSDP + QLoRA, during model loading, Please comment if my understanding is correct.
* If model is quantized, then the model is loaded on GPU and further casted into CPU, because of `is_quantized` in this [line](https://github.com/huggingface/transformers/blob/dd4654eab7593be34294dc16279f52e4efa8869e/src/transformers/modeling_utils.py#L4210)) and [this comment](https://github.com/huggingface/transformers/blob/dd4654eab7593be34294dc16279f52e4efa8869e/src/transformers/modeling_utils.py#L890). 
* If model is not quantized, then the model is directly loaded into CPU.

2. The OOM happens on CPU as I didn't see any error of "not enough CUDA memory". Thus, for the model that is quantized, when you cast the model into CPU, is only rank 0 doing the job or each of all ranks is casting into CPU leading CPU memory exploding? Same comment for the model that is not quantized during loading. 

3. For quantized model, if you load it firstly into GPU, are you using all GPUs to load the model or using rank 0 to load it? 

### Who can help?

@SunMarc @ArthurZucker 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

[Distributed-finetuning.zip](https://github.com/user-attachments/files/16054015/Distributed-finetuning.zip)
Here is my code to reproduce the issue

### Expected behavior

error free

### PR DESCRIPTION
**Pull request by matthewdouglas**
# What does this PR do?

This PR fixes an issue with FSDP + CPU_RAM_EFFICIENT_LOADING where a copy of the parameters are loaded into CPU memory for each rank. The change offloads to CPU only for rank 0, and the rest on the meta device. On a typical 8x node this will dramatically decrease the system RAM overhead required to load a large model.

This is split from a previously reverted PR #32276 originally contributed by @winglian. The revert was due to issues we had with validating the change that have since been resolved.

The issue we encountered was specific to our cluster environment on AWS. With the [AWS EFI plugin for NCCL](https://github.com/aws/aws-ofi-nccl), we encountered consistent hangs. If we upgrade NCCL from the version bundled with PyTorch (2.20.5) to NCCL 2.22.3 via `pip install nvidia-nccl-cu12==2.22.3`, this issue is resolved. ([Internal discussion](https://huggingface.slack.com/archives/C043JTYE1MJ/p1724260357959149))

Fixes #31721, #31577

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@ArthurZucker @LysandreJik

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Ping me when this is ready for review!

**Comment by matthewdouglas** [comment]
@ArthurZucker Ready!

**Review by ArthurZucker — COMMENTED** [review]
Sorry as the changes are exactly the same as what we had in #32276, could you explain what was resolved on main that no longer fails?

**Comment by matthewdouglas** [comment]
@ArthurZucker I've added more background to the description.

> The issue we encountered was specific to our cluster environment on AWS. With the [AWS EFI plugin for NCCL](https://github.com/aws/aws-ofi-nccl), we encountered consistent hangs. If we upgrade NCCL from the version bundled with PyTorch (2.20.5) to NCCL 2.22.3 via pip install nvidia-nccl-cu12==2.22.3, this issue is resolved. ([Internal discussion](https://huggingface.slack.com/archives/C043JTYE1MJ/p1724260357959149))

**Review by ArthurZucker — APPROVED** [review]
Thanks a lot all for clarifying!

**Comment by fabianlim** [comment]
@ArthurZucker @matthewdouglas I tried this fix but im having similar NCCL issues as what you had. Unfortunately your suggestion to upgrade to latest is not working. I understand you have some internal debugging discussions on this topic. Is it possible to share NCCL env settings and other package versions, that might shed  light on the root cause?

**Pull request merged**
