### PR TITLE
Added Deberta model type support

### PR DESCRIPTION
**Pull request by FilipposVentirozos**
# What does this PR do?

Fixes in the token_classification example the support for Deberta. Since it was not included in an 'if' clause. Specifically, I added there since it's mentioned that Deberta needs the 'add_prefix_space' to be True and that 'if' clause covers this parameter. I tested it and it works well.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hey @FilipposVentirozos, have you tried running the script with DeBERTa? Does it run/train successfully?

**Comment by FilipposVentirozos** [comment]
Hello @LysandreJik  yes it runs as intended. That is Deberta version 1 (microsoft/deberta-base). The newer versions (i.e. v2, v3) still not supported cause of the need of the slow tokenisation instead, may look into it more later.

**Comment by FilipposVentirozos** [comment]
I tried again with `microsoft/deberta-v3-base` and it actually works. FYI, I tested it locally on my Mac and on my custom dataset and on Conll2003 that was for train, eval and predict. If you would like me to do any other experiment, please let me know.

**Comment by LysandreJik** [comment]
Ok let's merge it then! Thanks for your efforts

**Pull request merged**
