### PR TITLE
[WIP] enable BNB HFQuantizer on xpu

### PR DESCRIPTION
**Pull request by faaany**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
cc @Titus-von-Koeller and @SunMarc !

**Comment by SunMarc** [comment]
Thanks for the PR @faaany, I'll let Titus decide but I think it is better to have only one PR to test the multi-backend for bnb ! Since the changes here are very simple, it should be pretty easy to integrate it. Maybe in this PR ? https://github.com/huggingface/transformers/pull/31098#issuecomment-2267995701 cc @Titus-von-Koeller

**Comment by faaany** [comment]
Hi @SunMarc, @ArthurZucker , sure. If we merge the change into #31098 , I can close this one.

**Comment by Titus-von-Koeller** [comment]
> If we merge the change into https://github.com/huggingface/transformers/pull/31098, I can close this one.

Yes, @faaany that would be best! You could submit a PR to @jiqing-fengs PR to integrate these changes. Would that still be possible today, as I'm in the process of finalizing testing on these matters?

I sent an invite to your email to the #bitsandbytes-intel-collab channel to coordinate and discuss as we go along. Please join.

**Comment by Titus-von-Koeller** [comment]
Closing this in favor of a unified PR in #31098.

**Pull request closed without merging**
