### PR TITLE
Update git templates

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Update who to ping

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks a lot !

**Review by amyeroberts — APPROVED** [review]
😢

**Review by LysandreJik — APPROVED** [review]

**Comment by LysandreJik** [comment]
:wave:

**Comment by LysandreJik** [comment]
Hope we'll continue to see your contributions @younesbelkada ;- )

**Pull request merged**
