### PR TITLE
Fix the behavior of collecting 'num_input_tokens_seen'

### LINKED ISSUE #28791: Inappropriate reduce operation of "num_input_tokens_seen" is prone to get training stuck.
### System Info

Trivial

### Who can help?

@pacman100 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

See [src/transformers/trainer.py line 1870](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L1870)
`self.state.num_input_tokens_seen += self.accelerator.gather(inputs[main_input_name]).numel()`

The length of "inputs[main_input_name]" is not guaranteed to be the same when using ddp, which may make the training process hang. Besides, in a distributed setup, it costs a lot to gather the WHOLE input tensors on different workers. It is better to call .numel() first and then .gather().

Ref: [Stuck when using model.generate() and acclerator.gather() in the distributed setting](https://github.com/huggingface/accelerate/issues/1326#issuecomment-1513145864)

### Expected behavior

Fix:
input_device = inputs[main_input_name].device
self.state.num_input_tokens_seen += torch.sum(self.accelerator.gather(torch.tensor(inputs[main_input_name].numel(), device=input_device, dtype=torch.int64))).item()

### PR DESCRIPTION
**Pull request by youliangh**
# What does this PR do?

The length of "inputs[main_input_name]" is not guaranteed to be the same when using DDP, which may make the training process hang. Besides, in a distributed setup, it costs a lot to gather the WHOLE input tensors on different workers. It is better to call .numel() first and then .gather().

Fixes https://github.com/huggingface/transformers/issues/28791

The modified code has already passed the relevant test ``tests/trainer/test_trainer_distributed.py`` with additional argument 'include_num_input_tokens_seen'.

## Who can review?

@pacman100 
@muellerzr

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
Thanks! Overall this looks good to me, can you rebase from main to ensure that tests pass?

**Comment by YouliangHUANG** [comment]
Just got it rebased from the main. However something still went wrong in the test, and it seems irrevelant to my PR.
Could you help identify?
Much appreciate @muellerzr

**Review by ArthurZucker — APPROVED** [review]
LGTM, it's been three weeks the unrelated tests are fixed, sorry to ask you to rebase one more time!

**Comment by YouliangHUANG** [comment]
Done, and it has passed all the tests.
@muellerzr @ArthurZucker

**Comment by ArthurZucker** [comment]
thanks for this fix

**Pull request merged**
