### PR TITLE
Reproducible checkpoint for npu

### PR DESCRIPTION
**Pull request by ji-huazhong**
# What does this PR do?

Save npu's RNG states when saving a checkpoint and set after all the data skip phase when resuming training.
Links to https://github.com/huggingface/transformers/pull/11582

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @muellerzr

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for adding!

**Review by muellerzr — APPROVED** [review]
Thanks!

**Comment by statelesshz** [comment]
`check_repository_consistency` has been executing for over 10 hours and it hasn't ended yet.

**Comment by statelesshz** [comment]
@amyeroberts Good day, this PR is ready to be merged :-)

**Pull request merged**
