### PR TITLE
enable non-cuda awq model support without modify version

### PR DESCRIPTION
**Pull request by jiqing-feng**
The IPEX awq linear is inherited from GEMM awq linear, see [here](https://github.com/casper-hansen/AutoAWQ/blob/main/awq/modules/linear/gemm_ipex.py#L14). So it's safe to convert GEMM to IPEX when no Cuda is found. It will let users run AWQ model on a non-cuda device without modifying the quantization config to change the version.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @SunMarc @MekkCyber

**Review by MekkCyber — APPROVED** [review]

**Comment by MekkCyber** [comment]
Thanks for the PR @jiqing-feng LGTM 🔥 ! Can you update the branch please

**Review by SunMarc — APPROVED** [review]
SGTM !

**Comment by jiqing-feng** [comment]
Updated to the main branch. Now it's ready to merge. Thanks!

**Pull request merged**
