### PR TITLE
[CI] Better reports #2

### PR DESCRIPTION
**Pull request by stas00**
As discussed at https://github.com/huggingface/transformers/pull/8110 this PR:

* [x] - generates 3 types of failure reports - long, short and one-per-line
* [x] - fixes multiple test suite tasks in a single job to allow them all to run regardless of the outcome of the previous test suites (using `if: always()`
* [x] - adds a workaround for the cumbersome way github makes the artifacts available by printing the short failure report in its own tab, so getting to errors should be very easy now.

Once we perfect this hack to our liking, I intend to submit this to `pytest` and see if perhaps they would consider accepting it as a feature.

@sshleifer

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM, thanks stas!

**Comment by sshleifer** [comment]
Thanks!

**Comment by stas00** [comment]
OK, everything seems to be working well. Let me know if you have any comments/suggestions/recommendations.

See: https://github.com/huggingface/transformers/runs/1329578690?check_suite_focus=true

I will wait for https://github.com/huggingface/transformers/pull/8007 to be merged before spreading the love to the rest of the jobs, so that they won't need to deal with a lot of conflicts.

**Comment by stas00** [comment]
I also proposed this a `pytest` feature: https://github.com/pytest-dev/pytest/issues/7972 - probably others would benefit from it.

**Pull request merged**
