### PR TITLE
Adding links to pipelines parameters documentation

### PR DESCRIPTION
**Pull request by AndreaSottana**
# What does this PR do?

Improving documentation, adding links to text generation pipelines documentation with more complete list of available parameters based on suggestion in this issue https://github.com/huggingface/transformers/issues/19038#issuecomment-1259592359

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@Narsil or any other suitable reviewer

### CODE REVIEW

**Comment by Narsil** [comment]
Hi, in order to pass the checks you might want to run

```python
pip install transformers[dev]
make fixup
```

Which should fix the docs for you.

**Comment by AndreaSottana** [comment]
I get the following error when calling `make fixup`

```
fatal: Not a valid object name main
Traceback (most recent call last):
  File "/Users/projects/transformers/utils/get_modified_files.py", line 27, in <module>
    fork_point_sha = subprocess.check_output("git merge-base main HEAD".split()).decode("utf-8")
  File "/Users/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'merge-base', 'main', 'HEAD']' returned non-zero exit status 128.
No library .py files were modified
python utils/custom_init_isort.py
python utils/sort_auto_mappings.py
doc-builder style src/transformers docs/source --max_len 119 --path_to_docs docs/source
make: doc-builder: No such file or directory
make: *** [extra_style_checks] Error 1
```

**Comment by AndreaSottana** [comment]
> Hi, in order to pass the checks you might want to run
> 
> ```python
> pip install transformers[dev]
> make fixup
> ```
> 
> Which should fix the docs for you.

Hi @Narsil it's done. Feel free to approve the PR if you're happy, thanks

**Comment by Narsil** [comment]
@sgugger any idea why the tests are not passing ?

**Comment by sgugger** [comment]
It seems there is an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

**Comment by AndreaSottana** [comment]
> It seems there is an issue with your CircleCI permissions, the tests won't run.
> Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

I'm unable to follow the guidance as when I click on the last link
`5.` Refresh permissions at https://app.circleci.com/settings/user

I get the following message

> **Something Unexpected Happened**
> This is certainly annoying, our apologies. Maybe a refresh would help. If that doesn't work, you may not have permissions to view this page or you may have the incorrect URL.

Can these checks be run on your end somehow or must they be run from my GitHub account?

**Comment by AndreaSottana** [comment]
@sgugger 
You can see the error I get here https://app.circleci.com/pipelines/github/AndreaSottana/transformers/4/workflows/49a7c689-e6b8-430b-b324-32968f9a0962/jobs/42 

```
#!/bin/bash -eo pipefail
python utils/tests_fetcher.py | tee tests_fetched_summary.txt

Traceback (most recent call last):
  File "utils/tests_fetcher.py", line 689, in <module>
    if not diff_with_last_commit and not repo.head.is_detached and repo.head.ref == repo.refs.main:
  File "/home/circleci/.pyenv/versions/3.7.12/lib/python3.7/site-packages/git/util.py", line 1083, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'main'

Exited with code exit status 1

CircleCI received exit code 1
```

I have no idea where this comes from as my PR only edited some documentation. This whole process doesn't really make life easier for those who just want to make quick contributions to the repository

**Review by sgugger — APPROVED** [review]

**Comment by sgugger** [comment]
I have never seen that error before, will report this to CircleCI to see if they have a better idea of what went wrong. In any case, the tests are not needed here, the quality checks are the ones I wanted to make sure were passing before merging.
Just waiting for the doc build job and will merge after!

**Pull request merged**
