### PR TITLE
Fix cvt docstrings

### PR DESCRIPTION
**Pull request by AnugunjNaman**
# What does this PR do?

This PR does the following:
1. Remove the error in `README.md` where `CvT` description was copy of `CTRL`
2. Fix `size` of image for `feature extractor` which was set to `224`.
3. fix the input docstring for forward classes of `CvtModel` and `CvtForImageClassification` (head mask etc not needed).

@NielsRogge

### CODE REVIEW

**Review by NielsRogge — APPROVED** [review]
LGTM

**Review by LysandreJik — APPROVED** [review]
Yes, LGTM!

**Comment by LysandreJik** [comment]
Will merge as soon as it's green!

**Comment by AnugunjNaman** [comment]
@LysandreJik @NielsRogge You can merge it. Thanks for review!

**Pull request merged**
