### PR TITLE
[CI] Add CircleCI workflow to build docs for preview

### PR DESCRIPTION
**Pull request by harupy**
This PR adds a CircleCI workflow to build the documentation and store it as an artifact so that we can preview it and verify it's rendered properly.

### CODE REVIEW

**Comment by harupy** [comment]
The built documentation:

https://30100-155220641-gh.circle-artifacts.com/0/docs/_build/html/index.html

**Comment by harupy** [comment]
How to view the built documentation:

doc

**Review by sshleifer — COMMENTED** [review]
Very cool! Are we worried about wasting lots of disk? When do artifacts get deleted?

**Comment by sshleifer** [comment]
@LysandreJik this might interest you!

**Comment by harupy** [comment]
@sshleifer Thanks for the comment!

[The CircleCI doc](https://circleci.com/docs/2.0/artifacts/) says:

> Artifacts are stored on Amazon S3 and are protected with your CircleCI account for private projects. There is a 3GB curl file size limit. **Artifacts will be accessible for thirty days after creation**.

**Review by sshleifer — APPROVED** [review]
LGTM, @julien-c @LysandreJik

**Review by LysandreJik — APPROVED** [review]
This is very nice!

**Pull request merged**
