### PR TITLE
fix bug: avoid divide by zero in _maybe_log_save_evaluate()

### PR DESCRIPTION
**Pull request by frankenliu**
set logging_strategy="steps" and logging_steps=10,  
when that one epoch have 100 steps, the should_log will be set to True in last step.
And self._globalstep_last_logged will be assign to self.state.global_step in _maybe_log_save_evaluate() method by line 1917 in trainer.py.
the line 1933 in trainer.py , self.callback_handler.on_epoch_end() will keep the should_log=True, then in line 1934 run _maybe_log_save_evaluate() method  (self.state.global_step - self._globalstep_last_logged) will be zero in line 2247.

@muellerzr @pacman100

### CODE REVIEW

**Review by pacman100 — COMMENTED** [review]
Hello, thank you for the PR, but I think better solution would be to the following check in `_maybe_log_save_evaluate`:

```
if self.control.should_log and self.state.global_step>self._globalstep_last_logged:
```

**Comment by frankenliu** [comment]
> Hello, thank you for the PR, but I think better solution would be to the following check in `_maybe_log_save_evaluate`:
> 
> ```
> if self.control.should_log and self.state.global_step>self._globalstep_last_logged:
> ```

Yes, your solution are better. I just think to avoid in _inner_training_loop() when training.

**Comment by muellerzr** [comment]
@frankenliu can you either try and fix the addition of all the commits (after rebasing I don't think you did a force push) or open a new clean PR? It's hard to read just what's changed with now 30+ files modified. Thanks!

**Comment by frankenliu** [comment]
> @frankenliu can you either try and fix the addition of all the commits (after rebasing I don't think you did a force push) or open a new clean PR? It's hard to read just what's changed with now 30+ files modified. Thanks!

OK，i will open a new clean PR.

**Pull request closed without merging**
