### PR TITLE
fix(tokenization): `encode` should remove leading batch axis for all types of single batch to keep consistent.

### LINKED ISSUE #28635: Tokenizer `encode/decode` methods are inconsistent, TypeError: argument 'ids': 'list' object cannot be interpreted as an integer
### System Info

- `transformers` version: 4.35.2
- Platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35
- Python version: 3.11.6
- Huggingface_hub version: 0.20.2
- Safetensors version: 0.4.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Run the following code:
```python
from transformers import AutoTokenizer

text = "test"
tokenizer = AutoTokenizer.from_pretrained("gpt2")
encoded = tokenizer.encode(text, return_tensors='pt')
result_text = tokenizer.decode(encoded, skip_special_tokens=True)
print(text)
```

Will raise exception:
```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    tokenizer.decode(encoded, skip_special_tokens=True)
  File "/home/scruel/mambaforge/envs/vae/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 3748, in decode
    return self._decode(
           ^^^^^^^^^^^^^
  File "/home/scruel/mambaforge/envs/vae/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 625, in _decode
    text = self._tokenizer.decode(token_ids, skip_special_tokens=skip_special_tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'ids': 'list' object cannot be interpreted as an integer
```

### Expected behavior

Should be able to print the original text `"test"`, rather than raise an exception(`TypeError`).

### LINKED ISSUE #28935: Add support for prefix_allowed_tokens_fn to maintain a state throughout decoding
### Feature request

Add an optional argument in `prefix_allow_tokens_fn` to allow for state to maintained throughout decoding or add a stateful alternative to `prefix_allowed_tokens_fn`.

### Motivation

`prefix_allowed_tokens_fn` is great but has one major downfall which is that you cannot maintain a state throughout decoding. This is inefficient because at each step you must go through your past `inputIds`, build up your current "state", and then figure out which tokens are allowed to appear next.

Instead, there should be a class we can subclass that gets passed the next token ID at each step of decoding (`Constraint` does not achieve this as `update` does not get every token ID). For example if you are trying to create a function to output json format (https://gist.github.com/BorisTheBrave/969f303a082c9da1916d04ee1eb04452), then you could track where you currently on in the json as each token ID is being received instead of going through everything on each new token.

### Your contribution

Unfortunately can't make a PR.

### PR DESCRIPTION
**Pull request by scruel**
# What does this PR do?
`encode` should remove leading batch axis for all types to keep consistent with `decode` method.

Fixes #28635

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@ArthurZucker

### CODE REVIEW

**Comment by scruel** [comment]
Hi @ArthurZucker, as we discussed in #28935, instead of let `encode` directly support multiple batches, this PR is main to fix the error of existing behaviour for a single batch. Let's call this as the first step for achieving your plan.

**Comment by scruel** [comment]
I may willhave few questions for the next step of your plan to deprecate some of the APIs to let `decode` supports both single and batch processing, along with some questions about your code style, which place should I post them to ask? Or may I reach you team in your public discord server? Thanks.

**Comment by ArthurZucker** [comment]
We can keep the discussion on the related issue 🤗

**Comment by scruel** [comment]
Ok, this PR won't solve the issue it self and have some errors, so I closed it, will create another after I done.

**Pull request closed without merging**
