### PR TITLE
Resolve DeepSpeed cannot resume training with PeftModel

### PR DESCRIPTION
**Pull request by lh0x00**
Hi all,

I found an issue about resume ft **PeftModel** with **DeepSpeed** while I using `accelerate launch` to follow [zephyr-7b-beta recipes](https://github.com/huggingface/alignment-handbook/tree/c74ed111710d57f563cfbf1806cfb8f07dd3dc67/recipes/zephyr-7b-beta) with **qlora**. 
In details, the process will be crashing on load resume checkpoint with **DeepSpeed** with **PeftModel**. I referred to https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/559#issuecomment-1585948697 and created a PR to resolve this issue. I was updated and it works accurately on my fork.

Thanks for review @pacman100 @muellerzr

### CODE REVIEW

**Comment by lh0x00** [comment]
hiii, any feedback are welcome, I waiting to a new version to use instead of a fork version or give me feedback if my pr having any issues. many thanks @pacman100 @muellerzr

**Comment by nathan-az** [comment]
Nice! Assuming this works, really excited for it to get merged in, as I've had this issue with checkpoints.

Quick one - it looks like your local formatter may have different line length settings to the default for `transformers`, since the diff shows a bunch of changes that aren't relevant to your updates. Up to you if you want to revert those, but I'd hate for them to hold up the PR :)

**Comment by amyeroberts** [comment]
cc @younesbelkada

**Comment by lh0x00** [comment]
yeah, @nathan-az  I was able to continue my fine tuning, and it worked well. You can use it through my branch while waiting for the PR to be merged.

**Review by younesbelkada — APPROVED** [review]
In principle this looks good to me ! Thanks a lot ! I would love to have a second look from @pacman100 on the DeepSpeed end to make sure all is good

**Comment by manishiitg** [comment]
waiting for this merge

**Comment by lh0x00** [comment]
me too, waiting for this merge -.-

**Comment by younesbelkada** [comment]
Hi everyone! Sure yes, please give us some time to review properly this PR and we'll make sure the fix is going to be landed!

**Review by pacman100 — APPROVED** [review]
Thank you @lh0x00, the changes make sense, thank you for the fixes!

**Comment by lh0x00** [comment]
thanks for reviewed, @pacman100 @younesbelkada

**Review by ArthurZucker — APPROVED** [review]
Thanks for the fix! 🔥

**Pull request merged**
