### PR TITLE
Deprecate models script - correctly set the model name for the doc file

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

There was a bug in #30184, in initial model name e.g. `model_name` was returned as the found model doc name, instead of the one which relates to the found path. 

This means, if the model name has a different hyphenation, it's config cannot be found, and therefore it is not deprecated. 

This fixes the issue for certain models e.g. `gptsan_japanese`.

### CODE REVIEW

**Comment by amyeroberts** [comment]
@ydshieh There was actually one remaining bug! I didn't catch because when I tested I wasn't using models with hyphens in the name.

**Review by ydshieh — APPROVED** [review]
OK for me, thanks.

I am not sure if we have a correspondence of `model_name` to `model_doc_path`.
If no such correspondence exist, the current `zip` won't be enough (which gives 3 items), and a product (which gives the 9 combinations ...) would be required.

Anyway, I might overthinking and I am not really requiring a change in this PR.

**Comment by amyeroberts** [comment]
> I am not sure if we have a correspondence of model_name to model_doc_path.

@ydshieh Ah, yes, it's a bit unclear from this diff. The model name returned here is set to [model_doc_name here](https://github.com/huggingface/transformers/blob/bdfefbadaf7553d8a104dce096fd2905692f8197/utils/deprecate_models.py#L99). So the correspondence should work, because the mapping is just between the name used and the doc path.

**Comment by ydshieh** [comment]
@amyeroberts 

right, thanks!

**Pull request merged**
