### PR TITLE
[FLAX] Add dtype to embedding for gpt2 model

### PR DESCRIPTION
**Pull request by merrymercy**
# What does this PR do?

Add dtype to embedding for gpt2 models.  This dtype is necessary for mixed precision training.

## Who can review?
@patrickvonplaten, @LysandreJik

### CODE REVIEW

**Comment by sanchit-gandhi** [comment]
Thanks @merrymercy, I've noticed that we omit the `dtype` arg from all Flax `nn.Embed` modules! @patil-suraj is there a reason why we do this?

BART:
https://github.com/huggingface/transformers/blob/ab2006e3d6db88654526a4169e65d4bfc52da2e3/src/transformers/models/bart/modeling_flax_bart.py#L841-L845
BERT:
https://github.com/huggingface/transformers/blob/ab2006e3d6db88654526a4169e65d4bfc52da2e3/src/transformers/models/bert/modeling_flax_bert.py#L186-L200
T5:
https://github.com/huggingface/transformers/blob/ab2006e3d6db88654526a4169e65d4bfc52da2e3/src/transformers/models/t5/modeling_flax_t5.py#L1259-L1263

**Comment by merrymercy** [comment]
I don't know the reasons, but this dtype is required for half-precision training. I can modify all other classes as well if needed.

**Comment by sanchit-gandhi** [comment]
Let's wait for @patil-suraj to weigh in on this!

**Comment by merrymercy** [comment]
Gentle ping @patil-suraj

**Comment by patrickvonplaten** [comment]
@sanchit-gandhi could you maybe take a look here?

**Comment by sanchit-gandhi** [comment]
Sorry @patrickvonplaten - as mentioned in my previous comment https://github.com/huggingface/transformers/pull/18462#issuecomment-1209435023 I'm not sure why we omit the `dtype` from all Flax `nn.Embed` modules, hence the request for @patil-suraj to weight in! Maybe you could shed some light on this? It seems like intrinsic design philosophy given that we do this for all models.

**Comment by patrickvonplaten** [comment]
The change looks good to me. T5x also puts the embedding in half precision if necessary: https://github.com/google-research/t5x/blob/1f8cec78b1f28f1955d70741792d7b6e7dd76226/t5x/examples/t5/network.py#L287

@patil-suraj what do you think?

**Comment by merrymercy** [comment]
Can we merge this?

**Comment by sanchit-gandhi** [comment]
It's interesting that we omit the `dtype` arg in the embedding layer for both PyTorch and Flax:
https://github.com/huggingface/transformers/blob/cbb8a37929c3860210f95c9ec99b8b84b8cf57a1/src/transformers/models/gpt2/modeling_gpt2.py#L675-L676

Wondering if this was a deliberate design decision that we're violating in this PR? Otherwise am happy with the change for half-precision training!

**Review by patrickvonplaten — COMMENTED** [review]
Having talked to @patil-suraj offline, I don't think we should merge this because embeddings should **not** be casted to low-precision dtypes. 

When taking a look into T5x: https://github.com/google-research/t5x/blob/ca3d2e43c8db2e6769073ffa98b7689443e3b2b8/t5x/examples/t5/layers.py#L479 

You can see that they always force `dtype` to be `float32` . Only the computation of the `nn.Embedding` is done in self.dtype further below.

So @patil-suraj  and I are **not** in favor of merging this PR

**Comment by sanchit-gandhi** [comment]
Your conclusion aligns with the previous observations of embedding dtypes never being down-cast in any Transformer models, both for PyTorch and Flax!

Wondering if you could share the rationale behind _why_ one must not down-cast embedding weights to half-precision? This would be helpful in understanding why this should be avoided and help educate us all!

**Comment by merrymercy** [comment]
I think my modification does not conflict with t5x.
My modification changes the dtype of computation and output tensor, not the parameter type.

The code @patrickvonplaten refers is for parameter type not the computation/output type.
In t5x, they use fp16 for computation/output as well https://github.com/google-research/t5x/blob/ca3d2e43c8db2e6769073ffa98b7689443e3b2b8/t5x/examples/t5/layers.py#L497-L499

**Comment by patrickvonplaten** [comment]
Hey @merrymercy,

I think `nn.Embed` is an exception in Flax where providing a `dtype` does exactly modify the embedding weights and not just the computation. @patil-suraj can maybe explain better here :-)

**Comment by merrymercy** [comment]
By looking at the code, I don't know why `dtype` changes the type of parameters. You can check the code
https://github.com/google/flax/blob/0be6f32582b9acafe1741e8641a748eb99501021/flax/linen/linear.py#L739-L742. The type of parameters is controlled by `param_dtype`.

Could you explain how the "exception" happens?

**Comment by patrickvonplaten** [comment]
The way I see it, `dtype` promotes the whole embedding matrix to `bf16` here: https://flax.readthedocs.io/en/latest/_modules/flax/linen/linear.html#Embed and then takes a bf16 vector from this tensor -> this is different from just doing the matrix computation in bf16 IMO

**Comment by merrymercy** [comment]
You are right @patrickvonplaten. This is how fp16 mixed precision training with fp32 master weights works.

My point is, the current code is hugging face is wrong. The code in t5x is wrong. My modification makes hugging face’ code match t5x’ code.

Reasons:
1. Regard less of self.dtype. The weights is stored in fp32. This holds for both my PR and t5x.
2. If dtype is fp16, the computation is in fp16. This holds for my PR and t5x (https://github.com/google-research/t5x/blob/ca3d2e43c8db2e6769073ffa98b7689443e3b2b8/t5x/examples/t5/layers.py#L501). But the original hugging face code is wrong

**Comment by patrickvonplaten** [comment]
@merrymercy But T5X exactly doesn't set `dtype=jnp.bfloat16` when instantiating the layer, see: https://github.com/google-research/t5x/blob/ca3d2e43c8db2e6769073ffa98b7689443e3b2b8/t5x/examples/t5/layers.py#L479 but instead wraps the embedding in `dtype=jnp.bfloat16` only during the forward: https://github.com/google-research/t5x/blob/ca3d2e43c8db2e6769073ffa98b7689443e3b2b8/t5x/examples/t5/layers.py#L501 

Shouldn't we try to match this?

**Comment by merrymercy** [comment]
Aha! I think we are talking at different levels and my comment below can address your concerns 

The code you refers to is ‘nn.Embed’ in t5x, the equivalence of this in our code base is ‘flax.nn.Embed’. Both of them are implemented correctly.

In t5x, ‘nn.Embed’ has one argument dtype to control the type of computation and hard code fp32 for the type of parameters.
In flax, ‘nn.Embed’ has two arguments. One for dtype of computation and one for the dtype of parameter. I never change the ‘param_dtype’, so this makes flax’ embedding match t5x’s embedding.

In my PR, I didn’t modify the ‘nn.Embed’ at all. I modified the way we call ‘nn.Embed’. What my pr should match is this line in t5x.
https://github.com/google-research/t5x/blob/ca3d2e43c8db2e6769073ffa98b7689443e3b2b8/t5x/examples/t5/network.py#L287
You can see it passes dtype to ‘nn.Embed’

**Comment by patrickvonplaten** [comment]
Hey @merrymercy, thanks for clarifying and sorry for not making the connection before! The PR looks good to me then :-) 

Just one other thing - it seems there is an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

**Comment by merrymercy** [comment]
I fixed the circle CI issue, but I don't know how to fix the "Build PR Documentation" test

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
