### PR TITLE
Fix: unfinished_sequences with correct device 

### PR DESCRIPTION
**Pull request by Stxr**
The original code was causing errors when running torch.jit.trace due to the tensor options being incorrect. I fixed this by using torch.ones to create a tensor with the correct device and dtype. This should resolve the issue with running torch.jit.trace.

# What does this PR do?
This PR fixes a bug that causes errors when running torch.jit.trace in transformers.

## Before submitting
- [x] This PR fixes a bug.
- [x] I read the contributor guideline.
- [ ] This was discussed in issue # (insert issue number here).
- [ ] I updated the documentation.
- [ ] I wrote new tests.

## Who can review?

Please tag @ArthurZucker and @younesbelkada for text models review.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @gante

**Comment by Stxr** [comment]
The following code will reproduce the error:
```python
import torch
from transformers import AutoTokenizer, AutoModel
device = 'cuda' if torch.cuda.is_available() else 'cpu'

class Wrapper(torch.nn.Module):
    """
    Wrapper for the model to be traced
    """
    def __init__(self):
        super().__init__()
        self.model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).half().to(device)
        self.tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)

    def forward(self, input_ids):
        self.model.eval()
        input_ids = input_ids.to(device)
        gen_kwargs = {"max_length": 2048, "num_beams": 1, "do_sample": True, "top_p": 0.7,
                      "temperature": 0.95}
        outputs = self.model.generate(input_ids=input_ids, **gen_kwargs)
        return outputs[0, len(input_ids[0]) - 2:]

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True)
query = "hello"
input = tokenizer([query], return_tensors="pt", padding=True)
model = Wrapper()
torch.jit.trace(model, (input.input_ids,)).save("chatglm-6b.pt")
```

**Review by ArthurZucker — APPROVED** [review]
LGTM thanks for the catch 😉 We should probably add a test

**Review by gante — APPROVED** [review]
👍 Thank for the fix!

**Comment by gante** [comment]
Interestingly, I don't see `.new()` on pytorch's docs. Good thing we're removing it :D

**Review by amyeroberts — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
