### PR TITLE
Raise exceptions instead of asserts in src/transformers/models/bart/modeling_flax_[bart, marian, mbart, pegasus].py

### LINKED ISSUE #12789: Raise exceptions instead of using assertions for control flow
https://github.com/huggingface/transformers/blob/546dc24e0883e5e9f5eb06ec8060e3e6ccc5f6d7/src/transformers/models/gpt2/modeling_gpt2.py#L698

Assertions can't be relied upon for control flow because they can be disabled, as per the following:

```shell
$ python --help
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
...
-O     : remove assert and __debug__-dependent statements; add .opt-1 before
         .pyc extension; also PYTHONOPTIMIZE=x
...
```

From my understanding, this is why mypy has no qualms about using them to narrow types because you can turn them off at runtime and so they incur zero cost.

Would you be open to me changing these assertions to other appropriate exceptions as I encounter them?

### PR DESCRIPTION
**Pull request by killazz67**
# What does this PR do?

Fixes  #12789.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by patil-suraj — APPROVED** [review]
Thank you for the PR! Just left a small comment.

> I wanted to just change one file but the code quality check forced me to also update the other three files. So that's why I am changing multiple at once. I hope you don't mind.

This is expected. The quality checks ensure that copied modules always stay in sync. This also prevents to manually copy the changes to multiple similar modules.

**Comment by killazz67** [comment]
@patil-suraj I am confused , do you know why the ci fails to install the dependencies? I thought that it could be a temporary issue with the runner that's why I tried to rerun it, but it somehow is another issue.

**Comment by LysandreJik** [comment]
I have traced it back to the release of pip 21.3 today. I have pushed a hotfix on `master`, do you mind rebasing on the `master` branch to include the fix? Thank you!

**Review by LysandreJik — APPROVED** [review]
Great, thank you! I didn't find anything out other than that version being the culprit, unfortunately.

**Pull request merged**
