### PR TITLE
fix-qwen2vl-no-position_ids

### PR DESCRIPTION
**Pull request by simonJJJ**
# What does this PR do?

Fixes # [(issue)](https://github.com/QwenLM/Qwen2-VL/issues/105) [(issue)](https://github.com/QwenLM/Qwen2-VL/issues/112)

We encountered some issues with `position_ids==None` when fine-tuning the qwen2vl model, because the model_inputs do not pass the `position_ids` arg.

## Before submitting
- [] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Makes sense! Do you want to add a small test for training? 🤗

**Comment by zhangfaen** [comment]
I am trying to finetune Qwen2-VL for Object detection on coco dataset ( https://github.com/zhangfaen/finetune-Qwen2-VL  )

Without this PR, my finetuned model performance is bad.
With this PR, my finetuned model performance is really good.

Any progress for this PR to be merged?  

Thank you

**Comment by zytx121** [comment]
> I am trying to finetune Qwen2-VL for Object detection on coco dataset ( https://github.com/zhangfaen/finetune-Qwen2-VL )
> 
> Without this PR, my finetuned model performance is bad. With this PR (by cherry picking), my finetuned model performance is really good.
> 
> Any progress for this PR to be merged?
> 
> Thank you

@zhangfaen Strange, after I modified this code, the fine-tuning performance still did not improve. Is there anything else that needs to be modified?

**Comment by zhangfaen** [comment]
> > I am trying to finetune Qwen2-VL for Object detection on coco dataset ( https://github.com/zhangfaen/finetune-Qwen2-VL )
> > Without this PR, my finetuned model performance is bad. With this PR (by cherry picking), my finetuned model performance is really good.
> > Any progress for this PR to be merged?
> > Thank you
> 
> @zhangfaen Strange, after I modified this code, the fine-tuning performance still did not improve. Is there anything else that needs to be modified?

for what task and against what dataset are you finetuning qwen2-vl ?

**Comment by simonJJJ** [comment]
hi @ArthurZucker, would u mind taking a look at merging this PR? The community is waiting for it.

**Comment by zhangfaen** [comment]
> hi @ArthurZucker, would u mind taking a look at merging this PR? The community is waiting for it.

+1 @ArthurZucker

**Review by ArthurZucker — COMMENTED** [review]
Yep sorry I approved I don't know why it was lost in tracks!

**Comment by Betty-J** [comment]
> Yep sorry I approved I don't know why it was lost in tracks!

Hi there, when I used `pip install transformers`, I installed version 4.46.2, which still does not include the updates mentioned here https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen2_vl/modeling_qwen2_vl.py#L1723.

**Pull request merged**
