### PR TITLE
Feature: Add `MLFLOW_MAX_LOG_PARAMS` to `MLflowCallback`

### LINKED ISSUE #34276: Limit number of parametes logged with `MLflowCallback`
### Feature request

Add a new environment variable, such as `MLFLOW_MAX_LOG_PARAMS`, which can limit the number of parameters logged by the `MLflowCallback`.

### Motivation

When using mlflow in Azure ML, there is a limit of 200 parameters that can be logged in a single run, meaning that when attempting to run a training job, the callback needs to be disabled entirely, or the module needs to be "monkeypatched" to limit the number of params logged.

### Your contribution

I will submit a PR

### PR DESCRIPTION
**Pull request by cecheta**
# What does this PR do?

This PR adds `MLFLOW_MAX_LOG_PARAMS` environment variable, to allow the user to limit the number of parameters logged to MLflow.

Closes #34276 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

_Copying from #29032_

@muellerzr @pacman100 @noise-field @amyeroberts

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Thanks!

**Comment by LysandreJik** [comment]
Could you just run the code quality tool to ensure that the code quality passes? You can install them with the following, from the root of your clone:
```
pip install -e ".[quality]"
```
And then run them with:
```
make fixup
```

**Comment by cecheta** [comment]
> Could you just run the code quality tool to ensure that the code quality passes? You can install them with the following, from the root of your clone:
> 
> ```
> pip install -e ".[quality]"
> ```
> 
> And then run them with:
> 
> ```
> make fixup
> ```

@LysandreJik I've rebased my branch and run the tool, but it's still failing. However, I don't think it's related to my change

image

**Comment by LysandreJik** [comment]
Seems good! Thanks for your changes, merging

**Pull request merged**
