### PR TITLE
[Whisper] Fix slow test

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

This PR fixes a slow test for Whisper that doesn't work anymore because it's using a deprecated dataset. For this slow test to pass, we will need the CI to have access to a security token (cc @ydshieh)

### CODE REVIEW

**Comment by ydshieh** [comment]
ah, you are too fast. See this comment 

https://github.com/huggingface/transformers/pull/28400#discussion_r1445856908

in short: `mozilla-foundation/common_voice_11_0` doesn't require token if this works for you

**Comment by patrickvonplaten** [comment]
> mozilla-foundation/common_voice_11_0

The problem with CV 11.0 is that the expected results will change. 6_1 is exactly the dataset that was there before as well - is it that difficult. Don't we already have access to secret tokens? E.g. couldn't we just use `HUGGINGFACE_PUSH`?

**Comment by ydshieh** [comment]
I personally don't know if `HUGGINGFACE_PUSH` is the right token (is it a HF token or github token).

We have

```
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
```
Since we have such tokens, I think the infra team is fine with such tokens. We just need to talk to the infra team to make sure we are using the right one. And IMO, for read access, we should not use a push token (and better to have a read only token).

I will talk to the infra.

**Comment by ydshieh** [comment]
There is a new secret (token) added. I will update this PR accordingly and push

**Review by ydshieh — APPROVED** [review]
now it works

Feel free to ping a maintainer is you feel necessary

**Comment by ydshieh** [comment]
well, I have to add it to all workflow files 😅

**Comment by patrickvonplaten** [comment]
Thanks a lot @ydshieh!

**Comment by patrickvonplaten** [comment]
This PR should be good to merge!

**Review by amyeroberts — APPROVED** [review]
Thanks for updating!

**Pull request merged**
