### PR TITLE
Hashlib specification

### LINKED ISSUE #27034: Hashlib usage is underspecified
### Feature request

From python 3.9 hashlib introduced the `usedforsecurity` argument:
> Changed in version 3.9: All hashlib constructors take a keyword-only argument usedforsecurity with default value True. A false value allows the use of insecure and blocked hashing algorithms in restricted environments. False indicates that the hashing algorithm is not used in a security context, e.g. as a non-cryptographic one-way compression function.

`transformers` use hashing in many cases where the purpose is indeed _not for security_ purposes. This should be specifed in the code.

### Motivation

Transformers use MD5 from hashlib, which is not a secure algorithm, but are not specifying that it is for other purposes than security. This is causing issues for organisations following certain security standard. FIPS compliance could be an example. 

### Your contribution

I will attach a PR specifying the usage of hashlib algorithms. Since `usedforsecurity` is only specified from 3.9+ and transformers support 3.6+, I'll add a functionality to detect python version and change kwargs based on that.

### PR DESCRIPTION
**Pull request by DueViktor**
# What does this PR do?
The following PR address the issue raised in #27034.

Fixes # (issue)
Close #27034

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by DueViktor** [comment]
@ArthurZucker, perhaps you can review this?

**Comment by ArthurZucker** [comment]
Hey! As this might affect other HF repos we want to take our time and find a solution for all of them 🤗 gotta be aligned with other library maintainers!

**Comment by DueViktor** [comment]
> Hey! As this might affect other HF repos we want to take our time and find a solution for all of them 🤗 gotta be aligned with other library maintainers! FYI @Wauplin

That's fair. In case you need some references, similar changes have been included in other repos:
- https://github.com/mlflow/mlflow/issues/10106#issuecomment-1778790113
- https://github.com/mlflow/mlflow/pull/9961
- https://github.com/streamlit/streamlit/issues/7120
- https://github.com/streamlit/streamlit/issues/7526

**Comment by Wauplin** [comment]
Thanks a lot @DueViktor for raising the question :pray: I opened a PR in `huggingface_hub` which is the underlying library common to the other HF-libraries (transformers, diffusers, datasets,.): https://github.com/huggingface/huggingface_hub/pull/1782. My plan is to release that and then integrate with dependent libraries once adopted.

**Pull request closed without merging**
