### PR TITLE
Update feature_extraction_utils.py

### PR DESCRIPTION
**Pull request by daquarti**
config.json is needed to use custom ViTForImageClassification.from_pretrained()
but FEATURE_EXTRACTOR_NAME = "preprocessor_config.json"
so ---> output_feature_extractor_file = os.path.join(save_directory, "config.json") 

preprocessor_config.json

# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by NielsRogge** [comment]
@patrickvonplaten could you take a look at this?

**Comment by patrickvonplaten** [comment]
Hey @daquarti, 

This looks wrong to me -> the feature extractors don't save their parameters into `config.json`, but into `preprocessor_config.json`. Could you elaborate a bit more on the PR?

**Comment by daquarti** [comment]
Thanks for help Patrick, maybe may solution was not good because ViTFeatureExtractor.from_pretrained() needs "preprocessor_config.json"

The problem is the following:
When I use ViTFeatureExtractor.from_pretrained() "preprocessor_config.json" woks good.
but them, when I use ViTForImageClassification.from_pretrained() "config.json" is needed. If I rename "preprocessor_config.json" like "config.json"  ViTForImageClassification.from_pretrained() works

**Comment by patrickvonplaten** [comment]
Note that in order to load the model `ViTForImageClassification` one needs a `config.json`. In order to load the feature extractor one needs `preprocessor_config.json`.

**Comment by patrickvonplaten** [comment]
Those are actually two different configs for two different classes

**Pull request closed without merging**
