### PR TITLE
correct TTS pipeline docstrings snippet

### PR DESCRIPTION
**Pull request by ylacombe**
This PR aims to correct the TTS pipeline code snippet [that was failing](https://github.com/huggingface/transformers/actions/runs/5898104885/job/15998670461).

I simply wrote a correct snippet instead!

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?
Hey @ydshieh and @ArthurZucker, WDYT of that ?

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Can you just add your filename to `documentation_tests.txt`. We'll make this automatic for new files cc @ydshieh

**Comment by ylacombe** [comment]
Hey @ArthurZucker , thanks for the quick review !

Just a QQ before addressing your comments, [there is already a line](https://github.com/ylacombe/transformers/blob/b64cccafd178f7bbf83da2a75c8697836d60f533/utils/documentation_tests.txt#L491-L492) `src/transformers/pipelines/` in `documentation_tests.txt`.

I'm thus afraid to be redundant if I add `src/transformers/pipelines/text_to_audio.py` in `documentation_tests.txt`. WDYT?

**Comment by ydshieh** [comment]
Let me check, probably it's a logic error in test fetcher.

**Comment by ArthurZucker** [comment]
cc @ydshieh as he suggested this. If it's there it should indeed be tested and no need to add it again.

**Comment by ArthurZucker** [comment]
Can you also check the `empty` CI @ydshieh

**Comment by ydshieh** [comment]
well, that line is added after the new doc test logic was merged.

For this PR, let's just add the full path to the file to `documentation_tests.txt` and move on to merge this.
Will address the test fetcher later.

**Comment by ydshieh** [comment]
empty CI is expected as no code is changed - if I understand correctly

**Comment by ylacombe** [comment]
> For this PR, let's just add the full path to the file to documentation_tests.txt and move on to merge this.

It's done now!

**Comment by ydshieh** [comment]
@ylacombe Let's merge this unless something else to be done?

**Comment by ylacombe** [comment]
@ydshieh I agree, can you do it?

**Pull request merged**
