### PR TITLE
make small fixes in logging

### PR DESCRIPTION
**Pull request by kventinel**
# What does this PR do?

Fix some typing errors in logging file

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
Hello! What problem does that solve? :)

**Comment by kventinel** [comment]
> Hello! What problem does that solve? :)

Fix style of imports and froze constant dict to save it unmodified and preserve from errors.

**Comment by kventinel** [comment]
@LysandreJik, can you help me please with imports problems in tests?

**Comment by LysandreJik** [comment]
I am not sure we want to accept this PR, unfortunately I do not understand what problem it fixes. It seems to me that this already works well, do you have an example of where something would fail to do its intended purpose? Thanks!

**Comment by kventinel** [comment]
> I am not sure we want to accept this PR, unfortunately I do not understand what problem it fixes. It seems to me that this already works well, do you have an example of where something would fail to do its intended purpose? Thanks!

Frozendict -- its some good for python coding constraint, that dissalow chanding of dict. So its can help to avoid bags in future.

And some minor code style changes to rid from NOQA

**Comment by LysandreJik** [comment]
Thanks for your PR @kventinel, but I don't think this fixes any real issue so we will not be merging this PR as it is. Thanks.

**Pull request closed without merging**
