### PR TITLE
New model sharing tutorial

### PR DESCRIPTION
**Pull request by sgugger**
This PR removes the old serialization guide which was a bit outdated and adds the new instructions to the current model sharing tutorial (rewritten in rst to have proper links to the rest of the docs).

Also it adds a link to the trainer tutorial recently merged in the quicktour.

Preview is [here](https://53867-155220641-gh.circle-artifacts.com/0/docs/_build/html/model_sharing.html)

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Very cool!

**Review by patrickvonplaten — APPROVED** [review]
This is great!

**Comment by clmnt** [comment]
very cool! Let's share it with the hugging face twitter account when it's live to get more people to share their models on the hub!

**Comment by sgugger** [comment]
That would be now then, it's live in the [master docs](https://huggingface.co/transformers/master/model_sharing.html).

**Pull request merged**
