### PR TITLE
[docs] Update es/pipeline_tutorial.md

### PR DESCRIPTION
**Pull request by aaronjimv**
# What does this PR do?

The Spanish version of `pipeline_tutorial.md` is incomplete and outdated than the English version, which is mentioned in #30252.

This PR updates the content of  `es/pipeline_tutorial.md` so that it aligns with the `en/` version.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@stevhliu

### CODE REVIEW

**Comment by aaronjimv** [comment]
Hello! I had to modify the original content in the documentation. This is why I'd like to confirm the changes made to the structure of `es/pipeline_tutorial.md`,  before verifying the translation. Thanks.

**Review by stevhliu — COMMENTED** [review]
Thanks for aligning this tutorial with the more updated English version, LGTM!

**Comment by aaronjimv** [comment]
> Thanks for aligning this tutorial with the more updated English version, LGTM!

Thanks for confirm!

**Comment by tadeodonegana** [comment]
> cc: @tadeodonegana, @gisturiz
> 
> Hello guys, grateful as always for your help in evaluating the translation. I am open to any comments.

I will review this later today!

**Review by tadeodonegana — APPROVED** [review]
LGTM @aaronjimv @stevhliu

**Comment by aaronjimv** [comment]
> LGTM @aaronjimv @stevhliu

Thanks you👍

**Review by stevhliu — APPROVED** [review]
Thanks! 🤗

**Pull request merged**
