### PR TITLE
Fix resize_token_embeddings for Transformer-XL

### LINKED ISSUE #3554: resize_token_embeddings error for Transformer-XL
# 🐛 Bug

## Information

Model I am using : Transformer-XL

Language I am using the model on : English

The problem arises when using:
* [ ] my own modified scripts: a fine-tuning script for TransfoXLLMHeadModel

## To reproduce

The following code aims to add two new tokens to the vocabulary, 'wug' and 'wugs'. After doing so to the tokenizer, we call `resize_token_embeddings` with the model in order to update its input embeddings to have correct dimension to account for the new tokens.

``` python
import torch
from transformers import TransfoXLTokenizer, TransfoXLLMHeadModel

model = TransfoXLLMHeadModel.from_pretrained('transfo-xl-wt103')
tokenizer = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')

tokenizer.add_tokens(['wug', 'wugs'])
model.resize_token_embeddings(len(tokenizer))
```

Running the above gives the following error 
```
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    model.resize_token_embeddings(len(tokenizer))
  File "/home/AD/rdsie/anaconda3/envs/lign251/lib/python3.7/site-packages/transformers/modeling_utils.py", line 198, in resize_token_embeddings
    model_embeds = base_model._resize_token_embeddings(new_num_tokens)
  File "/home/AD/rdsie/anaconda3/envs/lign251/lib/python3.7/site-packages/transformers/modeling_utils.py", line 213, in _resize_token_embeddings
    new_embeddings = self._get_resized_embeddings(old_embeddings, new_num_tokens)
  File "/home/AD/rdsie/anaconda3/envs/lign251/lib/python3.7/site-packages/transformers/modeling_utils.py", line 234, in _get_resized_embeddings
    old_num_tokens, old_embedding_dim = old_embeddings.weight.size()
  File "/home/AD/rdsie/anaconda3/envs/lign251/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'AdaptiveEmbedding' object has no attribute 'weight'
```
It seems that the function `resize_token_embeddings()` does not currently account for the particulars of the input embeddings used for the TransformerXLLMHeadModel.

## Expected behavior

We expect that `resize_token_embeddings` should handle the appropriate updating of the embedding layers for the new vocabulary size, so that the model can be correctly used with the new tokens.

Thank you in advance

### PR DESCRIPTION
**Pull request by RafaelWO**
Fixes #3554 

As discussed in the issue above, the fix ensures that per default the last layer of the `AdaptiveEmbedding` is resized. Otherwise the target layer can be passed to the `resize_token_embeddings()` method as the parameter `layer`.

After the resizing is done, the cutoffs are adjusted accordingly.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
This looks clean! We would want to test that function before adding it, however. I don't think it can leverage the `test_resize_tokens_embeddings` test in `tests/modeling_common_tests.py` out of the box, given that `AdaptiveEmbeddings` doesn't have a weight attribute.

We would have to override it directly in `TransfoXLModelTest` with a custom test for `AdaptiveEmbeddings`.

Do you think you could add such a test, with strong inspiration from the [test_resize_tokens_embeddings](https://github.com/huggingface/transformers/blob/master/tests/test_modeling_common.py#L496) method?

**Comment by RafaelWO** [comment]
Thanks!
Yes sure, I was already thinking that a test could be useful here. I will try my best and add a test in [test_modeling_transfo_xl.py](https://github.com/huggingface/transformers/blob/master/tests/test_modeling_transfo_xl.py), correct? Do I have to add a separate class for it or include it in [TransfoXLModelTester](https://github.com/huggingface/transformers/blob/2b8b6c929e282958a920ba2aa26ee59106986ec3/tests/test_modeling_transfo_xl.py#L42) ?

Is there any proper way to run/debug only one test so I can try out my test-code easily?

**Comment by LysandreJik** [comment]
I was thinking of putting it in `TransfoXLModelTest` under the name `test_resize_tokens_embeddings` so that it overrides the parent class' method. Alongside the method `test_model_from_pretrained`, do you see what I mean?

You can run the test suite for only this file using the following command (requires `pytest` and `pytest-cov` installed, which gets you the best stacktrace):

```
python -m pytest -sv ./tests/*modeling_transfo* --cov       
```

Let me know if you need any help!

**Comment by RafaelWO** [comment]
Ok I added a test for the new `resize_token_embeddings` method.

P.S. running `isort --recursive examples templates tests src utils` reformats the file `examples\benchmarking\plot_csv_file.py` for me. Should I add this change too or ignore it?

**Review by LysandreJik — APPROVED** [review]
Great, this LGTM! Thanks @RafaelWO!

@thomwolf, do you want to take a look?

**Comment by RafaelWO** [comment]
@LysandreJik I'm happy to contribute :)
I have another question: Since my implementation supports resizing embedding layers other than the first, the added tokens have to be moved in the tokenizer as well. I also have a solution for this which I added into the `TransfoXLTokenizer`. Should I open a separate issue and PR for this (or just PR) or add it here, as it's somehow related?

**Comment by LysandreJik** [comment]
@patrickvonplaten, since you've worked a bit with TransformerXL in the past, do you want to take a look before we merge?

**Comment by patrickvonplaten** [comment]
I like it - looks very clean to me!

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
