### PR TITLE
CI: setup-dependent pip cache

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

This PR makes two changes to the way we cache our pip dependencies in the `add-model-like.yml` GH actions workflow:
1. The name of the cache depends on the hash of `setup.py`;
2. We do not restore the cache from partial name matches.

(this pattern exists in one of our CI files, `github-torch-hub.yml` , [here](https://github.com/huggingface/transformers/blob/main/.github/workflows/github-torch-hub.yml#L30))

Together, these changes will make us start from a fresh environment whenever we change `setup.py`. Having a stale cache was causing us to have dependency problems (e.g. [old, incompatible protobuf version](https://github.com/huggingface/transformers/runs/6007067240?check_suite_focus=true)), and potentially miss dependency issues from fresh installs.

If you agree, I will also port these changes to `model-templates.yml` and `update_metdata.yml`, which have the same pattern/issue. EDIT: ported.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing! Pinging @LysandreJik also on this.

**Review by LysandreJik — APPROVED** [review]
Ok for me!

**Review by ydshieh — APPROVED** [review]
I learn this thing from you in this PR, @gante!

LGTM.

**Comment by ydshieh** [comment]
To learn more: how long you figured out the cause for the error you mentioned:

https://github.com/huggingface/transformers/runs/6007067240?check_suite_focus=true

If it was me, I don't even know if I could figure this out!

**Comment by gante** [comment]
@ydshieh It definitely helps that I had this exact issue (stale CI caches) in my previous role :) 

To pin the error to this issue, I reran the failing CI workflow locally, from a fresh virtual env. Since it ran without issues, I had a look at the `.yml` file, and saw that it had a cache for `pip`. Then I went on to see that `pip install -e .[dev]` was doing in the failing CI file, and I noticed that it had error messages due to incompatible package versions, which I did not have locally -- because an old version was cached.

**Pull request merged**
