### PR TITLE
Add options to load CLIP Transformer models

### PR DESCRIPTION
**Pull request by amitkumarj441**
# What does this PR do?

Flexible options around loading CLIP transformer models

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! Could you share the motivations behind this? 🤗

**Comment by amitkumarj441** [comment]
> Hey! Could you share the motivations behind this? 🤗

@ArthurZucker I needed to have an independent feature extractor using CLIP text model for generating (query) embeddings, though, [CLIPTextModelWithProjection](https://github.com/huggingface/transformers/blob/50726f9ea7afc6113da617f8f4ca1ab264a5e28a/src/transformers/models/clip/modeling_clip.py#L1181C7-L1181C34) and similarly for `CLIP_vision` model has `AutoModelFor...` instance. So, to standardise this process around Transformer, we need options to avail these CLIP text/image models separately.

**Comment by ArthurZucker** [comment]
This is a custom usage and would recommend you to build on top of transformers. It's not really standard as you are gonna have missing keys and unexpected keys for both.

**Comment by amitkumarj441** [comment]
> This is a custom usage and would recommend you to build on top of transformers. It's not really standard as you are gonna have missing keys and unexpected keys for both.

Yes, it is, though, the tweaking options to adopt independent CLIP models (text/image) should lie within `modeling_clip.py` for flexibility.

**Comment by ArthurZucker** [comment]
Sorry but no, if you only want the vision model or only want the text model you should use the CLIPVisionModel and the CLIPTextModel rather than add this 😉

**Pull request closed without merging**
