### PR TITLE
typo in docstring

### PR DESCRIPTION
**Pull request by JadeKim042386**
# What does this PR do?

Fixes # (#18721)

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

### CODE REVIEW

**Comment by ydshieh** [comment]
@JadeKim042386 Thank you for the fix! I could find there are 15 same occurrences in `transformers`. Could you replace all of them by the correct one? Thank you!

**Comment by ydshieh** [comment]
@JadeKim042386 The commit history is now not clean - there are 35 files changed.
May I know if you use `git merge` or `git rebase` command? What's the exact command used?

Anyway, we need a clean status to review and approve the PR :pray.

**Comment by JadeKim042386** [comment]
@ydshieh sorry, I was looking for the build failed problem. I used `git commit --amend`. 
Now, I will make clean status.

**Comment by ydshieh** [comment]
No problem. Thank you :-)

**Comment by JadeKim042386** [comment]
@ydshieh
There were 35 files of the same occurrences in `transformers`.
Can I get a review and approval now? 😄

**Comment by ydshieh** [comment]
Hi, we can't merge a PR in such status. Considering the change could be quickly replicated: search -> replace, could you maybe 

```bash
git checkout main
git pull upstream main
git checkout -b new_fix  # a new branch to work this
```

and open a new PR instead of this one. Sorry to see this happens.

**Comment by JadeKim042386** [comment]
@ydshieh No problem~ 😎 I quickly open new PR.

**Pull request closed without merging**
