### PR TITLE
Fix bug leading to missing token in GPTSanJapaneseTokenizer

### PR DESCRIPTION
**Pull request by passaglia**
# Fixes the missing comma (,) token in the GPTSanJapaneseTokenizer

The comma character "," is a token in the default vocabulary file used by GPTSanJapaneseTokenizer.

However, the vocab file parser has a bug that deletes this token and so the GPTSanJapaneseTokenizer encodes commas as the <byte 44> token instead of a unique token.

This fixes that bug.

@tanreinama @younesbelkada @ArthurZucker

### CODE REVIEW

**Review by tanreinama — APPROVED** [review]

**Comment by ArthurZucker** [comment]
Hey! Could you make sure to run `make fix-copies` ! Otherzise looks good to me

**Comment by ArthurZucker** [comment]
😅 sorry, you can remove the `copied from` to get rid of the issue with make fix copies overwriting

**Comment by ArthurZucker** [comment]
Remove this : `# Copied from transformers.models.gpt_neox_japanese.tokenization_gpt_neox_japanese.load_vocab_and_emoji`

**Review by ArthurZucker — APPROVED** [review]
Thanks for catching this

**Pull request merged**
