### PR TITLE
[fsmt] onnx triu workaround

### LINKED ISSUE #9737: [fsmt] Exporting the operator triu to ONNX opset version 12 is not supported
As a follow up to https://github.com/huggingface/transformers/issues/9722

```
import torch
import transformers
from transformers import convert_graph_to_onnx
from pathlib import Path

convert_graph_to_onnx.convert(
    framework="pt",
    model="facebook/wmt19-en-de",
    output=Path("encoder/en_de_trans.onnx"),
    opset=12,
    tokenizer="facebook/wmt19-en-de",
    use_external_format= False,
    pipeline_name= "translation_en_to_de",
)
```
after applying the fix from https://github.com/huggingface/transformers/pull/9736
it then crashes with:

```
Traceback (most recent call last):
  File "/mnt/nvme1/code/huggingface/transformers-master/porting/onnx2.py", line 26, in <module>
    convert_graph_to_onnx.convert(
  File "/hf/transformers-master/src/transformers/convert_graph_to_onnx.py", line 367, in convert
    convert_pytorch(nlp, opset, output, use_external_format)
  File "/hf/transformers-master/src/transformers/convert_graph_to_onnx.py", line 279, in convert_pytorch
    export(
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/__init__.py", line 271, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/utils.py", line 671, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/utils.py", line 450, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/utils.py", line 204, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/__init__.py", line 309, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/utils.py", line 970, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/utils.py", line 927, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/onnx/symbolic_registry.py", line 112, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator triu to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

Process finished with exit code 1
```

Need to look at workarounds proposed at https://github.com/pytorch/pytorch/issues/32968

### PR DESCRIPTION
**Pull request by stas00**
This PR 

* solves 
   ``` 
   RuntimeError: Exporting the operator triu to ONNX opset version 12 is not supported. Please open a bug to request ONNX    export support for the missing operator.
   ```
   as reported in https://github.com/huggingface/transformers/issues/9737.
   It adds a workaround for `triu` not being supported by pytorch's onnx set, as proposed here: https://github.com/pytorch/pytorch/issues/32968#issuecomment-733240232 with some modifications to make it work with transformers. The original workaround couldn't handle a matrix with `-inf`.
* adds an onnx export test

The workaround fix is localized to fsmt, but transformers has a handful of those:

```
src/transformers/pipelines/question_answering.py:        candidates = np.tril(np.triu(outer), max_answer_len - 1)
src/transformers/models/fsmt/modeling_fsmt.py:    causal_mask = torch.triu(fill_with_neg_inf(torch.zeros(tgt_len, tgt_len)), 1).to(
src/transformers/models/transfo_xl/modeling_transfo_xl.py:            dec_attn_mask = (torch.triu(all_ones, 1 + mlen) + torch.tril(all_ones, -mask_shift_len))[:, :, None]  # -1
src/transformers/models/transfo_xl/modeling_transfo_xl.py:            dec_attn_mask = torch.triu(word_emb.new_ones((qlen, klen), dtype=torch.uint8), diagonal=1 + mlen)[
src/transformers/models/xlnet/modeling_xlnet.py:        mask_up = torch.triu(attn_mask, diagonal=1)
src/transformers/models/ctrl/modeling_ctrl.py:        mask = torch.triu(torch.ones(seq_len + past_length, seq_len + past_length), 1).to(inputs_embeds.device)
src/transformers/models/prophetnet/modeling_prophetnet.py:        left_block[stream_idx].triu_(-stream_idx + 1)
src/transformers/models/prophetnet/modeling_prophetnet.py:        causal_mask = torch.triu(causal_mask, 1)
```

Perhaps the workaround wrapper should be somewhere in the common tools and used in other places?

Or merge this to let the user who needed this in first place move forward and then refactor to other places which haven't been spoken for. But actually if you look at https://github.com/pytorch/pytorch/issues/32968 many of the me-too comments talk about `transformers`.

https://github.com/pytorch/pytorch/issues/32968 proposes other solutions too. I tried them and either they didn't work, or were inefficient as spotted by @patrickvonplaten 

Fixes: https://github.com/huggingface/transformers/issues/9737

@LysandreJik, @mfuntowicz

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
I'm a bit worried that this fix will blow up the memory for very long sequences, *e.g.* applying this to a max_length of 16384 (which we already have) would create a 1GB tensor

**Comment by patrickvonplaten** [comment]
Wouldn't this work-around be better in terms of memory? https://github.com/pytorch/pytorch/issues/32968#issuecomment-733240232

**Comment by stas00** [comment]
Glad you have the deep understanding of this one, @patrickvonplaten 

wrt, https://github.com/pytorch/pytorch/issues/32968#issuecomment-733240232 - I tried it originally and everything failed with it.

Perhaps it can be re-written not to use `triu`?

**Comment by stas00** [comment]
> Wouldn't this work-around be better in terms of memory? [pytorch/pytorch#32968 (comment)](https://github.com/pytorch/pytorch/issues/32968#issuecomment-733240232)

I managed to fix this more efficient version to work with `-inf`. It's in the PR now.

**Review by LysandreJik — APPROVED** [review]
LGTM for FSMT. Did you run the FSMT integration tests to ensure that it doesn't diverge?

**Review by sgugger — APPROVED** [review]
LGTM!

**Review by patrickvonplaten — APPROVED** [review]
Nice!

**Comment by stas00** [comment]
> Did you run the FSMT integration tests to ensure that it doesn't diverge?

Yes, the function produces the same output as `triu` for the inputs we use.

**Comment by gugarosa** [comment]
This workaround seems to only work for squared-sized tensors, while `torch.triu` works for any shape (PyTorch 1.9.0). For example:

```
a = torch.randn(8, 4)
triu_onnx(a)
```
raises an `RuntimeError: The size of tensor a (8) must match the size of tensor b (4) at non-singleton dimension 1`.

Is there any additional workaround when working with non-squared shape tensors?

Thank you and best regards,
Gustavo.

**Comment by stas00** [comment]
Indeed, the workaround was written for that sort of inputs.

Are you running into this problem with `transformers`? Could you please file a new issue then including the way to reproduce the problem?

But I also see that perhaps we can switch back to pytorch implementation as reported here:
https://github.com/pytorch/pytorch/issues/32968#issuecomment-827054124
it's called `trilu`.

Would you like to experiment with it and see if it solves the problem? If it works you may consider creating a PR that switches to that version instead and we can work together on polishing out the details (as we need to support older pytorch as well).

**Pull request merged**
