### PR TITLE
Add chat templating support for KeyDataset in text-generation pipeline

### PR DESCRIPTION
**Pull request by DarshanDeshpande**
# What does this PR do?
Adds direct support for KeyDatasets containing chat messages to the `text-generation` pipeline. Additionally, we now have better compatibility with the docs that explain how to use KeyDatasets with the generation pipeline ([here](https://huggingface.co/docs/transformers/main_classes/pipelines)).

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @Rocketknight1

**Review by Rocketknight1 — APPROVED** [review]
This looks good to me - it seems clean, and I appreciate the included test!

**Comment by Rocketknight1** [comment]
cc @amyeroberts for core maintainer review

**Review by amyeroberts — APPROVED** [review]
Thanks for adding this feature!

**Pull request merged**
