### PR TITLE
Update llm_engine.py

### PR DESCRIPTION
**Pull request by louisbrulenaudet**
# What does this PR do?
- Added support for optional token and max_tokens parameters in the constructor.
- Provided usage examples and detailed documentation for each method.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by LysandreJik** [comment]
cc @aymeric-roucher for review

**Review by aymeric-roucher — APPROVED** [review]
Great changes, thanks a lot @louisbrulenaudet!

**Comment by aymeric-roucher** [comment]
@louisbrulenaudet you'll just have to do a few style fixes (trailing whitespaces) before being able to merge.

**Comment by louisbrulenaudet** [comment]
```
Hi @aymeric, normally I've made the necessary corrections and removed the whitespaces, but I'm still getting a validation error that I can't explain.

Could you tell me what you think is wrong?
```

**Comment by aymeric-roucher** [comment]
@louisbrulenaudet the error in both `check_repository_consistency`  and `check_code_quality` is the following:
```
The following objects docstrings do not match their signature. Run `make fix-copies` to fix this. In some cases, this error may be raised incorrectly by the docstring checker. If you think this is the case, you can manually check the docstrings and then add the object name to `OBJECTS_TO_IGNORE` in `utils/check_docstrings.py`.
- HfApiEngine
```
I believe it might be because 3 of the 4 arguments are defined as `(str, optional)` in the docstrings but are only `str` instead of `Optional[str]` in their signature, so should be `str`in the docstrings (yes the verification is picky 😅). You can run `make fix-copies` to check this.

**Comment by louisbrulenaudet** [comment]
Hello @aymeric-roucher,

I have the impression that all the tests have been passed, thank you again for your information and your help, I hope that everything will go well from now on and wish you a good day.

**Comment by aymeric-roucher** [comment]
It's merged! Thanks a lot for this PR @louisbrulenaudet 🤗

**Pull request merged**
