### PR TITLE
add greek translation to index

### LINKED ISSUE #19788: Add translation of docs to greek

### PR DESCRIPTION
**Pull request by ArchontisKostis**
# What does this PR do?

Fixes #19788

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Thanks for adding this. For language codes, it looks like we use `el` for Greek on the Hub. Is this the right standard @osanseviero ?

**Comment by osanseviero** [comment]
Yes, Greek under ISO 639-1 would be `el`. `gre` corresponds to 639-2. 

(source: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by ArchontisKostis** [comment]
Hello! I am really sorry for the mistake I will fix it shortly!

**Comment by sgugger** [comment]
Sorry missed the change! It looks like there is a problem with CircleCI (tests are not run). Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

Could you also add the Greek language code [here](https://github.com/huggingface/transformers/blob/11f3ec7224c83c9e5c379a774b9d3984e68d26fa/.github/workflows/build_documentation.yml#L18) and [there](https://github.com/huggingface/transformers/blob/11f3ec7224c83c9e5c379a774b9d3984e68d26fa/.github/workflows/build_pr_documentation.yml#L17) so that the doc is built in Greek?

let us know if you need any help, thanks!

**Pull request closed without merging**
