### PR TITLE
Serializing XLMRobertaTokenizer

### PR DESCRIPTION
**Pull request by brandenchan**
I am currently trying to use the XLMRobertaTokenizer in a multiprocessor setting. To do this, the XLMRobertaTokenizer needs to be serializable. Currently XLMRobertaTokenizer is not serializable while other tokenizers such as AlbertTokenizer are.

This PR adds the __getstate__ and __setstate__ methods to XLMRobertaTokenizer so that it can be serialized.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
This looks good to me!

**Comment by tholor** [comment]
Is anything blocking from merging this? :)
Would help us a lot with parallelizing the preprocessing!

**Comment by tholor** [comment]
Awesome! Thanks @LysandreJik  :)

**Comment by LysandreJik** [comment]
Thank you for your contribution, @tholor !

**Pull request merged**
