### PR TITLE
MLU devices : Checks if mlu is available via an cndev-based check which won't trigger the drivers and leave mlu

### PR DESCRIPTION
**Pull request by huismiling**
# What does this PR do?

MLU devices : Checks if mlu is available via an cndev-based check which won't trigger the drivers and leave mlu

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by huismiling** [comment]
@ArthurZucker 
Hi, Could you help to merge this PR ?

**Review by ArthurZucker — COMMENTED** [review]
Hey is there any doc regarding `PYTORCH_CNDEV_BASED_MLU_CHECK` anywhere? Or are we just using / creating is for this?

**Comment by huismiling** [comment]
> Hey is there any doc regarding `PYTORCH_CNDEV_BASED_MLU_CHECK` anywhere? Or are we just using / creating is for this?

@ArthurZucker 
Hi, Just using / creating `PYTORCH_CNDEV_BASED_MLU_CHECK` is OK.
Like nvml, CNDEV is a cambricon library for MLUs, . It will not affect pytorch but torch_mlu.

`nvml-based` and `cndev-based` check has been used in accelerate. 
https://github.com/huggingface/accelerate/pull/3187

https://github.com/huggingface/accelerate/blob/ba7ab93f5e688466ea56908ea3b056fae2f9a023/src/accelerate/utils/imports.py#L116
```
def is_cuda_available():
    """
    Checks if `cuda` is available via an `nvml-based` check which won't trigger the drivers and leave cuda
    uninitialized.
    """
    with patch_environment(PYTORCH_NVML_BASED_CUDA_CHECK="1"):
        available = torch.cuda.is_available()

    return available
```

https://github.com/huggingface/accelerate/blob/ba7ab93f5e688466ea56908ea3b056fae2f9a023/src/accelerate/utils/imports.py#L322

```
def is_mlu_available(check_device=False):
    """
    Checks if `mlu` is available via an `cndev-based` check which won't trigger the drivers and leave mlu
    uninitialized.
    """
    if importlib.util.find_spec("torch_mlu") is None:
        return False

    import torch_mlu  # noqa: F401

    with patch_environment(PYTORCH_CNDEV_BASED_MLU_CHECK="1"):
        available = torch.mlu.is_available()

    return available
```

**Comment by huismiling** [comment]
@ArthurZucker 
Hi, is this PR okay to merge ? Is there anything else I can help ?

**Comment by huismiling** [comment]
@ArthurZucker 
Hey, Just remind this .

**Review by ArthurZucker — APPROVED** [review]
Cool! Thanks for updating! 🤗 
Sorry we were on a company wide offsite, had no time to work 🌴

**Pull request merged**
