### PR TITLE
Improving `image-segmentation` pipeline tests.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

This PR (https://github.com/huggingface/transformers/pull/19367) introduced a few breaking changes:

- Removed an argument `mask_threshold`.
- Broke the default behavior (instance vs panoptic in the function call)
  https://github.com/huggingface/transformers/pull/19367/files#diff-60f846b86fb6a21d4caf60f5b3d593a04accb8f248de3029cccae2ff898c5bc3R119-R120
- Broke the actual masks: https://github.com/huggingface/transformers/pull/1961

This PR is the start of a handful that will aim at bringing back the old
behavior(s).

- tests should not have to specify `task` by default, unless we want to
  modify the behavior and have a lower form of segmentation running)
- `test_small_model_pt` should be working.

This specific PR starts with adding more information to the masks hash
because missing the actual mask was actual easy to miss (the hashes do
change, but it was easy to miss that one code path wasn't properly
updated).

So we go from a simple `hash` to
```
{"hash": #smaller hash, "shape": (h, w), "white_pixels": n}
```

The `shape` should help make sure the interpolation of the mask works
correctly, the `white_pixels` hopefully helps detect big regressions in
their amount when the hash gets modified.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for the improvement! ⭐  Having this information alongside the hash is great - it will definitely help when debugging and I know would have saved me time previously. 

I'm not sure I understand your point about 
> missing the actual mask was actual easy to miss (the hashes do
change, but it was easy to miss that one code path wasn't properly
updated).

as it seems this PR is adding supplementary information to existing tests. Do we still need to add a test for this missing codepath?

**Review by alaradirik — APPROVED** [review]
Thank you for the improvement! Definitely makes it easier to debug issues.

**Comment by Narsil** [comment]
> as it seems this PR is adding supplementary information to existing tests. Do we still need to add a test for this missing codepath?

I meant that missing `astype(np.uint8)` was easy to miss, and since mask inspection was pretty manual, it was easy to check a few different setups, think everything was correct, and miss the one mask that was incorrect, and updated the tests without realizing the tests results were actually not making any sense.

This addition merely tries to reduce the risk of that happening, but if the tests don´t  use that path we won't know either.

**Review by sgugger — APPROVED** [review]
Thanks for all the fixes in the tests!

**Pull request merged**
