### PR TITLE
Check device map for saving tokenizer config on TPU (fix for issue #31971)

### LINKED ISSUE #31971: "TypeError: Object of type device is not JSON serializable" when saving the model on TPU
### System Info

Running on v4-64 Google TPU Pod:
- torch~=2.3.1
- torch_xla[tpu]~=2.3.0
- accelerate=0.32.1
- transformers=4.42.4
CLI env output:
- `transformers` version: 4.42.4
- Platform: Linux-5.19.0-1022-gcp-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.23.4
- Safetensors version: 0.4.3
- Accelerate version: 0.32.1
- Accelerate config:    not found
- PyTorch version (GPU?): 2.3.1+cu121 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

### Who can help?

@muellerz @SunMarc 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to finetune Gemma/Llama models on Google TPU Pod (v4-64). When I save the model at the end of trainer or separately using trainer.save_model() I encounter the following error which happens when saving tokenizer:

```
Traceback (most recent call last):
  File "/home/user_name/train_llama.py", line 254, in <module>
    main()
  File "/home/user_name/train_llama.py", line 246, in main
    trainer.train()
  File "/home/user_name/.local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 440, in train
    output = super().train(*args, **kwargs)
  File "/home/user_name/.local/lib/python3.10/site-packages/transformers/trainer.py", line 1932, in train
    return inner_training_loop(
  File "/home/user_name/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2345, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/home/user_name/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2796, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/home/user_name/.local/lib/python3.10/site-packages/transformers/trainer.py", line 2875, in _save_checkpoint
    self.save_model(output_dir, _internal_call=True)
  File "/home/user_name/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3395, in save_model
    self._save_tpu(output_dir)
  File "/home/user_name/.local/lib/python3.10/site-packages/transformers/trainer.py", line 3472, in _save_tpu
    self.tokenizer.save_pretrained(output_dir)
  File "/home/user_name/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2572, in save_pretrained
    out_str = json.dumps(tokenizer_config, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type device is not JSON serializable
wandb: \ 0.044 MB of 0.044 MB uploaded
```
### Code reproduction
Similar lunch process as in the example [here](https://github.com/huggingface/transformers/blob/350aed70765cac5acfa7a4cfac4d1e6e2dc0b19b/examples/legacy/seq2seq/finetune_tpu.sh) either with spawning or directly launching the training script.
```python
def main():
    device = xm.xla_device()
    print(device)
    max_seq_length = 1024 
    packing = True
    base_model = "google/gemma-2-9b"
    output_dir = f"{base_model}-lora" 
    fsdp_config = {"fsdp_transformer_layer_cls_to_wrap": [
            "GemmaDecoderLayer",
        ],
        "xla": True,
        "xla_fsdp_v2": True,
        "xla_fsdp_grad_ckpt": True} 
    
    model = AutoModelForCausalLM.from_pretrained(base_model, device_map=device, token=token)
    tokenizer = AutoTokenizer.from_pretrained(base_model, token=token, return_tensors="pt", device_map=device)
    tokenizer.pad_token = "[PAD]"
    tokenizer.padding_side = "left"
    lora_config = LoraConfig(
            r=32,
            lora_alpha=64,
            target_modules=["q_proj", "o_proj", "k_proj", "v_proj", "gate_proj", "up_proj", "down_proj"],#"all-linear",
            lora_dropout=0.05,
            bias="none",
            task_type="CAUSAL_LM",
        )

    model.enable_input_require_grads()
    prepare_model_for_kbit_training(model)
    peft_model = get_peft_model(model, lora_config)
    peft_model.print_trainable_parameters()

    val_set_size = 0.1

    dataset = load_dataset("Abirate/english_quotes")
    len(dataset["train"])
    train_val = dataset["train"].train_test_split(
        test_size=val_set_size, shuffle=True, seed=2024
    )
    train_data = train_val["train"].shuffle(seed=2024)
    val_data = train_val["test"].shuffle(seed=2024)

    
    # Set the training arguments
    args = TrainingArguments(
        output_dir = output_dir,
        # auto_find_batch_size=True,
        per_device_train_batch_size=1, # Batch size = per_device_train_batch_size * gradient_accumulation_steps * num_gpus (if using DataParallel)
        per_device_eval_batch_size=1, # Batch size = per_device_train_batch_size * gradient_accumulation_steps * num_gpus (if using DataParallel)
        eval_accumulation_steps=5,
        gradient_checkpointing=False,
        tpu_num_cores = num_cores,
        warmup_steps=100, 
        max_steps=3, #3
        learning_rate=1e-5,
        bf16=True,
        deepspeed=deepspeed_config,
        ddp_backend="mpi",
        logging_strategy="steps",
        logging_steps=2,
        optim="adamw_torch",
        logging_dir="/data/training_output",
        lr_scheduler_type="cosine",
        evaluation_strategy="steps",
        fsdp="full_shard",
        fsdp_config=fsdp_config,
        save_strategy="steps",
        report_to="wandb",
        eval_steps=5,
        dataloader_drop_last = True,
        save_steps=50,
        save_total_limit=4,
        load_best_model_at_end=True,
        save_on_each_node=True,
    )

    trainer = SFTTrainer(
            model=peft_model,
            args=args,
            train_dataset=train_data,
            eval_dataset=val_data,
            tokenizer=tokenizer,
            packing=packing,
            max_seq_length=max_seq_length,
            dataset_text_field="quote",
        )

    # Train the model
    trainer.train()
    trainer.save_model(f"{output_dir}/trainer")
    tokenizer.save_pretrained(output_dir)

def _mp_fn(index):
    # For xla_spawn (multi-host TPUs)
    args = parse_arguments()
    main(deepspeed_config=args.deepspeed_config, num_cores=args.tpu_num_cores)

if __name__ == "__main__":
    args = parse_arguments()
    main(deepspeed_config=args.deepspeed_config, num_cores=args.tpu_num_cores)
```

### Expected behavior

The error arises [here](https://github.com/huggingface/transformers/blob/350aed70765cac5acfa7a4cfac4d1e6e2dc0b19b/src/transformers/tokenization_utils_base.py#L2572). I tried somehow changing the device for model and tokenizer, but as it is configured internally inside Trainer I do not think I can fix it. I checked the source code and did not see device mentioned anywhere during config saving, not sure why this issue arises on TPU specifically.

### Expected behavior

- Both model and tokenizer trained on TPU are saved correctly without issues
- TPU device in configuration should be ignored when saving? In other cases I assume the code should be modified to handle TPU device

### PR DESCRIPTION
**Pull request by ayukh**
# What does this PR do?

Removes device_map from tokenizer_config when saving tokenizer on **TPU**. 

Fixes [#31971](https://github.com/huggingface/transformers/issues/31971)

**Why?**

As mentioned in the issue above, configs after training on TPU and non-TPU devices are different. After training on TPU, we get the following tokenizer config:
```
{'clean_up_tokenization_spaces': False, 'unk_token': '<unk>', 'bos_token': '<bos>', 'eos_token': '<eos>', 'pad_token': '[PAD]', 'add_bos_token': True, 'add_eos_token': False, 'additional_special_tokens': ['<start_of_turn>', '<end_of_turn>'], 'model_max_length': 1000000000000000019884624838656, 'sp_model_kwargs': {}, 'spaces_between_special_tokens': False, 'use_default_system_prompt': False, 'device_map': device(type='xla', index=0),...
```
While after training or non-TPU (e.g. GPU), we get the same config, but without `device_map`:
```
{'clean_up_tokenization_spaces': False, 'unk_token': '<unk>', 'bos_token': '<bos>', 'eos_token': '<eos>', 'pad_token': '<pad>', 'add_bos_token': True, 'add_eos_token': False, 'additional_special_tokens': ['<start_of_turn>', '<end_of_turn>'], 'model_max_length': 1000000000000000019884624838656, 'sp_model_kwargs': {}, 'spaces_between_special_tokens': False, 'use_default_system_prompt': False,...
```
`device_map` is not being used anywhere when loading tokenizer, therefore we can exclude it from config to support consistency across devices.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. -> Discussed in the [issue](https://github.com/huggingface/transformers/issues/31971) listed above.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? -> not sure if need to run big tests here as I am not adding any models; just a minor fix, which was tested on Google TPU Pods and fixes the error mentioned in the issue above.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@SunMarc

### CODE REVIEW

**Review by SunMarc — APPROVED** [review]
Thanks for the investigation and the fix @ayukh ! LGTM !

**Review by ArthurZucker — COMMENTED** [review]
LGTM but how did device map end up here? 
AFAIK, device map should not go on the tokenizer, unless accelerate automatically dispatches the input ids?

**Comment by ayukh** [comment]
> LGTM but how did device map end up here? AFAIK, device map should not go on the tokenizer, unless accelerate automatically dispatches the input ids?

To be honest, not sure why it appears there, maybe because it was a multi-TPU training and that code did not use accelerate, just SFTTrainer.
I should note that my experience with using HF modules on Colab TPU and big TPU Pods is quite different as accelerate does not recognize TPU device case with VMs even.

**Comment by ArthurZucker** [comment]
I mostly see this:
> tokenizer = AutoTokenizer.from_pretrained(base_model, token=token, return_tensors="pt", device_map=device)

passing device map to the tokenizer init

**Comment by ayukh** [comment]
> passing device map to the tokenizer init

Can confirm that without passing device_map I have the same issue, this was just left in the code when trying to find the problem fix. I re-ran the code without it on transformers==4.42.4 to check and somehow I get the same error as described in the issue. I should note that before I used the same code as you mentioned above on both Colab GPU and multi-host TPU Pod and I had no device_map written for GPU config. Is it possible that it saving device due to multiple hosts?🤷
In any case device_map in TPU format is causing troubles in saving config, I can either remove it or rewrite the class as a string ('xla:index').

**Comment by ayukh** [comment]
Also apologies for multiple edits before, I figured out which command saves device_map and which doesn't🤷
On non-TPU devices device_map using accelerate also looks ok, but I can't test it for TPU since it doesn't work properly on Google TPU Pod at the moment.

**Comment by ArthurZucker** [comment]
Not sure what's the best solution, we can raise and error if device map is passed as it seems recurring

**Comment by ayukh** [comment]
Potentially can just use a check for `device_map` and then throw an error if it is not in str format:
```
if "device_map" in tokenizer_config and not isinstance(tokenizer_config["device_map"], str):
    tokenizer_device = tokenizer_config["device_map"]
    raise TypeError(f"'device_map' is not in str type, got {type(tokenizer_device)}. Please set the value in str format (e.g. 'auto') or do not pass it into tokenizer (for TPU).")
```
This would throw an error for any non-str device, like xm.xla_device()/torch.device, which would be in torch.device class format.

**Comment by ayukh** [comment]
> We could, but overall tokenizer should not be related to any device! SO better just removing it and not serializing

I agree, initially I wasn't sure if device is used anywhere for tokenizer after checking the source code. Then we can keep the before proposed code, where we just remove the device using:
```
if "device_map" in tokenizer_config:
    tokenizer_config.pop("device_map")
```
Does this look like a good solution to the issue?

**Comment by ArthurZucker** [comment]
yeah sure!

**Pull request merged**
