### PR TITLE
[WIP] Trainer supporting evaluation on multiple datasets

### LINKED ISSUE #15857: Supporting multiple evaluation datasets in `Trainer` and `Seq2seqTrainer`
# 🚀 Feature request

Support for evaluating on multiple validation datasets when using the `Trainer` class.

## Motivation

This is a common use case in research. Imagine that you train your model on some data, and you have validation data coming from two distinct distributions. You want to compute two sets of metrics - one for the validation dataset with the same distribution as the training data and one for the validation dataset with known  distribution.

## Your contribution

- Happy to submit an example with my own code (assuming the research makes sense) so that others see how this can be achieved in practice. 

- Could update relevant posts on the huggingface forum so that other users requiring this feature can see how it can be done.

## Things I have tried

Inspired by this post [here](https://discuss.huggingface.co/t/evaluating-your-model-on-more-than-one-dataset/1544) and @sgugger's solution, I set out to see if implementing the `on_evaluate` callback is possible, but I can't figure out how to get the other validation datasets to it - the callaback can only access the trainer init arguments/state but none of these objects can be passed additional data loaders. 

How can this be approached instead? My current solution is not clean, but may work:

1. Use `setattr` to add an attribute to the trainer after init, call it `additional_eval_datasets`
2. Override the `_maybe_log_save_evaluate` method as follows:
         - Call the `Trainer` superclass method first to do what the trainer would normally do
         - loop through the additional datasets, calling the `Trainer.evaluate` for each dataset with appropriate inputs

This is a bit hacky as I should not be overriding a private method, but override `evaluate` instead. However, the implementation would be more concise in this way. Please feedback of any undesirable side effects that this may lead to - I did read through the `Trainer` source code and did not spot any pitfalls!

Of course, this approach can be adapted in order to support evaluation on multiple datasets natively in the `Trainer`.

### PR DESCRIPTION
**Pull request by timbmg**
# What does this PR do?
With this PR `Trainer` and `Seq2SeqTrainer` support evaluating on multiple datasets. For this, the `eval_dataset` and `compute_metrics` parameters have been updated. In order to evaluate on multiple datasets, `eval_dataset` should be a dict mapping a dataset name to a Dataset. In `_maybe_log_save_evaluate` we then loop over the dict, calling `evaluate` with each Dataset. The metric prefix is also updated to contain the dataset name. Furthermore, each eval dataset can optionally have its own `compute_metrics` function. For this, `compute_metrics` should be a dict where the keys match with `eval_dataset`.

Fixes #15857

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
 @sgugger

### CODE REVIEW

**Comment by timbmg** [comment]
Hey @sgugger, I mostly followed your suggestion in #15857, except instead of having a list of eval_datasets and another training arg, I solved it via passing a dict of eval_datasets. I thought a dict would work better because we also need multiple compute_metric functions. This way it is all lined up and less error-prone. However, let me know if you think otherwise.

Also, could you suggest what tests to write for this PR?

**Review by sgugger — COMMENTED** [review]
Thanks for your PR! Having the multiple datasets as a dict solves the problem of distinguishing a single dataset that is a list or a list of datasets. So I like this part.

However I didn't see anything in the issue regarding using several `compute_metrics` function. If there is a need for different metrics, it probably means different Trainer should be built as it represents different tasks/problems. That change should be reverted, as the part where `compute_metrics` can be passed along to the `evaluate`/`predict` function.

**Comment by timbmg** [comment]
Thanks for checking it so quickly!

In my case, I am training a seq2seq QA model and evaluating it on multiple datasets. However, they have different fromats (eg extractive qa like SQuAD, or multiple-choice qa like commonsese QA). Using a seq2seq model for multiple formats has been for example proposed in the [UnifiedQA paper](https://arxiv.org/abs/2005.00700). Having multiple trainers has the limitation that I could only train on a single dataset at a time, but not train on multiple ones at the same time. However, note that if you pass multiple eval_datasets as a dict, but only a single compute_metric callable, the same compute_metrics function will be called on all the eval_datasets. That's what [this if statement](https://github.com/huggingface/transformers/pull/19158/files#diff-ed55888e6665791fe92cc8fc0c499da54f4ace6738551cd9a2591881cda076deR2048) is doing. So the original scenario described in the Issue is also solved.

**Comment by sgugger** [comment]
It's too niche of a use-case to allow for support, especially when we have other tools that easily let you more customizable training/evaluation loops like Accelerate.

**Comment by timbmg** [comment]
Alright, I have reverted the change. Let me know in case of anything else:)

**Review by sgugger — APPROVED** [review]
Looking good, thanks a lot for amending the PR!

**Review by sgugger — APPROVED** [review]

**Comment by jurrr** [comment]
I'm trying to take advantage of the feature to include multiple eval_datasets in the trainer. Maybe I'm misreading the documentation, I've tried several ways to present the eval_dataset, but keep getting a KeyError when I include a DatasetDict / dict with datasets for the eval_dataset parameter. Am I doing something wrong? Do I need to specify the compute_metrics differently? Couldn't find anything on that. 

Here's an example notebook resulting in the ValueError: https://colab.research.google.com/drive/1yLo9iqY4Cz9_h8BtAvcYRCtK5O_xa5jP?usp=sharing

**Comment by alexcoca** [comment]
> Thanks for your PR! Having the multiple datasets as a dict solves the problem of distinguishing a single dataset that is a list or a list of datasets. So I like this part.
> 
> However I didn't see anything in the issue regarding using several `compute_metrics` function. If there is a need for different metrics, it probably means different Trainer should be built as it represents different tasks/problems. That change should be reverted, as the part where `compute_metrics` can be passed along to the `evaluate`/`predict` function.

@sgugger passing multiple `compute_metrics` functions for evaluation purposes can actually be more general than stated by @timbmg. For example, suppose we are doing multi-task training and we wish to evaluate on the same or held-out tasks as we train. This is common in recent research publications (eg FLAN-T5). Would you accept to support the multiple compute metrics functions? Or would your advice be to not use the trainer altogether and look towards using `accelerate`?

**Comment by sgugger** [comment]
I'd recommend using Accelerate instead of the Trainer for this use case.

**Comment by dcruiz01** [comment]
@sgugger Any examples out there of using Accelerate for this? I would also like to evaluate on multiple datasets while training. Thanks!

**Comment by sieu-n** [comment]
fyi, @dcruiz01 I guess this can be implemented by overriding the `Trainer` class following the initial commit? Or some mixin regarding multiple trainers.. Another workaround that comes to my mind is identifying the eval dataset with an additional field and splitting them in the compute_metrics function. I'll try to share if any actually works. 

+ Though I agree this is less common for fine-tuning, I want to add another use case of fine-tuning LLMs, in which we want to measure performance on many many different task / metrics / dataset.

**Comment by dcruiz01** [comment]
@sieu-n Any luck with the experiments you mentioned?

**Comment by lhallee** [comment]
@sgugger @timbmg it looks like the eval_datasets change was pushed for support as a dict but the compute_metrics changes were not pushed. Will this change be made or no?

**Comment by 0seba** [comment]
Hey, I think the additional feature to use separated data collators would be useful

**Pull request merged**
