### PR TITLE
[`Llama ROPE`] Fix torch export but also slow downs in forward

### LINKED ISSUE #29173: llama model: causal_mask does not exist
### System Info

Line: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L372C43-L372C54

`causal_mask` does not exist if attention_mask is None.

```python
  if attention_mask is not None:  # no matter the length, we just slice it
      if cache_position is not None:
          causal_mask = attention_mask[:, :, cache_position, : key_states.shape[-2]]
      attn_weights = attn_weights + causal_mask
```

### Who can help?

@onnx

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
config = LlamaConfig(
    num_hidden_layers=num_hidden_layers,
    vocab_size=vocab_size,
    hidden_size=hidden_size,
    intermediate_size=intermediate_size,
    max_position_embeddings=max_position_embeddings,
    num_attention_heads=num_attention_heads,
)
config._attn_implementation = _attn_implementation
model = LlamaAttention(config)
torch.compile(model)
optimized_model = torch.compile(model)
optimized_model(*inputs)
```

### Expected behavior

No exception.

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Reverts some of the breaking changes introduce in #29109 
The release mentions that we have a breaking change.
This makes it truly BC in the way you access `sin_cache` without memory / tracing / forward issue. 
fixes #29173

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Seems good once the CI passes!

**Review by gante — APPROVED** [review]
Missing: a test for torch.compile!

**Comment by fxmarty** [comment]
+1 @gante there should be tests for torch.compile / torch.compile with `fullgraph=True`

**Comment by ArthurZucker** [comment]
Yes yes!

**Pull request merged**
