### PR TITLE
Fixing DeformableDETR the easy but not the best way (IMO).

### LINKED ISSUE #19024: Add Deformable DETR to the object detection pipeline tests
Deformable DETR was added in #17281, however I had to [disable](https://github.com/huggingface/transformers/blob/9f4acd059f9c2a195a3ff71c5bc34cb5512b0446/tests/pipelines/test_pipelines_object_detection.py#L56-L60) the model for the object detection pipeline tests, as it fails.

However, the model runs just fine with the pipeline as shown [in this notebook](https://colab.research.google.com/drive/1OPmsjC7mSyEpZ2qYGYIwyfIqGyMXyZ2O?usp=sharing).

cc @Narsil 

Also cc'ing @mishig25, it may be beneficial to add a "threshold" button to the object detection widget, as Deformable DETR for instance only detects objects on the cats image with a threshold of 0.7, whereas the current threshold is [set to 0.9](https://github.com/huggingface/transformers/blob/9f4acd059f9c2a195a3ff71c5bc34cb5512b0446/src/transformers/pipelines/object_detection.py#L64).

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

This PR fixes the pipeline to accomodate  DeformableDETR.

The core of the issue is 
https://github.com/huggingface/transformers/blob/main/src/transformers/models/deformable_detr/modeling_deformable_detr.py#L178-L181

Both these tensor don't use `batch_size` in the first place, so the magic batchig/debatching of the pipeline is confused.

It's not entirely clear why the tensor has this weird shape though. @NielsRogge is there any reason ?
Regardless we can't really change that this it would be a breaking change.

The culprit lines are here:
https://github.com/huggingface/transformers/blob/585f9c6d9efa9f6e93888b6adf84912ba3f98dfc/src/transformers/models/deformable_detr/modeling_deformable_detr.py#L1397-L1398

@sgugger I though I remembered some tensors where not returned by default with `return_loss=False`.
Would that be something acceptable ?

The pipeline fix is fine to avoid all complications, but it's brittle since during batching/debatching the pipeline has only access to the tensor name, so if any other model reuses the same name we're going to have a bigger issue.

Fixes: https://github.com/huggingface/transformers/issues/19024

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
> Regardless we can't really change that this it would be a breaking change.

Deformable DETR is very new and I haven't seen it widely used, so there is still time to fix this in the model IMO. It would probably be cleaner to do it this way if @NielsRogge agree than hard-code something like this in the pipeline.

**Comment by NielsRogge** [comment]
Thanks for your PR, so the issue would be resolved if these tensors have `batch_size` in the first dimension (rather than the second)?

I think we can still fix that.

**Comment by Narsil** [comment]
> Thanks for your PR, so the issue would be resolved if these tensors have batch_size in the first dimension (rather than the second)?

Yes it should. When unknown tensors are seen, the batching/unbatching assumes the first dimension is the batch_size.

**Comment by Narsil** [comment]
We fixed it correctly

**Pull request closed without merging**
