### PR TITLE
Fix examples in M2M100 docstrings

### PR DESCRIPTION
**Pull request by lewtun**
# What does this PR do?

Replaces `tok` with `tokenizer` so examples can run with copy-paste

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patil-suraj

### CODE REVIEW

**Comment by shahriartaan1** [comment]
U r good guy who was other guy mastermind

**Comment by shahriartaan1** [comment]
Where is my sister?

**Comment by shahriartaan1** [comment]
Tell her to call me now man. Please

**Review by patil-suraj — APPROVED** [review]
Thanks a lot for fixing this!

**Pull request merged**
