### PR TITLE
Cambricon MLUs support SDPA and flash_attn

### PR DESCRIPTION
**Pull request by huismiling**
# What does this PR do?

add features: MLUs support SDPA and flash_attn.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by LysandreJik** [comment]
cc @ArthurZucker @younesbelkada

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for this contribution ! Can you point me to the commit on Flash Attention that enables support on Cambricon MLU devices ? 🙏

**Comment by huismiling** [comment]
@younesbelkada Thanks, this is the commit. 
[Cambricon support SDPA and flash_attn](https://github.com/huggingface/transformers/pull/31102/commits/6adf3d9e7908a1ff03853f0ac339ac07fd9ad452)

**Comment by younesbelkada** [comment]
Hi @huismiling 
This is not the commit from Flash Attention library, what I want to see is the commit in flash attention library that enables cambricon support to confirm it is included in the 2.3.3 version, so far I couldn't find it :/

**Comment by huismiling** [comment]
@younesbelkada 
Hi, MLU imply private flash attn. It is not included in flash-attention. 
MLU's flash attn has not been open-sourced yet.

**Review by younesbelkada — APPROVED** [review]
Thanks !

**Review by ArthurZucker — APPROVED** [review]
Since flash attention 2.3.3 is out I think it's fair to merge!

**Comment by huismiling** [comment]
@ArthurZucker @LysandreJik 
Hi, is this PR Okay to be merged ? Is there anything I can help?

**Comment by ArthurZucker** [comment]
Sorry I was waiting for the testse and got lost in track!

**Pull request merged**
