### PR TITLE
Fix typo (line 221) in portuguese translation. Documentation @sugger …

### PR DESCRIPTION
**Pull request by kant**
# What does this PR do?
Fix typo (line 221)

Fixes # (issue)
Relative with this issue #19443

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?
No

## Who can review?
@sgugger @ydshieh 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by ydshieh** [comment]
@kant

As @sgugger mentioned before:
> there is an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

You can also try to push an empty commit first to see if it can trigger the CI. You can do it by
```bash
git commit --allow-empty -m "push an empty commit to trigger CI"
```

**Comment by kant** [comment]
done the steps via this [resource](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)

**Review by ArthurZucker — APPROVED** [review]
LGTM, if you can also include a change in `[tf.keras.Model](http: //www.tensorflow.org/api_docs/python/tf/keras/Model))` it seems that there is an extra space. See line 328.

**Comment by ArthurZucker** [comment]
(juste make sure the `check-quality` test pass

**Comment by sgugger** [comment]
@kant We still need you to push an empty commit on this branch so that the tests are re-triggered with the appropriate permissions.

**Pull request closed without merging**
