### PR TITLE
Add DistilBERTForCausalLM

### LINKED ISSUE #7397: Add DistilBERTGeneration comparable to BertGeneration
# 🚀 Feature request

I noticed the new `BertGeneration` class, which uses BERT-style models as both encoder and decoder, as well as the more general `EncoderDecoder` class. This is all great stuff! It would also be great to be able to use distilled models. I believe this is possible for the encoder, but for the decoder a language head must be added.

Since DistilBert is implemented as its own model, and not as a BertModel, I don't think it's possible (or at least it's not easy) for the end user to do this. At least not loading pretrained models, since any pretrained model needs to be a type approved by `AutoModelForCausalLM`.

## Motivation

Same motivation as using distilled models in general. Same results at higher speed, this time applied to an `EncoderDecoder` model.

## Your contribution

Happy to be an alpha tester for this feature

### PR DESCRIPTION
**Pull request by leonjovanovic**
# What does this PR do?

Similar to the BertLMHeadModel this PR aims to add a DistilBertForCausalLM model in modeling_distilbert.py.

Fixes https://github.com/huggingface/transformers/issues/7397

Replaces https://github.com/huggingface/transformers/pull/8387, https://github.com/huggingface/transformers/pull/11085

## Who can review?

@patrickvonplaten
@ArthurZucker
@younesbelkada

### CODE REVIEW

**Comment by sgugger** [comment]
There is no checkpoint available for this task and DistilBERT, which is an encoder model. What is your usecase for adding this?

**Comment by leonjovanovic** [comment]
> There is no checkpoint available for this task and DistilBERT, which is an encoder model. What is your usecase for adding this?

@sgugger To fine-tune DistilBERT models for text generation with EncoderDecoder class.

**Comment by sgugger** [comment]
How is it different than using BERT?

**Comment by leonjovanovic** [comment]
@sgugger 
@patrickvonplaten
@ArthurZucker
@younesbelkada

Anyone looking at this?

**Comment by sgugger** [comment]
Those are not changes we want everyone to have in the distilBERT: it makes the model code too unreadable just so that you can use it in the EncoderDecoder framework. We can leave the fork open if you want to share it with others, and you can also push it in any repo on the Hub using the dynamic code feature.

**Pull request closed without merging**
