### PR TITLE
exclude jit time from the speed metric calculation of evaluation and …

### PR DESCRIPTION
**Pull request by sywangyi**
…prediction

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

### CODE REVIEW

**Comment by sywangyi** [comment]
@sgugger @jianan-gu  please have a review

**Review by sgugger — COMMENTED** [review]
Thanks for your PR. Could you just change the name of the metric added to `jit_compilation_time`? I find `jit_runtime` a bit unclear.

**Comment by sywangyi** [comment]
@sgugger done, please have a review of it.

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Pull request merged**
