### PR TITLE
Attempt at a temporary fix on `model_max_length` for roberta and Camembert variants

### LINKED ISSUE #8117: fast tokenizer issue on most user uploaded models
## Environment info

- `transformers` version: 3.4.0
- Platform: Linux-5.8.0-25-generic-x86_64-with-glibc2.32
- Python version: 3.8.6
- PyTorch version (GPU?): 1.6.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help
@mfuntowicz @julien-c
 
## Information

Found the bug on `camembert/camembert-base-ccnet` but probably common to many models uploaded by users.
On camembert base model, it works out of the box (there is no bug).

## To reproduce

Since `tokenizer` 0.9, it's possible to load the many unigram based tokenizers with the fast Rust implementation.  
It appears that the file `tokenizer_config.json` of some of them is not up to date, in particular the information `"model_max_length": 512` is missing.

Because of that, the value of `model_max_length` is a very big integer.

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("camembert/camembert-base-ccnet", use_fast=True)
tokenizer.model_max_length
# Out[4]: 1000000000000000019884624838656
```

To fix it, the field model_max_length has to be added to the config file.

## Expected behavior

I would expect `tokenizer.model_max_length` to be equal to 512.

### PR DESCRIPTION
**Pull request by Narsil**
- The issue is that this information is not contained in the
`tokenizer` config file.
- It used to be harcoded already (with 512 value too).
- It is unclear right now how to "properly" fix it.

# What does this PR do?

Fixes #8117  (tentatively) (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to the it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@LysandreJik

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
I see nothing wrong with this, but wouldn't this already be the case when loading with `from_pretrained`?

**Comment by Narsil** [comment]
No, `model_max_length` is not defined in the `tokenizer.json` for these models so truncation is off, or fails at inference in the model.

**Comment by thomwolf** [comment]
Well we also load the `transformers` specific configuration with `from_pretrained`, not only the `tokenizers` file (because We have additional attributes in `transformers`). It should be in this configuration file. I’ll take a look.

**Comment by Narsil** [comment]
Okay, I'll wait @thomwolf for your advice on this then.

**Comment by Narsil** [comment]
Stale

**Comment by Narsil** [comment]
Too old

**Pull request closed without merging**
