### PR TITLE
unpin torch

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

So we can use torch 2.2

### CODE REVIEW

**Comment by ydshieh** [comment]
Let's see what CI says.

**Comment by ydshieh** [comment]
The failing tests are already on `main`. I have no idea, but it's not from the torch 2.2.

https://app.circleci.com/pipelines/github/huggingface/transformers/83829/workflows/a864e1cf-46bc-4643-9a2f-9ba65ee7074e/jobs/1081960

Let's move on and check those tf/flax vs torch equivalence tests later

**Comment by ydshieh** [comment]
We are good to merge. The TF/Flax vs torch job is addressed

https://github.com/huggingface/transformers/pull/28898

**Review by amyeroberts — APPROVED** [review]
Thanks for handling all the version compatibility issues!

**Comment by ydshieh** [comment]
@amy

> Thanks for handling all the version compatibility issues!

Except ydshieh.__version__ ⬇️ 😫

**Pull request merged**
