### PR TITLE
Introduce logging_strategy training argument

### LINKED ISSUE #9838: logging_epochs argument for TrainingArguments
# 🚀 Feature request

There is no `logging_epochs` argument in `TrainingArguments`. When someone wants to train with `EvaluationStrategy.EPOCH`, he/she wants to see the logs after each epoch. Currently it is not possible. 

## Motivation

Better logging for training

## Your contribution

If I have time, I would like to add it. However, I am not available in a coming couple of weeks.

### PR DESCRIPTION
**Pull request by tanmay17061**
Introduce logging_strategy training argument
in TrainingArguments and TFTrainingArguments. (#9838)

# What does this PR do?

1. Introduce a `logging_strategy` argument in TrainingArguments.
2. Define a LoggingStrategy enumeration. This is similar to `EvalStrategy`.

Fixes #9838 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. [Link to issue](https://github.com/huggingface/transformers/issues/9838).
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

As changes in trainer: @sgugger

### CODE REVIEW

**Comment by tanmay17061** [comment]
Currently WIP.  
Thanks!

**Review by sgugger — COMMENTED** [review]
This is a useful addition but it needs to be backward compatible: this means the default should give the same behavior as before (which is not the case right now as highlighted by the failing tests) so "steps" for the default logging_strategy and keep the `eval_steps` default untouched either.

Could you amend your PR in that direction? Thanks!

**Comment by tanmay17061** [comment]
Thanks, yes that worked out!  
IMO, defaulting `eval_steps` to `logging_steps` is not a good decision any longer.  
With `logging_strategy` it seems more intuitive to me to decouple both. In case user chooses `logging_strategy="epoch"`, `logging_steps` is no longer a valid quantity.  
What is your take on this?

**Comment by sgugger** [comment]
> In case user chooses logging_strategy="epoch", logging_steps is no longer a valid quantity.

It will just be ignored in that case, so there is no weird behavior for the user.

**Comment by tanmay17061** [comment]
Sure! That makes sense.  
You can review the changes and let me know if any changes required.  
Thanks

**Review by sgugger — APPROVED** [review]
LGTM! I'm just wondering is we should add the `LoggingStrategy.NO` in case a user doesn't want any log since it comes for free (I don't think you'll need to change any line of code apart adding this to the enum).

This is because the next step is to do the same thing for saves (if you want to tackle it in a next PR!) which also would have the values steps/epochs/no so we could rename `EvaluationStrategy` to something more generic like `TimeInterval` (or any better name) which we would use for the evaluation strategy, saving strategy and logging strategy.

**Comment by tanmay17061** [comment]
Yes, something like `TimeInterval` (or `TimeStrategy`) will be a good generic enum.  
I can work on this generic enum and `saving_strategy` earlier next week most probably. Will raise a PR soon enough.  
For now I've made the amends to introduce `LoggingStrategy.NO`.

**Comment by sgugger** [comment]
Great! We can merge this in the meantime.
Looking forward to your next PR!

**Pull request merged**
