### PR TITLE
Typo in mlx tensor support

### PR DESCRIPTION
**Pull request by pcuenca**
# What does this PR do?

https://github.com/huggingface/transformers/pull/29406 recently added MLX tensor support to `BatchEncoding`. However, I think there's a typo in `_is_mlx` when importing the `mlx.core` module. 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

cc @Y4hL for verification

### CODE REVIEW

**Comment by Y4hL** [comment]
Yeah, it's a typo

**Review by amyeroberts — APPROVED** [review]
Thank for fixing! 

Reviewing in place of @ArthurZucker as I'm watching the repo now :)

**Comment by pcuenca** [comment]
Merged `main` to pull 4ed9ae623 and fix the failing test.

**Review by ArthurZucker — APPROVED** [review]

**Comment by pcuenca** [comment]
Feel free to merge whenever (I can't do it) :)

**Pull request merged**
