### PR TITLE
Remove mentions of models in the READMEs and link to the documentation page in which they are featured.

### PR DESCRIPTION
**Pull request by LysandreJik**
This aims to reduce the number of files that should be changed on each model contribution.

cc @ArthurZucker @amyeroberts

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Let's remove the tasks as well

**Comment by LysandreJik** [comment]
cc @stevhliu FYI

**Review by amyeroberts — APPROVED** [review]
Clean clean clean 🧹 🧹 🧹

**Comment by LysandreJik** [comment]
Thanks @amyeroberts!

**Pull request merged**
