### PR TITLE
Fixed bug Issue, where kernel functions were missing

### PR DESCRIPTION
**Pull request by adv-11**
# What does this PR do?

Hey everyone!

In this PR, I’ve added some new CUDA kernels to handle sparse matrix operations. These include functions for index_max, mm_to_sparse, sparse_dense_mm, reduce_sum, and scatter. I’ve written them in a new folder called custom_kernels inside the kernel directory.

Here’s a quick breakdown of what I’ve done:

Added kernels.cu to implement the CUDA kernels.
Created cuda_launch.h to declare the kernel functions.
Added sparse_kernels.cpp to bind the CUDA kernels to PyTorch using the pybind11 extension.
Updated setup.py to include the new custom kernel files so they compile correctly.
These new kernels should help with sparse matrix operations, and I’ve tried to keep the code modular in case we need to expand on it later.

Would love feedback on the implementation, and I’m happy to make any adjustments! Thanks for reviewing 😊

Fixes # (  Link :  https://github.com/huggingface/transformers/issues/33856) 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [✓ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ✓] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.

     Link :  https://github.com/huggingface/transformers/issues/33856
      
- [ ✓] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? : not req

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by akshit397a — APPROVED** [review]
Changes are up to the mark!

**Review by adv-11 — COMMENTED** [review]
should be fine to directly merge with any branch

**Comment by adv-11** [comment]
> Changes are up to the mark!

Thanks! this was my first PR, hope it gets approved tho

**Review by ArthurZucker — COMMENTED** [review]
Hey! 
Thanks for contributing! In general we avoid having kernels in `transformers` as our primary goal is to have general torch support for models. 

We usually rely on `torch.compile` for compiling torch to graphs 🤗 

Also if these are not used in any `modeling_xxx.py` then not entirely convinced of their utility to live in transformers!

**Comment by adv-11** [comment]
closing PR, if want to re open let me know

**Pull request closed without merging**
