### PR TITLE
Replace jnp.DeviceArray with jax.Array in FLAX models

### PR DESCRIPTION
**Pull request by akhilgoe**
## What does this PR do?

Recent JAX versions have dropped support for jax.numpy.DeviceArray. Many FLAX models refer to jax.numpy.DeviceArray which causes a crash. This PR replaces all references to jax.numpy.DeviceArray with jax.Array.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @sanchit-gandhi

### CODE REVIEW

**Comment by akhilgoe** [comment]
@sanchit-gandhi Can you please review this PR? Thanks!!

**Comment by sanchit-gandhi** [comment]
Thanks for the fix @akhilgoe - believe this is a duplicate of #24875?

**Comment by akhilgoe** [comment]
> Thanks for the fix @akhilgoe - believe this is a duplicate of #24875?

Yes correct!

**Comment by sanchit-gandhi** [comment]
If it's okay with you can we give @mariecwhite the opportunity to finish their PR since they've worked on it since last week? (should be merged asap, just requires CircleCI authentication)

**Comment by mariecwhite** [comment]
I'm still running into CircleCI issues with https://github.com/huggingface/transformers/pull/24875. Feel free to merge this PR instead.

**Comment by akhilgoe** [comment]
Hey guys...Thanks for the update! I don't have a preference, We can use either of the 2 PRs.

**Comment by akhilgoe** [comment]
Closing since the fix has been merged. Thanks!

**Pull request closed without merging**
