### PR TITLE
Transformer-XL: Improved tokenization with sacremoses

### LINKED ISSUE #5136: Transformer-XL tokenizer cannot properly tokenize brackets
# 🐛 Bug

## Information
The `TransfoXLTokenizer` is not able to tokenize words with surrounding brackets correctly. I compared it with the `BertTokenizer` from `bert-base-uncased` which gives the expected result. Example text is: `"Hello (bracket)"`

Model I am using: **Transformer-XL**

Language I am using the model on: **English**

The problem arises when using:
* [x] my own modified scripts

## To reproduce

```python
from transformers import BertTokenizer, TransfoXLTokenizer

bert = BertTokenizer.from_pretrained('bert-base-uncased')
transfoxl = TransfoXLTokenizer.from_pretrained('transfo-xl-wt103')

def test_bracket(tokenizer):
    enc = tokenizer.encode("Hello (bracket)")
    dec = tokenizer.decode(enc)
    print(f"ORG: Hello (bracket)\nENC: {enc}\nDEC: {dec}")
```
Results:  
`test_bracket(bert)` gives the following output:
```
ORG: Hello (bracket)
ENC: [101, 7592, 1006, 21605, 1007, 102]
DEC: [CLS] hello ( bracket ) [SEP]
```

`test_bracket(transfoxl)` gives the following output:
```
ORG: Hello (bracket)
ENC: [14049, 24]
DEC: Hello <unk>
```
If the parameter `add_space_before_punct_symbol=True` is passed, then the result is:
```
ORG: Hello (bracket)
ENC: [14049, 24, 21]
DEC: Hello <unk> )
```

## Expected behavior
The `TransfoXLTokenizer` should detect the punctuation symbols, e.g. `(`, separately and thus give the same result as the `BertTokenizer` (except the special tokens of course): `hello ( bracket )`

## Environment info

     
- `transformers` version: 2.11.0
- Platform: Windows-10-10.0.18362-SP0
- Python version: 3.6.10
- PyTorch version (GPU?): 1.4.0 (False)
- Tensorflow version (GPU?): 2.1.0 (False)

### PR DESCRIPTION
**Pull request by RafaelWO**
Fixes #5136

As explained in the above issue, this PR fixes the tokenization of the TransfoXLTokenizer by using the sacremoses library with an extended feature of tokenizing comma-separated and floating point numbers. That way the input text is tokenized the same way as in the WikiText-103 dateset used for pretraining.

Changes in a nutshell:
 * The TransfoXLTokenizer is now using sacremoses for tokenization
 * Added tokenization of comma-separated and floating point numbers.
 * Removed prepare_for_tokenization() from tokenization_transfo_xl.py because punctuation is handled by sacremoses
 * Added corresponding tests
 * Removed test comapring TransfoXLTokenizer and TransfoXLTokenizerFast (as discussed in #5302)
 * Added deprecation warning to TransfoXLTokenizerFast (as discussed in #5302)

@TevenLeScao

### CODE REVIEW

**Comment by RafaelWO** [comment]
`ci/circleci: check_code_quality` fails for me due to Python 3.6 is not compatible with PyTorch 1.6. Any ideas how to fix this?

**Comment by LysandreJik** [comment]
Pinging @n1t0 and @TevenLeScao (in holidays right now, will be back next week!)

**Comment by TevenLeScao** [comment]
Resolved a small conflict, LGTM!

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
