### PR TITLE
Fix AdamWeightDecay for TF 2.11

### LINKED ISSUE #20724: Tutorial on token classification throws casting error in Tensorflow 2.11
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
- Python version: 3.9.0
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): not installed (NA)
- Tensorflow version (GPU?): 2.11.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker @younesbelkada, the tutorial at `https://huggingface.co/docs/transformers/tasks/token_classification` throws the following  error in Tensorflow 2.11 but not in Tensorflow 2.9: 

`(0) UNIMPLEMENTED:  Cast string to float is not supported
	 [[{{node Cast_1}}]]
  (1) CANCELLED:  Function was cancelled before it was started
0 successful operations.
`

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The tutorial at `https://huggingface.co/docs/transformers/tasks/token_classification` for Tensorflow

### Expected behavior

Training should start, but it does not.

### PR DESCRIPTION
**Pull request by Rocketknight1**
Fixes #20724

### CODE REVIEW

**Comment by Rocketknight1** [comment]
@gante take a quick look at this one too, please! Our `AdamWeightDecay` doesn't work with the new Optimizer base class in TF 2.11, so I moved it onto the legacy class for now. When I have more time I should clean this up properly, and possibly just use [the official AdamW](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/experimental/AdamW) instead.

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Comment by el-profesor-04** [comment]
The same issue occurred with the Summarization tutorial. [https://huggingface.co/course/chapter7/5?fw=tf#models-for-text-summarization](url)

**Comment by Rocketknight1** [comment]
Thanks @el-profesor-04 - can you confirm that the issue goes away with you install the latest version of `transformers` from main with `pip install --upgrade git+https://github.com/huggingface/transformers.git`?

**Pull request merged**
