### PR TITLE
fix bug in group_texts function, that was inserting short batches

### LINKED ISSUE #23424: group_texts function produces batches with length shorter than block_size
### System Info

- `transformers` version: 4.28.1
- Platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.10.0
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 1.12.1+cu102 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

_No response_

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

There's a  bug in the PyTorch language_modeling examples: 
for example: [run_clm.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm.py)

The `group_texts` function is supposed to group the data into batches of equal sizes to `block_size`, and to ignore the small remainder chunk. There's a bug and instead, it inserts the last batch with a smaller size, which creates an error, as the model takes in data with equal sequence length. 

### Expected behavior

The expected behavior is for the function to return data with equal sequence lengths for all batches.

### PR DESCRIPTION
**Pull request by bodasadallah**
# What does this PR do?

Fixes #23424

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger @ArthurZucker

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Thanks for your PR but this will actually drop a full batch in all cases where `total_length >= block_size` just to support `total_length < block_size`. So we won't change the code like this, you should probably use a dataset that has longer texts, or adapt the preprocessing to suit your needs on your copy of the example file.

**Comment by BodaSadalla98** [comment]
You are right, my bad!

What about if we made it like this:
```python 
 k: [t[i : i + block_size] for i in range(0, total_length - block_size + 1, block_size)]
```
this way, we will not drop an entire batch when `total_length >= block_size` , and at the same time we will return an empty batch, in the case where `total_length < block_size`.

the issue with the code now is that it allows for some samples to have `sequence_length < block_size`, which throws an error when the `data_collator` tries to convert the batches into tensors. 

`batch[k] = torch.tensor([f[k] for f in features])
ValueError: expected sequence of length 128 at dim 1 (got 94)`

**Comment by sgugger** [comment]
Won't the empty block cause you the same error though?

**Comment by BodaSadalla98** [comment]
The empty entries are removed and aren't there anymore after the mapping with `group_texts` happens. Even though I don't know why the `map` function removes empty entries. 

I tried to replicate it here: 

```python 
def gen():
    yield {"id": [1,2,3]}
    yield {"id": [1]}
ds = datasets.Dataset.from_generator(gen)
def remove_short(example):
    if len(example['id']) < 2:
        example['id'] =  []
    return example
c = ds.map(remove_short)
for cc in c:
    print (cc)
```
but got the output: 

```
{'id': [1, 2, 3]}                                                                                                                                                
{'id': []} 
```
I don't know why does it removes the empty batch in the training script, and not here.

**Comment by sgugger** [comment]
We can also just remove the test which is how the script was originally written. The problem is that it then caused issues with users having a small dataset (see #12438).

So all in all there is always going to be one group of users not happy since there is no good solution. This script is primarily intended for training, so it just shouldn't be executed on a small dataset :man_shrugging:

**Comment by BodaSadalla98** [comment]
This will only fail when the dataset has only one batch, and the total_length  < block_size.  But I don't think that's a valid case. So, I think we should just adjust for the normal case where we have many batches, but sometimes one batch would be too short that we need to exclude it,  instead of returning a batch with shorter length, that will cause an error.

**Comment by sgugger** [comment]
True. So let's go with removing the test at line 496 (and unindent `total_length = (total_length // block_size) * block_size`).

**Comment by sgugger** [comment]
This PR is fine, and yes please treat other examples the same way.

**Review by sgugger — APPROVED** [review]
Thanks for iterating on this! Can you just run `make style` on your branch to get the quality check passing?

**Comment by BodaSadalla98** [comment]
yes, I did it pushing now

**Pull request merged**
