### PR TITLE
Add GPTJForQuestionAnswering

### PR DESCRIPTION
**Pull request by tucan9389**
# What does this PR do?

- Add `GPTJForQuestionAnswering` class for GPTJ upstream and QA downstream task

Fixes # (issue)

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten, @LysandreJik
@sgugger, @patil-suraj

### CODE REVIEW

**Comment by tucan9389** [comment]
Hi, @sgugger and @patrickvonplaten again.
Like the https://github.com/huggingface/transformers/pull/13290 PR that I made before, I made QA for GPT-J class and made this PR for that.
If you have time, I'd appreciate your review and feedback on it.

**Comment by LysandreJik** [comment]
This seems good to me - @patil-suraj, do you mind taking a look at this?

**Review by sgugger — APPROVED** [review]
Thanks for adding this new model!

**Comment by patrickvonplaten** [comment]
Looks good to me as well! @patil-suraj - could you also take a quick look? :-)

**Review by patrickvonplaten — APPROVED** [review]

**Review by patil-suraj — APPROVED** [review]
Thank you for adding this model!

**Comment by sgugger** [comment]
Thanks again for your PR!

**Pull request merged**
