### PR TITLE
fix: Update run_qa.py to work with deepset/germanquad

### PR DESCRIPTION
**Pull request by sjrl**
# What does this PR do?
This updates the `run_qa.py` script in the `examples/pytorch/question-answering` folder to work with the `deepset/germanquad` dataset. The script expects the ID field for each example in the dataset to be a string type, but the previously mentioned dataset stores the ID field as an int. So I added a `str` call on the id field to make sure any integer IDs are converted into the expected string format for squad datasets when using the `evaluate` library. This is relevant for https://huggingface.co/datasets/deepset/germanquad which stores the IDs of each example with an integer ID.

Fixes #N/A

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Hey @sgugger I would appreciate your review on this PR! I tagged you based on the recommendation of the PR template since you are listed as the maintainer of the pytorch examples.

### CODE REVIEW

**Comment by sgugger** [comment]
Could you explain what fails when leaving the code as is?

**Comment by sjrl** [comment]
Sure! I get a `pyarrow` error that the format of `predictions` does not match the defined schema for `predictions` which expects the ID field to be of type string. I'm a bit busy at the moment, but later I can reproduce the error and copy paste the message here.

**Comment by sgugger** [comment]
That's is a bit weird as we only use pyarrow through `dataset` but this is after the dataset creation.

**Comment by sgugger** [comment]
Ah good catch! Yes I get the issue now.

**Review by sgugger — APPROVED** [review]

**Pull request merged**
