### PR TITLE
Rename method to avoid clash with property

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Fixes a bug when the `self.rescale` method was being called, but `self.rescale` was set as a property. This arose after a refactoring of the feature extractors in my PR: https://github.com/huggingface/transformers/pull/18499, causing an issue in any model that had `rescale` as a property in its config. Renaming considered safe as the new `rescale` method was introduced yesterday. 

Issue raised by user here: https://github.com/huggingface/transformers/commit/49e44b216b2559e34e945d5dcdbbe2238859e29b#comments
and caught in doctests. 

Renames the method to be less ambiguous. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by amyeroberts** [comment]
The layoulmv2 and layoutlmv3 tests appear to be failing due to an issue when importing from the [detectron2](https://github.com/facebookresearch/detectron2) package. 

When `from detectron2.modeling import META_ARCH_REGISTRY` is called, it fails with the error `ImportError: cannot import name 'is_fx_tracing' from 'torch.fx._symbolic_trace'`. This has been reported by other users of the library - see [commit comments](https://github.com/facebookresearch/detectron2/commit/36a65a0907d90ed591479b2ebaa8b61cfa0b4ef0#comments).

**Review by ydshieh — COMMENTED** [review]
Looks good to me, but I am wondering where is the property that clash with the method?

**Review by alaradirik — APPROVED** [review]
Thank you! This fixes the OWL-ViT error too

**Comment by amyeroberts** [comment]
@ydshieh I believe it comes from the `preprocessor_config.json` file: https://huggingface.co/google/owlvit-large-patch14/blob/main/preprocessor_config.json.

**Comment by alaradirik** [comment]
> @ydshieh I believe it comes from the `preprocessor_config.json` file: https://huggingface.co/google/owlvit-large-patch14/blob/main/preprocessor_config.json.

I will update the `preprocessor_config.json` files, the rescale argument is not used anymore.

**Review by ydshieh — APPROVED** [review]
Thanks for the fix. As this `rescale` method is newly introduced (yesterday), good for me to rename it.

It would be nice/helpful to mention this (and a link to the PR that added this method) in this PR description.

**Comment by amyeroberts** [comment]
@ydshieh Yep - will do!

**Review by LysandreJik — APPROVED** [review]
I think there was an issue with the merge as some changes unrelated to your PR appear in the filed changed, but sounds good to me to rename to `rescale_image` so as to not interfere with existing config values.

**Pull request merged**
