### PR TITLE
Added translation of installation.mdx to Portuguese Issue #16824

### PR DESCRIPTION
**Pull request by rzimmerdev**
# What does this PR do?

Creates folder pt in docs/source for translating documentation to Portuguese
Currently, only the installation.mdx file was translated as of this PR.

Fixes issue #16824

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

### CODE REVIEW

**Comment by rzimmerdev** [comment]
I'm still working on translating the remaining files, although there's already some work done on three files.

**Comment by LysandreJik** [comment]
Maybe @gante ? :smile:

**Review by omarespejel — APPROVED** [review]
This is amazing @rzimmerdev! Thank you 🤗

**Comment by omarespejel** [comment]
Obrigado @rzimmerdev! @sgugger, LGTM. Ready to merge and start the Portuguese docs 🤗

**Review by sgugger — APPROVED** [review]
Thanks a lot for working on this!

**Pull request merged**
