### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by redewiedergabe**
added documentation for our fine-tuned BERT model

### CODE REVIEW

**Comment by julien-c** [comment]
Can you please add a 

```
---
language: german
---
```
metadata block at the top of the file? 

Also, cc'ing @severinsimmler who might be interested in this (if you guys don't know each other already)

**Comment by redewiedergabe** [comment]
Hey! I added the metablock.

One question: We uploaded our models as described in the huggingface documentation and everything looks okay, but when we try to test them with the suggested code, we get a message that the model is not found (OS Error: Model name was not found in tokenizers model name list). Could you please check if we made some error?

this is the test code we used:

> tokenizer = AutoTokenizer.from_pretrained("redewiedergabe/bert-base-historical-german-rw-cased")

**Comment by severinsimmler** [comment]
Hi @redewiedergabe,

I can't reproduce your error on `transformers` 2.7.0, Python 3.7.6 and macOS 10.15.4. Does loading the model with `AutoModel` work?

**Comment by julien-c** [comment]
works for me too

**Comment by julien-c** [comment]
Thanks! [Model page](https://huggingface.co/redewiedergabe/bert-base-historical-german-rw-cased)

**Pull request merged**
