### PR TITLE
[Examples] Check key exists in datasets first

### PR DESCRIPTION
**Pull request by oToToT**
# What does this PR do?

Correctly check the key exists before accessing it in some example scripts. I guess this is probably a mistake when writing example scripts.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?  

No tests since I didn't see any tests related to examples. Maybe someone could point it out for me.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

Probably @bhadreshpsavani would like to review this according to the log from `git blame`.
Or @sgugger, @patil-suraj as this is about examples.

### CODE REVIEW

**Comment by bhadreshpsavani** [comment]
Hi @oToToT,
Thanks for the PR, The changes seem valid to me. It should be as per changes
@sgugger what's your view on these changes?

**Review by sgugger — APPROVED** [review]
Thanks for fixing, it's better this way indeed!

**Comment by oToToT** [comment]
Hi, @sgugger
I'm not familiar with how huggingface do with pull requests, did I miss something to make it be merged?
Or I just need to stay and wait it.

Thanks!

**Comment by sgugger** [comment]
Thanks for the ping! I just forgot to click the merge button 🤦

**Pull request merged**
