### PR TITLE
[TTA Pipeline] Test MusicGen and VITS

### PR DESCRIPTION
**Pull request by sanchit-gandhi**
# What does this PR do?

Add tiny-random pipeline tests for MusicGen and VITS

### CODE REVIEW

**Review by ylacombe — APPROVED** [review]
LGTM, thanks !

**Review by ArthurZucker — APPROVED** [review]
Nice! Thanks for the nit

**Comment by ydshieh** [comment]
In order to make pipeline tests (those with tiny models) work, the tiny model should be in the file `tests/utils/tiny_model_summary.json`.

So far `MusicgenForConditionalGeneration` is on the Hub but not in this file. Same for `hf-internal-testing/tiny-random-VitsModel`.

I will update this file later.

**Comment by ydshieh** [comment]
Hi @sanchit-gandhi 

It is mentioned in [our internal notion doc](https://www.notion.so/huggingface2/Pipeline-Testing-in-transformers-87c5f26a2c3847ada94935878b77cc34#e2be051c13784bf8a459fd95674b1724)

> - The file [[**tests/utils/tiny_model_summary.json](https://github.com/huggingface/transformers/blob/main/tests/utils/tiny_model_summary.json)](https://github.com/huggingface/transformers/blob/main/tests/utils/tiny_model_summary.json)** needs to be updated with the information about the new tiny models created/uploaded in the previous step.

~ 1 year ago, we decided to make pipeline testing to use tiny models on `hf-internal-testing` (rather than creating them on the fly during testing). For some technical reasons, CI needs to access to `tiny_model_summary.json` which should be updated whenever some new architectures are available. Currently I check the results on a GitHub Action workflow once every 1 or 2 months and update this file.

**Comment by sanchit-gandhi** [comment]
Amazing! Thank you for the information 🤗

**Pull request merged**
