### PR TITLE
Remove accelerate from tf test reqs

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

This PR removes `accelerate` from the tf example test requirements as I believe its unused and causing issues with the `Accelerate` integration

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@Rocketknight1, @sgugger

### CODE REVIEW

**Comment by muellerzr** [comment]
While the tests aren't being ran here, I did run it on the branch I'm working on (that doesn't touch tf code) and it still passes (and passes now): 
image

**Review by sgugger — APPROVED** [review]
Thanks!

**Comment by muellerzr** [comment]
Per conversation with @Rocketknight1, not merging this because it actually makes the TF example tests fail. However since they were not run here, we can't test that.

**Comment by Rocketknight1** [comment]
This should work now after you rebase on main!

**Pull request merged**
