### PR TITLE
Fix default revision for pipelines

### LINKED ISSUE #33365: Pipelines download the latest revision by default instead of the default/output revision
### System Info

- `transformers` version: 4.44.2
- Platform: macOS-14.6.1-arm64-arm-64bit
- Python version: 3.12.5
- Huggingface_hub version: 0.24.5
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.3.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using distributed or parallel set-up in script?: no

### Who can help?

@Narsil 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier("We are very happy to show you the 🤗 Transformers library.")
```

outputs

```text
No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
```

However, it downloads the `main` revision instead of `af0f99b`.

From what I can tell, this happens with all of the pipelines.

Edit: I believe it was broken in dc9147ff362e4e69829f64d28178c77cab4bef6f shortly after being added (e4d2588573f2c68eb792f2d11f092eb2c562bef5)

### Expected behavior

The downloaded revision is consistent with the output.

Adding `revision` to `hub_kwargs`  seems to fix it, but it'd probably be good to update the defaults to the latest version of each model (since that's the current behavior).

```diff
--- a/src/transformers/pipelines/__init__.py
+++ b/src/transformers/pipelines/__init__.py
@@ -860,6 +860,7 @@ def pipeline(
             f" {revision} ({HUGGINGFACE_CO_RESOLVE_ENDPOINT}/{model}).\n"
             "Using a pipeline without specifying a model name and revision in production is not recommended."
         )
+        hub_kwargs['revision'] = revision
         if config is None and isinstance(model, str):
             config = AutoConfig.from_pretrained(model, _from_pipeline=task, **hub_kwargs, **model_kwargs)
             hub_kwargs["_commit_hash"] = config._commit_hash
```

### PR DESCRIPTION
**Pull request by ankane**
# What does this PR do?

Fixes #33365

I've updated the default models to use the latest revision since that's been the behavior of every released version (see the issue above for details).

## Before submitting

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@LysandreJik  @Narsil

### CODE REVIEW

**Review by Rocketknight1 — APPROVED** [review]
This looks good! (aside from the CircleCI failure, but that's not your fault)

@ankane I'm happy to merge this as-is, but while you're fixing up the default models in the pipelines, would you be willing to help out with a slightly larger project? We were discussing the outdated default models in the pipelines internally, and one project that's been on the list for a while has been to go through them and see if there are any improved defaults. 

For example, for a task like visual question answering, the current `vilt-b32-finetuned-vqa` could probably be replaced with one of the recent 2B `Qwen-VLM` models, or `distilbert` could be replaced with `deberta`. If you wanted to do some of that work in this PR, I think it could be really useful to the community, but don't stress if you'd prefer to keep this PR simple and not take on the bigger job!

**Comment by ankane** [comment]
Thanks @Rocketknight1. I'd prefer to keep this one simple.

**Comment by ankane** [comment]
Just updated, but still getting a `Could not find a usable config.yml` CircleCI failure.

**Comment by LysandreJik** [comment]
Hey @ankane, thanks for your PR! Could you try following the steps highlighted here to see if it fixes it? https://support.circleci.com/hc/en-us/articles/12504745606171-Why-am-I-seeing-the-Could-not-find-a-usable-config-yml-you-may-have-revoked-the-CircleCI-OAuth-app-message

**Comment by ankane** [comment]
Hi @LysandreJik, I'm not sure I have an active CircleCI account. If one is needed to contribute, will close this out.

**Comment by LysandreJik** [comment]
I think I can help this pass by just pushing your branch elsewhere; let me do that quickly.

**Comment by LysandreJik** [comment]
I pushed it here manually https://github.com/huggingface/transformers/compare/pipeline-revision-mirror?expand=1

and it launched the tests. Sorry this happens here, it's CircleCI being annoying.

@Rocketknight1 in case this happens elsewhere, this is what I did here:

```
git remote add ankane https://github.com/ankane/transformers
git fetch ankane
git checkout pipeline-revision
git checkout -b pipeline-revision-mirror
git push -u origin pipeline-revision-mirror
```

**Review by LysandreJik — APPROVED** [review]

**Comment by LysandreJik** [comment]
I'll let @Rocketknight1 double check and merge if happy.

**Comment by Rocketknight1** [comment]
Yes, look good to me, and CI is green now. Thank you for the PR!

**Comment by ankane** [comment]
Thanks

**Pull request merged**
