### PR TITLE
move wandb/comet logger init to train() to allow parallel logging

### PR DESCRIPTION
**Pull request by krfricke**
Moving the logger setup to the `train()` function allows parallel runs (e.g. in hyperparameter search) to log each run individually.

Alternative to #6791

### CODE REVIEW

**Comment by borisdayma** [comment]
I don't think you want to do the logger setup within `train` as users can call `Trainer` for evaluation only as well.
It probably needs to stay within `__init__` but should also go into a hyperparameter search function, maybe `_objective`.

What's important is for loggers to setup at `__init__` and at each parameter search.

However @sgugger will have a better idea in how to organize this function.

**Comment by sgugger** [comment]
Yes, the train method could be called several times on the same Trainer, or the Trainer could be used for evaluation only, and those logging platforms should be setup once only, so the init looks best. Maybe we could add a private attribute `_has_been_setup` that could be checked inside the log method before reporting to wandb/comet and call the setup method if needed? Would that work for the hp search with Ray?

**Comment by krfricke** [comment]
That sounds good. Should it still be setup in the init then? For hyperparameter search this doesn't really make sense (and creates an "empty" run in wandb), and if it is setup on logging calls anyway we wouldn't necessarily need it there. But happy to leave it there, too.

**Comment by sgugger** [comment]
We can leave the setup to the first time we try to log something or the first call to train then (if there is a check to the same flag, we can call the setup method several times safely).

**Comment by borisdayma** [comment]
I think the first time we try to log makes sense, and also allow to use `Trainer` in eval only.

If people just want to call multiple times `train`, it would be nice if it was straightforward for them to choose between logging to the same run or logging to a new run. Hyperparameter search would obviously automatically choose to log to a new run.

Note that logging several `train` calls to the same run is actually not currently supported due to `global_step` being reset to 0 [here](https://github.com/huggingface/transformers/blob/54cfefc2ac9e3e1c0968a2ed0dd3c711eee76196/src/transformers/trainer.py#L645) which will cause issues at least in both Tensorboard and W&B.

**Comment by krfricke** [comment]
I adjusted the PR so the loggers will be initialized on the first call to `log()`. Is this what you had in mind?

**Comment by krfricke** [comment]
Okay, so the current position is good? (When clicking the "Files changed" link it looks like it's in `_hp_search_setup`, but it's actually right at the beginning of `log`)

**Comment by borisdayma** [comment]
Looks great!

**Comment by sgugger** [comment]
Oh yeah, sorry I looked too fast. LGTM!

**Pull request merged**
