### PR TITLE
Code refactor for nested conditional statements

### PR DESCRIPTION
**Pull request by YeonwooSung**
# What does this PR do?

Simple code refactoring for "src/transformers/hf_argparser.py" and "src/transformers/image_utils.py".

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [v] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [v] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! Would recommend you to install `ruff==1.5` to make sure some of the quality check pass. Not against refactoring as long as the CI are all green!

**Comment by YeonwooSung** [comment]
> Hey! Would recommend you to install `ruff==1.5` to make sure some of the quality check pass. Not against refactoring as long as the CI are all green!

Thanks. Will definitely try this!

**Review by ArthurZucker — COMMENTED** [review]
hey! this doesn't seem to improve readability so won't accept it sorry!

**Comment by YeonwooSung** [comment]
> hey! this doesn't seem to improve readability so won't accept it sorry!

Fair enough! Thanks. Will close this pull request, since this does not improve the readability

**Pull request closed without merging**
