### PR TITLE
rag import not on windows

### PR DESCRIPTION
**Pull request by flozi00**
just a small fix to use automodels on windows
faiss is not available on windows, and RAG is using faiss, so the import fails

### CODE REVIEW

**Comment by LysandreJik** [comment]
There's a lot of changes relative to `black` - could you install the version the repo uses with:
```
pip install -U -e .[quality]
```
?


Also I would put this behind a `if is_faiss_available():` rather than a platform check. Could you show the error you obtain on Windows when using an auto model?

**Comment by flozi00** [comment]
> Also I would put this behind a `if is_faiss_available():` rather than a platform check. Could you show the error you obtain on Windows when using an auto model?

how should that looks like ?
putting faiss import into try catch block ?

the error is an "dll not found error" on windows

```
from transformers import ViTFeatureExtractor, ViTForImageClassification, AutoModel, AutoTokenizer
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\__init__.py", line 2487, in __getattr__
    return super().__getattr__(name)
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\file_utils.py", line 1700, in __getattr__
    value = getattr(module, name)
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\file_utils.py", line 1699, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\models\auto\__init__.py", line 198, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\models\auto\modeling_auto.py", line 199, in <module>
    from ..rag.modeling_rag import (  # noqa: F401 - need to import all RagModels to be in globals() function
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\models\rag\modeling_rag.py", line 29, in <module>
    from .retrieval_rag import RagRetriever
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\models\rag\retrieval_rag.py", line 42, in <module>
    import faiss
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\faiss\__init__.py", line 17, in <module>
    from .loader import *
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\faiss\loader.py", line 39, in <module>
    from .swigfaiss import *
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\faiss\swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: DLL load failed while importing _swigfaiss: Das angegebene Modul wurde nicht gefunden.
```

**Comment by LysandreJik** [comment]
What is your transformer version? 
I see this in your stack-trace:
```
  File "C:\Users\flozi\anaconda3\envs\wav2vec\lib\site-packages\transformers\models\rag\retrieval_rag.py", line 42, in <module>
    import faiss
```
But this should be behind the `is_faiss_available()` statement:

https://github.com/huggingface/transformers/blob/db9dd09cf9d8f5de9a5293ec16e7b3d0c01dcbbb/src/transformers/models/rag/retrieval_rag.py#L31-L38

**Comment by flozi00** [comment]
latest release and master branche
then it looks like enviroment bug, I dont know which library did, but my pip freeze tells me faiss-cpu is installed on my notebook.
I removed and now it's working again, so closing this PR

**Pull request closed without merging**
