### PR TITLE
Doc: NLP tasks between NLU and Text Generation

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

As discussed [here](https://github.com/huggingface/transformers/pull/25240#issuecomment-1668029668), this PR splits the NLP task section in two:
- Moves generative tasks to the new text generation task section
- Renames NLP into NLU, which now holds non-generative tasks, for clarity

Related issue: #24575

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
I don't really understand that split especially when you see it written like this in the index. NLU and text generation are the same modality: text.

Speech has some generative tasks with speech to text and Computer vision will hold generative tasks at some point (like super-resolution) and we will also have multimodal tasks doing generative stuff (text to speech).

I would leave the index (which is copied from the main README by the way) as it is.

**Comment by gante** [comment]
@sgugger so like this?

(I thought it would make sense to keep a 1:1 correspondence between tasks and the information present in the index, but no strong feelings about it :) )

**Review by sgugger — APPROVED** [review]
You can add a note that this modality is split in two sections due to the number of tasks if you feel strongly.

**Review by stevhliu — APPROVED** [review]
Thanks, it looks good to me! 😄

**Review by patrickvonplaten — APPROVED** [review]

**Pull request closed without merging**
