### PR TITLE
Put all models in the constants

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

It was impossible to use all pretrained checkpoints in the tapas tokenzier file because they were not in the constants of the file. This PR fixes that.

### CODE REVIEW

**Comment by sgugger** [comment]
An alternative is to remove all content, but the previous state where one variable as some keys but the others no leads to failures.

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks @sgugger!

**Comment by julien-c** [comment]
Yes, we really need to remove all of this @LysandreJik @thomwolf

**Comment by LysandreJik** [comment]
We do, but right now we still use them in the tests

**Comment by NielsRogge** [comment]
It was a bit confusing to me which to add in the constants and which not.. 😅

**Comment by NielsRogge** [comment]
@sgugger one more small fix you can add is in tapas.rst under "Usage: inference", there should be one more space:

docs

**Comment by LysandreJik** [comment]
Pushing your fix on master directly Niels

**Pull request merged**
