### PR TITLE
Move test model folders

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

As discussed offline, this PR moves model specific test folders (e.g. `tests/bert`) to `tests/models` (e.g. `tests/models/bert`)

In addition to the necessary changes on `import`, the following changes are made:

- In some test files regarding processors (tokenizer/feature extractor, etc.), change
```
SAMPLE_ROBERTA_CONFIG = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".../fixtures/dummy-config.json")
```
to
```
SAMPLE_ROBERTA_CONFIG = get_tests_dir("fixtures/dummy-config.json")
```
(see [the commit](https://github.com/huggingface/transformers/pull/17034/commits/ee9956cf4181932c821d4c3c28677ac33660496a))

- The changes (**to be reviewed particularly**)

  - `.circleci/config.yml`
  - `.github/workflows/self-scheduled.yml`

  - `src/transformers/commands/add_new_model.py`
  - `src/transformers/commands/add_new_model_like.py`

  - `utils/check_repo.py`
  - `utils/notification_service.py`
  - `utils/test_fetcher.py`

### Remarks:

  - The `self-push` result is [here](https://github.com/huggingface/transformers/actions/runs/2256959215)
    - The slack report job has `Artifact was not found, job was probably canceled.`, but this issue exists for some time. My plan is to continue the task of changing self-push report format (and fix this issue)
    - The `run_tests_flax_gpu` failure is just the same as in other runs. This is not in the scope of this PR.
  - The scheduled CI (partial) result is [here](https://github.com/huggingface/transformers/actions/runs/2254833118). The report is available on Slack.
    - On the GitHub Actions page, the jobs have name like `Model tests (models/albert, single-gpu-docker)`. It becomes a bit long (with `models/`).
    - Same for the Slack report
        ```
        0 |         0 |         3 |         0 |         0 | models_auto
        ```
    - So far I only ran a subset of models. From the results, I think the PR is ready. We can run a full suite of tests before merge.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Impressive work! My only concern is on the changes in `self.scheduled.yml`, so I'd really like to launch that CI once and check everything is okay before we merge this.

**Review by LysandreJik — APPROVED** [review]
Very impressive PR, thanks @ydshieh!

If you're rebasing on `main` to take care of the conflicts, I would advocate to squash all of your commits in a single one, which means you'll only take care of the conflicts once (similarly to a merge). Having 32 commits to rebase on `main` must be hard :)

**Review by stas00 — APPROVED** [review]
Super awesome work, @ydshieh! Thank you!

I made a few minor optional suggestions if these resonate with you. But please feel free to ignore.

I wonder if this

https://github.com/huggingface/transformers/blob/1073f00d4ea3eae6279c80d311387012b20d0113/src/transformers/testing_utils.py#L960-L963

needs to have another level, or perhaps it's still reaching to the repo's root. I think I coded it originally to have some spare levels.

**Comment by ydshieh** [comment]
Hi, @stas00 Thank you for the feedbacks.

- Regarding `difficult to read` (the long command): totally agreed! I had the same feeling, and thought might be a good idea to create a tiny python script and just call it.
- About `parents[4]`: thank you for the information!
- I can check `TestCasePlus` later.

I would prefer to merge as it is now, and work on these points in another PR. The main reason is that I ran the full suite of tests, the results look all good, and would like to merge with a version that has been fully tested :-)

**Comment by ydshieh** [comment]
Merged now (after rebase on main for the merged `flax_bert` and `yolos` PRs).

**Pull request merged**
