### PR TITLE
Adds MuRIL - BERT based model for 17 Indian Languages to the library

### PR DESCRIPTION
**Pull request by ravi03071991**
# What does this PR do?

This PR adds a TensorFlow-based MuRIL model to the library. More details about the MuRIL model can be found [here](https://tfhub.dev/google/MuRIL/1).

Fixes: #9190
@LysandreJik @patrickvonplaten

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @ravi03071991, 

thanks a lot for the new model! There are quite some empty files in the PR - can we maybe delete those?

**Comment by patrickvonplaten** [comment]
From https://tfhub.dev/google/MuRIL/1 it seems that MuRIL is the same as BERT - do we need a new model class? It would be awesome if you could specify the differences between MuRIL and BERT in this PR :-)

**Comment by ravi03071991** [comment]
> Hey @ravi03071991,
> 
> thanks a lot for the new model! There are quite some empty files in the PR - can we maybe delete those?

Sure. We can delete them.

**Comment by mapmeld** [comment]
- I've posted an adapted MuRIL BERT model here https://huggingface.co/monsoon-nlp/muril-adapted-local
- Simran Khanuja has posted here https://huggingface.co/simran-kh/muril-cased-temp
- there is also https://huggingface.co/google/muril-cased/tree/main but it has no model files

Does this do the job?

**Comment by patrickvonplaten** [comment]
Hey @ravi03071991 and @mapmeld, 

So what I understand is that the model can be used with **no** code addition using `BertModel` and `BertTokenizer` - is this correct? I think in this case it does make more sense to just add a model to the model hub as it's done with this checkpoint: https://huggingface.co/monsoon-nlp/muril-adapted-local/tree/main 

Did you guys check whether the model works as expected? We could do some quick fine-tuning evaluation on the XTREME benchmark to make sure the model behaves correctly in transformers. We should get more or less the same results as shown on the tf-hub: https://tfhub.dev/google/MuRIL/1 . I think it'll be pretty easy to do some fine-tuning / evaluation by slightly adapting this notebooks: https://github.com/huggingface/notebooks/blob/master/examples/text_classification.ipynb to use the XTREME dataset from `datasets`: https://huggingface.co/datasets/xtreme . Would someone be interested in giving it a shot at making such a notebook?

I think with such a notebook, we can upload the pre-trained checkpoint to an "official" org name in the hub - probably `google/muril-bert-base` or something (google trained the model no?). Then we're happy to do some promotion on the model as well :-)

**Comment by ravi03071991** [comment]
> Hey @ravi03071991 and @mapmeld,
> 
> So what I understand is that the model can be used with **no** code addition using `BertModel` and `BertTokenizer` - is this correct? I think in this case it does make more sense to just add a model to the model hub as it's done with this checkpoint: https://huggingface.co/monsoon-nlp/muril-adapted-local/tree/main
> 
> Did you guys check whether the model works as expected? We could do some quick fine-tuning evaluation on the XTREME benchmark to make sure the model behaves correctly in transformers. We should get more or less the same results as shown on the tf-hub: https://tfhub.dev/google/MuRIL/1 . I think it'll be pretty easy to do some fine-tuning / evaluation by slightly adapting this notebooks: https://github.com/huggingface/notebooks/blob/master/examples/text_classification.ipynb to use the XTREME dataset from `datasets`: https://huggingface.co/datasets/xtreme . Would someone be interested in giving it a shot at making such a notebook?
> 
> I think with such a notebook, we can upload the pre-trained checkpoint to an "official" org name in the hub - probably `google/muril-bert-base` or something (google trained the model no?). Then we're happy to do some promotion on the model as well :-)

Sure. I am can take up the task of making the notebook.

**Pull request closed without merging**
