### PR TITLE
gpt-bigcode: avoid `zero_` to support Core ML

### PR DESCRIPTION
**Pull request by pcuenca**
# What does this PR do?

In-place `zero_` is not supported by the Core ML conversion process. This PR replaces it with `zeros_like` so conversion can proceed.

The change only affects a workaround for a PyTorch bug on the `cpu` device.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@younesbelkada, @loubnabnl, @jlamypoirier

### CODE REVIEW

**Comment by pcuenca** [comment]
Note: to fully test conversion of `gpt-bigcode` models, the following `coremltools` PRs (or equivalent workarounds) need to be applied as well: https://github.com/apple/coremltools/pull/1910, https://github.com/apple/coremltools/pull/1911.

**Review by jlamypoirier — APPROVED** [review]
I suggest moving the torch.empty to the else to avoid double allocation, otherwise lgtm

**Review by younesbelkada — APPROVED** [review]
Thanks @pcuenca  !

**Comment by mayank31398** [comment]
@younesbelkada I think this is already fixed in PT.
Should we just drop this logic?
Opened a PR: https://github.com/huggingface/transformers/pull/24768

**Comment by sgugger** [comment]
We support versions of PyTorch from 1.10 and onward, so we need to keep the workaround for the bug.

**Review by sgugger — APPROVED** [review]

**Pull request merged**
