### PR TITLE
Generate: correct default model input creation for decoder-only models

### LINKED ISSUE #21578: `RuntimeError` when running batched inference for `Salesforce/blip2-opt-2.7b`
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.27.0.dev0
- Platform: Linux-5.15.0-57-generic-x86_64-with-glibc2.10
- Python version: 3.8.12
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.11.0a0+b6df043 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

I'm trying to run batched inference using BLIP v2 with a slight modification from the [example script](https://huggingface.co/docs/transformers/main/en/model_doc/blip-2#transformers.Blip2ForConditionalGeneration.forward.example). Anything above a batch size of produces a `RuntimeError` due to a shape mismatch in a `torch.cat` operation. The error stems from the `.generate()` function inside the language model componenet of BLIP v2.

cc  @NielsRogge @gante

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

## Code To Reproduce

```python
from PIL import Image
import requests
from transformers import Blip2Processor, Blip2ForConditionalGeneration
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

processor = Blip2Processor.from_pretrained("Salesforce/blip2-opt-2.7b")
model = Blip2ForConditionalGeneration.from_pretrained(
    "Salesforce/blip2-opt-2.7b", torch_dtype=torch.float16
)
model.to(device)
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

# ---------------------- Change made here ---------------------- #
# Passing `images=[image, image]` instead of `images=image` for testing batched inference
inputs = processor(images=[image, image], return_tensors="pt").to(device, torch.float16)
# ---------------------------------------------------------------- #

generated_ids = model.generate(**inputs)
```

## Error Stack Trace

```python
╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│                                                                                           │
│ /tmp/ipykernel_1000/1893006406.py:18 in <module>                                          │
│                                                                                           │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_1000/1893006406.py'                  │
│ /opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py:28 in decorate_context │
│                                                                                           │
│    25 │   │   @functools.wraps(func)                                                      │
│    26 │   │   def decorate_context(*args, **kwargs):                                      │
│    27 │   │   │   with self.__class__():                                                  │
│ ❱  28 │   │   │   │   return func(*args, **kwargs)                                        │
│    29 │   │   return cast(F, decorate_context)                                            │
│    30 │                                                                                   │
│    31 │   def _wrap_generator(self, func):                                                │
│                                                                                           │
│ /home/synopsis/git/transformers/src/transformers/models/blip_2/modeling_blip_2.py:1421 in │
│ generate                                                                                  │
│                                                                                           │
│   1418 │   │   inputs_embeds = self.language_model.get_input_embeddings()(input_ids)      │
│   1419 │   │   inputs_embeds = torch.cat([language_model_inputs, inputs_embeds], dim=1)   │
│   1420 │   │                                                                              │
│ ❱ 1421 │   │   outputs = self.language_model.generate(                                    │
│   1422 │   │   │   inputs_embeds=inputs_embeds,                                           │
│   1423 │   │   │   attention_mask=attention_mask,                                         │
│   1424 │   │   │   **generate_kwargs,                                                     │
│                                                                                           │
│ /opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py:28 in decorate_context │
│                                                                                           │
│    25 │   │   @functools.wraps(func)                                                      │
│    26 │   │   def decorate_context(*args, **kwargs):                                      │
│    27 │   │   │   with self.__class__():                                                  │
│ ❱  28 │   │   │   │   return func(*args, **kwargs)                                        │
│    29 │   │   return cast(F, decorate_context)                                            │
│    30 │                                                                                   │
│    31 │   def _wrap_generator(self, func):                                                │
│                                                                                           │
│ /home/synopsis/git/transformers/src/transformers/generation/utils.py:1386 in generate     │
│                                                                                           │
│   1383 │   │   │   │   )                                                                  │
│   1384 │   │   │                                                                          │
│   1385 │   │   │   # 11. run greedy search                                                │
│ ❱ 1386 │   │   │   return self.greedy_search(                                             │
│   1387 │   │   │   │   input_ids,                                                         │
│   1388 │   │   │   │   logits_processor=logits_processor,                                 │
│   1389 │   │   │   │   stopping_criteria=stopping_criteria,                               │
│                                                                                           │
│ /home/synopsis/git/transformers/src/transformers/generation/utils.py:2224 in              │
│ greedy_search                                                                             │
│                                                                                           │
│   2221 │   │   │   │   next_tokens = next_tokens * unfinished_sequences + pad_token_id *  │
│   2222 │   │   │                                                                          │
│   2223 │   │   │   # update generated ids, model inputs, and length for next step         │
│ ❱ 2224 │   │   │   input_ids = torch.cat([input_ids, next_tokens[:, None]], dim=-1)       │
│   2225 │   │   │   model_kwargs = self._update_model_kwargs_for_generation(               │
│   2226 │   │   │   │   outputs, model_kwargs, is_encoder_decoder=self.config.is_encoder_d │
│   2227 │   │   │   )                                                                      │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 1 but got size
2 for tensor number 1 in the list.
```

### Expected behavior

I'd expect being able to run batched inference for a batch size > 1

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

Fixes #21578 and addresses concerns in #21575 

## Context
Support for `.generate()` from `inputs_embeds` with selected decoder-only models was added recently (#21405). This feature enables a `.generate(inputs_embeds=inputs_embeds)` call, i.e. without a `input_ids`. 

This specific call strategy, under the hood, implies that `.generate()` is in charge of creating a) an `input_ids` for later use (to concatenate the generated tokens) and b) the corresponding `attention_mask`. This automated creation was not working properly for `batch_size>1`.

## Changes
The changes in the PR respect the following desiderata (which required moving a few things around):
1. The `attention_mask` can be automatically inferred (with all ones) regardless of the shape of `inputs_embeds`;
2. When `inputs_embeds` is passed and `input_ids` is not, the automated `input_ids` has a sequence length of 1. This is particularly relevant for BLIP, as we don't want `input_ids` to start with the embeddings' sequence length.

This PR also adds/enhances tests, to ensure we don't regress on this capability.

⚠️ if approved, I will make the corresponding TF changes before merging.

### CODE REVIEW

**Comment by gante** [comment]
cc @dimitry12 this fixes the error you reported in #21575 (GPT2 was throwing the same error as GPTJ, and gets fixed here)

cc @NielsRogge please don't forget to add batched tests on models with generation capabilities, generate+batching is surprisingly tricky🙏

**Review by sgugger — APPROVED** [review]
Thanks for your work on this!

**Comment by sgugger** [comment]
But it does seem like it breaks a lot of tests 😅

**Comment by gante** [comment]
(Merging -- the failing test is a known failing test)

**Pull request merged**
