### PR TITLE
Use min version for huggingface-hub dependency

### PR DESCRIPTION
**Pull request by lewtun**
# What does this PR do?

This PR proposes to use a min version for the `huggingface_hub` dependency. 

The reasoning behind this is that we're currently running into dependency conflicts between `autonlp` (which uses `transformers` v4.8.0) and `evaluate` which relies on `huggingface_hub` v0.0.15. If I am not mistaken, setting a min version will provide the flexibility for `pip` to figure out which one to pick.

I realise that `huggingface_hub` is under active development, so feel free to close this PR if there's a strong need to freeze the version explicitly in `transformers`.

cc @abhishekkrthakur @SBrandeis 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
Yes the exact pin has been set on purpose because `huggingface_hub` is not stable enough right now, and there might breaking changes in the future that would break older versions of Transformers.

We can accept an upgrade on the Transformers side (bumping to 0.0.15) but we will only switch to a minimum version when `huggingface_hub` is more mature.

Also, for something like this, no merge before @LysandreJik is back please, as he knows more than me (and may have a different opinion) :-)

**Comment by lewtun** [comment]
Thanks for the clarification @sgugger! I totally understand the reasoning to pin the exact version, so will find a work around in the meantime.

I'll keep this PR open until @LysandreJik is back in case he wants to accept a bump to v0.0.15 😃

**Comment by lewtun** [comment]
i found a work around using the `/datasets` endpoint so happy to close this PR until `huggingface_hub` is more stable

**Comment by LysandreJik** [comment]
Just checked, and it should be fine to bump to 0.0.15. Most of the `huggingface_hub` specifics in `transformers` is using the logic defined in `src/transformers/hf_api.py`, so close to nothing would be affected by that upgrade.

Feel free to upgrade and merge if all tests pass, I'll keep a close eye on the slow tests.

**Pull request merged**
