### PR TITLE
[CI-Test] Fixes but also skips the mT5 tests

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Silences the `MT5` tests. They are irrelevant as the model behind is T5, which function well. 
I want to delete everything but prefer to ask if there is a reason why we have these? 
cc @sgugger

### CODE REVIEW

**Comment by ydshieh** [comment]
My opinion is that we should have test file(s) for each model type we have. MT5 has its own modeling file and model type, so we should keep it.

**Comment by sgugger** [comment]
mT5 does not really have its own modeling file since it's just T5. I'm happy if the tests for that model are contained to a slow integration test to not bloat the CI, like what is done for similar models (Camembert for instance).

**Comment by ydshieh** [comment]
I am OK with the decision, but just want to point out that we will lose these models for tiny model creation, which are required for ONNX testing and pipeline testing. I just want to every party involved agree this.

cc @LysandreJik, @Narsil  and @lewtun

**Comment by LysandreJik** [comment]
Ok with the decision as well!

**Review by sgugger — APPROVED** [review]

**Pull request merged**
