### PR TITLE
[model card] model card for bart-large-finetuned-squadv1

### PR DESCRIPTION
**Pull request by patil-suraj**

### CODE REVIEW

**Comment by julien-c** [comment]
could you also add a metadata link to the dataset, as demonstrated in https://github.com/huggingface/transformers/commit/ca5e1cdf8e314288bd0242a531815a6c75d8178e? Thanks!

**Comment by patil-suraj** [comment]
> could you also add a metadata link to the dataset, as demonstrated in [ca5e1cd](https://github.com/huggingface/transformers/commit/ca5e1cdf8e314288bd0242a531815a6c75d8178e)? Thanks!

Sure

**Comment by julien-c** [comment]
Great, thanks @patil-suraj

**Comment by julien-c** [comment]
with link to dataset: https://huggingface.co/valhalla/bart-large-finetuned-squadv1

**Pull request merged**
