### PR TITLE
Remove max length beam scorer

### LINKED ISSUE #11040: max_length in beam_search() and  group_beam_search() does not consider beam_scorer.max_length
## Environment info

- `transformers` version: 
- Platform: 4.3.2
- Python version: 3.8.5
- PyTorch version (GPU?): 1.8.0
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

## Information

I am using BART model in particular, but this problem exists for all the other models, using `beam_search()` and `group_beam_search()` for decoding the generated text.

The `max_length` variable set using `BeamSearchScorer` is not used by `beam_search()` or `group_beam_search()` function in `generation_utils.py` script.

Thus using a  smaller `max_length` while initializing the object of class, for example:
```
beam_scorer = BeamSearchScorer(
    batch_size=1,
    max_length=5,
    num_beams=num_beams,
    device=model.device,
)
```
instead of 
```
beam_scorer = BeamSearchScorer(
    batch_size=1,
    max_length=model.config.max_length,
    num_beams=num_beams,
    device=model.device,
)
```

in the example given [here](https://huggingface.co/transformers/main_classes/model.html#transformers.generation_utils.GenerationMixin.beam_search) 

results in an error:
```
File "temp.py", line 34, in <module>
    outputs = model.beam_search(input_ids, beam_scorer, logits_processor=logits_processor, **model_kwargs)
  File "<conda_env_dir>/lib/python3.8/site-packages/transformers/generation_utils.py", line 1680, in beam_search
    sequence_outputs = beam_scorer.finalize(
  File "<conda_env_dir>/lib/python3.8/site-packages/transformers/generation_beam_search.py", line 328, in finalize
    decoded[i, : sent_lengths[i]] = hypo
RuntimeError: The expanded size of the tensor (5) must match the existing size (6) at non-singleton dimension 0.  Target sizes: [5].  Tensor sizes: [6]
```

The problem arises when using:
* [x] the official example scripts: 
- [beam_scorer_example](https://huggingface.co/transformers/main_classes/model.html#transformers.generation_utils.GenerationMixin.beam_search)
* [x] my own modified scripts: 
-  Also, using `max_length` higher than `model.config.max_length` while initializing object (`beam_scorer`) of type `BeamSearchScorer` does not help in generating longer sequences, as `beam_scorer.max_length` is not used by `beam_search()` or `group_beam_search()`

## To reproduce

1. The above mentioned modification in the [example](https://huggingface.co/transformers/main_classes/model.html#transformers.generation_utils.GenerationMixin.beam_search)

## Expected behavior
1. The program to run without any errors when lower `max_length` is set for object of type `BeamSearchScorer`
2. Generate longer length sequences (longer than `model.config.max_length`) when higher `max_length` is set for object of type `BeamSearchScorer`

### PR DESCRIPTION
**Pull request by GeetDsa**
# What does this PR do?

Fixes #11040
Modifies ad per the comments from Pull #11122 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@patil-suraj ; @patrickvonplaten ; @Narsil 

Note: I have modified code in the `./tests/` where, `max_length` was used with `beam_scorer`.
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Awesome job @GeetDsa - this looks good to me :-) 

Also pinging @patil-suraj and @Narsil for review.

**Review by patrickvonplaten — APPROVED** [review]

**Comment by patrickvonplaten** [comment]
@Narsil - do you think we need a test here or should this be fine without?

**Review by patrickvonplaten — COMMENTED** [review]
Ok tests are not passing anymore after the merge @GeetDsa - could you take a final look what could be wrong here? :-) 

If it's too difficult, let me know and I'll fix it!

**Comment by GeetDsa** [comment]
Hi @patrickvonplaten , Most of the errors are caused because of "max_length" attribute used while creating `beam_scorer` object in the test cases. These errors are arising as the beam_scorer attribute is removed from the source code. Infact, I had modified the files under `tests/*` to take account for this.(This can be found in my commits. Sorry that I did not had different commits for the actual source code and the tests).  So, may be can you review the files that I have modified under `tests/*`  as well?

**Comment by Narsil** [comment]
I think we shouldn´t modify the tests if possible (thats what make backward compatiblity enforced).

Instead, we should probably : 
- add some warning for users that used the raw components/functions
- point the towards a better solution
- modify the tests that DO raise warnings to make sure we do raise them (and also swallow them in the logs) (they become backward compatibility tests their names should probably reflect that too) (We can remove some backward tests if they are very redundant btw)
- Have new tests that point show new API.
- Higher level tests (within models) should not be affected.
@GeetDsa  I can do this for you if you want.

**Comment by GeetDsa** [comment]
> I think we shouldn´t modify the tests if possible (thats what make backward compatiblity enforced).
> 
> Instead, we should probably :
> 
> * add some warning for users that used the raw components/functions
> * point the towards a better solution
> * modify the tests that DO raise warnings to make sure we do raise them (and also swallow them in the logs) (they become backward compatibility tests their names should probably reflect that too) (We can remove some backward tests if they are very redundant btw)
> * Have new tests that point show new API.
> * Higher level tests (within models) should not be affected.
>   @GeetDsa  I can do this for you if you want.

Hi @Narsil, I think it would be better if you can do it, as I don't really know how to deal with tests.

**Comment by GeetDsa** [comment]
> > I think we shouldn´t modify the tests if possible (thats what make backward compatiblity enforced).
> > Instead, we should probably :
> > 
> > * add some warning for users that used the raw components/functions
> > * point the towards a better solution
> > * modify the tests that DO raise warnings to make sure we do raise them (and also swallow them in the logs) (they become backward compatibility tests their names should probably reflect that too) (We can remove some backward tests if they are very redundant btw)
> > * Have new tests that point show new API.
> > * Higher level tests (within models) should not be affected.
> >   @GeetDsa  I can do this for you if you want.


 Hi @Narsil, I think it would be better if you can do it, as I don't really know how to deal with tests.

**Comment by patrickvonplaten** [comment]
I'll take care of it

**Comment by patrickvonplaten** [comment]
@Narsil - I think we don't need to add a test here. By design the PR prevents errors such as the one mentioned in the issue - It's not possible anymore to pass `max_length` to `BeamSearchScorer` and thus a test doesn't make much sense here IMO.

**Comment by patrickvonplaten** [comment]
Will wait for https://github.com/huggingface/transformers/pull/11442 to be merged before rebasing this one to merge

**Comment by Narsil** [comment]
@patrickvonplaten But if users were using the BeamScorer object, that's a breaking change, isn't it ?

**Comment by patrickvonplaten** [comment]
> @patrickvonplaten But if users were using the BeamScorer object, that's a breaking change, isn't it ?

Yes true. IMO, no functionality is lost though because:

- Previously, if one had passed `max_length` to both `def beam_search(...)` and `BeamSearchScorer(...)`, then there would have been a bug (see issue). The correct way of fixing the bug (while still allowing `BeamSearchScorer(...)` to accept `max_length`) would have been to overwrite `BeamSearchScorer's` max_length with `beam_search(...)`'s max_length. On the other hand it's never possible to **not** pass `max_length` to `def beam_search(...)` => therefore I think either way the `max_length` arg to `BeamSearchScorer` is useless (the `max_length` value of `beam_search(...)` would have been preferred in any way. 

=> However, we could/should probably add `**kwargs` to `BeamSearchScorer` that throws a warning if `max_length` is passed & says that's it's deprecated. This would be cleaner overall and have no breaking changes - what do you think @Narsil ?

**Comment by Narsil** [comment]
Yep, that's what I had in mind, just accept it, raise a warning (and ignore it, exactly as it used to if I understand correctly)

**Comment by patrickvonplaten** [comment]
> Yep, that's what I had in mind, just accept it, raise a warning (and ignore it, exactly as it used to if I understand correctly)

Done! Could you review one last time and merge if ok for you? @Narsil

**Comment by GeetDsa** [comment]
@patrickvonplaten, thank you for taking care of it. I found a small issue in the warning message. The message provided in the latest commit is ""`max_length` should be passed directly to `beam_search(...)`, `beam_sample(...)`"", shouldn't you include "generate(..)" as well, as sometime, `generate(...)` inherently calls `beam_search(..,)` or `group_beam_search(..,)`, or other relevant functions.

**Comment by patrickvonplaten** [comment]
> @patrickvonplaten, thank you for taking care of it. I found a small issue in the warning message. The message provided in the latest commit is ""`max_length` should be passed directly to `beam_search(...)`, `beam_sample(...)`"", shouldn't you include "generate(..)" as well, as sometime, `generate(...)` inherently calls `beam_search(..,)` or `group_beam_search(..,)`, or other relevant functions.

Hey @GeetDsa, 

It should be fine, since the warning is impossible to be triggered by `generate(...)` since when one calls `generate(...)`, one cannot pass `max_length` to `BeamScorer`

**Pull request merged**
