### PR TITLE
🌐 [i18n-KO] Translated `bertology.mdx` to Korean

### PR DESCRIPTION
**Pull request by wonhyeongseo**
# What does this PR do?

Translated the `bertology.mdx` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

### CODE REVIEW

**Comment by wonhyeongseo** [comment]
* Live preview is not working, although checks have passed. I confirmed there are no gotchas using GitHub Codespace. (We should create a pre-built environment (where all `pip install` commands are completed) for mentees and new-comers, preferably with `preview --[lang]` commands built-in as well)

Team PseudoLab, may you please review this PR? @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

**Review by sim-so — COMMENTED** [review]
고생 많으셨습니다! 모두 좋습니다 😄

**Review by 0525hhgus — CHANGES_REQUESTED** [review]
좋은 번역 감사합니다 😀 
논문 내용이 잘 드러나도록 타이틀을 번역해주셨군요 👍
아래 짧은 리뷰를 남겼습니다!

**Comment by wonhyeongseo** [comment]
@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

**Review by ArthurZucker — APPROVED** [review]
Nice 🔥

**Pull request merged**
