### PR TITLE
Updated `ruff` to the latest version

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# What does this PR do?
Updated `ruff` to the [latest version](https://github.com/astral-sh/ruff/releases) and fixed the required code according to the latest version.

After updating ruff to the latest version, I ran `make style`, `make quality`, and the following `ruff` rule was failing at few places:
[E721](https://docs.astral.sh/ruff/rules/type-comparison/) (use **is** and **is not** for type comparisons, or **isinstance()** for isinstance checks). So, i fixed them.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@ArthurZucker @amyeroberts

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Thanks! The tests are failing because our docker images are built using previous version of ruff! cc @ydshieh is there a way to trigger build on this branch ?

**Comment by ydshieh** [comment]
We will have to modify the workflow file around this part

```
  push:
    branches:
      - build_ci_docker_image*
```
in order to trigger the build.

Look `ruff` release history, almost every week there is a release. I am not sure we want to update (so frequently) our `ruff` pin and the corresponding code changes to keep update with it.

**Comment by ydshieh** [comment]
Hi @Sai-Suraj-27 Yes, every 2-3 month is reasonable.

This PR itself is still running against `ruff==0.4.4` however, and we still have to build the new images and run CI against the new images first before we merge. 

(that only our team can do)

**Comment by ydshieh** [comment]
@ArthurZucker 

CI is green with the new images

https://app.circleci.com/pipelines/github/huggingface/transformers/97697/workflows/3e9c46ec-919b-4941-bf65-73780438ad5e


Once you approved, I will push the images and merge the PR.

**Review by ArthurZucker — APPROVED** [review]
Thanks

**Pull request merged**
