### PR TITLE
[GPTJ] enable common tests and few fixes

### LINKED ISSUE #14107: GPT-J Models Cannot Load If Tokens Have Been Resized Using resize_token_embeddings Method
## Environment info

- `transformers` versions: 4.11.1, 4.11.3
- Platform: Ubuntu 18.04, Windows
- Python version: 3.7.5

### Who can help
@patil-suraj @patrickvonplaten, @LysandreJik @stas00

## Information

Something seems to be wrong in the serialization of GPTJ models. They are not behaving like other models in the library. After loading a GPTJ model using `.from_pretrained`, calling `model.resize_token_embeddings` and saving the model using `.save_pretrained`, it is not possible to load a GPTJ model again using `.from_pretrained`. Is there a workaround that's suggested? 

This error is thrown:

```
RuntimeError: Error(s) in loading state_dict for GPTJForCausalLM:
	size mismatch for lm_head.weight: copying a param with shape torch.Size([50400, 4096]) from checkpoint, the shape in current model is torch.Size([54001, 4096]).
	size mismatch for lm_head.bias: copying a param with shape torch.Size([50400]) from checkpoint, the shape in current model is torch.Size([54001]).
```

## To reproduce

```
from transformers import GPTJForCausalLM
model = GPTJForCausalLM.from_pretrained("EleutherAI/gpt-j-6B")
model.resize_token_embeddings(54001)
model.save_pretrained("model_dir")
model = GPTJForCausalLM.from_pretrained("model_dir")
```

## Expected behavior

The model should be loaded correctly if the token embeddings have been changed in the standard way.

### PR DESCRIPTION
**Pull request by patil-suraj**
# What does this PR do?

Currently, GPTJ does not run common tests because its testes class does not subclass `ModelTesterMixin, GenerationTesterMixin`.  This PR enables common tests for GPTJ and fixes a few things along the way.
I've run the slow tests manually and verified that they pass.

Thanks a lot, @sgugger  for spotting this!

cc @StellaAthena 

Fixes #14107

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks a lot for fixing the common tests!

**Comment by alexorona** [comment]
@patil-suraj For the specific issue of `resize_token_embeddings` on gptj (#14107), I got it to work by changing two methods in modeling_gptj.py below. I'm not sure this is right because the model needs to train 2 epochs to get a good result whereas I almost always need just 1 epoch with other model types (gpt-2, gpt-neo, etc.). Will this PR cover the `resize_token_embeddings` issue? It doesn't seem to make changes to these methods.

```
def get_output_embeddings(self):
    return self.lm_head

def set_output_embeddings(self, new_embeddings):
    self.lm_head = new_embeddings
```

**Comment by alexorona** [comment]
> @patil-suraj For the specific issue of `resize_token_embeddings` on gptj (#14107), I got it to work by changing two methods in modeling_gptj.py below. I'm not sure this is right because the model needs to train 2 epochs to get a good result whereas I almost always need just 1 epoch with other model types (gpt-2, gpt-neo, etc.). Will this PR cover the `resize_token_embeddings` issue? It doesn't seem to make changes to these methods.
> 
> ```
> def get_output_embeddings(self):
>     return self.lm_head
> 
> def set_output_embeddings(self, new_embeddings):
>     self.lm_head = new_embeddings
> ```

@patil-suraj Nevermind! It looks like you caught this and also made additional changes!

**Comment by patil-suraj** [comment]
>I got it to work by changing two methods in modeling_gptj.py below. I'm not sure this is right because the model needs to train 2 epochs to get a good result whereas I almost always need just 1 epoch with other model types 

@alexorona We also need to set `tie_word_embeddings=False` in `config`, because GPT-J does not share word embeddings with `lm_head`. It was not set by default, so when we resize the embeddings, the weights get tied, maybe this was the issue.

**Review by LysandreJik — APPROVED** [review]
Looks good to me, thank you @patil-suraj!

cc @StellaAthena

**Comment by StellaAthena** [comment]
Looks good to me too!

**Pull request merged**
