### PR TITLE
Time to Say Goodbye, torch 1.7 and 1.8

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

We have been together for more than 2 years ❤️ 

(see this [discussion](https://github.com/huggingface/transformers/issues/18817))

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
There is a bit more work to do ;-) The goal of pinning a minimum version is to remove all the code specific to older PyTorch versions.

In this case I haven't caught some PyTorch 1.7 specific code but there are a lot of PyTorch 1.8-specific code. In particular we can replace all instance of `torch_int_div` which was there to execute a different line depending on the version.

**Comment by ydshieh** [comment]
Thank you @sgugger . I will try to make a clean breakup

**Comment by ydshieh** [comment]
Hope I don't miss anything 😂

**Review by amyeroberts — APPROVED** [review]
LGTM! 

Parting is such sweet sorrow, but it's time to say goodbye torch < 1.9 🥲

**Review by sgugger — COMMENTED** [review]
Thanks a lot! Diving into the codebase a bit more, I see a test for PyTorch 1.8.0 in onnx.convert (and anything using `TORCH_ONNX_DICT_INPUTS_MINIMUM_VERSION` which is 1.8.0).

In modeling_utils there are also some `require_version_core("torch>=1.9")` which can now be removed.

**Review by sgugger — APPROVED** [review]
Thanks again!

**Comment by stas00** [comment]
ok, the deepspeed CI is running pt-1.8 - how do we solve that then?

I have passed this change to the Deepspeed team let's see what they say.

**Pull request merged**
