### PR TITLE
Add Pytorch Tensor Parallel support for Mistral

### PR DESCRIPTION
**Pull request by VladOS95-cyber**
# What does this PR do?

This PR uses the torch.distributed.tensor.parallel subpackage to implement Tensor Parallel for Mistral.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. Link:https://github.com/huggingface/transformers/issues/34789
- [] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @arthurzucker since I think he was handling the tensor parallelism issue - let me know if I should have pinged someone else instead!

**Review by ArthurZucker — APPROVED** [review]
LGTM thanks for adding! 🤗

**Comment by DebarshiChanda** [comment]
@VladOS95-cyber @ArthurZucker Hi guys, I had a small doubt. Why aren't the changes in the query_states, key_states and value_states applied to other attention classes (like `MistralFlashAttention2`, `MistralSdpaAttention`) as well?

**Comment by VladOS95-cyber** [comment]
> @VladOS95-cyber @ArthurZucker Hi guys, I had a small doubt. Why aren't the changes in the query_states, key_states and value_states applied to other attention classes (like `MistralFlashAttention2`, `MistralSdpaAttention`) as well?

Hey @DebarshiChanda! Thanks for noticed that, i think you are right and we should apply the same infer logic for other attention classes. I am going to fix it in another PR https://github.com/huggingface/transformers/pull/35007

**Pull request merged**
