### PR TITLE
Bugfix converting added tokens before save

### PR DESCRIPTION
**Pull request by amirza1**
convert_added_tokens is called on every save.
It also modifies the AddedTokens by performing pop, which prevents saving a tokenizer more than one time

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @ArthurZucker @itazap

**Comment by itazap** [comment]
hey @amirza1 ! Thanks for opening this PR!! 🤗  Can you please link the issue # or provide a small code snippet / reproducer for the bug? Thank you! 😊

**Comment by amirza1** [comment]
I apologize, we can probably close it, it appears the latest versions of the code do not have this issue.

**Comment by itazap** [comment]
No worries! Thank you for the quick follow up! Closing 🤗

**Comment by amirza1** [comment]
A closer inspection shows that the rust version of tokenizers works. The bug is still in the code, so it's up to you :)

**Comment by itazap** [comment]
Can you please provide a reproducer? Thanks!

**Pull request closed without merging**
