### PR TITLE
Releasing file lock

### PR DESCRIPTION
**Pull request by dimagalat**
`With` scope creates a file lock, which leads to the following error:

INFO:filelock:Lock 1408081097608 released on C:\Users\dimag\.cache\torch\transformers\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084.lock
Traceback (most recent call last):
  File "C:\Users\dimag\Anaconda3\envs\pytorch\lib\site-packages\transformers\tokenization_utils.py", line 398, in _from_pretrained
    resume_download=resume_download,
  File "C:\Users\dimag\Anaconda3\envs\pytorch\lib\site-packages\transformers\file_utils.py", line 212, in cached_path
    user_agent=user_agent,
  File "C:\Users\dimag\Anaconda3\envs\pytorch\lib\site-packages\transformers\file_utils.py", line 392, in get_from_cache
    os.rename(temp_file.name, cache_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\dimag\\.cache\\torch\\transformers\\tmpnhzxze8u' -> 'C:\\Users\\dimag\\.cache\\torch\\transformers\\26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084'

### CODE REVIEW

**Comment by thomwolf** [comment]
@aaugustin could you have a quick look at this PR related to the filelock system?

**Comment by aaugustin** [comment]
This isn't directly related to the file lock system. Rather, it's related to moving the file rather than copying it.

Given the current implementation, closing the file before moving it (which is all this PR does) looks safe to me. We're still within the lock-protected section.

Could you take this opportunity remove the following two lines?

```python
                # we are copying the file before closing it, so flush to avoid truncation
                temp_file.flush()
```

Indeed, you're now closing the file before copying it. (To be honest, I should have removed them when I stopped copying the file and started moving it instead.)

**Comment by dimagalat** [comment]
@aaugustin I agree, `.flush()` is unnecessary, thanks for pointing it out. I've made the change.

**Review by aaugustin — APPROVED** [review]

**Comment by thomwolf** [comment]
Ok great thanks @dimagalat and @aaugustin

**Pull request merged**
