### PR TITLE
Fix tensor-parallelism link

### PR DESCRIPTION
**Pull request by steilgedacht**
# What does this PR do?

Replaces the old link in the llama configuration file to the new section on the website.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

@stevhliu and @MKhalusova

### CODE REVIEW

**Review by stevhliu — APPROVED** [review]
Thanks for fixing the link! Would you mind also correcting the link for BLOOM here: 

https://github.com/huggingface/transformers/blob/a502b0d427e6ea217bb4d28b352297823385860a/src/transformers/models/bloom/configuration_bloom.py#L79

**Comment by steilgedacht** [comment]
Yes, I also changed now the second link, however I commited and pushed to fast and had another typo in it which I corrected with a second commit, because I didn't found a option to delete the first commit. I hope that's okay - I am not that experienced yet with pull request.

**Comment by stevhliu** [comment]
No problem, and thanks for updating BLOOM as well! The last step is to run `make style` to reformat the code so the CI test passes :)

**Comment by steilgedacht** [comment]
Hmmm, I totally agree that the other files shouldn't be touched. The newest ruff version changed these files. I reversed now the changes, and then I ran `pip uninstall black && pip install -U ruff==0.1.5`. After that I ran `make style` again, but this hasn't made any changes to any files and as you can see the test failed again. I also tried to run your suggestion with `make fixup`, but I just got error messages which I coun't fix. What should we do now?

**Comment by stevhliu** [comment]
Ah ok, can you try rebasing on main and push with `--force` then?

**Comment by steilgedacht** [comment]
Done, it made a lot of changes and I have no idea now if that was correct 😅

**Comment by stevhliu** [comment]
Oops I don't think you pushed with `--force` which is why we're seeing all these other changes! On the positive side though, changes to the bloom/fuyu/mpt modeling files looks like they're fixed 🎉 

Do you mind opening a clean PR and then we can merge 😄

**Pull request closed without merging**
