### PR TITLE
[`Mamba2`] Fix slow path

### LINKED ISSUE #34817: Mamba2 `torch_forward` reduction dimension possibly incorrect?
### System Info

NA

### Who can help?

@ArthurZucker

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

NA

### Expected behavior

In the `torch_forward` part of Mamba2, it seems like the reduction dimension should be `dim=3` instead of `dim=2`?

https://github.com/huggingface/transformers/blob/30335093276212ce74938bdfd85bfd5df31a668a/src/transformers/models/mamba2/modeling_mamba2.py#L560

with `dim=3`, the output seems to more or less match that of Mamba-2's [`ssd_minimal`](https://github.com/state-spaces/mamba/blob/main/mamba_ssm/modules/ssd_minimal.py) implementation, but not with `dim=2`

### PR DESCRIPTION
**Pull request by vasqu**
# What does this PR do?
- Fixes a wrong contraction in the mamba2 slow path discovered by @HanGuo97 
- Simplifying one step (4 vs 1 permutations) 
- Cleaning up some comments to follow the og ssd minimal more closely again 

Verified it locally, see the test over [here](https://github.com/vasqu/mamba2-torch/blob/main/tests/TestSSDMinimal.py)

Fixes #34817

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @molbap

### CODE REVIEW

**Comment by molbap** [comment]
Thanks @vasqu for the investigation and fix - and @HanGuo97 for reporting!
Indeed, looks like this is a better reduction - pen&paper helped me understand it. One thing, could you move the test you did locally to an actual test, with a dependency check to protect the `mamba_chunk_scan_combined` import? that way, either with a test image with this dep installed or locally, one can verify that this is always true

**Comment by vasqu** [comment]
@molbap I think there might be a missing initialization in the cuda forward, i.e. see https://github.com/huggingface/transformers/blob/0044dabbc01f287e791de43d68c26b8f4de6484f/src/transformers/models/mamba2/modeling_mamba2.py#L368-L373 where some copy mises. Not sure when I'll get to it, but I would leave that to a separate PR.

Added a test now. It takes 3-4s on my machine due to the warming of the triton kernel - should I make it a slow test?

**Comment by molbap** [comment]
@vasqu 3-4 s is ok, no need to flag it as slow I think!
and for sure, ping me on the separate PR when you have time :saluting_face: 
Slow tests have one failure that seems to be independent from this PR
```python
             # Discretize x into dB
            # [bsz, intermediate_size] -> [bsz, num_heads, head_dim]
            hidden_states = hidden_states.reshape(batch_size, -1, self.head_dim)
            dBx = dB * hidden_states[..., None]
    
            # State calculation
            cache_params.ssm_states[self.layer_idx].copy_(
>               cache_params.ssm_states[self.layer_idx] * dA + dBx
            )
E           RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```
it's related to multi-GPU runs, it's separate from this issue, I think we're ok to go here! cc @ArthurZucker

**Review by molbap — APPROVED** [review]
LGTM as discussed above :) to be reviewed by core maintainer

**Comment by vasqu** [comment]
I found an issue for the failure, so yea seems like a separate issue ^^ #33567

**Comment by vasqu** [comment]
gentle ping @ArthurZucker

**Review by saeed6944 — APPROVED** [review]

**Review by saeed6944 — APPROVED** [review]

**Comment by vasqu** [comment]
Closing in favor for #35154

**Pull request closed without merging**
