### PR TITLE
Fix unsupported setting of self._n_gpu in training_args on XPU devices

### PR DESCRIPTION
**Pull request by Liangliang-Ma**
In current training_args, self._n_gpu is set to device_count on XPU device, which will cause crash on XPU devices.
In Trainer, if self.args.n_gpu greater than one, it will utilize torch.nn.DataParallel to wrap the model. But Ipex(intel_extension_for_pytorch) don't support DataParallel, while it suggests using DDP instead.
So to make huggingface Trainer work on intel devices, this fix should be applied.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! This seems to have been introduce in #25714, and thus I am not convinced that the fix is as simple as that! 
Would you mind also sharing a reproducer of the issue? Might be related to specific hard / soft versions

**Comment by Liangliang-Ma** [comment]
> Hey! This seems to have been introduce in #25714, and thus I am not convinced that the fix is as simple as that! Would you mind also sharing a reproducer of the issue? Might be related to specific hard / soft versions

Hi! I have discussed with @abhilash1910 about the issue before this PR and we thought it can be fixed like this. This could be reproduced in a multi intel GPUs env, for the `distributedType `should be set to `MULTI_XPU` [in accelerator](https://github.com/huggingface/accelerate/blob/main/src/accelerate/state.py#L230). I think most example scripts using Trainer and more than one gpu should be reproducer.

**Review by abhilash1910 — APPROVED** [review]
Thanks @Liangliang-Ma  for addressing this. 
@ArthurZucker  yes the current limitation of pure dp on ipex only allows us to use n_gpu=1 .
Could you help re-trigger the CI test ? Thanks

**Review by ArthurZucker — APPROVED** [review]
Alright thanks all for checking, triggering the CI

**Comment by Liangliang-Ma** [comment]
@ArthurZucker Seems CI got block by Internet issue. Could you please check with that? Thanks

**Comment by ArthurZucker** [comment]
Seems like I can't would you mind merging with main to trigger it?!

**Pull request merged**
