### PR TITLE
[docstring] misc arg doc corrections

### PR DESCRIPTION
**Pull request by stas00**
- fix docstring s/int/bool/
- correct arg description
- fix num_labels to match reality

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks. Will in these fixes don't hesitate to replace the True or False by :obj:`True` and :obj:`False` for consistency (also don't hesitate to tag me on doc PR for quicker reviews :-) )

**Comment by stas00** [comment]
Understood!

Do we have a model of perhaps one largish module that we can use a reference for how the rest should be done? So that you polish the hell out of it, and then this will be the model to follow.

**Comment by sgugger** [comment]
`tokenization_utils_base` is a good example for instance, all other utils modules too. `config_utils` has an example of how to split parameters in several subgroups if you ever need a model of that. Rules are the usual sphinx-like and some more personal nits are:
- not writing "defaults to :obj:\`None\`" for optional things that have default (it's implied)
- using :obj:\`foo\` syntax for objects (like False, True, all strings) or mention to other arguments
 but not numbers (like 0, 1.0...)
- using italics for optional

**Comment by stas00** [comment]
Great tips on the model docs and the small specifics. I see some are already here:
https://github.com/huggingface/transformers/tree/master/docs#writing-documentation---specification
add the others too?

Loving params subgroup docs - it's very helpful. I'd organize the params in the function in the same groups too.

Thank you for sharing all these, @sgugger!

**Comment by sgugger** [comment]
Yes we could add those general rules to that section of the docs README. (I am unsure people actually read that so did not take the time to properly update it :-) )

**Comment by stas00** [comment]
I didn't know it was there, but now that I do, I'd definitely per-use it - so yes, please update it!

**Comment by stas00** [comment]
>     * not writing "defaults to :obj:`None`" for optional things that have default (it's implied)
```
grep -r "defaults to :obj:.None." src | wc -l
```
```
580
```
might be easy to replace in one swoop.

**Comment by sgugger** [comment]
Feel free to do it in one PR :-)

**Comment by stas00** [comment]
https://github.com/huggingface/transformers/pull/6956

**Pull request merged**
