### PR TITLE
[`PEFT`] Pass token when calling `find_adapter_config`

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

This PR fixes an issue that was reported on Spaces. I was not able to reproduce the issue locally though. 
When loading a model with `token=True` (i.e. on a gated or private repository), `find_adapter_config` will try to look for an adapter file inside a private repository without the token, leading to an authentication error. 

The fix is to pass the token to `adapter_kwargs` and remove the duplication here: https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L2529 

cc @LysandreJik

### CODE REVIEW

**Comment by abhishekkrthakur** [comment]
This seems to fix the issue for me. Shall we merge it? Or figure out the actual cause?

**Review by LysandreJik — APPROVED** [review]
LGTM

**Comment by denys-fridman** [comment]
@younesbelkada `adapter_kwargs` can be `None`, in which case the code breaks.

For reference, I was running
```
python main.py \
  --model path_to_mistral_7B \
  --tasks mbpp \
  --temperature 0.1 \
  --n_samples 15 \
  --batch_size 4 \
  --precision fp16 \
  --allow_code_execution \
  --save_generations \
  --max_length_generation 512 \
  --save_generations_path predictions.json \
  --metric_output_path metrics.json
```

**Comment by younesbelkada** [comment]
Nice catch!  Will open a PR soon to fix that

**Pull request merged**
