### PR TITLE
examples/seq2seq/__init__.py mutates sys.path

### PR DESCRIPTION
**Pull request by stas00**
(**edit**: the PR went through a change - i updated the description here).

Fixes part of the issue raised here: https://github.com/huggingface/transformers/pull/7109#issuecomment-693213029

This PR replaces the hack of retrying to import modules via `foo` and if failed via `.foo` depending on where the test is invoked from, so now it's possible to do:
```
pytest ./examples/seq2seq/test_seq2seq_examples.py --collect-only -q
cd examples
pytest ./seq2seq/test_seq2seq_examples.py --collect-only -q
cd seq2seq/
pytest ./test_seq2seq_examples.py --collect-only -q
```
and all the imports just work. (I used `--collect-only -q` just to validate that it works, as it's a fast run)

For scripts invocations work too:
```
python ./examples/seq2seq/run_eval.py -h
cd examples
python ./seq2seq/run_eval.py -h
cd seq2seq/
python ./run_eval.py -h
```

While `conftest.py` worked for tests, it left the scripts broken. So in the 2nd attempt I replaced `conftest.py` with `__init__.py` that does the same and works for both types.

If it's fitting, we can do the same for the rest of the `examples` sub-dirs.

@sshleifer

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]

**Comment by sshleifer** [comment]
Have you tested invoking run_eval.py from examples/seq2seq? 

That is the workflow documented in `seq2seq/README.md`

**Comment by stas00** [comment]
Ah, we need tests that aren't tests too :) 

Good catch!
```
cd examples/seq2seq/
python ./run_eval.py -h
Traceback (most recent call last):
  File "./run_eval.py", line 15, in <module>
    from .utils import calculate_bleu, calculate_rouge, parse_numeric_n_bool_cl_kwargs, use_task_specific_params
ImportError: attempted relative import with no known parent package
```

back to the drawing board.

Thanks for your vigilance, @sshleifer

**Comment by stas00** [comment]
OK, so while `conftest.py` worked for tests, it left the scripts broken. So in the 2nd attempt I replaced `conftest.py` with `__init__.py` that does the same and works for both types. 

@sshleifer

**Comment by stas00** [comment]
> This command is cheap and if it starts running you know you are fine:

Much faster to test is to:
```
python finetune.py -h
```

**Comment by sshleifer** [comment]
Pycharm users who develop on seq2seq a lot (I can think of 0 others haha) may need to change Preferences/Project Structure/Content Root to accommodate this. I posted [instructions](https://discuss.huggingface.co/t/pycharm-project-structure-seq2seq/1206) on the forums that I'll delete if this doesn't get merged: .

**Comment by sshleifer** [comment]
Merging this with the idea that there is a 10% chance we will have to revert because of some unforeseen dealbreaking issue.

**Pull request merged**
