### PR TITLE
Allow smart context to use accelerator

### LINKED ISSUE #28512: AMP autocast not invoked with CUDA 11.8 build of Pytorch
### System Info

pytorch 2.1 + CUDA 11.8
transformers 4.36.2
accelerate 0.26.0

### Who can help?

@pacman100 , @muellerz 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

in `Trainer.autocast_smart_context_manager()`, only CPU AMP is supported, and CUDA autocast wrapper is managed by `accelerate` when training starts. This design works with pytorch 2.1 built with CUDA 12.1, but not with the CUDA 11.8 version.

### Expected behavior

CUDA AMP works with torch 2.1+CUDA 11.8

My simple fix is as follows:
- add `force_cuda_amp` to TrainingArguments to flag the code to enable CUDA AMP autocast
- derive `Trainer.autocast_smart_context_manager()` to return CUDA AMP context if `force_cuda_amp` is flagged.

A more systematic solution (more like a hack) is to detect CUDA version when Trainer is initialized, if CUDA is < 12 then enable this flag automatically.

~~Edit: my fix resulted in NaN so no fix yet~~
Edit 2: my fix actually worked. The NaN problem was from the hidden `_fast_init` flag of `from_pretrained` that caused some new modules not properly initialized.

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

I believe this fixes the issue in https://github.com/huggingface/transformers/issues/28512, we weren't picking up the `Accelerator`'s context manager if it had one.

Fixes https://github.com/huggingface/transformers/issues/28512

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@amyeroberts

### CODE REVIEW

**Comment by muellerzr** [comment]
I did verify there's no computational difference in double auto-casting (just in case). (double meaning one from the model, the other from the context manager)

**Review by amyeroberts — APPROVED** [review]
Thanks for handling this! 

Could we add a test?

**Comment by muellerzr** [comment]
This may be a more complicated fix needed, as accelerate doesn't support AMP. 

At the time we just dropped it hoping more people wouldn't use it/end support, but since we have that issue I'll be putting it back in

**Comment by muellerzr** [comment]
Bringing it back, I think it's fine. Waiting for the user to report back how they could tell of this issue first and then will write a test based on that exact scenario (if not I'll just write a new one)

**Pull request closed without merging**
