### PR TITLE
Clap processor: remove wasteful np.stack operations

### PR DESCRIPTION
**Pull request by m-bain**
# What does this PR do?

Upon profiling, it showed some strange result that the ClapProcessor was taking **0.5s** to apply `_get_input_mel(...)` on short audio (less than 10s), whereas medium length audio (10s-20s) was taking only **0.02s**

As it turns out there was a wasteful `np.stack` operation on the 1-D waveform numpy array, meaning that the 1-D array is unpacked then stacked back together again, with no effect. This PR removes this wasteful op and short audio is now also processed in **0.02s**

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ArthurZucker 
@sanchit-gandhi

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for updating @m-bain! 

Could you provide an example snippet you used to run this for future reference of anyone visiting this PR?

**Comment by m-bain** [comment]
```python
import time
import numpy as np

waveform = np.random.rand(100_000)
n_repeat = 10

t1_p = time.time()
prev_impl = np.stack(np.tile(waveform, n_repeat))
t2_p = time.time()

t1_n = time.time()
new_impl = np.tile(waveform, n_repeat)
t2_n = time.time()

assert (prev_impl == new_impl).all()
print(f"Time to process [prev. impl.]: {t2_p-t1_p:.3f}s")
print(f"Time to process [new. impl.]: {t2_n-t1_n:.3f}s")
```
```plaintext
Time to process [prev. impl.]: 0.883s
Time to process [new. impl.]: 0.001s
```

**Comment by amyeroberts** [comment]
@m-bain Thanks!

**Review by ArthurZucker — APPROVED** [review]
Thanks for the catch! 🤗

**Review by sanchit-gandhi — COMMENTED** [review]
Awesome - thanks @m-bain! Also cc @ylacombe

**Pull request merged**
