### PR TITLE
[CIs] Better reports everywhere

### PR DESCRIPTION
**Pull request by stas00**
Continuing the work in https://github.com/huggingface/transformers/pull/8110 and https://github.com/huggingface/transformers/pull/8163 this PR does the following:

* [x] rename `pytest --make_reports` to `pytest --make-reports` for consistency with the rest of `pytest` opts that don't use `_`
* [x] move the `--make_reports` opt adding to a shared location and load it only once to avoid `pytest` failure 
   - some pytest plugins like `pytest-instafail` load `tests/conftest.py` even when running `examples`
   - now we can run tests from both test suites at once
* [x] rename `reports/report_foo` to `reports/foo` - avoid repetition
* [x] install `--make_reports` in all CIs: circleci and github actions 
* [x] make the reports available via artifacts
* [x] always cat short failure reports for github actions in its own "tab" since getting to artifacts there is a cumbersome process. I'm not sure this is needed in circleci jobs since each report in artifacts is available in 2 clicks, so I left the `cat *failures_short.txt` out on CircleCI jobs.
* [x] fixed a few issues in the github actions job configuration

@sgugger, @LysandreJik, @sshleifer

### CODE REVIEW

**Comment by stas00** [comment]
And and update on proposing this multiple reports feature to be a core feature in pytest https://github.com/pytest-dev/pytest/issues/7972 - one of the developers vetoed it, so I guess it will remain just here for now. It makes no sense for this not to be a core feature of pytest, but there was no invitation to discuss that - just NO. If someone wants to make it into a nice plugin please go for it.

**Review by sgugger — APPROVED** [review]
LGTM, thanks for adding those reports!
I saw the discussion (or lack thereof) on pytest. Their loss! We don't mind having the post-processing in transformers.

**Review by LysandreJik — APPROVED** [review]
Very nice, thanks @stas00!

**Comment by stas00** [comment]
> I saw the discussion (or lack thereof) on pytest. Their loss! We don't mind having the post-processing in transformers.

Eventually we will either have to port it to pytest hooks or keep up with the pytest API changes, since currently the code uses `pytest` internals and could break should they change those. It's just so much simpler doing that than reinventing the wheel.

**Pull request merged**
