### PR TITLE
[Very WIP] Migrating ALL pipelines to new testing + fixes

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

For now we just need to see the tests times to see how bad we are, and how much we need to improve.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by LysandreJik** [comment]
I'm curious how long it takes to run the whole suite - would it be possible to add a commit that impacts all pipelines to see how long that takes?

**Comment by Narsil** [comment]
@LysandreJik  That's the one.

**Comment by Narsil** [comment]
Or you mean hitting the `pipelines` files  ?

**Comment by LysandreJik** [comment]
Yes, I can push a commit that does that on your branch if you want!

**Comment by Narsil** [comment]
Go ahead ! Not sure how to trigger it.

**Comment by Narsil** [comment]
Done in many smaller PRs.

**Pull request closed without merging**
