### PR TITLE
[examples] fix no grad in second pruning in run_bertology

### PR DESCRIPTION
**Pull request by TobiasLee**
the `new_head_mask` index assignment operation makes it become a non-leaf node in the following gradient computation, resulting in grad is None bug as mentioned in  #3895

### CODE REVIEW

**Comment by julien-c** [comment]
This looks reasonable to me. Thanks for looking into it.

**Comment by julien-c** [comment]
can you run 

```
pip install -e .[quality]
make style
```
?

Thanks!

**Comment by TobiasLee** [comment]
Thanks for noting how to run code reformatting!

**Comment by julien-c** [comment]
Thanks!

**Pull request merged**
