### PR TITLE
pin gguf 

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR do ? 
This PR pins the gguf packages since it is incompatible with transformers integration of gguf file for now. I will unpin it when it's fixed ! 

cc @Titus-von-Koeller

### CODE REVIEW

**Comment by amyeroberts** [comment]
@ydshieh Am I right in thinking we have to explicitly build a new docker file, rather than change here? Or is this sufficient c.f. this internal doc: https://www.notion.so/huggingface2/Circle-Ci-Docker-images-3bedc8bc602e4ca88c34c6c194accd74

**Comment by ydshieh** [comment]
@amyeroberts 

No, for **daily** quantization CI job, it's this docker file to be modified. At midnight, a new image will be built automatically.

(I don't know much regarding if we run quantization tests on CircleCI for pull requests however)

**Comment by SunMarc** [comment]
As far as I know, we don't run the quantization tests for pull request !

**Review by amyeroberts — APPROVED** [review]
Thanks for updating and for clarifying for me @ydshieh!

**Comment by SunMarc** [comment]
Finally, I think we don't need to merge this PR !  https://github.com/huggingface/transformers/pull/32298

**Comment by Titus-von-Koeller** [comment]
Thanks a lot @SunMarc, really appreciated that you coordinated this ❤️

**Pull request closed without merging**
