### PR TITLE
Reorganize repo

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR reorgnaizes the structure of the repository by putting all model-related files (modeling, configuration, tokenization, conversion) in subfolders.

**Breaking change**

This breaks any import for model/config/tokenizer objects that is not done at the top level:
```
from transformers import BertModel
```
works but not
```
from transformers.modeling_bert import BertModel
```
It needs to be updated to
```
from transformers.models.bert.modeling_bert import BertModel
```

Internally, after this PR is merged the following will need fixing:
- the check_repo script does not properly finds the models now (so it does not check if they are properly tested/documented/ in auto classes)
- the new model template needs to be updated

The other internal scripts work as usual.

### CODE REVIEW

**Comment by sgugger** [comment]
Got approval offline from @LysandreJik so merging. If anything needs fixing, we'll do so tomorrow morning!

**Comment by stas00** [comment]
Question - if breaking changes are done anyway, why not remove the newly created redundancy?
```
- from transformers.models.bert.modeling_bert import BertModel
+ from transformers.models.bert.modeling import BertModel
```
why repeat the model name twice?

I guess keeping it the way you did will make it easier to know which files is loaded in the editor buffer list.

**Comment by stas00** [comment]
examples/seq2seq/finetune.py is failing after this PR:

```
Traceback (most recent call last):
  File "finetune.py", line 442, in <module>
    main(args)
  File "finetune.py", line 409, in main
    trainer: pl.Trainer = generic_train(
  File "/mnt/nvme1/code/huggingface/transformers-master/examples/lightning_base.py", line 398, in generic_train
    trainer.fit(model)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 444, in fit
    results = self.accelerator_backend.train()
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 63, in train
    results = self.train_or_test()
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 493, in train
    self.train_loop.run_training_epoch()
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 554, in run_training_epoch
    for batch_idx, (batch, is_last_batch) in train_dataloader:
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/pytorch_lightning/profiler/profilers.py", line 80, in profile_iterable
    value = next(iterator)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 46, in _with_is_last
    last = next(it)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 519, in __next__
    data = self._next_data()
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1169, in _next_data
    return self._process_data(data)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1195, in _process_data
    data.reraise()
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/nvme1/code/huggingface/transformers-master/examples/seq2seq/utils.py", line 251, in collate_fn
    batch_encoding: Dict[str, torch.Tensor] = self.tokenizer.prepare_seq2seq_batch(
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/models/bart/tokenization_bart_fast.py", line 127, in prepare_seq2seq_batch
    model_inputs: BatchEncoding = self(
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/tokenization_utils_base.py", line 2319, in __call__
    return self.batch_encode_plus(
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/tokenization_utils_base.py", line 2504, in batch_encode_plus
    return self._batch_encode_plus(
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/models/gpt2/tokenization_gpt2_fast.py", line 167, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/tokenization_utils_fast.py", line 433, in _batch_encode_plus
    return BatchEncoding(sanitized_tokens, sanitized_encodings, tensor_type=return_tensors)
  File "/mnt/nvme1/code/huggingface/transformers-master/src/transformers/tokenization_utils_base.py", line 242, in __init__
    n_sequences = encoding[0].n_sequences
AttributeError: 'tokenizers.Encoding' object has no attribute 'n_sequences'

Exception ignored in: <function tqdm.__del__ at 0x7f60b55d7b80>
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/tqdm/std.py", line 1128, in __del__
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/tqdm/std.py", line 1341, in close
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/tqdm/std.py", line 1520, in display
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/tqdm/std.py", line 1131, in __repr__
  File "/home/stas/anaconda3/envs/main-38/lib/python3.8/site-packages/tqdm/std.py", line 1481, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by patrickvonplaten** [comment]
The GPU tests throw this error: 

```
2020-11-17 11:24:06.538757: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/home/hf/actions-runner_transformers/_work/transformers/transformers/.env/bin/transformers-cli", line 5, in <module>
    from transformers.commands.transformers_cli import main
  File "/home/hf/actions-runner_transformers/_work/transformers/transformers/.env/lib/python3.7/site-packages/transformers/__init__.py", line 34, in <module>
    from .data import (
  File "/home/hf/actions-runner_transformers/_work/transformers/transformers/.env/lib/python3.7/site-packages/transformers/data/__init__.py", line 6, in <module>
    from .processors import (
  File "/home/hf/actions-runner_transformers/_work/transformers/transformers/.env/lib/python3.7/site-packages/transformers/data/processors/__init__.py", line 6, in <module>
    from .squad import SquadExample, SquadFeatures, SquadV1Processor, SquadV2Processor, squad_convert_examples_to_features
  File "/home/hf/actions-runner_transformers/_work/transformers/transformers/.env/lib/python3.7/site-packages/transformers/data/processors/squad.py", line 10, in <module>
    from ...models.bert.tokenization_bert import whitespace_tokenize
ModuleNotFoundError: No module named 'transformers.models'
```

https://github.com/huggingface/transformers/runs/1411825179

Not 100% sure what's going on there

**Comment by RORO-ML** [comment]
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-11bca228d6cd> in <module>()
      1 get_ipython().system(' pip install ./transformers/')
----> 2 import transformers

3 frames
/usr/local/lib/python3.6/dist-packages/transformers/__init__.py in <module>()
     32 
     33 # Data
---> 34 from .data import (
     35     DataProcessor,
     36     InputExample,

/usr/local/lib/python3.6/dist-packages/transformers/data/__init__.py in <module>()
      4 
      5 from .metrics import glue_compute_metrics, xnli_compute_metrics
----> 6 from .processors import (
      7     DataProcessor,
      8     InputExample,

/usr/local/lib/python3.6/dist-packages/transformers/data/processors/__init__.py in <module>()
      4 
      5 from .glue import glue_convert_examples_to_features, glue_output_modes, glue_processors, glue_tasks_num_labels
----> 6 from .squad import SquadExample, SquadFeatures, SquadV1Processor, SquadV2Processor, squad_convert_examples_to_features
      7 from .utils import DataProcessor, InputExample, InputFeatures, SingleSentenceClassificationProcessor
      8 from .xnli import xnli_output_modes, xnli_processors, xnli_tasks_num_labels

/usr/local/lib/python3.6/dist-packages/transformers/data/processors/squad.py in <module>()
      8 
      9 from ...file_utils import is_tf_available, is_torch_available
---> 10 from ...models.bert.tokenization_bert import whitespace_tokenize
     11 from ...tokenization_utils_base import BatchEncoding, PreTrainedTokenizerBase, TruncationStrategy
     12 from ...utils import logging

ModuleNotFoundError: No module named 'transformers.models'`

**Comment by RORO-ML** [comment]
Import throw this error:

**Comment by RORO-ML** [comment]
Import throw this error:

```
Successfully installed sacremoses-0.0.43 tokenizers-0.9.4 transformers-4.0.0.dev0
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-11bca228d6cd> in <module>()
      1 get_ipython().system(' pip install ./transformers/')
----> 2 import transformers

3 frames
/usr/local/lib/python3.6/dist-packages/transformers/__init__.py in <module>()
     32 
     33 # Data
---> 34 from .data import (
     35     DataProcessor,
     36     InputExample,

/usr/local/lib/python3.6/dist-packages/transformers/data/__init__.py in <module>()
      4 
      5 from .metrics import glue_compute_metrics, xnli_compute_metrics
----> 6 from .processors import (
      7     DataProcessor,
      8     InputExample,

/usr/local/lib/python3.6/dist-packages/transformers/data/processors/__init__.py in <module>()
      4 
      5 from .glue import glue_convert_examples_to_features, glue_output_modes, glue_processors, glue_tasks_num_labels
----> 6 from .squad import SquadExample, SquadFeatures, SquadV1Processor, SquadV2Processor, squad_convert_examples_to_features
      7 from .utils import DataProcessor, InputExample, InputFeatures, SingleSentenceClassificationProcessor
      8 from .xnli import xnli_output_modes, xnli_processors, xnli_tasks_num_labels

/usr/local/lib/python3.6/dist-packages/transformers/data/processors/squad.py in <module>()
      8 
      9 from ...file_utils import is_tf_available, is_torch_available
---> 10 from ...models.bert.tokenization_bert import whitespace_tokenize
     11 from ...tokenization_utils_base import BatchEncoding, PreTrainedTokenizerBase, TruncationStrategy
     12 from ...utils import logging

ModuleNotFoundError: No module named 'transformers.models'
```

**Comment by thomwolf** [comment]
I think maybe the `models` folder needs a `__init__.py`

**Comment by sgugger** [comment]
I'm always confused by why Python lets it works in some cases and sometimes not. Will push an init directly on master.

**Pull request merged**
