### PR TITLE
[HPO] update to sigopt new experiment api

### LINKED ISSUE #18145: the Sigopt api is outdated in transformers trainer.py, the old api could not work
### System Info

- `transformers` version: 4.21.0.dev0
- Platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.7.0
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- Tensorflow version (GPU?): 2.9.1 (False)
- Flax version (CPU?/GPU?/TPU?): 0.5.0 (cpu)
- Jax version: 0.3.6
- JaxLib version: 0.3.5
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1.enable sigopt HPO in example and run.
2. work log like"UserWarning: You're currently using the old SigOpt Experience. Try out the new and improved SigOpt experience by getting started with the docs today. You have until July 2022 to migrate over without experiencing breaking changes."

### Expected behavior

HPO with sigopt backend could work correctly without warning

### PR DESCRIPTION
**Pull request by sywangyi**
* follow https://docs.sigopt.com/experiments

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/18145

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

trainer: @sgugger

### CODE REVIEW

**Comment by mfuntowicz** [comment]
Hi @sywangyi, thanks for your contribution 🤗.

The current changes introduce a significant breaking change and we tend to limit them as much as possible.
Still, we though about this and we would like to propose 3 options in order to keep backward compatibility with previous sigopt versions:

1. Introduce a `if sigopt_version < x.y.z` -> previous behaviour `else` -> new behaviour in this PR
2. Split the current implement and the one introduced in this PR in two distinct functions and dispatch to the right one based on the sigopt version
3. Keep only the behaviour introduced in this PR but guard with a version check, raising an error if the version is too old to inform the user to upgrade its dependency.

Please pick one of the suggested options above (_or comment with potential other alternatives 🤓_) and we will be on track for merging 🤗.

Thanks, 
Morgan

**Comment by sywangyi** [comment]
@mfuntowicz hi, thanks for the suggestion, and choose option 1 and patch is uploaded

**Comment by mfuntowicz** [comment]
Thanks a lot @sywangyi!

It looks good to me, the failure in the CI seems related but I will let @sgugger have the final word 😃

**Review by sgugger — APPROVED** [review]
Thanks for your PR and maintaining backward compatibility. LGTM!
(Failures are fixed on main and unrelated to this PR.)

**Pull request merged**
