### PR TITLE
🌐 [i18n-KO] Default to English for Untranslated Pages

### LINKED ISSUE #23971: 🌐 [i18n-KO] Display English version of untranslated pages as a default option for improved UX
### Summary

We've been collecting feedback from our users, and a common theme we've identified is concerning the user experience when encountering untranslated pages. Users have expressed a preference to see the English version of a page directly if the localized translation is not yet available. This allows them to utilize tools like Google Chrome's translation feature to understand the content. 

#### Current Behavior:

Presently, when a user navigates to a page that hasn't been translated into their selected language, they're presented with a placeholder message indicating that the page is unavailable in their language. This leaves them without immediate access to the content they were seeking.

#### Desired Behavior:

Instead of showing a placeholder message for untranslated pages, users prefer to be automatically shown the English version of the page. This way, they can use automated translation tools if necessary. In addition, users can also choose to read the page in English if they're comfortable doing so.

### Additional Benefits

This approach provides several additional benefits:

- **Conflict mitigation:** This will likely reduce the number of merge conflicts that can occur due to manual reference edits in multiple language versions.
- **Easier Table of Contents (TOC) control:** By defaulting to English versions, we ensure that the TOC structure remains consistent across the site, providing a more predictable and streamlined user experience.

### Next Steps

We suggest implementing this feature to enhance the user experience and streamline the site's operations. This would involve modifying the behavior of the site when a page is unavailable in the selected language. We look forward to feedback and any additional perspectives on this proposed enhancement.

cc: [HF] @sgugger @ArthurZucker [PseudoLab] @0525hhgus @gabrielwithappy @sim-so @HanNayeoniee @jungnerd @KIHOON71

### PR DESCRIPTION
**Pull request by wonhyeongseo**
# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/23971

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
[HF] @sgugger @ArthurZucker
[PseudoLab] @0525hhgus @gabrielwithappy @sim-so @HanNayeoniee @jungnerd @KIHOON71

### CODE REVIEW

**Comment by wonhyeongseo** [comment]
In the initial implementation, I opted to prefix untranslated page links with `../en/` to direct the user to the English version of the page. However, this approach has a side effect of redirecting users away from the localized version of our docs and into the English one.

To address this, I'm currently exploring an alternative solution where we duplicate the entire English docs into the Korean directory. The upside to this approach is that it keeps users within their chosen language directory, even when viewing untranslated pages in English.

Additionally, this approach could also provide valuable insights about which untranslated guides are accessed the most. This data could help us prioritize future translation efforts based on user interest and need.

I'm actively working on this alternative approach and will update/open this PR once I have made substantial progress.

**Comment by wonhyeongseo** [comment]
While copying the entire English docs into the untranslated language directories has some advantages, I've identified a potential side effect. The copied documents are only up-to-date at the time of copying, which means they do not reflect any subsequent updates made to the original English documents. This could lead to outdated information being displayed for untranslated pages. What might be a good solution?

One potential solution I came up with:

#### Implement a continuous integration (CI) script to automate the copying process:

The script would copy the English documents into the untranslated language directories every time a change is made to the English version. This will ensure that the copied documents always reflect the most up-to-date information.

The CI script would trigger on every commit to the main branch (or whichever branch holds the latest version of your documentation). It will then perform a copy operation to the untranslated language directories, ensuring they're always updated with the latest English content.

While this does increase the computational requirements (as the script would run for each update), it would likely be a worthwhile tradeoff for maintaining accuracy and consistency in the documentation. This process can be optimized to run only when English documentation is updated, reducing the number of unnecessary runs.

**Comment by sgugger** [comment]
Thanks for your PR but this will make the repository heavier for nothing and make the doc building time longer for every PR so we cannot accept it.
The redirect should already be implemented on the website, we don't need to add pages.

**Comment by wonhyeongseo** [comment]
Thank you so much for your review, @sgugger . I definitely understand the overhead and will close this PR and issue for now.

**Pull request closed without merging**
