### PR TITLE
Convert tutorials

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR converts the rst files in the documentation that currently have a corresponding notebook to Markdown so I can then work on updating the script that auto-generates the notebooks form the documentation.

### CODE REVIEW

**Comment by mishig25** [comment]
You need to follow this format for the ColabDropdown to appear:
https://github.com/huggingface/doc-builder/blame/92bc1f3833fc825bd772455df17505d1f322ee88/build/transformers/master/en/quicktour.mdx#L43-L51
1. Put `ColabDropdown` svelte component after the title
2. And change `options` attribute

Also, for this change ti take effect, we need to merge various PR in a specific order:
1. https://github.com/huggingface/moon-landing/pull/1621
2. https://github.com/huggingface/doc-builder/pull/42
3. https://github.com/huggingface/transformers/pull/14655

**Comment by sgugger** [comment]
Thanks for the syntax! Will amend this PR but I think we can make it a bit easier on the documentation writer since all the links are automatically generated. I'll add a syntax `[[colab]]` (like we use `[[autodoc]]`) to the `doc-builder` and it will replace it with the component you created.

**Comment by mishig25** [comment]
@sgugger sounds great to me! could you add the parsing side for `[[colab]]` on doc-builder?

**Comment by sgugger** [comment]
Yes, I will work on that this morning. Feel free to merge the two PRs in order once they are ready, I want @LysandreJik to review this one anyway.

**Comment by sgugger** [comment]
Arg, rebase messed up the diff :-( Closing an re-opening.

**Pull request closed without merging**
