### PR TITLE
Fix whisper export

### PR DESCRIPTION
**Pull request by mht-sharma**
# What does this PR do?

Fix the export for the whisper model

The current export for whisper fails with error `Invalid Feed Input Name:past_key_values.3.encoder.value`, because the cross attention key values are not exported as input in the ONNX model after the new condition introduced in the [transformers@97a51](https://github.com/huggingface/transformers/commit/97a51b0c7d483cdf13ea878a987f9aa1c9eecc91).

The error occurs due to incorrect dummy input generation for cross attention key values for export. The PR fixes the same.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@lewtun

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Hey, would you mind adding a bit more context? What is the issue related to current export?

**Comment by mht-sharma** [comment]
> Hey, would you mind adding a bit more context? What is the issue related to current export?

Hi @ArthurZucker I have updated the PR description.

**Review by ArthurZucker — APPROVED** [review]
Thanks for this fix! 😄

**Comment by mht-sharma** [comment]
@ArthurZucker could you please merge this. I do not have the permissions. Thanks!

**Pull request merged**
