### PR TITLE
Trainer hyperparameter search kwargs docs update

### LINKED ISSUE #34239: `Trainer.hyperparameter_search` `kwargs` parameter has an inexact definition if using Optuna
According to the [docs](https://huggingface.co/docs/transformers/v4.45.2/en/main_classes/trainer#transformers.Trainer.hyperparameter_search.kwargs), those `kwargs` will only be used in the `create_study` method in Optuna.

However that is not exactly true, as we can see in `run_hp_search_optuna`. Some parameters from those `kwargs` will end up being used in the `optimize` method (which is great because it is what I wanted to do but the docs said I could not do it).

https://github.com/huggingface/transformers/blob/b54109c7466f6e680156fbd30fa929e2e222d730/src/transformers/integrations/integration_utils.py#L256

https://github.com/huggingface/transformers/blob/b54109c7466f6e680156fbd30fa929e2e222d730/src/transformers/integrations/integration_utils.py#L261

I didn't check ray or sigopt but I guess that something similar can be happening.

I don't really know what would be a good solution given that not every parameter in `optimize` is used and creating a `kwargs_optimize` would not make sense given that you support 2 other backends. Maybe a simple list of accepted paramters in the docstring?

If you tell me what solution would be the best, I could send a PR.

@stevhliu

### PR DESCRIPTION
**Pull request by GuillemGSubies**
# What does this PR do?

superseding of #34311 

Fixes #34239

### CODE REVIEW

**Comment by GuillemGSubies** [comment]
@stevhliu

**Comment by stevhliu** [comment]
Thanks for your patience and for trying out all these potential fixes! Unfortunately, it looks like it didn't work :( I'm not sure why the other CI tests aren't running for you. @ydshieh do you happen to know why the other tests aren't running?

**Comment by stevhliu** [comment]
@LysandreJik @ArthurZucker, not sure why the two tests just hang without ever starting. This happened in https://github.com/huggingface/transformers/pull/34311 as well, and opening a new PR didn't help. Do you think its ok to just merge this?

**Comment by LysandreJik** [comment]
Trying to push this branch on another to see if it triggers it

**Comment by LysandreJik** [comment]
I pushed the branch to another and it now works. Unfortunately couldn't get to the root of the issue as the last commit was too old; @stevhliu, let me know if you see this issue happening again. In the meantime, yes, let's merge it as soon as it's green.

**Review by LysandreJik — APPROVED** [review]

**Pull request merged**
