### PR TITLE
move code to Trainer.evaluate to enable use of that function with multiple datasets

### PR DESCRIPTION
**Pull request by peter-sk**
# What does this PR do?

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@lvwerra
@younesbelkada

### CODE REVIEW

**Comment by peter-sk** [comment]
@younesbelkada
@lvwerra 
Let me know if you would like a test for this.

**Review by younesbelkada — APPROVED** [review]
Thanks ! This looks ok no? cc @muellerzr @pacman100

**Review by muellerzr — APPROVED** [review]
This looks fine to me, but let's go ahead and adjust the type for the docstring and tell users how they can pass in multiple eval datasets as a `<Tip>` in the docstring to `evaluate` please!

**Comment by younesbelkada** [comment]
Makes sense! @peter-sk would you be happy to address:

> let's go ahead and adjust the type for the docstring and tell users how they can pass in multiple eval datasets as a <Tip> in the docstring to evaluate please! 

This would require slightly changing the docstring of the evaluate method in the PR

**Review by pacman100 — COMMENTED** [review]
Thank you @peter-sk for refactoring code to allow `trainer.evaluate` to handle a multiple eval datasets. Good from my side post addressing Zach's comment!

**Review by amyeroberts — APPROVED** [review]
Nice! Thanks for adding this!

**Comment by peter-sk** [comment]
Finally got around to changing the doc string and adding a tup. Any further requests for changes? Or is this good-to-go?

**Comment by younesbelkada** [comment]
Upon CI passing, that should be good to go I think

**Pull request merged**
