### PR TITLE
Authorize last version of tokenizer

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR bumps the version pinned in the setup to authorize the last version of tokenziers (which in particular contains fixes for the `run_qa` script).

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
~Yes, LGTM~

**Review by LysandreJik — CHANGES_REQUESTED** [review]
Actually, not LGTM. It looks like Transformers isn't compatible with the new version, as you can see in the failing tests.

**Comment by sgugger** [comment]
Yeah I forgot to add this in a comment -> Talked to @n1t0 about it and he says those are unwanted breaking changes, so we will pin to the next patch release he is going to make to tokenizers. Leaving the PR open in the meantime!

**Review by LysandreJik — APPROVED** [review]
The changes here look good to me (once the CI passes)

**Comment by n1t0** [comment]
Added a few more things to this PR:
- Use last tokenizers RC release
- Update the conversion from slow to fast tokenizers as described in https://github.com/huggingface/transformers/issues/9637
- Added a script to verify the conversion from slow to fast tokenizers looks good
- Fix some links to the hub

**Comment by LysandreJik** [comment]
Regarding the masks, should that be applied to all SentencePiece-based tokenizers? Should it be added to XLNet/ALBERT/T5 as well?

**Comment by sgugger** [comment]
Can't approve since this is my PR originally, but this looks good to me. We just need to make sure all special masks tokens are taken into account.

**Comment by LysandreJik** [comment]
Most of the tests are unrelated (a rebase on `master` will make them pass), but these two aren't:

```
FAILED tests/test_tokenization_pegasus.py::PegasusTokenizationTest::test_mask_tokens_rust_pegasus
FAILED tests/test_tokenization_mbart.py::MBartTokenizationTest::test_embeded_special_tokens
=== 2 failed, 3352 passed, 3280 skipped, 2512 warnings in 765.06s (0:12:45) ====
```

**Pull request merged**
