### PR TITLE
[ProphetNet] Correct Doc string example

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to the it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
Can we have the examples take less than 119 chars (i'd even settle for 200 honestly)?

![](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEhUTEhMVFhUWGBcXGBUVFRcXFRcVFRUWFxcVFRUYHSggGBolHRUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGy0lICUtLS0tLS0tLS0tLS0tLS0tLi0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAL0BCgMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAADBAECBQYAB//EADsQAAEDAgQDBQcEAgEDBQAAAAEAAhEDIQQSMUEFUWEicYGRsQYTMqHB0fBCUmLhFPEVI5KjM0NjcoL/xAAaAQACAwEBAAAAAAAAAAAAAAACBAABAwUG/8QAKxEAAgICAgIABgEEAwAAAAAAAAECEQMhBBIxQRMiMlFxgZEFYaHhFELR/9oADAMBAAIRAxEAPwDinsnZXbSCuNENx5Ln9m9IgR9IAaKtKmN15tXSUSoRMzKH5loq90Cc0Be930XjfRS2vGqP5q0WMUjCpYXN0u6pJsrvqdmIQfDfsFr7Bq7g6MgXqHakObcc0rhq7mmVcul0kkSicK0U06omq4C0JbIJ0TzarBaJ6qjKQKkZ9UEnZRjbaK9On0Umyv73kglN+izwaDtCllCDNkPISUQtLdUP7IOUajY0CFii3YBDnkqVHzYCUCjsgINi8LzQCVerIFh56INOm8m+nctVtXZp8GdWF980WhVdB5I9bBNiRqgktAuqTi/pM6KsBBlEdTEgqrX2RKD5N1cu3kg46S2AAqU6Df1eSJJ2SteoQVgr8IgatRaSIEc17sjYJYViJVqVQbo3F0RaCPog7BAdSg6BHqYibNQSTOsqRbIFpOA2CqQCdArO0QmVCCole0QY9z3KmYdEvXxBKqjWJtWyUDp1BoqOYQZiyK9s3gIZe4dVqn9jNSLB3RXa0FCDjqoc+dLKUGmWAOyA9hJRRoqit0Wiu9FhmsyhBqVkNziVQtgKRh7ZAlOoURzyUKm5MWUlSfghVpA1R6WIBsl3tVGEIXFSRBirUBMBeYFSIV6TSdELSSIXyu1XruNyj/4dUjssd5I/COFOc6aoIA/Tz/pYvJGMXJta/k2x4JzaSRfC8OJg7JxuDa3YLWbhSBAsOSrUwtlzpclyZ2MPEhjV+zG/wPeHoNe5K13BpA2C6rDYdlMEO/VM7lc5xPD/APWMA5bbdE1CX/UV5X0WvuDDcwSeJw7eaeb0SeJElaQbTOYDY0QiDDTove7AEq+HqyUTb8ooIzs2XmUwRfVer1Y2UisGiSs9kIr0YCSqtkWXsTiy7RWw7XQt4wlFWX1ZDWmEFlUg3RC68FTlBR3X1Iot71ejmoyiVGKcBEFCqtJFgioV2PCiAtbJYEOOisQRqFYPDRzKtUxEiCFVu9IySKsvuqVG2spaFFQq15DSKUZRSAe9Q0wgvqAd6vywqsJkChzFNJjnLRw+CB1uUM8qh5NYcecjKDFYroKWCb+0JhmCZ+xvksHzI/YYjwJv2jApszCN03R4dO0d/wBFo1qDafaa0A9FqYTCte0GIOo/tL5OVStaNIcHfzGI/hOWDMjuse5PcOaz4S0N/kNfFaNMEdioLc/qlcZgyx09Fg8vf5ZP8DcMEYbih6jNN0Ou37ouMwQ1Ctw+Kjcrr2kc97eiYwbpbkdqNJ5BIzk4v8eRuKQOg+wDj0HerOo9oEEWk/JVfQsbIDWEc0Kq7QbjoZbRkknfrokOJsa0EiJOs9O9XqvqAGBN55HS351WXWxLntLT8fKNe4FP48spbZzc2FpUYXE8SRdp+SXpMc4TKJWZmMJY1TStqF18NVXs5UX9wVRzmkgmycwNQHQ3QWVmP1QcTSLbsstZ41JURx9msTzS1UTaUjh8XbtFGDpNkusTizMM3CHmisqCIBUNoOi5UNw6in92EpMkMJuhvrRZepsM2Ko+kd1pqwuyC03NjqhVKcqGU4RWOGiH6XaAFSI0VspVqp5KsdVrdkIbGqrUdKguiyrJlRL2UQ958FUVDKO8yNEsJRR2iDjW80CtSI7Tb8x9lBlM0m2QP5dlxbTKYV5dutfDBw5JDB4MB1teS6jhvCHu/VHh9lnP4co2xzHOXlC2Fc4/p8inGOjXuXS8O4QWiXhp6jtHxkA8kDi2GYO023Pb5LkZ5QT+U6OCcn5MfEYcWJHmmcP0QakmExh6R5eA+iWk/lG0q2N1sPnb/IafYqtBgqMLHat0O9xH9ItOWifOdQeo2VmMpuduHHyPcl3JpU/0XS8oxaM0KvanX7rYfh4qAj9RnzEkL2MpFzDmHaGhHfZRh6uYT+027j/SKU3Jdv0y6CvdBI31hK4nExtJsB5Au9Y8Uag/PUc4afD5eiDWpZhmB3IJ2tOyqFRdMFuxZ+IgXid+n9rOx5a7oeY152U5h1dGw08zr5K+HwbnO09deQnwTaiobM3K1RzeMokGUi+lMyu14nwR1NuY6309fzmFzFXCGLaLo4M6aORyePT7RMOozKbIv+dLcpWkzCTaEpUwYDoKfjmi9Cik0ZTxey3+FYSwlSzCU2xKtTqZTY2WWXL3VRBHHtI7kpUfeyP/AJVoSGMrXkLDHBt0Q8apaVAxMlLtqSbq5IBTPw17RQd7wUrUbBU1a3JVL0UItEJqVAq5lJIVYR0WXc0m6GHc1Y1UN1UclEmUGVShirNgiUnRqpTRLJyRdHp4gAIb6k9yggQgatbIMMxJYcw1XYcC401nxDvtYab76riKcLRw0EDW5lL54JxoZ48qZ9Fr8WBG0QT/AFZc7W4iarg0mBtMfPksjFYxxkAwNvRK4EuLufJc6HGSTbOosm0kdlTaPl+Rz8FHvBOpHcJn5rPouMI9OkXGO1/23npsUs4KxztoepEudMyNAdCOhnUeYTpwod2bhw0KWwWEqDRmv7z6ACy3sHwp7v8A1II5iQR91jNSnKoAOairZle9LTlfvoef9pam0h7287/MrY4pw4CQHEgaTqD0KyXvu1x1Fj479dln1cW4+w4SUlaPYKg5zWtBiSSXchO3UrbqcFaWhmbs9DEnqs3B1spibfIG+/l5qON8QNIPMw1rS/yBMI4yt1RlkTvTHv8AjaFEEvcxg6kBZlf2uwLTkp1GE6SDPz0Xxvi3Fq+KqEveSJs0nsjeI8FGGwzqtRtJjZe9wa0fyJgCV24f0ldfnlv+3/r/ANHLlzd6Vn2atxVrxDog7zYjvC5XHUGl8U7dOnNZ/CeC4rJlz5Syu7D1abtadQMztII1aQD4jrberYRtBwaCXO/U46k/ZJSwrjzpStjuPIssdIycRhsozLCxbiTK63HVg9sFcxWMSITnEm35Wzm8vEoStAHscDrIVmPVhWblM6pJuITqi5LaFBz3hNkRlIwTBI5pam+y3cFxNjaWUiXX2t4q4wjdPRTb9GLUoCJCoxlrpqSTprsFOIERZZrI/BYo7DoD2wUxXrJU1breHathBHFAzHkiOqnkqe8PJGkQZ4jhQyq4AyAdkFolM4Gu33uarpcnvTPEqlNz81Ow8lcvFgIRbSVqmirUfdCL+qzSbCCMadFctjRVadIV3vhU7souHRqj4OqB4JMAuum6FA67LOaSWzTFfYtUfz/D3JzgrM7oa1020Nvk1ZuIsTdaHszRLqvIc9j0J5LHJFfDbHYT+dH0bhfA5aCQfH+wtnDcMoUhJIneIWf/AMmGtidhAGi4L229rXCadN0bOcPQH80XJxY3kydIq/z4X6G8k2o9pOkfQsf7S4PD2c5gPIuCz2e2zKpIpEEDZrgvgj6r3mSfzZanC6NU1qVOi4Co5wa1xOUS4/qJ2uus/wCmvpXf+FS/wIrlR7bj/mz7HW44HgwQCNQdUJtQO8vA8vRcUcW5mIyVABUa40qjWmW5wYkH9pmV0+GxcAgiT+GVxuRxXj/J08OVSevAw50mN9PLX0Wf7XOLsI9wv2YPeHCUcVIfE63nfeyFj6Rq0alLQuFu+8R3oMS65Iy+zRtlj2g0j49SqQRtBn1+6O/GwQWGHAggixBFwZG6viOE1WuIc0i+uy0OHcJoNcHYl4LR/wC2wyXdCbQF655IqNrf4PNdXdM7j2Ee8YRrquZz8Xi84mXOLadJ0vO5uzXqE/xf43TrKJ7P0KpP+XWZ7tjGFmHpR8LTEuI2kAeXnXLMuN5PgvN8id5b9+/36/SOzw4NQMZ5nSVjY0gOvuuoqUxt5rnOJUpeTa3QJnjSTZjzl8pl1GHUaITmCQU3igABCTJ56rqwdo5NBqYKYZVgQdUs2pY81AZMc0Mo35IaeGde69iXSlqNlNRpKX6pSCQvUpklXbhYVokwjudFgtpZGtIsSq041QYCZxIJQsq0g9EAht7oodyViFAYi8lAqjkMOujOYhGxVogemjZRul2E6ozJNyEEiIaa3omw6B/azGPErTBLm7ec/MWS+WL0MYWZ+LR+G8UNKw07kviKRH59kGi0k2uUfVONM02mdDiONPcIpsc8xqGmJ3XHcboPGSo64fJPR02nwX0Hg+NcxgFiI0sFXi/s7UrNNSg0PYQc1IfFrMtnXwSvGzQxz6pV/f7mvIxzlFM+WCpzG8+n2TD8ZaB+FO4zgrmugyzpUa4ELQ4T7I1KzgGBz9JyMdHi90NHzPRdR5oRVtiCg26oy+CVne9bc3c2T1nmvotCuZ8Ofzv0SXEfZhuGNGnMPmTGlhpP1TrqZaJ1+i43LzQzNOJ1uLilBbCMq8/HroPujU3EHp+fJIUauvojtqJSWNj8ZmhhiM2bIHg/FTIBPUt6roKFHBU+2zDtzbENGp1WPwFnvHFoEuF10R4e4H4fHZKTnkjKopmeSONvZm4tz6pzEQ0aDQW/PksrGaRfwH1WtxOvAgAk/KPz/awnNb8VV7jya209J+wRYYdtl2kgFEQNFz+OxBDjmgd4AP3K6vEvLaRLKbGf/fM58eJ9AuYxHFIFw13g5o8Mrgunxoq2/Jy+dN2omJVqS6QrloeQEy7EscbsI6tdmH/a+fVSaAjM0g+GU/byK6MmkjnAG0gLKfdhXoUJMK9emQYgrNyd1ZAetl4tJ02RW0Mo1RWUQdEDml4CoUbSmSom6JVZlKLSDYndE5asoG5shC/xjzTobmBQPclDGTXssQDZTVOmISlFpceiZfWEQE7RKF6jCgOaEc1ospw9EON1LoqguEoyr4mkdEz2WgRZQ2swm5S/dt3Rp1MoUzzTtCk6Jv4olSgMwg6rSZSAAgaKsmZVoPFHdmSQf6hGw2H336R6p2P9NAnz2VRTveI5CT6fUrFztUhqNXY/h6jiL5oG9/VN4fFuY4ZHFvTtX7ykC+RHwgbanwvZNYLFTbsgDUnUjzCSnH2OxaaOow/FqjtQ1/VzQdo3E7lP0+OvaPga3rAA8FztHFM2LOepH1hMf8g0XGQ97wD4HMk+s71aCahW0iOL1ffVWv1gK9XhZe05dYHVUw2Na55Ef+RrvGYkea7D2foUw2XESdBPJFHHOU1FP9lPMoxuj5FVo1WVw1wLQ4gS4ECdoO/Jb2Ew9OSS8PyHKWiWw+QA10iQLr6xWwdOoIcxp7wFyftD7M02B1WmS2XNdUGoe1pGad5yT8l0skXGKsww8iNtMY9i+GENNdzWtc8CGiSGjbVdHXzEQNIu77DbvQOH1WhgiAIEcgjVyCIP+/D7qY+vT87FsspSnbOW9oKLBYHS5E7/AMo9Fk0aTTp0uBBPjr4WWl7QNa0ANMep7+XcFlsf1XLlPq31OljjcVYy+QMrWjydf6Lh/aHF1qVUtLWZTcWcPm1wXZ2IWP7R03OpnL2ovlcJB8Nu/wBFtwuR1yK/Zly8PfHryjjzxFhHapNB5sJHiQZJ8wrH3Z+F5AOxH0v6rNrgfpBB3abgdx+6Z4eJ+LZd+cUo2cM0+H0w0ib9VoVKrJ2Wdh3AyNAq1CBcXXPlHtLYfojEgaymMNWpwAs/EvkSlQDst1h7R2wbNzF0mlpIusgOTbMR2IS510uqxpxtMFlmV4TQrjkg06faEhaP+O3ogyOKCRgkQ2AkH4jWE1iK+ULPokmTzXSRctF6YcbpykT5IAqZe5XbrIKp7BGKlQmyrkgqacnZXqkCFn4dEsZ4a2XLYeLLN4aZPctNoSmV3OhnF9IkAZVwAfsorWSD6haeinVSWg06G3Eg2H59k1hqFR5AZTc4u0sYJ74+aFg3Oc3M53u2fusCd4adUR/EBdtMu7ViGZs9To+q7tR/FoVrCvYfxX6DPwzaboxGIpMI1Y0mpUnkQyQ3xM9F6pjaDRNN2HP8qr6z3Hupim1o8QUvQwLA3M+nTY2bTL3Ho1xJaT0DHdYTzuIsZ2aVFoI1ysYD3vIGVvlPOETxwS0T4k2avs5j8xHba4f/AB0mtb4nK0/JdjhOJtEtBPMGMre4GPovmjeMVXOl7xH7W38JNo7jC6jh3FQRqI5THkUr16tv0Hdne08TIDrTHPnrCDxWoH0nt1zNIHiI+q5vDcSDnjK4TpJk+RK3cMWgC87ye/ZZyyt6RFBLYnwypVawNLdAB5C+vVI8S9oS05Wi9xmmVqcQxrWNdJjr9VyBw4eXOGh+qUnJrV6GIdPLQrjMYXG5k9VajiRumncMBCSxfCnNu0oE4PRp8QNUxY/SUA1c2qQptymCbq1fEeaNY0noJTsxOL4LK8kXBvpceO6zqQdPRbmIqFzTzWdBAFl1cWWXWmcfkY+s9eGBqTEjRAZWJsmX0nRbRKVKd0zBa2Y9Q3ad3LzhELzczR0U08QDsqfb14Bou7mEajUAIJQCQVLgCICBxTWyDb3tJuUwKlPms8YR0SE02gY0WUoxryWmctUk3KswIz6cqjbLp2CWAnVFpjyQjZVzRoUNWQc/ypNgikCJKzWPIKuXkoHj+xDd4Ude6fstSmbLL4PGU+qZq1C3833SmT6hrH9ISuhCi0DM+42bu4j6dfXRebWESfLn/Sg9p0nfYchsOQQwTsJieIqPqOE2FgAAYE/paNSSfE6ncq7sUykOy3M/kbt//cfEf4Ds882ipjsRAys1IjMOv6Wcgdzqe5ZjKnuxa7zYfxG5H8tp740lNxVmbdHRU8ZDpqnNV3H7P4z+nuGmlt/FvvNp5NAho6wPXVJcI4Q50TYL6BwrgQaBbWNUtlzQi6j5NYY5NWzl8LwBz5sY/N1s8O4F7q+WTzmV1DaDWnK7w5JTi1I2LSRGy5+bJPJpMZglEVpAk5RbvQKnHDSfkds06X8OiZIa+nfr8l809pq7qNQgWEWnS86KuJxlKdMrLlqNnX8Y9oA+zDsJ5xy8DHmUxhqU0wZuL23hfN+C13Oe4k306Qu8wWL7BnT6Jvk8akkjHHls1KeLOXXZL4rEl1PU3GqQ/wAwCxKBWxvZyjol48P2G8ozxSlmpZmmCBM93NcUONOB7Wq651eaZB5H0Xz2rqe9P8TCurUkY5M0otUbY4y0rz67iJbfu18lz6ltdzdCmv8AjxW0Zyzd/rX8HSYSqTdxsorN3CysNxGT2/7810eHpMqslhBjUbhZzXXyRL2hWlUkQUjiKLgbbpwCHQoxBt1RJUBLYNrCBBTFGiSRZKszQtDCVnFwjyWOWTS0ZrybnDsOcpkI2Zn7fkiU3ENvYK/Y5rjyk7NaR83c9Cb1XiIsdQrMC9LVGBbKN9FJaAbCyPSaIuvPbfoEHbZBd1NXaZEaKzpPcquZMQpZZ0HBGQwfkpiswE30S/DgWsnwVi8uI6JCf1McgvlRZ1Hc+X5sksa61j39Ry/P9tYlr3Enb8+yzjObKfz8stIPemRxdbFsxcIaL6T0T+CwrWmTd3yHRXZSg6bIuAdclTJPstEiurN3gT5fG0T5QPquxr4khvZOg0XzrDcR93WaBfY32P13XXsxRi/JLyx1FaDUm3sbdiRUbDrHY8j0Q6WMmWuuRvzhZdfGwYlZ+Hxkucevr/tBHG3sJySNOvig2Y09F829ruJNrVBkuGjXYzp3rqOP4uGOvqF88LCnuLgUX2YtlyXomhWLHBw2+a36ftLLQ0tOwJH5+QucRqFPdOSin5ME2vB0FDiOaC46aBTW4nDp1WOoKHqgrNHFcWc4Q2w3+3zWYQrKpRJJeCmyhVHIjlQqygZTvDcc6m6QeneOSTVSFGrLTp2dPTfmGYGVSrUOyzOG4mOyd/XZaVClmIKXkuvk0bVD2AeCe1putmhTpyDSEkJLCtY07Jugxx7VMxfRczLK3rQCNUYjMC1wiFYVR+1VMRJ1hBFN3NJJINnzg3Ku10FeDo2VnFem8mA2DIV2uiyWoPlXqVLFYtFhK1EAzNihioJsLJY1LImGItZEo62Udfw6l/02z3q7MrfEwpwDuwO5T7sGTy/2uPkdyo6uPUT2Jqjl3rLp0odmTGMbG/RUPwwjx6VAz2yKbpM2IUV6wpgkC50HVVwrIcRKzsfVLqxGgbAjvuT6eSYhDtKjN6AMx4p1mZr3kk9V2WHxzKjew4GPvoV8wxjy5znHnHkj8OxL2E5XEfk/ROywqSFnlfazrOL8QyGx8FnYfjZa42sZPisyvWLjJMoTyrjjUVRUpNjOLxz6nxHfZI1gryqkrRIEDTo80wAqtKsDurIWUKSfzvVCVCHiqyvSqlQo8SquK9KqrIQVVWUKELUnQV0NMgNtqVz1IXW06tFoWc1bI/A0yrcX71uUXtpjXVcxhj2ls03TAInxSPIgrSIjRo48k2uFoDHNWacMxrA4Az3rKdWM7+aVWGOTwFZ//9k=)

**Comment by patrickvonplaten** [comment]
> Can we have the examples take less than 119 chars (i'd even settle for 200 honestly)?

Can I break lines while using `>>>` ? Or just use a smaller input text?

**Comment by sgugger** [comment]
> Can I break lines while using `>>>` ? Or just use a smaller input text?

You use `... ` instead of `>>> ` for the intermediate lines, but yes you can. See the [quicktour](https://github.com/huggingface/transformers/blob/master/docs/source/quicktour.rst) for an example (scroll down to "That's encouraging! You can use it on a list of sentences" since GitHub doesn't let me link a specific line in a rst file).

**Review by sgugger — APPROVED** [review]
Thanks :-)

**Comment by patrickvonplaten** [comment]
> Thanks :-)

My Pylinter doesn't pick up the docstring :-/ will have to find a way to fix this. Sorry for all those long lines in the docs

**Pull request merged**
