### PR TITLE
Update examples with image processors

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Updates all of the feature extractor references to image processors in the `examples` folder.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by NielsRogge — APPROVED** [review]
Thanks a lot for fixing! 🙏

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Comment by stas00** [comment]
This broke deepspeed tests. Fix is here: https://github.com/huggingface/transformers/pull/21283

when modifying examples and breaking back compat please scan the slow tests and adjust those too. Thank you!

**Comment by amyeroberts** [comment]
@stas00  - thanks for applying a quick fix and apologies about the break. I'll make sure to remember the slow tests next time!

**Comment by stas00** [comment]
Thank you, Amy!

`tests/extended/` and `tests/deepspeed` are the ones that heavily rely on `examples/pytorch`

**Pull request merged**
