### PR TITLE
Bugfix/alexsherstinsky/fix none check for attention factor in rope scaling 2024 08 28 0

### PR DESCRIPTION
**Pull request by alexsherstinsky**
# What does this PR do?
* This PR fixes a small bug in "src/transformers/modeling_rope_utils.py" whereby the check for `attention_factor` can raise `"TypeError: '<' not supported between instances of 'NoneType' and 'int'"` if `attention_factor` is `None`.
* The test `tests/utils/test_modeling_rope_utils.py::RopeTest::test_longrope_rope_numerically` is extended to ensure that the `config` is validated and the above error is not raised.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by alexsherstinsky** [comment]
Hello, @ArthurZucker -- could you please help me with some guidance in terms of what I need to do in order to get this pull request reviewed (and merged, if approved).  Please feel free to make edits on my behalf.  Thank you very much in advance.

**Comment by LysandreJik** [comment]
Hey @alexsherstinsky, Arthur will review your PR as soon as he has a bit of bandwidth available! Sorry for the delay, the repo is particularly active right now.

**Review by ArthurZucker — APPROVED** [review]
Thanks for finding and fixing! 🤗

**Comment by alexsherstinsky** [comment]
> Hey @alexsherstinsky, Arthur will review your PR as soon as he has a bit of bandwidth available! Sorry for the delay, the repo is particularly active right now.

@LysandreJik Many thanks to you and @ArthurZucker for reviewing and merging -- your libraries are a treasure trove!

**Comment by ArthurZucker** [comment]
🤗 thanks for your warm words

**Pull request merged**
