### PR TITLE
add back self.max_position_embeddings = config.max_position_embeddings

### PR DESCRIPTION
**Pull request by chengchengpei**
# What does this PR do?

Fix https://github.com/hiyouga/LLaMA-Factory/issues/5461

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by chengchengpei** [comment]
@zucchini-nlp ^^ can you take a look at this change? ^^

**Comment by zucchini-nlp** [comment]
@chengchengpei I am not sure why the error is being raised, as the new RoPE doesn't need any position embeddings in its init. Am I missing smth?

**Comment by chengchengpei** [comment]
> @chengchengpei I am not sure why the error is being raised, as the new RoPE doesn't need any position embeddings in its init. Am I missing smth?

@zucchini-nlp thanks for your reply :)

I am new to transformers. 

i used llama-factory to fine tune. last week, it works. but yesterday, i saw some errors described in https://github.com/hiyouga/LLaMA-Factory/issues/5461

i tracked the code changes and found `self.max_position_embeddings = config.max_position_embeddings` was removed  currently. i can run the finetune again after i added it back. 
if `self.max_position_embeddings = config.max_position_embeddings` is not required, how to fix the errors i saw in https://github.com/hiyouga/LLaMA-Factory/issues/5461 ? thanks for your help.

**Review by zucchini-nlp — APPROVED** [review]
I see, just for my own understanding wanted to know where exactly the attribute is being accessed. I'll try to reproduce it later :)

Thanks for fixing this! It is in line with Llama and seems to be causing bugs while tuning, so we can have it back

**Review by ArthurZucker — APPROVED** [review]
Okay, cc @gante to take into account if we refactor

**Comment by chengchengpei** [comment]
@zucchini-nlp 

thanks.

when this PR can be merged?

**Comment by zucchini-nlp** [comment]
Yes, sorry. I was off for a while, merging :)

**Pull request merged**
