### PR TITLE
oneccl_bindings_for_pytorch 1.12.0 prebuilt wheel does not work with …

### PR DESCRIPTION
**Pull request by sywangyi**
…PyTorch 1.12.1

raise error in this condition and update the doc

Signed-off-by: Wang, Yi A <yi.a.wang@intel.com>

Fixes # (issue)
torch 1.12.1 does not work with intel ccl 1.12.0

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@sgugger

### CODE REVIEW

**Comment by sywangyi** [comment]
@yao-matrix @sgugger please notice the issue and help review

**Review by sgugger — COMMENTED** [review]
As was said before, we cannot constantly update the library like this for tierce integrations.  Also Transformers does not work with PyTorch 1.12.0 (all audio models will fail).

**Comment by sywangyi** [comment]
@sgugger I agree with your point, so I upload another PR (https://github.com/huggingface/transformers/pull/19151) to only update the doc.

**Comment by sywangyi** [comment]
we will release a new oneCCL 1.12.1 to work with torch 1.12.1

**Pull request closed without merging**
