### PR TITLE
Add Multimodal heading and Document question answering in task_summary.mdx

### PR DESCRIPTION
**Pull request by y3sar**
# What does this PR do?
From #18926 
This PR creates a new Multimodal heading in task_summary and add Document question answering task example inside of it.

# Who can review?
@stevhliu

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Really nice - thanks for adding!

**Comment by amyeroberts** [comment]
@y3sar - The current CI tests are failing because this PR triggers tests checking code snippets in the docs, and the doctest CI environment doesn't have ffmpeg installed. I've opened a PR #23329 to resolve this. Once I've confirmed everything works, we can re-run for this PR and if all green then merge :)

**Review by stevhliu — APPROVED** [review]
Looks great, thanks again for your contribution and for adding the new multimodal section! 🤗

**Comment by amyeroberts** [comment]
@y3sar  Sorry for the delay in this. There's been a lot of changes in how doctests are retrieved and run. Could you rebase onto main to get the latest updates?

**Comment by y3sar** [comment]
@amyeroberts sure thing I'll rebase and commit again

**Comment by amyeroberts** [comment]
@y3sar Did you force push after rebasing the branch? The current commit history looks like what I get if I push but don't force.

**Comment by y3sar** [comment]
@y3sar no I did not force push. I rebased and pull pushed. What should I do to solve this problem?

**Comment by amyeroberts** [comment]
@y3sar To rebase onto main you need to force push, as rebasing is a form of history rewrite. The steps are: 

* Get the most recent version of main: `git fetch upstream main`
* Rebase: `git rebase upstream/main`
* Push changes: `git push -f`

**Comment by y3sar** [comment]
@amyeroberts ffmpeg bug still remains. What can I do to solve this?

**Comment by amyeroberts** [comment]
@y3sar You'll want to modify [this line](https://github.com/huggingface/transformers/blob/860d11ff7c4235e0baaeee50d96cf1686781bdd3/.circleci/create_circleci_config.py#LL455C14-L455C15) to: 

```python
"sudo apt-get -y update && sudo apt-get install -y libsndfile1-dev espeak-ng time ffmpeg",
```

**Comment by y3sar** [comment]
@amyeroberts should I commit in this branch or should I create another pull request?

**Comment by amyeroberts** [comment]
@y3sar Apologies for the delay with this PR. Could you rebase again and push. We've been having issues with timeouts on the CI which should now be resolved. Additionally, could you update the extension for the `.mdx` to `.md` please?

**Comment by y3sar** [comment]
@amyeroberts thank you for remembering this pull request 😄😄😄🙏
Yes ma'am.

**Comment by y3sar** [comment]
@amyeroberts looks like the timeout issue remains. Should I change the code example?

**Comment by amyeroberts** [comment]
@y3sar Let's draft in help from the king of tests @ydshieh :) 

I did a test run of this example on a CPU and it took 40s, so not fats but not super slow either. I think we could try:
* Another checkpoint. Are there any other smaller DocQA checkpoints we could use? 
* Forcing this example to be skipped in the tests

**Comment by ydshieh** [comment]
Let me see what's happening on the CI runner.

**Comment by ydshieh** [comment]
Hi, I checked. That `task_summary.md` is considered as a single test , but it has multiple examples (and the checkpoints are not always small).

I can change the environment variable to avoid this situation. Once that change is merged, you can rebase and the CI should be green.

**Comment by ydshieh** [comment]
The PR is opened 

https://github.com/huggingface/transformers/pull/24753

**Comment by ydshieh** [comment]
That PR is merged into `main`. If you pull the latest `main` and rebase on it, we should be good to  merge this PR.

**Comment by y3sar** [comment]
Thank you the king of tests and @amyeroberts should I check for a smaller checkpoint?

**Comment by ydshieh** [comment]
> Should I check for a smaller checkpoint?

It would be always great to use a small(er) checkpoint for testing (if there is any) 🙏 Thank you @y3sar

**Comment by y3sar** [comment]
@ydshieh @amyeroberts I have found some small(er) models. The model that is being used currently is 803 mb. I have found a [checkpoint](https://huggingface.co/magorshunov/layoutlm-invoices) that is 500 mb. Which is still very big but smaller. And also I have found an even smaller [checkpoint](hf-tiny-model-private/tiny-random-LayoutLMForQuestionAnswering) that is used for testing by the huggingface internals. But the results are not that reliable.

**Comment by amyeroberts** [comment]
@y3sar Thanks for looking into this! The tiny models are just for internal testing and probably not something we want to have in the docs (we want to be able to adapt to our needs without considering breaking changes). I'd say go for the 500MB one :)

**Comment by amyeroberts** [comment]
@y3sar Thanks again for iterating and adding this!

**Pull request merged**
