### PR TITLE
Add DebertaV2ForMultipleChoice

### PR DESCRIPTION
**Pull request by zphang**
# What does this PR do?

Adds `DebertaV2ForMultipleChoice`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@LysandreJik

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
From a first look this looks good to me, essentially a tweak of the `DebertaV2ForSequenceClassification` with additional preprocessing of the inputs to handle multiple choice inputs.

WDYT @sgugger?

**Comment by zphang** [comment]
Also for additional context, the implementation of the multiple choice model is taken from `RobertaForMultipleChoice`.

**Review by sgugger — APPROVED** [review]
LGTM, thanks a lot for adding this model!

**Comment by LysandreJik** [comment]
Thanks for your contribution @zphang!

**Pull request merged**
