### PR TITLE
Update generation_logits_process.py

### PR DESCRIPTION
**Pull request by willfrey**
# What does this PR do?

If you're using type hints, then passing an `int` where a `float` is annotated is acceptable as per [PEP 484](https://www.python.org/dev/peps/pep-0484/#the-numeric-tower).

This makes life a little nicer.

~Fixes # (issue)~

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by JetRunner** [comment]
Hi @willfrey, I've merged many of your PRs but I don't agree with this one since there is no integer between 0 and 1 so it'll be nice to have the instance check here (in case someone passes a tensor or something).

**Comment by willfrey** [comment]
I’d suggest checking against numbers.Integral then because that’s the ABC/protocol for anything like an integer.

**Comment by willfrey** [comment]
Sorry, not numbers.Integral but numbers.Real.

**Comment by willfrey** [comment]
I'm just trying to not have it raise an exception if I pass in `1` instead of `1.0` because I can't rely on passing `None` to default to `1.0` because it may be overridden by a model's config.

I can change it so that it checks against that and won't yell at you for passing a `1`, if you'd prefer.

**Comment by JetRunner** [comment]
> I'm just trying to not have it raise an exception if I pass in `1` instead of `1.0` because I can't rely on passing `None` to default to `1.0` because it may be overridden by a model's config.
> 
> I can change it so that it checks against that and won't yell at you for passing a `1`, if you'd prefer.

Hi @willfrey I checked again and I think the best solution is to add a try-except for the typecasting `float()`. If it throws an exception we should catch it and tell the users you should pass a number

**Comment by willfrey** [comment]
Sure, I’ll make that change!

**Comment by JetRunner** [comment]
@willfrey Hi, could you make the change as we discussed? I'm pinging again since the stale bot is pinging.

**Comment by willfrey** [comment]
Hi @JetRunner.

Sorry, had this drop off my radar.

Do we want to re-raise an exception from just calling `float(top_p)`? That'll throw a `TypeError` if whatever the original `top_p` parameter does not support being an argument to `float(...)`.

It'd basically be:

```py3
try:
    top_p = float(top_p)
except TypeError:
    raise TypeError(f"cannot interpret {top_p!r} as a float")
```

which seems a little redundant.

Happy to make the change if you want, though.

**Comment by JetRunner** [comment]
You made a point! I'll just merge it as it is now.

**Review by JetRunner — APPROVED** [review]

**Pull request merged**
