### PR TITLE
parse arguments from dict

### PR DESCRIPTION
**Pull request by patil-suraj**
This PR adds `parse_dict` method to `HfArgumentParser`  to allow parsing arguments from `dict`.  

I find this necessary for notebook workflows where I'm not using `Trainer` from command line. Otherwise I need to write arguments to json file and  use that path with `parse_json_file` or pass a list of strings to `parse_args_into_dataclasses`. 

@julien-c @patrickvonplaten

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @patil-suraj :-),

Hmm, not sure we would definitely need that...let's say you have a dict of arguments that you want to parse it into a dataclass like `TrainingArguments`, you could just do 

```python
training_args = TrainingArguments(**your_dict)
```

like it is done in the Reformer Colab for example: https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/PyTorch_Reformer.ipynb

Can you give me an example, where going over the `HfArgumentParser` instead of directly instantiating the dataclass makes more sense?

**Comment by patil-suraj** [comment]
@patrickvonplaten 
wouldn't this 
```
train_args, model_args, data_args = parser.parse_dict(your_dict)
```
be better than this  
```
training_args = TrainingArguments(**your_dict)
model_args = ModelArguments(**your_dict)
data_args = DataArguments(**your_dict)
```

Anyway, its just a small utility, so if not needed by lot of people we can close this.

**Comment by julien-c** [comment]
I'm ok with merging this!

Always nice to add a unit test though:)

**Comment by patil-suraj** [comment]
closing this, accidentally merged upstream into this. Will open a new one

**Pull request closed without merging**
