### PR TITLE
docs: ko: tasks/awq.md

### PR DESCRIPTION
**Pull request by ahnjj**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Hi @ahnjj, thanks for opening a PR to add this translation! We should have a review from a native speaker to verify the translation - is there anyone you know in the community who could do this? 

cc @stevhliu

**Comment by SangbumChoi** [comment]
@amyeroberts Do you need any help on this?

**Comment by SangbumChoi** [comment]
If you guide me which one to look then I can do this @stevhliu

**Comment by amyeroberts** [comment]
@SangbumChoi Thanks for offering! 

> e.g. @ahnjj translated only tip part is this enought?

No, the whole document page should be translated. @ahnjj If you still plan on completing this translation, could you ping us once the work is complete?

**Comment by stevhliu** [comment]
The PseudoLab group has been doing excellent work translating all the docs to Korean. @jungnerd recently updated the toctree to include the new quantization docs here https://github.com/huggingface/transformers/pull/31969. Feel free to also ping them for a review if needed! 🙂

**Comment by jungnerd** [comment]
Hi @stevhliu 🙌
@ahnjj is one of our teammates 🤗 
I think her translation isn't done yet, so we'll let her finish it!

**Pull request closed without merging**
