### PR TITLE
[Doctest] Add configuartion_longformer.py

### PR DESCRIPTION
**Pull request by AShreyam**
# What does this PR do?
Fixes # 19487

Add configuration_longformer.py to utils/documentation_tests.txt for doctest.

Based on issue https://github.com/huggingface/transformers/issues/19487

@sgugger could you take a look at it?
Thanks :)

### CODE REVIEW

**Review by AShreyam — COMMENTED** [review]
I updated the configuration python file for longformer and flava.

**Review by sgugger — COMMENTED** [review]
Same as in the other PR. Please don't touch the order of the imports and run `make style` on your branch to make sure the quality tests pass.

Thanks!

**Comment by ydshieh** [comment]
Hi @AShreyam

This PR is not ready to merge. It contains other changes that is not for this config doctest sprint.

**Comment by ydshieh** [comment]
Hi @AShreyam

This PR is not ready to merge. It contains other changes that is not for this config doctest sprint.

**Pull request closed without merging**
