### PR TITLE
Pytorch type hints

### PR DESCRIPTION
**Pull request by IMvision12**
# What does this PR do?

Added Type hints

## Who can review?
@Rocketknight1

### CODE REVIEW

**Review by Rocketknight1 — APPROVED** [review]
Woah! This is a really big type hint PR and I couldn't find a single issue. I'm not sure if you're done, or if you're still adding more, but ping me if it's ready and I'll merge it!

**Comment by IMvision12** [comment]
Sure, I will add all type hints for pytorch and ping you

**Comment by IMvision12** [comment]
@Rocketknight1 I think I've covered all PyTorch models!

**Review by Rocketknight1 — APPROVED** [review]

**Comment by Rocketknight1** [comment]
@IMvision12 Amazing, thank you! I just finished reviewing and it all looks good, so I'm going to merge now. Once we have full type hint coverage we can add tests to ensure that it stays that way in future, and then start using the type hints in library checking, so this should help a lot!

**Comment by IMvision12** [comment]
@Rocketknight1 I guess there still some models left when i ran `find_missing_type_hints.ipynb` this are the models : `EsmForProteinFolding,
FlavaForPreTraining,
GLPNForDepthEstimation,
JukeboxPrior,
JukeboxVQVAE,
MarkupLMModel,
RoCBertForTokenClassification,
SegformerDecodeHead,
TapasForMaskedLM,
TapasForQuestionAnswering,
TapasForSequenceClassification,
TapasModel,
TrOCRForCausalLM,
VideoMAEForPreTraining,
VideoMAEForVideoClassification,
VideoMAEModel,
Wav2Vec2ForMaskedLM,
YolosModel`

**Pull request merged**
