### PR TITLE
Fix device of masks in tests

### PR DESCRIPTION
**Pull request by fxmarty**
As per title, fix a bug introduced in https://github.com/huggingface/transformers/pull/24587 in the GPU tests.

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Thanks

**Comment by ydshieh** [comment]
Strange that we don't see the issue on our CI. Do you know why @fxmarty?

**Comment by fxmarty** [comment]
@ydshieh Can you try `RUN_SLOW=1 CUDA_VISIBLE_DEVICES=0 pytest tests/models/llama -s -vvvvv -k "test_resize_tokens_embeddings"` on main?

**Comment by fxmarty** [comment]
I am not sure it's weird. The `push` tests should run on GPU so those should have failed...
https://github.com/huggingface/transformers/blob/fc71e815f6ff5fc8b743786e2146cff9644ec598/.github/workflows/self-push.yml#L133

**Pull request merged**
