### PR TITLE
Workaround for #27758 to avoid ZeroDivisionError

### LINKED ISSUE #27758: ZeroDivisionError when training on a single batch of data
### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.35.2
- Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
- Python version: 3.10.8
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.1
- Accelerate version: 0.24.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: not that I'm aware, there's only a single GPU and single machine

### Who can help?

@muellerzr and @pacman100 (tagging for trainer)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Overview

With very small datasets that end up being a single batch, this code in [transformers/trainer.py#L1968-L1969](https://github.com/huggingface/transformers/blob/v4.35.2/src/transformers/trainer.py#L1968-L1969) from:

```
# add remaining tr_loss
self._total_loss_scalar += tr_loss.item()
train_loss = self._total_loss_scalar / self.state.global_step
``` 

will throw a `ZeroDivisionError`.  

Since I can't always control the data that is being uploaded to the service I'm working on, this is problematic because users will receive a cryptic error that makes it appear that the service is broken. 

### Reproduction

Train on a dataset with a single batch of data.

Logger info:

```
Currently training with a batch size of: 1
***** Running training *****
  Num examples = 37
  Num Epochs = 3
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 32
  Total optimization steps = 3
  Number of trainable parameters = 109,051,904
```

Error stack trace:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/dalm/training/generator_only/trainer.py", line 301, in <module>
    main()
  File "/opt/conda/lib/python3.10/site-packages/dalm/training/generator_only/trainer.py", line 264, in main
    train_generator(
  File "/opt/conda/lib/python3.10/site-packages/dalm/training/generator_only/trainer.py", line 255, in train_generator
    trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 280, in train
    output = super().train(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1969, in _inner_training_loop
    train_loss = self._total_loss_scalar / self.state.global_step
ZeroDivisionError: float division by zero
```

### Expected behavior

Instead of throwing a cryptic `ZeroDivisionError`, it should at least return a more user friendly error like "Training with a single batch of data is not supported.  Try again with a larger dataset"

But it would be much better if it just handled it more gracefully and approximated the loss, maybe by adding a small constant to the denominator or making the `global_step` to be 1-based instead of 0-based.

The following workaround in [transformers/trainer.py](https://github.com/huggingface/transformers/blob/v4.35.2/src/transformers/trainer.py#L1968-L1969) avoids the error. 

Update:

```
        # add remaining tr_loss
        self._total_loss_scalar += tr_loss.item()
        train_loss = self._total_loss_scalar / self.state.global_step
``` 

to:

```
        gstep = self.state.global_step
        if gstep <= 0:
            gstep = 1
        train_loss = self._total_loss_scalar / gstep
```

This avoids the error, though it gives the incorrect loss value.

### PR DESCRIPTION
**Pull request by tleyden**
# What does this PR do?

It can speed up devloops to test with very small datasets which end up being a single batch.  However, that can trigger the error described in #27758.

This PR works around it by changing the division by zero to division by a very small number.  The loss metric will already be meaningless if `self.state.global_step == 0`.  This PR won't change that, however it will prevent the unhelpful `ZeroDivisionError`

I have not written any tests yet, but would be happy to if the reviewers agree with the overall approach.

Fixes #27758

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ArthurZucker @pacman100

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
LGTM thanks for opening the PR 🤗

**Review by ArthurZucker — APPROVED** [review]
just missing a small test imo to make sure this does not break anything! 🤗

**Comment by tleyden** [comment]
@ArthurZucker sounds good, I'll look into adding a test.  If you know of any existing tests that I should look at, LMK!

**Comment by ArthurZucker** [comment]
Hey! If you can rebase we can merge as is it's alright

**Comment by tleyden** [comment]
@ArthurZucker I just rebased - can you approve the workflow?

**Comment by tleyden** [comment]
@ArthurZucker @pacman100 PTAL at approving workflow

**Review by pacman100 — APPROVED** [review]
Thank you @tleyden for the fix!

**Comment by tleyden** [comment]
Sure np @pacman100, but I would call it more of a workaround.  At some point it's worth finding out why `self.state.global_step` can end up as `0` in the first place

**Pull request merged**
