### PR TITLE
update docs to add the `phi-2` example

### PR DESCRIPTION
**Pull request by susnato**
# What does this PR do?

This updates the docs as discussed [here](https://github.com/huggingface/transformers/pull/28211#issuecomment-1880115245)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ArthurZucker 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Thanks, not a fan of having to rely on a custom model, but while #28163 is not merged let's have this

**Comment by ArthurZucker** [comment]
Can you make it into a tip / warning for the mean time.

**Comment by susnato** [comment]
Hi @ArthurZucker, I have added the tip/warning. 

Let me know if anything more needs to be added.

**Comment by ArthurZucker** [comment]
just need to rebase on main 😉

**Comment by susnato** [comment]
Sorry my bad :sweat_smile:

**Comment by ArthurZucker** [comment]
Thanks!

**Pull request merged**
