### PR TITLE
Update important model list

### PR DESCRIPTION
**Pull request by LysandreJik**
Adds LLaMa to the important models to test on each commit

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks ! shall we add mistral as well ?

**Comment by LysandreJik** [comment]
I hesitated but Mistral and Llama are very close in terms of architecture and support so I didn't find it necessary; do you think it's different enough to warrant being added?

**Comment by younesbelkada** [comment]
mistral uses sliding window attention which is not the case in llama, for that I thought maybe better to test it but I think all good to leave it as is as well

**Review by ArthurZucker — APPROVED** [review]
Makes sense for sure. 👍

**Pull request merged**
