### PR TITLE
Print more library versions in CI

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

- Print more library versions in CI jobs
  - `transformers`, `PyTorch`, `TensorFlow`, `DeepSpeed`, etc.  
  - easier to access without the need to open several tabs

### CODE REVIEW

**Review by stas00 — COMMENTED** [review]
Thank you for working on adding env info, @ydshieh 

So I started the work on avoiding massive copy-n-paste sections with
https://github.com/huggingface/transformers/blob/main/utils/print_env_pt.py

Perhaps it'd be useful to expand it to print other environment data so it'll be just a single script to run and not 10 lines of one liners. Perhaps one script for pt and another for tf? or one to rule them all and be configurable what to print so that it doesn't print irrelevant info in jobs where it's not relevant (i.e. no tf info for pt jobs)

Not only it'd help with easier to read job definitions it'd be faster too. Loading tf 5 times in a row starting a new interpreter each time is super slow.

**Comment by ydshieh** [comment]
@stas00 OK for me to use a script, on it!

**Comment by stas00** [comment]
Looks great, @ydshieh 

Perhaps let's just turn warnings off to keep the SNR high?

**Review by LysandreJik — APPROVED** [review]
Very cool! LGTM, thanks @ydshieh and @stas00!

**Pull request merged**
