### PR TITLE
Fix some TF GPT-J CI testings

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Fix some TF-GPT-J CI testing (scheduled)

- `test_mixed_precision`: require some casting
- `test_saved_model_creation` and `test_saved_model_creation_extended`: require `shape_list` instead of `shape`
- `test_model_from_pretrained`: skip for now otherwise GPU OOM

With the changes this PR, only the following test fails: `test_gptj_sample_max_time`: for example

https://github.com/huggingface/transformers/blob/c85547af2b69f9082bcd7bac97092b1d162f3fdc/tests/gptj/test_modeling_tf_gptj.py#L413

the PT gives a quite short generation sequence (say 19), while TF gives a sequence of length 256, and it takes much more time and therefore fails the tests.

I feel this remaining issue is better to be addressed in another PR.

### CODE REVIEW

**Comment by ydshieh** [comment]
I need to check why

```
@unittest.skipIf(len(tf.config.list_physical_devices("GPU")) > 0, "skip testing on GPU for now to avoid GPU OOM.")
```
causing problems in other tests (torch, pipeline etc ...)

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Review by gante — APPROVED** [review]
Thank for looking at these, @ydshieh 🙏

**Comment by gante** [comment]
Regarding the `max_time`/generate test -- when I first reviewed the GPT-J PR, I had little understanding of the current state of TF generate. Now I can tell that this test makes no sense :D Contrarily to PT's generate, TF generate has no time-based stopping criteria, so it is natural that the test fails. I'd remove it.

**Comment by ydshieh** [comment]
> Regarding the `max_time`/generate test -- when I first reviewed the GPT-J PR, I had little understanding of the current state of TF generate. Now I can tell that this test makes no sense :D Contrarily to PT's generate, TF generate has no time-based stopping criteria, so it is natural that the test fails. I'd remove it.

OK, thank you for the feedback.

But just curious: `TF generate has no time-based stopping criteria` --> do we plan to support this in the future ??

**Comment by gante** [comment]
> But just curious (off-topic): `TF generate has no time-based stopping criteria` --> do we plan to support this in the future ??
> 
> (not very sure, but I remembered before TF can generate short sequences too. And if TF can't stop earlier, it looks like a quite big drawback ..? Anyway, we shouldn't discuss this generation thing in this PR.)

The plan we have for the refactoring does not mention extras like the stopping criteria, so I can only tell that it probably won't happen in the next 2-3 months :) We can generate short sentences with TF if we pass the `max_length` argument, where `generate()` generates up to `max_length` tokens.

**Pull request merged**
