### PR TITLE
Adding `optimizer_cls_and_kwargs` to `Trainer.__init__`

### PR DESCRIPTION
**Pull request by apoorvkh**
# What does this PR do?

Currently, `Trainer` must be extended (as follows) to provide a custom `torch.optim.Optimizer`. The existing `optimizers` argument for `Trainer` assumes the model is already initialized on the correct devices (which is usually handled by `Trainer`).

```python
class CustomOptimizerTrainer(Trainer):
    @staticmethod
    def get_optimizer_cls_and_kwargs(args: HfTrainingArguments, model=None) -> tuple[type[torch.optim.Optimizer], dict[str, Any]]:
        optimizer = torch.optim.AdamW
        optimizer_kwargs = {
            "lr": 4e-3,
            "betas": (0.9, 0.999),
            "weight_decay": 0.05,
        }
        return optimizer, optimizer_kwargs
```

This PR adds an `optimizer_cls_and_kwargs` argument to `Trainer`. This simply allows a user to pass `Type[torch.optim.Optimizer]` and `Dict[str, Any]` when initializing the `Trainer` rather than having to extend the class (as above).

I am making this PR after #31875 (cc: @amyeroberts @muellerzr)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Nice! Seems like a great fix :)

**Comment by muellerzr** [comment]
If you do `pip install -e .[quality]; make fixup` it should fix the style failures

**Review by SunMarc — APPROVED** [review]
Thanks for the PR ! LGTM ! I'm curious about  why the optimizers args is not enough for you use case ?

**Comment by apoorvkh** [comment]
@SunMarc I am writing a codebase that uses `Trainer` for training with arbitrary models / hyper-parameters, especially using methods like FSDP / Deepspeed.

I believe the `optimizers` argument pre-supposes that a model is copied/sharded onto the right devices. But if we rely on Trainer to do the copying/sharding, the model parameters won't be available earlier (when defining the `optimizers` argument). I think that necessitates using `optimizer_cls` and `optimizer_kwargs` in `Trainer`. This PR simply tries to expose those options more conveniently :)

**Comment by apoorvkh** [comment]
Most checks pass now! A few tests in `tests_torch_and_flax` fail, but this does not seem specific to this PR.

**Comment by SunMarc** [comment]
Makes sense ! Thanks for explaining ! Maybe you can add a note explaining that in the description of the arg.

**Comment by apoorvkh** [comment]
For sure! Done.

**Comment by SunMarc** [comment]
Sorry for the wait ! When the CI is fixed from our side, we will merge the PR @apoorvkh

**Comment by apoorvkh** [comment]
Sounds great, thanks!

**Review by ArthurZucker — APPROVED** [review]
Thanks, would you like to add a bit of documentation for discoverability? With an example use case maybe? 🤗

**Comment by apoorvkh** [comment]
Sure, how do those changes to `trainer.md` look?

**Review by ArthurZucker — APPROVED** [review]
LGTM thanks

**Pull request merged**
