### PR TITLE
fix loading special_tokens_map_file

### PR DESCRIPTION
**Pull request by ZhiyuanChen**
# What does this PR do?

If special tokens map have special specified, e.g.:

```python
SPECIAL_TOKENS_MAP = {
    "pad_token": {
        "content": "<pad>",
        "lstrip": False,
        "normalized": False,
        "rstrip": False,
        "single_word": False,
        "special": True,
    },
}
```

loading pretrained with special tokens map would complain:

```bash
TypeError: tokenizers.AddedToken() got multiple values for keyword argument 'special'
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Hey! Which version of transformers are you using? Also which tokenizer are you trying to load? 
Special map is depracted and only kept for BC

**Comment by ZhiyuanChen** [comment]
> Hey! Which version of transformers are you using? Also which tokenizer are you trying to load? Special map is depracted and only kept for BC

Hi~ 
I'm using 4.39.3 to load an external tokenizer. 
I believe numerous codebase are still keeping the special tokens map like https://huggingface.co/facebook/esm2_t6_8M_UR50D/blob/main/special_tokens_map.json.

**Review by ArthurZucker — APPROVED** [review]
Okay! Could you just rebase on main ?

**Comment by ZhiyuanChen** [comment]
> Okay! Could you just rebase on main ?

One moment

**Pull request merged**
