### PR TITLE
implement diffllama with modular way

### LINKED ISSUE #34500: add diffllama with modular transformers
### Model description

- this is almost first try to use modular transformers
- it is implementation for differential transformers described in this [paper](https://arxiv.org/abs/2410.05258)
- the architecure cancels noise by subtracting attention scores as the difference between two separate softmax attention maps

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available

### Provide useful links for the implementation

https://arxiv.org/abs/2410.05258

### PR DESCRIPTION
**Pull request by bzantium**
# What does this PR do?

This PR implements differential transformers architecture mainly on top of the llama.

Fixes #34500 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ x ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ArthurZucker 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by bzantium** [comment]
I have only little document to refer on modular implementation so it's hard to figure out why tests fail.
I got following error:
 `ValueError: We were unable to find dependencies for DiffLlamaConfig (based on inheriting from LlamaConfig)   Here are all the global dependencies that we found in you modular file: ['DiffllamaConfig'].   This usually means that the name of 
 DiffLlamaConfig does not match the pattern of LlamaConfig`
 with command: `make fix-copies`

**Comment by Rocketknight1** [comment]
Hi @bzantium, we already have a PR for this open at #34083! Can you explain what this second PR is for?

**Comment by bzantium** [comment]
I am testing how to use modular script since there is not enough document. sorry for bothering you!
do not care for this PR :) thanks!

**Comment by ArthurZucker** [comment]
It's alright, it looked perfect in term of modular changes! 🤗

**Pull request closed without merging**
