### PR TITLE
Add cross attentions to TFGPT2Model

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Add cross attention to TFGPT2.

This was previously done in #13222, but we decided to move this to a new PR.
I also added `TFGPT2EncoderDecoderModelTest` with `test_bert2gpt2_summarization`.

### CODE REVIEW

**Review by Rocketknight1 — APPROVED** [review]
This looks very similar to the previous PR adding cross-attention to other models. Tests looks good and are passing, so I'm happy to approve it.

**Review by LysandreJik — APPROVED** [review]
This looks good to me but asking @patrickvonplaten for a review as wel

**Comment by patrickvonplaten** [comment]
Sorry, I tried fixing some merge conflicts, but I think this introduced a new error. @ydshieh could you maybe quickly go into the PR again and fix those last tests? :-) The PR looks good for me otherwise!

**Comment by ydshieh** [comment]
> 
> 
> Sorry, I tried fixing some merge conflicts, but I think this introduced a new error. @ydshieh could you maybe quickly go into the PR again and fix those last tests? :-) The PR looks good for me otherwise!

It's OK now :)

**Pull request merged**
