### PR TITLE
[QOL] add signature for prepare_seq2seq_batch

### PR DESCRIPTION
**Pull request by sshleifer**
This pr adds the signature, but no implementation of `prepare_seq2seq_batch` to `PretrainedTokenizer` to allow IDE autocompletion when `AutoTokenizer` is used.
+ The signature is quite large and it is nice to see what needs to be supplied.
+ The signature is enforced by the unittests, so it won't be misleading.

On this branch, where `self.tokenizer = AutoTokenizer(...)`:
image

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Cool, great idea! LGTM!

It would be great to fill in the documentation for this item as well, this way all the methods in the inheriting tokenizers that don't have docs will have the generic one defined here.

**Review by sgugger — APPROVED** [review]
Great indeed and agree with @LysandreJik, adding a generic documentation would be terrific (and maybe avoid copy-pasting the same thing in subclasses).

**Comment by sshleifer** [comment]
Didn't know docstring inheritance worked like that. Very cool!

**Comment by sgugger** [comment]
Docstring looks great to me, thanks for adding!

**Pull request merged**
