### PR TITLE
Fix run_mlm_wwm example

### PR DESCRIPTION
**Pull request by changjonathanc**
# What does this PR do?

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

### CODE REVIEW

**Comment by cccntu** [comment]
Wait, the example for `run_mlm_wwm.py` doesn't seem to run:
```
Traceback (most recent call last):
  File "run_mlm_wwm.py", line 334, in <module>
    main()
  File "run_mlm_wwm.py", line 161, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File ".../transformers/src/transformers/hf_argparser.py", line 144, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--dataset_name', 'wikitext', '--dataset_config_name', 'wikitext-2-raw-v1']
```

I will try to fix it too.

**Comment by sgugger** [comment]
Thanks for the fixes. I'm unsure the script can run on datasets hosted on the hub because of the need for reference files, that's why I hadn't added the `dataset_name` and `dataset_config_name` arguments in this one.

**Comment by cccntu** [comment]
You can still ignore the `dataset_name` arg and use the old behavior, so adding `dataset_name` should be fine.
I want to mention that I did not run the example with ref file.

**Comment by sgugger** [comment]
Ok, then we should add a check in the post_init to make sure no reference file is passed if we're using `dataset_name`, otherwise it won't work,

**Pull request closed without merging**
