### PR TITLE
get default device through `PartialState().default_device` as it has been officially released

### PR DESCRIPTION
**Pull request by ji-huazhong**
# What does this PR do?
As per title.

The main branch is now at 4.38.dev0, so I submit this PR which is a continuation of (the merged) https://github.com/huggingface/transformers/pull/26774.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks! This was introduced in ~0.19.0, well early enough for it to be included in Trainer’s requirements too. Though perhaps to be safe we should include a version check similar to the trainer? WDYT @amyeroberts

**Review by amyeroberts — APPROVED** [review]
Thanks for updating this!

**Comment by amyeroberts** [comment]
@muellerzr If we've had a deprecation notice for a few releases and it's available from the lowest version of accelerate officially supported in setup.py then I think we're fine. 

However, @statelesshz I can see that in this PR: https://github.com/huggingface/transformers/pull/26774/files that the deprecation notice mentions that it will be removed in v4.36 but this warning should still be present in v.4.35 (current release). This is entirely my bad - I shouldn't have approved and merged the PR. 

As such, we'll need to do a version check like @muellerzr suggests, add back the warning from #26774, updating the notice to v4.37 and then remove it all in v4.37. Sorry for not catching this.

**Comment by statelesshz** [comment]
> @muellerzr If we've had a deprecation notice for a few releases and it's available from the lowest version of accelerate officially supported in setup.py then I think we're fine.
> 
> However, @statelesshz I can see that in this PR: https://github.com/huggingface/transformers/pull/26774/files that the deprecation notice mentions that it will be removed in v4.36 but this warning should still be present in v.4.35 (current release). This is entirely my bad - I shouldn't have approved and merged the PR.
> 
> As such, we'll need to do a version check like @muellerzr suggests, add back the warning from #26774, updating the notice to v4.37 and then remove it all in v4.37. Sorry for not catching this.

This sounds reasonable :)

**Comment by muellerzr** [comment]
cc @statelesshz, can you do it for v4.38 instead? Thanks! (A new release is coming this week)

**Comment by statelesshz** [comment]
I would like to first open a new PR to update the warning notifications to v4.38 and keep this PR until it can be merged:-) WDYT @muellerzr

**Comment by statelesshz** [comment]
I would like to first open a new PR to update the warning notifications to v4.38 and keep this PR until it can be merged:-) WDYT @muellerzr

**Comment by statelesshz** [comment]
@muellerzr OK, I'll open another PR to update the warning notice to v4.38 and hang up this PR :-)

**Comment by statelesshz** [comment]
I'd like to open another PR to update the notice to v4.38 and leave this PR open until it's OK to be merged :-) WDYT @muellerzr

**Comment by muellerzr** [comment]
Works with me @statelesshz!

**Comment by ArthurZucker** [comment]
@muellerzr do you want to merge this?

**Comment by statelesshz** [comment]
@amyeroberts The main branch is now at 4.38.dev0, I think this PR is ready to be merged :-)

**Review by muellerzr — APPROVED** [review]
All good from merging on my side, sorry it fell through the cracks!

**Review by amyeroberts — APPROVED** [review]
LGTM - thanks for following up!

**Pull request merged**
