### PR TITLE
Cache: models return input cache type

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

Changes the `Cache` compatible models to return the same type of cache as the cache passed through `past_key_values`. This was not happening in the case a `DynamicCache` was explicitly passed as input, which was breaking a test :)

### CODE REVIEW

**Comment by gante** [comment]
@zucchini-nlp this was the issue you pointed me to yesterday 🤗

**Review by ArthurZucker — APPROVED** [review]
It overall a clean fix. I think we deprecated the legacy cache so at some point we can just return whatever was given!

**Review by zucchini-nlp — APPROVED** [review]
Great, thanks a lot for standardizing this!

**Comment by gante** [comment]
> I think we deprecated the legacy cache so at some point we can just return whatever was given!

@ArthurZucker `generate` still defaults to the legacy format -- I'm going to rectify this 😉

**Pull request merged**
