### PR TITLE
Fix bert issue

### PR DESCRIPTION
**Pull request by saswatmeher**
# What does this PR do?
This PR fixes a bug that a user can encounter while using generate and models that use gradient_checkpointing.

Fixes issue #21737  for Bert.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.(#21737)
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@younesbelkada, @gante

### CODE REVIEW

**Comment by saswatmeher** [comment]
@younesbelkada or @gante, Can anyone of you please help me with the error I am getting after running fix-copies. Running fix-copies made changes to multiple files(19) and now I am getting tests_torch, tests_torch_and_tf error on it.

**Comment by younesbelkada** [comment]
Hi @saswatmeher 
Thanks for the PR! 
I would probably try:
1- `pip install --upgrade -e .["quality"]` and then run `make fix-copies`
Let us know if this works!

**Comment by saswatmeher** [comment]
@younesbelkada It worked. Thanks!

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for your great work on this! 
The large number of changed files is explained by the fact that a lot of models copy from roberta, which is itself copied from bert 
Thanks again!

**Review by gante — APPROVED** [review]
Awesome, thanks for the matryoshka fix :D

**Pull request merged**
