### PR TITLE
2 typos in modeling_rag.py

### PR DESCRIPTION
**Pull request by ratthachat**
# What does this PR do?
Fix 2 typos in `modeling_rag.py`
`from_encoder_generator_configs` --> `from_question_encoder_generator_configs`

## Who can review?
@lhoestq

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hi! Could you run `make style` on your branch so that the code quality check passes? Thanks!

**Review by lhoestq — COMMENTED** [review]
Good catch ! Could you run `make style` to make the CI pass ?

**Comment by ratthachat** [comment]
Hi guys, I only have mobile phone until Dec. 1. I will do it as soon as I can access PC.

**Comment by ratthachat** [comment]
@lhoestq @LysandreJik done applying style. Sorry for late!

**Review by lhoestq — APPROVED** [review]
thanks :)

**Pull request merged**
