### PR TITLE
Add CamemBERT model for TF2

### PR DESCRIPTION
**Pull request by jplu**
Hello,

Here another contribution :) I have implemented the CamemBERT model handling for Tensorflow 2.

I now have the model on my disk, should I send it to you? Or will you generate it from your side? Or should I upload it on my account? As you wish :)

Best.

Julien.

### CODE REVIEW

**Comment by jplu** [comment]
Humm I don't understand why this test is failing I haven't touched to DistilBERT...

```=================================== FAILURES ===================================
______________ TFDistilBertModelTest.test_pt_tf_model_equivalence ______________
[gw2] linux -- Python 3.5.9 /usr/local/bin/python

self = <tests.test_modeling_tf_distilbert.TFDistilBertModelTest testMethod=test_pt_tf_model_equivalence>

    def test_pt_tf_model_equivalence(self):
        if not is_torch_available():
            return
    
        import torch
        import transformers
    
        config, inputs_dict = self.model_tester.prepare_config_and_inputs_for_common()
    
        for model_class in self.all_model_classes:
            pt_model_class_name = model_class.__name__[2:]  # Skip the "TF" at the beggining
            pt_model_class = getattr(transformers, pt_model_class_name)
    
            config.output_hidden_states = True
            tf_model = model_class(config)
            pt_model = pt_model_class(config)
    
            # Check we can load pt model in tf and vice-versa with model => model functions
            tf_model = transformers.load_pytorch_model_in_tf2_model(tf_model, pt_model, tf_inputs=inputs_dict)
            pt_model = transformers.load_tf2_model_in_pytorch_model(pt_model, tf_model)
    
            # Check predictions on first output (logits/hidden-states) are close enought given low-level computational differences
            pt_model.eval()
            pt_inputs_dict = dict(
                (name, torch.from_numpy(key.numpy()).to(torch.long)) for name, key in inputs_dict.items()
            )
            with torch.no_grad():
                pto = pt_model(**pt_inputs_dict)
            tfo = tf_model(inputs_dict, training=False)
            tf_hidden_states = tfo[0].numpy()
            pt_hidden_states = pto[0].numpy()
            tf_hidden_states[np.isnan(tf_hidden_states)] = 0
            pt_hidden_states[np.isnan(pt_hidden_states)] = 0
            max_diff = np.amax(np.abs(tf_hidden_states - pt_hidden_states))
            # Debug info (remove when fixed)
            if max_diff >= 2e-2:
                print("===")
                print(model_class)
                print(config)
                print(inputs_dict)
                print(pt_inputs_dict)
>           self.assertLessEqual(max_diff, 2e-2)
E           AssertionError: 2.3126152 not less than or equal to 0.02

tests/test_modeling_tf_common.py:125: AssertionError```

**Comment by julien-c** [comment]
@jplu It's an unrelated Heisenbug. 

@thomwolf For some reason the debug prints were not printed :(

**Comment by jplu** [comment]
Ok I thought it was coming from me ahah

@thomwolf I let you check, do not hesitate to ping me if I have to do something from my side.

**Comment by LysandreJik** [comment]
@jplu Here too, I took the liberty of updating the documentation directly on your fork. Thank you very much for your contributions, this is great!

**Pull request merged**
