### PR TITLE
Adding Finnish BERT.

### PR DESCRIPTION
**Pull request by haamis**
We have trained BERT-base on Finnish text and wish to have it included in the library. Both cased and uncased models are available. You can see the paper [here](https://arxiv.org/abs/1912.07076) and a website for the model can be found [here](http://turkunlp.org/FinBERT/).

These changes passed all the relevant tests (\*auto\*, \*common\*, \*_bert_test\*) including `test_model_from_pretrained` with the Finnish models.

### CODE REVIEW

**Comment by julien-c** [comment]
This looks really awesome, thanks for sharing!

**Uskomatonta**!! (yes this is the only Finnish word I know)

The new recommended way of uploading the files is inside folders, that way you'll be able to 
do `AutoModel.from_pretrained("TurkuNLP/bert-base-finnish-[un]cased-v1")` out-of-the-box, without even having to modify the lib's code (though we may want to add "bert-base-finnish-[un]cased-v1" as a shortcut name anyways).

(We just [updated the documentation](https://github.com/huggingface/transformers/commit/855ff0e91d8b3bd75a3b1c1316e2efd814373764#commitcomment-36452545) this morning so this is very new)

Do you want to re-upload the files inside folders? Or I can do it on our side too.

Also the ArXiv link in the PR's post seems broken, is the paper not public yet?

Anyways, thanks for sharing, this is awesome!

**Comment by haamis** [comment]
> (We just updated the documentation this morning so this is very new)

Ah, just missed it then.

> Do you want to re-upload the files inside folders? Or I can do it on our side too.

Would be great if you could do it, thanks.

> Also the ArXiv link in the PR's post seems broken, is the paper not public yet?

The paper is scheduled to be announced on arxiv at 8pm EST so I'll fix the link tomorrow (in 12 hours or so).

**Comment by julien-c** [comment]
Looks like a URL was incorrect in the original PR, fixed it.

Merging now, thank you again!

**Comment by julien-c** [comment]
By the way, would you guys be interesting in beta-testing a new way of pre-training a tokenizer on a corpus, @haamis?

@n1t0 is working on something that might be of interest to you.

**Comment by julien-c** [comment]
Also @haamis we're rolling out model and contributor pages: e.g. https://huggingface.co/TurkuNLP

Anything you would like to see added to this page? How can it be most helpful? Thanks!

**Comment by haamis** [comment]
> By the way, would you guys be interesting in beta-testing a new way of pre-training a tokenizer on a corpus, @haamis?
> 
> @n1t0 is working on something that might be of interest to you.

I saw there was a faster implementation of the tokenizer in the works, improved speed would be nice.

> Also @haamis we're rolling out model and contributor pages: e.g. https://huggingface.co/TurkuNLP
> 
> Anything you would like to see added to this page? How can it be most helpful? Thanks!

That looks good to me.

Sorry about the late reply.

**Pull request merged**
