### PR TITLE
update the logger message with accordant weights_file_name

### PR DESCRIPTION
**Pull request by izyForever**
# What does this PR do?

Update the logger message with accordant weights_file_name.

Fixes # (issue)
https://github.com/huggingface/transformers/issues/28076

@amyeroberts

### CODE REVIEW

**Comment by izyForever** [comment]
@amyeroberts

**Comment by izyForever** [comment]
> @amyeroberts
> 
> I can't figure out why I failed the tests_torch for I only changed the logger info.😖 Could you help me?
> 
> )6)H WRK7EVWMBBDTCFV 8

 Does it relate to "a maintainer with write access may need to approve any workflow runs" ? I was confused.

**Review by amyeroberts — APPROVED** [review]
Thanks for updating this and contributing to improving the code! 

For the failing (unrelated) tests, there was a fix merge into main recently - #28202. Could you rebase and push the updated branch? This should resolve and trigger another CI run

**Comment by izyForever** [comment]
> Thanks for updating this and contributing to improving the code!
> 
> For the failing (unrelated) tests, there was a fix merge into main recently - #28202. Could you rebase and push the updated branch? This should resolve and trigger another CI run

It works！It seems the workflow need approval to finisg merge.

**Comment by amyeroberts** [comment]
@izyForever Yes - the doc tests are automatically run for security reasons. I've approved the workflow now - once that passes I'll merge in. 

Thanks again for your contribution!

**Pull request merged**
