### PR TITLE
[EncoderDecoder] Fix initialization and save/load bug

### LINKED ISSUE #4293: No crossattention layers in decoder from pretrained encoder-decoder model
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): BERT

Language I am using the model on (English, Chinese ...): English

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

Custom sequence to sequence task.

## To reproduce

1. Run the following script:
```
from transformers import EncoderDecoderModel
model = EncoderDecoderModel.from_encoder_decoder_pretrained('bert-base-uncased', 'bert-base-uncased') 
print(model.get_decoder())
```
2. You will find there's no crossattention layers in the decoder.

## Expected behavior

Cross attention layers initialized (not weights, but the layers themselves) in the decoder.

## Environment info
     
- `transformers` version: 2.9.0
- Platform: Linux-5.5.6-1.el7.x86_64-x86_64-with-debian-buster-sid
- Python version: 3.7.4
- PyTorch version (GPU?): 1.3.0 (True)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: NO
- Using distributed or parallel set-up in script?:NO

### PR DESCRIPTION
**Pull request by patrickvonplaten**
This PR fixes two bugs:

- Cross attention layers were not initialized when initiating the `EncoderDecoderModel` via `from_encoder_decoder_pretrained()`. Thanks goes to https://github.com/huggingface/transformers/issues/4293 for finding this bug! A slow test is including in this PR to prevent future bugs of this  kind.

- Saving / loading of pretrained models didn't work because the weights were initialized from the `model_to_load` weights because of a missing `base_model_prefix` in the `EncoderDecoderModel` class. Another slow test is included in this PR to prevent future bugs. I think this problem was mentioned in this issue: https://github.com/huggingface/transformers/issues/4517. I didn't rerun the code attached here: https://github.com/huggingface/transformers/issues/4517#issuecomment-636189365 but I'm quite positive that this is the bug that will be fixed in this PR.

## IMPORTANT
*To everybody who has been training Bert2Bert using the EncoderDecoder framework: Training with the EncoderDecoderModel before this PR did not work because there were no cross attention layers to be trained if you initialized your `EncoderDecoderModel` using `.from_encoder_decoder_pretrained(...)`.  - I'm very sorry for the wasted compute and energy! Training should work now. I will add an encoder decoder notebook in the next 1-2 weeks showing in-detail how Bert2Bert can be used with `EncoderDecoder`*

This regards the Issues: #4445, #4647, #4517, #4443, #4293, #4640

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@thomwolf @LysandreJik - merging for now to solve a bunch of issues. On a side-note, we have not really released the `EncoderDecoderModel` feature of `transformers` yet, or? Are we planning on doing something semi-official for this?

**Comment by patrickvonplaten** [comment]
> > I will add an encoder decoder notebook in the next 1-2 weeks showing in-detail how Bert2Bert can be used with EncoderDecoder
> 
> @patrickvonplaten
> 
> I'm already working on a EncoderDecoder notebook for summarization task using kaggle news summery dataset. Hope to finish it in a week :)

That's great news! Do you use a Bert2Bert implementation?

**Comment by patil-suraj** [comment]
Yes, I am using Bert2Bert

**Comment by afcruzs** [comment]
@patrickvonplaten I noticed that since this change this issue happens #5826, is it possible I'm using the config api incorrectly or may be a real issue? 

Sorry for tagging you, thanks in advance!

**Comment by patrickvonplaten** [comment]
Hey @afcruzs - will answer on the issue :-)

**Comment by kimmo1019** [comment]
Hey, @patrickvonplaten ,  I wonder if there is any way to get the cross attention weights in the decoder from `EncoderDecoderModel` model. I looked at the document, it only will return the self-attention weights (`decoder_attentions `) in the decoder from `EncoderDecoderModel`? Thanks very much, it bothers me for a while.

**Comment by patrickvonplaten** [comment]
Hey @kimmo1019 - could you please open a new issue about this? :-)

**Pull request merged**
