### PR TITLE
fixed docstring typos

### PR DESCRIPTION
**Pull request by JadeKim042386**
# What does this PR do?

Fixes # (#18721)

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

@ydshieh

### CODE REVIEW

**Comment by ydshieh** [comment]
LGTM, but the change

from
```
kwargs: (*optional*) Remaining dictionary ...
```
to
```
kwargs (*optional*) Remaining dictionary ...
```
should be 
```
kwargs (*optional*): Remaining dictionary ...
```
Do you agree?

**Comment by JadeKim042386** [comment]
@ydshieh
Oh, the colon was missing!
I think it would be better to put a colon~

**Review by ydshieh — APPROVED** [review]
LGTM, thanks, @JadeKim042386 ! Will wait another reviewer to double check.

**Comment by ydshieh** [comment]
@LysandreJik The number of changed files is large, but it just remove the extra `:` from some docstrings. I checked on the documentation page, and indeed there are missing arguments due to this fact.

```
encoder_layerdrop: (`float`, *optional*, defaults to 0.0):
```
to
```
encoder_layerdrop (`float`, *optional*, defaults to 0.0):
```

**Review by LysandreJik — APPROVED** [review]
Wow, very nice! Thanks for helping out on this @JadeKim042386, this is very appreciated!

**Pull request merged**
