### PR TITLE
remaining pytorch type hints

### PR DESCRIPTION
**Pull request by IMvision12**
# What does this PR do?

Type hints

@Rocketknight1

### CODE REVIEW

**Comment by IMvision12** [comment]
There are only three left: `JukeboxPrior`, `JukeboxVQVAE` and `EsmForProteinFolding`. I'm not sure how to write type hints for these, so i've skipped them.

**Comment by IMvision12** [comment]
@Rocketknight1 There is only 1 left: EsmForProteinFolding. when I tested test_modeling_esmfold.py before doing any changes to the file some tests where initially getting failed.

Capture

**Comment by Rocketknight1** [comment]
@IMvision12 Those tests shouldn't be failing anymore, but don't worry - I'm happy to accept all the other changes!

**Review by Rocketknight1 — APPROVED** [review]
Looks perfect to me, thank you!

**Pull request merged**
