### PR TITLE
enable QA bf16 pipeline

### PR DESCRIPTION
**Pull request by jiqing-feng**
Hi @SunMarc @ArthurZucker 

The same issue as #31625 . Numpy can only process fp32 data type but the input tensor could be bf16/fp16 based on the model's dtype. Please review it, thx!

### CODE REVIEW

**Comment by jiqing-feng** [comment]
The issue can be reproduced by:
```python
import torch
from transformers import pipeline

question = "How many programming languages does BLOOM support?"
context = "BLOOM has 176 billion parameters and can generate text in 46 languages natural languages and 13 programming languages."

question_answerer = pipeline("question-answering", model="bert-large-uncased-whole-word-masking-finetuned-squad", torch_dtype=torch.bfloat16)
out = question_answerer(question=question, context=context)
```

**Comment by jiqing-feng** [comment]
Hi @Rocketknight1 , could you please review this PR ? Thx!

**Review by Rocketknight1 — APPROVED** [review]
Yes, good fix, and thank you for the clean reproducer!

**Comment by Rocketknight1** [comment]
Merging without core maintainer review since this is a straightforward pipeline dtype fix that shouldn't have any side effects

**Pull request merged**
