### PR TITLE
adding a tip for deepspeed integration in multi-node environment

### PR DESCRIPTION
**Pull request by izapolsk**
This PR 
1. adds a tip for training in multi-node environment with deepspeed w/o shared filesystem
2. automatically configures deepspeed to inject:
```
{
  "checkpoint": {
    "use_node_local_storage": true
  }
}
```
when `--save_on_each_node` is passed.

-------------------
note from @stas00: I took this opportunity to expand much further these sections, as it has been long overdue!

### CODE REVIEW

**Comment by izapolsk** [comment]
@stas00, could you please review  ? ^^

**Comment by izapolsk** [comment]
Maybe, it's also worth adding `use_node_local_storage: true` when `save_on_each_node=True` and use_node_local_storage isn't defined in deepspeed config file.

**Comment by stas00** [comment]
Great additions, @izapolsk!

> Maybe, it's also worth adding use_node_local_storage: true when save_on_each_node=True and use_node_local_storage isn't defined in deepspeed config file.

yes, please and thank you!

Also if you'd like it might be a good idea to update `torch.distributed.launch` with the new API of ``torch.distributed.run` as the former is deprecated now. If you want to that is - if not I can update it later.

We can also say expand your note that any launcher can be used, including `accelerate` I think. i.e. the launcher is independent from the program it runs.

**Comment by izapolsk** [comment]
I'll do. thank you

**Comment by stas00** [comment]
Please let me know when you finished editing and I will add a few more notes - as some users will be still using `launch`, so we should mentioned both.

**Comment by izapolsk** [comment]
@stas00, please review

**Comment by stas00** [comment]
Excellent integration addition, @izapolsk - thank you for the initiative.

I took this opportunity to expand much further these sections, as it has been long overdue! Hope you don't mind that I did it in your PR. All your content is there, I just expanded the content a lot more.

Please let me know if it looks good to you and if you have any suggestions to make.

**Review by stas00 — APPROVED** [review]

**Comment by izapolsk** [comment]
awesome, thank you !

**Review by sgugger — APPROVED** [review]
Thanks a lot for your contribution!

**Pull request merged**
