### PR TITLE
Add script to convert tf2.x checkpoint to PyTorch

### PR DESCRIPTION
**Pull request by mar-muel**
The script converts the newer TF2.x checkpoints (as published on their [official GitHub](https://github.com/tensorflow/models/tree/master/official/nlp/bert) to Pytorch. The [existing script](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_bert_original_tf_checkpoint_to_pytorch.py) only works with checkpoints from the [original BERT repository](https://github.com/google-research/bert) which uses TF 1.4.

The script currently only converts the encoder part (but no MLM/NSP heads). The official checkpoints published by the tensorflow team unfortunately also don't contain these heads. I have written a script which takes care of these, but it does add a fair bit of complexity.

I have tested on my side by comparing all model weights with the official Huggingface version:

```python
from transformers import BertModel
import torch

def validate_model(bert_original, bert_converted):
    assert bert_original.num_parameters() == bert_converted.num_parameters()
    assert len(bert_original.state_dict()) == len(bert_converted.state_dict())
    for (layer_original, value_original), (layer_converted, value_converted) in zip(bert_original.state_dict().items(), bert_converted.state_dict().items()):
        assert layer_original == layer_converted
        if not torch.eq(value_original, value_converted).all():
            raise ValueError(f'Incorrect weights for {layer_original}')
    print('Success! Both models are identical!')

if __name__ == "__main__":
    validate_against = 'bert-base-uncased'
    path_to_converted_model = './converted_bert_base_uncased'
    bert_converted = BertModel.from_pretrained(path_to_converted_model)
    bert_original = BertModel.from_pretrained(validate_against)
    validate_model(bert_original, bert_converted)
```

I'm happy to write some tests for this if needed (and if possible) or have any other input.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
This is very cool! I'm testing it right now.

Could you modify the name of the file to `convert_bert_original_tf2_checkpoint_to_pytorch.py`? It's important to understand that this script is for the original repository, as we also have TF2 BERT checkpoints.

**Comment by LysandreJik** [comment]
Other than that, LGTM! Thanks for your work!

**Comment by mar-muel** [comment]
Great, just renamed it - let me know if anything else should be changed!

**Review by LysandreJik — APPROVED** [review]
Great, LGTM!

**Pull request merged**
