### PR TITLE
support no gpt_j_residual for gpt-neox

### PR DESCRIPTION
**Pull request by TopIdiot**
# What does this PR do?

Support "gpt_j_residual == False"  for gpt-neox, which implement "else" branch in https://github.com/EleutherAI/gpt-neox/blob/main/megatron/model/transformer.py#L627

## Who can review?
Anyone in the community is free to review the PR.
@sgugger @patrickvonplaten

### CODE REVIEW

**Comment by LysandreJik** [comment]
@TopIdiot, would existing checkpoints (i.e., https://huggingface.co/EleutherAI/gpt-neox-20b) be usable with this configuration option, or would they output gibberish?

**Comment by TopIdiot** [comment]
> @TopIdiot, would existing checkpoints (i.e., https://huggingface.co/EleutherAI/gpt-neox-20b) be usable with this configuration option, or would they output gibberish?

Yes, it can be used. The default value for gpt_j_residual is "True",  so the exsiting checkpoints would enter the "if self.gpt_j_residual" branch. btw, I tested gpt-neox-20b, the result looks good for me.

**Comment by sgugger** [comment]
The question is whether the model would give sensible results if you set it to `False`. Transformers is not a modular toolbox, we don't add options to models that make no sense with the pretrained checkpoints of that model, we add new models instead.

**Comment by TopIdiot** [comment]
> The question is whether the model would give sensible results if you set it to `False`. Transformers is not a modular toolbox, we don't add options to models that make no sense with the pretrained checkpoints of that model, we add new models instead.

gpt_j_residual  is an option which already existed in gpt-neox (i.e.  https://github.com/EleutherAI/gpt-neox/blob/main/configs/20B.yml#L29)

Recently, we trained EleutherAI/gpt-neox with option gpt_j_residual == False and successfully convert the checkpoint to torch. However, we found that the current version of huggingface's gpt-neox doesn't implement this part. We added it by ourself and got excepted result.

**Pull request closed without merging**
