### PR TITLE
Tokengt for Graph Classification

### PR DESCRIPTION
**Pull request by clefourrier**
# What does this PR do?
replaces #21098 
Adds the TokenGT model for graph classification in Transformers.

Done:
- [x] Architecture ported
- [x]  Collator (the model has no tokenizer) and preprocessing

Todo:
- [ ] Test results against original implementation, to make sure they are within precision range.
- [ ] Add checkpoints and make sure they load properly
- [ ] Update doc
- [ ] Update test suite
- [ ] Add model card for the checkpoints once added

## Dependencies
Cython, like Graphormer, and einops. 

Linked to #21079

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. (Discussed on Slack)
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Not tagging anyone for now as this is a draft.

### CODE REVIEW

**Comment by Raman-Kumar** [comment]
Oops. Don't mark stale. Hold on ...

**Comment by Raman-Kumar** [comment]
Hi, @clefourrier, soon I will **must**  complete 
(I was focusing on my new full-time job recently)

**Comment by clefourrier** [comment]
Congrats on your new job! I'll have some time off soon so I'll be less responsive, but feel free to ping me nonetheless!

**Comment by Raman-Kumar** [comment]
In July Month, I work on this.

**Comment by sarah-af** [comment]
Hi @clefourrier and @Raman-Kumar,
I'm fairly new to ML. I have a pretrained Graphormer model that I'd like to use for inference on individual instances. Looking around I arrived here, yet it's still not clear to me how I can proceed. Would you kindly provide some guidance?

Many thanks!

**Comment by clefourrier** [comment]
Hi @sarah-af ,
Did you read the Graphormer page documentation [here](https://huggingface.co/docs/transformers/model_doc/graphormer) and the Graph ML classification [blog post](https://huggingface.co/blog/graphml-classification)?
If yes, what is not clear?

**Comment by sarah-af** [comment]
Thank you for the quick response. I did read the documentation and the
blog. For some reason, I'm unable to do a forward pass on the test split
that has already been collated and preprocessed. Perhaps I missed
something. I'll check again, and I'll open a dedicated issue if I can't
figure it out.
Cheers!

**Pull request closed without merging**
