### PR TITLE
Fix typo of `Block`.

### PR DESCRIPTION
**Pull request by xkszltl**
Models:
- text models: @ArthurZucker and @younesbelkada

Was introduced in:
- https://github.com/huggingface/transformers/pull/27942

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks for fixing the typos on the class names! These classes are used internally so no breaking change 👌

**Review by ArthurZucker — DISMISSED** [review]
Looks good but not BC!

**Review by ArthurZucker — COMMENTED** [review]
Thanks. I think that a deprecation cycle would be nice  😢 A [quick search](https://github.com/search?q=MixtralBlockSparseTop2MLP&type=code) shows that it is used in a few instances

**Comment by younesbelkada** [comment]
Nice catch on checking on GH !

**Review by amyeroberts — COMMENTED** [review]
Thanks for adding this fix @xkszltl! 

Agreed with @ArthurZucker - we should do a quick deprecation cycle. Something as simple as: 

```py
class MixtralBLockSparseTop2MLP(MixtralBlockSparseTop2MLP):
    def __init__(self, *args, **kwargs):
        warnings.warn(
             """MixtralBLockSparseTop2MLP is deprecated and will be removed in v4.40. 
             Please use MixtralBlockSparseTop2MLP instead."""
        )
        super().__init__(*args, **kwargs)
```

**Comment by xkszltl** [comment]
Sounds good to me, added.

**Comment by xkszltl** [comment]
BTW why 4.40?
Any convention and consideration regarding the deprecation cycle?

**Comment by amyeroberts** [comment]
> BTW why 4.40? Any convention and consideration regarding the deprecation cycle?

We typically deprecate in 2 release cycles and this commit will be part of 4.38.

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing and handling the deprecation!

**Comment by amyeroberts** [comment]
@xkszltl For the failing tests on CI, running `make fixup` and pushing the changes should resolve the issue and trigger a new CI run

**Comment by xkszltl** [comment]
> @xkszltl For the failing tests on CI, running `make fixup` and pushing the changes should resolve the issue and trigger a new CI run

Would be great if we can actually lint in CI (not just check) and print out the git diff.
This way we don't have to run anything locally and can make whatever change needed directly from the log.

**Comment by amyeroberts** [comment]
> This way we don't have to run anything locally and can make whatever change needed directly from the log.

Isn't having to look at a diff in the CI run and manually apply the changes more work than just having the linter run locally?

**Comment by xkszltl** [comment]
> Isn't having to look at a diff in the CI run and manually apply the changes more work than just having the linter run locally?

Good question.
My opinion is: not always.
- For people continuously developing on the project, yes, a simple linter command is the easiest.
- For people occasionally joining, or currently focus on other projects, spending extra effort to setup another environment locally with possibly conflict dependencies is a lot more than copy-pasting diff from CI log.

**Comment by xkszltl** [comment]
Fixed.
Also change to log only once or it may be too annoying.

**Pull request merged**
