### PR TITLE
remove tee

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Remove the piping with `| tee` when running pytest. 
1. No one looks at the artifacts, and `tee` makes the output un-readable, color less etc. 
2. I checked that even if you remove this, the outputs are still visible because Circle CI uses a custom file system handling for this and not the `output.txt`. 
3. Subtests are omitted from the output this it does not include everything

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Example test that does not have tee: https://app.circleci.com/pipelines/github/huggingface/transformers/63142/workflows/4754f622-1e12-40bb-be2f-0dcb363a216b/jobs/778648/steps?invite=true#step-111-6582

**Comment by ArthurZucker** [comment]
Other files are still available: 
[~/transformers/installed.txt](https://output.circle-artifacts.com/output/job/c12dd81b-f182-4b6a-bdaf-051887b78948/artifacts/0/~/transformers/installed.txt)
[~/transformers/reports/tests_onnx/durations.txt](https://output.circle-artifacts.com/output/job/c12dd81b-f182-4b6a-bdaf-051887b78948/artifacts/0/~/transformers/reports/tests_onnx/durations.txt)
[~/transformers/reports/tests_onnx/stats.txt](https://output.circle-artifacts.com/output/job/c12dd81b-f182-4b6a-bdaf-051887b78948/artifacts/0/~/transformers/reports/tests_onnx/stats.txt)
[~/transformers/reports/tests_onnx/summary_short.txt](https://output.circle-artifacts.com/output/job/c12dd81b-f182-4b6a-bdaf-051887b78948/artifacts/0/~/transformers/reports/tests_onnx/summary_short.txt)
[~/transformers/reports/tests_onnx/warnings.txt](https://output.circle-artifacts.com/output/job/c12dd81b-f182-4b6a-bdaf-051887b78948/artifacts/0/~/transformers/reports/tests_onnx/warnings.txt)

**Comment by sgugger** [comment]
> No one looks at the artifacts

Speak for yourself ;-) , I only look at artifacts since it's impossible to get the traceback in the output. I do not look at the output artifact however, so that change wouldn't impact how I use the reports. However I'm not alone so make sure @LysandreJik @amyeroberts and @ydshieh all agree before merging this.

**Comment by ArthurZucker** [comment]
(The full traceback can still be seen!)

**Comment by ydshieh** [comment]
It seems expanding the run test step is still fast, and personally I don't read `test_output.txt` but just the reports given by `--make_reports`, I am OK for this change.

One thing remaining is to remove the upload artifact step if we don't produce it.

**Comment by amyeroberts** [comment]
I use the artefacts all the time :D! 

I think it's fine for `test_outputs.txt` to go though, as I rarely look at it and I think all the other info can be found in the other .txt files 👍

**Pull request closed without merging**
