### PR TITLE
Set missing seq_length variable when using inputs_embeds with ALBERT & Remove code duplication

### PR DESCRIPTION
**Pull request by olenmg**
# What does this PR do?

I think this bug is similar to #13128 , only difference is that this PR is for ALBERT. 
`AlbertModel` has the same issue that `seq_length` variable is not declared when using `inputs_embeds`

I checked that other models that were implemented in the same code format as ALBERT/ELECTRA don't have this issue anymore.

++Additional
Remove all of code duplications as @NielsRogge referred on the comments.
```Diff
        if input_ids is not None and inputs_embeds is not None:
            raise ValueError("You cannot specify both input_ids and inputs_embeds at the same time")
        elif input_ids is not None:
            input_shape = input_ids.size()
-           batch_size, seq_length = input_shape
        elif inputs_embeds is not None:
            input_shape = inputs_embeds.size()[:-1]
-           batch_size, seq_length = input_shape
        else:
            raise ValueError("You have to specify either input_ids or inputs_embeds")

+       batch_size, seq_length = input_shape        
        device = input_ids.device if input_ids is not None else inputs_embeds.device
```

I think it is trivial, so I don't make additional PR. (If this is the problem, please inform me.)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@LysandreJik

### CODE REVIEW

**Comment by NielsRogge** [comment]
Not sure why I can't add the code suggestion, but it makes more sense to do this:

```diff
if input_ids is not None and inputs_embeds is not None:
            raise ValueError("You cannot specify both input_ids and inputs_embeds at the same time")
        elif input_ids is not None:
            input_shape = input_ids.size()
-            batch_size, seq_length = input_shape
        elif inputs_embeds is not None:
            input_shape = inputs_embeds.size()[:-1]
-           batch_size, seq_length = input_shape
        else:
            raise ValueError("You have to specify either input_ids or inputs_embeds")

+        batch_size, seq_length = input_shape        
         device = input_ids.device if input_ids is not None else inputs_embeds.device
```

**Comment by olenmg** [comment]
> Not sure why I can't add the code suggestion, but it makes more sense to do this:
> 
> ```diff
> if input_ids is not None and inputs_embeds is not None:
>             raise ValueError("You cannot specify both input_ids and inputs_embeds at the same time")
>         elif input_ids is not None:
>             input_shape = input_ids.size()
> -            batch_size, seq_length = input_shape
>         elif inputs_embeds is not None:
>             input_shape = inputs_embeds.size()[:-1]
> -           batch_size, seq_length = input_shape
>         else:
>             raise ValueError("You have to specify either input_ids or inputs_embeds")
> 
> +        batch_size, seq_length = input_shape        
>          device = input_ids.device if input_ids is not None else inputs_embeds.device
> ```

Yes, I fully agree with you. But most of the codes of other models are implemented as I wrote, and I just wanted to unify the format to prevent confusion.

For example, the code below is from src/transformers/models/bert/modeling_bert.py:
```python
if input_ids is not None and inputs_embeds is not None:
    raise ValueError("You cannot specify both input_ids and inputs_embeds at the same time")
elif input_ids is not None:
    input_shape = input_ids.size()
    batch_size, seq_length = input_shape
elif inputs_embeds is not None:
    input_shape = inputs_embeds.size()[:-1]
    batch_size, seq_length = input_shape
else:
    raise ValueError("You have to specify either input_ids or inputs_embeds")

device = input_ids.device if input_ids is not None else inputs_embeds.device
```

If needed, I could change all of the code looks like above.

**Comment by NielsRogge** [comment]
> But if needed, I could change all of the code looks like above.

Actually, I'm in favor of this, because it's duplicated code, and I think it's cleaner when just writing it once.

**Comment by NielsRogge** [comment]
In that case, you can also update the [CookieCutter template](https://github.com/huggingface/transformers/blob/master/templates/adding_a_new_model/cookiecutter-template-%7B%7Bcookiecutter.modelname%7D%7D/modeling_%7B%7Bcookiecutter.lowercase_modelname%7D%7D.py), which is used when adding a new model.

**Comment by olenmg** [comment]
@NielsRogge 
Okay, I reflected it! (for at least the files I've found)
Please check again.

**Comment by NielsRogge** [comment]
LGTM! Thanks for making this cleaner.

**Review by LysandreJik — APPROVED** [review]
Looks good, thank you for updating the template as well!

**Pull request merged**
