### PR TITLE
Add offline mode for agents

### LINKED ISSUE #25223: Agent trying to load remote tools when being offline
### System Info

Transformers 4.31
Python 3.11.4
Windows 10

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code:

```
import os
os.environ['TRANSFORMERS_OFFLINE'] = '1'

from transformers import LocalAgent, AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("tiiuae/falcon-7b-instruct", trust_remote_code=True)
tokenizer = AutoTokenizer.from_pretrained("tiiuae/falcon-7b-instruct")

agent = LocalAgent(model=model, tokenizer=tokenizer) # Error here

agent.run("my query");
```

Error:

```
Max retries exceeded with url: /api/spaces?author=huggingface-tools
```

### Expected behavior

To not access the remote tools.

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR adds a check in the remote tools setup to bypass it when Transformers is in offline mode.
Fixes #25223

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thanks for the super quick response!
LGTM

**Comment by Romainlg29** [comment]
I'm getting an error:

```
ValueError: image-transformation is not implemented on the Hub.
```

It's coming from ```_setup_default_tools``` called from the ```__init__```.

**Comment by Romainlg29** [comment]
It's working great!
Thank you!

**Review by LysandreJik — APPROVED** [review]
Nice LGTM! Thanks for the implementation @sgugger

**Pull request merged**
