### PR TITLE
Add type annotations for Beit, ViT and Deit models - Pytorch

### PR DESCRIPTION
**Pull request by johnnv1**
# What does this PR do?

I added type annotations for  Beit, ViT and Deit models at PyTorch as described in #16059 

@Rocketknight1 

At Beit model, have some missing annotations because the annotation is another class at the file that are declared after. Also, at `BeitSelfOutput` class, I don't know the correct type for the gamma parameter at `forward` method -- the `gamma`  and `input_tensor` seems not to be used, but I prefer not to modify this now.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
Hi, thank you for this! I won't merge it yet because I'm going to ask the other team members on Monday what we think about the missing annotations - it's possible to use [forward references](https://peps.python.org/pep-0484/#forward-references) for this, but I want to make sure that plays well with our code analysis tools before we do that.

**Comment by johnnv1** [comment]
Already have a command that runs something like `mypy` to check the types?

**Comment by Rocketknight1** [comment]
Hi @johnnv1, I just confirmed with the team that forward references for types that aren't defined yet!

**Comment by johnnv1** [comment]
@Rocketknight1 after rebase upstream/master the `make fixup` shows that `vit_mae` need to be updated because of the `# Copied from ...`, but when I run `make fix-copies` he has been adding the `ViTConfig` on the config type annotation, I think these need to be `ViTMAEConfig`, what is the right way to deal with this?

**Pull request closed without merging**
