### PR TITLE
Flava multimodal add attention mask

### LINKED ISSUE #29408: FLAVA ITM output changes due to padding
TLDR; batch processing (padding) changes the output of `itm_scores` in FLAVA.

Hi,

I opened a GitHub [issue](https://github.com/apsdehal/flava-tutorials/issues/3#issue-2140965074) with the original FLAVA authors a while ago, but it appears that that repository is currently not being maintained. Since the issue arises from using the model from the `transformers` library, I think you might know what is happening here.

When calculating the ITM score with FLAVA, the results vary depending on the batch size. More specifically, padding seems to drastically change the model output. I ran this [demo notebook](https://github.com/apsdehal/flava-tutorials/blob/main/winoground-flava-example.ipynb) that tests FLAVA (the HF transformers implementation) on the Winoground dataset. With that, I get the following behaviour (copied from [my original GitHub issue](https://github.com/apsdehal/flava-tutorials/issues/3)).

Under the header 'Look at an example from Winoground and get the image-caption scores from FLAVA', the text and image of Winograd sample 155 are processed with `max_length=77, padding=True`: 

```
inputs_c0_i0 = flava_processor(text=[winoground[155]["caption_0"]], images=[winoground[155]["image_0"].convert("RGB")], return_tensors="pt", max_length=77, padding=True, return_codebook_pixels=True, return_image_mask=True).to("cuda")
```

According to the [HuggingFace documentation](https://huggingface.co/docs/transformers/pad_truncation), `padding=True` pads to the max sequence in the batch. That means that for this sample with a batch size of 1, no padding is applied. Inspecting the output of the processor, we find that indeed, no padding is applied.

Now in the next section of the notebook ('Get FLAVA image-caption scores from the whole dataset'), padding is set as `padding="max_length", max_length=77`, causing all tokenized inputs to have length 77. This yields the following scores:

```
contrastive text score: 0.2525
contrastive image score: 0.135
contrastive group score: 0.09
itm text score: 0.3225
itm image score: 0.1975
itm group score: 0.14
```

Changing the settings here to `padding=True` (removing padding and leaving everything else as it was), the scores now become:

```
contrastive text score: 0.2525
contrastive image score: 0.135
contrastive group score: 0.09
itm text score: 0.2125
itm image score: 0.1025
itm group score: 0.0475
```

We observe that the contrastive scores remain the same, but the itm scores have changed. Going back to sample 155, we find that going from `padding=True` (no padding) to `padding="max_length"` drastically changes the itm-score for each (image, text) pair.

```
FLAVA itm image-text match scores (no padding):
image_0, caption_0: 0.5821857452392578
image_0, caption_1: 0.6948502063751221
image_1, caption_0: 0.5699254274368286
image_1, caption_1: 0.7856388092041016

FLAVA itm image-text match scores (padding to max_length=77):
image_0, caption_0: 0.9999473094940186
image_0, caption_1: 0.9999871253967285
image_1, caption_0: 0.9997100234031677
image_1, caption_1: 0.9999109506607056
```

What could be the cause of this, and would this mean that we cannot use FLAVA with HuggingFace for batch processing (since that will add padding)?

### Who can help?
@ArthurZucker @younesbelkada @amyeroberts

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/apsdehal/flava-tutorials/blob/main/winoground-flava-example.ipynb

### Expected behavior

Padding does not affect the ITM output.

### PR DESCRIPTION
**Pull request by zucchini-nlp**
# What does this PR do?

Fixes #29408 . Multimodal part of FlavaModel was generating attentions masks with full ones on the fly, ignoring attentions masks passed by the user. Fixed by generating masks as a concatenation of the two modality's masks.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @gante

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Alright let's add a test for this! 🤗 
Otherwise we should also check that the attention mask is not None

**Comment by zucchini-nlp** [comment]
@ArthurZucker Oh yeah, added a check that the mask is not `None` and ran all `Flava` tests, including slow. 

I will work on the test for padding vs. unpadding soon. It will be a general modeling test, so I guess we do not need to write a separate padding test for `Flava` right now.

**Review by gante — APPROVED** [review]
LGTM, thank you having a look at this issue 🔥

**Review by ArthurZucker — APPROVED** [review]
Thanks!

**Comment by zucchini-nlp** [comment]
@gante this can be merged

**Pull request merged**
