### PR TITLE
distilbert-base-cased

### PR DESCRIPTION
**Pull request by VictorSanh**
- Weights
- Readmes and docs
- Previous omissions

weights are uploaded on s3, along with modelcards.

@LysandreJik Could you make sure I didn't forget anything?
@mfuntowicz Could have a check on the pipeline part?

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Looks good to me, feel free to merge when ready

**Comment by julien-c** [comment]
do we want to actually change the model used in the pipeline?

**Comment by VictorSanh** [comment]
> do we want to actually change the model used in the pipeline?

I'm not sure to understand the rationale behind the question.
Purely from a perf point of view, it's the same inf speed, while having better metrics than before.

**Comment by LysandreJik** [comment]
Nevermind the failing test, it's a Heisenbug. Merge when ready.

**Pull request merged**
