### PR TITLE
Add more missing models to models/__init__.py

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

After #14151, I just checked if there are other missing models - and added them in this PR.
There will be some issues showing up that are previously undetected.

## Who can review?

@sgugger  @LysandreJik

### CODE REVIEW

**Comment by ydshieh** [comment]
I add a new check `check_model_list` in `check_repo.py` in order to avoid the missing models.

For example, if `vision_encoder_decoder` is not included in `src/transformers/models/__init__.py`, the test would fail with the following message
```
Checking all models are included.
Traceback (most recent call last):
  File "C:\Users\33611\Desktop\Projects\transformers-dev-2\transformers\utils\check_repo.py", line 600, in <module>
    check_repo_quality()
  File "C:\Users\33611\Desktop\Projects\transformers-dev-2\transformers\utils\check_repo.py", line 587, in check_repo_quality
    check_model_list()
  File "C:\Users\33611\Desktop\Projects\transformers-dev-2\transformers\utils\check_repo.py", line 168, in check_model_list
    raise Exception(
Exception: The following models should be included in src/transformers\models/__init__.py: vision_encoder_decoder.
make[1]: *** [Makefile:40: extra_quality_checks] Error 1
make[1]: Leaving directory '/c/Users/33611/Desktop/Projects/transformers-dev-2/transformers'
make: *** [Makefile:50: quality] Error 2
```

**Review by sgugger — APPROVED** [review]
Thanks a lot for the new check, that is going to be very useful!

As an aside, is there a reason `bort` is excluded?

**Comment by ydshieh** [comment]
> As an aside, is there a reason `bort` is excluded?

Glad it will be helpful.

`bort` only contains a checkpoint conversion script.

If I include it, then we also need to have `bort` in `models/__init__.py`, like

```
from . import (
    albert,
    ...
    bort
```
which won't work.

**Comment by ydshieh** [comment]
> As an aside, is there a reason `bort` is excluded?

Glad it will be helpful.

`bort` only contains a checkpoint conversion script.

If I include it, then we also need to have `bort` included in `models.__init__.py` (otherwise the test will fail).
```
from . import (
    albert,
    ...
    bort
    ...
```
but this won't work.

**Pull request merged**
