### PR TITLE
Migrate metrics used in flax examples to Evaluate

### PR DESCRIPTION
**Pull request by VijayKalmath**
Currently, tensorflow examples use the `load_metric` function from
Datasets library,

commit migrates function call to `load` function in from Evaluate library for flax examples.

Fix for #18306

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger

### CODE REVIEW

**Comment by VijayKalmath** [comment]
@sgugger  , run_examples_flax successful ! Should be good to merge.

**Review by sgugger — APPROVED** [review]
Perfect, thanks a lot for working on this!

**Comment by VijayKalmath** [comment]
@sgugger  , I was wondering if you could point me at a good first issue I can try contributing to next. I looked at the issues and most of them seem to have folks working on them

**Comment by sgugger** [comment]
I think there are a couples of models left where help is needed on [this issue](https://github.com/huggingface/transformers/issues/16059).

**Pull request merged**
