### PR TITLE
Add `accelerate` support for LongT5 models

### PR DESCRIPTION
**Pull request by pszemraj**
Signed-off-by: peter szemraj <peterszemraj@gmail.com>

# What does this PR do?

This PR adds `accelerate` support for the longT5 models (i.e., make it possible to use `device_map="auto"`), so these models can be loaded in 8bit using load_in_8bit=True.

This helps enable inference with trained/fine-tuned SoTA long summarization models using limited memory :relaxed:  

Took inspiration from reviewing similar PRs for other models: #19912 and #19927 

cc @sgugger 

## test results

I made [a Colab notebook](https://colab.research.google.com/gist/pszemraj/6ea0a3046452fc51061f4bde2df0aa77/testing-accelerate-long-t5-tglobal-base-16384-book-summary.ipynb) that clones the branch from my fork to demo the `load_in_8bit=True` working. Everything else is the same for comparison purposes (_except the function that says the model size_) as [the fp32/standard notebook](https://colab.research.google.com/gist/pszemraj/d9a0495861776168fd5cdcd7731bc4ee/example-long-t5-tglobal-base-16384-book-summary.ipynb) listed on [my fine-tuned model card](https://huggingface.co/pszemraj/long-t5-tglobal-base-16384-book-summary).

I also ran the tests for `longT5` locally: 

```bash
$ python -m pytest -n auto --dist=loadfile -s -v tests/models/longt5/test_modeling_longt5.py 

( ... many things here ...)

=================================================== 196 passed, 58 skipped, 118 warnings in 30.49s ===================================================
```

### CODE REVIEW

**Comment by pszemraj** [comment]
cc @KMFODA for inputs on tests & more :crossed_fingers:

**Review by younesbelkada — COMMENTED** [review]
Very cool PR! Glad to see that `8-bit` integration is gaining interest and attention on more models 🔥 
Just a small typo on the Google Colab: the `.cuda()` is not needed after instantiating the model with `load_in_8bit` and `device_map=auto`, so I would advice to remove it ;)

Can you make sure the slow tests pass with the command `RUN_SLOW=1 pytest tests/models/longt5/test_modeling_longt5.py` ? (You will need to have access to a GPU instance) - When I ran your fix, `accelerate` tests were failing. You can fix them by adding the lines [here](https://github.com/pszemraj/transformers/blob/1269fb74846c2eb81260a7b0c3f9a3b1383b5884/src/transformers/models/longt5/modeling_longt5.py#L1364) as it was done for BART / NLLB in #19912
```
self.embed_tokens = nn.Embedding(config.vocab_size, config.d_model)
if embed_tokens is not None:
    self.embed_tokens.weight = embed_tokens.weight
```

**Comment by pszemraj** [comment]
Thanks for the feedback & good catch on the Colab! I've updated the notebook - will run and resolve the slow tests/accelerate items later today/tomorrow and revert back 👌

**Comment by younesbelkada** [comment]
Hey @pszemraj ! 
How is the integration going 💪 ! Let me know if I can help at some point to debug / make the tests pass ;) !

**Comment by younesbelkada** [comment]
Hi @pszemraj !
Is it ok if I try to take over the PR? this addition could be very nice to the lib! Let me know what do you think :)

**Comment by younesbelkada** [comment]
Thanks a lot @pszemraj for your great efforts, will have a look ASAP ;) this is definitely in my TODO list

**Comment by pszemraj** [comment]
thanks so much! I see you pushed so I will leave you to it (but feel free to let me know if questions or you need me to change anything on my end)

then we can get [this bad boi](https://huggingface.co/pszemraj/long-t5-tglobal-xl-16384-book-summary) usable on free Colab runtimes :)

**Review by younesbelkada — APPROVED** [review]
I can confirm all slow tests pass (single & multi-gpu)!
Thanks so much @pszemraj for your great contribution and patience! Thanks a lot for making Long-T5 models more accessible to anyone 
Leaving it now to @sgugger for a final review

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Comment by pszemraj** [comment]
Thanks for taking it home @younesbelkada! and thanks for the review @sgugger. Happy to help :)

**Pull request merged**
