### PR TITLE
Mark `test_eager_matches_sdpa_generate` flaky for some models

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

cc @fxmarty

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
These should not be flaky, I think it means there is an issue in the implemented sdpa vs eager! Or do they pass with 3 attempts?

**Comment by fxmarty** [comment]
Apart from qwen2 (that is bugged and I did not work on), other tests are simply flacky. In my experience (for inference) this had no impact on e.g. generation.

see https://github.com/pytorch/pytorch/issues/103462 for numerical differences (although for gradients there)

**Review by ArthurZucker — APPROVED** [review]
Alright thanks then!

**Comment by ydshieh** [comment]
I will remove the one for `qwen2`.

**Comment by fxmarty** [comment]
For qwen2 I think we should find which one of eager/sdpa is correct and maybe disable the one that is not until fixed :/

**Comment by ydshieh** [comment]
> For qwen2 I think we should find which one of eager/sdpa is correct and maybe disable the one that is not until fixed :/

I can skip it for now.

**Pull request merged**
