### PR TITLE
quick fix SummarizationPipeline error messages

### PR DESCRIPTION
**Pull request by nmntz**
Fix error messages to avoid spam errors, and errors of type:
`Your max_length is set to 50, but you input_length is only 46. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)`

### CODE REVIEW

**Review by j0gu4l667 — APPROVED** [review]

**Review by j0gu4l667 — APPROVED** [review]

**Comment by LysandreJik** [comment]
Pinging @Narsil and @patrickvonplaten

**Comment by LysandreJik** [comment]
Thanks for your contribution @NouamaneTazi :)

You have an error in your code quality; do you mind running the following commands at the root of your clone?
```
pip install -e ".[quality"]
make fixup
```

This should fix most quality issues and let you know if there are some the scripts cannot resolve.

**Comment by Narsil** [comment]
@NouamaneTazi .

I am not sure you PR achieves your desired goal:

You are changing another error than the error you're posting in the description.
You report `max_length is set to ....`    and are modifying another warning. Actually the error you're modifying is different and linked to using `min_length` and having a length very well smaller than `min_length`.


FWIW. Summarization usually ingests large texts, and tries to generate something between `min_length` and `max_length` of size as a summary.

If `input_length` < `min_length` or `input_length` < `max_length` then the summary is likely to be not very summarized (since the original string already fits the requirements, or worse, the summary is supposed to expand on it. (Since original text is smaller than the supposedly `min_length`.

Do that clarify why the warnings are originally here ? If yes, then maybe we could clarify the warning instead to make them self sufficient ?

The warnings originated here 9c683ef01e19c4dc1216dcd1ae3c8e7c44d7b2b9 (tried to get a better rationale for the `// 2` but doesn't seem to be explained)

**Comment by NouamaneTazi** [comment]
Hello @Narsil , thanks for your clarification.
Indeed, since I tried to make the quick fix using Github web IDE, it didn't save all my changes. Here are my intended changes:
* assert `max_length > min_length`
* assert `input_length > max_length` (if not suggest `max_length = input_length // 2`)
Do you think there is more checks to do?

**Comment by Narsil** [comment]
I think it should be fine to check both, but would that avoid the spam you were referring to ?

**Comment by NouamaneTazi** [comment]
Yes, because before the solution proposed wasn't clear:
`Your max_length is set to 50, but you input_length is only 46. You might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)`
Whereas now, we do propose a `max_length = input_length // 2` which should stop showing the error if fixed.

**Comment by Narsil** [comment]
Makes sense.

**Review by Narsil — APPROVED** [review]
LGTM

**Review by patrickvonplaten — APPROVED** [review]
Thanks!

**Pull request merged**
