### PR TITLE
check if None before use

### PR DESCRIPTION
**Pull request by jiqing-feng**
Hi @gante . We should check if the variable is None before we use it :)

### CODE REVIEW

**Comment by jiqing-feng** [comment]
Hi @amyeroberts @gante . Would you please review this PR? Thx!  The failed tests are not related to my changes.

**Review by gante — APPROVED** [review]
Thank you for the fix 🤗

**Comment by jiqing-feng** [comment]
Hi @amyeroberts , would you please take a look and review it? Thx!

**Review by amyeroberts — COMMENTED** [review]
Thanks for fixing @jiqing-feng! 

Could you provide some more context in the PR description on this issue this resolves, ideally with a small code snippet or description of the scenario? 

Could you also add a test which would have caught this?

**Comment by jiqing-feng** [comment]
> Thanks for fixing @jiqing-feng!
> 
> Could you provide some more context in the PR description on this issue this resolves, ideally with a small code snippet or description of the scenario?
> 
> Could you also add a test which would have caught this?

I see you have fixed it by checking `if model_kwargs.get("past_key_values") is not None`, which will ensure the cache is not None; it might be fixed in some updates when I rebase this PR since this PR has opened for almost a month. I am closing this PR since it has been fixed. Thx!

**Pull request closed without merging**
