### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by abedkhooli**
Model card for akhooli/mbart-large-cc25-en-ar

### CODE REVIEW

**Comment by julien-c** [comment]
@sshleifer want to update the inference API so that the correct pipeline shows up at https://huggingface.co/akhooli/mbart-large-cc25-en-ar ? (cc @mfuntowicz)

**Comment by sshleifer** [comment]
Seems fixed?
https://huggingface.co/akhooli/mbart-large-cc25-en-ar
image

**Comment by abedkhooli** [comment]
> 
> 
> Seems fixed?
> https://huggingface.co/akhooli/mbart-large-cc25-en-ar
> image
Sure, just after the model card was merged. Not sure if it was due to the 'translation' tag in the card or some other magic done by your team.

**Comment by abedkhooli** [comment]
Just uploaded https://huggingface.co/akhooli/mbart-large-cc25-ar-en and it seems inference type is not recognized automatically. It defaults to fill-mask (model card submitted).

**Comment by julien-c** [comment]
model card merged.

**Pull request merged**
