### PR TITLE
Add special tokens to documentation for bert examples to resolve issue: #1561

### PR DESCRIPTION
**Pull request by enzoampil**
**Currently the BERT examples only show the strings encoded without the inclusion of special tokens (e.g. [CLS] and [SEP]) as illustrated below:**
```
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
sentence = "Hello there, General Kenobi!"
print(tokenizer.encode(sentence))
print(tokenizer.cls_token_id, tokenizer.sep_token_id)

# [7592, 2045, 1010, 2236, 6358, 16429, 2072, 999]
# 101 102
```
**In this pull request i set add_special_tokens=True in order to include special tokens in the documented examples as illustrated below:**

```
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
sentence = "Hello there, General Kenobi!"
print(tokenizer.encode(sentence, add_special_tokens=True))
print(tokenizer.cls_token_id, tokenizer.sep_token_id)
# [101, 7592, 2045, 1010, 2236, 6358, 16429, 2072, 999, 102]
# 101 102
```

### CODE REVIEW

**Comment by thomwolf** [comment]
This is great thanks. Actually we should be adding this to all the examples for all the models...

**Comment by enzoampil** [comment]
@thomwolf  Would be happy to make the changes for the rest of the models.

**Comment by enzoampil** [comment]
@thomwolf added changes for the rest of the pytorch model examples and all the tensorflow model examples

**Comment by thomwolf** [comment]
Thanks for that.

@LysandreJik even though we will have special tokens added by default in the coming release, maybe we still want to update the doc for the current release with this? (not sure this is possible)

**Comment by LysandreJik** [comment]
I agree that the necessity to add special tokens should be explicit. However, the documentation is based on previous commits so changing the previous documentation would require to change the commit history of the repo (which we should not do). 

We might need to think of a way to work around that to update the misleading documentation of previous versions like in this case.

**Pull request merged**
