### PR TITLE
Minor type annotation fix

### PR DESCRIPTION
**Pull request by vwxyzjn**
# What does this PR do?

Very minor type annotation fix.

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing! 

To be able to merge we need the CI to be green. I looks like a timeout issue happened so just set things to re-run. Hopefully after that we can merge 🤞

**Review by younesbelkada — APPROVED** [review]
Thanks @vwxyzjn !!

**Comment by vwxyzjn** [comment]
Hi @amyeroberts thanks foe the comment!

```
FAILED examples/pytorch/test_accelerate_examples.py::ExamplesTestsNoTrainer::test_run_glue_no_trainer - AssertionError: 0.6666666666666666 not greater than or equal to 0.75
FAILED examples/pytorch/test_pytorch_examples.py::ExamplesTests::test_run_ner - AssertionError: 0.6674960851669312 not less than 0.5
```

Looks like the CI got the error above. Any thoughts?

**Comment by amyeroberts** [comment]
The good news is that these failures appear to be unrelated to your PR as I've seen them in other PRs today. The bad news is that we don't know what the issue is yet, looking into it now 🔍

**Comment by amyeroberts** [comment]
There's a PR open to resolve the failing tests: https://github.com/huggingface/accelerate/pull/2126

Once that's merged, we'll need to update the CI runners. I'll ping here once that's done and we can rebase and then (hopefully) merge

**Comment by vwxyzjn** [comment]
Great! Thanks @amyeroberts!

**Comment by amyeroberts** [comment]
@vwxyzjn Could you rebase on main? This should resolve the currently failing tests.

**Comment by vwxyzjn** [comment]
@amyeroberts thanks! I rebased but still seems to have some test case errors... 👀

**Comment by amyeroberts** [comment]
@vwxyzjn Could you try rebasing again? There were a few (more!) failures because of new package releases which should now be resolved. Sorry to ask you to again.

**Comment by amyeroberts** [comment]
@vwxyzjn Thanks again for this contribution and apologies for the issues with the CI

**Comment by vwxyzjn** [comment]
Thanks @amyeroberts for helping with the PR!

**Pull request merged**
