### PR TITLE
Enable testing against mi250

### PR DESCRIPTION
**Pull request by mfuntowicz**
Currently we are testing only against mi210 AMD devices, this PR enables testing on mi250 as well 🤗

### CODE REVIEW

**Comment by ydshieh** [comment]
Sorry for the previous long comment.

I might be able to do minimal changes to make the slack report work with the CI having 2 GPU favors like this PR. I will have to try though.

**Comment by mfuntowicz** [comment]
Yes 3 flavorsm nothing more expected so far 🙂

**Comment by ydshieh** [comment]
Your points are also valid :-) I have to make the changes to the slack reporting script. Could this PR wait a bit?

**Comment by ydshieh** [comment]
@mfuntowicz In order not to block this PR, let's go for duplicating. Eventually, I can rework when we decide a change is necessary at some point.

**Comment by ydshieh** [comment]
For @mfuntowicz to check #26634. If it is fine, we can incoperate the changes into this PR.

**Comment by ydshieh** [comment]
@mfuntowicz any comment for #26634 ?

**Comment by mfuntowicz** [comment]
Just approved it, thanks a lot @ydshieh 🙏🏻.

LMK if there is anything i need to take a look at to merge these PRs :)

**Comment by ydshieh** [comment]
Close in favor of #26634. Will add mfuntowicz as the contributor.

**Pull request closed without merging**
