### PR TITLE
[Pixtral] Improve docs, rename model

### PR DESCRIPTION
**Pull request by NielsRogge**
# What does this PR do?

This PR is a follow-up to #33449, some cosmetic updates, and renaming `PixtralModel` to `PixtralVisionModel` for consistency with models like `SiglipVisionModel`.

### CODE REVIEW

**Comment by NielsRogge** [comment]
cc @ArthurZucker feel free to takeover, not sure why CI is failing (`make fixup` is passing locally)

**Review by ArthurZucker — COMMENTED** [review]
Thanks, can you make sure slow ci pass with `https://huggingface.co/mistral-community/pixtral-12b` 🤗 Won't have time to take over, rebasing should help

**Review by ArthurZucker — COMMENTED** [review]
Can you rebase as well ? 🤗 good to go otherwise

**Comment by ArthurZucker** [comment]
Merging I will fix failing in my end

**Pull request merged**
