### PR TITLE
added type hints for Yolos Pytorch model

### PR DESCRIPTION
**Pull request by WhiteWolf47**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by WhiteWolf47** [comment]
@sgugger can you please help?

**Comment by Rocketknight1** [comment]
This looks good, but a few comments!

1) You'll need to run `make fixup` to ensure our code style stays consistent. You might need to install the dev dependencies for that, [see here](https://huggingface.co/docs/transformers/contributing#start-contributing-pull-requests)
2) We'd prefer to just use the built-in `bool` rather than `traitlets.Bool`
3) The most important methods to add type hints to are the `forward()` methods on the main model classes (e.g. in `modeling_yolos.py`). Still, I'll totally accept PRs covering other methods!

**Comment by WhiteWolf47** [comment]
@sgugger pls help

**Comment by WhiteWolf47** [comment]
> This looks good, but a few comments!
> 
> 1. You'll need to run `make fixup` to ensure our code style stays consistent. You might need to install the dev dependencies for that, [see here](https://huggingface.co/docs/transformers/contributing#start-contributing-pull-requests)
> 2. We'd prefer to just use the built-in `bool` rather than `traitlets.Bool`
> 3. The most important methods to add type hints to are the `forward()` methods on the main model classes (e.g. in `modeling_yolos.py`). Still, I'll totally accept PRs covering other methods!

hey, i installed the dev dependencies but make fixup is giving error: no such file or directory

**Comment by Rocketknight1** [comment]
Alright, let me see if I can run it here!

**Review by Rocketknight1 — APPROVED** [review]
Looks good to me now - I deleted the `traitlets.Bool` thing, but aside from that I'm happy with it!

**Comment by WhiteWolf47** [comment]
> Looks good to me now - I deleted the `traitlets.Bool` thing, but aside from that I'm happy with it!

Thanks man, It feels good finally get my first PR on transformers, looking forward to contributing more

**Pull request merged**
