### PR TITLE
Fix import error of tf 2.4.1 on TPU.

### PR DESCRIPTION
**Pull request by innat**
# What does this PR do?

The import of https://github.com/huggingface/transformers/blob/06a6a4bd516f7d0ba7c4966a2d3d9c0bf07797ae/src/transformers/modeling_tf_utils.py#L39

should be 

```python
from tensorflow.python.keras.saving.hdf5_format import save_attributes_to_hdf5_group
```

Otherwise, model like CLIP-TensorFlow can't import in TF 2.4.1 on TPU (kaggle env).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by innat** [comment]
@sgugger 
Could you please take a look into this. It's a very short fix.

**Comment by LysandreJik** [comment]
@gante, could you take a look at this?

**Comment by LysandreJik** [comment]
It seems there is an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

**Comment by gante** [comment]
Hey @innat -- the change looks good, but we still want to default to the public namespace.

Can you wrap the import in a try/except block? (try importing the original, and import the line you added if it fails)

**Comment by innat** [comment]
@gante I think it's done. Please check.

**Review by gante — APPROVED** [review]
LGTM 👍 

(Have a look at Lysandre's comment, to enable CI. Without a CI run, we can't merge the PR :) )

**Comment by gante** [comment]
Hi @innat -- can you have a look at Lysandre's comment, to allow CI to run?

Alternatively, you can follow [this guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to give me write access over this PR, and I'll take care of the rest :)

**Pull request closed without merging**
