### PR TITLE
[`Mamba2`] Move dt calculations to kernel

### PR DESCRIPTION
**Pull request by vasqu**
# What does this PR do?
Moves calculations of `time_step` to the kernel instead of using torch's softplus directly. It seems like it influences the end result even more than expected, see https://github.com/sustcsonglin/flash-linear-attention/issues/63 for reference (2. point made there). 

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @molbap

### CODE REVIEW

**Comment by vasqu** [comment]
Maybe for clarification the referenced repo's mamba2 is mostly a mirror of this one.

**Comment by molbap** [comment]
Thanks for the PR! Very interesting, not opposed but what exactly changes between the in-kernel and out-of-kernel computation results? Train mode vs eval mode yield different results? In that case we should also add it as a minimal test specific for mamba2!

**Comment by vasqu** [comment]
Just seems like that it's more aligned with the completely fused kernel then, or rather the numerical differences are minimized. Tbh it's a huge nit in of itself :D 

I can add a slow test that requires a GPU and the kernels; would be a copy paste of the test in the repo.

**Review by molbap — APPROVED** [review]
Nice, just needs the copy-pasted test indeed (credit to the other repo) for future code inspectors!

**Review by amyeroberts — APPROVED** [review]
Nice! thanks for updating

Final step is running the slow tests for the model before merge, as this might have affected the integration tests. Could you push an empty commit with the message `[run_slow] mamba`?

**Comment by vasqu** [comment]
I'll write the test tomorrow and ping you then; I don't have much time this evening.

**Comment by vasqu** [comment]
Would be ready but ig waiting for #33560 to be merged seems appropriate for now :eyes: 
cc @amyeroberts

**Comment by vasqu** [comment]
Does it need a new decorator to check if the kernels are available or is it directly included in the slow runs? Might need an updated image if that's not the case. @molbap

**Comment by molbap** [comment]
Nope, there's no such decorator! Slow run ought to do it :)

**Comment by vasqu** [comment]
Good to go now :) #33567 is to be expected
cc @amyeroberts (sry for the constant pinging)

**Comment by amyeroberts** [comment]
@vasqu Pings are always welcome - it makes sure things aren't lost in the notification inbox :)

**Pull request merged**
