### PR TITLE
Add DPT hybrid

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

Adds DPT Hybrid support to `transformers`

Do not merge until #20550 gets merged

cc @NielsRogge @sgugger @patrickvonplatten @patil-suraj

### CODE REVIEW

**Comment by sgugger** [comment]
You should have opened your PR to go on the branch adding BiT and VitHybrid as the PR is not easy to review as it is.

**Comment by younesbelkada** [comment]
Yes sorry :/  Let me open a PR on the other branch

**Comment by younesbelkada** [comment]
Here is a much cleaner version of the PR: https://github.com/NielsRogge/transformers/pull/51 ;)

**Comment by younesbelkada** [comment]
Closing in favor of https://github.com/huggingface/transformers/pull/20645

**Pull request closed without merging**
