### PR TITLE
Add AMD nightly CI

### PR DESCRIPTION
**Pull request by fxmarty**
As per title.

### CODE REVIEW

**Comment by ydshieh** [comment]
Thank you @fxmarty .

But I think the priority is to have a daily (complete) CI run for `latest torch version`. It's like `.github/workflows/self-scheduled.yml` (maybe ignore the deepspeed part etc.).

We have push event for AMD CI, but it is really difficult to follow (as there are always some failures, even for nvidia!). Even for Nvidia CI, others and me almost only look the result of the daily (complete) run.

Of course, if you really want to have this nightly CI (i.e. with nightly torch version) before the `daily CI with stable torch`, I am happy to review and merge once it is all good.

**Comment by fxmarty** [comment]
Sounds good @ydshieh, indeed it makes sense to have first a scheduled CI for tests on PyTorch stable, and merge this one later on. It should be pretty similar, I will ping you there.

**Comment by mfuntowicz** [comment]
Thanks @ydshieh, will give the priority as you mentioned:
- daily
- then, nightly

DeepSpeed should works OOB, so maybe let's try to include it right away @fxmarty?

**Comment by ydshieh** [comment]
scheduled CI involves more stuff: 4 different docker images, example test job, (torch/tf)pipeline test jobs etc.

we will also have a new slack channel for the report (I can take care of this) + a way to display the diff between the latest run with the previous run (all these could be treated toward the end)

**Pull request closed without merging**
