### PR TITLE
Fix TF nightly tests

### PR DESCRIPTION
**Pull request by Rocketknight1**
This PR fixes two issues with the TF tests:

1) `test_saved_model_creation` failed sometimes because the dict being passed to the saved model didn't match the inputs it was traced/compiled with. This should be fixed now.

2) Some of the tests for the new `TFGPT2Tokenizer` (cc @piEsposito) were using `is_tensorflow_text_available` or `requires_tensorflow_text`, but `TFGPT2Tokenizer` actually depends on `keras-nlp`. I made sure the requirements were changed and that `is_keras_nlp_available` is importable from the root.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for the fixes!

**Review by ydshieh — APPROVED** [review]
Good for me with a tiny change I believe :-)

We are going to have 0 TF failure soon, thank you @Rocketknight1 !!!

**Review by piEsposito — APPROVED** [review]
Thank you for mixing my mistake of the TF GPT2 Tokenizer test.

**Comment by Rocketknight1** [comment]
Don't worry, it was a really small fix! Just making sure you saw this so you didn't get confused about why your code was being changed.

**Pull request merged**
