### PR TITLE
Feature: Option to set the tracking URI for MLflowCallback.

### LINKED ISSUE #28961: Option to set the tracking URI for MLflowCallback.
### Feature request

Option to set not only the experiment name but also the tracking URI for MLflow.

### Motivation

My company and I use our own MLflow URI and all of our code has `mlflow.set_tracking_uri($URI)` inside. I'm not seeing such an option for the MLflowCallback and am only seeing an option to set the experiment.

The `run_name` seems to be using the `run_name` value in TrainingArguments, so there's not really any problem with that.

### Your contribution

It seems like adding a few lines of code to the `setup` method would do the trick.

https://github.com/huggingface/transformers/blob/345b9b1a6a308a1fa6559251eb33ead2211240ac/src/transformers/integrations/integration_utils.py#L952

### PR DESCRIPTION
**Pull request by seanswyi**
# What does this PR do?

Previously, the MLflowCallback was only able to set MLflow experiments or runs. This PR adds the option to also set the tracking URI.

Fixes https://github.com/huggingface/transformers/issues/28961

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. https://github.com/huggingface/transformers/issues/28961
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

- Trainer maintainers: @muellerzr @pacman100
- Original author of MLflowCallback: @noise-field (https://github.com/huggingface/transformers/commit/c48b16b8da991ba87ca82ed03e33481fc712fbfa)

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for adding! Changes LGTM

Third-party integrations are maintained by their original contributors, rather than the transformers team. So let's get a review from @noise-field

**Comment by seanswyi** [comment]
Sounds good, thanks for the feedback @amyeroberts! I just made another minor change in the docstring and committed it: the default value of `MLFLOW_TRACKING_URI` should be an empty string rather than `None`.

**Comment by amyeroberts** [comment]
@seanswyi I can re-run tests for you. I've just set `tests_torch` run off again

**Review by muellerzr — APPROVED** [review]
Thanks for the quick turnaround!

**Comment by amyeroberts** [comment]
@seanswyi As everything is passing and both @muellerzr and I approve, let's just merge and if @noise-field has any comments we can do a follow-up PR. 

Thanks again for adding!

**Comment by harupy** [comment]
I'm an MLflow maintainer. What if we run this code like this?

```python
import mlflow
import os

assert "MLFLOW_TRACKING_URI" not in os.environ
mlflow.set_tracking_uri("sqlite:///my.db")

# train
```

**Comment by seanswyi** [comment]
@harupy Could you elaborate a bit on why you think that would be better? The reason I wrote the initial PR the way I did is because to me it made sense to allow the user to keep `MLFLOW_TRACKING_URI` as an environment variable along with the other MLflow-related environment variables such as `MLFLOW_RUN_NAME`. I also left the default value as an empty string because that seemed to be consistent with MLflow's documentation as well (https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.set_tracking_uri). I feel like the snippet you provided takes away that control from the user, as it actually seems to be enforcing the user keep the tracking URI to a hardcoded value of `"sqlite:///my.db"`.

Please let me know if I'm misunderstanding or missing something. I haven't been able to fully look into the failed tests you provided but it seems like there's an issue between this PR and the [autologging module](https://github.com/mlflow/mlflow/blob/e27821c256ff08879f17721adb0b034552f2cf2c/mlflow/tracking/fluent.py#L2013)?

**Comment by harupy** [comment]
@seanswyi

> I feel like the snippet you provided takes away that control from the user, as it actually seems to be enforcing the user keep the tracking URI to a hardcoded value of "sqlite:///my.db".

True, but there may be users who use the code like this (we do something similar in our tests, no `MLFLOW_TRACKING_URI` env var, just all `mlflow.set_tracking_uri` with a temporary database name). Can we avoid defaulting to an empty string?

**Comment by seanswyi** [comment]
@harupy If you believe that only calling the function when the environment variable exists is better then how about changing the current code to something like this?

```Python
if "MLFLOW_TRACKING_URI" in os.environ:
    self._tracking_uri = os.environ["MLFLOW_TRACKING_URI"]
    logger.debug(f"MLflow tracking URI is set to {self._tracking_uri}")
    self._ml_flow.set_tracking_uri(self._tracking_uri)
else:
    logger.debug(f"Environment variable `MLFLOW_TRACKING_URI` is not provided and therefore will not be explicitly set.")
```

Just curious, is there any reason why a temporary SQLite DB is used? It seems like the documentation would suggest that setting a tracking URI isn't necessary and that the data will just be stored locally at `./mlruns`.

**Comment by harupy** [comment]
> is there any reason why a temporary SQLite DB is used?

To run tests faster.

**Comment by njbrake** [comment]
Hi! I'm here because this PR broke my code :) I think there might be a compatibility break here? 

In my code I call `mlflow.set_tracking_uri(my_mlflow_tracking_uri)`  , but I never set the MLFLOW_TRACKING_URI env var. Is there a way to change this logic so that it checks if the tracking_uri was already set in the mlflow library? In my case it appears that the code 
```
        self._tracking_uri = os.getenv("MLFLOW_TRACKING_URI", "")
        self._experiment_name = os.getenv("MLFLOW_EXPERIMENT_NAME", None)
        self._flatten_params = os.getenv("MLFLOW_FLATTEN_PARAMS", "FALSE").upper() in ENV_VARS_TRUE_VALUES
        self._run_id = os.getenv("MLFLOW_RUN_ID", None)
        logger.debug(
            f"MLflow experiment_name={self._experiment_name}, run_name={args.run_name}, nested={self._nested_run},"
            f" tags={self._nested_run}"
            f" tags={self._nested_run}, tracking_uri={self._tracking_uri}"
        )
```
means that the tracking_uri is getting overriden to be "" because I didn't set the env var.

I can change my implementation to be compatible with the change that was merged, but others may have similar issues if their implementation was similar to mine.

**Comment by seanswyi** [comment]
Hi @njbrake! Thanks for the comment, that's something that I missed earlier. The MLflow API seems to provide a [`mlflow.get_tracking_uri()`](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.get_tracking_uri) and [`mlflow.is_tracking_uri_set()`](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.is_tracking_uri_set) function. It would probably be better to check before initializing `self._tracking_uri`.

Maybe I could incorporate this in the other PR (https://github.com/huggingface/transformers/pull/29096) that addresses @harupy's previous comment as well? (cc. @amyeroberts)

**Comment by amyeroberts** [comment]
@seanswyi Yes please!

**Pull request merged**
