### PR TITLE
Update CometCallback to allow reusing of the running experiment

### PR DESCRIPTION
**Pull request by Lothiraldan**
# What does this PR do?

Update CometCallback to allow reusing of the running experiment.

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Hi @Lothiraldan, thanks for opening a PR! Let us know when it's ready for review. 

cc @muellerzr

**Comment by Lothiraldan** [comment]
Hi @amyeroberts, I wanted to open a PR in our fork for internal review first. Sorry about the noise.

I can close this one, reopen one in our fork or leave this one open and have the comments shared internally, let me know what would works best for you.

**Comment by amyeroberts** [comment]
@Lothiraldan Any of the options work for us. We can leave this open until your internal review has happened, this PR has been updated to reflect the review and then you can just ping us when it's ready :)

**Comment by Lothiraldan** [comment]
@amyeroberts Hi, this PR is now ready for a review. Sorry for the delay, the internal reviews highlighted some potential improvements that took a bit of time.

**Review by muellerzr — APPROVED** [review]
Thanks, this looks good to me. cc @amyeroberts for final review? :)

**Review by LysandreJik — APPROVED** [review]
Clean handling of the versioning. LGTM!

**Pull request merged**
