### PR TITLE
Add GeoLM

### PR DESCRIPTION
**Pull request by zekun-li**
# What does this PR do?

Add a new model called **GeoLM** into the Transformer library. GeoLM is a language model based on BERT that facilitates **geospatial understanding** in NL documents. It is pretrained on world-wide OpenStreetMap (OSM), WikiData and Wikipedia data, and can be adapted to various geospatial related downstream tasks such as **toponym recognition** and **toponym linking**.

Paper not published yet. 

## Model Weights:
* Pretrained GeoLM (ready-to-use for zero-shot toponym linking): [zekun-li/geolm-base-cased](https://huggingface.co/zekun-li/geolm-base-cased)
* Fine-tuned GeoLM for toponym recognition: [zekun-li/geolm-base-toponym-recognition](https://huggingface.co/zekun-li/geolm-base-toponym-recognition)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Open Source Status: 
- [x] The model implementation is available in this PR
- [x] The model weights are available in HuggingFace model hub

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. 

Feel free to tag members/contributors who may be interested in your PR:  @sgugger , @ArthurZucker and @younesbelkada

### CODE REVIEW

**Comment by zekun-li** [comment]
I made a new commit in my fork to fix the Build PR Documentation check. Is there a way to update this PR or I need to create a new PR?

**Comment by amyeroberts** [comment]
Hi @zekun-li, thanks for opening this PR! 

The easiest and recommended way to make a model available in transformers is to add the modeling code directly on the hub: https://huggingface.co/docs/transformers/custom_models

This means, once working, the model can be found and used immediately without having to go through the PR process. We find this is a lot quicker as the bar for adding code into the library is high due to the maintenance cost of every new model, and so reviews take quite a while.

Let us know if you have any questions about how to add a model using this process. Looking forward to seeing this model in action!

**Comment by zekun-li** [comment]
> Hi @zekun-li, thanks for opening this PR!
> 
> The easiest and recommended way to make a model available in transformers is to add the modeling code directly on the hub: https://huggingface.co/docs/transformers/custom_models
> 
> This means, once working, the model can be found and used immediately without having to go through the PR process. We find this is a lot quicker as the bar for adding code into the library is high due to the maintenance cost of every new model, and so reviews take quite a while.
> 
> Let us know if you have any questions about how to add a model using this process. Looking forward to seeing this model in action!

Hi @amyeroberts Thanks a lot for the suggestion! 

Although this model is built upon BERT, it has a customized embedding layer and the model input can be different from BERT. This model can take geocoordinates as additional inputs. So unlike the changes of using different values for `num_layers` or `num_hidden_units`,  these changes require a different model structure, which is not supported in the existing models in Transformer.  

I wonder are these supported in the "Sharing custom models" approach? 

Thanks for your time!

**Comment by amyeroberts** [comment]
@zekun-li Yes - you can add any model architecture directly onto the hub and share the model that way! In fact, it's an even more flexible way to define models as you don't have to be as strict about following certain library patterns.

**Pull request closed without merging**
