### PR TITLE
Refactoring checkpoint names for multiple models

### LINKED ISSUE #10193: Make use of our copy-consistency script for task-specific models
This is an intermediate issue, which is why it gets both the good first issue and good second issue tags.

We have an automated script to check when copies of the same code are consistent inside the library, which allows us to avoid subclassing and keep all code for one model's forward pass inside one file (see our [philosophy]() for more details on this).

The XxxModelForYyy are very similar to one another and should be able to leverage that functionality, so we can easily change only one file when there is a bug/docstring to tweak and all the others are updated. More precisely, models that have a pooler layer could probably base themselves on BERT and models that don't could be based on ELECTRA. The Seq2Seq models that are a bit particular could be based on BART.

To enable this, the checkpoint use in the decorator `@add_code_sample_docstrings` needs to be defined in a constant (otherwise it will end up being copied which we don't want) so to tackle this issue, your mission, should you accept it, will have two steps:

1. Define in all modeling files a `_CHECKPOINT_FOR_DOC` at the beginning (with `_TOKENIZER_FOR_DOC` and `_CONFIG_FOR_DOC`) that should then be used in all the XxxModelForYyy. 
2. Adds the relevant `# Copied from xxx with Xxx -> Yyy` whenever possible.

### PR DESCRIPTION
**Pull request by danielpatrickhug**
Hi, @sgugger reupload without datasets dir and added tf_modeling files, removed extra decorator in distilbert.
Linked to #10193, this PR refactors the checkpoint names in one private constant. 

one note: longformer_tf has two checkpoints "allenai/longformer-base-4096" & "allenai/longformer-large-4096-finetuned-triviaqa". I set the checkpoint constant to "allenai/longformer-base-4096" and left the one decorator with "allenai/longformer-large-4096-finetuned-triviaqa".

Fixes #10193

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by danielpatrickhug** [comment]
...The test pasts on my local machine, I ran make test, style, quality, fixup. I dont know why this failed..

**Review by sgugger — APPROVED** [review]
Thanks a lot for adding the TF models! The failures are unrelated I think, and due to the PyTorch 1.8 release.

**Review by LysandreJik — APPROVED** [review]
Very cool, thanks for taking care of it!

**Comment by LysandreJik** [comment]
I just rebased the PR to ensure that the tests pass. We'll merge if all is green!

**Comment by danielpatrickhug** [comment]
Thanks guys. my b for the delay

**Pull request merged**
