### PR TITLE
no need for explicit EXTRA_TOKENS in processing_paligemma.py

### PR DESCRIPTION
**Pull request by grahamannett**
# What does this PR do?

Jumping into processing_paligemma.py from vim/vscode with text wrapping is very unsettling.  

Seems also in the future someone might implement the loc/seg as part of the processor like it is done for other multimodal models such as Fuyu/CogAgent/etc as it does not seem to be now.  In which case loc/seg might be in variable names and with the EXTRA_TOKENS as is will be a huge headache if searching for loc/seg.  

Also means you dont have to `# fmt: skip` :)

I can see explicitly giving them if there was more randomness or less tokens but for 1152 tokens that are essentially just numbers it seems too much.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Did you write any new necessary tests?
    - Should I write a test that `EXTRA_TOKENS == ['<loc0000>', '<loc0001>', '<loc0002>', ... ]`?

## Who can review?
Guessing from previous PaliGemma
@ArthurZucker @molbap

### CODE REVIEW

**Comment by molbap** [comment]
Thanks for the formatting PR, seems good: the manual addition was necessary due to a missed conversion of the slow to fast gemma tokenizer that is due to a `sentencepiece` bug. Hence the need for this addition

**Comment by grahamannett** [comment]
@molbap Not sure I understand exactly what you mean but does that mean this wont be merged?  In terms of these loc/seg tokens, is there any info for how ideally they should be created for finetuning/training the model further?  I get that <loc> will be 4x to be a box (and comes from scaling the coords to 1024) but I dont really follow where the <seg> * 16 is decided based on for instance https://huggingface.co/spaces/big-vision/paligemma/blob/main/paligemma_parse.py (e.g. will it always be 16? and is that 16 specific to that included VAE?)

It seems like the next step for the PaliGemma processor would be to integrate the processing/scaling of the input tokens somehow similar to how Kosmos2 and Fuyu have it as part of their processor, or is that not something that is likely to be integrated into this models processor and should be fully handled by the user?

**Comment by molbap** [comment]
Regarding this PR in particular nope as I said, sounds good, cc @ArthurZucker 
For your 2 other questions: 1) no, there's no specific info from the model authors, I'd assume you pass the needed seg/loc tokens in your training `suffix` (in the processor) based on a classical bounding box/segmentation coords setup. 2) And there's no plan to integrate more advanced processing of these tokens in the model processor just yet, but feel free to open a PR on that if you have a design in mind!

**Review by ArthurZucker — COMMENTED** [review]
as long as this does not slow down importing the model, DOWN! 
can we just test this? 
cc @ydshieh as en example of thing too lookout for !

**Comment by grahamannett** [comment]
How would this slow down the model?  The time delta to generate the list versus explicit writing the values is going to be extremely small for a list of this size and if the list became massively greater seems like it would be preferable to move into another file?

Mostly this seemed like a very simple merge to not have loc/seg take up a large amount of screen and also I was patching PaliGemmaProcessor to add loc/seg input/output for a given image with scaling and it ruined the ability to search for loc/seg in the file (which was annoying to me). 

Its not even really a good benchmark since these lists/values arent being imported anywhere as they are used in the __init__ for a pretrained model but here:

```python
# tokens_explicit.py
EXTRA_TOKENS = ['<loc0000>', '<loc0001>', '<loc0002>', ...
```

```python
# tokens_listcomprehension.py
EXTRA_TOKENS = [f"<loc{i:0>4}>" for i in range(1024)] + [
    f"<seg{i:0>3}>" for i in range(128)
]
```


```python
# benchmark.py
import timeit

n = 10000
print("explicit time", timeit.timeit(stmt="import tokens_explicit", number=n))
print("lc time", timeit.timeit(stmt="import tokens_listcomprehension", number=n))
```

```bash
> python benchmark.py
explicit time 0.001373915933072567
lc time 0.0015027918852865696
```

**Review by ArthurZucker — APPROVED** [review]
You are right, the EXTRA_TOKENS is not directly used so unless we import * from the file, only `__init__` will get a tiny slow down. 
Good for me

**Pull request merged**
