### PR TITLE
Pass datasets trust_remote_code

### PR DESCRIPTION
**Pull request by albertvillanova**
# What does this PR do?

Next release of `datasets` will raise an error for script-datasets if `trust_remote_code` is not set to True.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by albertvillanova** [comment]
I think this is more intricate than I first thought.

What about if I make another PR to pin upper version of datasets and then handle this PR more calmly?

**Comment by amyeroberts** [comment]
> What about if I make another PR to pin upper version of datasets and then handle this PR more calmly?

Sounds good! 

> Should we define it in DataTrainingArguments?

Happy with that 👍

**Review by ydshieh — APPROVED** [review]
Thank you @albertvillanova ! LGTM, but I have 2 questions:

- Any reason that we don't have this `trust_remote_dataset_code` in all files in `examples` that has `class DataTrainingArguments`? (it seems this PR only adds to some files)

- I would like to have @muellerzr 's comment as he deals with `examples` folder frequently
- I guess the name `trust_remote_dataset_code` is because we have used `trust_remote_code` for `ModelArguments`, right? Would like @amyeroberts 's opinion on this too.

**Comment by amyeroberts** [comment]
> I guess the name trust_remote_dataset_code is because we have used trust_remote_code for ModelArguments, right? Would like @amyeroberts 's opinion on this too.

So if the argument already exists in `ModelArguments` we can either add `trust_remote_dataset_code` to `DataTrainingArguments` or just use the one from `ModelArguments`. I'd do that latter for simplicity: I don't really see why we'd trust the model code and not the datasets' code, and from the users' perspective on the CLI they don't see that the division of the arguments.

**Comment by ydshieh** [comment]
> > I guess the name trust_remote_dataset_code is because we have used trust_remote_code for ModelArguments, right? Would like @amyeroberts 's opinion on this too.
> 
> So if the argument already exists in `ModelArguments` we can either add `trust_remote_dataset_code` to `DataTrainingArguments` or just use the one from `ModelArguments`. I'd do that latter for simplicity: I don't really see why we'd trust the model code and not the datasets' code, and from the users' perspective on the CLI they don't see that the division of the arguments.

Yeah, I would love the latter if `HfArgumentParser` could handle a single `trust_remote_code` and assign it to both `ModelArguments` and `DataTrainingArguments`

**Comment by albertvillanova** [comment]
Thanks for your reviews, @amyeroberts and @ydshieh.

So, you would prefer to have just a single `trust_remote_arg` that should be defined `ModelArguments` (as it was already the case for some examples) but also used to load the dataset? Something like:
```python
load_dataset(
    trust_remote_code=model_args.trust_remote_code,
```

**Comment by ydshieh** [comment]
Hi @albertvillanova Not really. What I am thinking is:

- we only need to specify `--trust_remote_code` on the commandline
- have `trust_remote_code` defined in `ModelArguments` and/or `DataTrainingArguments` (could be only one or could be both depends on the usage)
- `HfArgumentParser` take `trust_remote_code` from commandline, and assign it to both `ModelArguments.trust_remote_code` and `DataTrainingArguments.trust_remote_code`
  - for this, I don't know if  `HfArgumentParser` already handle this, **need to verify**.
  - if this is not (currently) possible + if this PR needs to be merged **urgently**, we might need to use `trust_remote_dataset_code` for now and come back to it once merged. (But changing arguments afterwards is not so good)
- and later in the code,  we can use `data_args.trust_remote_code` for `load_dataset` (and `model_args.trust_remote_code` for model related code)

**Comment by albertvillanova** [comment]
Thanks, @ydshieh.

I will check if `HfArgumentParser` can assign the argument to both.

On the other hand, for the cases where `ArgumentParser` is used directly, I think the change is trivial. See example commit: [8380ae5](https://github.com/huggingface/transformers/pull/31406/commits/8380ae57f53bdb7891b8754bb04d314e3db6bd81)

**Comment by albertvillanova** [comment]
The assignment of the argument by `HfArgumentParser` to both is not trivial. I will leave that for a subsequent PR.

In this PR, I will use `trust_remote_code` as `ModelArguments` if it already existed before this PR, or as `DataTrainingArguments` if it is added in this PR and only udes within `load_dataset`.

**Comment by ydshieh** [comment]
> The assignment of the argument by `HfArgumentParser` to both is not trivial. I will leave that for a subsequent PR.

Thanks for checking @albertvillanova. That part is rather on our side, but if you want to take it, that would be much appreciated.

> In this PR, I will use `trust_remote_code` as `ModelArguments` if it already existed before this PR, or as `DataTrainingArguments` if it is added in this PR and only used within `load_dataset`.
> 
>     * Note that `ModelArguments` are already used in `load_dataset`, e.g. `token=model_args.token`

Works for me :-)

**Review by amyeroberts — APPROVED** [review]
Thanks for handling all of these cases!

**Pull request merged**
