### PR TITLE
[Tentative] Adds support for exporting TransformerXL-based models to ONNX

### PR DESCRIPTION
**Pull request by gugarosa**
# What does this PR do?

Hello everyone! I hope everything is going well with you.

This PR adds a naïve support when trying to export a TransformerXL model with ONNX. Nevertheless, this is a tentative PR as PyTorch still does not support the newest ONNX opset versions (13+), which includes `triu` and `tril` operators (required by TransformerXL).

As soon as PyTorch updates its API, any reflected change will also be updated in this PR. Meanwhile, this tentative PR serves as a guide to anyone that needs to export their model.

**Note:** there is a trick to leverage `triu` and `tril` operators by hand-implementing them with a compatible format to ONNX, instead of using the ones PyTorch's provides.

Best regards,
Gustavo.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
It seems I'm facing the issue you mention about `tril` when trying to export a Transfo-XL model using your PR:
```
RuntimeError: Exporting the operator triu to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

Is this due to a mismatch in `onnxruntime` version? cc @mfuntowicz

**Comment by gugarosa** [comment]
> It seems I'm facing the issue you mention about `tril` when trying to export a Transfo-XL model using your PR:
> 
> ```
> RuntimeError: Exporting the operator triu to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
> ```
> 
> Is this due to a mismatch in `onnxruntime` version? cc @mfuntowicz

Exactly! Actually, the main problem is that onnx/onnxruntime added the `triu` operator on opset version 13 (if I am not mistaken), but PyTorch has not released a version which supports such version yet (current PyTorch opset version 12).

In my humble opinion, I guess this PR should be staled until PyTorch releases their new version, hopefully by the end of the month. With that in mind, we do not need to leverage the `triu` operator or even implement a hacked-version that allows to be exported to ONNX.

What do you think?

**Comment by LysandreJik** [comment]
I see - thank you for the explanation. I'll add the `WIP` label to the PR so that the stalebot does not close it, and let's revisit once pytorch 1.10 comes out.

**Comment by genolve** [comment]
Torch nightly now has opset 14 with support for both triu/tril, however my testing had these issues:
**1) both triu and tril want a constant for the diagonal parameter**
A work-around hack is  to:
use model config:
        same_length=False
and this code change in modeling_transfo_xl.py (line 908 and 945):

> if mems is None and False:
>             mems = self.init_mems(bsz)
> ...
> if mems is not None:
>                 print("WARNING: if using mems no onnx export")
>                 dec_attn_mask = torch.triu(word_emb.new_ones((qlen, klen), dtype=torch.uint8), diagonal=1 + mlen)[:, :, None]
>  else:
>                 dec_attn_mask = torch.triu(word_emb.new_ones((qlen, klen), dtype=torch.uint8), diagonal=1)[:, :, None]

**2) The export command 
python -m transformers.onnx --model models --feature causal-lm --opset 14 models_onnx
still gives an error:**

> File "/home/craig/envcond/transformers/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 378, in _create_inference_session
>     sess.initialize_session(providers, provider_options, disabled_optimizers)
> onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Trilu(14) node with name 'Trilu_64'

**Pull request closed without merging**
