### PR TITLE
[WAITING YOUR REVIEW] Issue #2196: now it's possible to save PreTrainedEncoderDecoder objects correctly to file system

### PR DESCRIPTION
**Pull request by TheEdoardo93**
**Details implemented in this PR:**

- [X] Create the output directory (whose name is passed by the user in the "save_directory" parameter) where it will be saved encoder and decoder, if not exists.
- [X] Empty the output directory, if it contains any files or subdirectories.
- [X] Create the "encoder" directory inside "save_directory", if not exists.
- [X] Create the "decoder" directory inside "save_directory", if not exists.
- [X] Save the encoder and the decoder in the previous two directories, respectively.

### CODE REVIEW

**Comment by TheEdoardo93** [comment]
My PR has passed all tests except **build_py3_torch_and_tf** which returns `Received "segmentation fault" signal`. I don't know how to fix this issue, and I think that the code I've written doesn't cause this issue. Any ideas please?

**Comment by TheEdoardo93** [comment]
@julien-c @LysandreJik @thomwolf you can review my code for solving issue #2196 :)

**Comment by LysandreJik** [comment]
Cool, thanks @TheEdoardo93 ! Do you mind if I clean the commits as to not have a merge commit (rebasing on master instead)? I'll push directly on your fork if that's okay. You'll still be the author of the commits.

**Comment by TheEdoardo93** [comment]
The steps I’ve done for this PR are the following:
- make my changes on the source code
- git add/commit/push
- after that, the automatic tests start to run but an error of “segmentation fault” occurs
- i’ve changed a line only for “redo” the testa suite after the bug was solved, but my local branch was below “master”. I didn’t see this fact so I didn’t do a “git pull”. After that, I’ve done git add/commit/push and run the tests suite and now the tests suite is working without error

Said so, my changes only occurs in my first commit. The other ones are due to Transformers’ master changes. Have I answered to you? I hope yes.

**Comment by LysandreJik** [comment]
I rebased your code on the current master branch so that there's only the two commits. Thanks @TheEdoardo93.

**Comment by julien-c** [comment]
I feel like this is very verbose so let's maybe revisit when we drop Python 2 support.

**Pull request merged**
