### PR TITLE
fix to ensure that returned tensors after the tokenization is Long

### LINKED ISSUE #7026: RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.FloatTensor instead (while checking arguments for embedding)
## Environment info

     
- `transformers` version: 3.1.0
- Platform: Linux-4.19.0-10-amd64-x86_64-with-debian-10.5
- Python version: 3.6.10
- PyTorch version (GPU?): 1.3.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Information

Model I am using (GPT2-large) for fine-tuning on custom data:

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)

Trace:

>   File "gpt_language_generation.py", line 209, in <module>
>     main()
>   File "gpt_language_generation.py", line 136, in main
>     trainer.train(model_path=None)
>   File "<conda_env>/lib/python3.6/site-packages/transformers/trainer.py", line 708, in train
>     tr_loss += self.training_step(model, inputs)
>   File "<conda_env>/lib/python3.6/site-packages/transformers/trainer.py", line 995, in training_step
>     outputs = model(**inputs)
>   File "<conda_env>/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "<conda_env>/lib/python3.6/site-packages/transformers/modeling_gpt2.py", line 731, in forward
>     return_dict=return_dict,
>   File "<conda_env>/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "<conda_env>/lib/python3.6/site-packages/transformers/modeling_gpt2.py", line 593, in forward
>     inputs_embeds = self.wte(input_ids)
>   File "<conda_env>/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
>     result = self.forward(*input, **kwargs)
>   File "<conda_env>/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
>     self.norm_type, self.scale_grad_by_freq, self.sparse)
>   File "<conda_env>/lib/python3.6/site-packages/torch/nn/functional.py", line 1484, in embedding
>     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [x] my own task or dataset: (give details below)

## To reproduce

```
model_class, tokenizer_class = GPT2LMHeadModel, GPT2Tokenizer
model = model_class.from_pretrained("gpt2-large")
tokenizer = tokenizer_class.from_pretrained("gpt2-large")
special_tokens_dict = {'bos_token': '<BOS>', 'eos_token': '<EOS>', 'pad_token': '<PAD>'}
num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)
model.resize_token_embeddings(len(tokenizer))
input_text = ["a cat is sitting on the mat"]*100
train_dataset = tokenizer(input_text,add_special_tokens=True, truncation=True, max_length=64)
train_dataset = train_dataset["input_ids"]
eval_dataset = tokenizer(input_text,add_special_tokens=True, truncation=True, max_length=64)
eval_dataset = eval_dataset["input_ids"]
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer,mlm=False)
training_args = TrainingArguments(output_dir='./gpt_model/')
training_args.do_train = True
training_args.do_eval = True
training_args.per_device_train_batch_size = 32
trainer = Trainer(
           model=model,
            args=training_args,
            data_collator=data_collator,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            prediction_loss_only=True)

trainer.train(model_path=None) // The error occurs here
trainer.save_model()
```

## Expected behavior

Expect the training to continue without an error.

### PR DESCRIPTION
**Pull request by GeetDsa**
Fixes #7026

### CODE REVIEW

**Comment by LysandreJik** [comment]
Wouldn't it be better to do `torch.tensor(e, dtype=torch.long)` when creating the tensor, instead of casting the batch once the tensors are created?

**Comment by GeetDsa** [comment]
@LysandreJik , It gives a different error:

```
TypeError: new() received an invalid combination of arguments - got (list, dtype=torch.dtype), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: dtype
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)
```

**Comment by GeetDsa** [comment]
@LysandreJik, made the suggested changes. :+1:

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Review by sgugger — APPROVED** [review]

**Comment by sgugger** [comment]
Thanks for the fix!

**Pull request merged**
