### PR TITLE
Fixes to alternating SWA layers in Gemma2

### PR DESCRIPTION
**Pull request by turboderp**
# What does this PR do?

- Reverses the order of global and sliding attention layers in Gemma2. This brings it in line with [Google's implementation](https://github.com/google/gemma_pytorch/blob/1814f8d0a6ba93b875c46a64e6ad1873df448eef/gemma/config.py#L118) in which sliding attention is used on layers 0, 2, 4.., whereas currently the Transformers implementation uses sliding attn on layers 1, 3, 5...

- Changes `HybridCache.update` to read the `sliding_window` argument from `cache_kwargs` since it wasn't being parsed otherwise. The cache was created with alternating max seq lenghts of 4k and 8k, but all layers were being updated as if they were 8k, causing out-of-bounds errors and CUDA exceptions.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR. @ArthurZucker

### CODE REVIEW

**Comment by LysandreJik** [comment]
Thanks for your PR @turboderp, we're taking a look with @ArthurZucker

**Comment by fizzAI** [comment]
Any updates on this? It's likely required to get the proper performance out of the Gemma 2 models

**Review by ArthurZucker — APPROVED** [review]
LGTM thanks for fixing!

**Review by ArthurZucker — COMMENTED** [review]
yep good catch thanks for adressing both!

**Comment by ArthurZucker** [comment]
The slow tests are gonna fail potentially cc @ydshieh if it's alright with you to update later on? I think a patch will include this!

**Comment by ArthurZucker** [comment]
Thanks @turboderp

**Pull request merged**
