### PR TITLE
Add type hints for Pegasus model (PyTorch)

### PR DESCRIPTION
**Pull request by Tegzes**
Adding type hints for forward methods in user-facing class for Pegasus model (PyTorch) as mentioned in #16059

@Rocketknight1

### CODE REVIEW

**Comment by Tegzes** [comment]
it seems like BART model was not updated yet, hence the inconsistency

**Comment by Rocketknight1** [comment]
@Tegzes Unfortunately this will have to wait for the BART PR to avoid breaking repository consistency, but I'll take a look at that point!

**Comment by Tegzes** [comment]
@Rocketknight1  I saw that BART model was updated, along with multiple models depending on it, including this one. Should I close the PR?

**Comment by Rocketknight1** [comment]
Hi @Tegzes, there might still be portions of `modeling_pegasus.py` that need type hints - if you could check that and either submit a Pegasus PR or close this one that would be great. And sorry for the confusion caused by the copying dependencies!

**Pull request closed without merging**
