### PR TITLE
TFLongformer: Add missing type hints and unpack inputs decorator

### PR DESCRIPTION
**Pull request by johnnygreco**
# What does this PR do?

1. Adds missing type hints to the TF Longformer model classes.
    
    - Issue: #16059
    - Note: I also added `Numpy array` as a possible argument type to parameters listed in `LONGFORMER_INPUTS_DOCSTRING`.
    
2. Unpacks TF Longformer model inputs using the `unpack_inputs` decorator. 
    
    - Issue:  #16051

### Tests / Checks
- `RUN_SLOW=1 py.test -vv tests/longformer/test_modeling_tf_longforme.py` ran without any failures.
- I ran `make fixup` before my final commit. 
    
_This PR is part of the Great Code Cleanup 2022!_

@gante @Rocketknight1

### CODE REVIEW

**Review by gante — APPROVED** [review]
LGTM 👍  Thank you for the contribution! I'll let @Rocketknight1 do a final check on the type hints, as he has been taking charge of those

**Comment by johnnygreco** [comment]
Lol just realized I accidentally committed my changes using my work email address 🤦‍♂️

**Review by Rocketknight1 — APPROVED** [review]
Type hints look good to me!

**Comment by Rocketknight1** [comment]
One thing I note in the docstring changes is that you wrote `Numpy array` rather than `np.ndarray`, which might be causing our doc builder some confusion! Can you try changing that and seeing if we get a green light on the doc building tests afterwards?

**Comment by Rocketknight1** [comment]
...I take it back, the doc builder is fine. Can we make that change anyway, though?

**Comment by johnnygreco** [comment]
Done!

**Comment by Rocketknight1** [comment]
LGTM!

**Pull request merged**
