### PR TITLE
Use new parametrization based weight norm if available

### PR DESCRIPTION
**Pull request by ezyang**
# What does this PR do?

In https://github.com/pytorch/pytorch/pull/103001 I introduce a new
parametrization based version of `weight_norm`.  One big benefit of
the new API is that the resulting model is deepcopy'able; today, you can't
deepcopy Wav2Vec2 models.

Since the new API isn't even in PyTorch main yet, I'd like to feature
gate it here, so that it gets used whenever PyTorch is recent enough to
support it.  It would be a big help for me if you could take this change
earlier rather than later; otherwise I will have to patch transformers
in our own CI to get our benchmark harness working on Wav2Vec2.

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

cc @sanchit-gandhi

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM as it's properly gated. @sanchit-gandhi can you have a second look?
You'll just need to run `make style` and `make fix-copies` on your branch to make the CI happy.

**Comment by ezyang** [comment]
PyTorch side PR has landed!

**Review by sanchit-gandhi — APPROVED** [review]
LGTM too - thanks for the PR @ezyang! Here's the PR in the PyTorch repo for reference: https://github.com/pytorch/pytorch/pull/103001

**Comment by ydshieh** [comment]
@ezyang 

With nightly pytorch, we get 

> AttributeError: encoder.pos_conv_embed.conv.weight_v not found in PyTorch model

when trying to load a pytorch model into a TF model.

The TF model is looking `encoder.pos_conv_embed.conv.weight_v` but we now have `encoder.pos_conv_embed.conv.parametrizations.weight.original0`. (This is from our `(TF)Wav2Vec2Model` model class).

**Question**: In your PR https://github.com/pytorch/pytorch/pull/103001, is this part

`def _weight_norm_compat_hook()`

that deals with the backward compatibility? If so, we will copy it :-)

**Comment by ezyang** [comment]
Yep. The change here is not FC so the ingester needs updating.

**Pull request merged**
