### PR TITLE
Enable Gradient Checkpointing in Deformable DETR

### PR DESCRIPTION
**Pull request by FoamoftheSea**
# What does this PR do?

Gradient Checkpointing is not currently supported by Deformable DETR, but with slight modifications I was able to get it working in both the encoder and decoder stages, which both independently led to noticeable reductions in VRAM usage during training. This makes a default Deformable DETR configuration trainable on a 4GB GPU.

@amyeroberts

### CODE REVIEW

**Comment by FoamoftheSea** [comment]
Note that fix-copies made changes to DETA model because it has the "# copied from" comments over methods taken from Deformable DETR. If we don't want to change that model, alternatively we could remove those comments and revert the changes.

**Comment by amyeroberts** [comment]
Hi @FoamoftheSea, thanks for working on this!

There's another open PR which addresses enabling gradient checkpointing for DETA -- #28615. What I'd suggest is removing the relevant `# Copied from` headers in DETA and the changes in its modeling file. 

This way we can include both of your respective contributions without clashes.

**Comment by FoamoftheSea** [comment]
@amyeroberts All done!

**Review by amyeroberts — APPROVED** [review]
Great - thanks for contributing this!

**Comment by FoamoftheSea** [comment]
No problem! 😀

**Pull request merged**
