### PR TITLE
Add Italian translation of converting_tensorflow_models.mdx

### PR DESCRIPTION
**Pull request by Xpiri**
# What does this PR do?

Italian translation of converting_tensorflow_models
See issue: https://github.com/huggingface/transformers/issues/17459

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? 
https://github.com/huggingface/transformers/issues/17459

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@mfumanelli

### CODE REVIEW

**Comment by nickprock** [comment]
Hi @Xpiri you started a new line many times, could you check?

e.g. A partire dalla versione 2.3.0 lo script di conversione è parte di transformers CLI (**transformers-cli**), disponibile in ogni installazione 
di transformers >=2.3.0 --> A partire dalla versione 2.3.0 lo script di conversione è parte di transformers CLI (**transformers-cli**), disponibile in ogni installazione di transformers >=2.3.0

And at line 1 È disponibile un'interfaccia per i comandi di linea --> È disponibile un'interfaccia a linea di comando

Thanks

**Comment by Xpiri** [comment]
Hi @nickprock, yes, in the raw file I started a new line many times, this is something that was also done in some other docs that I found, and I believe it makes it easier to edit the documentation (such as [here](https://github.com/huggingface/transformers/blob/b9a768b3ffa80c4c19d024f9f42d5917e7d8109e/docs/source/en/custom_models.mdx))  

Line 1 was edited, thanks!

**Comment by omarespejel** [comment]
Thanks @Xpiri and @nickprock! 🇮🇹

This LGTM @sgugger.

**Review by sgugger — APPROVED** [review]
Thanks a lot for adding this file! Just left one small comment.

**Pull request merged**
