### PR TITLE
Fix code example to load bigcode starcoder2 7b

### PR DESCRIPTION
**Pull request by JuanFKurucz**
# What does this PR do?

Fixes the issue to load the example code, the model `bigcode/starcoder2-7b_16k` does not exist anymore, it has been renamed to `bigcode/starcoder2-7b` https://huggingface.co/bigcode/starcoder2-7b

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

Documentation: @stevhliu

### CODE REVIEW

**Review by stevhliu — COMMENTED** [review]
Thanks again!

Would you mind also changing the docstring in [Starcoder2Config](https://huggingface.co/docs/transformers/model_doc/starcoder2#transformers.Starcoder2Config) and the [example](https://huggingface.co/docs/transformers/model_doc/starcoder2#transformers.Starcoder2ForCausalLM) in Starcoder2ForCausalLM to the correct checkpoint?

Finally, running `make fix-copies` should fix the failing checks.

**Comment by JuanFKurucz** [comment]
> Thanks again!
> 
> Would you mind also changing the docstring in [Starcoder2Config](https://huggingface.co/docs/transformers/model_doc/starcoder2#transformers.Starcoder2Config) and the [example](https://huggingface.co/docs/transformers/model_doc/starcoder2#transformers.Starcoder2ForCausalLM) in Starcoder2ForCausalLM to the correct checkpoint?
> 
> Finally, running `make fix-copies` should fix the failing checks.

Sure! Will add the change for the Starcode2Config that i missed out, the other example is coming out from the file I already fixed 👍

**Comment by stevhliu** [comment]
@amyeroberts is it ok if the slow CI tests are skipped?

**Comment by JuanFKurucz** [comment]
> @amyeroberts is it ok if the slow CI tests are skipped?

Actually seems like the llama fix code issue was fixed elsewhere, rebasing made that thing obsolete. I just updated the PR to check that everything works

**Comment by stevhliu** [comment]
Would you mind pushing an empty commit to trigger a new pipeline run? I'm afraid I might have caused the `fetch_tests` test to fail because I tried to re-run jobs from the UI too many times 😅

**Comment by JuanFKurucz** [comment]
> Would you mind pushing an empty commit to trigger a new pipeline run? I'm afraid I might have caused the `fetch_tests` test to fail because I tried to re-run jobs from the UI too many times 😅

Sure will do

**Review by stevhliu — APPROVED** [review]
Thanks!

**Pull request merged**
