### PR TITLE
[Docs] Spanish translation of task_summary.md

### PR DESCRIPTION
**Pull request by aaronjimv**
# What does this PR do?

Add the Spanish version of task_summary.md to transformers/docs/source/es

Fixes #15947 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@stevhliu

### CODE REVIEW

**Comment by aaronjimv** [comment]
Hello. This is a long doc page, so I am open to any feedback. Thanks.

**Comment by ArthurZucker** [comment]
Thanks for the PR. Let's try not to ping as many people for this please!

**Review by stevhliu — APPROVED** [review]
The structure/format of the docs LGTM! I can't review the content itself since I'm not a native Spanish speaker. Do you know anyone in the ML community who would be interested in contributing and reviewing your work?

**Comment by aaronjimv** [comment]
> The structure/format of the docs LGTM! I can't review the content itself since I'm not a native Spanish speaker. Do you know anyone in the ML community who would be interested in contributing and reviewing your work?

Hi @stevhliu, thanks!
@osanseviero has reviewed my work before.

**Comment by stevhliu** [comment]
For sure, but it’ll probably be faster if there are other community members who can help review your translation since 
@osanseviero is pretty busy himself!

Let me see if I can organize something with @mariagrandury and @mrm8488, founders of [SomosNLP](https://somosnlp.org/) (an awesome NLP community for Spanish speakers) to help review these translations 🙂

**Comment by aaronjimv** [comment]
> For sure, but it’ll probably be faster if there are other community members who can help review your translation since @osanseviero is pretty busy himself!
> 
> Let me see if I can organize something with @mariagrandury and @mrm8488, founders of [SomosNLP](https://somosnlp.org/) (an awesome NLP community for Spanish speakers) to help review these translations 🙂

Hi @stevhliu thanks for your support, I really appreciate it. 
I am attentive to any feedback by SomosNLP 🤗.

**Comment by aaronjimv** [comment]
Hi @stevhliu.
I would like to ask, is there any update on this PR? 
I appreciate your help, thanks.

**Comment by stevhliu** [comment]
cc @gisturiz, would you be interested in helping review this translation? 🙂

**Comment by tadeodonegana** [comment]
Hi! I saw a message from @osanseviero in the SomosNLP community asking for help with the review of a translation. 

I would be happy to review it!

**Review by tadeodonegana — APPROVED** [review]
LGTM. The translation accurately represents the content of the original English text.

**Comment by aaronjimv** [comment]
Thanks for the help @tadeodonegana 😊

@stevhliu let me know is it anything's else, thanks🤗.

**Review by stevhliu — APPROVED** [review]
LGTM, thanks so much y'all! 🚀

**Review by KidiIT — COMMENTED** [review]
All reviewed and approved🫶❤️

**Review by KidiIT — COMMENTED** [review]
All reviewed and approved🫶❤️

**Pull request merged**
