### PR TITLE
Fix command of doc tests for local testing

### PR DESCRIPTION
**Pull request by oneraghavan**
# What does this PR do?

In the utils/prepare_for_doc_test.py file, the command to test the doc test locally had typo, this fixes it

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ydshieh 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hey! You should update line 39 in a similar fashion :)

**Comment by oneraghavan** [comment]
> Hey! You should update line 39 in a similar fashion :)

Yes, realised bit later, Done

**Review by ydshieh — APPROVED** [review]
Thanks for the fix!

**Comment by oneraghavan** [comment]
@ydshieh Can we close this ? 
@LysandreJik  Please point to a next good bug to pick up.

**Review by LysandreJik — APPROVED** [review]

**Comment by LysandreJik** [comment]
@oneraghavan, thanks for wanting to contribute! There are a lot of issues available [here](https://github.com/huggingface/transformers/issues). Feel free to take a look and find one you'd like to try your hand at!

**Pull request merged**
