### PR TITLE
Enable PyTorch 1.13

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR enables PyTorch 1.13 for Transformers so we can start adding functionality like safer loading with `torch.load`. Since there are no wheels for torch scatter, this comes at the price of uninstalling `torch-scatter`. However the PR to move away from this dep and use the PyTorch core ops seems well under way, so skipping the TAPAS tests for now until the PR is merged does not seem like a heavy price to pay (cc @NielsRogge for information).

A couple of tests are still failing, which are all torch FX tests (cc @michaelbenayoun, see failing job [here](https://app.circleci.com/pipelines/github/huggingface/transformers/51241/workflows/4a2c365b-8721-4c2c-adac-54f0fd7cf9c8/jobs/613048)). I'm skipping them and we can fix them next week in a followup PR.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
LGTM

**Comment by ydshieh** [comment]
cc @sgugger , there is a PR

https://github.com/huggingface/transformers/pull/20149

but we forgot to ping you.

**Review by ydshieh — APPROVED** [review]
Finally PT 1.13, thanks @sgugger !

**Comment by Bearnardd** [comment]
Hi @sgugger :) - One question, you have removed `torch-scatter` dependency but at the same time you have added decorator `require_scatter` for `test_pt_tf_model_equivalence` test. Is that correct or am I just missing something?

**Comment by sgugger** [comment]
The scatter dependency is only removed from the CPU runners on circleCI, it's not removed from the library byt his PR, that's your job ;-) . When testing in our other setups that include the `scatter` dependency, the tests will be run (until your PR is merged and the dep is removed entirely).

**Pull request merged**
