### PR TITLE
Include image processor in add-new-model-like

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

* Adds logic to `add-new-model-like` CLI to include image processors
* Updates `tests/utils/add_new_model_like.py` so tests run (was outdated) 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing the tests and adding support for this!

**Review by ydshieh — APPROVED** [review]
Thank you @amyeroberts for working on this.

Just wondering, is the CI `test_add_new_model_like.py` currently broken? I can't see it from other PRs. Otherwise, are the changes necessary for your PR to pass this CI?

**Comment by sgugger** [comment]
@ydshieh The test requires all three frameworks (PyTorch, TensorFlow and Flax) so it is never run in the CI.

**Comment by ydshieh** [comment]
OK, I completely misunderstand `Add model like runner / Add new model like template tests (pull_request)`.
Ignore my previous comment 🙏 .

**Pull request merged**
