### PR TITLE
[model cards] ported allenai Deep Encoder, Shallow Decoder models

### LINKED ISSUE #7049: Convert 12-1 and 6-1 en-de models from AllenNLP
https://github.com/jungokasai/deep-shallow#download-trained-deep-shallow-models

+ These should be FSMT models, so can be part of #6940 or done after. 
+ They should be uploaded to the AllenNLP namespace. If stas takes this, they can start in stas/ and I will move them.
+ model card(s) should link to the original repo and paper.
+ I hope same en-de tokenizer already ported.
+ Would be interesting to compare BLEU to the initial models in that PR. There is no ensemble so we should be able to reported scores pretty well.
+ **Ideally** this requires 0 lines of checked in python code, besides maybe an integration test.

Desired Signature:
```python
model = FSMT.from_pretrained('allen_nlp/en-de-12-1')
```

Weights can be downloaded with gdown https://pypi.org/project/gdown/

```bash
pip install gdown
gdown https://drive.google.com/uc?id=1x_G2cjvM1nW5hjAB8-vWxRqtQTlmIaQU
```

@stas00 if you are blocked in the late stages of #6940 and have extra cycles, you could give this a whirl. We could also wait for that to be finalized and then either of us can take this.

### PR DESCRIPTION
**Pull request by stas00**
Once @LysandreJik merges https://github.com/huggingface/transformers/pull/6940, please merge these cards 

These are models ported from https://github.com/jungokasai/deep-shallow/

The models are already on s3 under `allenai` - thank you for moving those from my username, @sshleifer.

And added 2 more models from the same author.

Fixes #7049

### CODE REVIEW

**Comment by stas00** [comment]
I wasn't sure about the format for multiple languages in the head of the card, I added:
```
language: en, de
```
Is this correct?

I couldn't find an example of the same situation. Perhaps this can be documented?

**Comment by sshleifer** [comment]
I think you want like this

https://s3.amazonaws.com/models.huggingface.co/bert/Helsinki-NLP/opus-mt-en-roa/README.md

**Comment by stas00** [comment]
> I think you want like this

Do you mean:

```
language: - en - de
```
?

**Review by LysandreJik — APPROVED** [review]
Great, thanks!

**Pull request merged**
