### PR TITLE
Add setters by type of args to TrainingArguments

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR introduces setters that group some of the `TrainingArguments` by type, to make this class easier to use. This was suggested in #20831 

If the idea is of interest, I'll create more of those to cover all training arguments.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
I like the API! Let's see what others think about it on the linked issue, but I find the separation of arguments logical and simpler to parse.

Thanks for working on it!

**Comment by sgugger** [comment]
@MKhalusova this is a way to split the documentation of training arguments (currently 96 :grimacing: ) by splitting them in groups, could you have a quick look?

**Comment by MKhalusova** [comment]
I really like the idea of splitting 96 arguments into reasonable chunks. Looking at the examples, I am not sure how it would look when you use more than one group. 
Is it going to look something like this? 

```
args = TrainingArguments("working_dir")
args = args.set_training(learning_rate=1e-4, batch_size=32)
args = args.set_logging(strategy="steps", steps=100)
args = args.set_evaluate(strategy="steps", steps=100)
```

**Comment by sgugger** [comment]
Yup, or chained directly if that's more your style:
```py
args = (
    TrainingArguments("working_dir")
    .set_training(learning_rate=1e-4, batch_size=32)
    .set_logging(strategy="steps", steps=100)
    .set_evaluate(strategy="steps", steps=100)
)
```

**Review by MKhalusova — APPROVED** [review]

**Comment by MKhalusova** [comment]
I think this should make the docs much more readable and might make the code more readable as well.

**Pull request merged**
