### PR TITLE
feat(tokeniser): add lazy token conversion to ids

### PR DESCRIPTION
**Pull request by winstxnhdw**
## Summary

Add fast tokenisation method to lazily convert tokens to ids. This doesn't introduce any breaking changes.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hello! Could you explain the motivations behind this? 🤗

**Comment by winstxnhdw** [comment]
I have my own decode method that can lazily evaluate the tokens so that I can have an end-to-end lazy pipeline from my model all the way to client.

**Comment by itazap** [comment]
@winstxnhdw are you experiencing memory limitations with the existing`convert_tokens_to_ids`?

**Comment by winstxnhdw** [comment]
I am running this in a really light VPS with little memory and this function is forcing my program to accumulate all the tokens into memory.

**Review by itazap — APPROVED** [review]
LGTM 🤗 but will let @ArthurZucker do the final decision on adding this as it is a new (mini) feature!

**Review by ArthurZucker — COMMENTED** [review]
Hey! In general for feature requests, we usually wait until ~10 people from the community ask for it, as I think it should be fairly simple for you to overwrite that 🤗

**Comment by winstxnhdw** [comment]
Sure, if not for the feature, could you at least get rid of this redundant if-condition.

https://github.com/huggingface/transformers/pull/33644/files#diff-a8b32d72cf9a75d81e800354cf32933ddcf7c8c3e3d3d12bb7450fee98bb9595L352-L353

**Comment by ArthurZucker** [comment]
This would fail `[self._convert_token_to_id_with_added_voc(token) for token in tokens]` for k in None

**Comment by winstxnhdw** [comment]
> This would fail `[self._convert_token_to_id_with_added_voc(token) for token in tokens]` for k in None

It would fail the type checker first.

**Comment by ArthurZucker** [comment]
It will fail type checking but does not prevent anyone from calling that function!

**Comment by winstxnhdw** [comment]
If the user passes in a variable of the wrong type, that’s a user error and not the library’s responsibility. What’s the point of type hints if you are going to check for `None` unnecessarily? Why not just do this check for every single parameter of all your publicly exposed functions/methods since the user could potentially pass in `None`?

**Comment by ArthurZucker** [comment]
I agree with you! 🤗 Feel free to just remove this check then! 🤗

**Comment by winstxnhdw** [comment]
I have opened a new PR to remove this check at #34030. I will be closing this PR.

**Pull request closed without merging**
