### PR TITLE
remove codecov PR comments

### LINKED ISSUE #6317: codecov invalid reports due to inconsistent code coverage outputs (non-idempotent test-suite)
Currently PRs get a codecov report

1. Observing various commits - especially pure doc commits - It's either not working right or it needs to be configured.

e.g., this PR has 0.00% change to the code:
https://github.com/huggingface/transformers/pull/6315/files
yet, codecov found  -0.51%  decrease in coverage - this makes no sense. (edit: it updates itself with other commits to master, now it shows -0.31%)

2. Does it have to send a notification and not just comment on the PR?

It appears that it can be finetuned, and notifications sent only if a desired threshold is passed: https://docs.codecov.io/docs/notifications#standard-notification-fields - so that it actually flags an issue when there is one.
Here is a ready conf file from a random project: https://github.com/zulip/zulip/blob/master/.codecov.yml
except perhaps adjusting threshold to 1%? (edited) and not sure whether we want it to comment by default.

### PR DESCRIPTION
**Pull request by sshleifer**
#### Problem
+ @stas00 has tried very hard to get codecov working to no avail in https://github.com/huggingface/transformers/issues/6317
+ Files that are not affected by a PR show changes in coverage.
+ Codecoverage information is rarely/never useful
+ lots of distracting spam emails
+ lots of vertical space that could otherwise be used for reading discussion history.

#### Proposed solution:
The idea of codecov -- to warn people before they introduce untested code -- is good, but the current implementation is worse than nothing, and after significant effort (mostly from @stas00) I think it is time to give up. If we see another tool we like, or manage to reconfigure this one to work well, that's great, but I think that should happen without broken codecov on master.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
I agree that the codecov reports are unreliable, especially w.r.t reports on pull requests. However, it's useful to go check https://codecov.io/gh/huggingface/transformers/tree/master/src/transformers to get an idea of the coverage on each file and on the repo as a whole, even if unreliable.

Is there another tool we could leverage to give us more reliable information on our code coverage?

**Comment by sshleifer** [comment]
The page is nice but the data seems wrong -- 
https://codecov.io/gh/huggingface/transformers/src/master/src/transformers/modeling_layoutlm.py
says that `__init__` is not covered, but I checked and it is.. in `test_modeling_layoutlm.py`.

I can also just disable PR comments if that works better for you.

**Comment by stas00** [comment]
> Is there another tool we could leverage to give us more reliable information on our code coverage?

The tool is not the problem, the problem lies in our test suite being not idempotent. codecov only compares the old coverage to new coverage. It can't give correct coverage if the data it works with is invalid. Garbage in garbage out.

If you want an approximate coverage, you can just add  `cov: pytest --cov` in Makefile. It has a bunch of formats if you want the report in a particular format. It should be within 98% of correctness based on the current state of the test suite.

**Comment by LysandreJik** [comment]
I understand the issue. Could we simply disable the PR comments for now @sshleifer, as that's the only pain point?

**Comment by sshleifer** [comment]
Done. Will merge once checks pass!

**Pull request merged**
