### PR TITLE
[WIP] Add FLMR model

### PR DESCRIPTION
**Pull request by LinWeizheDragon**
# What does this PR do?

This PR aims to add a new model, Fine-grained Late-interaction Multi-modal Retriever (FLMR). The model was proposed in [here](https://openreview.net/forum?id=IWWWulAX7g) and [here](https://arxiv.org/abs/2402.08327). This PR contains the following content:
- Model class for both FLMR and PreFLMR.
- Example scripts to run indexing and inference with FLMR and PreFLMR.

The original code base of this work is at [here](https://github.com/linweizhedragon/retrieval-augmented-visual-question-answering). The pre-trained checkpoints are [here](https://huggingface.co/models?search=PreFLMR).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@ArthurZucker
@younesbelkada
@amyeroberts

### CODE REVIEW

**Comment by LinWeizheDragon** [comment]
@ArthurZucker
@younesbelkada
@amyeroberts
Can anyone help me to finish this PR or assign someone knowledgeable? The whole process is a little complicated and I have no idea what to do next. Thanks!

**Comment by ArthurZucker** [comment]
Hello @LinWeizheDragon, could you update the readme to have links to the pretrained checkpoints, the original codebase etc? 
I would recommend you to first start with a [code on the hub ](https://huggingface.co/docs/transformers/en/model_sharing)+ an issue on `transformers` to add support for this model. If it picks up the interest of the community 😉

**Comment by LinWeizheDragon** [comment]
> Hello @LinWeizheDragon, could you update the readme to have links to the pretrained checkpoints, the original codebase etc? I would recommend you to first start with a [code on the hub ](https://huggingface.co/docs/transformers/en/model_sharing)+ an issue on `transformers` to add support for this model. If it picks up the interest of the community 😉

Thanks for your reply. I have added the requested info to the description of this PR.
 We are the authors of this model. We plan to release the pre-trained models here directly to provide easy access to multi-modal late-interaction models. I followed the docs [here](https://huggingface.co/docs/transformers/add_new_model#how-to-add-a-model-to--transformers) to finish a runnable version. Could you please let me know what to do next?

**Comment by amyeroberts** [comment]
Hi @LinWeizheDragon, thanks for all the work opening this PR! 

As Arthur mentioned, we suggest adding the model directly to the hub. This is the recommended way to add models and we try to have as much support as possible for enabling this. This way, the model will be available to use and findable on the hub immediately. Adding a model into the transformers repo introduces maintenance costs. As such, the bar for adding models is high and the review process can take a long time.

**Comment by LinWeizheDragon** [comment]
> Hi @LinWeizheDragon, thanks for all the work opening this PR!
> 
> As Arthur mentioned, we suggest adding the model directly to the hub. This is the recommended way to add models and we try to have as much support as possible for enabling this. This way, the model will be available to use and findable on the hub immediately. Adding a model into the transformers repo introduces maintenance costs. As such, the bar for adding models is high and the review process can take a long time.

@amyeroberts Thanks for your reply. Given that the model weights are already on the Hub, what is the recommended way of sharing the model classes and definitions with users? Is there a way to allow users to do "AutoModel.from_pretrained" easily?

**Comment by amyeroberts** [comment]
@LinWeizheDragon Yes! :D Here's a guide on custom models and making them available on the hub: https://huggingface.co/docs/transformers/custom_models

If you want to use `AutoModel.from_pretrained`, you'll need to make sure to [register your model](https://huggingface.co/docs/transformers/custom_models#registering-a-model-with-custom-code-to-the-auto-classes). Here's an example of modeling code on the hub: https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/modeling_baichuan.py

**Pull request closed without merging**
