### PR TITLE
Adding hiera

### PR DESCRIPTION
**Pull request by EduardoPach**
# What does this PR do?

Adds Hiera model from Meta as suggested in https://github.com/huggingface/transformers/issues/28993

GitHub Repo: https://github.com/facebookresearch/hiera/ 
arXiv: https://arxiv.org/abs/2306.00989

Model License recently changed to `Apache`

As the work in https://github.com/huggingface/transformers/pull/29339 is on hold and had a lot of things to change to meet the library standards I've opened this new PR

c.c. @amyeroberts

### CODE REVIEW

**Comment by amyeroberts** [comment]
Thanks for opening this @EduardoPach! 

As there's an already open PR which the contributor gave us warning would be pending for a few weeks because of their exams and we acknowledged, the best thing and polite this to do it ping the contributor on their PR to ask if and when it's going to be picked back up. If they aren't able to work on it and get it to a reviewable state in the next e.g. 2 weeks, then I'd say it's free to work on (letting them know on the PR, of course).

**Comment by EduardoPach** [comment]
> Thanks for opening this @EduardoPach! 
> 
> 
> 
> As there's an already open PR which the contributor gave us warning would be pending for a few weeks because of their exams and we acknowledged, the best thing and polite this to do it ping the contributor on their PR to ask if and when it's going to be picked back up. If they aren't able to work on it and get it to a reviewable state in the next e.g. 2 weeks, then I'd say it's free to work on (letting them know on the PR, of course). 

Thanks for the heads up @amyeroberts! Didn't mean to be unpolite I just have a particular interest in the model and thought I could contribute, but will have that in mind for future contributions. 

Regarding the other PR that is already open I've messaged the author to check if he was interested in merging our works so he could keep working on it by himself or together. If you have any comments feel free to add.

**Comment by EduardoPach** [comment]
@amyeroberts tests are green

**Comment by EduardoPach** [comment]
c.c. @NielsRogge

**Comment by EduardoPach** [comment]
Closing this one as this is being worked on https://github.com/huggingface/transformers/pull/30356

**Pull request closed without merging**
