### PR TITLE
fix the mlm longformer example by changing [MASK] to <mask>

### LINKED ISSUE #11488: TFLongformerForMaskedMLM example throws ValueError "shapes are incompatible"
An official example of the `TFLongFormerX` page does not work. 

## Environment info
- `transformers` version: 2.4.1
- Platform: ubuntu 20.04
- Python version: python3.8
- PyTorch version (GPU?): N/A
- Tensorflow version (GPU?): 2.4.1
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
@patrickvonplaten (Longformer)
@Rocketknight1 (tensorflow)
@sgugger (maintained examples )

## Information
Model I am using: Longformer

The problem arises when using:
* [x ] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

## To reproduce

1. `docker run -it --rm python:3.8 bash` (no gpus attached)
2. `python3 -m pip install pip --upgrade`
3. `python3 -m pip install transformers tensorflow`
4. `python3` -> launch interactive shell
5.  run following lines: 
```
from transformers import LongformerTokenizer, TFLongformerForMaskedLM
import tensorflow as tf
tokenizer = LongformerTokenizer.from_pretrained('allenai/longformer-base-4096')
model = TFLongformerForMaskedLM.from_pretrained('allenai/longformer-base-4096')
inputs = tokenizer("The capital of France is [MASK].", return_tensors="tf")
inputs["labels"] = tokenizer("The capital of France is Paris.", return_tensors="tf")["input_ids"]
outputs = model(inputs)
# loss = outputs.loss
# logits = outputs.logits
```
This throws following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1012, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/transformers/models/longformer/modeling_tf_longformer.py", line 2140, in call
    loss = None if inputs["labels"] is None else self.compute_loss(inputs["labels"], prediction_scores)
  File "/usr/local/lib/python3.8/site-packages/transformers/modeling_tf_utils.py", line 158, in compute_loss
    reduced_logits = tf.boolean_mask(tf.reshape(logits, (-1, shape_list(logits)[2])), active_loss)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1831, in boolean_mask_v2
    return boolean_mask(tensor, mask, name, axis)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1751, in boolean_mask
    shape_tensor[axis:axis + ndims_mask].assert_is_compatible_with(shape_mask)
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/tensor_shape.py", line 1134, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (11,) and (9,) are incompatible
```

### PR DESCRIPTION
**Pull request by fredo838**
This PR fixes an official Huggingface example in the Longformer model

## Before submitting
- [x ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

@Rocketknight1 this PR is to address https://github.com/huggingface/transformers/issues/11488#issuecomment-830065245

Is this what you meant?

### CODE REVIEW

**Comment by fredo838** [comment]
Is there any way to look at the "new" docs locally?

**Comment by LysandreJik** [comment]
Yes! You can run `make docs` at the root of your clone. You can also run `make html` in the `docs` folder :)

**Comment by LysandreJik** [comment]
You'll need to do `pip install .[docs]` beforehand to have all the appropriate dependencies.

**Comment by fredo838** [comment]
thanks! It's looking good: 
image

**Comment by Rocketknight1** [comment]
Great job, thanks for this! I made one minor change - I ran the `black` code formatter to make sure the code fits our style guidelines. You can do this yourself in future by running `pip install -U -e .[quality]` in the project root to install the code formatters, and then `make style` to reformat the code, but it's a very minor detail.

Once the tests check out I'll merge it. Thanks again for making my job as a maintainer easier!

**Comment by fredo838** [comment]
No problem, this is what open source is about :D

**Pull request merged**
