### PR TITLE
Create README.md (Model card for Norod78/hewiki-articles-distilGPT2py-il)

### PR DESCRIPTION
**Pull request by Norod**
Model card for Norod78/hewiki-articles-distilGPT2py-il
A tiny GPT2 model for generating Hebrew text

### CODE REVIEW

**Comment by julien-c** [comment]
Hi @Norod, this is our first model for Hebrew, that's awesome – thanks for sharing.

Do you think you'd be up for adding default example inputs to all models for Hebrew? If you are, just open a PR against [this file](https://github.com/huggingface/widgets-server/blob/master/DefaultWidget.ts).

**Comment by julien-c** [comment]
(also cc'ing @JetRunner)

**Comment by Norod** [comment]
Hello @julien-c 
Thank you for having such and awesome model and community. 
While it's the first GPT2 model in Hebrew, there are several ones which were contributed by "Helsinki-NLP" for translating to Hebrew and from Hebrew. For example: https://huggingface.co/Helsinki-NLP/opus-mt-he-de?text=%D7%A9%D7%9C%D7%95%D7%9D  
There is also one BERT model contributed by "TurkuNLP" [TurkuNLP/wikibert-base-he-cased](https://huggingface.co/TurkuNLP/wikibert-base-he-cased) that can generate masked predictions. 

Thank you for pointing out the 'default example inputs' file, I will have a look.

**Comment by julien-c** [comment]
@Norod Good point! We now have a clearer webpage that lists (mono-lingual) models by language: see e.g. this link for Hebrew https://huggingface.co/languages#he

**Pull request merged**
