### PR TITLE
Translate README.md to Simplified Chinese

### PR DESCRIPTION
**Pull request by JetRunner**
This is part of the Hugging Face document translation project. I appreciate it if anyone (from Hong Kong / Taiwan) could help verify the traditional Chinese version (which is still WIP).

### CODE REVIEW

**Comment by MichaelZhouwang** [comment]
The Chinese translations looks good to me!

**Comment by sIncerass** [comment]
LGTM.

**Comment by qqaatw** [comment]
@JetRunner I can help with the translation of Traditional Chinese. Would you like me submitting a PR or any kinds of assistance?

**Comment by JetRunner** [comment]
> @JetRunner I can help with the translation of Traditional Chinese. Would you like me submitting a PR or any kinds of assistance?

Sure! Please do so. I recommend you convert the simplified Chinese version to traditional Chinese with a software and then polish it (e.g., replace `软件` with `軟體`) - in this way we can keep the two versions consistent (which is desirable for future maintenance).

**Comment by qqaatw** [comment]
@JetRunner No problem, I'll work on this soon. Once the PR is opened, I'll ping you for reviewing.

**Pull request merged**
