### PR TITLE
change shape to support dynamic batch input in tf.function XLA generate for tf serving

### LINKED ISSUE #16823: (TF) model.generate to tf.function for tf serving
### Feature request

It would be nice if you wrapped the generate method of autorregressive models into a `tf.function`. That way we could export and serve it with all the Tensorflow production stack. 

Its kinda a revival of #5443.

It would enable us to do something like:
```python
from transformers import AutoTokenizer, TFAutoModelForCausalLM
import tensorflow as tf

model = TFAutoModelForCausalLM.from_pretrained("gpt2")
model.save(
    "some_place",
    signatures={
        "serving_default": model.generate.get_concrete_function(tf.TensorSpec([None, None], tf.int32))
    }
)
```

And then serve it on TF production stack.

### Motivation

It would be nice if you wrapped the generate method of autorregressive models into a `tf.function`. That way we could export and serve it with all the Tensorflow production stack. 

It is frustrating to have to write generate by hand or move to PyTorch to serve generative language models. 

### Your contribution

I could write a PR, thou it would be nice if HF could share what they have done when trying it, as @Rocketknight1 and @patrickvonplaten said in : https://github.com/huggingface/transformers/issues/5443#issuecomment-1020067525_ , so I would have somewhere to go from.

### LINKED ISSUE #18357: generate with tf.function (xla) not working for tf model export
### System Info

using the latest version with tf.function for generate still doesn't work for tensorflow model export which would be useful for serving.

### Who can help?

@gante @patrickvonplaten 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import tensorflow as tf
from transformers import TFAutoModelForSeq2SeqLM

class MyOwnModel(tf.Module):
    def __init__(self, model_path="t5-small"):
        super(MyOwnModel, self).__init__()
        self.model = TFAutoModelForSeq2SeqLM.from_pretrained(model_path)

    @tf.function(input_signature=(tf.TensorSpec((None, 32), tf.int32, name="input_ids"),
                                  tf.TensorSpec((None, 32), tf.int32, name="attention_mask")), jit_compile=True)
    def serving(self, input_ids, attention_mask):
        return self.model.generate(input_ids=input_ids, attention_mask=attention_mask, max_new_tokens=32)

model = MyOwnModel()
export_dir = "./"
tf.saved_model.save(
    model,
    export_dir,
    signatures={
        "serving_default":
            model.serving
    })
```

error:
```
File "../python3.8/site-packages/transformers/generation_tf_utils.py", line 1561, in _generate  *
        input_ids = self._prepare_decoder_input_ids_for_generation(
    File "../python3.8/site-packages/transformers/generation_tf_utils.py", line 1758, in _prepare_decoder_input_ids_for_generation  *
        return tf.ones((batch_size, 1), dtype=tf.int32) * decoder_start_token_id

    TypeError: Expected int32, but got None of type 'NoneType'.
```

### Expected behavior

generate can be exported in tf model for serving

### PR DESCRIPTION
**Pull request by nlpcat**
# What does this PR do?

support dynamic input for tf.function + generate (XLA). needed for batch tf serving

export:
```
import tensorflow as tf
from transformers import TFAutoModelForSeq2SeqLM

class MyOwnModel(tf.Module):
    def __init__(self, model_path="t5-small"):
        super(MyOwnModel, self).__init__()
        self.model = TFAutoModelForSeq2SeqLM.from_pretrained(model_path)

    @tf.function(input_signature=(tf.TensorSpec((None, 32), tf.int32, name="input_ids"),
                                  tf.TensorSpec((None, 32), tf.int32, name="attention_mask")), jit_compile=True)
    def serving(self, input_ids, attention_mask):
        outputs = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, max_new_tokens=32,
                                   return_dict_in_generate=True)
        return {"sequences": outputs["sequences"]}

model = MyOwnModel()
export_dir = "./"
tf.saved_model.save(
    model,
    export_dir,
    signatures={
        "serving_default":
            model.serving
    })
```
tf model run
```
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM
export_dir = "./"
model = tf.saved_model.load(export_dir)

tokenizer = AutoTokenizer.from_pretrained("t5-small")
tokenization_kwargs = {"pad_to_multiple_of": 32, "padding": True, "return_tensors": "tf"}

input_prompts = [
    f"translate English to {language}: I have four cats and three dogs."
    for language in ["German", "French", "Romanian"]
]

def generate_text(inputs):
    tokenized_inputs = tokenizer(inputs, **tokenization_kwargs)
    generated_texts = model.signatures["serving_default"](**tokenized_inputs)
    for text in generated_texts["sequences"]:
        print(tokenizer.decode(text, skip_special_tokens=True))
# The first prompt will be slow (compiling), the others will be very fast!
generate_text(input_prompts[:2])
generate_text(input_prompts[:3])
```
xla_run
```
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("t5-small")
model = TFAutoModelForSeq2SeqLM.from_pretrained("t5-small")

# Main changes with respect to the original generate workflow: `tf.function` and `pad_to_multiple_of`
xla_generate = tf.function(model.generate, jit_compile=True)
tokenization_kwargs = {"pad_to_multiple_of": 32, "padding": True, "return_tensors": "tf"}

# The first prompt will be slow (compiling), the others will be very fast!
input_prompts = [
    f"translate English to {language}: I have four cats and three dogs."
    for language in ["German", "French", "Romanian"]
]
tokenized_inputs = tokenizer(input_prompts, **tokenization_kwargs)
generated_texts = xla_generate(**tokenized_inputs, max_new_tokens=32)
for text in generated_texts:
    print(tokenizer.decode(text, skip_special_tokens=True))
```

this also works for beam search by changing exported code as 
```
def serving(self, input_ids, attention_mask):
        outputs = self.model.generate(input_ids=input_ids, attention_mask=attention_mask, max_new_tokens=32,
                                   return_dict_in_generate=True, num_beams=3, num_return_sequences=3)
        return {"sequences": outputs["sequences"]}
```

Fixes #18357
Fixes #16823

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @gante @patrickvonplaten

### CODE REVIEW

**Comment by nlpcat** [comment]
Cc @gante @patrickvonplaten

**Comment by gante** [comment]
Hi @nlpcat 👋 I see the change is needed because an unknown batch size is specified (hence the need for dynamic shapes). I'm going to double-check a few cases against this branch and, if all goes well, will propose a few changes -- mostly to avoid using `shape_list`, which we are trying to deprecate.

**Review by gante — APPROVED** [review]
Thank you for this contribution! (I've double-checked that it doesn't affect the performance of generate)

One bit is missing, if you're up to it -- a test to ensure we don't lose this feature. The best place would probably be `UtilsFunctionsTest` inside `test_modeling_tf_common.py`, and the test could be a copy of the example you shared in the PR description.

Let us know if you'd rather have us adding the test instead :)

**Review by sgugger — APPROVED** [review]
Yes, adding a test would be nice.
Thanks a lot for your PR!

**Comment by gante** [comment]
(edited the PR header to link more issues this PR fixes :) )

**Comment by nlpcat** [comment]
> Thank you for this contribution! (I've double-checked that it doesn't affect the performance of generate)
> 
> 
> 
> One bit is missing, if you're up to it -- a test to ensure we don't lose this feature. The best place would probably be `UtilsFunctionsTest` inside `test_modeling_tf_common.py`, and the test could be a copy of the example you shared in the PR description.
> 
> 
> 
> Let us know if you'd rather have us adding the test instead :)

How about me making another pr to add the test? Wdyt?

**Comment by nlpcat** [comment]
@gante @sgugger  i have added the test . https://github.com/huggingface/transformers/pull/18372/commits/596ecf4003ed8fdf46dda220062f1bba08bec689.
Can you help review and merge this PR if it looks good? Thanks.

**Comment by gante** [comment]
@nlpcat this is fantastic! Thank you so much for your contribution 🙏

**Comment by s4sarath** [comment]
The whole idea of Tensorflow in Huggingface is very complicated and a pain.
@nlpcat  - You better look into 

https://github.com/legacyai/tf-transformers/blob/main/docs/source/model_usage/text_generation_using_t5.ipynb

**Pull request merged**
