### PR TITLE
Update bros checkpoint

### PR DESCRIPTION
**Pull request by jinhopark8345**
# What does this PR do?

Update [Bros](https://arxiv.org/abs/2108.04539) checkpoint.

The `naver-clova-ocr/bros-base-uncased` checkpoint has `bbox_projection` layer in `BrosEmbeddings` class but this layer is moved to `BrosBboxEmbeddings` class. And users are expected to use `jinho8345/bros-base-uncased` checkpoint instead of `naver-clova-ocr/bros-base-uncased`.

* `naver-clova-ocr/bros-base-uncased` : original pretrained checkpoint from naver-clova-ocr
* `jinho8345/bros-base-uncased` :  weights renamed version from `naver-clova-ocr/bros-base-uncased` using [conversion script](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bros/convert_bros_to_pytorch.py)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. - https://github.com/huggingface/transformers/pull/23190#issuecomment-1725882060
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ydshieh

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thank you @jinhopark8345 🤗

**Comment by ArthurZucker** [comment]
Is there a reason why we did not go with creating new repos with `naver-clova-ocr/bros-base-uncased-hf` instead of a custom repo?

**Comment by jinhopark8345** [comment]
> Is there a reason why we did not go with creating new repos with `naver-clova-ocr/bros-base-uncased-hf` instead of a custom repo?

No reason at all. I also considered that it would be more reliable to use checkpoint that huggingface controls.

**Comment by ArthurZucker** [comment]
I'll ask for the models to be moved if that is okay with you?

**Comment by ydshieh** [comment]
I am not sure if @jinhopark8345 can move repo to `naver-clova-ocr`. Even for us, we will need `naver-clova-ocr` to approve I think.

Sorry merged this PR without waiting core maintainers' approval.

**Comment by jinhopark8345** [comment]
@ArthurZucker I can not move the repo to `naver-clova-ocr` as @ydshieh assumed. And I am sorry that I didn't mention about my concern earlier, @ydshieh.

**Comment by ArthurZucker** [comment]
I'll ask for the checkpoints to be move then 😉

**Pull request merged**
