### PR TITLE
Add support for PyTorch/XLA 2.1+ PJRT (Neuron SDK)

### PR DESCRIPTION
**Pull request by jeffhataws**
# What does this PR do?

In PyTorch/XLA 2.1+, `init_method="xla://"` is now needed in `dist.init_process_group` to properly initialize PJRT.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerzr and @pacman100

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
Let me get back to you today on this, but we might/should probably be handling this in Accelerate directly. XLA stuff in the TrainingArguments could have been overlooked in the integration. I'll check :)

**Comment by jeffhataws** [comment]
We don't need this anymore as we have overwritten init_process_group within torch-neuronx to have pjrt as default. You might need this for torch-xla for other platforms.

**Comment by muellerzr** [comment]
@jeffhataws are we okay to close this then? Or are you saying this needs to be merged.

**Comment by jeffhataws** [comment]
We can close this. Thanks!

**Pull request closed without merging**
