### PR TITLE
Add support for Ascend NPU

### PR DESCRIPTION
**Pull request by ji-huazhong**
# What does this PR do?

This PR enables users to leverage the Ascend NPU for training and inference of 🤗 Transformers models.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. #22600 
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger

### CODE REVIEW

**Comment by statelesshz** [comment]
For example, you can run the official question answering task using Ascend NPU with below command:

python examples/pytorch/question-answering/run_qa.py
       --model_name_or_path bert-base-uncased \
       --dataset_name squad \
       --do_train \
       --do_eval \
       --device_id 5 \   // The specific device to be used for single card training on Ascend NPUs.
       --per_device_train_batch_size 24 \
       --num_train_epochs 2 \
       --learning_rate 3e-5 \
       --max_seq_length 384 \
       --doc_stride 128 \
       --save_steps 5000 \
       --fp16_opt_level O2 \
       --half_precision_backend apex \
       --dataloader_drop_last \
       --overwrite_output_dir \
       --output_dir ./output \

**Comment by statelesshz** [comment]
The test case needs to be executed on the Ascend NPU, and the results are shown below:
image

**Review by sgugger — COMMENTED** [review]
Thanks for your PR. We can leave this branch as is for people who want to use NPUs but:
1. We do not have the ability to test them, so cannot commit to maintain this yet.
2. The Trainer will be rewritten to use Accelerate very soon, so the support should be added in Accelerate and then will come in the Trainer for free.

**Comment by 021214317** [comment]
@sgugger now if i want to use Ascend NPU and accelerate to complete distributed training.  how can i start and is there any examples for reference

**Comment by sgugger** [comment]
The PR hasn't been moved there to add support for NPUs, so for now it's not possible.

**Comment by 021214317** [comment]
@sgugger Currently, I can use transformers on npu based on this PR, but I find that accelerate cannot be used. What should I do if I want to use accelerate on npu? Is there any reference?

**Pull request closed without merging**
