### PR TITLE
Make OpenAIGPTTokenizer work with SpaCy 2.x and 3.x

### LINKED ISSUE #14449: OpenAIGPTTokenizer does not work with spacy 3.x installed
## Environment info

- `transformers` version: 4.11.3
- Platform: Darwin-19.6.0-x86_64-i386-64bit
- Python version: 3.6.8
- PyTorch version (GPU?): 1.9.1 (False)
- Tensorflow version (GPU?): 2.6.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help

@patrickvonplaten @LysandreJik since it is related to OpenAI GPT model.

## Information

It seems that OpenAIGPTTokenizer does not work with spacy>=3.0.0.

In `tokenization_openai.py`, there is logic that uses spacy tokenizer if spacy and ftfy are installed:

```
        try:
            import ftfy
            from spacy.lang.en import English

            _nlp = English()
            self.nlp = _nlp.Defaults.create_tokenizer(_nlp)
            self.fix_text = ftfy.fix_text
        except ImportError:
            logger.warning("ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.")
            self.nlp = BasicTokenizer(do_lower_case=True)
            self.fix_text = None
```

This block executes correctly for spacy versions 2.x. But for spacy versions 3.x, the API changed and the proper way to create the tokenizer is like so (taken from the docs at https://spacy.io/api/tokenizer):

```
from spacy.lang.en import English
nlp = English()
# Create a Tokenizer with the default settings for English
# including punctuation rules and exceptions
tokenizer = nlp.tokenizer
```

## To reproduce

1. `pip install transformers==4.11.3 ftfy==6.0.3 spacy==3.0.0`
2. Open a python shell and run the following:

```
from transformers import OpenAIGPTTokenizer

tokenizer = OpenAIGPTTokenizer.from_pretrained('openai-gpt')
```

3. Should break with a stack trace that looks like the following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cody/.pyenvs/test/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1750, in from_pretrained
    **kwargs,
  File "/Users/cody/.pyenvs/test/lib/python3.6/site-packages/transformers/tokenization_utils_base.py", line 1872, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/cody/.pyenvs/test/lib/python3.6/site-packages/transformers/models/openai/tokenization_openai.py", line 107, in __init__
    self.nlp = _nlp.Defaults.create_tokenizer(_nlp)
AttributeError: type object 'EnglishDefaults' has no attribute 'create_tokenizer'
```

## Expected behavior

The tokenizer should be able to work with spacy 3.x.

### PR DESCRIPTION
**Pull request by cody-moveworks**
SpaCy 3.x introduced an API change to creating the tokenizer that
breaks OpenAIGPTTokenizer. The old API for creating the tokenizer in
SpaCy 2.x no longer works under SpaCy 3.x, but the new API for creating
the tokenizer in SpaCy 3.x DOES work under SpaCy 2.x. Switching to the
new API should allow OpenAIGPTTokenizer to work under both SpaCy 2.x and
SpaCy 3.x versions.

Fixes https://github.com/huggingface/transformers/issues/14449

### CODE REVIEW

**Comment by cody-moveworks** [comment]
I'm not able to test the changes locally. When I run `pip install -e ".[dev]"`, I encounter a build error and the install fails. It doesn't look like pytest coverage is sufficient here either since SpaCy and ftfy are not required by transformers, and the code can execute correctly without them being installed.

**Comment by cody-moveworks** [comment]
@patrickvonplaten @LysandreJik Not sure why but I can't tag you as reviewers on GitHub, so tagging you in comments here.

**Review by patrickvonplaten — APPROVED** [review]
That looks good to me. @LysandreJik do you think it's worth adding a test the depends on a `spacys` install?

**Comment by LysandreJik** [comment]
Yes, why not! GPT-2 is among our most used models, so I think testing that the tokenization behaves correctly across all possibilities is important. Would you like to take a stab at it @cody-moveworks?

In order to do so, you could start by adding an `is_spacy_available` method in `file_utils.py`, analog to other methods such as `is_vision_available` here: https://github.com/huggingface/transformers/blob/2e9af294940083915ccb2740a7c8d5b154194f15/src/transformers/file_utils.py#L507-L508

Then it would require defining a `require_spacy` unittest decorator in `testing_utils.py`, such as the `require_vision` here: https://github.com/huggingface/transformers/blob/2e9af294940083915ccb2740a7c8d5b154194f15/src/transformers/testing_utils.py#L404-L412

Thirdly, you can add a test in the `tests/test_tokenization_gpt2.py` file with the `@require_spacy` decorator, which will only run when SpaCy is installed.

And finally, we can modify this CircleCI run: https://github.com/huggingface/transformers/blob/2e9af294940083915ccb2740a7c8d5b154194f15/.circleci/config.yml#L538-L565

So that it:
1. Installs SpaCy
2. Runs the tokenization GPT-2 test file!

**Comment by cody-moveworks** [comment]
@LysandreJik Thanks for the detailed walkthrough of the changes needed to add testing. I'll take a stab at it.

**Comment by cody-moveworks** [comment]
@LysandreJik I made the changes and all checks are passing. Can you take a look?

**Review by LysandreJik — APPROVED** [review]
That's very nice! This looks good to me, @cody-moveworks, tested it locally.

Thank you, merging!

**Pull request merged**
