### PR TITLE
[Wait to merge] [Bart] Rename lm_labels argument to masked_lm_labels

### PR DESCRIPTION
**Pull request by dougian**
While the docstring correctly lists masked_lm_labels, forward
was expecting lm_labels. Renaming to match BERT and the rest of
the MLM-based models

### CODE REVIEW

**Review by sshleifer — APPROVED** [review]
Lgtm!

**Comment by sshleifer** [comment]
Could you make sure the kwarg in `examples/summarization/bart/run_bart_sum.py` is correct? Thanks!

**Comment by dougian** [comment]
> Could you make sure the kwarg in `examples/summarization/bart/run_bart_sum.py` is correct? Thanks!

Sure, updated all occurrences on that file

**Comment by sshleifer** [comment]
@dougian : we are going to merge/adopt this after a few other PRs are merged in order to coordinate the signature with T5's signature. Thanks for your contribution!

**Review by LysandreJik — APPROVED** [review]
LGTM

**Comment by sshleifer** [comment]
Fixed on master by other PRs, closing. Thanks!

**Pull request closed without merging**
