### PR TITLE
fix bart compatibility with numpy tensors

### PR DESCRIPTION
**Pull request by kventinel**
# What does this PR do?

Changes only on `modeling_bart.py` file. Other changes just by copying mechanics.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks for your PR, but PyTorch models do not accept NumPy arrays as inputs, and your changes won't make any difference for that I believe.

**Comment by kventinel** [comment]
@sgugger, ping

**Comment by sgugger** [comment]
I think I have been pretty clear on why we don't want this change. PyTorch models do not support NumPy arrays and we are not interested in replacing all the `size()` by `shape`.

**Comment by kventinel** [comment]
> I think I have been pretty clear on why we don't want this change. PyTorch models do not support NumPy arrays and we are not interested in replacing all the `size()` by `shape`.

Yep, I understand it. This PR only about more clear errors on numpy tensors. Nothing else. So I think it's make little easier to debug.

**Comment by kventinel** [comment]
@sgugger, ping

**Pull request closed without merging**
