### PR TITLE
Fix utf-8 yaml load for marian conversion to pytorch in Windows

### PR DESCRIPTION
**Pull request by SystemPanic**
# What does this PR do?

Fix yaml load for yaml files with UTF-8 encoding in convert_marian_to_pytorch.py

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed.

@ArthurZucker

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Thanks, did you have an issue with the default ? 🤗

**Comment by SystemPanic** [comment]
Yes, you can reproduce it with following Marian yaml file (Github doesn't allow .yml upload, so **change the file from .txt to .yml after download**):

```
with open('opusTCv20210807.spm32k-spm32k.vocab.yml') as f:
    print(yaml.load(f, Loader=yaml.BaseLoader))
```

and with the simple pull applied:

```
with open('opusTCv20210807.spm32k-spm32k.vocab.yml', encoding='utf-8') as f:
    print(yaml.load(f, Loader=yaml.BaseLoader))
```

[opusTCv20210807.spm32k-spm32k.vocab.txt](https://github.com/huggingface/transformers/files/14026656/opusTCv20210807.spm32k-spm32k.vocab.txt)

**Comment by ArthurZucker** [comment]
But I am not sure I follow why you are changing the file type?

**Comment by SystemPanic** [comment]
@ArthurZucker 

I already said it, Github has not included the .yml extension in their supported file types for the "Attach files" button.

You can check if you want, try to attach a .yml file in a Github comment, you can't.

Just renaming to .txt it's the simpler way to attach it. I don't get the point of confusion with this...

**Comment by ArthurZucker** [comment]
Sorry I got confused! 😓 alright thanks for providing a file, I can't reproduce your issue as it works out of the box for me

**Comment by SystemPanic** [comment]
@ArthurZucker 

That's not possible. I forgot to mention that i'm using Windows 10.

transformers-cli env:

```
- `transformers` version: 4.37.1
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.10.11
- Huggingface_hub version: 0.19.4
- Safetensors version: 0.4.2
- Accelerate version: 0.22.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu118 (True)
- Tensorflow version (GPU?): 2.10.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
```

**Review by ArthurZucker — COMMENTED** [review]
Alright, LGTM let's update the PR's title to something that says this is to fix on windows.

**Review by ArthurZucker — APPROVED** [review]

**Comment by ArthurZucker** [comment]
Thanks you!

**Pull request merged**
