### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by Cyrilvallez**
https://github.com/huggingface/transformers/pull/34858 modified Llama, but Aria relying on Llama got merged in the meantime. This correctly reapplies modular to Aria (order of RotaryEmbedding got changed because now the Attention does not need it anymore, thus it got closer to the class actually needing it)

### CODE REVIEW

**Comment by ydshieh** [comment]
BTW, it's always a good idea to trigger a slow CI :-)

**Comment by Cyrilvallez** [comment]
Humm, it seems very tricky to always avoid race conditions, it would probably require some check at merge time 🤔 I thought about this becoming an issue as we scale modular, but it's probably already the case with the "copied from". Here's the scenario:
- last commit on https://github.com/huggingface/transformers/pull/34858 pass all CIs as it should
- In the meantime, https://github.com/huggingface/transformers/pull/34157 is merged, relying on actual library version of Llama (not the modified one in https://github.com/huggingface/transformers/pull/34858)
- https://github.com/huggingface/transformers/pull/34858 is approved and merged (without any new commits, thus no new CI check)
- As Llama was modified in https://github.com/huggingface/transformers/pull/34858, Aria version is not longer up-to-date

**Review by ArthurZucker — APPROVED** [review]
Thanks

**Comment by ydshieh** [comment]
@Cyrilvallez Thanks for explaining. Yes, this happens from time to time. There is `Update branch` button, but click it all the time is also frustrating. We will try to think of solutions.

**Pull request merged**
