### PR TITLE
Pin deepspeed properly

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

Pins deepspeed in the dep table to (hopefully) fix the test failures

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ydshieh @pacman100

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thank you a lot. Version control is a hard science!

**Review by pacman100 — COMMENTED** [review]
Instead of this, let's disable the failing tests with a Todo comment to enable once DeepSpeed fixes them. Let me know your thoughts.

**Comment by ydshieh** [comment]
I don't feel strong between these 2 choices. Disable them means we can't see any failure (if any) introduced by our code changes.
And I don't know if it's a (little) bit time consuming to to skip those 10 tests after all the work done by now.
But I will leave you two to make the final call.

**Comment by muellerzr** [comment]
Closing in favor of Sourab's fix :)

**Pull request closed without merging**
