### PR TITLE
Final fix of the accelerate installation issue

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Fixfixfix

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Ty! 🙏

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by ydshieh** [comment]
Still get `@4f100318f499cff48b62555ca7d96ad97d7cb9be`, I will check check!!!!!!

**Review by muellerzr — APPROVED** [review]
Double ✅ , included updated empty commit from accelerate main on rerun 🔥

**Pull request merged**
