### PR TITLE
fix galore layerwise with frozen params

### PR DESCRIPTION
**Pull request by peterjc123**
# What does this PR do?

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by peterjc123** [comment]
@younesbelkada

**Review by younesbelkada — APPROVED** [review]
Nice catch thanks !

**Comment by younesbelkada** [comment]
@peterjc123 can you run the styling checks? `make fixup`

**Comment by peterjc123** [comment]
@younesbelkada Done.

**Review by younesbelkada — COMMENTED** [review]
Thanks ! Hmmm many undesired files have been modified, can you try to `pip install -U ".[quality]"` to make sure you have the same `ruff` version as us and re-run `make fixup` again?

**Comment by peterjc123** [comment]
@younesbelkada Should be okay this time.

**Review by amyeroberts — APPROVED** [review]
Thanks for the quick fix!

**Pull request merged**
