### PR TITLE
Layoutlm tf

### PR DESCRIPTION
**Pull request by atahmasb**
# What does this PR do?

This PR adds TF version of LayoutLM for issue [(10312)](https://github.com/huggingface/transformers/issues/10312)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Comment by LysandreJik** [comment]
Oh, no! Did you have some issues with a rebase? Can we help in any way?

**Comment by atahmasb** [comment]
> Oh, no! Did you have some issues with a rebase? Can we help in any way?

I do! For some reason when I rebased I was not able to push my changes. It was rejected because my branch was diverged too much form the remote. Then my option was to pull all changes which results in many file changes that are not mine.

**Comment by LysandreJik** [comment]
Ah! Would you like me to try and retrieve your commits and push them on a new branch of your repository? I can take care of the rebasing as well.

**Comment by atahmasb** [comment]
> Ah! Would you like me to try and retrieve your commits and push them on a new branch of your repository? I can take care of the rebasing as well.

that would be great, ty.

**Comment by LysandreJik** [comment]
I'm getting permission denied on your fork, can you invite me to it so I can push the new branch? Thanks!

**Comment by atahmasb** [comment]
> I'm getting permission denied on your fork, can you invite me to it so I can push the new branch? Thanks!

done. Let me know if there was any access issues and Thanks again for helping me with this

**Comment by LysandreJik** [comment]
You can find the branch [here](https://github.com/atahmasb/transformers/tree/layout-lm-tf-2)! I've rebased it for you, and fixed the code quality issues. The `TFLayoutLMForSequenceClassification` class was in double so I removed one of them. Let me know if this shouldn't have been removed!

**Comment by atahmasb** [comment]
> You can find the branch [here](https://github.com/atahmasb/transformers/tree/layout-lm-tf-2)! I've rebased it for you, and fixed the code quality issues. The `TFLayoutLMForSequenceClassification` class was in double so I removed one of them. Let me know if this shouldn't have been removed!

Thanks! You're awesome!

**Pull request closed without merging**
