### PR TITLE
fix image-to-text batch incorrect output issue

### PR DESCRIPTION
**Pull request by sywangyi**
fix image to text multi-batch input , but output incorrect issue

- pipelines: @Narsil

### CODE REVIEW

**Comment by sywangyi** [comment]
@amyeroberts please help review

**Comment by amyeroberts** [comment]
Hi @sywangyi, thanks for opening a PR! 

To show what this PR addresses could you:
* Provide a code snippet to reproduce? 
* Copy-paste the output of the terminal to show it working, rather than take a screen shot? This is 1) more readable, 2) makes the relevant code searchable and 3) means others can copy the text to be able to test on their own setup

Have you tested with non-batched input to confirm it's equivalent?

**Comment by sywangyi** [comment]
`from transformers import pipeline
import torch
import requests
import PIL.Image
import time

image_url = "https://ankur3107.github.io/assets/images/image-captioning-example.png"
image = []
image.append(PIL.Image.open(requests.get(image_url, stream=True, timeout=3000).raw))
image.append(PIL.Image.open(requests.get(image_url, stream=True, timeout=3000).raw))

generator = pipeline(
   "image-to-text",
    model="Salesforce/blip-image-captioning-large",
    torch_dtype=torch.bfloat16,
    device="cuda",
)

result = generator(image, batch_size=2)
print(f"{result}")
`

**Comment by sywangyi** [comment]
I have tested with non-batched input and confirm it's equivalent.

**Comment by sywangyi** [comment]
Hi, @amyeroberts  with and wo batch_size=2, it goes to different running logic.
with batch_size=2, the running logic is like
preprocess - > forward (bs=2)->postprocess
wo batch_size = 2, the running logic is like
preprocess->forward(bs=1)->postprocess->preprocess->forward(bs=1)->postprocess

**Comment by amyeroberts** [comment]
@sywangyi Right. My understanding is that `batch_size` is to be used when passing in e.g. a dataset object to the pipeline. Is there a reason you passed it in here, rather than calling the pipeline directly? 

My concern is that this is going to change the behaviour for the cases when datasets are passed - it's not obvious from the change or PR description what is being fixed here. 

Could you add some tests to make sure the pipeline still have the intended behaviour for the following cases: 
* Passing in a list of two elements with `batch_size=2`
* Passing in a list of two elements
* Passing in a dataset wit `batch_size=2` c.f. [the docs](https://huggingface.co/docs/transformers/en/main_classes/pipelines#pipeline-batching) for an example to use

**Comment by sywangyi** [comment]
> from transformers import pipeline
> import torch
> import requests
> import PIL.Image
> import time
> 
> image_url = "https://ankur3107.github.io/assets/images/image-captioning-example.png"
> image = []
> image.append(PIL.Image.open(requests.get(image_url, stream=True, timeout=3000).raw))
> image.append(PIL.Image.open(requests.get(image_url, stream=True, timeout=3000).raw))
> 
> generator = pipeline(
>    "image-to-text",
>     model="Salesforce/blip-image-captioning-large",
>     torch_dtype=torch.bfloat16,
>     device="cuda",
> )
> 
> result = generator(image, batch_size=2)
> print(f"{result}")

Hi, @amyeroberts . I write the test for the third case you mentioned
'''
from transformers import pipeline
import torch
import requests
import PIL.Image
import time
from torch.utils.data import Dataset


image2_url = "https://ankur3107.github.io/assets/images/image-captioning-example.png"
image_url = "https://storage.googleapis.com/sfr-vision-language-research/BLIP/demo.jpg"
class MyDataset(Dataset):
    def __len__(self):
        return 10

    def __getitem__(self, i):
        if i % 2 == 0:
            return PIL.Image.open(requests.get(image_url, stream=True, timeout=3000).raw)
        else:
            return PIL.Image.open(requests.get(image2_url, stream=True, timeout=3000).raw)


dataset = MyDataset()


generator = pipeline(
   "image-to-text",
    model="Salesforce/blip-image-captioning-large",
    torch_dtype=torch.bfloat16,
    device="cuda",
)

result = generator(dataset, batch_size=2)
print(f"{list(result)}")
'''

without the PR. the behavior of the 3 cases you mentioned is

- Passing in a list of two elements with batch_size=2 (incorrect)
- Passing in a list of two elements (correct)
- Passing in a dataset wit batch_size=2 (incorrect)

with the PR.
- Passing in a list of two elements with batch_size=2 (correct)
- Passing in a list of two elements (correct)
- Passing in a dataset wit batch_size=2 (correct)

**Comment by amyeroberts** [comment]
@sywangyi Sorry, what I meant was add a test to our testing suite.

**Comment by sywangyi** [comment]
I add some test, is it enough? @amyeroberts

**Review by amyeroberts — COMMENTED** [review]
Thanks for adding this fix and tests! 

Just a small note on the tests. One addressed I think we'll be good to merge!

**Review by amyeroberts — APPROVED** [review]
Great - thanks a lot for working on this and adding tests!

**Pull request merged**
