### PR TITLE
Exclude torch.compile time from metrics computation

### PR DESCRIPTION
**Pull request by zxd1997066**
When using torch.compile in accelerator.prepare_model, compilation time is being included while computing statistics. And this  may result in incorrect performance metrics calculations. This PR measures time after the torch.compile called in accelerate to exclude the compilation time.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @muellerzr @SunMarc

**Review by SunMarc — COMMENTED** [review]
Thanks for the PR @zxd1997066 ! I think it would be better if we can do similar to what we did with  f"{metric_key_prefix}_jit_compilation_time".  
```
        if f"{metric_key_prefix}_jit_compilation_time" in output.metrics:
            start_time += output.metrics[f"{metric_key_prefix}_jit_compilation_time"]
```

**Comment by zxd1997066** [comment]
> Thanks for the PR @zxd1997066 ! I think it would be better if we can do similar to what we did with f"{metric_key_prefix}_jit_compilation_time".
> 
> ```
>         if f"{metric_key_prefix}_jit_compilation_time" in output.metrics:
>             start_time += output.metrics[f"{metric_key_prefix}_jit_compilation_time"]
> ```

Hi @SunMarc , thanks for the review, I will take a look at it.

**Review by SunMarc — APPROVED** [review]
This is a lot better @zxd1997066 , thanks for iterating ! Could you fix the quality issue by typing `make style` ?

**Comment by zxd1997066** [comment]
> This is a lot better @zxd1997066 , thanks for iterating ! Could you fix the quality issue by typing `make style` ?

Fixed the quality issue, thanks!

**Comment by zxd1997066** [comment]
Hi @SunMarc , could you please help merge this PR if all good? I do not have access. Thanks!

**Comment by SunMarc** [comment]
Hey @zxd1997066, I've pinged @amyeroberts for a final review !

**Review by LysandreJik — APPROVED** [review]
Thanks for your PR!

**Pull request merged**
