### PR TITLE
Error (also in original) model, scaling only q matrix not qk.T dot product (qk.T/sqrt(dim_per_head))

### PR DESCRIPTION
**Pull request by BenoitDalFerro**
As per Vaswani et al, 2017 p.4
Is torch.matmul(q, k.transpose(2, 3)) / math.sqrt(dim_per_head) not q / math.sqrt(dim_per_head) https://arxiv.org/pdf/1912.05372.pdf

Error was in original FlauBERT repo and effectively scales queries but not keys cf. https://github.com/getalp/Flaubert/pull/45/commits/6d176880ca3a1a8dfa2b76c97030bb51c5e917b8

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
cc @ArthurZucker and @younesbelkada 

Also note that the same change would need to be applied to XLM.

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for the fix! I am ok with this PR in the principle that the result should be mathematically the same
Can you run `make fixup` to apply the styling changes?

You have to do the same changes inside this PR for XLM in order for the `repo_consistency` check to pass!

**Review by ArthurZucker — APPROVED** [review]
Yeah also looks good to me.

**Comment by younesbelkada** [comment]
This comment might help you: https://github.com/huggingface/transformers/pull/20939#issuecomment-1423974311

Looking closer at your code, a bad rebase happened on the `xlm` file, can you revert the changes there, and just modify the line as you did for flaubert, then run `make fix-copies` ?

**Comment by younesbelkada** [comment]
This is interesting, thanks for sharing! 
Feel free to add this change inside [`MultiHeadAttention`](https://github.com/huggingface/transformers/blob/d3b1adf59fff726f1c8f324728e562237f080ce6/src/transformers/models/xlm/modeling_xlm.py#L104) and then apply `make fix-copies` so that users can benefit from interesting speedups as you are suggesting
Otherwise, this can be addressed in a follow up PR too

**Review by younesbelkada — APPROVED** [review]
Thanks again for your work on this!

**Review by sgugger — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
