### PR TITLE
Fix of issue #13327: Wrong weight initialization for TF t5 model

### PR DESCRIPTION
**Pull request by dshirron**
# What does this PR do?

Fixes # 13327

## Who can review?
@patrickvonplaten

### CODE REVIEW

**Comment by Rocketknight1** [comment]
This looks great! The only change I'd suggest is that we don't usually sign names on comments - there are a lot of contributors to this repo and it could get out of hand.

**Review by Rocketknight1 — APPROVED** [review]

**Comment by Rocketknight1** [comment]
Looks good! Let me know when you're happy and I'll merge it.

**Comment by dshirron** [comment]
You can merge it. I only saw your comment and didnt see you already pushed a fix that removed all my comments in code, this is why i pushed a fix. Any solution is ok with me...

**Comment by Rocketknight1** [comment]
We're leaving the comments in, just with the author attributions removed. Thanks for your contribution, I'm merging now!

**Pull request merged**
