### PR TITLE
Add ability to get a list of supported pipeline tasks

### PR DESCRIPTION
**Pull request by codesue**
# What does this PR do?

This change adds the ability to programmatically get a list of supported pipeline tasks.

Currently, when new users want to know which tasks are supported in a pipeline, we have to reference the [Pipelines documentation](https://huggingface.co/docs/transformers/main_classes/pipelines) or parse the SUPPORTED_TASKS and TASK_ALIASES dictionaries. Being able to  programmatically get a list of supported pipeline tasks would be more convenient since it requires less context switching and parsing.

Example usage:
```
>>> from transformers.pipelines import get_supported_tasks
>>> print(*get_supported_tasks(), sep=“\n”)
audio-classification
automatic-speech-recognition
conversational
feature-extraction
fill-mask
image-classification
image-segmentation
ner
object-detection
question-answering
sentiment-analysis
summarization
table-question-answering
text-classification
text-generation
text2text-generation
token-classification
translation
zero-shot-classification
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@LysandreJik @Narsil

### CODE REVIEW

**Comment by julien-c** [comment]
Thanks for the PR! 

Off-topic from the actual PR but for background information, this is where the "canonical" list of pipelines (even outside of transformers) supported by the HuggingFace hub is stored: https://github.com/huggingface/huggingface_hub/blob/main/widgets/src/lib/interfaces/Types.ts

**Review by LysandreJik — APPROVED** [review]
Thank you for your PR, @codesue, this is useful! The failing tests are unrelated to your PR and are currently being fixed.

LGTM

**Review by Narsil — APPROVED** [review]
LGTM

**Comment by codesue** [comment]
Thanks for the reviews, everyone! And, wow, that was so fast! 🤩

**Pull request merged**
