### PR TITLE
Use huggingface_hub helper function to split state dict

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR do ? 
This PR uses the helper function from huggingface-hub to split a state dict into shards instead of `shard_checkpoint`. This will make maintenance easier for all HF libraries. Similar PR have been created in [accelerate](https://github.com/huggingface/accelerate/pull/2795) and [diffusers](https://github.com/huggingface/diffusers/pull/7830).

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
This looks good in theory to me; @Wauplin, could you give this a quick look as well?

**Comment by SunMarc** [comment]
Could you make `get_storage_id` public/documented since it is used in multiple places (not only when cleaning the state dict) @Wauplin ? Thanks !

**Review by Wauplin — APPROVED** [review]
Looks good to me as well! Thanks for taking care of this @SunMarc :)

If I'm not mistaken there are similar methods for tf / flax in `transformers` that could benefit from it. Can be done in separate PRs though.

**Comment by SunMarc** [comment]
> If I'm not mistaken there are similar methods for tf / flax in transformers that could benefit from it. Can be done in separate PRs though.

I'll have a look and do it in another PR after this PR gets merged and tested !

**Comment by Wauplin** [comment]
> Could you make get_storage_id public/documented since it is used in multiple places (not only when cleaning the state dict) @Wauplin ? 

@SunMarc Done in https://github.com/huggingface/huggingface_hub/pull/2304

> he current helper function in huggingface-hub introduced a regression in transformers (not able to handle kiB, miB). Is is fine ?

I'm not a `transformers`'s maintainer but I would assume it's fine. I'm quite convinced those parameters are never used (expect for the default value) and even less using kib, mib, etc. notation. If others feel strongly about it, we could somehow mitigate it directly in `transformers` (typically with a `max_size.lower().replace("mib", "mb").replace("gib", "gb")` + a deprecation warning). But I'd prefer not to update `huggingface_hub` for those.

**Comment by SunMarc** [comment]
> I'm not a transformers's maintainer but I would assume it's fine. I'm quite convinced those parameters are never used (expect for the default value) and even less using kib, mib, etc. notation. If others feel strongly about it, we could somehow mitigate it directly in transformers (typically with a max_size.lower().replace("mib", "mb").replace("gib", "gb") + a deprecation warning). But I'd prefer not to update huggingface_hub for those.

WDYT @amyeroberts ?

**Comment by amyeroberts** [comment]
> but I would assume it's fine. I'm quite convinced those parameters are never used (expect for the default value) and even less using kib, mib, etc. notation. If others feel strongly about it, we could somehow mitigate it directly in transformers (typically with a max_size.lower().replace("mib", "mb").replace("gib", "gb") + a deprecation warning). But I'd prefer not to update huggingface_hub for those.

@Wauplin @SunMarc Sounds good to me! Agreed, I don't think we need to handle a deprecation cycle here

**Review by amyeroberts — APPROVED** [review]

**Pull request merged**
