### PR TITLE
RAG README & pl version updated

### PR DESCRIPTION
**Pull request by knwoo**
# What does this PR do?

The current code for fine tuning examples/research_projects/rag' can't be executed without passing `--distributed_retriever ray` parameter.

In addition, `pytorch-lightning==1.5.10`  should be recommended to prevent other miscellaneous error.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@patrickvonplaten @shamanez 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Thanks for your PR, but we don't maintain this example, nor do we want to update it to more recent versions of any libraries it uses

**Comment by kaiiwoo** [comment]
> Thanks for your PR, but we don't maintain this example, nor do we want to update it to more recent versions of any libraries it uses

Hi, thanks for the reply. This PR is late response for https://github.com/huggingface/transformers/issues/18704#issue-1345102153 issue. Nevertheless, if this PR can't be accepted now, can you tell me the reasons for not mainitaining RAG?

**Comment by sgugger** [comment]
The RAG model is maintained, it's just this example which is not. It clearly says in the README it should be run with PyTorch ligthning 1.3.1. If you want to run it with a more recent version you need to adapt the script, probably as you did, but I'm not changing what the original authors have done in this research project.

Maintained examples are in the pytorch/tensorflow/flax subfolders of the examples folder.

**Review by patrickvonplaten — APPROVED** [review]

**Comment by patrickvonplaten** [comment]
Agree with @sgugger actually (sorry for approving it)

But, ok for me to also update the example since fine-tuning RAG seems to be used quite a bit

**Comment by shamanez** [comment]
@patrickvonplaten 

Actually, with the latest PL versions, we can't use **DDPPlugin**. So my suggestion is to move with ray_distributed_retriever only. If we update the code with the current changes, it will fail.

**Comment by sgugger** [comment]
@shamanez Why not host an updated version of the example on your repo then link to it from here and our community page in the doc?

**Pull request closed without merging**
