### PR TITLE
[WIP] Generate: implement prefilling

### LINKED ISSUE #27449: Compute logits and past_key_values once for the initial context rather than `num_beams` times?
### Feature request

It looks like (at least) the following methods:
- sample
- beam search
- beam sample
- group beam search

all immediately expand their input batch size to either `num_beams` or `num_return_sequences`. This means that the initial context, which can be very long, will be run through the model `num_beams`/`num_return_sequences` times, which seems to be unnecessary and causes a large overhead, especially when the initial context is long.

It seems to be possible to run the model once on the initial context within `beam_search` and related functions and broadcast the model's outputs to the desired batch size rather than expand the batch beforehand and run a full batch of the same context.

### Motivation

I wrote a short hack in the contribution section of the report that fixes this redundancy, at least for beam search, and at least for decoder only models, etc-- it's not a complete PR, but it demonstrates the kind of change that should be made.

I also tested the performance using this script: 

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

torch.set_default_device("cuda")
model = AutoModelForCausalLM.from_pretrained("PY007/TinyLlama-1.1B-step-50K-105b", load_in_4bit=True)
tokenizer = AutoTokenizer.from_pretrained("PY007/TinyLlama-1.1B-step-50K-105b")
inputs = tokenizer('''The unanimous Declaration of the thirteen united States of America, When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation.

We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.--That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, --That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness. Prudence, indeed, will dictate that Governments long established should not be changed for light and transient causes; and accordingly all experience hath shewn, that mankind are more disposed to suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they are accustomed. But when a long train of abuses and usurpations, pursuing invariably the same Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty, to throw off such Government, and to provide new Guards for their future security.--Such has been the patient sufferance of these Colonies; and such is now the necessity which constrains them to alter their former Systems of Government. The history of the present King of Great Britain is a history of repeated injuries and usurpations, all having in direct object the establishment of an absolute Tyranny over these States. To prove this, let Facts be submitted to a candid world.

''', return_tensors="pt", return_attention_mask=False)

import time

start = time.time()
for _ in range(10):
	outputs = model.generate(**inputs, max_new_tokens=15, do_sample=False, num_beams=6, num_return_sequences=6)
print("elapsed",(time.time()-start)/10)


text = tokenizer.batch_decode(outputs[:,-15:])
print(text)
```

Before the diff below was applied, this was the output:
```
elapsed 4.5888751745224
['We hold these truths to be self-evident, that all men', 'We hold these truths to be self evident, that all men are created', 'We hold these truths to be self-evident, that all Men', 'He has refused his Assent to Laws for establishing Judiciary', 'We hold these truths to be self-evident, that allmen', 'He has refused his Assent to Laws for establishing Judicial Systems']
```

After the diff below was applied, this was the output:
```
elapsed 2.614666700363159
['We hold these truths to be self-evident, that all men', 'We hold these truths to be self evident, that all men are created', 'We hold these truths to be self-evident, that all Men', 'He has refused his Assent to Laws for establishing Judiciary', 'We hold these truths to be self-evident, that allmen', 'He has refused his Assent to Laws for establishing Judicial Systems']
```

So, the change seems to give a ~1.7x speedup for this specific case while leaving the results of `beam_search` unchanged.

The speedup should be better for higher `num_beams` or longer contexts.

### Your contribution

As an example, I wrote a short hack that changes the behavior of `beam_search` on the main branch of huggingface so that it does not recompute `logits` and `past_key_values` `num_beams` times:
```diff
diff --git a/src/transformers/generation/utils.py b/src/transformers/generation/utils.py
index 4dbfc3670..63f863c80 100644
--- a/src/transformers/generation/utils.py
+++ b/src/transformers/generation/utils.py
@@ -1821,13 +1821,6 @@ class GenerationMixin:
                 num_beam_hyps_to_keep=generation_config.num_return_sequences,
                 max_length=generation_config.max_length,
             )
-            # 12. interleave input_ids with `num_beams` additional sequences per batch
-            input_ids, model_kwargs = self._expand_inputs_for_generation(
-                input_ids=input_ids,
-                expand_size=generation_config.num_beams,
-                is_encoder_decoder=self.config.is_encoder_decoder,
-                **model_kwargs,
-            )
             # 13. run beam search
             return self.beam_search(
                 input_ids,
@@ -3142,12 +3135,7 @@ class GenerationMixin:
         batch_size = len(beam_scorer._beam_hyps)
         num_beams = beam_scorer.num_beams
 
-        batch_beam_size, cur_len = input_ids.shape
-
-        if num_beams * batch_size != batch_beam_size:
-            raise ValueError(
-                f"Batch dimension of `input_ids` should be {num_beams * batch_size}, but is {batch_beam_size}."
-            )
+        batch_beam_size, cur_len = batch_size*num_beams, input_ids.shape[1]
 
         # init attention / hidden states / scores tuples
         scores = () if (return_dict_in_generate and output_scores) else None
@@ -3171,6 +3159,7 @@ class GenerationMixin:
         beam_scores[:, 1:] = -1e9
         beam_scores = beam_scores.view((batch_size * num_beams,))
 
+        expander = lambda x : x.expand([num_beams,*x.shape[1:]])
         this_peer_finished = False  # used by synced_gpus only
         while True:
             if synced_gpus:
@@ -3192,6 +3181,13 @@ class GenerationMixin:
                 output_hidden_states=output_hidden_states,
             )
 
+
+            if num_beams * batch_size != input_ids.shape[0]:
+                # ok, NOW expand the batch dimension
+                # AFTER the hard part is done
+                outputs["logits"] = expander(outputs["logits"])
+                outputs["past_key_values"] = [[expander(y) for y in x] for x in outputs["past_key_values"]]
+
             if synced_gpus and this_peer_finished:
                 cur_len = cur_len + 1
                 continue  # don't waste resources running the code we don't need
@@ -3237,6 +3233,11 @@ class GenerationMixin:
             next_indices = torch.div(next_tokens, vocab_size, rounding_mode="floor")
             next_tokens = next_tokens % vocab_size
 
+            if input_ids.shape[0] != num_beams:
+                    input_ids = expander(input_ids)
+                    if "attention_mask" in model_kwargs:
+                            model_kwargs["attention_mask"] = expander(model_kwargs["attention_mask"])
+
             # stateless
             beam_outputs = beam_scorer.process(
                 input_ids,
```

a change would have to be made to each one of the affected functions.

I may be able to expand this into a PR if desired.

### PR DESCRIPTION
**Pull request by tom-p-reichel**
# What does this PR do?

Fixes #27449

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@gante

### CODE REVIEW

**Comment by tom-p-reichel** [comment]
OK, current issues I understand:
- code quality error (fixed automatically with ruff).
- I forgot to handle an edge case where 1 or 0 length `input_ids` are passed in, fixable by refusing to prefill those sequences.

Current issues I don't understand at the moment:
- Some models do not put their `input_ids` in the output of `prepare_inputs_for_generation`-- e.g. t5. while others do, e.g. llama. This is strange because other parts of the code seem to assume that input_ids are in the output of `prepare_inputs_for_generation`: https://github.com/huggingface/transformers/blob/d1a00f9dd0b851245e4a54cbd70816a80e781ec2/src/transformers/generation/utils.py#L2612-L2620

**Comment by gante** [comment]
@tom-p-reichel ping me when you're stuck or when it's ready for review 🤗

**Comment by tom-p-reichel** [comment]
@gante Down to only 6 failing tests in test_torch!

As far as I can tell, all of the remaining failing tests here are due to the fact that prefilling currently changes the length of returned `past_key_values`, attentions, etc. returned from calls to `generate`-- the search functions don't know they're taking a prefilled input and don't make any considerations towards appending prefilled `past_key_values` or attentions to the output they generate. This seems messy to fix because we would have to edit the return values or possibly logic of multiple search algorithms.

Alternatively, maybe prefilling should be opt-in through a keyword arg to generate and simply shouldn't be enabled for those tests?

I'm a graduate student, so I am now facing final exams for a while, so I figure now is a good time to look at this and tell me if I'm on the right track. I could also use advice on addressing the last remaining failed tests.

I also checked that as of now this PR still produces a speedup in the example from my original issue on this topic.

Thanks in advance!

**Comment by gante** [comment]
Hey @tom-p-reichel! In general, the PR looks in a good direction.

I'm not fully aware of the details of the problem -- would have to dig into the code. I might be able to do it next week :)

**Pull request closed without merging**
