### PR TITLE
Translation/training: italian translation training.mdx

### PR DESCRIPTION
**Pull request by nickprock**
# What does this PR do?

* added translation.mdx
* updated _toctree.yml

See issue: [#17459](https://github.com/huggingface/transformers/issues/17459)

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@omarespejel @sgugger

### CODE REVIEW

**Comment by mfumanelli** [comment]
Hi @nickprock , I found these typos could you edit the file? Thanks!
- "benifici" --> "benefici"
- "stratergia" --> "strategia"
- "Addestranento" --> "Addestramento"
- "Le [Trainer] API supporta" --> "L'API [Trainer] supporta"
-  Here: "tutti gli iperparametri che puoi impostare" It doesn't seem so clear, I would maybe put it this way:  "tutti gli iperparametri che si possono calibrare". What do you think?
- "nonchè" --> "nonché"
- "funzione [accuratezza](https://huggingface.co/metrics/accuracy)" maybe I would keep the function names in English (i.e., with the original name)
- "maggiorni informazioni" --> "maggiori informazioni"
- "le Keras API" --> "l'API di Keras"
- "Sii sicuro" --> "Assicurati" (for gender neutrality)
- "sepecificare" --> "specificare"
- "Compila e fit" --> "Compilazione e adattamento"
- "Per gli utenti che preferiscono scrivere il loro personale ciclo di addestramento" --> "Per chi preferisse scrivere un proprio ciclo di addestramento personale"
- "pò di memoria" --> "po' di memoria"
- "perchè" --> "perché"
- "adesso sei pronto per addestrare!" --> "adesso possiamo addestrare!"  (for gender neutrality)

**Comment by nickprock** [comment]
Thanks for the review @mfumanelli :pray:, I fixed them.

**Comment by sgugger** [comment]
cc @omarespejel

**Review by sgugger — APPROVED** [review]
Same story as in #17600
Thanks a lot!

**Pull request merged**
