### PR TITLE
Fix failing DeepSpeed model zoo tests

### PR DESCRIPTION
**Pull request by pacman100**
# What does this PR do?
1. Fixing DeepSpeed model zoo tests
    a. `tests/deepspeed/test_model_zoo.py::TestDeepSpeedModelZoo::test_zero_to_fp32_zero3_img_clas_vit` was failing earlier due to `ValueError: --label_column_name label not found in dataset 'hf-internal-testing/cats_vs_dogs_sample'. Make sure to set `--label_column_name` to the correct text column - one of image, labels.`. Fixed this.
    b. `tests/deepspeed/test_model_zoo.py::TestDeepSpeedModelZoo::test_zero_to_fp32_zero3_trans_fsmt` was failing earlier due to `TypeError: Old language model head is of type <class 'torch.nn.modules.sparse.Embedding'>, which is not an instance of <class 'torch.nn.modules.linear.Linear'>. You should either use a different resize function or make sure that `old_lm_head` are an instance of <class 'torch.nn.modules.linear.Linear'>.`. This was because the `resize_token_embeddings` didn't account for the case when lm_head is an instance of `torch.nn.Embedding` and it was forcing the new lm_head to be an instance of `torch.nn.Linear`.
    c. `tests/deepspeed/test_model_zoo.py::TestDeepSpeedModelZoo::test_zero_to_fp32_zero2_trans_m2m_100` was failing earlier due to `ValueError: `--max_source_length` is set to 1024, but the model only has 512 position encodings. Consider either reducing `--max_source_length` to 512 or using a model with larger position embeddings`. Fixed the test to use appropriate source and target sequence lengths.

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks for fixing! cc @amyeroberts for final review :)

**Review by ArthurZucker — APPROVED** [review]
Thanks, tests are unrelated and I think failed on main. 
Would be nice to add a test, but alright otherwise

**Comment by pacman100** [comment]
> Would be nice to add a test, but alright otherwise

Could you please clarify what you mean?

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing all of these! 🙏

**Pull request merged**
