### PR TITLE
Fix whisper kwargs and generation config

### PR DESCRIPTION
**Pull request by zucchini-nlp**
# What does this PR do?

Whisper code was changed recently to use `prepare_generation_config` from the GenerationMixin [here](https://github.com/huggingface/transformers/blob/81642d2b51de9d5e5aee1768abdc744d90f7f52d/src/transformers/models/whisper/generation_whisper.py#L477), which started causing some bugs. See failing test in [this PR](https://github.com/huggingface/transformers/pull/30016).

Before, Whisper generation config did not do any `generation_config.update` and manually updated kwargs along the way. After the above change, kwargs cannot be used anymore because it contains unused kwargs from generation config.

This PR replaces everywhere we had `kwargs.pop()` with `generaion_config`. All tests are passing, except for some slow tests. But the slow tests are not passing in `main` also, so should be unrelated.

### CODE REVIEW

**Review by gante — APPROVED** [review]
LGTM, thank you for fixing 💛 

(I am surprised that no failures were raised in the previous PR's CI 👀 )

**Comment by ydshieh** [comment]
likely test fetcher didn't find it ...

**Comment by ydshieh** [comment]
well, i see , whisper is not in `IMPORTANT_MODELS`

IMPORTANT_MODELS = [
    "auto",
    # Most downloaded models
    "bert",
    "clip",
    "t5",
    "xlm-roberta",
    "gpt2",
    "bart",
    "mpnet",
    "gpt-j",
    "wav2vec2",
    "deberta-v2",
    "layoutlm",
    "llama",
    "opt",
    "longformer",
    "vit",
    # Pipeline-specific model (to be sure each pipeline has one model in this list)
    "tapas",
    "vilt",
    "clap",
    "detr",
    "owlvit",
    "dpt",
    "videomae",
]

should we put it ... 😄 @sanchit-gandhi @ArthurZucker ?

**Review by sanchit-gandhi — APPROVED** [review]
Awesome - thanks for the fix @zucchini-nlp! Requesting final review from @ArthurZucker

**Comment by sanchit-gandhi** [comment]
I would be in favour of adding Whisper and possible Wav2Vec2 as well to this list as the two most used audio models @ydshieh

**Comment by ydshieh** [comment]
@sanchit-gandhi `wav2vec2` is already in that list.

**Review by ArthurZucker — COMMENTED** [review]
Could you resolve merge conflicts since #29225 was merged!

**Comment by zucchini-nlp** [comment]
Done!

**Review by ArthurZucker — APPROVED** [review]
Thanks

**Comment by ydshieh** [comment]
@zucchini-nlp Do you have the merge permission (i.e. click the `squash and merge` button above)?

**Comment by zucchini-nlp** [comment]
yep, merged!

**Pull request merged**
