### PR TITLE
Add t5 convert to transformers-cli

### PR DESCRIPTION
**Pull request by acul3**
# What does this PR do?

add t5 model convert to transformers-cli

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@patrickvonplaten @sgugger @LysandreJik 
and
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM, thanks for adding!

**Comment by patrickvonplaten** [comment]
Can we trigger the CI again to make sure all tests are passing? Think you can add an empty git commit with 

```
git commit --allow-empty -m "Trigger notification"
```

**Comment by acul3** [comment]
@patrickvonplaten done it!..it seems failing 1 check only

**Comment by acul3** [comment]
@patrickvonplaten all seems good now...kindly check

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
