### PR TITLE
Fix Dropout Implementation in Graphormer

### PR DESCRIPTION
**Pull request by alexanderkrauck**
# What does this PR do?

This commit corrects the dropout implementation in Graphormer, aligning it with the original implementation (https://github.com/microsoft/Graphormer) and improving performance. Specifically:

1. The `attention_dropout` variable, intended for use in GraphormerMultiheadAttention, was defined but not used. This has been corrected to use `attention_dropout` instead of the regular `dropout`.
2. The `activation_dropout` for the activations in the feed-forward layers was missing. Instead, the regular `dropout` was used. This commit adds `activation_dropout` to the feed-forward layers and to the GraphormerConfig including documentation.

These changes ensure the dropout implementation matches the original Graphormer and delivers empirically better performance.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@clefourrier

### CODE REVIEW

**Comment by alexanderkrauck** [comment]
Hi @clefourrier and others,
this is the first time contributing to Huggingface for me. In the course of my thesis I found some improvements/fixes to your current Graphormer implementation including this one which is quite simple but has a big impact and should be easy to review. I plan to make some more pull requests with more performance related changes to speed Graphormer up and possibly also to add the 3D version in the following days/weeks. Feel free to reach out.
Best wishes, Alexander

**Comment by alexanderkrauck** [comment]
It still needs to be adressed! @clefourrier or whoever is responsible for it, am I doing something wrong with my pull request or what is taking so long for anyone to anwer?! How am I supposed to contribute if I am being ignored.

**Comment by clefourrier** [comment]
Hi @alexanderkrauck !
I have been very busy taking care of the Open LLM Leaderboard, and I put the graph transformers issues on the backburner for the summer. I was hoping to come back to this quite earlier than now, I'm very sorry about that.
I'll do my best to come back to these before the end of September

**Review by clefourrier — APPROVED** [review]
LGTM, thank you for this fix

**Comment by clefourrier** [comment]
@amyeroberts or @ArthurZucker ?

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
