### PR TITLE
chore: move `conftest.py` to `tests/`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
# What does this PR do?

It's common practice to place the `conftest.py` file within the `tests/` directory.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Request for Review: @stevhliu

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @ydshieh

**Comment by ydshieh** [comment]
@SauravMaheshkar

Could you take a look the error shown in the CI job `ci/circleci: examples_tensorflow `

(The other failures are irrelevant)

```bash
/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
UsageError: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --make-reports=examples_tensorflow
  inifile: /root/project/pyproject.toml
  rootdir: /root/project
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: --make-reports=examples_tensorflow
  inifile: /root/project/pyproject.toml
  rootdir: /root/project
```

**Comment by SauravMaheshkar** [comment]
> @SauravMaheshkar
> 
> Could you take a look the error shown in the CI job `ci/circleci: examples_tensorflow `
> 
> (The other failures are irrelevant)
> 
> ```shell
> /usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
> Plugin: helpconfig, Hook: pytest_cmdline_parse
> UsageError: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
> __main__.py: error: unrecognized arguments: --make-reports=examples_tensorflow
>   inifile: /root/project/pyproject.toml
>   rootdir: /root/project
> For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
>   config = pluginmanager.hook.pytest_cmdline_parse(
> ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
> __main__.py: error: unrecognized arguments: --make-reports=examples_tensorflow
>   inifile: /root/project/pyproject.toml
>   rootdir: /root/project
> ```

@ydshieh I was able to fix this locally by installing the `pytest-xdist` package.

**Review by ydshieh — APPROVED** [review]
Thanks!

**Comment by ydshieh** [comment]
Hi @SauravMaheshka,


We have `pytest-xdist==3.6.1` in our CI runners. But the issue persists.

**Comment by SauravMaheshkar** [comment]
> Hi @SauravMaheshka,
> 
> We have `pytest-xdist==3.6.1` in our CI runners. But the issue persists.

I can't reproduce this locally then. I got the tensorflow tests to pass locally after installing `pytest-xdist` in my virtual environment.

**Comment by ydshieh** [comment]
Hi @SauravMaheshkar 

You could look at 

https://app.circleci.com/pipelines/github/huggingface/transformers/98894/workflows/0204d85c-0fea-4e16-a724-e699e3f1e020/jobs/1313978

You can also check

> Show installed libraries and their versions

for more information

**Comment by SauravMaheshkar** [comment]
Hey I opened an issue for this #32512, so that we can look into later in more detail.

**Pull request closed without merging**
