### PR TITLE
Fix #17893, removed dead code

### LINKED ISSUE #17893: Ambiguous positional embedding management in LongformerEmbeddings
### System Info

```shell
Current main version of the transformer lib (4.20.1?)
```

### Who can help?

@ydshieh

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Hi!

In the code of the LongformerEmbeddings ([here](https://github.com/huggingface/transformers/blob/401fcca6c561d61db6ce25d9b1cebb75325a034f/src/transformers/models/longformer/modeling_longformer.py#L459)), there is unreachable code for the `position_ids` in `forward`.

```python
   def forward(self, input_ids=None, token_type_ids=None, position_ids=None, inputs_embeds=None):
        if position_ids is None:
            if input_ids is not None:
                # Create the position ids from the input token ids. Any padded tokens remain padded.
                position_ids = create_position_ids_from_input_ids(input_ids, self.padding_idx).to(input_ids.device)
            else:
                position_ids = self.create_position_ids_from_inputs_embeds(inputs_embeds)

        ...

        # Here, code is unreachable
        # as both create_position_ids_from_input_ids and create_position_ids_from_inputs_embeds always return stg 
        if position_ids is None:
            position_ids = self.position_ids[:, :seq_length]
```

So, what is the actual expected behavior of this layer for the positional embeddings ids? 
Is it supposed to use self.position_ids or not? 
(If yes, then this is indeed a bug, if not, then some code could be removed for clarity)

### PR DESCRIPTION
**Pull request by clefourrier**
# What does this PR do?

Fixes #17893 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? 

## Who can review?
@ydshieh

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
LGTM, thank you, @clefourrier !

I think we can also remove the line `_keys_to_ignore_on_load_missing = [r"position_ids"]` (line 1395), but let's wait for @sgugger  to confirm.

**Comment by LysandreJik** [comment]
Hey @clefourrier! The code quality error comes from a new release from `black`. Rebasing on `main should solve the issue as you'll benefit from https://github.com/huggingface/transformers/pull/17918.

**Comment by ydshieh** [comment]
Regarding the test

from Lysandre on Slack
```
There was a new release from black that has a slightly different behavior for the --preview flag that we use in the CI.
If you see failures in the CI for the code quality test, with a large number of file changes (>500), please mention to the author that they just need to rebase on/merge main in order to benefit from the fix.
Thanks 
[@Niels Rogge](https://huggingface.slack.com/team/U02758XGZLH)
 and 
[@Yih-Dar SHIEH](https://huggingface.slack.com/team/U01JNPUN1ML)
 for reporting!
```

**Comment by clefourrier** [comment]
@LysandreJik @ydshieh Should be good now! :smiley: 
Ty both, I had missed it on the slack

**Review by sgugger — APPROVED** [review]
I'll defer to @patrickvonplaten who knows the model best. Changes look good to me.

One last thing to change is the line
```
_keys_to_ignore_on_load_missing = [r"position_ids"]
```
later on in the pretrained model, which should be now
```
_keys_to_ignore_on_load_unexpected = [r"position_ids"]
```
Just in case there are some longformer checkpoints in the wild with a `position_ids` key in their state dict.

**Comment by clefourrier** [comment]
@sgugger Done :)

**Review by patrickvonplaten — APPROVED** [review]
Thanks for the fix! Great catch :-)

**Pull request merged**
