### PR TITLE
Fix err with FSDP

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

One potential solution for https://github.com/huggingface/transformers/issues/25988, we need to guard for things in Accelerate main better for items, especially items like fsdp and deepspeed

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@pacman100

### CODE REVIEW

**Review by pacman100 — COMMENTED** [review]
Hello Zach, I think the better way is to handle via version comparison.

**Comment by muellerzr** [comment]
@pacman100 sounds good, let me know if you are pleased :)

**Comment by jmif** [comment]
Ran into this issue too, confirmed this PR resolves for us.

**Review by pacman100 — APPROVED** [review]
Thank you @muellerzr for iterating!

**Pull request merged**
