### PR TITLE
fix CLAP integration tests

### PR DESCRIPTION
**Pull request by hollance**
# What does this PR do?

I noticed that the CLAP feature extractor tests were not being run, and that once enabled, they fail.

This PR fixes these tests.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for taking care of this! 💪

**Review by harshsingh32 — APPROVED** [review]

**Comment by hollance** [comment]
I don't have merge rights, so if all is good, feel free to merge. :-)

**Review by ArthurZucker — APPROVED** [review]
thanks for working on this! a lot of tests added 🔥

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
