### PR TITLE
Use templates

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR switches to use the templates in `doc-builder` for the doc building jobs.

### CODE REVIEW

**Comment by mishig25** [comment]
Is `.github/workflows/build_documentation.yml` handled in a different PR?

**Comment by sgugger** [comment]
Are you sure you looked at the whole diff? It's just modified by the PR, not deleted.

**Review by mishig25 — APPROVED** [review]
lgtm! I missaw (attached img) as completely deleted
Screenshot 2022-03-14 at 23 41 50

**Review by LysandreJik — APPROVED** [review]
Thanks for your work on this, @sgugger!

**Pull request merged**
