### PR TITLE
Remove token_type_ids from model_input_names (like #24788)

### PR DESCRIPTION
**Pull request by Apsod**
# What does this PR do?

Fixes an issue where the GPTSw3Tokenizer returns token_type_ids. These were not used in training and including them significantly degrades performance. This change is the same fix applied in #24788, which was later (erroneously?) reverted by #23909.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ArthurZucker @amyeroberts 

Members/contributors who may be interested in your PR:
@DarioSucic @ekgren @bjornrun

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing this! 

Looks fine to me, but let's get a second approval from @ArthurZucker who might know more about reasons for it being added back in previously

**Review by ArthurZucker — COMMENTED** [review]
Hey! Thanks for the PR! Could you make sure all the slow test pass for this tokenizer as well? I have no idea why I added this again but I think a test must have been failing!

**Comment by Apsod** [comment]
Thanks for the quick reply! 
I ran the following: 

```
RUN_SLOW=yes python -m pytest -n auto --dist=loadfile -s -v ./tests/models/gpt_sw3/test_tokenization_gpt_sw3.py
```
It did fail a test, namely an equality test where the reference output has token_type_ids.

It also (catastrophically) failed a test that referenced a closed model. 

I've removed the offending token_type_ids in the equality check and updated the model reference to an openly available model. It now passes all tests.

**Review by ArthurZucker — APPROVED** [review]
Thanks for the fix 🤗

**Pull request merged**
