### PR TITLE
Avoid collisions in writing metrics via 2 APIs - azureml + mlflow

### PR DESCRIPTION
**Pull request by akshaya-a**
MLflow tracking API is enabled by default in AzureML and HF MLflow integration is more fully featured. I'd remove the AzureML integration but leaving the current behavior for backwards compatibility (though it should really be removed)

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

It seems there is an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

**Comment by akshaya-a** [comment]
@sgugger thanks, I suppose I need to get a circleci account first? I can take a look tomorrow or feel free to merge this small change with an account someone already has

**Comment by akshaya-a** [comment]
@sgugger I have signed up and connected circleci, and the failed pipeline link doesn't seem to allow me to rerun, should I just bump it with a useless commit to retrigger the checks?

**Comment by sgugger** [comment]
You can try an empty commit indeed:
```
git commit -m "Trigger CI" --allow-empty
```

**Review by wamartin-aml — APPROVED** [review]

**Comment by sgugger** [comment]
Thanks again for yourcontribution!

**Pull request merged**
