### PR TITLE
#26566 swin2 sr allow in out channels

### LINKED ISSUE #26566: SWIN2SR: Allow to choose number of in_channels and out_channels
### Feature request

I'd like to be able to specify a different number of output and input channels for the Swin2sr superresolution model. The current [SWIN2SR](https://github.com/huggingface/transformers/blob/v4.33.3/src/transformers/models/swin2sr/modeling_swin2sr.py) implementation expects input and output images to have the same amount of channels (rgb). It's currently not possible to specify num_channels_in and num_channels_out in the model config. 

I propose to make in_channels = out_channels as default as most people will require this, but to give the user the possibility to specify a different number of out channels if required. There are some changes in the model logic required.

After implementing the feature, the config constructor should change from

```python
### [...]
  def __init__(
          self,
          image_size=64,
          patch_size=1,
          num_channels=3,
          embed_dim=180,
          depths=[6, 6, 6, 6, 6, 6],
          num_heads=[6, 6, 6, 6, 6, 6],
          window_size=8,
          mlp_ratio=2.0,
          qkv_bias=True,
          hidden_dropout_prob=0.0,
          attention_probs_dropout_prob=0.0,
          drop_path_rate=0.1,
          hidden_act="gelu",
          use_absolute_embeddings=False,
          initializer_range=0.02,
          layer_norm_eps=1e-5,
          upscale=2,
          img_range=1.0,
          resi_connection="1conv",
          upsampler="pixelshuffle",
          **kwargs,
      ):
          super().__init__(**kwargs)
  
          self.image_size = image_size
          self.patch_size = patch_size
          self.num_channels = num_channels
          self.embed_dim = embed_dim
          self.depths = depths
          self.num_layers = len(depths)
          self.num_heads = num_heads
          self.window_size = window_size
          self.mlp_ratio = mlp_ratio
          self.qkv_bias = qkv_bias
          self.hidden_dropout_prob = hidden_dropout_prob
          self.attention_probs_dropout_prob = attention_probs_dropout_prob
          self.drop_path_rate = drop_path_rate
          self.hidden_act = hidden_act
          self.use_absolute_embeddings = use_absolute_embeddings
          self.layer_norm_eps = layer_norm_eps
          self.initializer_range = initializer_range
          self.upscale = upscale
          self.img_range = img_range
          self.resi_connection = resi_connection
          self.upsampler = upsampler
```

to something like

```python

```python
### [...]
  def __init__(
          self,
          image_size=64,
          patch_size=1,
          num_channels_in=3,
          num_channels_out=3,
          embed_dim=180,
          depths=[6, 6, 6, 6, 6, 6],
          num_heads=[6, 6, 6, 6, 6, 6],
          window_size=8,
          mlp_ratio=2.0,
          qkv_bias=True,
          hidden_dropout_prob=0.0,
          attention_probs_dropout_prob=0.0,
          drop_path_rate=0.1,
          hidden_act="gelu",
          use_absolute_embeddings=False,
          initializer_range=0.02,
          layer_norm_eps=1e-5,
          upscale=2,
          img_range=1.0,
          resi_connection="1conv",
          upsampler="pixelshuffle",
          **kwargs,
      ):
          super().__init__(**kwargs)
  
          self.image_size = image_size
          self.patch_size = patch_size
          self.num_channels_in = num_channels_in
          self.num_channels_out= num_channels_out
          self.embed_dim = embed_dim
          self.depths = depths
          self.num_layers = len(depths)
          self.num_heads = num_heads
          self.window_size = window_size
          self.mlp_ratio = mlp_ratio
          self.qkv_bias = qkv_bias
          self.hidden_dropout_prob = hidden_dropout_prob
          self.attention_probs_dropout_prob = attention_probs_dropout_prob
          self.drop_path_rate = drop_path_rate
          self.hidden_act = hidden_act
          self.use_absolute_embeddings = use_absolute_embeddings
          self.layer_norm_eps = layer_norm_eps
          self.initializer_range = initializer_range
          self.upscale = upscale
          self.img_range = img_range
          self.resi_connection = resi_connection
          self.upsampler = upsampler
```

### Motivation

Having in=out in channels is totally fine when working with classical images. However when dealing with super resolution tasks in the context of earth observations, you often want to have different amounts of input and output channels, e.g. when performing super resolution from low res multi band satellite images to high res rgb band visible satellite. 

Other use cases I see is e.g. to predict from low res grayscale to high res colorscale.

### Your contribution

Happy to submit a PR for this one.

### PR DESCRIPTION
**Pull request by marvingabler**
# What does this PR do?

This PR adds the feature of accepting arbitary number of input and output channels when using the Swin2SR model. This allows to perform super resolution from greyscale (1 channel) to color (rgb), or from low resolution multi band satellite to high resolution rgb satellite.

All examples and pretrained models are running as expected based on my tests. No new dependencies have been added.

Just use it like

```python
from transformers import Swin2SRForImageSuperResolution, Swin2SRConfig
import torch

Swin2SRConfig = (
     num_channels_in=1,
     num_channels_out=3
)
model = Swin2SRForImageSuperResolution(Swin2SRConfig)

with torch.no_grad():
    # or use the image preprocessor per default
    out = model({"pixel_values":torch.randn((1,1,264,264))})

```

Fixes #26566.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Yes [here](https://github.com/huggingface/transformers/issues/26566)
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? No, test where there already.

## Tagging the reviewers

- text models: @ArthurZucker and @younesbelkada
- vision models: @amyeroberts

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Hi @marvingabler 
Thanks for your contribution! as you are removing the `num_channels` attribute I think that this is a breaking change, what about keeping `num_channels` and make it behave as `num_channels_in` and  use `num_channels_out` as an optional argument that is initialized as the same value as `num_channels` in case it is set to None. That way I believe changes will be backward compatible. What do you think?

**Comment by marvingabler** [comment]
Good point, yes lets do that! Let me update the PR soon :)

**Review by younesbelkada — APPROVED** [review]
Looking great to me! thanks!

**Review by ArthurZucker — COMMENTED** [review]
Thanks! Can you add a small test as well?  Making sure that a dummy model with a this can still perform as expected! 😉

**Comment by marvingabler** [comment]
Just realized that there are a couple of more changes required, as the `Swin2SRForImageSuperResolution` denormalizes based on the input images, while for the case of mapping from multiband images to single band, the mean&stds of inputs and outputs differ. Will add the changes soon.

**Review by ArthurZucker — APPROVED** [review]
Looks good to me thanks for adding this.

**Review by LysandreJik — APPROVED** [review]
Great, thanks!

**Pull request merged**
