### PR TITLE
Update convert_pytorch_checkpoint_to_tf2.py

### PR DESCRIPTION
**Pull request by sunyanrec**

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hello! What do you want to do with this PR?

**Comment by sunyanhust** [comment]
> Hello! What do you want to do with this PR?
The following error will be reported when the original code runs, and the new code fixes this bug.
image

**Comment by sunyanhust** [comment]
How to deal with this？
image

**Comment by sunyanhust** [comment]
> Hello! What do you want to do with this PR?

Hi! The original code has the following problems:

image

**Pull request closed without merging**
