### PR TITLE
Support Clip QKV for MPT

### PR DESCRIPTION
**Pull request by akakakakakaa**
# What does this PR do?
- Support Clip QKV for MPT

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@ArthurZucker and @younesbelkada

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks for this - @ArthurZucker indeed `clip_qkv` seems to be always there in MPTConfig: https://huggingface.co/mosaicml/mpt-7b/blob/main/config.json#L12 / https://github.com/huggingface/transformers/blob/bdf36dcd48106a4a0278ed7f3cc26cd65ab7b066/src/transformers/models/mpt/configuration_mpt.py#L48 but we never used it

**Comment by akakakakakaa** [comment]
@younesbelkada 
Is there any issue with merging this PR? Looking at the failed tests, it doesn't seem to be a problem with the PR code.

**Comment by younesbelkada** [comment]
Yes this looks good for me, just waiting for final core maintainer review
cc @amyeroberts @ArthurZucker

**Review by amyeroberts — APPROVED** [review]
Thanks for adding this support!

**Pull request merged**
