### PR TITLE
[Whisper] Make tests faster

### PR DESCRIPTION
**Pull request by sanchit-gandhi**
# What does this PR do?

Reduces the input seq length of the Whisper tests from 1500 -> 60 frames. This in turn should speed up the tests quite considerably.

### CODE REVIEW

**Comment by ydshieh** [comment]
Sorry, I am asking not because I see a test being slow, but just I saw some more Whisper test failures on daily CI, which is `tests/models/whisper/test_modeling_whisper.py::WhisperModelTest::test_cpu_offload`.

But yes, in general, it's best to use low number. I will take a look.

**Comment by ydshieh** [comment]
It's not because it's slow test that we use large value without really valid reason :-). Always better to make them use low values is the goal, unless it's absolute necessary.

**Comment by ydshieh** [comment]
OK, in flax test file, I see

```
        self.all_model_classes = (
            make_partial_class(model_class, input_shape=self.init_shape) for model_class in self.all_model_classes
        )
```
probably it's the reason.

**Review by ydshieh — APPROVED** [review]
Thank you @sanchit-gandhi  LGTM. I convinced myself regarding the `input_shape` thing.
But any comment is welcomed.

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
