### PR TITLE
solve Illegal seek in wandb teardown (test suite)

### PR DESCRIPTION
**Pull request by stas00**
somehow wandb teardown fails in `tests/test_trainer.py::TrainerIntegrationTest::test_trainer_eval_mrpc`:

```
pytest -n 1 tests/test_trainer.py::TrainerIntegrationTest::test_trainer_eval_mrpc
====================================================================== test session starts =======================================================================
platform linux -- Python 3.7.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /mnt/nvme1/code/huggingface/transformers-tests-1
plugins: hypothesis-5.5.4, filter-subpackage-0.1.1, arraydiff-0.3, flaky-3.6.1, ipynb-1.1.1.dev0, cov-2.10.0, astropy-header-0.1.2, forked-1.2.0, doctestplus-0.5.0, openfiles-0.4.0, remotedata-0.3.2, xdist-1.32.0
gw0 [1]
FE                                                                                                                                                         [100%]
wandb: Waiting for W&B process to finish, PID 19525

============================================================================= ERRORS =============================================================================
_______________________________________________ ERROR at teardown of TrainerIntegrationTest.test_trainer_eval_mrpc _______________________________________________
[gw0] linux -- Python 3.7.5 /home/stas/anaconda3/envs/main/bin/python

self = <contextlib._GeneratorContextManager object at 0x7efc47610690>, type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               OSError: [Errno 29] Illegal seek

/home/stas/anaconda3/envs/main/lib/python3.7/contextlib.py:119: OSError
============================================================================ FAILURES ============================================================================
_________________________________________________________ TrainerIntegrationTest.test_trainer_eval_mrpc __________________________________________________________
[gw0] linux -- Python 3.7.5 /home/stas/anaconda3/envs/main/bin/python

self = <contextlib._GeneratorContextManager object at 0x7efc476bbd50>, type = None, value = None, traceback = None

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
>               next(self.gen)
E               OSError: [Errno 29] Illegal seek

/home/stas/anaconda3/envs/main/lib/python3.7/contextlib.py:119: OSError
==================================================================== short test summary info =====================================================================
ERROR tests/test_trainer.py::TrainerIntegrationTest::test_trainer_eval_mrpc - OSError: [Errno 29] Illegal seek
FAILED tests/test_trainer.py::TrainerIntegrationTest::test_trainer_eval_mrpc - OSError: [Errno 29] Illegal seek
```

This is a possible solution, based on this solution 
https://github.com/wandb/client/issues/1138#issuecomment-654943065

### CODE REVIEW

**Review by sshleifer — APPROVED** [review]
why didn't this break CI?

**Comment by stas00** [comment]
CI doesn't have wandb installed.

**Comment by stas00** [comment]
I get an identical issue with wandb shutdown in other places as well, e.g. when running:

```pytest examples/test_examples.py::ExamplesTests::test_run_glue```

So far the solution seems to be to disable wandb. This works:

```
WANDB_DISABLED=true pytest examples/test_examples.py::ExamplesTests::test_run_glue
```

**Comment by julien-c** [comment]
pinging @borisdayma in case

**Comment by borisdayma** [comment]
The wandb cli is being updated and will have a noop mode that we can use for easier testing.
For now `WANDB_DISABLED=true` should work.

**Comment by stas00** [comment]
> The wandb cli is being updated and will have a noop mode that we can use for easier testing.

would it be possible to ping this issue when it happened, so that we could resolve this issue? Thank you very much, @borisdayma

**Comment by borisdayma** [comment]
Sounds good, I'll keep an eye on it!

**Comment by stas00** [comment]
Seems to have been resolved upstread (wandb) - I can no longer reproduce this problem, closing

**Pull request closed without merging**
