### PR TITLE
Fix bug in ChineseCLIPTextPooler

### PR DESCRIPTION
**Pull request by xiaohu2015**
# What does this PR do?

I think the ChineseCLIPTextPooler should be  consistent with https://github.com/huggingface/transformers/blob/main/src/transformers/models/chinese_clip/modeling_chinese_clip.py#L1374：
- bias=False
- don't use activation function

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by ydshieh** [comment]
Hi, @xiaohu2015! I think the pooling layer inside `ChineseCLIPTextModel` has nothing to do with the projection layer `text_projection` in ` ChineseCLIPModel`. And the model definition should be the one used by the model author which I believe the current one is the correct version.

**Comment by xiaohu2015** [comment]
> Hi, @xiaohu2015! I think the pooling layer inside `ChineseCLIPTextModel` has nothing to do with the projection layer `text_projection` in ` ChineseCLIPModel`. And the model definition should be the one used by the model author which I believe the current one is the correct version.

But CLIPTextModel is consistent with CLIPModel

**Comment by ydshieh** [comment]
> But CLIPTextModel is consistent with CLIPModel

This doesn't mean the relation of ChineseCLIPTextModel/ChineseCLIPModel should be the same as CLIPTextModel/CLIPModel. It is the author of ChineseCLIPModel who decided this way to construct the model.

**Comment by ydshieh** [comment]
I am going to close this thread. But don't hesitate to comment if you have any further question, @xiaohu2015

**Pull request closed without merging**
