### PR TITLE
Fix: Fix build issues with FalconMamba kernels

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

Currently when a user installs transformers from source and tries to import FalconMambaForCausalLM they will get an error: 
```bash
RuntimeError: Failed to import transformers.models.falcon_mamba.modeling_falcon_mamba because of the following error (look up to see its traceback):
No module named 'transformers.kernels.falcon_mamba'
```
The fix is to add the kernel file in the built transformers package 

cc @ArthurZucker

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
LGTM not tested in the fast tests, and our slow are a bit brokenb, and the slow-pr does not install the dependencuy

**Comment by ArthurZucker** [comment]
Feel free to rebase since #33356 should fix your cis

**Comment by younesbelkada** [comment]
Done @ArthurZucker

**Comment by younesbelkada** [comment]
This didn't work for packages that you install with git+... for some reason, I think it's simpler to just move the kernel on the same folder as the modeling file to avoid these issues

**Pull request closed without merging**
