### PR TITLE
Add SDPA support for M2M100

### PR DESCRIPTION
**Pull request by isaac091**
# What does this PR do?

This PR adds SDPA support for M2M100 models.

Part of #28005.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@ArthurZucker @fxmarty @amyeroberts

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for adding! 

Changes look good to me. 

Final step before merge is running the slow tests for the models. Could you push an empty commit with the message `[run_slow] m2m_100, nllb`?

**Comment by vasqu** [comment]
slow runs cc @amyeroberts

**Comment by amyeroberts** [comment]
Great - all looks good. @isaac091 could you resolve the conflicts? Once done we should be good to merge

**Comment by isaac091** [comment]
Resolved! Thanks @amyeroberts.

**Comment by amyeroberts** [comment]
Merging as the failing hub tests are unrelated (also on other PRs, shouldn't be impacted by this PR, looks like connection errors) and slow tests all pass (other than multi-gpu test which also failed for a connection error)

**Pull request merged**
