### PR TITLE
Fix typo in max_length deprecation warnings

### PR DESCRIPTION
**Pull request by siegeln**
# What does this PR do?

Specifying the max_length parameter in some text generation functions results in a deprecation warning. Currently, these warnings say to fix by using `stopping_criteria=StoppingCriteriaList(MaxLengthCriteria(max_length=max_length))`; however, this results in the error `TypeError: 'MaxLengthCriteria' object is not iterable`, as `StoppingCriteriaList` expects an iterable.

This PR fixes this typo.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Thanks! cc @gante pretty sure we can remove the warning no? `max_length` is as convenient as `max_new_tokens` IMO? 😉

**Review by gante — APPROVED** [review]
Thank you for the fix!

**Comment by gante** [comment]
@ArthurZucker in this case they are not interchangeable, `MaxLengthCriteria` expects `max_length`. In `generate`, `max_new_tokens` is converted into its `max_length` equivalent before `MaxLengthCriteria` is initialized :)

**Comment by ArthurZucker** [comment]
Ah right! Missed that, thanks 😉

**Review by ArthurZucker — APPROVED** [review]

**Pull request merged**
