### PR TITLE
Remove embarrassing debug print() in save_pretrained

### PR DESCRIPTION
**Pull request by Rocketknight1**
@sgugger spotted this one, sorry about that! (cc @gante)

### CODE REVIEW

**Review by gante — APPROVED** [review]
print("LGMT")

**Comment by sgugger** [comment]
This is already part of #19900 which is awaiting your review 😛

**Review by sgugger — APPROVED** [review]

**Comment by Rocketknight1** [comment]
If it is, you haven't pushed it!

**Comment by sgugger** [comment]
Oh! Then let's merge this.

**Pull request merged**
