### PR TITLE
Handle padding warning in generation when using `inputs_embeds`

### LINKED ISSUE #23042: Using `inputs_embeds` for generation gives an incorrect warning
I'm trying to use the `inputs_embeds` parameter to run the LLaMA model. This is part of my code.

```python
    # INPUT = ...embedding of a sequence, ensuring that there are no pad tokens
    output_sequences = LLaMA.generate(
        inputs_embeds=INPUT.to(device)
        pad_token_id=tokenizer.pad_token_id,
        # ... generation parameters, top_p top_k etc.
    )
```

I keep getting this warning, and the results are complete gibberish. I know this exact model performs well if I pass `input_ids`.

```
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set padding_side='left' when initializing the tokenizer.
```

After a lot of debugging, I found that this issue is because of the transformers library itself. The generate function checks that the last token ID in every batch should not be the pad token ID. If it is, it displays this warning.

https://github.com/huggingface/transformers/blob/a0e733283930bdb9ae2b1afdc53ec5f2daefb033/src/transformers/generation/utils.py#L1308-L1315

The `generate` function is expecting the shape `(Batch, Sequence)` where this logic would work.
```python
inputs_tensor[:, -1] == generation_config.pad_token_id
```
Now the problem is that I am passing `inputs_embeds` not IDs. My shape is `(Batch, Sequence, EmbeddingSize)`, so the above statement would be true if there are any zeros in the embedding of the last token. This is obviously incorrect.

That explains the warning but not the incorrect generation.

### Environment 
- `transformers==4.28.0`
- Python 3.10.11

### PR DESCRIPTION
**Pull request by zrthxn**
# What does this PR do?

Fixes: #23042
if `input_ids` was given, check if the last id in any sequence is `pad_token_id`
if `inputs_embeds` was given, check if the last embed in any sequence is *all* zeros

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? [Please add a link
      to it if that's the case.](https://github.com/huggingface/transformers/issues/23042)
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sgugger** [comment]
cc @gante

**Review by gante — COMMENTED** [review]
Why not simply add `and len(inputs_tensor.shape) == 2` to the `if`? Short, clear code is easier to maintain 🙌

**Comment by zrthxn** [comment]
> Why not simply add `and len(inputs_tensor.shape) == 2` to the `if`? Short, clear code is easier to maintain 🙌

Just adding `and len(inputs_tensor.shape) == 2` wouldn't print the warning if using `inputs_embeds`. Would you prefer that behaviour? Also, this logic would fail if the pad token for some embedding is **not** a tensor full of the `pad_token_id`.

**Comment by gante** [comment]
> Just adding and len(inputs_tensor.shape) == 2 wouldn't print the warning if using inputs_embeds. Would you prefer that behaviour? Also, this logic would fail if the pad token for some embedding is not a tensor full of the pad_token_id.

Yeah, I'd prefer the shorter version with the `len(inputs_tensor.shape) == 2` check only. The reason being that although it is less precise, using the embeddings as an input is an advanced use case, for which we tend to be more hands-off. It also makes the code shorter and, therefore, more readable :)

**Comment by zrthxn** [comment]
Alright, I've changed the logic to be very simple now. It just doesn't check this condition if `inputs_embeds` was passed.

**Review by gante — APPROVED** [review]
Thanks for improving the warning in this case!

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by zrthxn** [comment]
@gante no problem! Just did that.

**Pull request merged**
