### PR TITLE
precompiled_charsmap checking before adding to the normalizers' list for XLNetTokenizerFast conversion.

### LINKED ISSUE #24616: XLNetTokenizerFast conversion fails with identity normalization in Sentencepiece tokenizer
### System Info

- `transformers` version: 4.25.1
- Platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.17
- Python version: 3.8.13
- Huggingface_hub version: 0.15.1
- PyTorch version (GPU?): 1.12.1+cu102 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): 0.6.3 (cpu)
- Jax version: 0.4.1
- JaxLib version: 0.4.1
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZ

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I was trying to initialize an XLNetTokenizerFast tokenizer using a Sentencepiece tokenizer model.  While training the Sentencepiece tokenizer, I used the `identity` normalization rule name as I did not want to normalize the texts. While initializing XLNetTokenizerFast using this Sentencepiece tokenizer, it fails and raises the following error:

```bash
Traceback (most recent call last):
  File "xlnet_tok_test.py", line 10, in <module>
    tokenizer = transformers.XLNetTokenizerFast(
  File "/home/shahad/miniconda3/envs/gen/lib/python3.8/site-packages/transformers/models/xlnet/tokenization_xlnet_fast.py", line 150, in __init__
    super().__init__(
  File "/home/shahad/miniconda3/envs/gen/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 118, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "/home/shahad/miniconda3/envs/gen/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py", line 1162, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "/home/shahad/miniconda3/envs/gen/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py", line 503, in converted
    tokenizer.normalizer = self.normalizer(self.proto)
  File "/home/shahad/miniconda3/envs/gen/lib/python3.8/site-packages/transformers/convert_slow_tokenizer.py", line 786, in normalizer
    list_normalizers.append(normalizers.Precompiled(precompiled_charsmap))
Exception: Error while attempting to build Precompiled normalizer: Cannot parse precompiled_charsmap
```

However, I can successfully initialize XLNetTokenizerFast when the Sentencepiece tokenizer is trained with `nfkc` or the default `nmt_nfkc` normalization rule.

This bug can be reproduces using the following colab notebook:
https://colab.research.google.com/drive/1kj17NAP3xn22MEwp_96eNBLYg5d5np9u?usp=sharing

### Expected behavior

The XLNetTokenizerFast should be initialized without any error.

### PR DESCRIPTION
**Pull request by shahad-mahmud**
# What does this PR do?

There is a small change to check the `precompiled_charsmap` during the conversion of a slow tokenizer to `XLNetTokenizerFast`. It will check if the `precompiled_charsmap` is empty before initializing `normalizers.Precompiled` from the tokenizers library. If a [Sentencepiece](https://github.com/google/sentencepiece) tokenizer model is trained with `identity` normalization rule, i.e. no normalization is applied, it fails to initialize a XLNetTokenizerFast as discussed in issue #24616. This PR solves this issue.

Fixes #24616 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@ArthurZucker

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! Seems like this is a duplicated of #22809, but it has been stale for a while. Make sure to fix the tests, and incorporate changes so that it works with all models!

**Comment by shahad-mahmud** [comment]
Hey @ArthurZucker I have incorporated the changes so that it supports all the models. 

It is failing in one test case and it seems the test case is not related to this PR. From details I see that it fails due to the `module 'PIL.Image' has no attribute 'LINEAR'` error. Can it be related to the module or environment where the test is running? Do I need to work on this test case for this PR?

**Review by ArthurZucker — APPROVED** [review]
No need to work on the test case! You should probably just rebase/pull from the main branch and this should be solved

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by amyeroberts** [comment]
For the `test_exotic_models tests`, a fix, pinning the Pillow version has now been merged into main. Could you rebase to include these and trigger a re-run of the CI?

**Comment by shahad-mahmud** [comment]
Hey @ArthurZucker and @amyeroberts all tests passed after the rebase. Can you have a look?

**Comment by ArthurZucker** [comment]
Perfect! Thanks for addressing this and contributing! 🤗

**Pull request merged**
