### PR TITLE
[TF 2.2 compat]  use tf.VariableAggregation.ONLY_FIRST_REPLICA

### PR DESCRIPTION
**Pull request by jplu**
This PR updates the TF gradient accumulator optimization to make it compliant with the new TF 2.2.

### CODE REVIEW

**Review by thomwolf — APPROVED** [review]
Awesome!

**Comment by jplu** [comment]
Good to be merged for me :)

**Comment by thomwolf** [comment]
I think you can cc @LysandreJik @julien-c

**Comment by julien-c** [comment]
Yes can you do it in the same PR? and it'll be ready to merge.

**Comment by LysandreJik** [comment]
Nice! Unfortunately there are other issues with TF2.2, hence why the tests fail and why the version was pinned. I'm patching it now.

**Comment by jplu** [comment]
Yep I think @mfuntowicz is working on it as it is related to the Tokenizer. At least we have identified why it is not working :)

**Pull request merged**
