### PR TITLE
Fix: typo from qwen2 vl config

### PR DESCRIPTION
**Pull request by effortprogrammer**
# What does this PR do?

Fixes this error: 

```markdown
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/work/.vscode-server/extensions/ms-python.debugpy-2024.13.2024111901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 3704, in <module>
[rank0]:     main()
[rank0]:   File "/home/work/.vscode-server/extensions/ms-python.debugpy-2024.13.2024111901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 3689, in main
[rank0]:     globals = debugger.run(setup["file"], None, None, is_module)
[rank0]:   File "/home/work/.vscode-server/extensions/ms-python.debugpy-2024.13.2024111901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2687, in run
[rank0]:     return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
[rank0]:   File "/home/work/.vscode-server/extensions/ms-python.debugpy-2024.13.2024111901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/pydevd.py", line 2695, in _exec
[rank0]:     globals = pydevd_runpy.run_path(file, globals, "__main__")
[rank0]:   File "/home/work/.vscode-server/extensions/ms-python.debugpy-2024.13.2024111901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
[rank0]:     return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
[rank0]:   File "/home/work/.vscode-server/extensions/ms-python.debugpy-2024.13.2024111901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
[rank0]:     _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
[rank0]:   File "/home/work/.vscode-server/extensions/ms-python.debugpy-2024.13.2024111901-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/data/workspace/howard/workspace/Llava/qwen2_vl_instruct_post_train.py", line 423, in <module>
[rank0]:     main(train_args)
[rank0]:   File "/data/workspace/howard/workspace/Llava/qwen2_vl_instruct_post_train.py", line 329, in main
[rank0]:     model = Qwen2VLForConditionalGeneration.from_pretrained(model_name_or_path, config=config)
[rank0]:   File "/data/workspace/howard/workspace/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4096, in from_pretrained
[rank0]:     model = cls(config, *model_args, **model_kwargs)
[rank0]:   File "/data/workspace/howard/workspace/.venv/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 1421, in __init__
[rank0]:     self.visual = Qwen2VisionTransformerPretrainedModel._from_config(config.vision_config)
[rank0]:   File "/data/workspace/howard/workspace/.venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1543, in _from_config
[rank0]:     model = cls(config, **kwargs)
[rank0]:   File "/data/workspace/howard/workspace/.venv/lib/python3.10/site-packages/transformers/models/qwen2_vl/modeling_qwen2_vl.py", line 990, in __init__
[rank0]:     in_channels=config.in_channels,
[rank0]:   File "/data/workspace/howard/workspace/.venv/lib/python3.10/site-packages/transformers/configuration_utils.py", line 205, in __getattribute__
[rank0]:     return super().__getattribute__(key)
[rank0]: AttributeError: 'CLIPVisionConfig' object has no attribute 'in_channels'. Did you mean: 'in_chans'?
```

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @zucchini-nlp

### CODE REVIEW

**Review by zucchini-nlp — COMMENTED** [review]
Hey @effortprogrammer ! Qwen2-VL should use `Qwen2VLVisionConfig` config for the vision tower so there should be no need for modification

**Comment by ruidazeng** [comment]
> Hey @effortprogrammer ! Qwen2-VL should use `Qwen2VLVisionConfig` config for the vision tower so there should be no need for modification

What can we do instead to fix the aforementioned error?

**Comment by zucchini-nlp** [comment]
@ruidazeng I need a reproducer to see how the model is init, but the idea is to use `Qwen2VLVisionConfig` as the vision config

**Comment by effortprogrammer** [comment]
@zucchini-nlp I am calling the model by using 

```python
    model = Qwen2VLForConditionalGeneration.from_pretrained(model_name_or_path, config=config)

```
with model_name_or_path = "Qwen/Qwen2-VL-7B-Instruct"

with current implementation.

**Comment by effortprogrammer** [comment]
@zucchini-nlp I tested in the different version with installing from github source to test, but it seems like it's still having the issue... not sure what is wrong

**Comment by effortprogrammer** [comment]
I think this issue seems came from #34950, so closing this. I will make a new one if new problem has been found.

**Pull request closed without merging**
