### PR TITLE
Add type hints for PyTorch Models

### LINKED ISSUE #16059: Add missing type hints
### This issue is part of our **Great Code Cleanup 2022**. If you're interested in helping out, take a look at [this thread](https://twitter.com/carrigmat/status/1502319813510766599), or come [join us on Discord](https://t.co/kS42XBvpWH) and talk with other contributors!

# 🚀 Add missing type hints

Type hints are used inconsistently in the `transformers` repo across both TF and PT models, and it'd be nice to make them a complete, consistent thing for the core models, especially because we want to develop features that depend on them!

### Guide to contributing:

1. Ensure you've read our contributing [guidelines](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md) 📜 
2. Claim your architecture(s) in this thread (ensure no one is working on it). It's 100% okay to only take the TensorFlow or PyTorch version of a model, if you're not familiar with both frameworks! It's also okay to claim multiple models and group those changes into a single PR! 🎯 
3. Implement the changes as in https://github.com/huggingface/transformers/pull/16057 or https://github.com/huggingface/transformers/pull/16074 (see the diff on the model architectures for a few examples) 💪 
4. Open the PR and tag me in it. You should run `make fixup` at the end to do a code quality check before your final commit!

### Tips for making your PR

1. The files you need to edit will be in `src/transformers/models/[model_name]/`
2. For TensorFlow, you want the `modeling_tf_[model_name].py` file. For PyTorch, you want the `modeling_[model_name].py` file.
3.  Remember, you **do not** have to cover every class in that file!. The main thing we want to cover is the `call` (for TF) or `forward` (for PT) method for user-facing classes like `TFRobertaForMaskedLM` or `RobertaForSequenceClassification`. It's not necessary to add type hints to layers or base classes like `RobertaModel` or `TFRobertaPreTrainedModel` - these are trickier to write, and generally people do not use those classes as standalone models.
4. If you're unfamiliar with how type hints work, you can read the [Python library documentation on them](https://docs.python.org/3/library/typing.html), but it's probably even easier to just look at another PR that added them. Take a look at the list of changes in the pull requests linked above!
5. The types will usually be obvious - most inputs are `Optional[Union[np.ndarray, tf.Tensor]]` for TF models and `Optional[torch.Tensor]` for PyTorch models, and boolean inputs are `Optional[bool]`. Pay attention to the first input of TF models, though, which is usually `TFModelInputType` - this is because Keras handles that first input in a special way! Other inputs to pay attention to are `past_key_values`, which can vary between models, and also the model output type. For the base model classes like `RobertaModel`, you may have to look at the corresponding `MainLayer` to figure out the right output type! Also, note that the output type may be a tuple if `return_dict` is False, in which case you should specify `Union[Tuple, ...]`. Finally, note that in TF models, `training` is never `None`, so it should be `training: bool` and not `training: Optional[bool]`.
6. Note that some code is copied across our codebase. If you see a line like `# Copied from transformers.models.bert...`, this means that the code is copied from that source, and our scripts will automatically keep that in sync. If you see that, you should not edit the copied method! Instead, edit the original method it's copied from, and run `make fixup` to synchronize that across all the copies. Be sure you installed the development dependencies with `pip install -e ".[dev"]`, as described in the contributor guidelines above, to ensure that the code quality tools in `make fixup` can run.

### How can I find models that need type hints?

I used to maintain a list here, but it got out of date, I'm sorry. Instead, you can use [this Colab notebook](https://colab.research.google.com/drive/1EvZTslb50yfRqIcXjCZFrbod4HrPdA0G?usp=sharing). If you run this, it will show you models in PyTorch or TF that are still missing type hints. Unlike my manually curated lists, it's guaranteed to be up to date - but do double-check that someone else in the thread hasn't claimed a model before you start, because the Colab code will only register type hints after the PR containing them is merged!

### PR DESCRIPTION
**Pull request by karthikrangasai**
# What does this PR do?

Add type hints to as many PyTorch models as possible.

This PR targets the following models to type hint entire files:
- Albert
- Bart
- Bert
- BertGeneration
- BigBird
- BigBirdPegasus
- Canine
- ConvBert
- ConvNext
- CTRL
- Data2VecText
- Data2VecAudio
- Hubert
- Marian
- MBart
- Nystromformer
- Wav2Vec2
- WavLM
- XGLM
- XLMRobertaXL
- Yoso

Any other file that has been edited is a result of running `make fix-copies`.

In the next PR, I will target few other models to type hint complete files.

Fixes #16059 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@Rocketknight1

### CODE REVIEW

**Comment by karthikrangasai** [comment]
Hello all,

I changed the cokkiecutter template code because the `check_copies` script couldn't correct code that got changed to multiple lines.

Changing a method in Bart model:
```py
##########
## From ##
##########
# Copied from transformers.models.bart.modeling_bart.BartDecoder._prepare_decoder_attention_mask
def _prepare_decoder_attention_mask(self, attention_mask, input_shape, inputs_embeds, past_key_values_length):

########
## To ##
########
# Copied from transformers.models.bart.modeling_bart.BartDecoder._prepare_decoder_attention_mask
def _prepare_decoder_attention_mask(
    self,
    attention_mask: torch.Tensor,
    input_shape: torch.Size,
    inputs_embeds: torch.FloatTensor,
    past_key_values_length: int,
) -> Optional[torch.Tensor]:
```

The code correcter script would make the following change:
```py
# Copied from transformers.models.bart.modeling_bart.BartDecoder._prepare_decoder_attention_mask
def _prepare_decoder_attention_mask(self, attention_mask, input_shape, inputs_embeds, past_key_values_length):
    self,
    attention_mask: torch.Tensor,
    input_shape: torch.Size,
    inputs_embeds: torch.FloatTensor,
    past_key_values_length: int,
) -> Optional[torch.Tensor]:
```

Which caused the errors in [one of the test runs](https://github.com/huggingface/transformers/runs/5709841712?check_suite_focus=true).


Just commenting the reason here in case someone is taking a look at this PR later.

**Comment by karthikrangasai** [comment]
Hello all,

I have updated the code base with type hints for a few models. 
I will open a new PR for the remaining models after this one is merged, since this PR is getting bigger.

Thanks

**Comment by karthikrangasai** [comment]
Hello all,

The `Add model like runner` test is failing with an `ImportError` when starting to run the `Run all PyTorch modeling test` section of the tests with the following error:

```bash
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/home/runner/.local/lib/python3.8/site-packages/werkzeug/debug/tbtools.py)
```
I am unsure as to what is causing the error and any leads on how to resolve this issue would be appreciated.

Thank you

**Comment by Rocketknight1** [comment]
Wow, this is a huge PR! Did you do this manually, or have you figured out some kind of tool for it?

**Comment by karthikrangasai** [comment]
Hello @Rocketknight1 ,

Yeah, I made all this manually. This was how I spent my weekend 😛.

**Comment by Rocketknight1** [comment]
That's amazing! I'll try to review now.

**Comment by Rocketknight1** [comment]
This is a huge and very impressive PR, thank you! The main suggestion I have is that bools are not annotated in some cases, e.g. `output_attentions=False` should be `output_attentions: bool = False`, or `output_attentions: Optional[bool] = None` when the default is `None`. I'll try to recruit a couple of people from Huggingface to help me review the whole thing once that's resolved!

**Comment by Rocketknight1** [comment]
Absolutely! I saw in some cases `past` was missing annotations - if you're unsure about annotations like that, you can usually check the docstrings for the `past` or `past_key_values` argument for that model - it'll be something like `Tuple[torch.Tensor]`

**Comment by karthikrangasai** [comment]
Sure, later in the process I figured out the type and I had added for a few files. Fill fix for others as well.

**Comment by Rocketknight1** [comment]
Note that `past`/`past_key_values` can have different structure in different models!

**Comment by karthikrangasai** [comment]
Ohhh, thanks for the heads up.

**Comment by Tegzes** [comment]
@karthikrangasai The best way to make sure the type hints are correct is to check the [Model Name]_INPUTS_DOCSTRING, right before the first user interfaced forward method

**Comment by karthikrangasai** [comment]
Hello @Tegzes ,
I checked that for all forward methods. But it might be possible that I missed it for a few files.

I have type hinted the entire file, from first function to last class. So i might have missed something in other places.

**Comment by Rocketknight1** [comment]
Hi @karthikrangasai ! This is totally my bad - other PRs came in and I reviewed them without realizing they would create conflicts with your one. Would it be possible to break this PR up into a few separate ones and submit them one at a time? That greatly reduces the chances of conflicts for each one, and it'll make it possible for me to add specific comments/suggestions, whereas at this size I really can just give general advice!

**Pull request closed without merging**
