### PR TITLE
[WIP]Add splinter test tokenization file

### PR DESCRIPTION
**Pull request by farahdian**
# What does this PR do?

This PR adds test tokenization file for Splinter. It inherits from BERT Tokenizer.

Contributes fixes to issue https://github.com/huggingface/transformers/issues/16627

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@LysandreJik
@SaulLu

### CODE REVIEW

**Comment by farahdian** [comment]
> Hi @farahdian , thank you very much for your contribution. I see that several tests have failed, is this still a work in progress?

Yup a work in progress, but will appreciate some guidance and will be inspecting the failed tests. Sorry for any confusion!

**Comment by SaulLu** [comment]
Ok top! I'd be happy to give you a hand. 

I think in your case it would be great if the title of the PR started with `[WIP]` and a first failing test that you can fix is style of the files by running the `make fixup` command locally (cf the  [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests)).

For the rest of the tests that fail, could you tell me more about what is obscure for you?

**Comment by farahdian** [comment]
Many thanks. I've tried to run ```make fixup``` but this error keeps coming up:

```
make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ make fixup
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I've tried using ```python -m``` alongside but then it returns this:
```
usage: __main__.py [-h] {project,get} ...
__main__.py: error: invalid choice: 'fixup' (choose from 'project', 'get')
```

Think this may be related to why I've been having some issues running tests locally... appreciate you having a look!

**Comment by SaulLu** [comment]
From your error message, what I understand is that you don't have the `make` command installed on your computer. 

([source](https://www.computerhope.com/unix/umake.htm))
> On Unix-like operating systems, make is a utility for building and maintaining groups of programs (and other types of files) from source code.

Depending on your OS, you'll probably have an alternative to install it. For example on [Windows you can use WSL.](https://github.com/Microsoft/WSL/issues/2073)

**Comment by SaulLu** [comment]
Hi @farahdian ,

Just a quick message to see how you're doing with adding the tests on your end. :relaxed:

**Comment by SaulLu** [comment]
Hi @farahdian ,

Thanks for the update. What is your working directory when you run the `make fixup` command?

**Comment by SaulLu** [comment]
I see, you need to run it from the root repository `transformers/` where the `[Makefile](https://github.com/huggingface/transformers/blob/main/Makefile)` lives :blush:

**Comment by SaulLu** [comment]
Hi @farahdian, 

How things are going for you? :slightly_smiling_face:

**Comment by farahdian** [comment]
Sorry for the delay, think I reached beyond my capabilities with this one. Hope this can be passed on to another contributer

**Comment by SaulLu** [comment]
Thank you for keeping us informed

**Pull request closed without merging**
