### PR TITLE
Add Ray Tune hyperparameter search integration test

### PR DESCRIPTION
**Pull request by krfricke**
# What does this PR do?

Currently, only Optuna HP search is tested in integration tests. This PR duplicates and adjusts the test for the Ray backend.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@amogkam 
@sgugger

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
I like it, very elegant!

**Review by LysandreJik — APPROVED** [review]
This looks great, thanks!

I don't think this will be run though, as we don't have an environment where `ray` is installed in the CI? We can add it to the scheduled tests to ensure it runs once per day.

**Comment by krfricke** [comment]
Oh, that makes sense. Does this happen in the repo? Is this something I can help with, or do you have to configure it?

**Comment by LysandreJik** [comment]
I'm currently working on these scheduled tests, I'll enable these while I do so. Thanks!

**Pull request merged**
