### PR TITLE
Add gguf support for gpt2

### PR DESCRIPTION
**Pull request by VladOS95-cyber**
# What does this PR do?
Add GGUF support for GPT2

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. Link: https://github.com/huggingface/transformers/issues/33260
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Regarding the task @SunMarc @LysandreJik @ArthurZucker.

### CODE REVIEW

**Comment by VladOS95-cyber** [comment]
Hi @SunMarc! This PR is ready for review, please, take a look.

**Review by SunMarc — APPROVED** [review]
Thanks for your work as always !

**Review by LysandreJik — APPROVED** [review]
Nice and simple! Thanks @VladOS95-cyber!

**Comment by VladOS95-cyber** [comment]
> Nice and simple! Thanks @VladOS95-cyber!

@SunMarc @LysandreJik You are welcome!

**Pull request merged**
