### PR TITLE
Don't close ClearML Task when training is complete

### LINKED ISSUE #26762: ClearML task closes when done training - unnecessary and causes issues
### System Info

When a python script ends, it automatically closes the task.  After training, some people (me included) may want to do more for the task, including inferencing on the model.  Therefore, always automatically closing the task on training completion, while sounding nice, is not needed and causes issues.

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

See code here:
https://github.com/huggingface/transformers/blob/0ebee8b93358b6ef0182398b8fcbd7afd64c0f97/src/transformers/integrations/integration_utils.py#L1488-L1493

### Expected behavior

The ClearML task does not close when training is complete.

### PR DESCRIPTION
**Pull request by johnml1135**
This is to fix https://github.com/huggingface/transformers/issues/26762.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @skinan for first review - as integrations are maintained by the contributors who added them

**Comment by amyeroberts** [comment]
@johnml1135 Am I correct in understanding this PR can be closed as the issue was resolved in #26614 ?

**Comment by johnml1135** [comment]
Yes - it should be resolved now.

**Comment by amyeroberts** [comment]
@johnml1135 Thanks for confirming!

**Pull request closed without merging**
