### PR TITLE
Kill model archive maps

### PR DESCRIPTION
**Pull request by julien-c**
Links to model weights inside the code are not useful anymore, on the contrary, defining those shortcuts to URLs in code tend to lead to discrepancies with the canonical naming scheme of models at huggingface.co

As an example, we cannot cleanly load [`facebook/bart-large-cnn`](https://huggingface.co/facebook/bart-large-cnn) from either huggingface.co or the inference API because it's aliased to bart-large-cnn in the code.

If this PR is approved, before merging I will:
- do the same thing for configs (easy)
- just rename the renamed model identifiers for tokenizers. (completely getting rid of "archive maps" for tokenizers is way harder because of the hardcoded maps like `PRETRAINED_POSITIONAL_EMBEDDINGS_SIZES` and `PRETRAINED_INIT_CONFIGURATION`)

---

⚠️  **Note that the change in this PR is breaking for the names of the following models:**

```
"cl-tohoku/bert-base-japanese"
"cl-tohoku/bert-base-japanese-whole-word-masking"
"cl-tohoku/bert-base-japanese-char"
"cl-tohoku/bert-base-japanese-char-whole-word-masking"
"TurkuNLP/bert-base-finnish-cased-v1"
"TurkuNLP/bert-base-finnish-uncased-v1"
"wietsedv/bert-base-dutch-cased"
"flaubert/flaubert_small_cased"
"flaubert/flaubert_base_uncased"
"flaubert/flaubert_base_cased"
"flaubert/flaubert_large_cased"

all variants of "facebook/bart"
```

^^ You'll need to specify the organization prefix for those models from now on. However, no files were moved on S3 so this doesn't change anything for all current versions of the library.

However it's a breaking change so we'll be sure to pinpoint to it in the next release.

### CODE REVIEW

**Review by n1t0 — APPROVED** [review]
Nice, it's way better this way! It doesn't make sense to keep hard-coded URLs in the code, especially now that the naming scheme is well defined. I think the breaking change is totally worth it.

I don't know how all of this works well enough to make a thorough review though, but looks good to me!

**Comment by sshleifer** [comment]
Love this! is there a plan to allow aliases moving forward?
typing `'Helsinki-NLP/opus-mt-romance-en'` is not awful so I don't feel very strongly that we should, but interested in your thoughts.

**Comment by julien-c** [comment]
Hmm no I don't see an obvious need for aliases personally.

**Review by LysandreJik — APPROVED** [review]
Cool, that's a much needed clean-up.

**Comment by patrickvonplaten** [comment]
Awesome!

**Review by patrickvonplaten — APPROVED** [review]

**Comment by julien-c** [comment]
For configs, I decided to leave the URLs (even if they're not used) to have quick reference and be able to open them from the code. We can always delete them later though.

Ok, merging this!

**Pull request merged**
