### PR TITLE
Implement Fast Tokenization for Deberta

### LINKED ISSUE #10498: DeBERTa Fast Tokenizer
Hi, I am interested in using the DeBERTa model that was recently implemented here and incorporating it into [FARM](https://github.com/deepset-ai/FARM) so that it can also be used in open-domain QA settings through [Haystack](https://github.com/deepset-ai/haystack).

Just wondering why there's only a Slow Tokenizer implemented for DeBERTa and wondering if there are plans to create the Fast Tokenizer too. Thanks in advance!

Hi @stefan-it! Wondering if you might have any insight on this?

### PR DESCRIPTION
**Pull request by ShubhamSanghvi**
# What does this PR do?

Fixes #10498 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@LysandreJik

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
This is fantastic! Great job on the implementation @ShubhamSanghvi.

Do you want to take a look at it @BigBird01?

@ShubhamSanghvi, we're in the midst of making it easier to contribute fast tokenizers. Could you give us a bit of feedback on whether adding this tokenizer was simple or not, the pain points you've encountered?

**Review by LysandreJik — APPROVED** [review]

**Review by sgugger — APPROVED** [review]
Amazing! Thanks a lot for your work on this!

**Comment by ShubhamSanghvi** [comment]
@LysandreJik , most of it was easy to figure out by looking at other tokenizers. The setup and testing guidelines were very easy to follow, I was up and running very quickly.

For the fast tokenizers, few things that might help someone like me who is new to the transformers library:
1. A top-level difference between the fast and slow tokenizers. At first, I did not know there was a tokenization library and took some time to figure that out.
2. Overview of how we implement tokenizers. Things like what do the vocab files do and what does the merges_file do. (Although this could just be me.)
3. In some fast tokenizers, there are files listed which are not being used. That confused me initially as I thought we needed those files for a fast tokenizer.

Hope this helps.

**Comment by ShubhamSanghvi** [comment]
@LysandreJik, 

#10498 mentioned implementing a tokenizer for deberta v2 as well. I have created a new feature request #11529 for that.

**Comment by LysandreJik** [comment]
Thank you @ShubhamSanghvi, this is all very helpful. We'll take care of including that in the documentation so that it's clearer from now on.

Will take a look at #11529!

**Pull request merged**
