### PR TITLE
🐛  torch baddbmm error fixed for BigCode models

### PR DESCRIPTION
**Pull request by mayank31398**
Fixes # (issue)
This was needed because of a bug in pytorch https://github.com/pytorch/pytorch/issues/80588.
The bug was fixed in https://github.com/pytorch/pytorch/pull/96086

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

@ArthurZucker @younesbelkada @jlamypoirier

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks for the PR, the CI is failing with these proposed changes, for example the test below fails:
```
tests/models/gpt_bigcode/test_modeling_gpt_bigcode.py::GPTBigCodeMHAModelTest::test_training
```

What is the reason to call `.split` with `kv_dim` instead of `head_dim`? Reverting that logic should fix the failing CIs

**Review by younesbelkada — COMMENTED** [review]
Hi @mayank31398 
Thanks again, the CI is still failing for the same resons I have encountered in the past, I think we don't use PT>2.0.0 that includes the fix you mentioned above, there should be a reason for that. cc @ydshieh
If we need to stick to PT 2.0.0 for the CI, I don't think we can merge this PR until we upgrade the PT version of the CI

**Comment by ydshieh** [comment]
> I think we don't use PT>2.0.0 that includes the fix you mentioned above, there should be a reason for that. cc @ydshieh

You prediction is 200% correct: we have torch `2.0.1`. The mentioned torch fix is not included in that minor bug release.

**Comment by younesbelkada** [comment]
Ah I see thanks for double checking @ydshieh !

**Comment by mayank31398** [comment]
closing this since its not relevant at this point in time.

**Pull request closed without merging**
