### PR TITLE
[Fix]: Send model output to cpu before numpy cast in token_clf_pipeline

### LINKED ISSUE #13816: Device error on TokenClassificationPipeline
## Environment info

- `transformers` version: 4.11.0
- Platform: Linux-5.14.8-arch1-1-x86_64-with-arch
- Python version: 3.7.11
- PyTorch version (GPU?): 1.9.1+cu102 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: False

### Who can help

Library:
- pipelines: @LysandreJik

## Information

Model I am using (Bert, XLNet ...):

The problem arises when using:
* [X] the official example scripts: (give details below)

The tasks I am working on is:
* [X] an official GLUE/SQUaD task: (give the name)

## To reproduce

1. Create a `pipe = TokenClassificationPipeline(model=DistilBertForTokenClassification.from_pretrained("PATH"))`
2. Pipe some text in `pipe(["My",  "text", "tokens"])`
3. Get a `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

## Expected behavior
Be able to run the pipeline

The pipeline should bring data to gpu/cpu or model to gpu/cpu and vice versa. 

The traceback 

```shell
In .venv/lib/python3.7/site-packages/transformers/pipelines/token_classification.py:209 in _forward                                                                                
    206 │   │   if self.framework == "tf":                                                         
    207 │   │   │   outputs = self.model(model_inputs.data)[0][0].numpy()                          
    208 │   │   else:                                                                              
 ❱ 209 │   │   │   outputs = self.model(**model_inputs)[0][0].numpy()   <== HERE
    210 │   │   return {                                                                           
    211 │   │   │   "outputs": outputs,                                                            
    212 │   │   │   "special_tokens_mask": special_tokens_mask,                                    
```

Placing a `.cpu()` would solve the problem

Thanks in advance for any help
Have a wonderful day

### PR DESCRIPTION
**Pull request by ierezell**
# What does this PR do?

Fixes #13816

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? https://github.com/huggingface/transformers/issues/13816
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation). No docs changes
- [X] Did you write any new necessary tests? No additional test needed

## Who can review?
 If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.
 Please tag fewer than 3 people.

Library:

- pipelines: @LysandreJik

### CODE REVIEW

**Comment by Ierezell** [comment]
@Narsil  Do you want me to also add a test (all currents tests are passing) ?

in `tests/test_pipelines_token_classification.py` like : 
```python
@require_torch_gpu
@slow
def test_correct_devices(self):
    sentence = "This dummy sentence checks if all the variables can be loaded on gpu and bring back to cpu"
    ner = TokenClassificationPipeline(model="distilbert-base-cased", device=0)    
```

Have a great day

**Comment by Narsil** [comment]
Hi @Ierezell .

Unfortunately this fix is not desirable, as we're trying to have all "CPU/GPU" logic be contained inside the `Pipeline` class (in `src/transformers/pipelines/base.py`).

I added another proposed fix (the test is still not ran as part of the unit tests (it's still slow) pinging @LysandreJik for advice on if/how we can make GPU tests part of the unit tests.

**Comment by Ierezell** [comment]
HI @Narsil, indeed it seems better to handle all the logic in the same place. I should've checked before. 

I looked at your fix and it's perfect for me. 

For the test, unfortunately, even if it's only a really small computation, the test needs GPU... Is it this bad to have it only as CI/CD test and not as a unit test? 

Thanks for keeping me as coauthor. 

Have a great day!

**Comment by Narsil** [comment]
Making ALL pipeline tests GPU as unit regular tests is something that was already raised internally.

Currently pipeline tests are relatively fast, so it really is doable. Slow tests are run on every release + once a day if I am not mistaken so it's already something.

**Pull request closed without merging**
