### PR TITLE
Add language and license information to model cards

### PR DESCRIPTION
**Pull request by alexcombessie**
Should fix issues #3397 and #3357

### CODE REVIEW

**Comment by alexcombessie** [comment]
Hi @julien-c !

I hope you are well. My pull request is ready for review.

I have tried my best to add license and language information to all model cards. I have added a few model cards as well.

Note that my changes may have some downstream consequences:
- the addition of a "license" key, the value being an atomic list)
- the normalization of the "languages" key (I added the "s"), the value being a list of [ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). For multilingual BERT, I had to simplify some rare languages by merging it with its ISO "macro code" (example: "South Azerbaijani" -> "az", "Bavarian" -> "de")
 
On the website, you may want to read those values and render them back in human-readable form.

Cheers,

Alex

**Comment by julien-c** [comment]
Hi Alex,

as mentioned in the previous issue, I'd rather use identifiers listed in https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

I can probably search and replace though.

Also, you pushed whitespace changes which make reviewing the actual changes slightly tedious.

**Comment by alexcombessie** [comment]
Sure, I will replace licenses with these identifiers tomorrow! 
For whitespaces, I have autoformatting activated on sublime, that's why. Sorry for the inconvenience.

**Comment by alexcombessie** [comment]
Good morning @julien-c,

I hope all is well. What do you think of this PR?

Cheers,

Alex

**Comment by julien-c** [comment]
I'm doing a partial merge (retaining your authorship information, @alexcombessie) of the licenses, as the languages will require some backend changes.

(I'll do a search and replace at a later point)

Thank you for your contribution

**Pull request merged**
