### PR TITLE
[`Gemma2`] Support FA2 softcapping

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Adds support for the new FA2 softcapping following https://github.com/Dao-AILab/flash-attention/pull/1025

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
OK, looks good to me! 2.6.0 was released 3 hours ago, let's go

**Review by amyeroberts — APPROVED** [review]
LGTM - thanks for adding!

**Comment by ShadowTeamCN** [comment]
Good to see this. Can we use it for model fine-tuning, or is it just for inference? Google recommends fine-tuning in 'eager' mode.

**Comment by heartkilla** [comment]
Great! Any plans for sdpa support as well?

**Comment by ArthurZucker** [comment]
Sdpa is a bit more complicated, we need to use flex attention, did not have time to implement. Do you want to open a PR?

**Comment by hiyouga** [comment]
Hi @ArthurZucker, should we also add the sliding window and soft-capping in `flash_attn_func`
https://github.com/huggingface/transformers/blob/fc35907f95459d7a6c5281dfadd680b6f7b620e3/src/transformers/models/gemma2/modeling_gemma2.py#L466-L469
just like
https://github.com/huggingface/transformers/blob/fc35907f95459d7a6c5281dfadd680b6f7b620e3/src/transformers/models/mistral/modeling_mistral.py#L519-L528

**Comment by ArthurZucker** [comment]
It should be here on main: https://github.com/huggingface/transformers/blob/main/src/transformers/models/gemma2/modeling_gemma2.py#L361 we updated the whole FA2 integration

**Pull request merged**
