### PR TITLE
Add support for the null answer in `QuestionAnsweringPipeline`

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Nice to handle that. What do you think @mfuntowicz @thomwolf @julien-c ?

**Comment by mfuntowicz** [comment]
Hi @bryant1410, thanks for pushing this into the QA pipeline.

My only concern is about the name of the parameter `version_2_with_negative` introduced in this PR. It seems very tight up to SQuAD2 and might be hard for newcomers to directly understand what it does.

Would you mind changing the name of the parameter `version_2_with_negative` to `handle_impossible_answer` ?

**Comment by bryant1410** [comment]
Sure. Btw, is it okay for it to default to `False`?

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks @bryant1410

**Comment by mfuntowicz** [comment]
LGTM too, thanks @bryant1410

**Pull request merged**
