### PR TITLE
rename "gpu" --> "device"

### PR DESCRIPTION
**Pull request by yuchenlin**
# What does this PR do?

Rename the arg names from "per_gpu" to "per_device" such that it aligns with the instruction in the readme  https://github.com/huggingface/transformers/tree/master/examples/text-classification#xnli

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Comment by LysandreJik** [comment]
Could you run the code quality scripts for the code quality test? `make style && make quality`, after installing the latest code quality versions: `pip install -U .[quality]`

**Review by sgugger — APPROVED** [review]
Yes, it aligns it better with the other example scripts! Thanks!

**Comment by sgugger** [comment]
Looks like there is some styling issue. Could you run `make style` on your branch?

**Pull request closed without merging**
