### PR TITLE
fix backend tokenizer args override: key mismatch

### PR DESCRIPTION
**Pull request by theo-m**
# What does this PR do?

Related to #10390

Turns out it was a simple key mismatch - leaving as draft for now just to see the results of the full test suites, but hopeful this will fix the main problem for the related issue.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
Great, nice catch! Happy to see a tiny fix resolves the issue. 

Is that the only tokenizer that needs to be updated?

Tried it locally and it seems your fix solves the issue. The test is nice as well.

**Comment by theo-m** [comment]
I'm talking with @n1t0 soon to get a better sense of where it might make sense as well yes! Will update then

**Comment by theo-m** [comment]
went looking for similar case with this regex `(\[|\()"do_lower_case`, found only one more: 7e42461

I think this is it, will move onto #10121 once this is merged

**Review by LysandreJik — APPROVED** [review]
Great, thanks a lot @theo-m! Thanks for adding a test.

**Comment by LysandreJik** [comment]
There does seem to be an issue remaining though, as the tests in the suite currently fail with:
```
=========================== short test summary info ============================
FAILED tests/test_tokenization_auto.py::AutoTokenizerTest::test_do_lower_case
=== 1 failed, 5143 passed, 2103 skipped, 2207 warnings in 266.40s (0:04:26) ====
```

**Pull request merged**
