### PR TITLE
Adds failing tests for the fast tokenizers

### PR DESCRIPTION
**Pull request by dirkgr**
This ports some of the tests over that started failing on the AllenNLP side when the new fast tokenizers came out.

Note: These tests are failing right now. They will need updates to the fast transformers before this can be merged. Maybe it would be better to merge this branch into the branch where the tokenizers are being fixed?

### CODE REVIEW

**Comment by dirkgr** [comment]
I can't assign reviewers, but you asked me in #3058 to ping @LysandreJik and @mfuntowicz when I do this.

**Comment by dirkgr** [comment]
I added a test for the issue from #3088.

**Comment by dirkgr** [comment]
Added another test for #3091.

**Comment by mfuntowicz** [comment]
@dirkgr thanks for taking the time to include your tests into ours. 

It will definitively help making sure everything is working as expected on your side 👍

**Comment by julien-c** [comment]
This can be closed now, right?

**Pull request closed without merging**
