### PR TITLE
Deprecate unused OpenLlama architecture

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

# What does this PR do?
1. Deprecate `OpenLlama` following #24787.
2. Add a disclaimer pointing users to `LLaMA` for the [OpenLLaMA models](https://huggingface.co/models?search=openllama).
3. Resolve a typo in a warning in `check_repo.py`
4. Read modeling files with `encoding="utf8"` in `check_config_attributes_being_used`.

If preferred, I can revert 3 and 4 and cherry-pick them into a separate PR.
Follow-up of #24913. This is a considerably better solution - I feel a bit embarrassed I even considered the other one.

## Details
I've followed the steps that @sgugger seems to have taken from #24787 to move OpenLlama into deprecation. This involves moving the main code, adapting the `__init__` files, removing the tests, and updating the documentation with a disclaimer.

Feel free to let me know if you'd rather keep the model non-deprecated for the time being, and then I'll revert to only the addition of the disclaimer.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Discussed in #24913.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sgugger 

- Tom Aarsen

### CODE REVIEW

**Comment by tomaarsen** [comment]
> FAILED tests/test_modeling_utils.py::ModelPushToHubTester::test_push_to_hub - huggingface_hub.utils._errors.HfHubHTTPError: 500 Server Error: Internal Server Error for url: https://hub-ci.huggingface.co/api/repos/create

Test failure seems unrelated, I can push an empty commit or let you rerun them.

**Review by sgugger — APPROVED** [review]
Re-launched the tests to make sure it's just a fluke. Pinging the original author @s-JoL for information and to see if there is any plan on open-sourcing another checkpoint for this architecture?

**Comment by s-JoL** [comment]
> Re-launched the tests to make sure it's just a fluke. Pinging the original author @s-JoL for information and to see if there is any plan on open-sourcing another checkpoint for this architecture?

Due to various reasons, the previous open-source project has been shut down. Considering that there are more and more open-source models available now (including commercially available ones like Llama2), I believe that open-sourcing another similar model won't add much value to the community. Therefore, I think it's reasonable to mark this model as deprecated. However, I understand that some users are training with the Llama model that includes XFormers. Is it possible to add an optional XFormers acceleration in the Llama model to facilitate these users?

**Comment by sgugger** [comment]
We can see how to add an optional XFormers acceleration in Llama in other PRs, yes.

**Pull request merged**
