### PR TITLE
Adding doc page for the object detection task 

### PR DESCRIPTION
**Pull request by MKhalusova**
This is a PR for the https://github.com/huggingface/transformers/issues/20805  issue. 
The guide has content and working code examples for: 
- [x] Introduction  
- [x] Loading CPPE-5 dataset from Hub
- [x] Preprocessing both images and annotations. Images are augmented, annotations are reformatted to be in the format DETR expects
- [x] Training with `Trainer`
- [x] Evaluation
- [x] Inference

### CODE REVIEW

**Comment by MKhalusova** [comment]
If I missed someone who has to be invited as a reviewer, please feel free to add them.

**Comment by sayakpaul** [comment]
@MKhalusova thanks for doing this!

I think you can follow the instructions noted [here](https://github.com/huggingface/transformers/pull/16255#discussion_r830432539) to resolve the quality bug in the CI. Let me know if anything's unclear.

**Comment by MKhalusova** [comment]
Did a rebase in an attempt to fix the CI issue. Accidentally added a whole bunch of unrelated commits to the PR. Figuring out how to remove them.

**Comment by sayakpaul** [comment]
> Did a rebase in an attempt to fix the CI issue. Accidentally added a whole bunch of unrelated commits to the PR. Figuring out how to remove them.

You might want to revert to the previous commit. [This thread](https://stackoverflow.com/questions/4114095/how-do-i-revert-a-git-repository-to-a-previous-commit) might be helpful in that regard. And then from there:

* Create a separate Python virtual environment. 
* Make sure you're in the virtual environment you just created and then from the `transformers` directory root run `pip install -e .[quality]`.
* Now, once the dependencies have been installed to the new virtual environment, run `make style`. 

This should likely fix it. Since the code quality errors were previously coming from a doc page (c.f. https://app.circleci.com/pipelines/github/huggingface/transformers/54549/workflows/18b53122-1cc3-4c87-ad12-486853427500/jobs/657389), I suspect this to be stemming from the task page we're adding in this PR. 

Let me know if anything is unclear.

**Comment by MKhalusova** [comment]
Closing this due to messed up rebase. The new PR is now here https://github.com/huggingface/transformers/pull/20925

**Pull request closed without merging**
