### PR TITLE
Try Fix Mistral Compile on T4

### PR DESCRIPTION
**Pull request by zhenglongjiepheonix**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @ydshieh

**Comment by ydshieh** [comment]
Will check, but probably it's not ready yet.

**Comment by zhenglongjiepheonix** [comment]
> Will check, but probably it's not ready yet.

Yes, I think it's related to dynamo needing more memory when tuning parameters for kernels, and I think gpu memory might not release in time between tests, in colab T4 env sometimes it passes sometimes it fails, still trying to make it work under little memory budget on T4

**Comment by ydshieh** [comment]
A few things to share from my experience:

- run that single test to see if it ever fails
  - in this case, we don't have much choice. Two things could try:
    - reduce the input length and/or the generation length 
    - Try `run_test_in_subprocess`
    - Try the hack fix I added in https://github.com/huggingface/transformers/pull/31263/files (the `0,1,2,3` stuff)

**Comment by zhenglongjiepheonix** [comment]
> A few things to share from my experience:
> 
> * run that single test to see if it ever fails
>   
>   * in this case, we don't have much choice. We could could try:
>     
>     * reduce the input length and/or the generation length
>     * Try `run_test_in_subprocess`
>     * Try the hack fix I added in https://github.com/huggingface/transformers/pull/31263/files (the `0,1,2,3` stuff)
> 
> But feel free to try anything you can think of. Happy to know if there are new ways!

Yes, the single test alone can fail, and it would require about 14GB out of 15GB available total GPU memory on T4 to load the model and do inference even if we don't do compile, and reduce length won't help because the kv cache only takes a small part of the used memory

**Comment by ydshieh** [comment]
OK then. It's fine for me if we only run this on A10. We have a CI workflow will run it on A10

.github/workflows/push-important-models.yml

(But feel free if you still want to try anything when you have time)

**Pull request closed without merging**
