### PR TITLE
Fix minor bug to handle dynamic sequence length 

### PR DESCRIPTION
**Pull request by duyvuleo**
This PR is to fix a minor bug for handling dynamic sequence length, e.g., during building the serving model(s).

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hi! Could you run `make quality` at the root of your clone so that it passes the code quality test?

**Comment by duyvuleo** [comment]
@LysandreJik : I did run `make quality` but got the following error:

`(pyvenv3-transformers-forked) ➜  transformers git:(master-minor-fix-t5) make quality
black --check examples tests src utils
All done! ✨ 🍰 ✨
621 files would be left unchanged.
isort --check-only examples tests src utils
flake8 examples tests src utils
python utils/style_doc.py src/transformers docs/source --max_len 119 --check_only
/Library/Developer/CommandLineTools/usr/bin/make extra_quality_checks
/Users/PZ9DU5/vuh/tools/pyvenv3-transformers-forked/lib/python3.7/site-packages/setuptools/dist.py:454: UserWarning: Normalizing '4.0.0-rc-1' to '4.0.0rc1'
  warnings.warn(tmpl.format(**locals()))
running deps_table_update
updating src/transformers/dependency_versions_table.py
python utils/check_copies.py
python utils/check_dummies.py
python utils/check_repo.py
Checking all models are properly tested.
Checking all models are properly documented.
Checking all models are in at least one auto class.
Traceback (most recent call last):
  File "utils/check_repo.py", line 400, in <module>
    check_repo_quality()
  File "utils/check_repo.py", line 396, in check_repo_quality
    check_all_models_are_auto_configured()
  File "utils/check_repo.py", line 342, in check_all_models_are_auto_configured
    all_auto_models = get_all_auto_configured_models()
  File "utils/check_repo.py", line 316, in get_all_auto_configured_models
    for attr_name in dir(transformers.models.auto.modeling_auto):
AttributeError: module 'transformers.models.auto' has no attribute 'modeling_auto'
make[1]: *** [extra_quality_checks] Error 1
make: *** [quality] Error 2`

**Comment by rajveer43** [comment]
anoy nody working on htis?

**Comment by ArthurZucker** [comment]
Closing as this PR is super old

**Pull request closed without merging**
