### PR TITLE
Fix LR decay in TF Trainer

### PR DESCRIPTION
**Pull request by jplu**
Revival of #5051

I have accidentally deleted the previous branch so I recreated this same one.

### CODE REVIEW

**Comment by jplu** [comment]
@LysandreJik Sorry for the inconvenience :(

**Review by LysandreJik — APPROVED** [review]
No worries, looks good!

**Comment by LysandreJik** [comment]
Will merge once the code quality passes

**Comment by jplu** [comment]
All tests are ok!

**Pull request merged**
