### PR TITLE
OpenAI to HF: Add large-v3 to conversion script

### PR DESCRIPTION
**Pull request by jstoone**
# What does this PR do?
It adds the new large-v3 to the script which converts OpenAI model to HF.

The URL is copied from the PR releasing large-v3: https://github.com/openai/whisper/pull/1761

I can't find any tests related to the conversion script, so I've gone ahead and skipped that. Let me know, if I've missed something.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sanchit-gandhi Do you know what has changed, since the model checkpoint seems to be a byte array instead of a directory?

### CODE REVIEW

**Comment by jstoone** [comment]
I've converted PR to draft, as I'm currently getting the following exception:
```
Traceback (most recent call last):
  File "/Users/jstoone/Sites/huggingface/transformers/src/transformers/models/whisper/convert_openai_to_hf.py", line 185, in <module>
    convert_openai_whisper_to_tfms(args.checkpoint_path, args.pytorch_dump_folder_path)
  File "/Users/jstoone/Sites/huggingface/transformers/src/transformers/models/whisper/convert_openai_to_hf.py", line 137, in convert_openai_whisper_to_tfms
    dimensions = original_checkpoint["dims"]
                 ~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: byte indices must be integers or slices, not str
```

**Comment by amyeroberts** [comment]
Hi @jstoone, thanks for opening this PR and contributing to the library! 

There's some other PRs relating to this
* #26834
* #27336
* #27338 

I believe #26834 tackles the issue being seen here. As #27336 is a more complete update - handling the addition of cantonese - then that will be the PR to be merged in. 

cc @ArthurZucker for reference.

**Comment by jstoone** [comment]
@amyeroberts That's amazing! The community moves so darn fast, it's amazing to see. I'll go ahead and close this one then. Thanks!

**Comment by gerrynjenny** [comment]
> As https://github.com/huggingface/transformers/pull/27336 is a more complete update - handling the addition of cantonese - then that will be the PR to be merged in.

Maybe I'm not understanding you, but the PR appears to only remove mention of Cantonese

**Comment by amyeroberts** [comment]
@gerrynjenny The diff in the [open PR](https://github.com/huggingface/transformers/pull/27336) remove instructions in the docs mentioning that you have to specify 100 languages. This is because it's now inferred from the checkpoint when converting. The PR previously included logic which added cantonese as a language in the tokenizer mapping. However that has already been merged in with #27338

**Pull request closed without merging**
