### PR TITLE
Add `LayoutXLMTokenizer` and `LayoutXLMTokenizerFast`

### LINKED ISSUE #13972: LayoutLMv2Processor does not accept the XLMRobertaTokenizerFast
## Environment info

- `transformers` version: 4.11.3
- Platform: Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.2.5
- Python version: 3.8.12
- PyTorch version (GPU?): 1.9.1+cu102 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
@NielsRogge

## Information

Model I am using: LayoutXLM

The problem arises when using:
* [x] the official example scripts: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/RVL-CDIP/Fine_tuning_LayoutLMv2ForSequenceClassification_on_RVL_CDIP.ipynb

The tasks I am working on is:
* [x] an official task: SequenceClassification

## To reproduce

When we replace the layoutlmv2 tokenizer in cell 8 of https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/RVL-CDIP/Fine_tuning_LayoutLMv2ForSequenceClassification_on_RVL_CDIP.ipynb
```python
from transformers import LayoutLMv2FeatureExtractor, LayoutLMv2Tokenizer, LayoutLMv2Processor
feature_extractor = LayoutLMv2FeatureExtractor()
tokenizer = LayoutLMv2Tokenizer.from_pretrained("microsoft/layoutlmv2-base-uncased")
processor = LayoutLMv2Processor(feature_extractor, tokenizer)
```
with the layoutxlm tokenizer as described in https://huggingface.co/transformers/model_doc/layoutxlm.html

```python
from transformers import LayoutLMv2FeatureExtractor, LayoutLMv2Tokenizer, LayoutLMv2Processor, AutoTokenizer
feature_extractor = LayoutLMv2FeatureExtractor()
tokenizer = AutoTokenizer.from_pretrained('microsoft/layoutxlm-base')
processor = LayoutLMv2Processor(feature_extractor, tokenizer)
```

the following error occurs
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_3433/3030379235.py in <module>
      5 tokenizer = AutoTokenizer.from_pretrained('microsoft/layoutxlm-base')
      6 #tokenizer = LayoutLMv2Tokenizer.from_pretrained("microsoft/layoutlmv2-base-uncased")
----> 7 processor = LayoutLMv2Processor(feature_extractor, tokenizer)

~/.cache/pypoetry/virtualenvs/stp-experiment0-RgVp7VCN-py3.8/lib/python3.8/site-packages/transformers/models/layoutlmv2/processing_layoutlmv2.py in __init__(self, feature_extractor, tokenizer)
     54             )
     55         if not isinstance(tokenizer, (LayoutLMv2Tokenizer, LayoutLMv2TokenizerFast)):
---> 56             raise ValueError(
     57                 f"`tokenizer` has to be of type {LayoutLMv2Tokenizer.__class__} or {LayoutLMv2TokenizerFast.__class__}, but is {type(tokenizer)}"
     58             )

ValueError: `tokenizer` has to be of type <class 'type'> or <class 'type'>, but is <class 'transformers.models.xlm_roberta.tokenization_xlm_roberta_fast.XLMRobertaTokenizerFast'>
```

It looks like the LayoutLMv2Processor does not accept the XLMRobertaTokenizerFast.

## Expected behavior

That the LayoutLMv2Processor accepts the XLMRobertaTokenizerFast.

### PR DESCRIPTION
**Pull request by kingyiusuen**
# What does this PR do?

Fixes #13972 (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by NielsRogge** [comment]
> The tokenizer in 'microsoft/layoutxlm-base' was registered with XLMRobertaTokenizer, so the user will get a warning

Yeah, that's because the config currently has an attribute `tokenizer_class` which is set to `XLMRobertaTokenizer` as can be seen [here](https://huggingface.co/microsoft/layoutxlm-base/blob/main/config.json). Once LayoutXLMTokenizer/LayoutXLMTokenizerFast are ready, we will upload the vocab files to the model repo, and remove the `tokenizer_class` attribute.

**Comment by kingyiusuen** [comment]
> > The tokenizer in 'microsoft/layoutxlm-base' was registered with XLMRobertaTokenizer, so the user will get a warning
> 
> Yeah, that's because the config currently has an attribute `tokenizer_class` which is set to `XLMRobertaTokenizer` as can be seen [here](https://huggingface.co/microsoft/layoutxlm-base/blob/main/config.json). Once `LayoutXLMTokenizer`/`LayoutXLMTokenizerFast` are ready, we will upload the vocab files to the model repo, and remove the `tokenizer_class` attribute.

Got it. I just have a failing test and a docstring error in the CI. Any advice on how to fix them?

**Comment by NielsRogge** [comment]
Ok, I'll take a look later today.

**Comment by kingyiusuen** [comment]
> I've made all necessary changes, fixed all tests, implemented a new `LayoutXLMProcessor` and created new tests for it accordingly.
> 
> You can find my branch here: https://github.com/NielsRogge/transformers/tree/add-layoutxlm-fast-tokenizer
> 
> Should I open a PR on your branch? Or should I directly open a PR to HuggingFace Transformers?

Maybe you should directly open a PR to HuggingFace Transformers. You've done most of the heavy-lifting. This should be counted as your contribution. 😃

**Pull request closed without merging**
