### PR TITLE
fix(DPT,Depth-Anything) Address expected_slice errors inside inference tests

### PR DESCRIPTION
**Pull request by philkuz**
# What does this PR do?
Fixes slow tests that are broken in main and discovered in this PR: https://github.com/huggingface/transformers/pull/34103

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@qubvel

### CODE REVIEW

**Comment by qubvel** [comment]
@philkuz  run-slow commit should be after the run-slow label is added, can you please push it once again?

**Review by qubvel — APPROVED** [review]
Thanks for the fix! The tests are green now!
cc @ydshieh for tests change

**Comment by ydshieh** [comment]
Yes, great!

(And thank you for requesting/triggering the slow tests!)

**Review by ydshieh — APPROVED** [review]

**Comment by philkuz** [comment]
Thanks all!!

**Pull request merged**
