### PR TITLE
[i18n-de] Translate README.md to German

### PR DESCRIPTION
**Pull request by khipp**
# What does this PR do?

This PR adds a German translation for the README.md.
The text is written in accordance with the [translation guidelines](https://github.com/huggingface/course/blob/main/chapters/de/TRANSLATING.txt) of the German Hugging Face course, and translations for technical terms are taken from the corresponding [glossary](https://huggingface.co/learn/nlp-course/de/glossary/1).

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Documentation: @stevhliu

### CODE REVIEW

**Review by stevhliu — COMMENTED** [review]
Structure and format LGTM! I don't speak German though so I can't review the content. 😅 

Do you know of any German speakers in the ML community who would be interested in contributing and reviewing your translation?

**Comment by khipp** [comment]
I don't know anyone in particular, I'm afraid.

Maybe @flozi00 can help me since he contributed to the existing German translations? :grin:

**Comment by flozi00** [comment]
I remember for an discussion about the form if we should "du" or "sie"
Last time the hugging face team decided for the more formulary "sie"

The rest LGTM

**Comment by khipp** [comment]
Thanks, I will update the translation accordingly.

It seems that the German translation for the Hugging Face Hub also uses the formal 'Sie', while the Hugging Face NLP Course is the outlier here.

**Review by flozi00 — APPROVED** [review]
LGTM

**Review by stevhliu — APPROVED** [review]
Thanks for the review @flozi00 and thanks again for the contribution @khipp!

**Pull request merged**
