### PR TITLE
add no split modules for xlmrobertaxl

### PR DESCRIPTION
**Pull request by ManuelFay**
# What does this PR do?

Enables loading XLMRobertaWL with the device map for multiGPU training.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@younesbelkada

### CODE REVIEW

**Comment by ManuelFay** [comment]
Follows the same no_split_modules than the XLMRoberta model

**Review by younesbelkada — COMMENTED** [review]
Thank you for this ! Can you confirm `accelerate` tests pass ?
```bash
RUN_SLOW=1 pytest tests/models/xlm_roberta/test_modeling_xlm_roberta.py
```

**Comment by ManuelFay** [comment]
It skips both tests but no fails at least.

**Review by younesbelkada — APPROVED** [review]
Thanks ! It should be all good as it uses same logic as XLM Roberta !

**Review by amyeroberts — APPROVED** [review]
Thanks for adding this capability to this model!

**Pull request merged**
