### PR TITLE
Add text_column_name and label_column_name to run_ner and run_ner_no_trainer args

### PR DESCRIPTION
**Pull request by kumapo**
# What does this PR do?

it's nice to enable to specify which columns are for `text` and `label` for run_ner with its arguments.
especially it's useful when we train it on not csv (i.e. json) dataset because `text` and `label` columns are determined by column order if default columns are missing.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

```
% python -m pytest -n auto --dist=loadfile -s -v ./examples/
...
Results (1653.79s):
      18 passed
       3 skipped
```

## Who can review?

- maintained examples (not research project or legacy): @sgugger, @patil-suraj

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for the PR, it's a good idea! I think we can make it a bit more robust however, I left suggestions.

**Comment by kumapo** [comment]
@sgugger thank you for your suggestions! 
I've pushed a commit based on it.

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Comment by kumapo** [comment]
I'm appreciated for your fix too!

**Pull request merged**
