### PR TITLE
Revert "[WIP] Hard error when ignoring tensors."

### PR DESCRIPTION
**Pull request by ydshieh**
Reverts huggingface/transformers#27484

Causing failing in TF/Flax vs torch equivalence tests

https://app.circleci.com/pipelines/github/huggingface/transformers/83829/workflows/a864e1cf-46bc-4643-9a2f-9ba65ee7074e

### CODE REVIEW

**Comment by ydshieh** [comment]
The failing will disappear after the unpin torch PR is merged

**Review by amyeroberts — APPROVED** [review]
Thanks for opening this!

**Comment by ydshieh** [comment]
cc @Narsil and @ArthurZucker for visibility 

Going to merge to keep CI green

**Comment by ydshieh** [comment]
> Just FMI who will take over the PR again?

I assume it would be @Narsil ...?

**Pull request merged**
