### PR TITLE
Update conditional logic and -> or in SAM postprocessing

### PR DESCRIPTION
**Pull request by hwuebben**
should be ors here

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks for the PR, I think that it should be as it is, `input_points`, `input_labels` and `input_boxes` are expected to be a list of lists (or a list of lists of lists), hence the `and` condition

**Comment by hwuebben** [comment]
@younesbelkada exactly but with the current implementation it could also be a list of arrays and the exception would not be thrown

**Review by younesbelkada — APPROVED** [review]
Ah yes, you are right, that sounds correct to me! Thanks for the heads up

**Review by amyeroberts — APPROVED** [review]
Thanks for the fix!

**Comment by ydshieh** [comment]
FYI, this PR triggered 3 test failures on the CI.

(The third one is GPU OOM, which is likely caused by the other 2 failures).

cc @younesbelkada 


```bash
tests/models/sam/test_modeling_sam.py::SamModelIntegrationTest::test_inference_mask_generation_one_point_one_bb
(line 235)  ValueError: Input boxes must be a list of list of list of floating integers.
tests/models/sam/test_modeling_sam.py::SamModelIntegrationTest::test_inference_mask_generation_one_point_one_bb_zero
(line 235)  ValueError: Input boxes must be a list of list of list of floating integers.
tests/models/sam/test_modeling_sam.py::SamModelIntegrationTest::test_inference_mask_generation_two_points_batched
(line 808)  torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 GiB (GPU 0; 14.76 GiB total capacity; 11.65 GiB already allocated; 792.75 MiB free; 12.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by younesbelkada** [comment]
Hi @karthikdatta98 
thanks for reporting, in https://github.com/huggingface/notebooks/pull/409 I modified the notebook accordingly to show how to correctly pass bounding boxes

**Pull request merged**
