### PR TITLE
Support custom scheduler in deepspeed training

### PR DESCRIPTION
**Pull request by VeryLazyBoy**
# What does this PR do?

PR https://github.com/huggingface/transformers/pull/25863 adds support for using HF built-in scheduler with deepspeed optimizer. This PR goes a step further by enabling users to use custom schedulers with deepspeed optimizer. It achieves this by utilizing the `trainer.create_scheduler` function in the deepspeed setup, allowing users to override it and create their own custom scheduler

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@muellerzr and @pacman100

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by muellerzr** [comment]
cc @pacman100

**Comment by muellerzr** [comment]
cc @pacman100

**Comment by ArthurZucker** [comment]
gently pinging @pacman100

**Review by pacman100 — APPROVED** [review]
Hello @VeryLazyBoy, thank you for these changes, make sense. I also quickly ran all the deepspeed tests and they are passing, LGTM! 🤗

**Review by ArthurZucker — APPROVED** [review]
Thanks you and sorry for the long delay 🤗

**Comment by ArthurZucker** [comment]
Could you just rebase on main to make sure the latest changes (to the CIs) are incorporated!

**Comment by VeryLazyBoy** [comment]
Thank you all for the reivew! Hi @ArthurZucker , I have rebased my code on the lasted main branch.

**Comment by ArthurZucker** [comment]
Hey @VeryLazyBoy sorry I think we forgot to merge it 😢 Thanks for this!

**Pull request merged**
