### PR TITLE
Added clefourrier as ref point for graph models in bug reports

### PR DESCRIPTION
**Pull request by clefourrier**
# What does this PR do?
Added myself as entry point for graph models in issue doc.

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thanks. Is any reason you don't add this in `.github/ISSUE_TEMPLATE/feature-request.yml`?

**Comment by ydshieh** [comment]
Also, I missed this file
```
.github/PULL_REQUEST_TEMPLATE.md
```
if you think it is relevant.

**Comment by ydshieh** [comment]
Add @sgugger as I never changed these files before, and this is also more administrative decision :-)

**Comment by clefourrier** [comment]
My bad, did not see the comments in these files when I opened them in browser edit - will edit them!

**Comment by ydshieh** [comment]
> Did not see the comment section in PULL_REQUEST_TEMPLATE when I opened them in browser view - edited!
> 
> Edit: However, not sure what I could add to `feature-request`?

My bad, my brain is not completed recovered with all the `drink` I had last week.

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
