### PR TITLE
[PEFT] Better Trainer error when prompt learning with loading best model at the end

### PR DESCRIPTION
**Pull request by BenjaminBossan**
# What does this PR do?

Original issue: https://github.com/huggingface/peft/issues/2256

There is a potential error when using load_best_model_at_end=True with a prompt learning PEFT method. This is because Trainer uses `load_adapter` under the hood but with some prompt learning methods, there is an optimization on the saved model to remove parameters that are not required for inference, which in turn requires a change to the model architecture. This is why `load_adapter` will fail in such cases and users should instead set `load_best_model_at_end=False` and use `PeftModel.from_pretrained`. As this is not obvious, we now intercept the error and add a helpful error message.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

### CODE REVIEW

**Comment by BenjaminBossan** [comment]
@ArthurZucker Please review or suggest a reviewer.

**Comment by BenjaminBossan** [comment]
@Rocketknight1 Do you know who could best review this PR?

**Comment by Rocketknight1** [comment]
Sounds like a job for @muellerzr @SunMarc !

**Review by muellerzr — APPROVED** [review]
Nice error :)

**Pull request merged**
