### PR TITLE
Update text-to-speech.md

### PR DESCRIPTION
**Pull request by jaguaryang**
SpeechBrain usage has changed

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @ylacombe

**Review by ylacombe — APPROVED** [review]
Hey @jaguaryang, thanks for the fix!

According to [SpeechBrain docs](https://speechbrain.readthedocs.io/en/latest/API/speechbrain.inference.classifiers.html#speechbrain.inference.classifiers.EncoderClassifier), this is indeed the new way to import the `EncoderClassifier`!

The rest of the code should still work, notably the `save_dir` and the [run_opt](https://github.com/speechbrain/speechbrain/blob/1bd75e4b5e10e0d45bcf06f9b9b4564341530dbe/speechbrain/inference/interfaces.py#L177) arguments passed to the `EncoderClassifier`.

 This looks great to me @jaguaryang ! but could you run the snippet just to make sure it's working as expected?

**Comment by jaguaryang** [comment]
Hi @ylacombe, sure, I have of course tested it successfully before I commit and create pull request. This doc worked now.

**Review by amyeroberts — APPROVED** [review]
Thanks for updating!

**Pull request merged**
