### PR TITLE
[Bart] fix slow bart mask-infilling tests

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

Fixes slow tests GPU Bart: https://github.com/huggingface/transformers/runs/3577103064?check_suite_focus=true#step:7:25556

```
tests/test_modeling_bart.py::BartModelIntegrationTests::test_base_mask_filling
tests/test_modeling_bart.py::BartModelIntegrationTests::test_large_mask_filling
```

cc @Narsil guess the output format has slightly changed? 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Narsil** [comment]
Seems odd that the output type has changed, it shouldn't have changed. The PR refactor was supossed to be with zero regression. 

I had no idea that there were tests of pipelines on GPU outside the test_pipelines_* location.

**Comment by Narsil** [comment]
I think it's because we didn't have a test for single item list before, hence the backward incompatiblity, we need to override the `__call__` method of the `fill-mask` pipeline instead to behave oddly (as it was before)


Can we add other tests here too for GPU I think it's great to have performance checks.

Also the pipeline tests do not allow for GPU setting (anymore, and only some seem to have had the option), so that might explain it.

**Comment by patrickvonplaten** [comment]
@Narsil - I don't follow here 100%. The tests were not just failing on GPU but also on CPU. What additional tests for pipelines should we add in your opinion exactly and where? 

IMO, we should **not** continue the practice of adding pipeline tests in model testing files such as `test_modeling_bart.py` (it's a very old test if I remember correctly). We could add more slow tests to the individual task specific tests, such as `test_pipelines_fill_mask.py`, but I think it'd be better to do this is a future PR.

**Comment by Narsil** [comment]
Superseeded by : https://github.com/huggingface/transformers/pull/13540

**Pull request closed without merging**
