### PR TITLE
Fix ViT-MAE decoder interpolate

### LINKED ISSUE #32410: Potential error in num_patches calculation in src/transformers/models/vit_mae/modeling_vit_mae.py
### System Info

I've been examining the `interpolate_pos_encoding` method in the ViTMAE implementation, and I've discovered what appears to be an error in the calculation of `num_patches`. This error seems to have unintended consequences on the method's behavior especially when the input image has the same size as the pretrained image. Here are my findings: 
1. Current implementation: 
```
def interpolate_pos_encoding(self, embeddings: torch.Tensor, height: int, width: int) -> torch.Tensor:
    num_patches = embeddings.shape[1] - 1
    num_positions = self.position_embeddings.shape[1] - 1
    
    if num_patches == num_positions and height == width:
        return self.position_embeddings
    # ... rest of the method
```

2. Issue with `num_patches` calculation:
- The embeddings passed to this method are created in `ViTMAEPatchEmbeddings.forward()`, 
`x = self.projection(pixel_values).flatten(2).transpose(1, 2)`
- For a 224x224 input image (same as pretrained size), x.shape is torch.Size([1, 196, 768]). This 196 represents the number of patches (14*14) **without including a CLS token**.
- For another higher resolution input image: 480x640:
`embeddings.shape` = [1, 1200, 768]. 
Current: `num_patches` = 1200 - 1 = 1199 which shouldn't be the case, since the n`um_patches` should be 30*40 = 1200. 

3. Consequences of the error:
- I suppose in the current implementation, `num_patches = embeddings.shape[1] - 1` the -1 is for removing the cls token?
- With `num_patches = embeddings.shape[1] - 1`, we get `num_patches` = 196 - 1 = 195.
- However, num_positions = self.position_embeddings.shape[1] - 1 = 197 - 1 = 196.
- This causes `num_patches != num_positions`, even when using the pre-trained image size.

4. Unintended behavior:
- Due to this discrepancy, the condition `num_patches == num_positions and height == width` is never true.
- As a result, the method never returns `self.position_embeddings` directly, even when it should (i.e., when the input image size matches the pretrained size).
- This forces unnecessary interpolation even when `interpolate_pos_encoding = True` and the image size matches the pretrained size.

6. Proposed fix:
Change `num_patches = embeddings.shape[1] - 1` to `num_patches = embeddings.shape[1]`

Can you confirm that this is indeed an error in the implementation? Are there any considerations I might be missing? Thank you for your time and for maintaining this amazing project!

### Who can help?

_No response_

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
def interpolate_pos_encoding(self, embeddings: torch.Tensor, height: int, width: int) -> torch.Tensor:
    **num_patches = embeddings.shape[1] - 1**
    num_positions = self.position_embeddings.shape[1] - 1
    
    if num_patches == num_positions and height == width:
        return self.position_embeddings
    # ... rest of the method
```

### Expected behavior

```
def interpolate_pos_encoding(self, embeddings: torch.Tensor, height: int, width: int) -> torch.Tensor:
    **num_patches = embeddings.shape[1]**
    num_positions = self.position_embeddings.shape[1] - 1
    
    if num_patches == num_positions and height == width:
        return self.position_embeddings
    # ... rest of the method
```

### PR DESCRIPTION
**Pull request by xenova**
# What does this PR do?
Similar to #33226, with a fix for the ViT-MAE decoder (see [comment](https://github.com/huggingface/transformers/issues/32410#issuecomment-2293359788)).

Fixes #32410

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@amyeroberts

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Thanks for another speedy and clean fix!

**Review by amyeroberts — APPROVED** [review]

**Comment by xenova** [comment]
I'll add a unit test and then merge 👍

**Comment by xenova** [comment]
Apologies for the delay - totally forgot about this! 😅 

Before:
```
FAILED tests/models/vit_mae/test_modeling_vit_mae.py::ViTMAEModelIntegrationTest::test_inference_interpolate_pos_encoding_custom_sizes - RuntimeError: The size of tensor a (257) must match the size of tensor b (256) at non-singleton dimension 1
```

After:
```
34 passed, 114 skipped, 4 warnings in 8.80s
```

---

@amyeroberts can we trigger slow tests and then I'll merge? :) Thanks!

**Review by amyeroberts — APPROVED** [review]
Looks great - thanks!

**Pull request merged**
