### PR TITLE
Extend Transformers Trainer Class to Enable XPU 

### PR DESCRIPTION
**Pull request by mingxiaoh**
Rename GPU utils to CUDA
Add XPU backend
Doc on XPU backend

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks for your PR, but we are not going to rename core utils like this.

**Comment by mingxiaoh** [comment]
> Thanks for your PR, but we are not going to rename core utils like this.

thanks for the review, if so, I just roll back the rename.

**Comment by mingxiaoh** [comment]
@sgugger  May you please help review it again? thanks.

**Comment by sgugger** [comment]
Thanks for your PR. We can leave this branch as is for people who want to use XPUs but:
1. We do not have the ability to test them, so cannot commit to maintain this yet.
2. The Trainer will be rewritten to use Accelerate very soon, so the support should be added in Accelerate (I believe there is already a PR open) and then will come in the Trainer for free.

**Comment by mingxiaoh** [comment]
> Thanks for your PR. We can leave this branch as is for people who want to use XPUs but:
> 
> 1. We do not have the ability to test them, so cannot commit to maintain this yet.
> 2. The Trainer will be rewritten to use Accelerate very soon, so the support should be added in Accelerate (I believe there is already a PR open) and then will come in the Trainer for free.

Yes, my colleague is working with me preparing the PR for accelerate now. But, we still would like to merge this change into transformer since intel-extension-for-pytorch cpu backend is already in transformer.

**Comment by mingxiaoh** [comment]
@sgugger sorry for being push, but your reply is quite important to us, thanks in advance.

**Comment by mingxiaoh** [comment]
@sgugger  we are investigating how to provide solution for xpu now, another PR is in https://github.com/huggingface/accelerate/pull/1118, detailed info about how  transformer depend on accelerate is important to us, may you please take time to explain it to us? Thanks in advance.

**Comment by mingxiaoh** [comment]
hello, @sgugger  
May you please take some time to help explain this issue? Thanks in advance.
I found that transormers Trainer is using Accelerate now, is it the final solution? Why I ask so is because I found that, currently, if a model is wrapped by transformers trainer(e.g., IPEX CPU), it won't use accelerate to prepare model(see https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L1757-L1760), which means, for IPEX cpu, it won't use accelerate to prepare model, for IPEX xpu, it will use accelerate to prepare model, this might make users confused. Besides, for accelerate, it could not tell whether it is inference mode or training mode, currently, in accelerate, IPEX xpu always assumes it is training mode and wrap model into training mode, in this case, we could not run transformers in inference mode for IPEX xpu, any comments for this issue?

**Comment by mingxiaoh** [comment]
@pacman100  my colleague told me that you are the owner of integration of traniner & accelerate, if it is not too trouble, may you please take time to help explain it a little bit for us? Thanks.

**Comment by pacman100** [comment]
Hello @mingxiaoh, we are still in the process of migration. The next steps would involve shifting to Accelerate for ipex and adding the functionality in Accelerate if it isn't available there yet. Gentle ping @muellerzr who will be looking into this.

**Comment by mingxiaoh** [comment]
@pacman100  hello, may I know the the process of migration? Intel would like to extend it to xpu asap for customers' usge. Thanks in advance.

**Comment by muellerzr** [comment]
@mingxiaoh XPU support is currently happen due to efforts of @abhilash1910 and @sywangyi. It was in the last Accelerate release, so from here we need to look at the specific DDP efforts the Trainer has that need to be handled with XPU specific support. (v 0.20.0). Related PR here: https://github.com/huggingface/accelerate/pull/1118

**Comment by mingxiaoh** [comment]
@muellerzr Thanks, I know https://github.com/huggingface/accelerate/pull/1118 and xpu is supported in accelerate, we were working together for it before. But the issue is, we would like to know how the process of migration, in accelerate currently, inference is not supported on xpu, but for transformers, we must consider inference case. So, may I know the process of migration? we were told there is some problem about one month ago.

**Pull request closed without merging**
