### PR TITLE
Fix v2 model loading issue

### PR DESCRIPTION
**Pull request by BigBird01**
# What does this PR do?
Fix few issues with loading deberta v2 models and deberta mnli fine-tuned model

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hi @BigBird01, thanks a lot for fixing these issues! I'd like to prevent as much as possible from having the `pre_load_hooks` in the code. When do you expect mismatched head dimensions?

**Comment by BigBird01** [comment]
This is the case that if we want to fine-tune a task based on mnli models, e.g. MRPC, SST, QNLI. If we want to avoid this method, we need to fix the error reporting when load pretrained models.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LysandreJik** [comment]
Usually we recommend to load through the base model to lose the head:

```py
from transformers import DebertaV2Model, DebertaV2ForSequenceClassification

seq_model = DebertaV2ForSequenceClassification.from_pretrained("xxx", num_labels=4)
seq_model.save_pretrained(directory)

base = DebertaV2Model.from_pretrained(directory)  # Lose the head

seq_model = DebertaV2ForSequenceClassification.from_pretrained(directory, num_labels=8)
```

Does that work in your case? I agree you're touching to something that has a bad API, and this should be handled in the `from_pretrained` method. I don't think we should handle it model-wise, however. I'll look into it soon.

**Comment by BigBird01** [comment]
yes. but this looks a little bit tricky. And need to modify existing text classification code to benefit from mnli fine-tuned models. How about we keep current hook method, and finish current PR? After we work out a systematic solution for such scenario, we can drop the hook method.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by LysandreJik** [comment]
Ok, will merge like that and we'll discuss with other team members for the main PR. Thanks!

**Pull request merged**
