### PR TITLE
🌐 [i18n-KO] Fix anchor links for docs `auto_tutorial`, `training`

### PR DESCRIPTION
**Pull request by gabrielwithappy**
# What does this PR do?

Fixed anchor links for `auto_tutorial` and `training` docs
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
Team PseudoLab, may you please review this PR?
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

@sgugger, @ArthurZucker, @eunseojo May you please review this PR?

### CODE REVIEW

**Comment by gabrielwithappy** [comment]
Team PseudoLab, may you please review this PR?
@0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd

I fixed anchor links for my documents.

**Review by wonhyeongseo — APPROVED** [review]
LGTM

**Review by 0525hhgus — APPROVED** [review]
Perfect! It works well 😀

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Pull request merged**
