### PR TITLE
fix: GPTNeoX half inference error

### PR DESCRIPTION
**Pull request by SeongBeomLEE**
norm_factor is still torch.float32 after using model.half

So I changed it to register_buffer so I can change it to torch.float16 after using model.half

This error does not occur in all cases, but it does happen occasionally. 

Thanks!

Error Message:
```
File "/data2/sblee/anaconda3/lib/python3.9/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py", line 206, in _attn
attn_scores = torch.baddbmm(
RuntimeError: expected scalar type Half but found Float
```

Error Code:
```
attn_scores = torch.baddbmm(
            attn_scores,
            query,
            key.transpose(1, 2),
            beta=1.0,
            alpha=(torch.tensor(1.0, dtype=self.norm_factor.dtype, device=self.norm_factor.device) / self.norm_factor),
        )
```

before Code:
```
class GPTNeoXAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.num_attention_heads = config.num_attention_heads
        self.hidden_size = config.hidden_size
        self.head_size = self.hidden_size // self.num_attention_heads
        self.rotary_ndims = int(self.head_size * config.rotary_pct)
        max_positions = config.max_position_embeddings
        self.register_buffer(
            "bias",
            torch.tril(torch.ones((max_positions, max_positions), dtype=torch.bool)).view(
                1, 1, max_positions, max_positions
            ),
        )
        self.register_buffer("masked_bias", torch.tensor(-1e9))
        self.rotary_emb = RotaryEmbedding(
            self.rotary_ndims, config.max_position_embeddings, base=config.rotary_emb_base
        )
        self.norm_factor = torch.sqrt(torch.tensor(self.head_size, dtype=torch.float32)).to(torch.get_default_dtype())
        self.query_key_value = nn.Linear(config.hidden_size, 3 * config.hidden_size)
        self.dense = nn.Linear(config.hidden_size, config.hidden_size)
```

after Code:
```
class GPTNeoXAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.num_attention_heads = config.num_attention_heads
        self.hidden_size = config.hidden_size
        self.head_size = self.hidden_size // self.num_attention_heads
        self.rotary_ndims = int(self.head_size * config.rotary_pct)
        max_positions = config.max_position_embeddings
        self.register_buffer(
            "bias",
            torch.tril(torch.ones((max_positions, max_positions), dtype=torch.bool)).view(
                1, 1, max_positions, max_positions
            ),
        )
        self.register_buffer("masked_bias", torch.tensor(-1e9))
        self.rotary_emb = RotaryEmbedding(
            self.rotary_ndims, config.max_position_embeddings, base=config.rotary_emb_base
        )
        self.register_buffer("norm_factor", torch.sqrt(torch.tensor(self.head_size, dtype=torch.float32)).to(torch.get_default_dtype()))
        self.query_key_value = nn.Linear(config.hidden_size, 3 * config.hidden_size)
        self.dense = nn.Linear(config.hidden_size, config.hidden_size)

```

before:
```
model = GPTNeoXForCausalLM.from_pretrained(F_MODEL_PATH, config=model_config)
model.half()
model.to("cuda")
model.gpt_neox.layers[0].attention.norm_factor.dtype

output: torch.float32
```

after:
```
model = GPTNeoXForCausalLM.from_pretrained(F_MODEL_PATH, config=model_config)
model.half()
model.to("cuda")
model.gpt_neox.layers[0].attention.norm_factor.dtype

output: torch.float16
```

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Hi @SeongBeomLEE 
Thanks for your PR! 
I think the canonical way of loading models in half precision on `transformers` is to call `from_pretrained` with `torch_dtype`
```python
model = AutoModelForCausalLM.from_pretrained(xxx, torch_dtype=torch.float16)
```
Can you try with this option and let us know if it works?

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for double checking, I am not sure about that as I think the canonical way to load models in half precision is to use `torch_dtype`. Also here as you are registering a new buffer it might break loading the model with `accelerate` as it can hit some corner cases (not sure though). So I would say to stay on the safe side better to educate users on how to load properly the model in half precision 
I am not sure though, I would love to hear what @sgugger & @amyeroberts will say here, to see if we are aligned on this or not!

**Comment by sgugger** [comment]
The canonical way is indeed to use `torch_dtype=torch.float16` as it saves a lot of memory (otherwise you instantiate your model in float32 so take a lot of space, then convert it to half). But `model.half()` should work nethertheless. Using a buffer seems like a good solution, but make it non-persistent so it doesn't get inside the `state_dict` (with `persistent=False`).

**Comment by SeongBeomLEE** [comment]
Added a variable "persistent=False"

Thanks!

**Review by sgugger — APPROVED** [review]
Thanks a lot! Can you jsut run `make style` on your branch to fix the quality issue?

**Comment by SeongBeomLEE** [comment]
Of course. Thanks!

**Comment by sgugger** [comment]
Failure of the FLax test is unrelated and already fixed on main, so merging!

**Pull request merged**
