### PR TITLE
[`Vilt`] align input and model dtype in the ViltPatchEmbeddings forward pass 

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?
Just like the case in [BlipVisionEmbeddings](https://github.com/huggingface/transformers/blob/main/src/transformers/models/blip/modeling_blip.py#L249), there should also be a dtype alignment in the ViltPatchEmbeddings as well. Otherwise, I would get the `RuntimeError: Input type (float) and bias type (c10::Half) should be the same`, when my "dandelin/vilt-b32-finetuned-vqa" model is loaded in half-precision data type.

## Reproduction
```python
from transformers import ViltProcessor, ViltForQuestionAnswering
import requests
from PIL import Image
import torch 

# prepare image + question
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
text = "How many cats are there?"

processor = ViltProcessor.from_pretrained("dandelin/vilt-b32-finetuned-vqa")
model = ViltForQuestionAnswering.from_pretrained("dandelin/vilt-b32-finetuned-vqa", torch_dtype=torch.float16).to("cuda")
# prepare inputs
encoding = processor(image, text, return_tensors="pt").to("cuda")

# forward pass
outputs = model(**encoding)
logits = outputs.logits
idx = logits.argmax(-1).item()
print("Predicted answer:", model.config.id2label[idx])
```

@ArthurZucker and @amyeroberts

### CODE REVIEW

**Comment by faaany** [comment]
@yao-matrix

**Comment by faaany** [comment]
@yao-matrix

**Comment by faaany** [comment]
Hi @ArthurZucker , could you take a look at this PR? Thx!

**Review by amyeroberts — APPROVED** [review]
Thanks for adding this @faaany! 

As a more general note, the general pattern in the library is that users should cast their inputs to match the model i.e. this isn't the responsibility of the model as mentioned [in this comment](https://github.com/huggingface/transformers/pull/24947#pullrequestreview-1539371698). 

However, as this is something which is already present in some models, and calling `.to` on the Vilt processor outputs won't work atm, I'm OK with it being merged in.

**Pull request merged**
