### PR TITLE
PyTorch >= 1.7.0 and TensorFlow >= 2.4.0

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

As discussed in #18817 we have decided that Transformers will support versions of PyTorch and TensorFlow for two years after their releases. As a result, Transformers can now assume a minimum version of 1.7.0 for PyTorch and 2.4.0 for TensorFlow. This PR enforces this in the setup and then simplifies a lot of code that was written to support older PyTorch versions.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Great, this is a very welcome end-of-summer cleaning :smile: 

LGTM.

Ok for you @ydshieh?

**Review by ydshieh — APPROVED** [review]
Thank you for the housekeeping 🤗

**Comment by corey-nm** [comment]
@sgugger curious what the reasoning was for blacklisting torch 1.12.0? I looked in  https://github.com/huggingface/transformers/issues/18817, but there's no info there for 1.12

**Comment by sgugger** [comment]
That particular release broke weightnorm, and thus all audio models.

**Pull request merged**
