### PR TITLE
[scripts] Proposal: add a specific device flag

### PR DESCRIPTION
**Pull request by julien-c**
wdyt?

Will do in other scripts if this gets merged.

My use case is I have an instance with multiple GPUs and want to run one generation on `cuda:0`, another one on `cuda:1`, etc.

### CODE REVIEW

**Comment by BramVanroy** [comment]
In my script, I take another approach for this. I assume that distributed training can only be instantiated by using torch's launch script. `local_rank` will be used for the GPU id, even when not in distributed mode.

```python
# torch.distributed.launch adds a world_size environment variable
distributed = int(os.environ['WORLD_SIZE']) > 1 if 'WORLD_SIZE' in os.environ else False
```

Based on that, you can decide what you want to do with `local_rank`. If we're in distributed mode, start the process group, if we're not: use the `local_rank` cuda device.

```python
if local_rank == -1 or not torch.cuda.is_available():
    device = torch.device('cpu')
else:
    device = torch.device(f"cuda:{local_rank}")
    if distributed:
        dist.init_process_group(backend='nccl', init_method='env://')
```

As a bonus, to ensure that all processes such as validating also happen on the main device, even if that's not cuda:0:

```python
is_first_process = not distributed or local_rank in [0, -1]
# ...
if args.do_eval and is_first_process:
    # do eval
```

I merely post this for possible inspiration, of course!

**Comment by thomwolf** [comment]
Sounds good to me let's add this to all the examples (and the template in `templates/adding_a_new_example_script`)

**Comment by julien-c** [comment]
> Sounds good to me let's add this to all the examples

The other scripts maybe make less sense as you would want to train on all available devices? Not 100% sure yet.

**Comment by thomwolf** [comment]
Ok I see, then maybe let's have the device flag on `run_generation` instead of `run_squad` (as currently proposed in the PR)?

**Pull request closed without merging**
