### PR TITLE
apply torch int div to layoutlmv2

### PR DESCRIPTION
**Pull request by ManuelFay**
# What does this PR do?

Linked to #14853 (now closed - bad rebase)

@LysandreJik

### CODE REVIEW

**Comment by ManuelFay** [comment]
REALM tests seem to be failing  - doesn't seem like they should be running ?

**Review by LysandreJik — APPROVED** [review]
This looks good to me! @NielsRogge can you give it a last look and merge if it looks good to you too?

Thanks for your contributions @ManuelFay!

**Review by NielsRogge — APPROVED** [review]
LGTM! Thanks for adding this (sorry for late reply).

**Comment by NielsRogge** [comment]
@ManuelFay can you rebase with master such that we can merge your PR?

**Comment by ManuelFay** [comment]
Done, and I changed the path to the custom divide function (compatible with older torch versions).

**Comment by ManuelFay** [comment]
No problem @NielsRogge ! Here you go, rebased ;)

**Pull request merged**
