### PR TITLE
update Roberta checkpoint conversion

### PR DESCRIPTION
**Pull request by armancohan**
- update to fix fairseq Roberta checkpoint conversion 

Fairseq had removed `in_proj_weight` and `in_proj_bias` from the self attention module:
https://github.com/pytorch/fairseq/commit/4c6b689eebe66a53717dacf28cba7a11b6ffa64f

- create save directory if not exist

### CODE REVIEW

**Comment by thomwolf** [comment]
Thanks a lot @armancohan 

I think we'll want to keep the possibility to import both types of models for backward compatibility. Can you add a switch based on an identification of the model type?

**Comment by julien-c** [comment]
@armancohan (rebased on top of master so I force-pushed to your fork)

**Comment by julien-c** [comment]
So, the fairseq weights themselves didn't change, it's the multiheadattention API that did, in fairseq `0.9.0`. I'll just check that the fairseq version is >= 0.9.

I've also updated the script to not hardcode the vocab length, which should make it compatible with other roberta-like fairseq models such as CamemBERT + maybe XLM-R.

cc @myleott @louismartin

**Comment by armancohan** [comment]
thanks @julien-c

**Review by LysandreJik — COMMENTED** [review]
Great job! - Approved.

**Pull request merged**
