### PR TITLE
Fix `LayoutLMv2` tokenization docstrings

### PR DESCRIPTION
**Pull request by qqaatw**
# What does this PR do?

The tokenizers of `LayoutLMv2` don't accept `is_split_into_words` keyword for `__call__`. Thus, I created a dedicated kwargs docstring to replace the one in `src/transformers/tokenization_utils_base.py` being used.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@NielsRogge @LysandreJik

### CODE REVIEW

**Comment by qqaatw** [comment]
Will open a follow-up PR for `LayoutXLM` after accepted and merged.

**Review by SaulLu — APPROVED** [review]
Thanks for fixing! :smile:

**Comment by LysandreJik** [comment]
@NielsRogge can you give this a look when you have a minute?

**Review by NielsRogge — APPROVED** [review]
Thanks for fixing :) can you rebase with the main branch, such that we can merge your PR?

**Comment by qqaatw** [comment]
Done.

**Comment by NielsRogge** [comment]
Seems like you changed some files which shouldn't be changed, like `index.mdx`. Could you fix those, please?

**Comment by NielsRogge** [comment]
Thanks, merging!

**Pull request merged**
