### PR TITLE
[ViTMAE] Renamed variable name

### PR DESCRIPTION
**Pull request by ariG23498**
The `sequence_masked` variable is actually the part of the sequence that is kept **unmasked** for the encoder to consume. This commit renames the variable accordingly.

CC: @sayakpaul

### CODE REVIEW

**Comment by gante** [comment]
Tagging @NielsRogge, as he's the vision master 👨‍🏫

**Comment by ariG23498** [comment]
Just a reminder here!

**Comment by gante** [comment]
(Niels it currently off, he'll be back in a few days :) )

**Review by NielsRogge — APPROVED** [review]
Thanks for fixing!

**Comment by NielsRogge** [comment]
FYI, I took this from the original repository: https://github.com/facebookresearch/mae/blob/efb2a8062c206524e35e47d04501ed4f544c0ae8/models_mae.py#L140

**Comment by ariG23498** [comment]
Do you think an issue in the original repository would be a good approach to move forward? @NielsRogge

**Comment by NielsRogge** [comment]
Yes indeed, to make the authors confirm!

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Comment by sayakpaul** [comment]
Thanks for leading the effort. Good work! 

@sgugger and @NielsRogge thanks for the reviews and actions.

**Pull request merged**
