### PR TITLE
[CI ] Remove `past` in favor of `pat_key_values`

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Related to #20944, The `past` arg was removed.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]

**Review by ydshieh — APPROVED** [review]
I confirmed `tests/models/encoder_decoder/test_modeling_tf_encoder_decoder.py::TFBertEncoderDecoderModelTest::test_bert2bert_summarization`

pass now. Thank you @ArthurZucker !

**Comment by ArthurZucker** [comment]
Other tests might also pass!

**Comment by ArthurZucker** [comment]
Git overides the `use_cache` arguments if labels are provided to `False` see [here](https://github.com/ArthurZucker/transformers/blob/c2f9aacee9326b9db886036497a4d157666cb040/src/transformers/models/git/modeling_git.py#L1475-L1476). I suspect that generating with `git` did not use the `past_key_values` as the argument was `past` (which was always None).

**Review by sgugger — APPROVED** [review]
Thanks for the cleanup!

**Comment by ArthurZucker** [comment]
The failing tests are unrelated, will merge

**Pull request merged**
