### PR TITLE
Fix: use unidic-lite instead of ipadic as the tokenizer dictionary for Japanese

### PR DESCRIPTION
**Pull request by KanTakahiro**
# What does this PR do?

Fixes the [issue](https://github.com/huggingface/transformers/issues/32482) that transformers default request `ipadic` as the tokenization dictionary of Japanese language. As the `ipadic` is old and `ipadic` developers suggest to use `unidic-lite`.(see their [GitHub](https://github.com/polm/ipadic-py))

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. -> **[this issue](https://github.com/huggingface/transformers/issues/32482)**
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? **No but I modified the source code and ran my project without any issue.**

## Who can review?

Library:

- tokenizers: @ArthurZucker 

## First-time Contributor Note

This is my first time contributing to an open source project. I've done my best to follow the project's guidelines and coding standards, but please let me know if there's anything I need to adjust or improve. Thank you for considering my contribution!

### CODE REVIEW

**Comment by KanTakahiro** [comment]
It seems that the CI test environment doesn't have unidic-lite installed so the test failed.

**Review by ArthurZucker — COMMENTED** [review]
Hey! The docker is created here: https://github.com/huggingface/transformers/blob/main/docker/custom-tokenizers.dockerfile#L20 but what you can do is change this line: 


adding:
```
    install_steps=["uv venv && uv pip install .[ja]"],
```
will make sure it's installed!

cc @ydshieh I'll open a PR for all ci jobs afterwards to properly rely on extras mapped to names!

**Comment by ArthurZucker** [comment]
Would you like me to push directly?

**Comment by KanTakahiro** [comment]
Sure! Please push it directly! I am not very familiar with how to do this.

**Comment by ArthurZucker** [comment]
@KanTakahiro it was just the default value that needed an update!

**Pull request merged**
