### PR TITLE
Fix vilt config docstring parameter to match value in init

### LINKED ISSUE #25639: hidden_dropout_prob and attention_probs_dropout_prob values in the documentation doesn't match with that in the code
### System Info

- `transformers` version: 4.30.2
- Platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Huggingface_hub version: 0.16.2
- Safetensors version: 0.3.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: RTX A5000
- Using distributed or parallel set-up in script?: No

### Who can help?

@sgugger 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I am training ViLT on e-SNLI-VE. This is basically what I am doing.
```
from transformers import ViltConfig, ViltProcessor, ViltForQuestionAnswering

label2id = {'contradiction':0, 'entailment':1, 'neutral':2}
id2label = {0:'contradiction', 1:'entailment', 2:'neutral'}

vilt_config = ViltConfig(label2id=label2id, id2label=id2label, max_position_embeddings=100)
vilt_config
```
This gives the following output. 
Screenshot from 2023-08-22 02-21-17
The values for both variables should be 0.1 as indicated by the documentation. 
Screenshot from 2023-08-22 02-23-18

### Expected behavior

The values of the variables should have been zero.

### PR DESCRIPTION
**Pull request by raghavanone**
# What does this PR do?

Fixes #25639 

This PR fixes the Vilt models config's init parameters to match the ones in the documentation.

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Thanks for opening this PR! The fix should go the other way: the documentation is updated to reflect the default values

**Comment by raghavanone** [comment]
> Thanks for opening this PR! The fix should go the other way: the documentation is updated to reflect the default values

Oh Yes, Got misled by the discussion [here](https://github.com/huggingface/transformers/issues/25639) . But checked [here](https://huggingface.co/dandelin/vilt-b32-mlm/blob/main/config.json) , the init is right, only the documentation needs to be changed .

**Comment by raghavanone** [comment]
@amyeroberts  Done.

**Review by amyeroberts — APPROVED** [review]
Thanks for updating!

**Pull request merged**
