### PR TITLE
Avoid race condition

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

We have some hub tests failing from time to time.

https://app.circleci.com/pipelines/github/huggingface/transformers/97781/workflows/d3365fb8-a6b4-489a-912e-6d142409f848/jobs/1295791

This is due to the race condition of deleting the repo. 

This PR avoid it by using `try ... except ...` just as in some `def tearDownClass(cls):`.

(Might be better to catch specific error code)

### CODE REVIEW

**Comment by ydshieh** [comment]
cc @LysandreJik as we have  talked a bit on slack few weeks back.

**Comment by amyeroberts** [comment]
Instead of using the same repo name for all the CI runs and a try/except catch could we instead us a randomly generate string at the end of each name? Or even the CI run ID? At the moment, we still will have the issue that concurrent tests will push to the same repo, which might obscure failures introduced by a PR

**Comment by ydshieh** [comment]
@amyeroberts  Yes, I am also thinking that! Would it be ok if we merge as it is to see how it goes for a few days? 

I will definitely work as what is suggested, but it would be nice to avoid the failures on main as soon as we can :-)

**Review by amyeroberts — APPROVED** [review]
@ydshieh Sure - let's get main on green and iterate!

**Pull request merged**
