### PR TITLE
Enable pegasus fp16 by clamping large activations

### PR DESCRIPTION
**Pull request by sshleifer**
+ If encoder layer is about to return inf, clamp to a float **near** the boundary of fp16 range
+ This improves rouge for distil-pegasus-xsum-12-12 in fp16 by 0.1 ROUGE 2
+ I cannot think of how this change could make things worse.
+ Other models' metrics are unaffected!

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
I think this is a great addition! Maybe we could leverage this fix for T5 as well.

**Review by sgugger — APPROVED** [review]
Nice and neat fix!

**Review by LysandreJik — APPROVED** [review]
Cool, clean!

**Comment by karthikgali** [comment]
Hi,

Any chances of implementing the same for the "pegasus-cnn_dailymail" (distilled) model?

Regards,
Karthik

**Comment by sshleifer** [comment]
@karthikgali this PR implements for all models that inherit from Bart. This includes pretty much every `sshleifer/` checkpoint and every `pegasus/` checkpoint.

Pegasus variants with 16 encoder layers still do not work well in fp16, but I will push a 12 layer distilled version soon that does!

**Pull request merged**
