### PR TITLE
Fix training schedules in examples to match new API

### PR DESCRIPTION
**Pull request by thomwolf**
Re #445:
- update examples to work with the new optimizer API

### CODE REVIEW

**Comment by thomwolf** [comment]
@lukovnikov do you want to give this PR a look and confirm it's fine?

Also, we should document a bit the new optimizer API in the README. Do you want to use this PR to copy a few docstring in the README (we currently don't have auto-generated doc)?

**Comment by lukovnikov** [comment]
Hi. Sorry, forgot about the examples.
Did a couple fixes in my 'schedules_in_examples' branch (see PR #531).
However, I don't have the fp16 setup yet so wasn't able to run the examples to be completely sure.
Docs update is underway.

**Comment by thomwolf** [comment]
Got it.
Ok to merge this PR @lukovnikov?

**Comment by lukovnikov** [comment]
With the fixes from #531, should be good.

**Comment by thomwolf** [comment]
Thanks!

**Pull request merged**
