### PR TITLE
Adding `skip_special_tokens=True` to FillMaskPipeline

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

- It's backward incompatible.
- It makes for sense for pipelines to remove references to special_tokens
(all of the other pipelines do that).
- Keeping special tokens makes it hard for users to actually remove them
because all models have different tokens (`<s>`, `<cls>`,` [CLS]`, ....)
- It's actually closer to the docs specs : 
```
            - **sequence** (:obj:`str`) -- The corresponding input with the mask token prediction.
```
as the input does not include the special tokens.

Linked to : https://github.com/huggingface/transformers/issues/9518

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@LysandreJik @patrickvonplaten 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
Yes! I like it a lot -> completely agree here @Narsil

**Review by LysandreJik — APPROVED** [review]
Yes, this makes sense. Thanks @Narsil. This is more of a bugfix than a breaking change imo.

**Comment by Narsil** [comment]
If it's a bug users relied on, then it's a feature, not a bug. 

Anyway I'll merge this.

**Comment by LysandreJik** [comment]
Good point, but I don't think that's the case here. Do you think users rely on the previous behavior? If that's the case, then we should revert this PR until we change of major version.

**Pull request merged**
