### PR TITLE
Fixed typo in docstring

### PR DESCRIPTION
**Pull request by tkburis**
# What does this PR do?

Missing 'to' in 'pad the inputs the maximum length'.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by stevhliu — APPROVED** [review]
Thanks for fixing! cc @sgugger

**Review by sgugger — APPROVED** [review]
Thanks for the fix! Can you just run `make style` on your branch to fix the quality issue?

**Comment by tkburis** [comment]
Hi @sgugger,

I've looked at the CircleCI test and it seems like it failed because of a timeout when installing from PIP, not because of styling. Is there any way to rerun the tests?

**Comment by sgugger** [comment]
Indeed, everything is green on re-launch. Thanks for your contribution!

**Pull request merged**
