### PR TITLE
Add `beautifulsoup4` to the dependency list

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Add `beautifulsoup4` to the dependency list - to enable the tests `MarkupLMFeatureExtractionTest` and `MarkupLMProcessorIntegrationTests`

On CircleCI, we now can have the following tested (those have `@require_bs4`)
```bash
PASSED tests/models/markuplm/test_feature_extraction_markuplm.py::MarkupLMFeatureExtractionTest::test_call
PASSED tests/models/markuplm/test_feature_extraction_markuplm.py::MarkupLMFeatureExtractionTest::test_feat_extract_from_and_save_pretrained
PASSED tests/models/markuplm/test_feature_extraction_markuplm.py::MarkupLMFeatureExtractionTest::test_feat_extract_to_json_file
PASSED tests/models/markuplm/test_feature_extraction_markuplm.py::MarkupLMFeatureExtractionTest::test_feat_extract_to_json_string
PASSED tests/models/markuplm/test_feature_extraction_markuplm.py::MarkupLMFeatureExtractionTest::test_init_without_params
```

### CODE REVIEW

**Review by NielsRogge — APPROVED** [review]
Thanks for adding!

**Review by sgugger — COMMENTED** [review]
No fan of making an extra specifically for this. Can you put it in testing?

**Comment by ydshieh** [comment]
Hi @sgugger I think I misread your message, and end up putting the installation in the CircleCI `config.yml` and GitHub workflow files. Should I instead put `beautifulsoup4` in `extras["testing"]`? Sorry.

**Review by sgugger — APPROVED** [review]

**Review by LysandreJik — APPROVED** [review]

**Comment by ydshieh** [comment]
test failure irrelevant, merge now.

**Pull request merged**
