### PR TITLE
[FlaxBert] Fix non-broadcastable attention mask for batched forward-passes

### LINKED ISSUE #8790: [FlaxBert] Non-broadcastable attention mask in batched forward-pass
## Environment info

     
- `transformers` version:
- Platform: Linux
- Python version: 3.8
- JAX version:
  - jax==0.2.6
  - jaxlib==0.1.57+cuda110
  - flax==0.2.2
- PyTorch version (GPU?): n/a
- Tensorflow version (GPU?): n/a
- Using GPU in script?: **yes** (cuda 11.0)
- Using distributed or parallel set-up in script?: **no**

### Who can help
@mfuntowicz 
@avital 
@LysandreJik 

## Information

I ran the script from the recent Twitter [post](https://twitter.com/huggingface/status/1331255460033400834):

The only thing I changed was that I fed in multiple sentences:

```python
from transformers import FlaxBertModel, BertTokenizerFast, TensorType

tokenizer = BertTokenizerFast.from_pretrained('bert-base-cased')
model = FlaxBertModel.from_pretrained('bert-base-cased')
# apply_fn = jax.jit(model.model.apply)

sentences = ["this is an example sentence", "this is another", "and a third one"]
encodings = tokenizer(sentences, return_tensors=TensorType.JAX, padding=True, truncation=True)
tokens, pooled = model(**encodings)
```
> ValueError: Incompatible shapes for broadcasting: ((3, 12, 7, 7), (1, 1, 3, 7))

See full stack trace: https://pastebin.com/sPUSjGVi

### PR DESCRIPTION
**Pull request by KristianHolsheimer**
# What does this PR do?

Fixes #8790

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@mfuntowicz 
@avital 
@LysandreJik

### CODE REVIEW

**Comment by KristianHolsheimer** [comment]
@mfuntowicz @avital
I just fixed the bug that I was hitting. There might be other places that need this fix as well.

**Comment by patrickvonplaten** [comment]
Wuuhu - first Flax PR :-). This looks great to me @KristianHolsheimer - think you touched all necessary files as well! 

@mfuntowicz - maybe you can take a look as well

**Review by patrickvonplaten — APPROVED** [review]

**Comment by KristianHolsheimer** [comment]
The flax tests time out. When I ran the tests locally with `pytest -n auto`, I did notice OOM issues due to preallocation of GPU memory by XLA. I addressed this in commit 6bb1f5e600cd35c712f4f980699df7735b4f59eb.

Other than that, it's hard to debug the tests when there's no output.

Would it be an option to run these tests single-threaded instead?

**Comment by mfuntowicz** [comment]
I had the changes in another branche I'm working on, happy to merge this one and will rebase mine 👍.

Thanks for looking at it @KristianHolsheimer

**Review by mfuntowicz — APPROVED** [review]

**Pull request merged**
