### PR TITLE
updated metrics saving and logging

### LINKED ISSUE #10337: [trainer] port metrics logging and saving methods to all example scripts
In an effort to make the examples easier to read, in https://github.com/huggingface/transformers/pull/10266 we added new trainer methods:

* `trainer.log_metrics` - to perform consistent formatting for logged metrics
* `trainer.save_metrics` - to save the metrics into a corresponding json file.

and deployed them in `run_seq2seq.py`.

The next task is do the same for all the other `examples/*/run_*.py` scripts.

Steps:
1. Study the diff for `run_seq2seq.py`. https://github.com/huggingface/transformers/pull/10266/files#diff-82bfb61a8b91894c2c2101734a6ab7b415be4ace5cd1e01b4c37663020d924ae
2. pick a script, e.g. `examples/multiple-choice/run_swag.py`
3. apply the same changes as in step 1 removing the explicit metrics printing lines and replacing them with the 2 new methods
4. test the modified script  (usually `README.md` for that folder should have the instructions to do so) and see that your change works - train/eval/test metrics are printed using the new way and that `(train|eval|test|all)_results.json` are generated.
You can use a very short datasample 5 records is enough, by just adding: `--max_train_samples 5 --max_val_samples 5 --max_test_samples 5`

repeat for other scripts.

Thank you very much!

The metrics log should be similar to this, with the exception of using different scoring metrics:

```


02/16/2021 17:06:39 - INFO - __main__ -   ***** train metrics *****
02/16/2021 17:06:39 - INFO - __main__ -     epoch                      =    1.0
02/16/2021 17:06:39 - INFO - __main__ -     init_mem_cpu_alloc_delta   =    2MB
02/16/2021 17:06:39 - INFO - __main__ -     init_mem_cpu_peaked_delta  =    0MB
02/16/2021 17:06:39 - INFO - __main__ -     init_mem_gpu_alloc_delta   =  230MB
02/16/2021 17:06:39 - INFO - __main__ -     init_mem_gpu_peaked_delta  =    0MB
02/16/2021 17:06:39 - INFO - __main__ -     total_flos                 = 2128GF
02/16/2021 17:06:39 - INFO - __main__ -     train_mem_cpu_alloc_delta  =   55MB
02/16/2021 17:06:39 - INFO - __main__ -     train_mem_cpu_peaked_delta =    0MB
02/16/2021 17:06:39 - INFO - __main__ -     train_mem_gpu_alloc_delta  =  692MB
02/16/2021 17:06:39 - INFO - __main__ -     train_mem_gpu_peaked_delta =  661MB
02/16/2021 17:06:39 - INFO - __main__ -     train_runtime              = 2.3114
02/16/2021 17:06:39 - INFO - __main__ -     train_samples              =    100
02/16/2021 17:06:39 - INFO - __main__ -     train_samples_per_second   =  3.028

02/16/2021 17:06:43 - INFO - __main__ -   ***** val metrics *****
02/16/2021 17:13:05 - INFO - __main__ -     epoch                     =     1.0
02/16/2021 17:13:05 - INFO - __main__ -     eval_bleu                 = 24.6502
02/16/2021 17:13:05 - INFO - __main__ -     eval_gen_len              =    32.9
02/16/2021 17:13:05 - INFO - __main__ -     eval_loss                 =  3.7533
02/16/2021 17:13:05 - INFO - __main__ -     eval_mem_cpu_alloc_delta  =     0MB
02/16/2021 17:13:05 - INFO - __main__ -     eval_mem_cpu_peaked_delta =     0MB
02/16/2021 17:13:05 - INFO - __main__ -     eval_mem_gpu_alloc_delta  =     0MB
02/16/2021 17:13:05 - INFO - __main__ -     eval_mem_gpu_peaked_delta =   510MB
02/16/2021 17:13:05 - INFO - __main__ -     eval_runtime              =  3.9266
02/16/2021 17:13:05 - INFO - __main__ -     eval_samples              =     100
02/16/2021 17:13:05 - INFO - __main__ -     eval_samples_per_second   =  25.467

02/16/2021 17:06:48 - INFO - __main__ -     ***** test metrics *****
02/16/2021 17:06:48 - INFO - __main__ -     test_bleu                 = 27.146
02/16/2021 17:06:48 - INFO - __main__ -     test_gen_len              =  41.37
02/16/2021 17:06:48 - INFO - __main__ -     test_loss                 = 3.6682
02/16/2021 17:06:48 - INFO - __main__ -     test_mem_cpu_alloc_delta  =    0MB
02/16/2021 17:06:48 - INFO - __main__ -     test_mem_cpu_peaked_delta =    0MB
02/16/2021 17:06:48 - INFO - __main__ -     test_mem_gpu_alloc_delta  =    0MB
02/16/2021 17:06:48 - INFO - __main__ -     test_mem_gpu_peaked_delta =  645MB
02/16/2021 17:06:48 - INFO - __main__ -     test_runtime              = 5.1136
02/16/2021 17:06:48 - INFO - __main__ -     test_samples              =    100
02/16/2021 17:06:48 - INFO - __main__ -     test_samples_per_second   = 19.556

```

### PR DESCRIPTION
**Pull request by bhadreshpsavani**
# What does this PR do?

I have updated redundant code for saving and logging metrics in the example scripts

Fixes #10337 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@stas00  @sgugger

### CODE REVIEW

**Comment by bhadreshpsavani** [comment]
I want to mention one thing here while testing the file I found that,
For files `run_clm.py, run_mlm.py, run_plm.py, run_ner.py, run glue.py`
The logs are as expected like this
```
02/26/2021 20:31:22 - INFO - __main__ -   ***** eval metrics *****
02/26/2021 20:31:22 - INFO - __main__ -     HasAns_exact = 0.0
02/26/2021 20:31:22 - INFO - __main__ -     HasAns_f1 = 0.0
02/26/2021 20:31:22 - INFO - __main__ -     HasAns_total = 8
02/26/2021 20:31:22 - INFO - __main__ -     NoAns_exact = 100.0
02/26/2021 20:31:22 - INFO - __main__ -     NoAns_f1 = 100.0
02/26/2021 20:31:22 - INFO - __main__ -     NoAns_total = 6
02/26/2021 20:31:22 - INFO - __main__ -     best_exact = 42.857142857142854
02/26/2021 20:31:22 - INFO - __main__ -     best_exact_thresh = 0.0
02/26/2021 20:31:22 - INFO - __main__ -     best_f1 = 42.857142857142854
02/26/2021 20:31:22 - INFO - __main__ -     best_f1_thresh = 0.0
02/26/2021 20:31:22 - INFO - __main__ -     epoch = 1.43
02/26/2021 20:31:22 - INFO - __main__ -     exact = 42.857142857142854
02/26/2021 20:31:22 - INFO - __main__ -     f1 = 42.857142857142854
02/26/2021 20:31:22 - INFO - __main__ -     total = 14
```
But for other files like `run_qa.py, run_qa_beam_search.py, run_swags.py`
The logs were like below,
```
***** eval metrics *****
  HasAns_exact      =     0.0
  HasAns_f1         =     0.0
  HasAns_total      =       8
  NoAns_exact       =   100.0
  NoAns_f1          =   100.0
  NoAns_total       =       6
  best_exact        = 42.8571
  best_exact_thresh =     0.0
  best_f1           = 42.8571
  best_f1_thresh    =     0.0
  epoch             =    1.43
  exact             = 42.8571
  f1                = 42.8571
  total             =      14
```
Without a timestamp, log level, and function name. 

When I run the command `python -m unittest discover -s examples -t examples -v` it was giving proper logs

**Review by sgugger — APPROVED** [review]
Thanks a lot for tackling this issue!

For the problem you're reporting, I believe that's because those three scripts don't have the following line when setting up the Transformers logger:
```
if is_main_process(training_args.local_rank):
        transformers.utils.logging.set_verbosity_info()
        transformers.utils.logging.enable_default_handler()
        transformers.utils.logging.enable_explicit_format()
```

The test is there but missing the last two lines in the three scripts you mention (but you can see it's correct in the otehrs). If you're willing to correct this in your PR as well, that would be great!

**Comment by stas00** [comment]
And also for consistency let's add this bit:

https://github.com/huggingface/transformers/blob/98569d4ba237d84714f6c15e2c301fd22d42d2b1/examples/seq2seq/run_seq2seq.py#L643-L644

this allows the user to load all metrics in one call.

It can be part of this PR, or a separate one if you'd like to make this completed faster. And I can make a separate issue to add it.

**Comment by sgugger** [comment]
I'm fine with it.
One thing that's striking me is that all those calls are inside an `if trainer.is_world_process_zero()`. Shouldn't we refactor that bit in the `log_metrics`/`save_metrics` method?

**Comment by bhadreshpsavani** [comment]
Sure @sgugger and @stas00 
I will make changes in this PR only for fast

**Comment by stas00** [comment]
It won't make much of a difference at the moment since there is other code that is running under `if trainer.is_world_process_zero()` - if we make that code refactored too then absolutely yes - it would make that part of the scripts so much simpler.

**Comment by stas00** [comment]
we could probably do something about:
```
            trainer.save_metrics("eval", metrics)
            all_metrics.update(metrics)
```

so that it's not done separately, by 
1. either having `save_metrics` always update `all_results.json` with every call
2. or simply have trainer store the metrics internally and then just have one call to flush it to the disk at the end of the run

**Comment by stas00** [comment]
@bhadreshpsavani, I suggest we finish this PR w/o introducing new changes we are discussing.

Then we tweak `run_seq2seq.py` to do things better, have it as a model, and then sync to other scripts? how does that sound?

**Comment by bhadreshpsavani** [comment]
Okay @stas00,
I have added [this](https://github.com/huggingface/transformers/pull/10421#pullrequestreview-599815674) changes about logger and it is working perfectly. I will commit it in this PR for that three files.

**Review by stas00 — APPROVED** [review]
Perfect! Thank you, @bhadreshpsavani for this very useful contribution!

**Comment by stas00** [comment]
OK, so the only missing thing is the template

**Comment by stas00** [comment]
@bhadreshpsavani, this is now merged: https://github.com/huggingface/transformers/pull/10427 and can be replicated to other scripts (and one template)

Please feel free to add it to this PR or open a new one - whatever works the best for you.

Thank you!

**Comment by bhadreshpsavani** [comment]
@stas00, I will first try to make changes to this PR

**Comment by bhadreshpsavani** [comment]
in the `run_glue.py` we have code like this for saving test result,
```
            output_test_file = os.path.join(training_args.output_dir, f"test_results_{task}.txt")
            if trainer.is_world_process_zero():
                with open(output_test_file, "w") as writer:
                    logger.info(f"***** Test results {task} *****")
                    writer.write("index\tprediction\n")
                    for index, item in enumerate(predictions):
                        if is_regression:
                            writer.write(f"{index}\t{item:3.3f}\n")
                        else:
                            item = label_list[item]
                            writer.write(f"{index}\t{item}\n")
```
I didn't change it because it was different than our general save_metrics() methods. 
Is there any way we can generalize it?

**Comment by bhadreshpsavani** [comment]
Hi @stas00 and @sgugger,

I was trying to make changes in the same PR and after doing rebase from master I needed to merge the new commits to my branch to push my changes. Let me know if i this PR is don't seem fine or I need to make another PR with all these changes and delete this one.

This is the first time I used `git rebase upstream/master` so I might have done it incorrectly.

**Comment by sgugger** [comment]
Yes the rebase has made new files appear in the diff that are irrelevant to your work, so it would be great if you could close this PR and open a new one (no need to do anything else than that like creating a new branch, it's just git being annoying here).

For your earlier question, leave the part in `run_glue` that doesn't refactor nicely as it is I would say.

**Comment by stas00** [comment]
BTW, If you want to use an automated rebase process please consider this little script: https://github.com/stas00/git-tools/tree/master/git-rebase

**Comment by bhadreshpsavani** [comment]
Sure @stas00,
I will use an automatic rebase script next time.
For simplicity, I have created another [PR](https://github.com/huggingface/transformers/pull/10436) with all the changes and tested the changes.
I closing this PR.

**Pull request closed without merging**
