### PR TITLE
Fix AttributeError: 'MMBTConfig' object has no attribute 'use_return_dict'

### PR DESCRIPTION
**Pull request by ahmed-mahran**
# What does this PR do?

Fixes ```AttributeError: 'MMBTConfig' object has no attribute 'use_return_dict'```
Attributes are copied from `transformers.PreTrainedConfig.__dict__` which does not contain object properties and `use_return_dict` is an object property that's not in the `__dict__`.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sgugger 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
The MMBT config is not a `PretrainedConfig`, so there is no point trying to use it as such (the MMBT model in general is completely broken and the original authors did help/release another opensource version of their models we could use as a guide).

**Comment by ahmed-mahran** [comment]
Thanks @sgugger 
Would you please provide a link to this implementation? I'd be interested to proceed on this.

**Comment by sgugger** [comment]
There is none that i know of, that is the problem.

**Comment by ahmed-mahran** [comment]
Ah! Any chance we can describe what are the issues with current implementation?

**Pull request closed without merging**
