### PR TITLE
fix the slow tests doc

### PR DESCRIPTION
**Pull request by stas00**
remove unnecessary duplication wrt `RUN_SLOW=yes`

@sgugger

### CODE REVIEW

**Comment by roblox34** [comment]
Closed

**Review by LysandreJik — COMMENTED** [review]
I think you deleted both instructions here, no?

**Comment by stas00** [comment]
Nope. They appear again, 2 paras later.

Moreover, the 2 deleted instructions are themselves bogus as they are identical ;)

**Review by sgugger — APPROVED** [review]
Yes the correct instructions are in a paragraph below so those are safe to remove. Thanks @stas00 !

**Pull request merged**
