### PR TITLE
Rbert - follow-up to #1301 - more robust configuration class loading

### PR DESCRIPTION
**Pull request by thomwolf**
This PR update #1301 as discussed in the thread of #1308.

The configuration classes are updated to be more robust to the addition of new parameters (load defaults value first and then update with pretrained configuration if needed).

This incorporates the entity token ids directly in `BertConfig`.

cc @RichJackson

### CODE REVIEW

**Comment by byzhang** [comment]
@thomwolf Is it possible to apply the changes on the TFxx classes as well?

**Comment by RichJackson** [comment]
hi @thomwolf anything I can do to help?

**Comment by thomwolf** [comment]
Thanks for the heads up. This one slipped out of my mind.
It's ready to merge I think (won't have time to do the TF conversion of the head).
Ok to merge @LysandreJik?

**Comment by thomwolf** [comment]
This actually needs deeper investigations to work with the new `input_embeds` inputs on master (skipping `input_ids`).

**Pull request closed without merging**
