### PR TITLE
Fix bug for checkpoint saving on multi node training setting

### PR DESCRIPTION
**Pull request by dumpmemory**
# What does this PR do?

Fixes # (issue)

fix bug on multi node training setting with shared file system
## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerzr

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Very good catch, this is a difference between the Accelerate and Trainer integration that I need to migrate to Accelerate, as I missed it. 

cc @LysandreJik just as an FYI (putting it on my list).

**Comment by muellerzr** [comment]
cc @thundergolfer too since I know you're trying to keep an eye on them all :)

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by thundergolfer** [comment]
Thanks @dumpmemory. Another edge case squashed!

**Pull request merged**
