### PR TITLE
Add dinov2 with registers diff

### PR DESCRIPTION
**Pull request by BernardZach**
# What does this PR do?
This PR is a follow up and rebase-ing of #32905 and it seems to be working well from the work done by @NielsRogge. 

## Relevent reviewers:
@ArthurZucker

### CODE REVIEW

**Comment by NielsRogge** [comment]
I think you need to change the diff_dinov2_with_registers.py to modular_dinov2_with_registers.py and then use the linter as described here: https://huggingface.co/docs/transformers/modular_transformers.

So you can run:
```bash
python PATH/utils/modular_model_converter.py --files_to_parse PATH/modular_dinov2_with_registers.py
```

**Comment by Cyrilvallez** [comment]
Indeed!

**Comment by BernardZach** [comment]
I beleive that I have changed the file name correclty and ran the command provided by @NielsRogge, some tests failing however.

**Comment by NielsRogge** [comment]
Great, let me know if you need any help fixing the tests, once they're green I can assign someone to review your PR

**Comment by BernardZach** [comment]
@NielsRogge having difficulty addressing test issues if you have a moment to take a look. Apoligies, first time contributing.

**Comment by NielsRogge** [comment]
Something went wrong with the git diff, showing nearly 3k files changed. Could you reverse that?

**Comment by BernardZach** [comment]
I have messed something up bad, closing this PR and attempting to start over from #32905.

**Pull request closed without merging**
