### PR TITLE
Add SiglipForImageClassification and CLIPForImageClassification

### PR DESCRIPTION
**Pull request by NielsRogge**
# What does this PR do?

This PR adds 2 new classes to the library, `SiglipForImageClassification` and `CLIPForImageClassification`.

This makes it easier to fine-tune SigLIP/CLIP for image classification, as otherwise people had to manually write a class based on SiglipVisionModel/CLIPVisionModel with a head on top. Given that SigLIP and CLIP are among the best vision encoders out there, it makes sense to add them.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Looks great - thanks for adding!

**Comment by NielsRogge** [comment]
@amyeroberts I assume the "build PR documentation" check is failing but unrelated to this PR, so I can merge?

**Comment by amyeroberts** [comment]
@NielsRogge Yes, if you look on main you can see that the build is failing for lots of (unrelated) PRs at the moment. I'm happy for you to merge as all the other CIs are passing.

**Comment by zhjohnchan** [comment]
Hi @NielsRogge and @amyeroberts,

Thanks for your contribution to the community @NielsRogge! I am wondering if `"do_rescale": true` is necessary for `SiglipImageProcessor`? Let me know if I miss anything!

Best,

**Comment by zhjohnchan** [comment]
@amyeroberts Thank you so much! Just realized it should be rescaled for all Transformers' preprocessors.

**Comment by NielsRogge** [comment]
@zhjohnchan I haven't encountered the same problem, made a fine-tuning notebook for SigLIP here: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/SigLIP/Fine_tuning_SigLIP_and_friends_for_multi_label_image_classification.ipynb.

**Comment by zhjohnchan** [comment]
@NielsRogge Got it! Thank you so much!

**Comment by Andron00e** [comment]
Hi, I am the one who proposed to add a CLIPForImageClassification. Now I am back to contributing with it. 
I see "Build documentation" failure. How can it be fixed?

**Comment by Andron00e** [comment]
Thank you! I'll try to fix minor bugs with CLIPForImageClassification and place its code into SigLIP's directory.

**Pull request merged**
