### PR TITLE
Improved type hinting for all attention parameters

### LINKED ISSUE #28345: Is there some bug in typehint in `modeling_outputs` (or maybe other files)?
### System Info

Hi! When I tried to modify some code which calls some classes in `src/transformers/modeling_outputs.py` such as the class `BaseModelOutput` and `BaseModelOutputwithPast`, I find the typehint of some parameters is different from your comments and my understanding of the code. I believe the correct type of them should be like `Optional[Tuple[torch.FloatTensor, ...]]` instead of `Optional[Tuple[torch.FloatTensor]]` because the comments say the tuple with length which equals to the num of layers or something else but not **ONE**. However, the type hint `Optional[Tuple[torch.FloatTensor]]` means the tuple should be length 1.

Is my understanding correct? Or am I misunderstanding what these codes do?

image

@ArthurZucker @younesbelkada Thank you!

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I use the Pylance as the type checker.

### Expected behavior

The typehint would not affect the behavior.

### PR DESCRIPTION
**Pull request by nakranivaibhav**
# What does this PR do?
The type hinting for all attention parameters has been changed to 'Optional[Tuple[torch.FloatTensor,...]] = None' to reflect a tuple of arbitrary size.

Fixes #28345

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@ArthurZucker @Rocketknight1

### CODE REVIEW

**Review by Rocketknight1 — APPROVED** [review]
LGTM! Would it make sense to do the same change for hidden states?

**Comment by nakranivaibhav** [comment]
I had a extra space between the "," and "..." That failed the formatting. 
Yeah @Rocketknight1 makes sense doing that to hidden states too, since it is the same as attentions, depends on num of layers. I can do that too

**Review by amyeroberts — COMMENTED** [review]
Thanks for updating all of these! 💪 

There's a lot of model-specific dataclasses in the [modeling files too](https://github.com/search?q=repo%3Ahuggingface%2Ftransformers++%22%28ModelOutput%29%3A%22++path%3A%2F%5Esrc%5C%2Ftransformers%5C%2Fmodels%5C%2F%2F&type=code). Could you apply these updates to those too?

**Comment by nakranivaibhav** [comment]
@amyeroberts I will look into it. I can do that too. Happy to help :)

**Comment by amyeroberts** [comment]
@nakranivaibhav Amazing 🤗 Let me know when it's ready for another review!

**Comment by nakranivaibhav** [comment]
@amyeroberts Kindly approve the changes.
@ArthurZucker Please review the changes.

**Comment by nakranivaibhav** [comment]
@amyeroberts can you approve recent changes. Chnaged 15 files. 
I also noticed there is no equivalent of CLIPTextModelOutput in the modeling_tf_clip.py script. Is it intended or that part is missed?

**Comment by amyeroberts** [comment]
@nakranivaibhav Awesome work! I believe that's just an oversight. Feel free to add as part of this PR! 

The current diff is quite large and contains changes recently merged into `main`. From the commit history it looks like you've rebase and pushed without forcing. To make sure the branch contains just your commits and is up-to-date with the development branch - working on this branch: 
* `git fetch upstream main`
* `git rebase upstream/main`
* `git push -f`

**Comment by nakranivaibhav** [comment]
@amyeroberts Yeah I did mess up something. Sorry, I am new to git. I will push the changes again.
I'll also add CLIPTextModelOutput in modeling_tf_clip.py

**Comment by amyeroberts** [comment]
@nakranivaibhav No worries - we've all done it at least once! Let me know when those changes are pushed and I should review

**Comment by nakranivaibhav** [comment]
@amyeroberts I have pushed a fresh commit. You can review it now.

**Comment by amyeroberts** [comment]
@nakranivaibhav There's currently a whole directory `myenv` which is part of this PR. You'll need to remove these: `git rm -r myenv`

**Comment by nakranivaibhav** [comment]
@amyeroberts I do have myvenv in the .gitignore file. For some reason, it got pushed too. I did git rm -r myvenv. Is that it or do i have to push a fresh commit?

**Comment by amyeroberts** [comment]
`git rm` is the complement to `git add`. In the same way, it's just a step which makes the files to staging - they still need to be applied with a commit and push to the remote. You can check this yourself by looking at the [files changed](https://github.com/huggingface/transformers/pull/28479/files) tab for this PR (you can see `myenv` is still there). 

I would recommend reviewing the diff in the file changes for a PR to see all the changes and make any modifications if needed before asking for review.

**Comment by nakranivaibhav** [comment]
@amyeroberts I have removed the myvenv directory. Do I need to update the .gitignore file as well and make a new generic venv already listed in the .gitignore file so that it does not get pushed and the .gitignore file remains unchanged?

P.S: Thank you for bearing this. I don't know my way around git and you are helping me a lot.

**Review by amyeroberts — COMMENTED** [review]
Great piece of work - thank you for this contribution! 

I'd suggest reviewing what was pushed with `myenv` in 80d56008b5449894761a514edb5abef3adc22e55 to make sure there's no information which shouldn't be leaked publicly e.g. a token. If there is, then you'll want to rebase and modify the commit history so that people returning to this PR can't find the information. 

Let me know once you've checked and if you've applied the changes if you want to modify the commit history. Once done, I'll merge.

**Comment by nakranivaibhav** [comment]
@amyeroberts Yes I have checked there is no confidential information in that commit. You can go ahead and merge.

**Review by amyeroberts — APPROVED** [review]

**Comment by amyeroberts** [comment]
@nakranivaibhav Thanks for confirming and all the work improving our types!

**Comment by nakranivaibhav** [comment]
@amyeroberts Always happy to help. On to the next one 🚀

**Pull request merged**
