### PR TITLE
Remove CLI spams with Whisper FeatureExtractor

### PR DESCRIPTION
**Pull request by qmeeus**
# What does this PR do?
Whisper feature extractor representation includes the MEL filters, a list of list that is represented as ~16,000 lines. This needlessly spams the command line. I added a `__repr__` method that replaces this list with a string `<array of shape (80, 201)>`

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@ArthurZucker

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Hey, thanks for the contribution! I agree with you, wee should not save the filters as they just depend on the parameters with which they were created, which is why I would be in favor of simply adding the following : 

```python
    def to_dict(self) -> Dict[str, Any]:
        """
        Serializes this instance to a Python dictionary.

        Returns:
            `Dict[str, Any]`: Dictionary of all the attributes that make up this configuration instance.
        """
        output = copy.deepcopy(self.__dict__)
        output["feature_extractor_type"] = self.__class__.__name__
        if "mel_filters" in output:
            del output["mel_filters"]
        return output
```
Also cc @sanchit-gandhi this seems very logitcal to me

**Comment by qmeeus** [comment]
Yes indeed, I think this solution is better

**Comment by ArthurZucker** [comment]
For the remaining failing test, I suggest you rebase on main 😉

**Comment by ArthurZucker** [comment]
You can also modify the test to make the CI go green 😉

**Review by sanchit-gandhi — COMMENTED** [review]
Very useful PR, thanks @qmeeus! Feel free to ping us if you need a hand getting the last test to pass 🤗

**Review by ArthurZucker — APPROVED** [review]
Thanks a lot for working on this

**Review by sgugger — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
