### PR TITLE
Fix imports of TF MobileViT

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

Small cleanup in the main init.

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]

**Review by ydshieh — APPROVED** [review]
Very nice!

**Comment by ydshieh** [comment]
Sorry, but I am a bit confused why I can still import that attribute without failure on current `main` ...? Am I missing anything?

**Comment by sgugger** [comment]
It's only the type hints that are wrong, not the actual init.

**Comment by ydshieh** [comment]
> It's only the type hints that are wrong, not the actual init.

Yeah, just figure it out after I posted. Deleted it but you are too fast to answer

**Comment by sgugger** [comment]
Failures are related to Hub being down, so no blocker to merge.

**Pull request merged**
