### PR TITLE
remvoe `_create_and_check_torch_fx_tracing` in specific test files

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Remvoe `_create_and_check_torch_fx_tracing` in specific model test files, as the common one can handle them correctly.
The only exception is `Hubert` model, but we can also remove it, and set `fx_compatible` to `False` (just as for `Wav2Vec2`).

It might be better to add `torch_script_compatible` to handle `Hubert` and related models.

**Motivation**: Make the change in #18547 available to all tests.

### CODE REVIEW

**Comment by michaelbenayoun** [comment]
The common case test for TorchScript, and if I recall correctly there was an issue for those models on that aspect?

You suggest to add a flag called `torch_script_compatible`? If so, [that is what I suggested back then](https://github.com/huggingface/transformers/pull/17206#discussion_r875989932), pinging @sgugger here.

Also, I think that some of those models can actually be torchscripted with torch 1.12, but the issue was that we are (were?) testing in torch 1.11.

**Comment by ydshieh** [comment]
> The common case test for TorchScript, and if I recall correctly there was an issue for those models on that aspect?

There might be before. But as far as I can tell, the issue probably came from the input and label names preparation. As the tests pass after I remove their re-definitions from the specific model test files, I think it's fine and better to clean them up. (The only failure is from Hubert).

> You suggest to add a flag called torch_script_compatible? 

This is to allow torch trace test still run while skip the torch script test, as currently Hubert test will fail on torchscript.
But I would prefer to add this flag (if the idea is approved) in a separate PR (and where we can enable the test for Wav2Vec2 too, for example)

> Also, I think that some of those models can actually be torchscripted with torch 1.12, but the issue was that we are (were?) testing in torch 1.11.

We can re-evaluate this, but again, let's not to do changes regarding this part in this PR.

This PR is merely to avoid overwriting `_create_and_check_torch_fx_tracing` unnecessary :-)

**Review by sgugger — APPROVED** [review]
Thanks for cleaning this up. Re-new flag, I am still opposed for the same reasons as in the comment linked above. Everything should be controlled by one `fx_compatible` flag, we don't want multiple ones :-)

**Comment by ydshieh** [comment]
@michaelbenayoun If this PR is OK on your side,  I am going to merge. Regarding the flag, let's see what we can do in a separate PR.

**Pull request merged**
