### PR TITLE
Docker image: keras-nlp<0.14 pin

### PR DESCRIPTION
**Pull request by gante**
Temporary PR to update the docker image

### CODE REVIEW

**Comment by gante** [comment]
this doesn't look right either 🤔

**Comment by ArthurZucker** [comment]
If the docker images are build correctly, the dev tag should exist

**Comment by gante** [comment]
pushed image, closing the PR

**Comment by amyeroberts** [comment]
@gante it seems something hasn't worked as there's still failures on the CI due keras

**Comment by gante** [comment]
This does not seem to be triggering [the build job](https://github.com/huggingface/transformers/actions/workflows/build-ci-docker-images.yml), despite having the correct commit message (see [here](https://github.com/huggingface/transformers/blob/cf85e86e9ad22ddd02c519d21c4783e3dbf72178/.github/workflows/build-ci-docker-images.yml#L25))

Could it be because the branch is from my fork, as opposed to from the repo? Going to test it

**Comment by gante** [comment]
Yup, that was it!

**Pull request closed without merging**
