### PR TITLE
Add random seed for generation

### PR DESCRIPTION
**Pull request by mokeyish**
# What does this PR do?

Add a random seed to GenerationConfig, such that with the same `seed` and parameters should return the same result.

openai adds a seed parameter to control the return of the same results, making it easier to reproduce the results and troubleshoot problems.

https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L5392

I would like to cc @ArthurZucker and @younesbelkada review my PR.

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks! In principle this looks good, however perhaps there is already a canonical way to set a seed in `generate`, what do you think @gante ?

**Comment by gante** [comment]
Hi @mokeyish 👋 

We already have a `set_seed` function in `transformers` ([doc](https://huggingface.co/docs/transformers/v4.35.2/en/internal/trainer_utils#transformers.set_seed)), which you can call as follows for complete reproducibility:

```py
from transformers import set_seed
# code to load the model

set_seed(0)
# generate code here
```

Would this solve your use case? 🤗 We want to avoid adding flags and further complexity to generate, unless strictly needed.

**Comment by mokeyish** [comment]
@gante This seed is passed in through the http RestAPIs, and your solution is a global setting, which is the same as before to make model training reproducible. But global settings, different API calls should conflict, right?

**Comment by gante** [comment]
In theory, yes. In practice, we're not interested in adding complexity to `generate` unless widely requested by the community -- our ability to maintain features is limited :) 

I haven't seen request for it, but I'll do my standard bargain: if this comment gets 10 reactions or more, it means users are actively looking for it. In that case, I'd be happy to include it in `transformers` 🤗 

(the person that does the 10th reaction: please ping me)

**Pull request closed without merging**
