### PR TITLE
Add type hints Yoso Pytorch

### PR DESCRIPTION
**Pull request by F02934**
# What does this PR do?
Add missing Type Hints for Yoso pytorch 
#16059 

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@Rocketknight1

### CODE REVIEW

**Comment by F02934** [comment]
Hello @Rocketknight1 I finished with yoso pytorch

**Comment by F02934** [comment]
I updated the file after running make fixup and now it passed all checks

**Comment by F02934** [comment]
@Rocketknight1 thank you! I will just leave as it is because I'm afraid to mess up. 
I will finish yolo tomorrow!

**Comment by Rocketknight1** [comment]
Sorry, you're completely right! The type hints for Yoso are ready to go.

I investigated the extra Italian documentation added by this PR, though - I think the problem there is that your PR branch was created as a branch of an existing PR branch, which was probably working on translation fixups. As a result, it sort of carries changes from both branches!

The simplest way to fix this would be to close this PR, make a new branch starting from `main` this time, and then just copy the changes in `modeling_yoso.py` to that branch, and finally open a PR from that new branch. Is that okay? I'll try to review it quickly if you do, since I've already checked your type hints, lol

**Comment by F02934** [comment]
@Rocketknight1 alright. I will do it right now!

**Pull request closed without merging**
