### PR TITLE
Install `sentencepiece` in `DeepSpeed` CI image

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Install `sentencepiece` in `DeepSpeed` CI image. 
  - The new base image has no `sentencepiece` pre-installed, but it's required for DeepSpeed CI tests
  - With this PR, the tests all pass (on single GPU runner)

### CODE REVIEW

**Review by stas00 — CHANGES_REQUESTED** [review]
If `sentencepiece` is required by deepspeed tests, let's add it to setup.py's `deepspeed-testing` group instead?

**Comment by ydshieh** [comment]
It's done :-) as suggested

**Review by stas00 — APPROVED** [review]
Perfect, thank you, @ydshieh

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Pull request merged**
