### PR TITLE
[Mask2Former] Add doc tests

### PR DESCRIPTION
**Pull request by NielsRogge**
# What does this PR do?

This PR ensures that the code snippet's in Mask2Former's docs work as intended, and are tested.

### CODE REVIEW

**Comment by NielsRogge** [comment]
@ydshieh not sure why CI is failing, running `make fixup` locally doesn't result in any updates. My version is black 22.3

**Comment by ydshieh** [comment]
@NielsRogge mine is also 22.03, but it reformates the modeling file. Not sure why though, do you want me to push? I can also post the whole content of `pip freeze` for you to check the package versions.

**Comment by NielsRogge** [comment]
Feel free to push a commit :)

**Comment by ydshieh** [comment]
I pushed a commit. Actually, you are right. `make fixup` will change the files twice in the run, and that 2 changes cancel each other's change. I am not sure why. After running `make style` to fix some issues, it then works for `make fixup` too.

**Review by sgugger — APPROVED** [review]
Thanks for adding those!

**Review by alaradirik — APPROVED** [review]
Thank you for adding these!

**Pull request merged**
