### PR TITLE
Autocast

### PR DESCRIPTION
**Pull request by jiqing-feng**
Enable autocast in the pipeline.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Hi @jiqing-feng, thanks for opening a PR and contributing to the library! Let us know when it's ready for final review. 

Could you provide some more context on what this addresses and how this should be used - ideally with an example snippet? I'm assuming to enable FA2?

As it's already possible to pass in a pretrained model which has been instantiated with a specific dtype e.g. `torch_dtype=torch.float16` or `torch_dtype="auto", there might be an interplay which should be tested to make sure no unexpected behaviour happens. 

cc @Narsil

**Comment by sywangyi** [comment]
@yao-matrix

**Comment by jiqing-feng** [comment]
Hi @amyeroberts . I am sorry that I don't understand what is FA2 (Flash Attention?).

The motivation from a bug, and we can reproduce it by the following script:
```python
from transformers import pipeline
from datasets import load_dataset
from datasets import Audio
import torch

minds = load_dataset("PolyAI/minds14", name="de-DE", split="train")
minds = minds.cast_column("audio", Audio(sampling_rate=16_000))
example = minds[0]

asr = pipeline("automatic-speech-recognition", model="maxidl/wav2vec2-large-xlsr-german", torch_dtype=torch.bfloat16)
output = asr(example["audio"]["array"])
```

The ASR pipeline does not support bf16, so I think we could enable `autocast` to fix the problem.

**Comment by jiqing-feng** [comment]
Hi @amyeroberts @Narsil . What do you think about this PR? I could enable autocast or full low-precision on the ASR pipeline.

**Comment by Narsil** [comment]
Hi @jiqing-feng,

Why cannot you wrap `autocast`  directly on the pipeline calls themselves ?

Also note that I've bitten hard by autocast it creates slower that it should inference pretty fast because of all the data movement. In my experience it' s almost always better to add the proper types where needed manually to get good performance.

**Pull request closed without merging**
