### PR TITLE
Update `Wav2Vec2ProcessorWithLM` doc example

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

The doctest for this doc example starts to fail. Even I roll back to commits a few days ago, it still fails. I think it's a dataset issue, so just updating the expected values.

### CODE REVIEW

**Comment by ArthurZucker** [comment]
I would rather make sure that the dataset was indeed changed! But otherwise ok for this

**Comment by ydshieh** [comment]
> I would rather make sure that the dataset was indeed changed! But otherwise ok for this

It's caused by the new release of `datasets==2.11.0` yesterday.

**Comment by amyeroberts** [comment]
> It's caused by the new release of datasets==2.11.0 yesterday.

@ydshieh I'm assuming yes, but if we pin to an old version of datasets, do we have the old values?

**Comment by ydshieh** [comment]
> > It's caused by the new release of datasets==2.11.0 yesterday.
> 
> @ydshieh I'm assuming yes, but if we pin to an old version of datasets, do we have the old values?

Yes, that's why I see the issue is coming from the datasets version :-)

**Review by amyeroberts — APPROVED** [review]
Thanks for the update and digging into the root cause!

Checking the [dataset on the hub](https://huggingface.co/datasets/common_voice/viewer/en/train), this prediction is (thankfully) more correct. It might be something we should keep track of in case users start reporting different outputs from models with a datasets dependency.

**Review by ArthurZucker — APPROVED** [review]
Thanks for digging! LGTM now

**Pull request merged**
