### PR TITLE
Update Support image on README.md

### PR DESCRIPTION
**Pull request by BritneyMuller**
# What does this PR do?

Updates the Support image linking to our [Expert Acceleration Program Page](https://huggingface.co/support). 

The Marketing + Monetization Team felt this image deserved a refresh to better highlight the incredible Machine Learning Experts at Hugging Face. In addition, we hope this helps drive additional EAP awareness among our brilliant community members in an effort to better support their ML work/roadmaps.

### CODE REVIEW

**Comment by julien-c** [comment]
whenever possible you should compress images using https://tinypng.com/

Here you'd be saving 83% for instance:

compressed image:
new-support (1)

Other than that, looks good to me! cc'ing @gary149 in case he has feedback on the design

**Comment by BritneyMuller** [comment]
> whenever possible you should compress images using https://tinypng.com/
> 
> Here you'd be saving 83% for instance:
> 
> compressed image: new-support (1)
> 
> Other than that, looks good to me! cc'ing @gary149 in case he has feedback on the design

Good catch! Completely slipped my mind. Would you rather I resubmit with a compressed png @julien-c ?

**Review by BritneyMuller — COMMENTED** [review]
Compressed EAP/Support image via tinypng

**Comment by gary149** [comment]
> Other than that, looks good to me! cc'ing @gary149 in case he has feedback on the design

Looks ok to me, but the logo is distorted and maybe the image should be vertically smaller to take less space on the readme?

**Comment by BritneyMuller** [comment]
The logo shouldn't be distorted. Have tested this and the original image was verified/improved by our graphic designer, Bibi. @feconroses if you have any other thoughts?

**Comment by feconroses** [comment]
Looks good to me!

**Comment by Bibi-O** [comment]
Hi! Bibi here. I'll have a look at the issue and resolve it

**Review by BritneyMuller — COMMENTED** [review]
new-support-improved

Let us know if this looks okay now @gary149 @julien-c? Thanks for all your help on this @Bibi-O

**Comment by gary149** [comment]
Ok for me.

**Review by LysandreJik — APPROVED** [review]
Looks great to me, thank you @BritneyMuller!

**Comment by julien-c** [comment]
you should tweet about it @BritneyMuller!

**Pull request merged**
