### PR TITLE
[Longformer] Notebook to train Longformer

### PR DESCRIPTION
**Pull request by ibeltagy**
This PR adds a community notebook that demonstrates how we pretrained Longformer starting from the RoBERTa checkpoint. The same procedure can be followed to convert other existing pretrained models into their Long version.

@patrickvonplaten, @patil-suraj, it would be great if you also check the notebook. Any comments are welcomed.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
BTW @patil-suraj - you can also add your longformer squad notebook to the community notebooks if you want

**Comment by patrickvonplaten** [comment]
Made a copy and added some comments here: https://colab.research.google.com/drive/1kS2yerrLwLnc-hM6PlisFVaJT98kUKRV#scrollTo=4TTSvW8MlKJJ 

I think the use case is really nice! For better engagement with the notebook, I think it can be polished a bit in terms of small code refactoring / better descriptions. I left some TODO: there as suggestions :-)

**Comment by ibeltagy** [comment]
@patrickvonplaten, thanks for the review, the notebook is much better now after incorporating your suggestions.

**Comment by patrickvonplaten** [comment]
Looks great merging!

**Pull request merged**
