### PR TITLE
Fix WhisperNoSpeechDetection when input is full silence 

### LINKED ISSUE #29036: `object of type 'NoneType' has no len()` when trying to use `WhisperNoSpeechDetection`
### System Info

- `transformers` version: 4.38.0.dev0 (5b6fa23 – after merging #28687)
- Platform: macOS-14.2.1-arm64-arm-64bit
- Python version: 3.10.13
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.2
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.2.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@patrickvonplaten @sanchit-gandhi

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
# %%
from transformers import WhisperForConditionalGeneration, AutoProcessor
import torch
import numpy as np

# %%
processor = AutoProcessor.from_pretrained("openai/whisper-base")
model = WhisperForConditionalGeneration.from_pretrained(
    "openai/whisper-base", torch_dtype=torch.float16
)
model.to("mps")

# %%
# 60 seconds of silence
raw_audio = np.zeros((1, 16_000 * 60))
inputs = processor(
    raw_audio,
    return_tensors="pt",
    truncation=False,
    padding="longest",
    return_attention_mask=True,
    sampling_rate=16_000,
)
inputs = inputs.to(model.device, torch.float16)

# %%
result = model.generate(
    **inputs,
    # chosen here to make it trigger the filter:
    no_speech_threshold=0.2,
    logprob_threshold=-0.2,
    # no_speech_threshold requires logprob_threshold, which in turn assumes temperature to be a list/tuple
    temperature=(0.0,),
)
decoded = processor.batch_decode(
    result, skip_special_tokens=False, decode_with_timestamps=True
)
print(decoded)
```
Result:
```pytb
Traceback (most recent call last):
  File "/Users/ondra/test-hf/test.py", line 27, in <module>
    result = model.generate(
  File "/Users/ondra/mambaforge/envs/transformers/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 735, in generate
    sequences = _pad_to_max_length(final_segments, generation_config.pad_token_id, padding="right")
  File "/Users/ondra/mambaforge/envs/transformers/lib/python3.10/site-packages/transformers/models/whisper/generation_whisper.py", line 148, in _pad_to_max_length
    pad_length = max_total_length - len(sequences[i])
TypeError: object of type 'NoneType' has no len()
```

### Expected behavior

Should not error out, should output `['']`.

### PR DESCRIPTION
**Pull request by ylacombe**
# What does this PR do?

@cifkao found an edge case that happens when the input of Whisper.generate is a full silence. This is a simple tentative PR.

cc @sanchit-gandhi 

Fixes #29036

### CODE REVIEW

**Comment by ylacombe** [comment]
I want to add a test, but I realized most of the slow tests of Whisper were failing, independently of this PR. 
cc @sanchit-gandhi

**Comment by cifkao** [comment]
Seems to work for me!

**Comment by ArthurZucker** [comment]
Do you need a review @ylacombe ?

**Comment by ylacombe** [comment]
I do, thanks !

**Review by ArthurZucker — APPROVED** [review]
😉

**Pull request merged**
