### PR TITLE
[tests] skip tests for xpu 

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?

This PR skips some tests for xpu, as xpu doesn't have that feature yet.

### CODE REVIEW

**Comment by faaany** [comment]
@amyeroberts

**Review by amyeroberts — APPROVED** [review]
Thanks for adding! 

In the future we might want something more general for other accelerators s.t. we can pass in e.g. a list to configure the decorator instead of having to have one per hardware

cc @ydshieh for reference

**Comment by ydshieh** [comment]
> In the future we might want something more general for other accelerators s.t. we can pass in e.g. a list to configure the decorator instead of having to have one per hardware

Good pint!

@faaany I am a bit confused by the changes like

```
    @require_non_xpu
    @require_torch_gpu
```

Previously, it was already has `@require_torch_gpu`, how were that/those tests be triggered on a xpu device ...?

**Comment by faaany** [comment]
Hi @ydshieh , this test will not run on XPU. But we end up with `this test require torch gpu` as message, but we are not sure whether this could run on xpu or not. `require_non_xpu` is more specific, so we know that this test is skipped because xpu doesn't have that feature yet.

**Comment by ydshieh** [comment]
Ah yeah, good point! Thanks for explaining.

**Pull request merged**
