### PR TITLE
Support ViT model in EncoderDecoder

### PR DESCRIPTION
**Pull request by abhishekkrthakur**

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
The idea is to use ViT as the encoder and then a LM as the decoder for Image captioning generation, *e.g.*? @patil-suraj and I were also thinking of using `EncoderDecoder` for Speech2Text. 

At the moment, I see two solutions: -> adapt `EncoderDecoder` to be usable for all modalities not just text2text **or** create new classes, *e.g.* a `SpeechEncoderDecoder` and a `VisionEncoderDecoder` since I'm not sure `EncoderDecoder` will be able to handle all the new use-cases. *E.g.* we might end up ending way too many if-else statements that would make the code unreadable... @patil-suraj @abhi1thakur what do you think?

**Comment by patil-suraj** [comment]
Unstale

**Comment by felixdittrich92** [comment]
Huhu,
any update at this ? :) 
a VisionEncoderDecoderModel would be a great also for models which follow in future
for example this one: [https://arxiv.org/abs/2109.10282](url)

**Comment by patrickvonplaten** [comment]
We'll add a new `VisionEncoderDecoder` class for this actually

**Comment by felixdittrich92** [comment]
@patrickvonplaten nice !
Is there any way or need to contribute ? :)

**Comment by LysandreJik** [comment]
Closing this as [VisionEncoderDecoder](https://huggingface.co/docs/transformers/main/en/model_doc/vision-encoder-decoder#vision-encoder-decoder-models) now exists.

**Comment by Leonardbrett** [comment]
My first investment with Catherine gave me profits of over $7,000 and ever since then she has never failed to deliver and I can even say she's the must sincere broker I have ever known'' communicate with her to be a successful investor. On Facebook Catherine Russell

**Pull request closed without merging**
