### PR TITLE
[doc] Add references to the fine-tuning blog and distil-whisper to Whisper.

### PR DESCRIPTION
**Pull request by Vaibhavs10**
[doc] Add references to the fine-tuning blog and distil-whisper to Whisper.

# What does this PR do?

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

## Who can review?

cc: @sanchit-gandhi

### CODE REVIEW

**Review by sanchit-gandhi — APPROVED** [review]
Awesome, thanks @Vaibhavs10! Looks like there are some style tests failing. Could you rebase onto main to try and eradicate these?

**Review by amyeroberts — APPROVED** [review]
Thanks for adding these resources!

**Comment by Vaibhavs10** [comment]
I think I messed up the merge! Whilst rebasing

I synced my fork with transformers followed by 

1. `git pull`
2. `git checkout <BRANCH>`
3. `git rebase main`
4. `git push --origin force`

Where did I go wrong lol?

**Comment by amyeroberts** [comment]
> * `git pull`
> * `git checkout <BRANCH>`
> * `git rebase main`
> * `git push --origin force`

@Vaibhavs10 A few questions to try and figure out what happened: 
* `I synced my fork with transformers`: How did you do this? Which branch was "synced"? 
* `git pull` on which branch are you pulling to and from? What is your default pull settings i.e. does running `git pull` do a merge or a rebase? 
* `git rebase main` I'm guessing this was on the feature branch? 

A few things might have happened. I suspect the culprit for any unexpected behaviour here is the pull, as it might have introduced merge commits. Working on my feature branch, these are the steps I normally take: 

```
git fetch upstream main
git rebase upstream/main
# My gitconfig settings will always push to the current branch by default
git push -f 
```

You don't technically need to update your main branch, you just need to fetch the most recent commits from upstream. 

The git history looks like what happens if one pulls then force pushes. The good new is, this can be rectified by rebase on main (no pulls!) and force pushing again.

**Comment by Vaibhavs10** [comment]
Thanks @amyeroberts - I synced via `git fetch upstream main` too. @sanchit-gandhi pointed out that I used `git push --force origin` instead of `git push --force origin` - hence the commits.

I followed your advice and that seems to have fixed the conflicts.

Wow! git is hard - thank you for being so patient and explaining this to me.

You both are the best! 🤗

Note: the code quality checks now pass haha!

**Comment by amyeroberts** [comment]
@Vaibhavs10 Do you have permission to merge? If not, I can do it for you

**Comment by Vaibhavs10** [comment]
Nope nope - would be great if you can merge. 🤗

Thanks again!

**Pull request merged**
