### PR TITLE
[`ViTHybrid`] + [`BiT`] cleaner `__init__`

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

a function in `BiT` is not needed, thus this PR makes the codebase less error-prone.
Before that, to get the feature maps size from the backbone model, `ViTHybrid` assumed that the backbone has the method `_get_feature_map` which is not the case for all backbones.

Related #20645

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Look reasonable. Let's wait vision expert @NielsRogge 's confirmation though.

**Review by NielsRogge — APPROVED** [review]
Thanks for making it cleaner!

Btw we can add a docstring for `backbone_config` in configuration_vit_hybrid.py, could you do that in this PR?

**Review by sgugger — APPROVED** [review]
Still not happy about the forward done each time there is an init (note that it will probably break the initialization on meta device) but I don't see any way around it right now, and we can always fix it later.

LGTM in the meantime!

**Comment by younesbelkada** [comment]
Yes, this can be addressed in a future PR

**Pull request merged**
