### PR TITLE
make opt checkpoint dir name correct

### PR DESCRIPTION
**Pull request by dumpmemory**
# What does this PR do?
I found i can't load the converted checkpoint with tp_8 pp_1 dp_1 or tp_4 pp_2 dp_1, only tp 2 pp 2 dp 2 works. I check the code and found it might be the opt dir name issue. so i just fix it. and it works on my side. 

Fixes # (issue)
https://github.com/huggingface/accelerate/issues/1088
#https://github.com/huggingface/accelerate/issues/1088

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
cc @pacman100

**Comment by sgugger** [comment]
Friendly ping @pacman100

**Comment by sgugger** [comment]
@pacman100 ?

**Review by pacman100 — APPROVED** [review]
Thank you @dumpmemory for fixing this issue. I went over the code in Megatron-LM to verify the changes, below is the relevant snippet:
```
if not pipeline_parallel:
        common_path = os.path.join(checkpoints_path, directory,
                            f'mp_rank_{tensor_rank:02d}')
    else:
        common_path = os.path.join(checkpoints_path, directory,
                        f'mp_rank_{tensor_rank:02d}_{pipeline_rank:03d}')

    if use_distributed_optimizer:
        model_name = os.path.join(common_path, "model_rng.pt")
        optim_name = os.path.join(
            common_path + "_%03d" % mpu.get_data_parallel_rank(),
            "optim.pt")
    else:
        model_name = optim_name = os.path.join(common_path, "model_optim_rng.pt")
```

As per this, the naming convention follows tensor rank, pipeline rank and data parallel rank, in that order, respectively. Your changes look good to me as you have correctly changed them . Thank you!  🤗

Given that you have verified that it works on your end, it looks good to be merged.

**Review by sgugger — APPROVED** [review]

**Pull request merged**
