### PR TITLE
fix AutoTP in deepspeed could not work for bloom

### PR DESCRIPTION
**Pull request by sywangyi**
# What does this PR do?

Fixes # (issue)
fix AutoTP in deepspeed could not work for bloom

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

<!-- Your PR will be replied to more quickly if you can figure out the right person to tag with @

 If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.
 Please tag fewer than 3 people.

Models:

- text models: @ArthurZucker and @younesbelkada

- deepspeed: HF Trainer: @stas00

### CODE REVIEW

**Comment by sywangyi** [comment]
should work with https://github.com/microsoft/DeepSpeed/pull/3035

**Comment by sywangyi** [comment]
@sgugger please help review

**Comment by sywangyi** [comment]
@yao-matrix

**Review by sgugger — APPROVED** [review]
LGTM! Thanks for the fix!

**Comment by sgugger** [comment]
Actually, just checked the modeling file and this function is only used in this class, so it would be cleaner to just make it a method. What do you think?

**Comment by sywangyi** [comment]
@sgugger I see code like "from transformers.models.bloom.modeling_bloom import build_alibi_tensor" in petals, if we make this a method, the petals code needs to be changed as well.

**Comment by sgugger** [comment]
Ok so let's keep it as a function in that module. I'd still prefer a real method (that directly returns the result of the function) to setting a function attribute like this if you don't mind.

**Comment by sywangyi** [comment]
@sgugger update the PR.

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
