### PR TITLE
Adds type checking to PreTrainedConfig.

### LINKED ISSUE #20915: Comparing a huggingface config with a dictionary raises an error as the `__eq__` method relies on `other` having a `__dict__` method
`PreTrainedConfig`s inherit their `__eq__` methods from this:  https://github.com/huggingface/transformers/blob/3f936df66287f557c6528912a9a68d7850913b9b/src/transformers/configuration_utils.py#L736

This works fine for comparing two configs, but if you compare a config to something of a different type, (in particular a type without a `__dict__` attribute, like a pure `dict`), it throws an error. It would be easy to add a type check into the equals comparison to ensure that off-type comparisons return False instead.

### PR DESCRIPTION
**Pull request by mmcdermott**
# What does this PR do?

Fixes [# (issue)](https://github.com/huggingface/transformers/issues/20915)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for the fix!

**Comment by sgugger** [comment]
Mmm, the tests are all failing for weird reasons. It seems the branch you are using for the PR is pretty outdated compared to main. Could you do a quick rebase?

**Comment by mmcdermott** [comment]
Huh... sorry, I thought I corrected that before pushing. I'll do a rebase and get things squared away.

**Comment by sgugger** [comment]
Thanks a lot!

**Pull request merged**
