### PR TITLE
Fix typo: indinces -> indices

### PR DESCRIPTION
**Pull request by bryant1410**

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Looks good, thanks! Just make sure to run `make style` to have our scripts automatically fix the files you changed.

**Comment by bryant1410** [comment]
> Looks good, thanks! Just make sure to run `make style` to have our scripts automatically fix the files you changed.

Oh. So should I send a new patch with the changes after running `make style`?

**Comment by sgugger** [comment]
I'm not following. Your last commit had the styling changes so all is good.

**Comment by bryant1410** [comment]
> I'm not following. Your last commit had the styling changes so all is good.

Oh. But if I run `make style` I see tons of changes (193 files changed, 754 insertions(+), 2969 deletions(-)). For example, this file:

```diff
diff --git a/examples/adversarial/utils_hans.py b/examples/adversarial/utils_hans.py
index bf0623ff..17d4a8c4 100644
--- a/examples/adversarial/utils_hans.py
+++ b/examples/adversarial/utils_hans.py
@@ -112,10 +112,7 @@ if is_torch_available():
             cached_features_file = os.path.join(
                 data_dir,
                 "cached_{}_{}_{}_{}".format(
-                    "dev" if evaluate else "train",
-                    tokenizer.__class__.__name__,
-                    str(max_seq_length),
-                    task,
+                    "dev" if evaluate else "train", tokenizer.__class__.__name__, str(max_seq_length), task,
                 ),
             )
             label_list = processor.get_labels()
@@ -281,10 +278,7 @@ class HansProcessor(DataProcessor):
 
 
 def hans_convert_examples_to_features(
-    examples: List[InputExample],
-    label_list: List[str],
-    max_length: int,
-    tokenizer: PreTrainedTokenizer,
+    examples: List[InputExample], label_list: List[str], max_length: int, tokenizer: PreTrainedTokenizer,
 ):
     """
     Loads a data file into a list of ``InputFeatures``
```

**Comment by sgugger** [comment]
Are you sure you have proper versions of black/isort/flake8 ? Run `pip install -e .[dev]` in the repo to make sure you have them.

**Comment by bryant1410** [comment]
Oh, yeah, it was that. Silly mistake. :hand: Sorry for the noise!

**Comment by sgugger** [comment]
Np!

**Pull request merged**
