### PR TITLE
add 1 to cur_len to make up the new beam length

### PR DESCRIPTION
**Pull request by jimmieliu**
# What does this PR do?
cur_len is 1 token shorter comparing to the length of the sequence whose best_sum_logprobs is the numerator.

Fixes # (issue)
add 1 to cur_len

## Who can review?
@LysandreJik

### CODE REVIEW

**Comment by sgugger** [comment]
cc @gante

**Review by gante — COMMENTED** [review]
Hey @jimmieliu -- great catch! I've confirmed that:
a) this is indeed a bug, we are off-by-one when computing the stopping condition (but not when we store the score)
b) TF and FLAX do not have this problem

I have one request, though :) Instead of changing `cur_len` to `cur_len+1` here, I'd suggest fixing the `cur_len` variable itself (as it is not holding the value it claims to hold, according to its name). My suggestion would be to add `cur_len += 1` on L289 and L618 🤗

**Comment by jimmieliu** [comment]
@gante Thx for the great advice. You are suggesting a better coding style.

**Review by gante — APPROVED** [review]
Thanks for making `transformers` a little bit better 💛

**Pull request merged**
