### PR TITLE
Fix gradient checkpointing bug in LongT5

### PR DESCRIPTION
**Pull request by KMFODA**
This PR fixes a bug that a user can encounter while using generate and models that use gradient_checkpointing.

Fixes Issue https://github.com/huggingface/transformers/issues/21737

cc @younesbelkada or @gante

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for this! Surprisingly the `warning_once` call was not present on LongT5Stack: https://github.com/huggingface/transformers/blob/main/src/transformers/models/longt5/modeling_longt5.py#L1503-L1504

**Comment by KMFODA** [comment]
No problem! Yeah I added it because I thought it was incorrectly omitted from LongT5Stack. Should it be removed?

**Comment by younesbelkada** [comment]
I think your changes are fine and it was something we forgot to add on our side at the first place !

**Review by amyeroberts — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
