### PR TITLE
Fixed quantization error in modules that use register_buffer

### LINKED ISSUE #29201: Quantization Error: register_buffer is not in module_parameters.
### System Info

Not a system issue. Code issue.

### Who can help?

_No response_

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Code:
~~~
import torch
from transformers.models.deformable_detr.modeling_deformable_detr import DeformableDetrModel
from transformers import BitsAndBytesConfig


bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        llm_int8_skip_modules=[
            'deformable_detr_model',
        ],
        bnb_4bit_compute_dtype=torch.float32,
    )
model = DeformableDetrModel.from_pretrained("SenseTime/deformable-detr", device_map="cuda:0", torch_dtype=torch.half, quantization_config=bnb_config)
~~~

### Expected behavior

Log:
~~~
Traceback (most recent call last):
  File "/selfsup/a.py", line 13, in <module>
    model = DeformableDetrModel.from_pretrained("SenseTime/deformable-detr", device_map="cuda:0", torch_dtype=torch.half, quantization_config=bnb_config)
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 3926, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py", line 802, in _load_state_dict_into_meta_model
    or (not hf_quantizer.check_quantized_param(model, param, param_name, state_dict))
  File "/usr/local/lib/python3.10/dist-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 124, in check_quantized_param
    if isinstance(module._parameters[tensor_name], bnb.nn.Params4bit):
KeyError: 'bias'
~~~

### PR DESCRIPTION
**Pull request by DonggeunYu**
# What does this PR do?

Fixed quantization error in modules that use register_buffer.
When using `self.register_buffer`, it is included in `state_dict`, but not in `_parameters`, which is why first validate that `tensor_name` exists in `_parameters` before searching for it by `tensor_name` in `_parameters`.

Fixes #29201

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

- quantization (bitsandbytes, autogpt): @SunMarc and @younesbelkada

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Great catch ! can you confirm the 4bit tests pass for you ? 

```bash
RUN_SLOW=1 pytest tests/quantization/bnb/test_4bit.py
```

If they pass I think we can safely merge the PR, depending on your hardware you might get some failure with respect to generated texts, for that you can simply check if you get the same failures between main branch and yours

**Comment by DonggeunYu** [comment]
@younesbelkada 

`RUN_SLOW=1 pytest tests/quantization/bnb/test_4bit.py` output:
~~~
=================================== short test summary info ===================================
FAILED tests/quantization/bnb/test_4bit.py::BaseSerializationTest::test_serialization - ValueError: Supplied state dict for model.decoder.layers.0.fc1.weight does not contain `bi...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_fp4_double_safe - ValueError: Supplied state dict for model.decoder.layers.0.fc1.weight does not contain `bi...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_fp4_double_unsafe - ValueError: Supplied state dict for model.decoder.layers.0.self_attn.k_proj.weight does no...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_fp4_single_safe - ValueError: Supplied state dict for model.decoder.layers.0.fc1.weight does not contain `bi...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_fp4_single_unsafe - ValueError: Supplied state dict for model.decoder.layers.0.self_attn.k_proj.weight does no...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_nf4_double_unsafe - ValueError: Supplied state dict for model.decoder.layers.0.self_attn.k_proj.weight does no...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_nf4_single_safe - ValueError: Supplied state dict for model.decoder.layers.0.fc1.weight does not contain `bi...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_nf4_single_unsafe - ValueError: Supplied state dict for model.decoder.layers.0.self_attn.k_proj.weight does no...
FAILED tests/quantization/bnb/test_4bit.py::ExtendedSerializationTest::test_serialization - ValueError: Supplied state dict for model.decoder.layers.0.fc1.weight does not contain `bi...
FAILED tests/quantization/bnb/test_4bit.py::BloomSerializationTest::test_serialization - ValueError: Supplied state dict for transformer.h.0.mlp.dense_4h_to_h.weight does not cont...
FAILED tests/quantization/bnb/test_4bit.py::GPTSerializationTest::test_serialization - ValueError: Supplied state dict for transformer.h.0.attn.c_attn.weight does not contain `b...
============= 11 failed, 27 passed, 1 skipped, 29 warnings in 1628.99s (0:27:08) ==============
~~~

**Review by SunMarc — APPROVED** [review]
LGTM !

**Review by younesbelkada — APPROVED** [review]
Thanks again @DonggeunYu ! 
Just to confirm one last point, could your re-run the bnb tests with `bitsandbytes==0.42.0` ?

**Comment by DonggeunYu** [comment]
> Thanks again @DonggeunYu ! Just to confirm one last point, could your re-run the bnb tests with `bitsandbytes==0.42.0` ?

But, the same 11 failed...

**Comment by DonggeunYu** [comment]
🥲
https://github.com/huggingface/transformers/pull/29329

**Comment by DonggeunYu** [comment]
> @DonggeunYu Am I correct in understanding this PR was superceded by #29329? If so, apologies for the delay in reviewing this, and we should close this PR. Please don't hesitate to ping me on a PR if there's a delay in response - thee's a lot of notifications and sometimes they slip through the cracks.

Yes, that's right. I understand. Thank you 😊

**Pull request closed without merging**
