### PR TITLE
[WIP - don't merge][TF generate] Make tf generate compatible with tf.function

### PR DESCRIPTION
**Pull request by patrickvonplaten**
The tf generate function shoud be cleaned up so that it can be used with tf.function.

### CODE REVIEW

**Comment by DarkIntegral** [comment]
is this still being worked on?

**Comment by patrickvonplaten** [comment]
I won't be able to take a look in the next ~2 weeks. Feel free to continue the PR :-)

**Comment by gyin-ai** [comment]
@patrickvonplaten can I ask whether this change is still working on? Will we be able to get one example for greedy search with tf function compatible? Thanks.

**Comment by desaibhargav** [comment]
Thank you for all the amazing work! This library is too good to be true and this would be a really good feature to have if possible and when possible!

**Pull request closed without merging**
