### PR TITLE
Fix: siglip image processor rgb_convert is not being applied correctly.

### PR DESCRIPTION
**Pull request by jp1924**
# What does this PR do?

```python
        # All transformations expect numpy arrays.
        images = [to_numpy_array(image) for image in images]

        if do_convert_rgb:
            images = [convert_to_rgb(image) for image in images]
```
The convert_to_rgb function is not being applied because ndarray values are being input 
(convert_to_rgb simply returns the input value if it's not a PIL.Image).

If an image with RGBA or similar format is input, the conversion doesn't work properly, 
causing the following error in the infer_channel_dimension_format method:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/image_utils.py", line 254, in infer_channel_dimension_format
    raise ValueError("Unable to infer channel dimension format")
ValueError: Unable to infer channel dimension format
```

`transformers` version: 4.46.0.dev0

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@amyeroberts

### CODE REVIEW

**Review by molbap — APPROVED** [review]
Good catch @jp1924 ! - I checked, it seems Siglip was the only exception with the wrong order of operations.

**Comment by jp1924** [comment]
@molbap 
Oh, thank you for reviewing.
Separately, I noticed that `do_convert_rgb` is not implemented in [ViTImageProcessor](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vit/image_processing_vit.py#L233-L239). Was this intentional?

**Comment by molbap** [comment]
There's no particular reason why - I have no opposition to introducing this in another PR :)

**Comment by jp1924** [comment]
@molbap 
Oh yeah? So I can just open the PR and add it?

**Review by qubvel — APPROVED** [review]
Thanks for the fix, indeed convert_rgb is not supported for numpy arrays! I suppose we can merge this fix!

Also would be great to update `convert_rgb` to avoid silently skipping numpy arrays.

**Review by ArthurZucker — APPROVED** [review]
thanks 🤗

**Pull request merged**
