### PR TITLE
Pin torch version to < 2.3

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Recent pytorch release breaks a bunch of tests on our CI 😢 

Pinning until resolved to avoid blocking for PR merges.

Example of failing run: https://app.circleci.com/pipelines/github/huggingface/transformers/90724/workflows/055d784f-ff15-412e-8033-9ebf8a5fa498/jobs/1184589

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks!

**Comment by amyeroberts** [comment]
cc @ydshieh Am I missing anything here?

**Comment by ydshieh** [comment]
LGTM. Not sure if we should change the dockerfile and 

examples/pytorch/_tests_requirements.txt

but the priority is to make CircleCI green I guess?

**Comment by amyeroberts** [comment]
@ydshieh Good point about the examples - I've added a pin. 

Re the dockerfile, which one are we talking about? (`transformers-gpu`?). As you say - it's really for CI, so I think it's OK to leave. If people complain, we can pin, WDYT?

**Comment by ydshieh** [comment]
Yes, leave those dockerfile is OK. Let's have daily CI run with torch 2.3 and see how it goes. I will check tomorrow and see what to do.

**Comment by ydshieh** [comment]
I am not sure, but I still see (at least in torch job)

```
torch==2.3.0
torchaudio==2.2.2
torchvision==0.17.2
```

maybe it's cache issue. I can take a look. But the fast way is to increase the cache version `cache_version` from `0.8.2` to anything new like `0.8.3`

**Comment by amyeroberts** [comment]
@ydshieh OK, thanks for helping out with this! Shall I remove the increment cache commit?

**Comment by ydshieh** [comment]
No, you can keep using the new version number it's fine.

**Comment by ydshieh** [comment]
if --no-deps not working, try change the order of install lines or try to reinstall torch after accelerate (not ideal, but if we just want to have green CI for now)

**Comment by amyeroberts** [comment]
Woo hoo! Only failing on non-torch related issues. Closing as compatibility is fixed in #30459

**Pull request closed without merging**
