### PR TITLE
Use next-gen CircleCI convenience images

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Use next-gen CircleCI convenience images.

From [CircleCI page](https://circleci.com/docs/circleci-images?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-maxConv-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAjwrNmWBhA4EiwAHbjEQJ4yXbmT654kFoIgTkjKea44E56-j7BGvVrqOkVAwCq97F_Je6EsohoC0OkQAvD_BwE):

*Legacy images with the prefix “circleci/” were deprecated on December 31, 2021. For faster builds, upgrade your projects with next-generation convenience images.*

It mentions [the following](https://circleci.com/docs/circleci-images?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-dsa-maxConv-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAjwrNmWBhA4EiwAHbjEQJ4yXbmT654kFoIgTkjKea44E56-j7BGvVrqOkVAwCq97F_Je6EsohoC0OkQAvD_BwE#next-generation-convenience-images): 
- Faster spin-up time (but I didn't measure the spin-up time)
- Improved reliability and stability 

There are some tiny things I observed: for example, running new images on GCP VM, I can use arrow up to get to the previous commands.

### CODE REVIEW

**Comment by sgugger** [comment]
Can you just explain why this change is needed? What's better about them?

**Comment by ydshieh** [comment]
> Can you just explain why this change is needed? What's better about them?

Sorry, I forgot to mention them in the description. I updated it. My main motivation is to avoid the deprecated (on December 31, 2021 images).

**Review by sgugger — APPROVED** [review]
Thanks for the explanation!

**Review by LysandreJik — APPROVED** [review]
LGTM

**Pull request merged**
