### PR TITLE
Update examples/ner/run_ner.py

### PR DESCRIPTION
**Pull request by lifefeel**
Update the example file by changing the name of AlbertForTokenClassification to AlbertForSequenceClassification.

### CODE REVIEW

**Comment by stefan-it** [comment]
Well, I don't think the `SequenceClassification" head is not the right one, as it is supposed for sequence classification/regression tasks (see https://huggingface.co/transformers/model_doc/albert.html#transformers.AlbertForSequenceClassification).

NER requires a per token classification implementation: https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_albert.py#L791

**Comment by srush** [comment]
Will this be fixed by switching to AutoModel? I think we are doing that here for `run_pl_ner.py` https://github.com/huggingface/transformers/pull/3290

**Comment by lifefeel** [comment]
I knew what the problem was.  In version 2.5.1, there is no definition for `AlbertForTokenClassification` in `__init__.py`
However, it is included in the master branch. Version 2.5.1 should be fixed.

**Comment by lifefeel** [comment]
@srush I think using AutoModelForTokenClassification is better than calling each model class. How about making a change to `run_ner.py`?

**Comment by srush** [comment]
Yes, if you can send that PR and add me as a reviewers

**Pull request closed without merging**
