### PR TITLE
Fix Blip-2 CI

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Avoid GPU OOM by using FP16.

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for this! 💯 
Thanks for making the daily-CI green 🍏

**Review by sgugger — COMMENTED** [review]
Mmmm, this is a T5-based model, which usually outputs garbage in FP16. Are you sure the tests pass with this?

**Comment by younesbelkada** [comment]
since we have put `_keep_in_fp32_modules` in a previous PR, I think it should work!

**Comment by ydshieh** [comment]
@sgugger I never merge my PR without running on a CI runner-like machines: ran it 3 times and all pass.

**Review by sgugger — APPROVED** [review]
Thanks a lot then! So is it safe to say we have fully fixed inference in FP16 for T5 models @younesbelkada ?

**Pull request merged**
