### PR TITLE
[gpt-neox] Add attention_bias config to support model trained without attention biases

### PR DESCRIPTION
**Pull request by dalgarak**
# What does this PR do?

This PR adds attention_bias configuration into GPT-NeoX models. Currently released models all use bias by default for the linear layers in attention block, but the GPT-NeoX library allows us to train models without attention bias. (can be trained with use_bias_in_attn_linear=False)

For compatibility with existing models, we set the default value of attention-bias to True. I've done some testing and verified the behavior with attn_implementation="flash_attention_2".

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks for the PR ! We have done this in past but to support inference for models that have attention bias that are pushed on the Hub such as Galactica that uses OPT architecture: https://github.com/huggingface/transformers/pull/20390 
Are there any model on the Hub that uses GPTNeoX architecture with attention bias?

**Comment by dalgarak** [comment]
Best of my knowledge, there are many(and almost) gpt-neox models are on the hub that uses attention bias:
 * pythia scailing suite family, e.g. EleutherAI/pythia-70m (https://huggingface.co/EleutherAI/pythia-70m),
 * polyglot korean LMs, e.g. EleutherAI/polyglot-ko-1.3b (https://huggingface.co/EleutherAI/polyglot-ko-1.3b)
 * and gpt-neox models, e.g. EleutherAI/gpt-neox-20b

and not public released yet(because training is undergoing)- but we want to release a model to hub, which trained with gpt-neox, without attention bias. 

To check attention_bias=False configure, we upload a 'intermediate checkpoint' of model of ours to the hub; see https://huggingface.co/dalgarak/gnx_6.7b_no_attn_bias_test 
(NOTE: public, gated user access but will approve automatically. it will available until this-or related PRs- merged into the main trunk.)

**Review by ArthurZucker — APPROVED** [review]
LGTM, we added something similar to LLama family models. Note that Flash attention does not support bias, ~ which means this is actually great because training a model without bias can lead to better inference~  so thanks for this! 🤗 
EDIT thanks @younesbelkada the bias not supported is the attention bias, which is added to the attention weights 😅

**Comment by dalgarak** [comment]
oh, I found a mistake in argument documentation, fixed it now. Thanks!

**Review by younesbelkada — APPROVED** [review]
Thanks for explaining!

**Pull request merged**
