### PR TITLE
change TokenClassificationTask class methods to static methods

### PR DESCRIPTION
**Pull request by donchev7**
Since we do not require self in the class methods of TokenClassificationTask we should probably switch to static methods. Also, since the class TokenClassificationTask does not contain a constructor it is currently unusable as is. By switching to static methods this fixes the issue of having to document the intent of the broken class.

Also, since the get_labels and read_examples_from_file methods are ought to be implemented. Static method definitions are unchanged even after inheritance, which means that it can be overridden, similar to other class methods.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to the it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Review by JetRunner — APPROVED** [review]
Why not?

**Comment by JetRunner** [comment]
But why doesn't this PR trigger a CI test? @LysandreJik

**Comment by LysandreJik** [comment]
I have no idea, this is the second time it happens. I sent an empty commit on your branch to trigger the build @donchev7.

**Comment by LysandreJik** [comment]
Pinging @stefan-it for review.

**Review by stefan-it — APPROVED** [review]
LGTM!

**Review by LysandreJik — APPROVED** [review]

**Pull request merged**
