### PR TITLE
Added do_lower_case parameters for tokenizer in mlm training.

### PR DESCRIPTION
**Pull request by K-Mike**
Added do_lower_case while training mlm. Useful for training cased BER, for instance.

### CODE REVIEW

**Comment by sgugger** [comment]
Hi there, thanks for your PR!
The examples scripts are kept simple and without too much functionality so users can easily understand and tweak them for their needs (they are just examples, they do not mean to cover **everything**). As you saw, it's super easy to add things like this option, if needed. The PR will stay this to demonstrate how, but I don't think we will merge it.

**Comment by stefan-it** [comment]
As far as I know this is alteady done in the Tokenizer logic. You can define this lower casing option in the `tokenizer_config.json` - and this is done for quite a lot models. I dont't see any reason to have this an extra cli option 🤔

**Comment by K-Mike** [comment]
I just tried to be useful :)

**Comment by sgugger** [comment]
No problem at all. If you want to make sure something you are working on will be accepted, don't hesitate to open an issue about it first, that way we can tell you if it's desirable or not :-)
Be sure to check the [good first issues](https://github.com/huggingface/transformers/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22) if you want to try something else!

**Pull request closed without merging**
