### PR TITLE
[WIP] Add TFSpeech2Text

### PR DESCRIPTION
**Pull request by will-rice**
# What does this PR do?

This PR adds TFSpeech2Text. The issue that requested it was recently closed due to inactivity so I don't think it is being worked on currently. If this is an incorrect assessment, feel free to let me know and I will close this. 

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@patil-suraj 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patil-suraj** [comment]
Gently pinging @stancld to see if he's still working on this :)

**Comment by will-rice** [comment]
@patil-suraj I'm having a little trouble with the generate tests. Should I just do a custom generate function for this model in the modeling file or modify the base generate function to accommodate this model?

**Comment by patil-suraj** [comment]
Sorry to only reply now.

What is the issue with `generate`? Ideally `generate` should work, so let's try to avoid adding a custom `generate`.

**Comment by will-rice** [comment]
This [assert](https://github.com/huggingface/transformers/blob/596bb85f2fabde6c5611cfa2664ddb357e228ec7/src/transformers/generation_tf_utils.py#L624) is the beginning of the issue. This is probably my interpretation of `input_ids`. Since the `input_ids` is changed to `input_features`, all of the generate functions pop the `input_ids` key. I'm going to try to wrap this up today though so I'll figure out what the issue is.

**Pull request closed without merging**
