### PR TITLE
[CLAP] Replace hard-coded batch size to enable dynamic ONNX export

### PR DESCRIPTION
**Pull request by xenova**
# What does this PR do?

This PR unblocks adding ONNX export support for CLAP models in Optimum (see [PR](https://github.com/huggingface/optimum/pull/1552)), by replacing hard-coded batch size in the `window_reverse` function. This was [already done in the past for other similar models](https://github.com/huggingface/transformers/commit/b651efe59ea506d38173e3a60a4228e7e74719f9) (by @lewtun), but since then, [CLAP was added](https://github.com/huggingface/transformers/pull/21370) (by @ArthurZucker), and this change was not brought across there.

Fixes https://github.com/huggingface/optimum/pull/1552#issuecomment-1836233113

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @lewtun @echarlaix

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
LGTM thanks

**Comment by xenova** [comment]
Added back the docstring 👍 - ready to merge imo? :)

**Comment by ArthurZucker** [comment]
Yep just make style and rebase should do the trick for the CIO

**Comment by xenova** [comment]
Done 👍 (failed style seemed to be unrelated; should be fixed now)
image

**Comment by ArthurZucker** [comment]
Thanks 👍🏻

**Pull request merged**
