### PR TITLE
Fix-ci-whisper

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Fixes the failing test. It is related to a modificaiton of the configuration on the hub. https://github.com/huggingface/transformers/pull/21307/files#diff-cf6c12f8da48db4d91bcc6db32ecb7c1609a76e30719b5d47cccf595d326d235 already fixed this before, now just enforcing transciption tasks

### CODE REVIEW

**Comment by ydshieh** [comment]
Hi @ArthurZucker 

I am running on a GCP VM (which is quite close to the CI runner env.), but I still get the same error.
Also this CI failure is shown up on Feb. 22nd, and at that time, I don't see any change on the Hub reop `openai/whisper-large`.
The latest change is only 15-17 ago.

Could you double check the cause and the fix, thank you. Or let me know if I miss something.

**Comment by ArthurZucker** [comment]
image
The tokenizers where properly modified

**Comment by ArthurZucker** [comment]
I ran the tests locally and they passed so not really sure what is happening. Also let's add the TF_call fix for doc daily. It is probably related to a TF PR

**Comment by ydshieh** [comment]
I got the 3rd id is different in `generated_ids` and `EXPECTED_LOGITS` when running this PR. I will check on the acutal CI runner.

```bash
(Pdb) generated_ids
tensor([[50258, 50259, 50359, 50363,  2221,    13,  2326,   388,   391,   307,
           264, 50244,   295,   264,  2808,  5359,   293,   321,   366,  5404],
        [50258, 50259, 50359, 50363,  6966,   307,  2221,    13,  2326,   388,
           391,   311,  9060,  1570,  1880,   813,   702,  1871,    13, 50257],
        [50258, 50259, 50359, 50363,   634,  5112,   505,   300,   412,   341,
         42729,  3196,   295,   264,  1064,    11,   365,  5272,   293, 12904],
        [50258, 50259, 50359, 50363,   634,   575, 12525, 22618,  1968,  6144,
         35617, 20084,  1756,   311,   589,   307,   534, 10281,   934,   439]])
(Pdb) EXPECTED_LOGITS
tensor([[50258, 50259, 50358, 50363,  2221,    13,  2326,   388,   391,   307,
           264, 50244,   295,   264,  2808,  5359,   293,   321,   366,  5404],
        [50258, 50259, 50358, 50363,  6966,   307,  2221,    13,  2326,   388,
           391,   311,  9060,  1570,  1880,   813,   702,  1871,    13, 50257],
        [50258, 50259, 50358, 50363,   634,  5112,   505,   300,   412,   341,
         42729,  3196,   295,   264,  1064,    11,   365,  5272,   293, 12904],
        [50258, 50259, 50358, 50363,   634,   575, 12525, 22618,  1968,  6144,
         35617, 20084,  1756,   311,   589,   307,   534, 10281,   934,   439]])
(Pdb)

```

**Comment by ArthurZucker** [comment]
Okay, checking! I was wrong, the task should be `translate` and not `transcribe`. But the default in the generation config is `translate`. So I am not sure I understand, this should not be failing.

**Comment by ArthurZucker** [comment]
doc test and related slow test both pass locally cc @ydshieh

**Comment by ydshieh** [comment]
> But the default in the generation config is translate. So I am not sure I understand, this should not be failing.

when I run the test and check the generation config in modeling forward, generation config has no task attribute, and `task` argument passed is also `None`. I think it explains things

**Review by ydshieh — APPROVED** [review]
Thank you @ArthurZucker for all the effort and fix.

I confirmed `WhisperModelIntegrationTests::test_large_batched_generation` and doctest for `modeling_tf_whisper.py` work with this PR.

For transparency: we didn't see `test_large_batched_generation` failing on CI before Feb. 22nd. But it actually fails - if we run it manually against previous commits.

On CI runners, we had `Aborted (core dumped)` on `Whisper` job, and that's why we didn't see the failure report regarding it.

**Pull request merged**
