### PR TITLE
README: install transformers from conda-forge channel

### LINKED ISSUE #28248: `transformers==4.36.2` not available from `huggingface` conda channel
### System Info

- `transformers` version: 4.33.3
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.10.13
- Huggingface_hub version: 0.20.1
- Safetensors version: 0.4.0
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.1.2 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install the latest version of [**Miniconda**](https://docs.conda.io/projects/conda/en/stable/user-guide/install/download.html)
2. Create a `conda` environment: `conda create -n ENVNAME python=3.10`
3. Activate the environment: `conda activate ENVNAME`
4. Search for the `transformers` package:

```
(ENVNAME) % conda search huggingface::transformers
Loading channels: done
# Name                       Version           Build  Channel
transformers                  v4.0.0    pyh39e3cac_0  huggingface
...
transformers                  4.33.3            py_0  huggingface
```

Note that the highest version available is `4.33.3`. When I attempt to install the _latest_ version (at the time of this writing, `4.36.2`):

```
(ENVNAME) % conda install huggingface::transformers==4.36.2
Channels:
 - defaults
 - huggingface
 - pytorch
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - huggingface::transformers==4.36.2
```

### Expected behavior

I expected the latest version of `transformers` (`4.36.2`) to be available from the `huggingface` conda channel.

### PR DESCRIPTION
**Pull request by kevherro**
# What does this PR do?

Switch to the conda-forge channel for transformer installation, as the huggingface channel does not offer the latest version.

Fixes #28248 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
LGTM we should probably link @LysandreJik's comment from the issue to follow this and mention that the `huggingface` channel is deprecated for transformers

**Comment by kevherro** [comment]
@ArthurZucker I appreciate your review!

> we should probably link @LysandreJik comment from the issue

"In the future we'll likely remove the huggingface channel support for conda unless we see explicit demand here; if that's the case, please put a thumbs up here (we'll monitor), otherwise, the conda-forge channel is usually very up to date." ([here](https://github.com/huggingface/transformers/issues/28248#issuecomment-1869765891))

> mention that the huggingface channel is deprecated for transformers

Good callout. Should this go in the README as well?

**Comment by stevhliu** [comment]
If you're up for it, would you also mind updating this in the [Installation](https://huggingface.co/docs/transformers/installation#install-with-conda) docs? 🙂

**Comment by kevherro** [comment]
@stevhliu I think I did this correctly!

**Review by stevhliu — APPROVED** [review]
Really nice, thanks for also updating across the other languages! 🎉

**Comment by kevherro** [comment]
My pleasure!

**Comment by LysandreJik** [comment]
Just seeing this now, but thanks for the PR @kevherro!

**Pull request merged**
