### PR TITLE
FixValidRatioForDeformableDetr

### PR DESCRIPTION
**Pull request by long8v**

### CODE REVIEW

**Review by NielsRogge — COMMENTED** [review]
Thanks a lot for fixing!

Could you make sure the CI is green so that we can merge your PR?

if you need any help, let me know. It might also be that some tests fail which are unrelated to your PR.

**Comment by long8v** [comment]
I don't think it is related with my PR. As you can see, my commit is about forward result in batch inference, and has nothing to do with repo consistency, build test, and so on.

**Comment by NielsRogge** [comment]
Hi, 

For repo consistency, you need to run `make fixup `from the root of the repo to fix style and quality of the code.

**Comment by long8v** [comment]
Hi, for repo consistency I ran `make fixup` and it raised same error with circleci, `No module named 'keras.saving.hdf5_format`. I found https://github.com/huggingface/transformers/issues/20393, so I downgraded tf==2.10 in local and it seems passed everything.

```
All done! ✨ 🍰 ✨
1 file left unchanged.
python utils/custom_init_isort.py
python utils/sort_auto_mappings.py
doc-builder style src/transformers docs/source --max_len 119 --path_to_docs docs/source
python utils/check_doc_toc.py --fix_and_overwrite
running deps_table_update
updating src/transformers/dependency_versions_table.py
python utils/check_copies.py
python utils/check_table.py
python utils/check_dummies.py
python utils/check_repo.py
Checking all models are included.
Checking all models are public.
2022-12-04 08:42:15.140190: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-04 08:42:15.963675: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib:
2022-12-04 08:42:15.963836: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib:
2022-12-04 08:42:15.963859: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Checking all models are properly tested.
Checking all objects are properly documented.
Checking all models are in at least one auto class.
python utils/check_inits.py
python utils/check_config_docstrings.py
python utils/tests_fetcher.py --sanity_check
python utils/update_metadata.py --check-only
2022-12-04 08:42:26.671899: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-04 08:42:26.916721: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-04 08:42:27.809325: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib:
2022-12-04 08:42:27.809472: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/usr/local/lib:
2022-12-04 08:42:27.809493: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```

and for others, I also tested all deformable detr related test codes(pytest two py files in `tests/models/deformable_detr`), and it passed everything.
Could you tell me what I should do else?

**Comment by NielsRogge** [comment]
@long8v you'll need to rebase on the main branch to fix this issue:
```
git remote add upstream https://github.com/huggingface/transformers.git
git fetch upstream
git rebase upstream/main
```

**Comment by long8v** [comment]
I reuploaded this PR [here](https://github.com/huggingface/transformers/pull/20958)!

**Pull request closed without merging**
