### PR TITLE
Fix usage of head masks by TF encoder-decoder models' `generate()` function

### PR DESCRIPTION
**Pull request by stancld**
TF counterpart to #11621 

**Description:** It is necessary to fix head masking for LED and T5 models.

Edit: Fix for T5 - #11857

<hr>

**Reviewers:** @patrickvonplaten @Rocketknight1

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Thanks for the addition @stancld ! 

I think once we fix the tests in led + T5 we can merge this one :-)

**Comment by Rocketknight1** [comment]
It also looks good to me!

**Comment by stancld** [comment]
Hey @patrickvonplaten, I haven't implemented head masking for the `generate` method for LED and T5 intentionally. The reason is that TF LED and T5 does not use head masks properly (there's an old glitch that the decoder uses encoder's `head_mask` instead of `cross_attn_head_mask`).  Maybe, I can fix this issue in other PRs and then enable testing for these two models? :)

**Comment by patrickvonplaten** [comment]
> Hey @patrickvonplaten, I haven't implemented head masking for the `generate` method for LED and T5 intentionally. The reason is that TF LED and T5 does not use head masks properly (there's an old glitch that the decoder uses encoder's `head_mask` instead of `cross_attn_head_mask`). Maybe, I can fix this issue in other PRs and then enable testing for these two models? :)

Good for me!

**Pull request merged**
