### PR TITLE
Fix default behaviour in TextClassificationPipeline for regression problem type

### LINKED ISSUE #33973: Default behaviour in `TextClassificationPipeline` for regression problem type
### Feature request

The `AutoModelForSequenceClassification` class also supports problem_type=regression. I am not sure if it is popularly used but I believe that function_to_apply in `TextClassificationPipeline` should behave as if it is set to "none"  for this case?

### Motivation

Currently, the "sigmoid" function is also applied for regression tasks which, in my opinion, might not be the correct default behaviour.

### Your contribution

I believe this can be handled by adding an additional condition for `self.model.config.problem_type == "regression"` before [this](https://github.com/huggingface/transformers/blob/38f9f10dd9240619ea17fb6c7acb51b3bc592232/src/transformers/pipelines/text_classification.py#L195) line.

### PR DESCRIPTION
**Pull request by subhalingamd**
# What does this PR do?

For `problem_type=="regression"`, set default behaviour for `function_to_apply` to "none" in `TextClassificationPipeline`.

Fixes #33973

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
@Rocketknight1

### CODE REVIEW

**Comment by subhalingamd** [comment]
I'm not sure if this change requires adding new tests and/or updating anything under `docs/`. Could you please help? I have updated the docstrings in the file.

**Review by Rocketknight1 — APPROVED** [review]
@subhalingamd no changes in `docs` are needed, because the docs are auto-generated from the docstrings here!

Adding a test might be useful, though - it should only be a couple of lines. Can you add it to `tests/pipelines/test_pipeline_text_classification.py`? You can either add a new test or just add a couple of lines to `test_small_model_pt()`.

**Comment by subhalingamd** [comment]
sure, i can add them. changing the pr to draft till then.

**Comment by subhalingamd** [comment]
@Rocketknight1 I have added a test case to `test_small_model_pt()`. Hope this works.

**Comment by Rocketknight1** [comment]
LGTM now! Pinging @LysandreJik for core maintainer review.

**Review by Rocketknight1 — APPROVED** [review]

**Review by LysandreJik — APPROVED** [review]
I'll trust you on this one @Rocketknight1

**Comment by Rocketknight1** [comment]
Merged, thanks for the PR @subhalingamd!

**Pull request merged**
