### PR TITLE
[`CI-test_torch`] skip `test_tf_from_pt_safetensors` for 4 models

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Skip `test_tf_from_pt_safetensors` tests for MobileBert,  TransfoXL, SPeech2text and XGLM

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]

**Comment by Saibo-creator** [comment]
Hello, @ArthurZucker 
Thanks for fixing the broken tests. I have made a PR and the tests failed because of the broken tests, how could I rerun the tests ? 

https://github.com/huggingface/transformers/pull/26304

**Comment by ArthurZucker** [comment]
I'll re-run them for you!

**Comment by ArthurZucker** [comment]
Thanks! @Rocketknight1 is working on a broader fix, I don't really mind skipping this test for all the other failing PRs

**Comment by Rocketknight1** [comment]
The proper fix is here #27490

**Pull request merged**
