### PR TITLE
Adds dvclive callback

### PR DESCRIPTION
**Pull request by dberenbaum**
# What does this PR do?

Adds a [DVCLive](https://dvc.org/doc/dvclive) callback. DVCLive is a logger for [DVC](https://dvc.org), which version data, models, metrics, etc. and keeps them connected to your Git repo. They can then be visualized in several different interfaces. For example, here is the output of [example code](https://github.com/iterative/dvclive/blob/main/examples/DVCLive-HuggingFace.ipynb) in the DVC extension for VS Code:

Screenshot 2023-11-06 at 4 19 11 PM

Screenshot 2023-11-06 at 4 19 28 PM

There is already a [DVCLive callback](https://dvc.org/doc/dvclive/ml-frameworks/huggingface) inside `dvclive`, and this PR migrates the callback from `dvclive` to `transformers` (the callback inside `dvclive` will be deprecated in the next major release of `dvclive`).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? (I don't see any tests for any of the callbacks but please let me know if I missed them somewhere)

## Who can review?

@sgugger It looks like you are the most relevant reviewer. Could you PTAL or redirect me if someone else should review it?

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Very nice - thanks for adding! 

There was a recent update which addressed the currently (unrelated) failing tests. Could you rebase on main to resolve these? 

The integrations are maintained by their contributors. If you're happy to be pinged if there's issues then we're happy to merge :)

**Comment by dberenbaum** [comment]
> There was a recent update which addressed the currently (unrelated) failing tests. Could you rebase on main to resolve these?

Done

> The integrations are maintained by their contributors. If you're happy to be pinged if there's issues then we're happy to merge :)

Sounds good, thanks for the quick approval!

**Comment by amyeroberts** [comment]
@dberenbaum There were a few more unexpected failures because of new packages releases. This should now be resolved on main. Could you rebase on main again?

**Comment by dberenbaum** [comment]
Rebased and checks passing now!

**Comment by muellerzr** [comment]
FYI @dberenbaum we're seeing a failure on our nightlies after this PR (showed up after the Accelerate PR since we run transformers tests in it and dvc got added to the test requirements)

```
FAILED tests/trainer/test_trainer.py::TrainerIntegrationPrerunTest::test_reduce_lr_on_plateau - dvclive.error.InvalidDataTypeError: Data 'learning_rate' has not supported type <class 'list'>
```

**Pull request merged**
