### PR TITLE
Fix MusicGen logging error

### PR DESCRIPTION
**Pull request by osanseviero**
# What does this PR do?

Issue: #26369 

Loading

```python
pipe = pipeline("text-to-audio", model="facebook/musicgen-small")
data = pipe("latin salsa with violins")
```

at the moment, throws a large error

## Who can review?

@ylacombe @sanchit-gandhi

### CODE REVIEW

**Review by zhangjunyi111 — COMMENTED** [review]
Can you tell me what is the difference between logger.warning and warnings.warn? And why this error happen?

**Review by zhangjunyi111 — COMMENTED** [review]
image

**Review by zhangjunyi111 — COMMENTED** [review]
According to https://github.com/huggingface/transformers/issues/26369,  there are two issuses,so which issue is fixed? And how to fix anthor one?

**Review by LysandreJik — APPROVED** [review]
Thank you @osanseviero!

**Review by sanchit-gandhi — COMMENTED** [review]
Awesome - thanks @osanseviero!

**Pull request merged**
