### PR TITLE
[run_seq2seq.py] restore functionality: saving to test_generations.txt

### LINKED ISSUE #10381: Option to output "test predictions" text file with each checkpoint in run_seq2seq.py
Further to this discussion:

https://discuss.huggingface.co/t/how-to-output-test-generations-txt-with-run-seq2seq-py/3825

The prior incarnation of this script would output test generations at each checkpoint, which was very useful for understanding the progress of model training.

The current script...

https://github.com/huggingface/transformers/blob/master/examples/seq2seq/run_seq2seq.py

Seems to only output this text file once, at the end of the last epoch.

If there was a way to enable the previous behavior, I am guessing that would be widely useful.

thanks

### PR DESCRIPTION
**Pull request by stas00**
This PR restores the original functionality that for some reason was modified.

Fixes: https://github.com/huggingface/transformers/issues/10381

@sgugger

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
I don't think that is waht the user wanted as it does not do prediction on all checkpoints (but perhaps I misunderstood).

**Comment by stas00** [comment]
Ah, I re-read it closer, you're correct? I just remembered the part about the `test_generations.txt` but didn't bother to check out the full story. My bad. I will study it and follow up once I understand it better.

**Comment by stas00** [comment]
I went back to `finetune_trainer.py` from December and checked that it was just saving `test_generations.txt` at the very end once. I can't find any code where it did generate this at every checkpoint.

If there were to be a `save_checkpoint` callback then it could generate one for each saved check point. So it probably needs to be requested via a feature request.

**Comment by sgugger** [comment]
I don't think it matters much, we just have to be quick if people using the new script start to rely on the new name.

**Comment by stas00** [comment]
OK, let's restore the original name.

**Pull request merged**
