### PR TITLE
Correct wrong function signatures on the docs website

### PR DESCRIPTION
**Pull request by qqaatw**
# What does this PR do?

Trying to address #13171.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger @patrickvonplaten

### CODE REVIEW

**Comment by qqaatw** [comment]
After a series of investigations, here is the concluding matrix:

| Env                       | Python version | Sphinx version | Correctness     |
|-------------------- |------------------|-----------------|-----------------|
| Circle CI Docker Image   |         3.6           |         3.2.1         |       X    |
| Circle CI Docker Image   |         3.6           |         3.5.4         |       X    |
| Circle CI Docker Image   |         3.7           |         3.2.1         |       X    |
| Circle CI Docker Image   |         3.7           |         3.5.4         |      *O [Artifact](https://258083-155220641-gh.circle-artifacts.com/0/docs/_build/html/main_classes/trainer.html)  |
| Ubuntu 18.04 Anaconda |         3.6.13      |         3.2.1         |       X    |
| Ubuntu 18.04 Anaconda |         3.7.11      |         3.2.1         |       O    |
| Ubuntu 18.04 Anaconda |         3.8.5        |         3.2.1         |       O    |

X: 
`model: torch.nn.modules.module.Module = None` (Union and PreTrainedModel missing)
O:
`model: Union[transformers.modeling_utils.PreTrainedModel, torch.nn.modules.module.Module] = None` (Correct)
*O: 
`Optional[Union[transformers.modeling_utils.PreTrainedModel, torch.nn.modules.module.Module]] = None`
(An `Optional` type hint was added by Sphinx which wasn't defined in the code, maybe inferred from the default value `None`)

As shown in the above matrix, Sphinx (3.2.1 & 3.5.4) with python 3.6 failed to generate correct html in testing environments. 
Should we upgrade CI/CD environments all together to python 3.7 in order to keep the consistency?

**Review by sgugger — APPROVED** [review]
Thanks for the deep dive into this issue! The version should indeed be changed in the `conf.py` file, can you set it to `"4.9.1"` (no u and double quotes)? The fact it's in a weird format is the reason our tooling does not update it at each release.

Historically, sphinx was pinned because the next version was very slow to build our doc, but this bug in sphinx has been fixed, so pinning to the new version is fine.

**Review by LysandreJik — APPROVED** [review]

**Comment by LysandreJik** [comment]
@sgugger correctly mentions I merged this without the last comment being taken into account - Sorry about that, Sylvain is pushing directly on `master` with the comment's request.

**Comment by sgugger** [comment]
I actually made a PR in #13337 :-)

**Comment by LysandreJik** [comment]
This had an unintended side-effect: the search functionality doesn't seem to be working anymore on huggingface.co/transformers.

I tracked the issue to Sphinx version v3.4.0. Checking out your useful table @qqaatw, switching back to v3.2.1 with Python v3.7x would be the second best choice?

**Comment by qqaatw** [comment]
@LysandreJik I've checked the search functionality, it's not working indeed. 

As you said, maybe we should switch back Sphinx's version to v3.2.1 but not with Python v3.7.11 because Sphinx v3.2.1 with Python v3.7.11 provided by CircleCI docker image seems not working either. It's weird though as I tested this combination on my machine and the output was correct.

I think another try would be using [Next-gen language images](https://circleci.com/docs/2.0/circleci-images/#next-gen-language-images). According to what the website states, these images are faster to build and have improved reliability and stability. Perhaps switching to this one can solve this problem.

**Comment by sgugger** [comment]
Since we are exploring a move away from sphinx anyway, we will revert this commit for now to re-enable the search. If we end up not moving away from sphinx we can explore more which image to pick and which versions to use, but in the meantime, it's more important to have the search enabled than the sometime wrong signatures.

**Comment by qqaatw** [comment]
Got it. Sorry for the inconvenience.

**Comment by sgugger** [comment]
No worries!

**Pull request merged**
