### PR TITLE
Added support for AzureOpenAiAgent in tools

### LINKED ISSUE #23324: Support Azure OpenAI in transformer agents
### Feature request

Support it by setting the openai properties.

``` python
openai.api_type = "azure"
openai.api_version = "2023-03-15-preview"
openai.api_base = "https://THE_NAME.openai.azure.com/"
openai.api_key = "AZURE_OPENAI_API_KEY"

# response = openai.Completion.create(engine="xxxx", ...)
```

### Motivation

Azure OpenAI is also used by a lot of people.
It would be great to support it in the transformer agents.

### Your contribution

I may contribute to test it.

### PR DESCRIPTION
**Pull request by waundme**
# What does this PR do?
Implements a new class AzureOpenAiAgent derived from Agent in transformer agents.

Fixes #23324

- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by waundme** [comment]
Seriously, I don't understand why this build fails. Why is the CI-process complaining about Python-Notebooks? I didn't add or reference Python-Notebooks. It's just a simple new agent class with no side effects. Can somebody please point me into the right direction how to fix this? Because Azure support for TF Agents would actually be great.

**Comment by MSDNAndi** [comment]
Awesome that you are contributing.
In my opinion, rather than having a separate AzureOpenAiAgent adding the options and API calls in the OpenAiAgent would be preferrable, so it is only configuration of parameters to switch to Azure. Not my call, but my preference.

**Comment by amyeroberts** [comment]
cc @sgugger

**Review by sgugger — COMMENTED** [review]
Thanks for your PR. This is exactly like the `OpenAiAgent` class execpt for two new arguments (`is_chat_model` is not useful since we can determine this from the model ID) so the arguments should just be added to `OpenAiAgent` as optionals.

**Comment by sgugger** [comment]
Ah actually I see two arguments are renamed. Maybe have this be a subclass of `OpenAiAgent` to avoid rewriting every method and just rewrites `_completion_generate` and `_chat_generate`?

**Comment by MSDNAndi** [comment]
DeploymentId is named arbitrarily and does not let you directly derive the model type from it unless you do additional requests to look it up.
The underlying Python OpenAI SDK has a way of differentiating between Azure OpenAI and OpenAI's own deployment. In my opinion it would make sense to align the API style and expose what the API exposes in a similar fashion.

**Comment by sgugger** [comment]
> The underlying Python OpenAI SDK has a way of differentiating between Azure OpenAI and OpenAI's own deployment. In my opinion it would make sense to align the API style and expose what the API exposes in a similar fashion.

If it's easily doable, then yes let's aim for that!

**Pull request closed without merging**
