### PR TITLE
Make create_extended_attention_mask_for_decoder static method

### PR DESCRIPTION
**Pull request by pbelevich**
# What does this PR do?'

`create_extended_attention_mask_for_decoder` doesn't access `self` and can be `@staticmethod`. This resolves some issues with fx tracing for pytorch pipeline parallelism project. 

cc @michaelbenayoun

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by ydshieh** [comment]
(just a comment)

Would it be possible to provide the code sample for the issue that occurs without this PR, or a link to the issue page?

**Comment by michaelbenayoun** [comment]
Looks good to me once all the tests pass.
Pinging @sgugger for review!

**Review by sgugger — APPROVED** [review]
LGTM, thanks for fixing!

**Comment by pbelevich** [comment]
> Would it be possible to provide the code sample for the issue that occurs without this PR, or a link to the issue page?

The project will be released and the repo will be opened soon

**Comment by sgugger** [comment]
Thanks again for your contribution!

**Pull request merged**
