### PR TITLE
bert（+lstm）+crf

### PR DESCRIPTION
**Pull request by michael-wzhu**
add crf layer for better performance in NER tasks

### CODE REVIEW

**Comment by petulla** [comment]
@michael-wzhu how much of an f1 boost did this give on CoNLL?

**Comment by fengliangjing** [comment]
> add crf layer for better performance in NER tasks

Hi. How do you solve the tokens with "##..." when they are fed into the crf layer?
e.g. De ##duct ##ive reasoning
Do "##duct" and ""##ive" are fed into the crf layer? If they are, do they have chance to be transfered in the transition matrix?

**Comment by mezig351** [comment]
> e" are fed into the crf layer? If they are, do they have chance to be transfered in the transition matrix?

I have used this to develop my own version. To answer your quesiton, ## sub word tokens are treated as padding, as suggested by the original BERT authors. This code relies on The padding label token being "X", at the first position (to get0th index) from the output of get_labels function in crf_utils_ner.py 

The pad token label id might need to be 0 for calculations in CRF, but you should be careful in declaring your mask so your model does not confuse padding with one of the tokens.

**Comment by yi-asapp** [comment]
If ## sub word tokens are treated as padding, it will break the tag-tag dependencies, so definitely not ideal.

**Comment by hasansalimkanmaz** [comment]
@srush @mezig351  What did you find after your work on this issue? Why didn't you merge it?

**Comment by shaked571** [comment]
I think you should add it, it's not trivial, and I myself spent 2 days to make it work...
and then I just found this thread...

**Pull request closed without merging**
