### PR TITLE
update deprecating `transformers-cli` to `huggingface-cli` in docs

### PR DESCRIPTION
**Pull request by fcakyon**

### CODE REVIEW

**Comment by julien-c** [comment]
looks good to me!

**Comment by LysandreJik** [comment]
Thanks @fcakyon!

This page seriously needs an update, and I believe some methods here don't exist in `huggingface-cli` ...

We should probably just link to the following: https://huggingface.co/docs/hub/adding-a-model

**Comment by julien-c** [comment]
let's merge this and we'll refine later (but the doc format changed on the main branch in the meantime :) )

**Comment by fcakyon** [comment]
@julien-c revised version of the docs fixed this issue i believe 👍

**Comment by julien-c** [comment]
cool, closing this then. Thanks! 🙏

**Pull request closed without merging**
