### PR TITLE
fixed direct input of state dict functionality

### PR DESCRIPTION
**Pull request by mikeybellissimo**
# What does this PR do?
In the documentation it says that if you call from_pretrained with pretrained_model_name_or_path set to None and specify config and state_dict then you can directly input the state_dict. This branch accomplishes that. 

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
Could you please post a reproducer of the bug you encounter? The situation described in the doc works and is tested, but it looks like you are trying to use it with other extra arguments like `low_cpu_mem_usage=True`, which is definitely not a combination we support.

**Comment by mikeybellissimo** [comment]
> Could you please post a reproducer of the bug you encounter? The situation described in the doc works and is tested, but it looks like you are trying to use it with other extra arguments like `low_cpu_mem_usage=True`, which is definitely not a combination we support.

Yeah my bad should have been more specific. I needed to specify the device map which automatically sets low_cpu_mem_usage to true, thereby disabling the above behavior.

**Comment by sgugger** [comment]
Yes, we do not support that use case. `device_map="auto"` requires loading the state dict from disk to.

**Comment by mikeybellissimo** [comment]
> Yes, we do not support that use case. `device_map="auto"` requires loading the state dict from disk to.

Thank you for your timely replies. It appears to work just as intended for me unless I’m missing something.

**Comment by mikeybellissimo** [comment]
I directly inputted the device map as = {‘’ :0} though.

**Comment by sgugger** [comment]
You misunderstand me: we offer the functionality to pass along a `state_dict` in the very basic case of no other kwargs and we do not want to complexify `from_pretrained` to support those use cases. Passing along a `state_dict` here is only possible to guarantee backward compatibility, but it is not a feature we maintain outside of the basic use case config + state_dict.

**Comment by mikeybellissimo** [comment]
> You misunderstand me: we offer the functionality to pass along a `state_dict` in the very basic case of no other kwargs and we do not want to complexify `from_pretrained` to support those use cases. Passing along a `state_dict` here is only possible to guarantee backward compatibility, but it is not a feature we maintain outside of the basic use case config + state_dict.

Ok thank you for your time. I’ll just stick to my using my fork for my use case.

**Pull request closed without merging**
