### PR TITLE
[WIP] Generate docs

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Still having hope of merging this one day :crossed_fingers:

**Comment by patrickvonplaten** [comment]
Ok sadly really not finding the time at the moment :cry: @gante @ArthurZucker @sanchit-gandhi  could it maybe be interesting for one of you to take it over?

**Comment by patrickvonplaten** [comment]
Also cc @sgugger just FYI

**Comment by sgugger** [comment]
You don't need to cc me, I see everything ;-)

image

**Comment by sanchit-gandhi** [comment]
I could look into this in a couple of weeks if you want to offload it! Reassuring to know @sgugger has assumed the role of Hugging Face's Big Brother 👀

**Comment by ArthurZucker** [comment]
I think I can take care of it maybe next week 😄 Adding it to my list !

**Pull request closed without merging**
