### PR TITLE
Fix doctest

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

We just need `# doctest: +IGNORE_RESULT` after `>>> dataset = load_dataset` as usual

### CODE REVIEW

**Review by sgugger — APPROVED** [review]

**Comment by sgugger** [comment]
Thanks for fixing!

**Comment by stevhliu** [comment]
Thanks @ydshieh! Sorry for breaking our streak of 6 days of no failures!

**Comment by ydshieh** [comment]
Oh, I haven't request yet and you already approved! Thanks a lot, so impressive your speed of response!

**Comment by sgugger** [comment]
image

**Comment by ydshieh** [comment]
I am so bad in doctest ... What we need here is actually `# doctest: +IGNORE_RESULT`. Sorry.

**Pull request merged**
