### PR TITLE
Pin datasets<2.20.0 for examples

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Temporarily pin datasets upper version until PR merged:

https://github.com/huggingface/transformers/pull/31406

c.f. #31407

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @albertvillanova @ydshieh

**Comment by amyeroberts** [comment]
Merging as this is blocking other PRs

**Review by albertvillanova — COMMENTED** [review]
Thanks, @amyeroberts.

Sorry, I did not know the dependencies were also set in those files.

**Comment by amyeroberts** [comment]
@albertvillanova No worries - I forgot in my review!

**Pull request merged**
