### PR TITLE
Fix image post-processing for OWLv2

### LINKED ISSUE #30131: [Bug] Owlv2 Zero-Shot Object Detection
### Who can help?

_No response_

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoProcessor, AutoModelForZeroShotObjectDetection
import requests
import torch

checkpoint=""google/owlv2-base-patch16-ensemble"
model = AutoModelForZeroShotObjectDetection.from_pretrained(checkpoint)
processor = AutoProcessor.from_pretrained(checkpoint)

url = "https://unsplash.com/photos/oj0zeY2Ltk4/download?ixid=MnwxMjA3fDB8MXxzZWFyY2h8MTR8fHBpY25pY3xlbnwwfHx8fDE2Nzc0OTE1NDk&force=true&w=640"
im = Image.open(requests.get(url, stream=True).raw)

text_queries = ["hat", "book", "sunglasses", "camera"]
inputs = processor(text=text_queries, images=im, return_tensors="pt")

with torch.no_grad():
    outputs = model(**inputs)
    target_sizes = torch.tensor([im.size[::-1]])
    results = processor.post_process_object_detection(outputs, threshold=0.1, target_sizes=target_sizes)[0]

draw = ImageDraw.Draw(im)

scores = results["scores"].tolist()
labels = results["labels"].tolist()
boxes = results["boxes"].tolist()

for box, score, label in zip(boxes, scores, labels):
    xmin, ymin, xmax, ymax = box
    draw.rectangle((xmin, ymin, xmax, ymax), outline="red", width=1)
    draw.text((xmin, ymin), f"{text_queries[label]}: {round(score,2)}", fill="white")

im
```

### Expected behavior

Expected behavior should be as shown in the second official example here: https://huggingface.co/docs/transformers/main/en/tasks/zero_shot_object_detection

However, the final bounding boxes are still shifted. Please refer to the code above (taken from the official example)

### PR DESCRIPTION
**Pull request by jla524**
# What does this PR do?

Fixes #30131 (issue)

## Who can review?

@NielsRogge @nisyad-ms

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Thanks for updating our example, @jla524! 

This is something which should really be handled within the image processor of the model itself, specifically the rescaling of the box dimensions

**Review by amyeroberts — COMMENTED** [review]
Looks great - thanks for taking the time to update the example as well! 

Technically this is a breaking change. However, as many users have highlighted this confusing behaviour and it should always have been done in the post-processing method, I think it's OK to add directly. 

Final request is to add a [test here](https://github.com/huggingface/transformers/blob/508c0bfe555936fc772cd000e2e8da739f777a4f/tests/models/owlv2/test_image_processor_owlv2.py#L86) so that we check the images and boxes are rescaled as expected in the post processing method. Once that's done I think we're good to merge!

**Comment by jla524** [comment]
> Looks great - thanks for taking the time to update the example as well!
> 
> Technically this is a breaking change. However, as many users have highlighted this confusing behaviour and it should always have been done in the post-processing method, I think it's OK to add directly.
> 
> Final request is to add a [test here](https://github.com/huggingface/transformers/blob/508c0bfe555936fc772cd000e2e8da739f777a4f/tests/models/owlv2/test_image_processor_owlv2.py#L86) so that we check the images and boxes are rescaled as expected in the post processing method. Once that's done I think we're good to merge!

Added a test for the resize. I'm not sure if this is the right approach. Let me know what you think!

**Review by amyeroberts — COMMENTED** [review]
Looks great - thanks for iterating on this! 

For the test, have you visualized the bounding boxes to confirm they are sensible? It would be good to check this + bboxes on the examples to make sure everything is a-ok before merge. Otherwise looks good to go!

**Comment by jla524** [comment]
> Looks great - thanks for iterating on this!
> 
> For the test, have you visualized the bounding boxes to confirm they are sensible? It would be good to check this + bboxes on the examples to make sure everything is a-ok before merge. Otherwise looks good to go!

Yes, the boxes look reasonable. One thing to note is that the box on the right is slightly out of bound. The box has a `x_max` of 642.32, whereas the image itself is 640 pixels.

image

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing, adding tests and verifying the outputs!

**Comment by ydshieh** [comment]
Hi @jla524 Thank you for the fix.

Our doctesting for this model now has one failure. See below.

> python3 -m pytest -v --make-reports doc_tests_gpu_docs_source_en_model_doc_owlv2.md --doctest-modules docs/source/en/model/doc/owlv2.md failures:
owlv2.md -sv --doctest-continue-on-failure --doctest-glob="*.md"

(on a T4 GPU machine)

I think it's expected? Would you like to take a look to confirm and open a pull request to update `docs/source/en/model/doc/owlv2.md` if that is the way to go?

```
Expected:
    Detected a photo of a cat with confidence 0.614 at location [341.67, 17.54, 642.32, 278.51]
    Detected a photo of a cat with confidence 0.665 at location [6.75, 38.97, 326.62, 354.85]
Got:
    Detected a photo of a cat with confidence 0.614 at location [341.67, 23.39, 642.32, 371.35]
    Detected a photo of a cat with confidence 0.665 at location [6.75, 51.96, 326.62, 473.13]
```

**Comment by jla524** [comment]
@ydshieh Yes, I'll send in a PR to fix this.

**Comment by zhangjingxian1998** [comment]
Hi @jla524, Thank you for your job.
when the owlv2 gets more than one input, it will get error at
https://github.com/huggingface/transformers/blob/9d35edbb30625489bf286a9b15aed0c5a3119c1c/src/transformers/models/owlv2/image_processing_owlv2.py#L531

it can be reproduced by
```
import requests
from PIL import Image
from io import BytesIO
from transformers import AutoProcessor, Owlv2ForObjectDetection

processor = AutoProcessor.from_pretrained('google/owlv2-base-patch16-ensemble')
model = Owlv2ForObjectDetection.from_pretrained('google/owlv2-base-patch16-ensemble')

url = 'http://demandware.edgesuite.net/sits_pod41/dw/image/v2/AAJI_PRD/on/demandware.static/-/Sites-londondrugs-master/default/dw99e32df7/products/L8191009/large/L8191009.JPG?sw=556&amp;sh=680&amp;sm=fit'
response = requests.get(url, timeout=2)
image = Image.open(BytesIO(response.content)).convert('RGB')
target_sizes = [image.size, image.size]
texts = ["human"]

inputs = processor(text=[texts, texts], images=[image,image], return_tensors="pt")
outputs = model(**inputs)
results = processor.post_process_object_detection(outputs=outputs, threshold=0.1, target_sizes=target_sizes)
```
could you help fix it

**Pull request merged**
