### PR TITLE
Fix docstrings and update docstring checker error message

### PR DESCRIPTION
**Pull request by Rocketknight1**
While I was making fixes to the docstring checker, I found another issue - this one seems to be intermittent, and I'm not sure why it only fails tests sometimes. Still, it's definitely wrong, so this fix should hopefully avoid issues in future!

### CODE REVIEW

**Comment by Rocketknight1** [comment]
Okay there's something more deeply wrong with the docstring checker than I realized - the new docstring is definitely more correct, but is failing checks in the CI! Will investigate.

**Review by ArthurZucker — APPROVED** [review]
LGTM

**Comment by Rocketknight1** [comment]
Quick re-review request @ArthurZucker, I'm going to update the error message in this PR too!

**Review by amyeroberts — APPROVED** [review]
Thanks!

**Pull request merged**
