### PR TITLE
[CI] add dependency table sync verification

### PR DESCRIPTION
**Pull request by stas00**
Sometimes version is being modified in `setup.py` but not updated in the autogenerated versions file `src/transformers/dependency_versions_table.py` and then all devs start getting this uncommitted change in their clone on `make fixup/style`. This PR adds a new make target to do the checking and adds it to the `check_code_quality` CI job.

Expecting it to fail in this PR initially as I didn't sync the table.

TODO: backout the setup.py version changes before merging.

@sgugger, @LysandreJik

### CODE REVIEW

**Comment by stas00** [comment]
So now when the table out of sync it fails with:

snapshot_3

Let me know if this is good and I will re-test with when it's in sync.

**Comment by stas00** [comment]
So now when the table out of sync it fails with:

snapshot_4


Let me know if this is good and I will re-test with when it's in sync.

**Review by LysandreJik — APPROVED** [review]
Great, thanks @stas00!

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Pull request merged**
