### PR TITLE
change `encoder_input_ids` value from `inputs_tensor` to `input_ids`

### PR DESCRIPTION
**Pull request by zhoubay**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

This issue is originated from PR #14784, which there's a [discussion](https://github.com/huggingface/transformers/pull/14784/files#r770422777) between @Narsil and @patrickvonplaten [in this lines](https://github.com/patrickvonplaten/transformers/blob/27c5509bfa072a096bb209af10c02f11af37824e/src/transformers/generation_utils.py#L1013-L1014)

After that, the generation file has changed to support `inputs_embeds` for decoder-only model as long as its signature contains `inputs_embeds` [in these lines](https://github.com/huggingface/transformers/blob/bbaa8ceff696c479aecdb4575b2deb1349efd3aa/src/transformers/generation/utils.py#L403-L411).

And the only classes using the `encoder_input_ids` is EncoderRepetitionPenaltyLogitsProcessor [in these lines](https://github.com/huggingface/transformers/blob/bbaa8ceff696c479aecdb4575b2deb1349efd3aa/src/transformers/generation/utils.py#L805-L807) and EncoderNoRepeatNGramLogitsProcessor [in these lines](https://github.com/huggingface/transformers/blob/bbaa8ceff696c479aecdb4575b2deb1349efd3aa/src/transformers/generation/utils.py#L817-L819). 

While I'm passing `inputs_embeds` to `generate` for a decoder-only model with `encoder_no_repeat_ngram_size` set, [this line](https://github.com/huggingface/transformers/blob/bbaa8ceff696c479aecdb4575b2deb1349efd3aa/src/transformers/generation/logits_process.py#L786) will throw out a `TypeError: unhashable type: 'list'`. After applying this commit, the error disappears.

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @gante

**Comment by zhoubay** [comment]
hello @gante , could you take some time to review this PR? Feel free to tell me what should I do to make this PR more professional since this is my first time. Maybe I should add a test case?

**Comment by zhoubay** [comment]
hello @gante , could you take some time to see this and tell me what should I do to move this PR further? Thank you for your time!

**Comment by gante** [comment]
> While I'm passing inputs_embeds to generate for a decoder-only model with encoder_no_repeat_ngram_size set

@zhoubay decoder-only models should not use `encoder_no_repeat_ngram_size`, that is meant for encoder-decoder models. 

The alternatives are:
1. if you want to prevent repetitions in the generated text, try the `no_repeat_ngram_size` flag ([docs](https://huggingface.co/docs/transformers/v4.41.0/en/main_classes/text_generation#transformers.GenerationConfig.no_repeat_ngram_size))
2. If you want to prevent prompt repetition, you need to pass `input_ids` containing the prompt to `generate`, then use the `no_repeat_ngram_size` flag

Do these options solve your use case? 🤗

**Comment by zhoubay** [comment]
> > While I'm passing inputs_embeds to generate for a decoder-only model with encoder_no_repeat_ngram_size set
> 
> @zhoubay decoder-only models should not use `encoder_no_repeat_ngram_size`, that is meant for encoder-decoder models.
> 
> The alternatives are:
> 
> 1. if you want to prevent repetitions in the generated text, try the `no_repeat_ngram_size` flag ([docs](https://huggingface.co/docs/transformers/v4.41.0/en/main_classes/text_generation#transformers.GenerationConfig.no_repeat_ngram_size))
> 2. If you want to prevent prompt repetition, you need to pass `input_ids` containing the prompt to `generate`, then use the `no_repeat_ngram_size` flag
> 
> Do these options solve your use case? 🤗

Hi @gante,  thank you for your advice! However, I've implement a test function in my [latest commit](https://github.com/huggingface/transformers/pull/30598/commits/e2da45da525cf693d2734df433cbeda4e731cb09) to demonstrate the bug. Without [the commit](https://github.com/huggingface/transformers/pull/30598/commits/aa3398d48c7424b31929696a65008b728baddc98), the test would fail, and apply the commit, the test would pass. 

It's not nonsense to use `encoder_no_repeat_ngram_size` in `decoder-only` model, since the class said that it supports the decoder-only model [in the lines](https://github.com/huggingface/transformers/blob/1518508467d96b3866fc4ebcb7a5b3a2e0df2aa4/src/transformers/generation/logits_process.py#L356-L357)

Here I quote:
> Although originally intended for encoder-decoder models, it can also be used with decoder-only models like LLMs.

Thank you for your suggestions, and hope you could take some time and review my PR!

Have a good day!

**Comment by gante** [comment]
@zhoubay 

The test case as in the script below

```py
from transformers import AutoModelForCausalLM, AutoTokenizer

article = "Today a dragon flew over Paris."
model = AutoModelForCausalLM.from_pretrained("hf-internal-testing/tiny-random-gpt2").to("cuda")
tokenizer = AutoTokenizer.from_pretrained("hf-internal-testing/tiny-random-gpt2")
input_ids = tokenizer(article, return_tensors="pt").input_ids.to("cuda")
inputs_embeds = model.get_input_embeddings()(input_ids)

model.generate(inputs_embeds=inputs_embeds, encoder_no_repeat_ngram_size=3, max_length=20)
```

does not make sense. `inputs_embeds` does not contain tokens (only their embeddings), so `encoder_no_repeat_ngram_size` has no prompt tokens to prevent the repetition of.

However, if you call instead

```py
model.generate(input_ids=input_ids, encoder_no_repeat_ngram_size=3, max_length=20)
```

it works.

Moreover, the proposed change breaks the intended use case, with encoder-decoder models (the encoder input in that case is contained in `inputs_tensor`, not in `input_ids`).

**Pull request closed without merging**
