### PR TITLE
Change unpacking of TF layoutlm inputs to use decorator

### PR DESCRIPTION
**Pull request by vumichien**
# What does this PR do?

As part of #16051 this PR changes the unpacking of the inputs of TF layoutlm to use the decorator instead.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
@Rocketknight1 @gante

### CODE REVIEW

**Review by gante — COMMENTED** [review]
Fantastic, thank you so much! I have the same comments as in the other PR:
1. Tests are failing due to formatting -- `make fixup` should fix it
2. Can you confirm that `RUN_SLOW=1 py.test -vv tests/[model_name]/test_modeling_tf_[model_name].py` runs?
3. Sorry to be picky about this -- other models have been adding @unpack_inputs as the top decorator, can I ask you to move it to the top (for consistency)?

Finally, one of the models you touched is RAG, whose tests are suuuuuper slow (like 1hr slow, needing >16GB of RAM) -- let me know if you want me to run the tests 🙏

**Comment by vumichien** [comment]
Yah, I agree Rag's test is suppper slow :( . Anyway, let me run all the tests again and will commit when they are done

**Comment by gante** [comment]
> Yah, I agree Rag's test is suppper slow :( . Anyway, let me run all the tests again and I will commit when they are done

I'm assuming all tests have passed, since you've made a commit -- is this correct? :D

**Review by gante — APPROVED** [review]

**Comment by vumichien** [comment]
Yeah, all the test have passed :D

**Pull request merged**
