### PR TITLE
fix dynamic_module import err

### PR DESCRIPTION
**Pull request by Fazziekey**
# What does this PR do?

 Fix the dynamic module import err for #28459, 
when user use custom model by `transformers.AutoModelForCausalLM.from_pretrained(model_name_or_path, trust_remote_code=True)`, for example [Phi](https://huggingface.co/microsoft/phi-1_5/discussions/72), [DeepSeekMOE](https://huggingface.co/deepseek-ai/deepseek-moe-16b-base), will get error 
```
ImportError: This modeling file requires the following packages that were not found in your environment: flash_attn. Run `pip install flash_attn`
python-BaseException
```
Which caused by import flash attention, however, some device for example Mac, don't support CUDA, but can run model on CPU, user will be blocked by this problem. I think it should be a warning rather than error.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Fazziekey** [comment]
@ArthurZucker

**Review by ArthurZucker — COMMENTED** [review]
Hey! I think that is not too bad. IMO we should rather check if the imports are protected or not / have a list of packages that can be ignored because this will no longer warn users for every other packages that might be mssing :(

**Comment by Fazziekey** [comment]
> Hey! I think that is not too bad. IMO we should rather check if the imports are protected or not / have a list of packages that can be ignored because this will no longer warn users for every other packages that might be missing :(

TheThe Ci is failed.
image

**Comment by Fazziekey** [comment]
> Hey! I think that is not too bad. IMO we should rather check if the imports are protected or not / have a list of packages that can be ignored because this will no longer warn users for every other packages that might be mssing :(

That‘s right, not all module is necessary

**Pull request closed without merging**
