### PR TITLE
Avoid the problem of gradient backpropagation being truncated when fine-tuning CLIP text encoder in diffusers

### PR DESCRIPTION
**Pull request by liming-ai**
…orting errors

# What does this PR do?

Fixes # (issue)
In many cases, we may want to fine-tune CLIP Text Encoder. However, naively modify the training code such as [train_t2i_model in diffusers](https://github.com/huggingface/diffusers/blob/d9f71ab3c3cc162226ec1c9945fef1a5faf4c512/examples/text_to_image/train_text_to_image.py#L621) to make `text_encoder.requires_grad_(True)` leads to gradient truncated issue and results in training errors like this:

```
Traceback (most recent call last):
  File "code/diffusers/examples/instruct_pix2pix/train_instruct_pix2pix.py", line 1261, in <module>
    main()
  File "code/diffusers/examples/instruct_pix2pix/train_instruct_pix2pix.py", line 1136, in main
    accelerator.backward(loss)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/accelerator.py", line 2134, in backward
    loss.backward(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/usr/local/lib/python3.9/dist-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [1, 77]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

To fix this issue, we should avoid the `position_ids` be changed by:
```
position_ids = self.position_ids[:, :seq_length].clone()
```

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Hi @liming-ai, thanks for opening this PR and adding this fix! 

Running `make fix-copies` and then `make fixup` should resolve the failing quality checks

**Comment by liming-ai** [comment]
> Hi @liming-ai, thanks for opening this PR and adding this fix!
> 
> Running `make fix-copies` and then `make fixup` should resolve the failing quality checks

Done, could you please check this PR again?

**Comment by amyeroberts** [comment]
@liming-ai Could you rebase on main to include any upstream changes? I think this should resolve the failing tokenization tests

**Comment by liming-ai** [comment]
> @liming-ai Could you rebase on main to include any upstream changes? I think this should resolve the failing tokenization tests

Hi @amyeroberts,

The code changes I pushed are the results of executing the command `make fix-copies` and then `make fixup` on the main branch. I have no ideas why there are still errors.

**Comment by amyeroberts** [comment]
@liming-ai Could you try rebasing on main to include upstream changes? This should resolve the failing tokenization tests

**Pull request closed without merging**
