### PR TITLE
Add HHEMv2 Model

### PR DESCRIPTION
**Pull request by Miaoranmmm**
This PR adds the support of codes for the HHEMv2 model. For information about HHEMv2 , please visit [model card](https://huggingface.co/vectara/hallucination_evaluation_model)
cc @forrestbao

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! from scanning through the code I am not sure I understand what is the difference with T5 here? 😓 If you want to add the model the best is to isolate the changes copied from t5 (wrap with. # Copied from) from the specificities of this model!

**Comment by Miaoranmmm** [comment]
> Hey! from scanning through the code I am not sure I understand what is the difference with T5 here? 😓 If you want to add the model the best is to isolate the changes copied from t5 (wrap with. # Copied from) from the specificities of this model!

Hi @ArthurZucker, thanks for your feedback. We have removed the duplicate content `modeling_hhemv2.py`. Please review the updated version.

**Review by ArthurZucker — COMMENTED** [review]
Hey! Thanks for updating, now as you are using `t5ForTokenClassification` I don't understand the need to add a new model entirely? 
If you want you can add this to the external ressources of the t5.md page to include a link to this work!

**Comment by forrestbao** [comment]
hi @ArthurZucker There are two differences here:
1. We hacked the T5ForTokenClassification for sequence classification. We padded a `<pad>` token at the beginning of the sequence in lieu of the `[CLS]` token and use the hidden state from the `<pad>` token to predict the final label. In this way, we only use the encoder part of T5. 
2. We also added the prompt template and tokenization into the class to save users the hassle. Now users can send pair of text and get the hallucination score -- while under the hood  the prompting and tokenization is done automatically for them.

**Comment by ArthurZucker** [comment]
Hey!
1. Changing the token should not induce changes in the modeling code. However if you change the way the forward pass (Not the token or the id being used) then alright! 
2. This is not really something we want to have in the model itlesf. The chat template should be in the documentation and directly saved in the model that is pushed to the hub! 
If you wait a bit for #33248 to be merged will be a lot better to use this approach!

**Pull request closed without merging**
