### PR TITLE
Test datasets@main for datasets-2.19.0 release

### PR DESCRIPTION
**Pull request by albertvillanova**
This PR tests that the transformers CI is green with datasets@main before we make the datasets-2.19.0 release.

I had to open a PR because I do not have right to push the branch to upstream:
```shell
$ git push -u upstream test-datasets-main-for-2.19.0-release
ERROR: Permission to huggingface/transformers.git denied to albertvillanova.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

TODO for the next release:
- Ask @huggingface/transformers team for rights to push to this repository

TODO: Rerun CI once these merged
- [x] https://github.com/huggingface/datasets/pull/6822
- [x] https://github.com/huggingface/transformers/pull/30319

### CODE REVIEW

**Comment by albertvillanova** [comment]
The CI is red. 

@huggingface/datasets, any ideas why?

**Comment by lhoestq** [comment]
Ok I found the issue - opening a PR in `datasets`

**Comment by lhoestq** [comment]
So the issue came from a new feature in `datasets` that reuses the exported `Features` from the Viewer.

This test dataset had erroneous exported `Features` in the Viewer and re-running the job fixed it.
I still opened https://github.com/huggingface/datasets/pull/6822 in `datasets` to avoid future issues when re-running jobs.

Feel free to re-run the tests once this PR is merged

**Comment by albertvillanova** [comment]
I have opened a PR to fix the test:
- #30319

**Comment by mariosasko** [comment]
Yes, I think we can consider this a bug fix (the EXIF orientation tag should not be ignored in ML workflows), which means the deprecation cycle is not needed.

**Comment by albertvillanova** [comment]
I am merging the main branch once #30319 is merged.

**Comment by albertvillanova** [comment]
The CI is green. I am making the release of datasets.

**Pull request closed without merging**
