### PR TITLE
Enable automatic creation of decoder_input_ids given labels in TF

### LINKED ISSUE #14397: [Consistency] Automatically set decoder_input_ids for TFEncoderDecoderModel
# 🚀 Feature request

Currently, the `EncoderDecoderModel` class in PyTorch automatically creates the `decoder_input_ids` based on the `labels` provided by the user (similar to how this is done for T5/BART). This should also be implemented for `TFEncoderDecoderModel`, because currently users should manually provide `decoder_input_ids` to the model.

One can take a look at the TF implementation of BART for example to see how to shift the labels in order to automatically create the `decoder_input_ids`, namely [here](https://github.com/huggingface/transformers/blob/29dfb2dbb10cdba6327ff287db56b182c1db29b1/src/transformers/models/bart/modeling_tf_bart.py#L1120).

One should then also update the docstring correspondingly.

### PR DESCRIPTION
**Pull request by Carlosbogo**
Added a way to automatically create the `decoder_input_ids` from the `labels` provided by the user the `TFEncoderDecoderModel`

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hey @Carlosbogo, thanks for your contribution! I've pinged @patrickvonplaten to review your PR, but please note that Patrick if off until next Monday. Thanks for your patience!

**Comment by patrickvonplaten** [comment]
Thanks for the PR @Carlosbogo! 

I think we should also move the loss computation into the `TFEncoderDecoderModel` class similar to how @NielsRogge has done it in this PR: https://github.com/huggingface/transformers/pull/14139 . Right now the loss is computed in the decoder. However we should compute the loss directly in the `TFEncoderDecoderModel` class.

**Comment by NielsRogge** [comment]
Hi @Carlosbogo, thanks for your contribution! Let me know if you are able to take into account the comment above.

Thanks!

**Comment by Carlosbogo** [comment]
Yeah,  I think I can work on that.
Should I create a new PR for it when I finish?

**Comment by NielsRogge** [comment]
No it can be included in this PR.

**Comment by patrickvonplaten** [comment]
Hey @Carlosbogo, 

Hope you had a good start to 2022! Let me know if I can help with anything to get this PR merged :-)

**Comment by Carlosbogo** [comment]
I'm really sorry for the delay: I had my university exams and couldn't find time to work on it. I'll try to do it as soon as possible.

**Pull request closed without merging**
