### PR TITLE
[tests] ensure device-required software is available in the testing environment before testing    

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?
When running unit tests on XPU, I notice that some tests fail because the required software `intel_extension_for_pytorch` is not imported beforehand. The fact is that third-party devices (e.g. xpu) should be used together with third-party software libraries (e.g. IPEX). Therefore, same as in [this](https://github.com/huggingface/transformers/blob/main/src/transformers/testing_utils.py#L814) line, we should make sure that the software is available in the environment, otherwise, we should interrupt the program, because user wants to use `xpu`, but he doesn't take care of its testing environment, e.g. install the required library.

BTW, this is an example how I run test on XPU:
```bash
TRANSFORMERS_TEST_DEVICE="xpu" TRANSFORMERS_TEST_DEVICE_SPEC="spec.py" python -m pytest -rA tests/test_modeling_utils.py
```

## Who can review?
@ArthurZucker and @muellerzr

### CODE REVIEW

**Comment by muellerzr** [comment]
I'd expect the `try/except` following that to fail if it's not available, do you know why that's not the case? (When testing `torch.device()`)

**Comment by faaany** [comment]
> I'd expect the `try/except` following that to fail if it's not available, do you know why that's not the case? (When testing `torch.device()`)

all devices in [this](https://github.com/pytorch/pytorch/blob/main/c10/core/Device.cpp#L17) list are valid for `torch.device()`, but this doesn't guarantee the required hardware and software are available in the environment.

**Comment by faaany** [comment]
@muellerzr but do you know why we have the variable `TRANSFORMERS_TEST_DEVICE` at all? Wouldn't be better that we auto-detect the hardware and set the corresponding `torch_device` for users automatically, just like in `accelerate`?

**Comment by ArthurZucker** [comment]
cc @ydshieh if you can have a look as well

**Comment by faaany** [comment]
Hi @ydshieh, could you take a look at this PR as well? Thank you so much!

**Comment by ydshieh** [comment]
Thank you @faaany This indeed improves the error message in an earlier stage.

@amyeroberts Do you feel strong to make them using `requires_backends`? I don't feel strong, as these places are not really about a library/package's availability. Also, the current approach is more precise regarding the error message.

**Review by ydshieh — APPROVED** [review]
Nice. 

BTW, the file `docs/source/en/testing.md` has no mention of XPU, you might want to add it to that file for XPU visibility :-)

**Review by amyeroberts — APPROVED** [review]
Thanks for adding! 

@ydshieh Not sure where you're suggesting to use `requires_backends`, but I think this is a good solution, which allows us to fail safely whilst still being flexible with the hardware for tests

**Comment by ydshieh** [comment]
@amyeroberts I am talking about the following block.

But let's keep as it is for now and revise in the future when necessary

```python
        if torch_device == "cuda" and not torch.cuda.is_available():
            raise ValueError(
                f"TRANSFORMERS_TEST_DEVICE={torch_device}, but CUDA is unavailable. Please double-check your testing environment."
            )
        if torch_device == "xpu" and not is_torch_xpu_available():
            raise ValueError(
                f"TRANSFORMERS_TEST_DEVICE={torch_device}, but XPU is unavailable. Please double-check your testing environment."
            )
        if torch_device == "npu" and not is_torch_npu_available():
            raise ValueError(
                f"TRANSFORMERS_TEST_DEVICE={torch_device}, but NPU is unavailable. Please double-check your testing environment."
            )
```

**Pull request merged**
