### PR TITLE
canonical repos moves

### PR DESCRIPTION
**Pull request by julien-c**
we are phasing out canonical models & datasets (as a reminder, "canonical" repos are those that were not under an org or user namespace) and moving them under ad hoc organization namespaces

Note that this move should be backward compatible i.e. old versions of transformers that do `AutoModel.from_pretrained("gpt2")` should still work. Download stats should also be backward-compatible.

Thanks for reading!

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Thanks for handling this as well!

**Review by ArthurZucker — COMMENTED** [review]
Can you run `make style` please ? 😉

**Comment by ArthurZucker** [comment]
too quick

**Comment by LysandreJik** [comment]
test is flaky no @ArthurZucker ?

**Comment by ArthurZucker** [comment]
Yes merging without it

**Comment by julien-c** [comment]
thanks friends!

**Pull request merged**
