### PR TITLE
fix uncaught init of linear layer in clip's/siglip's for image classification models

### LINKED ISSUE #30374: Bad weight init dependant of a processor import
### System Info

2024-04-21 16:25:02.913641: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-21 16:25:02.913701: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-21 16:25:02.915420: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-21 16:25:04.770200: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /usr/local/lib/python3.10/dist-packages/transformers/commands/env.py:100: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-04-21 16:25:08.126490: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `transformers` version: 4.38.2
- Platform: Linux-6.1.58+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.20.3
- Safetensors version: 0.4.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Tensorflow version (GPU?): 2.15.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.2 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@amyeroberts 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Colab demo: https://colab.research.google.com/drive/1eQMGHFvw7GJpYxtyInJjG60t0sIXXwiJ?usp=sharing

## The task

A custom classification problem using `CLIPForImageClassification` partially loading from pretrained.

```py
import torch
from transformers import AutoConfig, CLIPForImageClassification, CLIPProcessor


model_name="openai/clip-vit-base-patch32"

config = AutoConfig.from_pretrained(model_name)
```

The problem (weight initialised with huge numbers and nans (invert somewhere?)) arises when loading the model as:

```py
processor = CLIPProcessor.from_pretrained(model_name)
model = CLIPForImageClassification.from_pretrained(
    model_name, config=config
)
print(model.classifier.weight)
```

While loading the processor after the model doesn't initialise weirdly the weight (all 0, still weird but doable).

### Expected behavior

Good weight init. And definitely not dependant on when the processor is loaded.

### PR DESCRIPTION
**Pull request by vasqu**
# What does this PR do?
Fixes the uncaught initialisation of the last linear layer in `ForImageClassification` of Clip/Siglip, especially when using `from_pretrained`. More in-depth discussion at #30374. Possible failing tests are equivalence tests between tf/pt/flax; seems unrelated. 

The remaining discrepancy between `from_pretrained` and "from_config" has yet to be resolved. I'll leave it out since it might imply bigger things than reflected here. 

Fixes #30374

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@amyeroberts @Xmaster6y

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing so quickly!

**Comment by Xmaster6y** [comment]
LGTM!

**Comment by amyeroberts** [comment]
@vasqu Could you push an empty commit to this branch? This should trigger the slow model tests to make sure everything's still working as expected for CLIP

**Comment by vasqu** [comment]
@amyeroberts pushed an empty commit, but seems like the slow test still hasn't been triggered.

**Comment by vasqu** [comment]
Oh might've been that it's just slow :sweat_smile: my bad

**Comment by amyeroberts** [comment]
@vasqu Slow by name, slow by nature ;) I think it was actually waiting for me to approve - it won't run automatically for non-repo maintainers for security and to save our CI as they're quite heavy tests

**Comment by vasqu** [comment]
Ah, I see. Makes sense and yea, the name should've rang a bell ^^

**Comment by amyeroberts** [comment]
Thanks again for fixing this!

**Pull request merged**
