### PR TITLE
Add type hints for UniSpeech

### PR DESCRIPTION
**Pull request by Tegzes**
Adding type hints for forward methods in user-facing class for UniSpeech as mentioned in #16059

@Rocketknight1

### CODE REVIEW

**Comment by Rocketknight1** [comment]
Hey, this looks good but I'm going to leave a final review until the `Wav2vec` issue is resolved - for the record, I think it's totally fine for you to update that file too!

**Comment by Tegzes** [comment]
Yeah, I think I will work on it and make a commit today

**Comment by Tegzes** [comment]
There are some other models that are dependent on Wave2Vec2, I will modify them asap

**Comment by Tegzes** [comment]
@Rocketknight1  I think it's good to go now

**Comment by Tegzes** [comment]
@Rocketknight1  I think it's good to go now

**Review by Rocketknight1 — APPROVED** [review]
Looks great to me, thank you!

**Pull request merged**
