### PR TITLE
Fix SAM tests and use smaller checkpoints

### PR DESCRIPTION
**Pull request by Rocketknight1**
This PR moves all the SAM tests for both PT and TF to the `sam-vit-base` instead of the `sam-vit-huge` (!) checkpoint they were using before. The huge checkpoint made the tests quite slow and caused OOM issues in TensorFlow.

It also fixes an issue with the `check_pt_tf_equivalence` test in the PyTorch tests, which should now pass correctly.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for the fixes!

**Review by ydshieh — APPROVED** [review]
Thank you @Rocketknight1 you rock!

```bash
tests/models/sam/test_modeling_tf_sam.py::TFSamModelTest::test_model_from_pretrained
```
is still failing with
```bash
FAILED tests/models/sam/test_modeling_tf_sam.py::TFSamModelTest::test_model_from_pretrained - tensorflow.python.framework.errors_impl.ResourceExhaustedError: Exception encountered when calling layer 'attn' (type TFSamVisionAttention).
```

**Comment by Rocketknight1** [comment]
Ah! That test was also sneakily loading `sam-vit-huge`. I've fixed it, it should work fine now.

**Comment by ydshieh** [comment]
All pass now 🚀

**Pull request merged**
