### PR TITLE
Fix two tiny typos in `pipelines/base.py::Pipeline::_sanitize_parameters()`'s docstring

### PR DESCRIPTION
**Pull request by sadra-barikbin**
Hi there!
To fix two tiny typos in `pipelines/base.py::Pipeline::_sanitize_parameters()`'s docstring.

@Narsil

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by sadra-barikbin** [comment]
One more thing. We have `False` for default value of `clean_up_tokenization_spaces` argument in `TextGenerationPipeline`'s docstring:
https://github.com/huggingface/transformers/blob/593230f0a1150ea9c0477b9d859f25daf73c8c33/src/transformers/pipelines/text_generation.py#L207-L208

but its default value in `TextGenerationPipeline::postprocess` is `True`:
https://github.com/huggingface/transformers/blob/593230f0a1150ea9c0477b9d859f25daf73c8c33/src/transformers/pipelines/text_generation.py#L336

**Comment by amyeroberts** [comment]
@sadra-barikbin Good spot! Could you add a fix for the docstring in this PR too?

**Comment by sadra-barikbin** [comment]
The pipelines in `text2text_generatino.py` class have `clean_up_tokenization_spaces=False` as default. This has been the desired behavior?

**Comment by amyeroberts** [comment]
@sadra-barikbin Yes, I believe so. Changing the default behaviour would be a breaking change, so we should keep as-is

**Pull request merged**
