### PR TITLE
fix model ids for Qwen2

### PR DESCRIPTION
**Pull request by JustinLin610**
This PR fixes the names of doc and test files.

### CODE REVIEW

**Comment by LysandreJik** [comment]
@ydshieh @fxmarty can you take a look?

**Comment by ydshieh** [comment]
Hi @JustinLin610 Thank you for the fix.

`Qwen2-450m-beta` has 8 `occurrence` on the `main` branch (in the test files), but I only 2 places are replaced.

Also, it would be better to pull huggingface/transformers main and create a new branch for the PR (rather than just based on your original model addition PR). It looks a bit strange this PR contains 78 commits, despite the file changes are 3 files.

**Comment by JustinLin610** [comment]
I see what you mean. I'll just close this PR and start another one with a new branch

**Comment by JustinLin610** [comment]
> Hi @JustinLin610 Thank you for the fix.
> 
> `Qwen2-450m-beta` has 8 `occurrence` on the `main` branch (in the test files), but I only see 2 places are replaced.
> 
> Also, it would be better to pull huggingface/transformers main and create a new branch for the PR (rather than just based on your original model addition PR). It looks a bit strange this PR contains 78 commits, despite the file changes are 3 files.

https://github.com/huggingface/transformers/pull/29723 I just committed another PR here.

**Pull request closed without merging**
