### PR TITLE
Minor docs typo fixes

### PR DESCRIPTION
**Pull request by guyrosin**
# What does this PR do?
Just a few typo fixes in the docs.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?
@sgugger

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Great fixes, thanks a lot!

**Comment by sgugger** [comment]
Looks like you have a styling problem, could you run the command `make style` after doing a dev install with
```
pip install -e .[dev]
```
in the repo?

**Comment by guyrosin** [comment]
Oops! Done.

**Review by LysandreJik — APPROVED** [review]
Thanks!

**Pull request merged**
