### PR TITLE
[WIP] SMITH

### LINKED ISSUE #9526: Siamese Multi-depth Transformer-based Hierarchical Encoder
# 🌟 New model addition

## Model description
Recently Google is published paper titled ["Beyond 512 Tokens: Siamese Multi-depth Transformer-based Hierarchical Encoder for Long-Form Document Matching"](https://arxiv.org/abs/2004.12297). And according to paper for long-form document matching SMITH model outperforms the previous state-of-the-art models including hierarchical attention, multi-depth attention-based hierarchical recurrent neural network, and BERT.

I feel it is will add value to already awesome transformers models collection :slightly_smiling_face:

## Open source status

* [X] the model implementation is available: https://github.com/google-research/google-research/tree/master/smith
* [X] the model weights are available: [SMITH-WP+SP model checkpoint](http://storage.googleapis.com/gresearch/smith_gwikimatch/smith_wsp_pretrain_ckpt_opensource.zip) and [GWikiMatch data](http://storage.googleapis.com/gresearch/smith_gwikimatch/gwikimatch_open_source.zip)
* [X] who are the authors: https://github.com/yangliuy, https://github.com/eladeban

### PR DESCRIPTION
**Pull request by gchhablani**
# What does this PR do?

This PR adds SMITH encoder by Google Research and potentially closes #9526.

Potential reviewers:
@LysandreJik @patil-suraj

### CODE REVIEW

**Comment by amineabdaoui** [comment]
Hi @gchhablani 

What is the state if this PR ?

Have you tried loading [the official SMITH checkpoint](https://github.com/google-research/google-research/tree/master/smith#pre-trained-model-checkpoint) ?

Amine

**Comment by gchhablani** [comment]
Hi @amineabdaoui

I had tried it a while back and it had worked. My focus switched to other things. I'll get back onto this PR this week.

**Comment by amineabdaoui** [comment]
Good to hear that you were able to load it !
I guess that the conventional `from_pretrained()` method is not appropriate to load the Google's checkpoint in your new classes?

**Review by theMADAIguy — APPROVED** [review]

**Comment by ArthurZucker** [comment]
Closing as this PR is super old

**Pull request closed without merging**
