### PR TITLE
Fix CLAP link across all READMEs

### PR DESCRIPTION
**Pull request by ehsanmok**
# What does this PR do?

Fixes CLAP link across all READMEs

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Nice, catch! Thanks a lot for the fixes! Can you run `make fix-copies` on your branch to fix the link in the index of the doc too?

**Comment by ehsanmok** [comment]
I'm getting

```
Traceback (most recent call last):
  File "/Users/ehsan/workspace/transformers/utils/check_task_guides.py", line 58, in <module>
    "asr.mdx": transformers_module.models.auto.modeling_auto.MODEL_FOR_CTC_MAPPING_NAMES,
  File "/Users/ehsan/workspace/transformers/src/transformers/utils/import_utils.py", line 1150, in __getattr__
    raise AttributeError(f"module {self.__name__} has no attribute {name}")
AttributeError: module transformers.models.auto has no attribute modeling_auto. Did you mean: 'processing_auto'?
```

not sure what's going on so I added it manually to all the `index.mdx`. It seems not all models research paper links have been synced across docs.

**Review by sgugger — COMMENTED** [review]
Better to add it in the English index only, the others are not synchronized because we wait for the community to sync them from time to time along with the translation. Some of the index you added the CLAP to are mostly in English for this part, but for others you are introducing English instead of the language used in other lines.

**Comment by sgugger** [comment]
Thanks again!

**Pull request merged**
