### PR TITLE
Examples: add Bloom support for token classification

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

this PR adds support for fine-tuning Bloom models for token classification tasks.

After trying out the current example, I got an error message from the tokenizer part, that `add_prefix_space=True` needs to be set. So with this PR, Bloom can be used in token classification example for PyTorch (there's no support for TensorFlow/FLAX yet).

### CODE REVIEW

**Comment by LysandreJik** [comment]
cc @younesbelkada

**Review by younesbelkada — COMMENTED** [review]
Hi @stefan-it !
Thanks for adding this fix! Could you please provide me an example command to reproduce your initial issue? I was not able to reproduce it, so maybe we can find the rootcause of the initial issue and see if we can fix this instead
Thanks 🙏

**Comment by stefan-it** [comment]
Hi @younesbelkada ,

sure no problem, here are the steps (fresh environment):

```bash
git clone https://github.com/huggingface/transformers.git
cd transformers/
pip3 install -e .
pip3 install seqeval evaluate
cd examples/pytorch/token-classification
python3 run_ner.py   --model_name_or_path bigscience/bloom-560m   --dataset_name conll2003   --output_dir ./output-bloom-560m   --do_train   --do_eval   --do_predict
```

Then the following error message is thrown:

```bash
Traceback (most recent call last):
  File "run_ner.py", line 630, in <module>
    main()
  File "run_ner.py", line 464, in main
    train_dataset = train_dataset.map(
  File "/opt/conda/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2387, in map
    return self._map_single(
  File "/opt/conda/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 557, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 524, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datasets/fingerprint.py", line 480, in wrapper
    out = func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2775, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/opt/conda/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2655, in apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2347, in decorated
    result = f(decorated_item, *args, **kwargs)
  File "run_ner.py", line 422, in tokenize_and_align_labels
    tokenized_inputs = tokenizer(
  File "/workspace/transformers/src/transformers/tokenization_utils_base.py", line 2475, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/workspace/transformers/src/transformers/tokenization_utils_base.py", line 2561, in _call_one
    return self.batch_encode_plus(
  File "/workspace/transformers/src/transformers/tokenization_utils_base.py", line 2752, in batch_encode_plus
    return self._batch_encode_plus(
  File "/workspace/transformers/src/transformers/models/bloom/tokenization_bloom_fast.py", line 140, in _batch_encode_plus
    raise Exception(
Exception: You need to instantiate BloomTokenizerFast with add_prefix_space=True to use it with pretokenized inputs.
```

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for spotting the issue and fixing it!
Indeed it is better to go for this solution. I was thinking of putting `add_prefix_space=True` in the constructor of `BloomTokenizerFast` to have it as a default behaviour. But since the model has not been trained with this feature, it is preferable to keep the tokenizer definition as it is and hotfix the example script as you did 💪 !

**Review by LysandreJik — APPROVED** [review]

**Pull request merged**
