### PR TITLE
Auto-translate GPTNeo to TensorFlow with GPT-4

### PR DESCRIPTION
**Pull request by Rocketknight1**
cc @gante @amyeroberts @ydshieh @sayakpaul

This is the preliminary result of auto-translating an entire module to TensorFlow using GPT-4.

The prompt I used was:

> 
> Hi GPT, can you translate this class from Hugging Face Transformers from PyTorch to TensorFlow for me?
> Some pointers:
> - When creating layers, please pass their attribute name as the name kwarg.
> - Retain any docstrings attached to methods like forward and translate them, even when the method is being renamed to call.
> - If the new class inherits from tf.keras.layers.Layer, it should accept **kwargs and pass these to super.__init__ . It should also be renamed by adding "TF" to the start of its name.
> - You don't need to add any extra imports, you can assume that any other functions or classes you call will be imported for you.
> - If the class calls other classes in the same module, you can assume that these have already been converted. Please add "TF" to the start of their name if required.

I'm going to experiment with auto-translating the tests and seeing how successful this port was. Right now it's a WIP and there are likely issues, but I've had a lot of success avoiding problems just by mentioning them in the prompt and telling GPT what to do in those situations!

Other things to go in the prompt:

- PyTorch Embedding layers support a `padding_idx` initialization arg that TF does not. If you want to exactly match PT's behaviour, you need to manually zero out those positions after embedding in TF.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Shame Github doesn't have 🔥 as an available reaction

**Comment by ydshieh** [comment]
> Shame Github doesn't have 🔥 as an available reaction

@amyeroberts 🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

Screenshot 2023-03-24 185139

**Comment by sayakpaul** [comment]
@Rocketknight1 aren't the commits going a bit too fast? 😑

**Comment by sgugger** [comment]
I don't want to be a party pooper but this is really not a use case where I would trust any kind of language model output. LLMs tend to produce content that look good on the surface but are not rigorous and usually full of nasty little bugs (that's the reason why I personally stopped using Copilot) and we will completely miss them in such PRs that are usually adding one or several thousands of lines. I don't think our CI will catch all such bugs.

**Comment by Rocketknight1** [comment]
@sgugger Absolutely agree on the potential for small bugs, but in the case of model porting doesn't the CI test equivalence with the PT original? If the model accepts various inputs and always yields equivalent output to the PT version, I think it's probably "good enough" that most users shouldn't notice any issues, right?

**Comment by sgugger** [comment]
Well for now those tests fail even before returning a diff between the PT and TF model :-p

**Comment by Rocketknight1** [comment]
I'm still working on the prompt!!!!!

**Comment by sgugger** [comment]
Ah ah, are you saying this should be the code exercise if we ever decide to open a Prompt Engineer position?

**Comment by ydshieh** [comment]
> Ah ah, are you saying this should be the code exercise if we ever decide to open a Prompt Engineer position?

That would be **THE** middleman between `PyTorch` and `TensorFlow`.

**Pull request closed without merging**
