### PR TITLE
consistently use True/False for `return_tuple`

### PR DESCRIPTION
**Pull request by stas00**
…

consistently use True/False for `return_tuple` (currently it's sometimes None, sometimes False)

### CODE REVIEW

**Comment by sgugger** [comment]
Mmm, it should be `None` all the time except if the model doesn't have an inner config. The current behavior for all other flags (`output_hidden_states` and `output_attentions`) is that passing an argument supersedes the config. So for instance, passing `return_tuple=False` to the model even if `config.return_tuple = True` should end up with no `return_tuple`.

**Comment by stas00** [comment]
But why is there a need for a 3rd state, why not just default to `False`?

**Comment by sgugger** [comment]
That is the way those flags are set and consistency with the others is less likely to surprise users:
`None` -> use the value in config (defaulting to `False`)
`False` -> force-use `return_tuple=False` even if the config says `True`
`True` -> force-use `return_tuple=True` even if the config says `False`

One can imagine the user has set the config a certain way but needs to bypass it. Returning a tuple for a punctual conversion to ONNX for instance, or not returning one on a model set for jit-tracing/ONNX just to get the documented output while doing a punctual test.

**Comment by julien-c** [comment]
I agree that nullable boolean are a good API design 💯

**Comment by stas00** [comment]
Thank you for your explanation, @sgugger!

**Pull request closed without merging**
