### PR TITLE
Implement AsyncTextIteratorStreamer for asynchronous streaming

### PR DESCRIPTION
**Pull request by CISC**
# Asynchronous text generation streaming

Added a new `AsyncTextIteratorStreamer` class that allows you to have fully asynchronous text generation streaming in your application. Works identically to `TextIteratorStreamer` except that you iterate the stream as follows:
```python
generated_text = ""
async for new_text in streamer:
    generated_text += new_text
```

~~Requires Python 3.11+ due to use of `asyncio.timeout` to handle timeout.~~ Falls back to `asyncio.wait_for` if `asyncio.timeout` is not available.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

~~Any hints on how best to implement an async test would be appreciated. :)~~ pytest-asyncio seems to be the way to go...

## Who can review?

@gante @ArthurZucker

### CODE REVIEW

**Comment by CISC** [comment]
@gante @ArthurZucker Ready for review.

**Comment by CISC** [comment]
@ArthurZucker @gante ping

**Comment by CISC** [comment]
@ArthurZucker ping with sugar on top?

Seems @gante is on holiday, anyone else who can review?

**Comment by Rocketknight1** [comment]
Gentle ping @gante, or maybe @zucchini-nlp if I haven't totally overloaded her with pings at this point!

**Comment by CISC** [comment]
@Rocketknight1 Thanks! BTW, know what's up with `check_code_quality` and/or how to fix it?

**Comment by Rocketknight1** [comment]
@CISC that's usually a code style thing. Try `pip install transformers[quality]` followed by `make fixup`

**Comment by CISC** [comment]
@Rocketknight1 It's not, it's complaining about the import order in `src/transformers/__init__.py`, which I did not change... :(

**Comment by Rocketknight1** [comment]
@CISC `make fixup` will also resolve issues like that! In this case, the `__init__.py` has actually been modified in this PR to allow the class to be imported (check `Files changed` - it's in there!). Our code styling tools just want to correctly sort/order inputs into the standard format.

**Comment by ArthurZucker** [comment]
Sorry @CISC reviewing!

**Review by ArthurZucker — APPROVED** [review]
Looks marvelous sorry for being so late. I actually wanted to wait because we added https://github.com/huggingface/tokenizers/pull/1678 a decode stream api in `tokenizers` that fixes some issues with prefix space, but the changes are for another PR and for the base Text streamer! 🤗 cc @gante

**Comment by ArthurZucker** [comment]
Do you want us to fix the CIs for you? I can push directlyu

**Comment by CISC** [comment]
> Do you want us to fix the CIs for you? I can push directlyu

Yes please, thank you. :)

**Comment by ArthurZucker** [comment]
thanks @CISC 🤗

**Pull request merged**
