### PR TITLE
Super tiny fix 12 typos about "with with"

### PR DESCRIPTION
**Pull request by fzyzcjy**
Hi thanks for the library! Today when reading Bart's doc I see a `with with` typo, and when I want to search-and-modify it, I see a dozen of places having this, thus I made a quick replace about it.

# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
Hi @fzyzcjy, thanks for the update! Can you `pip install transformers[quality]` and then `make fixup` in the directory to run the code formatting tools? That should make the tests pass!

**Comment by fzyzcjy** [comment]
Done!

**Review by Rocketknight1 — APPROVED** [review]
Looks good to me now - thanks for the fix!

**Comment by fzyzcjy** [comment]
You are welcome and thanks for the lib!

**Pull request merged**
