### PR TITLE
Enabling live `automatic-speech-recognition` asr for Whisper.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

Enables live ASR for Whisper.
Inference is slower for ASR than CTC models though, so these demos come with 
come caveat:

**IT will not be live on too small hardware**. Just because it will fall behind
in inference times.

Simplest fix would be to increase the `stream_chunk_s` parameter. That will reduce
the "liveliness" of the inference but would put less strain on the hardware.

Another more complex fix (outside of these short scripts) would be to keep track
of real time, and **skip** some inferences in the pipelines when we are too late.

Live script:

```python
import sys
import numpy as np
from transformers import pipeline
from transformers.pipelines.audio_utils import ffmpeg_microphone_live
from curses import wrapper
import curses


def main():
    pipe = pipeline("automatic-speech-recognition", model="openai/whisper-base", device=0)
    sampling_rate = pipe.feature_extractor.sampling_rate

    chunk_length_s = 5
    stream_chunk_s = 0.1
    mic = ffmpeg_microphone_live(
        sampling_rate=sampling_rate,
        chunk_length_s=chunk_length_s,
        stream_chunk_s=stream_chunk_s,  # , stride_length_s=(1, 0.1)
    )
    print("Start talking...")
    stdscr = curses.initscr()
    curses.noecho()
    curses.cbreak()
    text = ""
    for item in pipe(mic):
        displayed = text + item["text"]
        if not item["partial"][0]:
            text += item["text"]

        stdscr.addstr(0, 0, displayed)
        stdscr.clrtoeol()
        stdscr.refresh()


if __name__ == "__main__":
    wrapper(main())

```

Simpler script:

```python
import datetime
import sys
from transformers import pipeline
from transformers.pipelines.audio_utils import ffmpeg_microphone_live

pipe = pipeline("automatic-speech-recognition", model="openai/whisper-base", device=0)
sampling_rate = pipe.feature_extractor.sampling_rate


start = datetime.datetime.now()

chunk_length_s = 5
stream_chunk_s = 0.1
mic = ffmpeg_microphone_live(
    sampling_rate=sampling_rate,
    chunk_length_s=chunk_length_s,
    stream_chunk_s=stream_chunk_s,
)
print("Start talking...")
for item in pipe(mic):
    sys.stdout.write("\033[K")
    print(item["text"], end="\r")
    if not item["partial"][0]:
        print("")
```

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
LGTM!

**Review by ArthurZucker — APPROVED** [review]
LGTM but we could add your script somewhere no? Seems like it was asked

**Comment by Narsil** [comment]
> LGTM but we could add your script somewhere no? Seems like it was asked

Where ? 
The `examples` is more focused on fine-tuning/training. It could be in the docstring of ASR pipeline ( which already contain tons of information).

Ultimately both examples are nice-to-have things, but definitely not something we want to support as the rest of core transformers iirc the discussions when this was added. Too many specific things, like capturing the correct mic is a hard job, then the amount of features that might be wanted could be very intense, and it's not really the goal of `tranformers` to maintain this. This is more a showcase and because using ffmpeg enables a relatively short code base for support.
Maybe something that could be more prominently be features in `speechbox`. @patrickvonplaten  for an opinion on this ?

**Comment by kadirnar** [comment]
@Narsil 
I'm testing it on Mac M2 Pro and it's not working. How can I fix this?
```bash
Start talking...
2024-05-11 12:56:44.036 ffmpeg[5850:59141] WARNING: Add NSCameraUseContinuityCameraDeviceType to your Info.plist to use AVCaptureDeviceTypeContinuityCamera.
2024-05-11 12:56:44.236 ffmpeg[5850:59141] WARNING: AVCaptureDeviceTypeExternal is deprecated for Continuity Cameras. Please use AVCaptureDeviceTypeContinuityCamera and add NSCameraUseContinuityCameraDeviceType to your Info.plist.
```

**Pull request merged**
