### PR TITLE
Update training_args.py to fix runtime error

### PR DESCRIPTION
**Pull request by sahel-sh**
Fix File "..../transformers/training_args.py", line 1544, in __post_init__
      for k, v in self.fsdp_config.items():
  RuntimeError: dictionary keys changed during iteration

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Hey! Thanks for opening a PR 🤗 could you also share a reproducer? Would help determine whether this is an intended use case or not!

**Comment by sahel-sh** [comment]
From [FastChat](https://github.com/lm-sys/FastChat/blob/main/scripts/test_readme_train.sh) repo:
```
torchrun --nproc_per_node=4 --master_port=20001 fastchat/train/train_mem.py \
    --model_name_or_path lmsys/vicuna-7b-v1.5 \
    --data_path data/dummy_conversation.json \
    --bf16 True \
    --output_dir output_vicuna \
    --num_train_epochs 3 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1200 \
    --save_total_limit 10 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --fsdp "full_shard auto_wrap" --fsdp_config $HOME/fsdp_config.json \
    --tf32 True \
    --model_max_length 4096 \
    --gradient_checkpointing True \
    --lazy_preprocess True
```

Where fsdp_config.json is:
```
{
    "fsdp_auto_wrap_policy": "FULL_SHARD",
    "fsdp_transformer_layer_cls_to_wrap": "LlamaDecoderLayer"
}
```
Any command with this config file or any other config files that has json keys starting with "fsdp_" will reproduce the issue. The code is updating dictionary elements while iterating over it.

**Comment by sahel-sh** [comment]
I think https://github.com/huggingface/transformers/pull/25920 is a better solution though.

**Comment by sahel-sh** [comment]
Closing this in favor of https://github.com/huggingface/transformers/pull/25920

**Pull request closed without merging**
