### PR TITLE
fix examples/rag imports, tests

### LINKED ISSUE #7713: rag examples tests fail
```
================================================================ ERRORS =================================================================
______________________________________ ERROR collecting examples/rag/test_distributed_retriever.py ______________________________________
ImportError while importing test module '/Users/shleifer/transformers_fork/examples/rag/test_distributed_retriever.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
examples/rag/test_distributed_retriever.py:26: in <module>
    from examples.rag.distributed_retriever import RagPyTorchDistributedRetriever  # noqa: E402 # isort:skip
E   ModuleNotFoundError: No module named 'examples.rag'
```

### PR DESCRIPTION
**Pull request by sshleifer**
Before
```bash
pytest examples/rag
```
fails with
```
================================================================ ERRORS =================================================================
______________________________________ ERROR collecting examples/rag/test_distributed_retriever.py ______________________________________
ImportError while importing test module '/Users/shleifer/transformers_fork/examples/rag/test_distributed_retriever.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
examples/rag/test_distributed_retriever.py:26: in <module>
    from examples.rag.distributed_retriever import RagPyTorchDistributedRetriever  # noqa: E402 # isort:skip
E   ModuleNotFoundError: No module named 'examples.rag'
```

After, the same command passes.

The fix was to change
`from examples.rag.file_name -> from filename` 
and add the same `sys.path` magic that `examples/seq2seq/` uses.

### TODO
- test the scripts in `examples/rag/README.md` after this change

### CODE REVIEW

**Comment by sshleifer** [comment]
@stas00 does this look reasonable? Am I missing anything you did for `examples/seq2seq`?

**Comment by stas00** [comment]
yes, except you shouldn't need 
```
sys.path.append(os.path.join(os.getcwd()))  # noqa: E402 # noqa: E402 # isort:skip
```
and once removed, all those `# noqa:` comments, that's what `__init__.py` already did for you.

**Review by patrickvonplaten — APPROVED** [review]
This is good for me

**Comment by sshleifer** [comment]
Scripts work, will merge on CI success.

**Comment by stas00** [comment]
btw, you can also remove most of the `# noqa: E402 # isort:skipq` as they are no longer needed.

**Pull request merged**
