### PR TITLE
Fix 29807, sinusoidal positional encodings overwritten by post_init()

### LINKED ISSUE #29807: Sinusoidal positional encodings overwritten by post_init()
I am trying to use DistillBert with sinusoidal positional encodings. At https://github.com/huggingface/transformers/blob/e68ff304194b4fba17cd13dc32fc3d3d61e9c0a7/src/transformers/models/distilbert/modeling_distilbert.py#L713 aren't sinusoidal positional encodings overwritten by `init_weights()` at line 632?

### PR DESCRIPTION
**Pull request by hovnatan**
# What does this PR do?

Fixes huggingface/transformers#29807, sinusoidal positional encodings overwritten by post_init(). First time contributing, please let me know of any issues, comments.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
      https://github.com/huggingface/transformers/issues/29807
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
@ArthurZucker, @younesbelkada, @amyeroberts

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! IMO we should rather place 
```
        if config.sinusoidal_pos_embds:
            create_sinusoidal_embeddings(
                n_pos=config.max_position_embeddings, dim=config.dim, out=self.position_embeddings.weight
            )

```

in the `_init_weights` function. 
Also this should be made BC as older version did not have the requirement on `_init_weights` being the only mode of initializing the weights

**Comment by hovnatan** [comment]
@ArthurZucker `_init_weights()` doesn't have config information. I moved sinusoidal positional encoding generation after `post_init()` in my latest commit. Is that ok?

**Comment by ArthurZucker** [comment]
It does but you can check if the name is `"position_embeddings"`! 🤗

**Comment by hovnatan** [comment]
AFAIK `post_init()` uses pytorch `Module`'s `apply(init_func)` functionality which doesn't pass name of the module to the `init_func()`, see https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.apply.

**Comment by hovnatan** [comment]
Anyways, please look at my latest changes. They solve the problem, but not sure if this is optimal

**Review by ArthurZucker — APPROVED** [review]
Perfect! Thanks for iterating

**Pull request merged**
