### PR TITLE
Consider do_lower_case in PreTrainedTokenizer

### PR DESCRIPTION
**Pull request by watkinsm**
As pointed out in #1545, when using an uncased model, and adding a new uncased token, the tokenizer does not correctly identify this in the case that the input text contains the token in a cased format.

For instance, if we load bert-base-uncased into BertTokenizer, and then use .add_tokens() to add "cool-token", we get the expected result for .tokenize('this is a cool-token'). However, we get a possibly unexpected result for .tokenize('this is a cOOl-Token'), which in fact mirrors the result for the former from before the new token was added.

This PR adds
- functionality to PreTrainedTokenizer to handle this situation in case a tokenizer (currently Bert, DistilBert, and XLNet) has the do_lower_case=True kwarg by:
    1) lowercasing tokens added with .add_tokens()
    2) lowercasing text at the beginning of .tokenize()
- new common test case for tokenizers

XLMTokenizer's `do_lowercase_and_remove_accent` is a bit more complicated and is not included in this PR.

### CODE REVIEW

**Comment by julien-c** [comment]
this lgtm but let's wait for @thomwolf and @LysandreJik to chime in

**Comment by watkinsm** [comment]
I'd also like to improve the test cases. I'll try to find some time for that this weekend

**Comment by LysandreJik** [comment]
Nice improvement, it would be even better with tests for DistilBERT and XLNet as both those models make use of the `do_lower_case` argument. TransfoXL also uses the `lower_case` argument and XLM the `do_lowercase_and_remove_accent` argument so it might be a good idea to test that those models have the correct behavior.

Putting tests in the `tokenization_tests_common` would probably be cleaner than in each model's test file, if we test all models rather than a single one.

**Comment by watkinsm** [comment]
@LysandreJik good points.

Now that I'm thinking about it, it seems like it would make more sense to do the lowercasing/accent removal directly in the subclasses (`BertTokenizer`, `XLMtokenizer`, etc.) by overriding the `tokenize()` method from `PreTrainedTokenizer`, performing the normalization there, then calling the super `tokenize()` with the now-normalized text.

**Comment by LysandreJik** [comment]
Alright that looks good to me!

**Comment by thomwolf** [comment]
Ok merging!

**Pull request merged**
