### PR TITLE
Fix issues caused by natten

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Don't really know what happened, but from the suggestion

> E   Failed to import NATTEN's CPP backend. This could be due to an invalid/incomplete install. Please uninstall NATTEN (pip uninstall natten) and re-install with the correct torch build: shi-labs.com/natten

I changed the installation command. It works, see https://app.circleci.com/pipelines/github/huggingface/transformers/83676/workflows/36ffade9-c7e6-49c2-b8f4-bb5fcb016a83/jobs/1079519

Fix current error we have

> __________ ERROR collecting tests/models/dinat/test_modeling_dinat.py __________
../.pyenv/versions/3.8.12/lib/python3.8/site-packages/natten/functional.py:28: in <module>
    from natten import _C
E   ImportError: /home/circleci/.pyenv/versions/3.8.12/lib/python3.8/site-packages/natten/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops10zeros_like4callERKNS_6TensorESt8optionalIN3c1010ScalarTypeEES5_INS6_6LayoutEES5_INS6_6DeviceEES5_IbES5_INS6_12MemoryFormatEE

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
That's only for the exotic and doctest, might have nightly issues no?

**Comment by ydshieh** [comment]
> might have nightly issues no?

sorry, what do you mean? You mean the daily CI? I haven't have the time to check, recently quite a lot of changes arriving

**Comment by ArthurZucker** [comment]
I mean we might want to change this for the daily ci as well 😉

**Comment by ydshieh** [comment]
Sure, but let's unblock red CircleCI first (I'm  fine but you probably prefer need it's green more than me need it 😄 )

**Comment by ArthurZucker** [comment]
Yep that's why I approved! 👍🏻

**Pull request merged**
