### PR TITLE
Fix mixtral ONNX Exporter Issue.

### PR DESCRIPTION
**Pull request by AdamLouly**
This PR addresses issue [#29857 ](https://github.com/huggingface/transformers/issues/29857) 

by removing the list conversion of top_x and idx in the Mixtral model code, which currently obstructs the ONNX exporter's functionality. 

By removing this conversion, the Mixtral model can be exported successfully using the ONNX exporter, resolving the compatibility issue.

### CODE REVIEW

**Comment by AdamLouly** [comment]
@thiagocrepaldi FYI.

**Review by thiagocrepaldi — COMMENTED** [review]
to expedite the code review, use git blame and find previous users who actually approved prs for changes in this file and add them to the code review.

Otherwise, the PR can be waiting for triage a long time

@ArthurZucker FYI

**Review by ArthurZucker — COMMENTED** [review]
Thanks a lot! 
Would love to merge this, we had to go with this because indexing is faster with list. 

would you mind just running some benchmarks in generation? 
Really sorry we don't have them yet in `transformers` but coming soon! (FYI @ydshieh )

**Comment by AdamLouly** [comment]
Hey @ArthurZucker  any updates on this?

**Comment by ydshieh** [comment]
@AdamLouly 

I think what @ArthurZucker 's comment is about

> would you mind just running some benchmarks in generation?

on your own side to see if the PR and `main` have difference in the speed of generation for this model

**Comment by ArthurZucker** [comment]
On point @ydshieh . This is very core, and we added this change for a reason, we need a good reason to update, and make sure we are not affecting performances

**Comment by AdamLouly** [comment]
@ArthurZucker, I actually found it faster when we use the changes in the PR.

Environment specs:
V100
Mixtral-8x7B-v0.1
2 Hidden layers
Loaded using torch_dtype=torch.float16

With the PR changes:
{'train_runtime': 182.1736, 'train_samples_per_second': 8.783, 'train_steps_per_second': 0.274, 'train_loss': 1.3467385864257813, 'epoch': 5.71}                                 


Without PR changes:
{'train_runtime': 200.6888, 'train_samples_per_second': 7.973, 'train_steps_per_second': 0.249, 'train_loss': 1.3390922546386719, 'epoch': 5.71}                                 

Thank you

**Review by ArthurZucker — COMMENTED** [review]
Alright. Let's also update the `qwen` models as well then! (ctrl + f for this operation)

**Comment by AdamLouly** [comment]
I could not find anything like that on qwen models, are you sure it uses the same thing?

**Comment by ArthurZucker** [comment]
This here! : https://github.com/huggingface/transformers/blob/8e51901872894c3bf9666daf485bb4c267980cad/src/transformers/models/qwen2_moe/modeling_qwen2_moe.py#L847

qwen2 sorry

**Review by ArthurZucker — APPROVED** [review]
Thanks

**Pull request merged**
