### PR TITLE
Add MP Net 2

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

Copy of #8971 that had to close because of problems with git history.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Comment by StillKeepTry** [comment]
@patrickvonplaten Never mind, just use this PR is ok. I am ok if our work can be merged into the master quickly.

**Comment by patrickvonplaten** [comment]
@jplu @LysandreJik @sgugger , we all gave our thumbs-up in the old PR. It's a bit unfortunate that the authorship is slightly changed here, but the PR should be read to merge.

**Review by jplu — APPROVED** [review]
I'm ok if the missing PreTraining models are ok for everyone!

**Review by sgugger — APPROVED** [review]
Still LGTM!

**Comment by LysandreJik** [comment]
Squashed commit & cherry picked on the `master` branch so that the authorship is kept in df2af6d. Closing.

**Comment by LysandreJik** [comment]
@StillKeepTry thanks a lot for all of your hard work on this PR! Glad to welcome MPNet in the library!

**Comment by StillKeepTry** [comment]
Thanks every reviewer for helping review our work. :)

**Pull request closed without merging**
