### PR TITLE
Fix onnx export input names order

### PR DESCRIPTION
**Pull request by RensDimmendaal**
This PR makes it possible to export custom bert models to onnx.

It resolves the issue addressed [here](https://github.com/huggingface/transformers/issues/4523#issuecomment-634920569).

TODO: 
- [x] update ensure_valid_input function
- [x] update test ensure_valid_input_function
- [x] update convert_pytorch
- [x] add a test of exporting a custom pytorch models

@mfuntowicz

### CODE REVIEW

**Comment by RensDimmendaal** [comment]
@mfuntowicz what do you think of my proposed changes?

I'm not sure why the CI fails on `TFAutoModelTest.test_from_identifier_from_model_type` as I haven't touched it.

**Comment by mfuntowicz** [comment]
LGTM! Thanks @RensDimmendaal for looking at this :)

**Comment by mfuntowicz** [comment]
@LysandreJik should we merge with the failing test? It seems totally unrelated

**Review by LysandreJik — APPROVED** [review]
LGTM

**Review by mfuntowicz — APPROVED** [review]

**Pull request merged**
