### PR TITLE
Fix doc examples: unexpected keyword argument

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Fix `unexpected keyword argument` in doc examples (in PT model files)

## Who can review?

@sgugger

### CODE REVIEW

**Comment by ydshieh** [comment]
Not sure why ProphetNetTokenizer returns `token_type_ids` by default while `ProphetNetEncoder` can't accept it.

```
            >>> tokenizer = ProphetNetTokenizer.from_pretrained('microsoft/prophetnet-large-uncased')
            >>> model = ProphetNetEncoder.from_pretrained('patrickvonplaten/prophetnet-large-uncased-standalone')
            >>> inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
            >>> del inputs["token_type_ids"]  # `ProphetNetEncoder` doesn't use `token_type_ids`
```

**Comment by sgugger** [comment]
That should be fixed in the tokenizer, not the doc example.

**Comment by ydshieh** [comment]
> That should be fixed in the tokenizer, not the doc example.

OK, I will revert it.

**Comment by ydshieh** [comment]
> > That should be fixed in the tokenizer, not the doc example.
> 
> OK, I will revert it.

@sgugger 
Can I change it to 

```
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt", return_token_type_ids=False)
```

for now in this PR, and open an issue for `ProphetNetTokenizer`.

**Comment by sgugger** [comment]
I'm afraid we will forget to re-change the documentation after the fix is done, so it should just stay as is until the tokenizer is fixed.

**Comment by patrickvonplaten** [comment]
Thanks a lot @ydshieh! 

@sgugger - feel free to merge if it's good to go from your side.

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
