### PR TITLE
Change logging level from warning to info for `max_steps` overriding `num_train_epochs`

### PR DESCRIPTION
**Pull request by qgallouedec**
# What does this PR do?

Passing `max_step` is a supported feature, and therefore should not raise a warning. I suggest lowering the level to info.

Alternatively, we could have an additional parameter like `ignore_max_step_warning` but this seems overengineered.

Considering that the use of `max_steps` is already documented:

https://github.com/huggingface/transformers/blob/ce1d328e3b73cf6d1d993fc0d487b7dc8a14d7ee/src/transformers/training_args.py#L307

lowering the level to info seems to be the best solution.

Technically, we can ignore this warnings with 

```python
TrainingArguments(
    ...,
    max_steps=100,
    num_train_epochs=-1
)
```

But it's not intuitive at all IMO.

---

As for warnings, I'd say that a good practice is that they should always be removable by the user:

- either by modifying their code, in the event of a feature being misused, deprecated, etc. E.g example:
    https://github.com/huggingface/transformers/blob/ce1d328e3b73cf6d1d993fc0d487b7dc8a14d7ee/src/transformers/models/speech_to_text/feature_extraction_speech_to_text.py#L235-L238

- or by acknowledging, in the case of very important information upgraded to warning; we add a parameter for acknowledging. E.g:
example: `allow_missing_key` in `load_pytorch_checkpoint_in_tf2_model`

Related: https://github.com/huggingface/trl/pull/2350

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@muellerzr and @SunMarc

### CODE REVIEW

**Review by SunMarc — APPROVED** [review]
LGTM ! cc @muellerzr for a second look

**Review by muellerzr — APPROVED** [review]
Agree with Marc, this change seems fine. cc @LysandreJik for final :)

**Review by LysandreJik — APPROVED** [review]
Sounds good to me, thanks all!

**Comment by LysandreJik** [comment]
Unrelated errors, merging

**Pull request merged**
