### PR TITLE
[Flax] remove jax.ops.index

### PR DESCRIPTION
**Pull request by patil-suraj**
# What does this PR do?

Remove `jax.ops.index` as this method is removed in latest jax release `v0.3.2`.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
There seem to be some failing tests still :-)

**Comment by patil-suraj** [comment]
The failing tests not related to this PR.

**Review by patrickvonplaten — APPROVED** [review]

**Comment by patil-suraj** [comment]
> Hi, I am not very into the detail here, but curious about that if this implies from this version, `transformers` will only work with the new version of `jax`?

No, the `.at` syntax is also supported in older jax versions.

**Comment by patrickvonplaten** [comment]
Feel free to merge if you want @patil-suraj

**Pull request merged**
