### PR TITLE
Train T5 in Tensoflow 2 Community Notebook

### PR DESCRIPTION
**Pull request by HarrisDePerceptron**
# What does this PR do?
This adds a link to **Training T5 in Tensoflow 2 Community Notebook** under the notebooks/Readme.md community notebook section.  

This notebook demonstrates how to train T5 for any task using Tensorflow 2. Trains a Question & Answer task implemented in Tensorflow 2 using SQUAD

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dimiss the other checks if that's the case). **Yes**
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests), 
      Pull Request section? **Yes**
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to the it if that's the case. [Forum Link](https://discuss.huggingface.co/t/how-to-train-t5-with-tensorflow/641)
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation). **Not Applicable**
- [ ] Did you write any new necessary tests?  **Not Applicable**

## Who can review?
@patrickvonplaten @jplu

### CODE REVIEW

**Comment by jplu** [comment]
Hello!

Thanks a lot for your awesome notebook! Just two tiny updates, can you clean your list of imports and use `datasets` instead of `tfds`?

**Comment by HarrisDePerceptron** [comment]
@jplu  much appreciated. i will clean up the imports. by datasets do you mean an alias for tensorflow datasets instead of tfds?

**Comment by jplu** [comment]
No, I mean using https://github.com/huggingface/datasets instead.

**Comment by HarrisDePerceptron** [comment]
@jplu  i have done the necessary changes. I have also switched to  [datasets](https://github.com/huggingface/datasets) as requested.

**Comment by jplu** [comment]
Awesome!! Thanks a lot for your notebook!!

**Comment by patrickvonplaten** [comment]
Thanks a lot @HarrisDePerceptron the community has been asking about such a notebook for a long time :-)

**Comment by HarrisDePerceptron** [comment]
Thanks @patrickvonplaten  !! it was long over due :)

**Pull request merged**
