### PR TITLE
DataParallel fixes

### PR DESCRIPTION
**Pull request by stas00**
1. switched to a more precise check as suggested by @thomwolf

```
-        if self.args.n_gpu > 1:
+        if isinstance(model, nn.DataParallel):
```
  discussion: https://github.com/huggingface/transformers/issues/5693#issuecomment-657937349

2. fix tests - require the same fixup under DataParallel as the training module fix merged earlier today:
https://github.com/huggingface/transformers/pull/5685
discussion: https://github.com/huggingface/transformers/issues/5693#issuecomment-657938856

### CODE REVIEW

**Comment by julien-c** [comment]
Way better fix, LGTM 

Did the multigpu test pass?

**Review by JetRunner — APPROVED** [review]

**Comment by stas00** [comment]
> Way better fix, LGTM

Well, I followed @sgugger and @thomwolf's breadcrumbs, so that was easy.

> Did the multigpu test pass?

Yes. And I retested the glue_run.py on multi-gpu machine.

**Comment by stas00** [comment]
Pushed another fix for https://github.com/huggingface/transformers/issues/5693#issuecomment-659564678

**Review by sshleifer — APPROVED** [review]

**Review by sgugger — APPROVED** [review]
Thanks for the nicer fix!

**Pull request merged**
