### PR TITLE
[WIP] Add support for CamembertForTokenClassification

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

this PR adds a `CamembertForTokenClassification` implementation, so that fine-tuning of NER models is possible.

Tasks:

* [x] Implement `CamembertForTokenClassification`
* [x] Add `CamembertForTokenClassification` to module import list
* [x] Add support for CamemBERT model in `run_ner.py` example

### CODE REVIEW

**Comment by julien-c** [comment]
This looks good to me @stefan-it 👌 

We'll also need to do the TF models but that can be in a different PR.

cc @LysandreJik @thomwolf

**Review by julien-c — APPROVED** [review]

**Comment by stefan-it** [comment]
I tried to replicate the results for PoS tagging on ParTUT dataset (using the tagged 2.2 version from [here](https://github.com/UniversalDependencies/UD_French-ParTUT)). I could replicate the results mentioned in the CamemBERT paper for the multilingual (cased) model (`run_ner` outputs F1-score, so locally I added the `accuracy_score` metric from the `seqeval` module ;) )

However, the CamemBERT model is ~10% behind it. I'm trying to figure out why, loss is really high compared to mBERT...

**Review by LysandreJik — APPROVED** [review]
Good job on the implementation @stefan-it!

**Review by thomwolf — APPROVED** [review]

**Comment by thomwolf** [comment]
LGTM thanks!

**Pull request merged**
