### PR TITLE
Make sliding window size inclusive in eager attention

### LINKED ISSUE #29176: Sliding window inconsistency between PyTorch and Flax
### System Info

transformers main (ae49b218c), Python 3.10.8

### Who can help?

@ArthurZucker, @sanchit-gandhi

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The attention `sliding_window` has different interpretation for PyTorch and Flax. Here's are matching examples:

**PyTorch**

```python
from transformers import MistralModel
import torch

model = MistralModel.from_pretrained("hf-internal-testing/tiny-random-MistralModel", sliding_window=2)

inputs = {
  "input_ids": torch.tensor([[10, 20, 30, 40, 50, 60, 70, 80, 0, 0]]),
  "attention_mask": torch.tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
}

outputs = model(**inputs)

print(outputs.last_hidden_state[:, 1:4, 1:4])
```

**Flax**

```python
from transformers import FlaxMistralModel
import jax.numpy as jnp

model = FlaxMistralModel.from_pretrained("hf-internal-testing/tiny-random-MistralModel", sliding_window=2, from_pt=True)

inputs = {
  "input_ids": jnp.array([[10, 20, 30, 40, 50, 60, 70, 80, 0, 0]]),
  "attention_mask": jnp.array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
}

outputs = model(**inputs)

print(outputs.last_hidden_state[:, 1:4, 1:4])
```

Both snippets return different results, however, if we use `sliding_window=3` in the PyTorch version, the results are the same.

In the Flax implementation, `sliding_window=2` means that a position will attend to self, and two previous position inclusive (which intuitively seems correct to me). It looks like in the PyTorch version it is not inclusive. Which behaviour is expected?

### Expected behavior

The `sliding_window` meaning to be consistent.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Closes #29176. See the issue for details.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Hi @jonatanklosko, thanks for opening this PR! 

It looks like this breaks some tests, specifically: 

```
FAILED tests/test_modeling_utils.py::AttentionMaskTester::test_2d_to_4d_causal_sliding - assert 3 == 6
FAILED tests/test_modeling_utils.py::AttentionMaskTester::test_causal_mask_sliding - assert 9 == 12
```

which will need to be addressed before merge

**Comment by jonatanklosko** [comment]
@amyeroberts fixed!

**Comment by amyeroberts** [comment]
@jonatanklosko Great! Last things to do before merging: 

* Rebase on main. We recently merged in a patch which should resolve the currently failing test
* Run the slow model tests for some of the main models this might affect, namely Mistral, Mixtral, LLama, Whisper, Bart, Falcon, Idefics, stablelm, starcoder2 `RUN_SLOW=1 pytest tests/models/mistral tests/models/mixtral tests/models/llama tests/models/whisper tests/models/bart tests/models/falcon tests/models/idefics tests/models/starcoder2 tests/models/stablelm tests/models/qwen2 tests/models/gpt_bigcode`

**Comment by amyeroberts** [comment]
@jonatanklosko I can run them on this branch

**Review by amyeroberts — APPROVED** [review]
Thanks for working on this!

**Comment by jonatanklosko** [comment]
@amyeroberts fantastic, thank you!

**Pull request merged**
