### PR TITLE
CI: skip failing TF hubert test

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

### CODE REVIEW

**Comment by gante** [comment]
cc @amyeroberts

**Review by ydshieh — APPROVED** [review]
Thanks - approved in case you want to merge quickly.

**Review by sgugger — APPROVED** [review]
Thanks!

**Comment by gante** [comment]
@susnato see #21606 (I skipped the wrong one here)

**Comment by susnato** [comment]
Hi @gante thanks for the fix but now there seems to be a new issue popping up regarding that same model, 
```
tests/models/hubert/test_modeling_tf_hubert.py::TFHubertRobustModelTest::test_keras_fit
```
This test is failing in the same PR I mentioned above. I did rebase before pushing.

**Pull request merged**
