### PR TITLE
[T5] Fix Cross Attention position bias

### PR DESCRIPTION
**Pull request by ZhuBaohe**
This PR fixes the Cross Attention position bias assignment in Class T5Stack.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hi @ZhuBaohe, 

Thansk for your PR! Can you explain a bit more in-detail what the fix is doing here? :-)

**Comment by ZhuBaohe** [comment]
@patrickvonplaten 

I fixes a bug that the variable **encoder_decoder_position_bias** was assigned by cross-attention weights, not by cross-attention position bias.

See Line 745 of the file modeling_t5.py as follow:
```
# layer_outputs = hidden-states,                   -> 0
                  key-value-states,                -> 1
                  (self-attention weights),        -> 2                               
                  (self-attention position bias),  -> 3  
                  (cross-attention weights),       -> 4 
                  (cross-attention position bias)  -> 5 
```
**encoder_decoder_position_bias** should be assigned by layer_outputs[5]  instead of layer_outputs[4] .

**Comment by patrickvonplaten** [comment]
Great, I agree with you. Previously the attention weights of the cross attention layer were taken instead of the bias. 

@LysandreJik @thomwolf I am quite surprised that we did not see an error earlier. I checked the slow tests and the summarization / translation results are equivalent as before. 

So good to merge for me!

**Review by LysandreJik — APPROVED** [review]
Indeed, thanks @ZhuBaohe

**Comment by thomwolf** [comment]
Surprising indeed @patrickvonplaten , I did fix a similar bug when implementing T5.

We should switch to NamedTuples one day 😄

**Pull request merged**
