### PR TITLE
Llama tokenizer: remove space in template comment

### PR DESCRIPTION
**Pull request by pcuenca**
I think the space between the eos and bos tokens is not present in the actual template output. I'm using this documentation as a reference for everyone asking about prompting, so would like to clarify whether there's a space or not :)

# What does this PR do?

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ Rocketknight1, @ArthurZucker

### CODE REVIEW

**Review by Rocketknight1 — APPROVED** [review]
This is correct, the space is not present!

**Review by ArthurZucker — COMMENTED** [review]
Thanks! Let's make sure the actual template is this and we could link to meta's original code as well!

**Review by ArthurZucker — APPROVED** [review]

**Comment by pcuenca** [comment]
Our template gives identical results as llama 2's original tokenization, I just double-checked by comparing the tokens using a three-turn conversation. The code has always been correct, there's no space between the `eos`/`bos` tokens.

Not sure what you mean by _linking to meta's original code_, should we include a link in the docs? This would be the place where the user/assistant turns are parsed: 
https://github.com/facebookresearch/llama/blob/556949fdfb72da27c2f4a40b7f0e4cf0b8153a28/llama/generation.py#L342

**Comment by ArthurZucker** [comment]
Yep if you feel like it! This way they can compare with their own eyes the source of truth! (even if it's code)

**Review by ArthurZucker — APPROVED** [review]
Thanks a lot ! 🤗

**Comment by pcuenca** [comment]
Thanks to you both for your quick reviews! Feel free to merge when you see fit, I don't have write permissions in this repo :)

**Comment by Rocketknight1** [comment]
Done!

**Pull request merged**
