### PR TITLE
WIP Create test_speech_recognition_deepspeed.py

### PR DESCRIPTION
**Pull request by flozi00**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by flozi00** [comment]
regarding to https://github.com/huggingface/transformers/issues/15330#issuecomment-1021930267

**Comment by flozi00** [comment]
locally the tests are just getting skipped, any tipps ?

**Comment by patrickvonplaten** [comment]
Are the tests passing for you locally @flozi00 ?

**Comment by flozi00** [comment]
The tests are skipping locally and I don't know why exactly

**Comment by stas00** [comment]
You first need to copy the config files:
```
cp examples/research_projects/wav2vec2/ds_config_wav2vec2_zero* examples/pytorch/speech-recognition
```
and make them part of the PR

And then the run command is:

```
RUN_SLOW=1 pytest  examples/pytorch/speech-recognition/test_speech_recognition_deepspeed.py -sv
```

you were probably missing `RUN_SLOW=1`

**Comment by flozi00** [comment]
RUN_SLOW=1 did it

i'm sorry but for health reasons i can't work on it in depth because i'm in the hospital with only a tablet

**Comment by patrickvonplaten** [comment]
Will try to allocate time for this (early next week)

**Pull request closed without merging**
