### PR TITLE
fix some errors for distributed lm_finetuning

### PR DESCRIPTION
**Pull request by yzy5630**
1. makedirs 
2. save models

### CODE REVIEW

**Comment by thomwolf** [comment]
Hi, do you want to update these examples to the new `pytorch-transformers` API at the same time?
Models now return `tuple` so we should take the first element of the model output as the loss.

**Comment by yzy5630** [comment]
ok， I  have a try, I‘m stilll use the old API.

**Comment by yzy5630** [comment]
Hi,  I have updated the opt to the new API , please check.

**Comment by thomwolf** [comment]
Thanks @yzy5630!

**Pull request merged**
