### PR TITLE
Add missing PLBart entry in README

### PR DESCRIPTION
**Pull request by gchhablani**
# What does this PR do?
This PR fixes the missing entry for PLBart (See #13269) in the index.

@sgugger @patil-suraj @patrickvonplaten @LysandreJik

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
You need to add it in the main README of the repo, then run make fix-copies to propagate it to the localized READMEs and this index.

**Review by sgugger — COMMENTED** [review]
Needs to be the master doc for now :-)

**Comment by ydshieh** [comment]
> Needs to be the master doc for now :-)

(When @sgugger is not busy)
Could you explain a bit why `master` is required here, and other links don't need it, please?

**Review by sgugger — APPROVED** [review]
Thanks for adding it!

**Pull request merged**
