### PR TITLE
GPT2ForQuestionAnswering

### PR DESCRIPTION
**Pull request by peter-sk**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker
@sgugger

### CODE REVIEW

**Comment by ArthurZucker** [comment]
GPT2 is an old model so it might still be checking for `model_parallel`, which in this case has to be added! LMK if this fixes the issues

**Comment by peter-sk** [comment]
@ArthurZucker ready for review!

**Comment by sgugger** [comment]
cc @younesbelkada since Arthur is on vacation.

**Review by younesbelkada — APPROVED** [review]
Awesome work , thanks for this!
From my understanding we need to keep `model_parallel` for code-legacy purposes otherwise some CI would fail (from what I have seen last week)

**Review by sgugger — APPROVED** [review]
Thanks for adding this!

**Pull request merged**
