### PR TITLE
fix the get_size_with_aspect_ratio in max_size situation

### PR DESCRIPTION
**Pull request by SangbumChoi**
# What does this PR do?

This fix the issue as the following example. AKA round issue.
This is important when the size should be divisible by specific value such as 32, 16.
@amyeroberts 

```
from transformers import DetrImageProcessor
from PIL import Image
import requests
import torch
import io
import numpy as np


def rgb_to_id(color):
    if isinstance(color, np.ndarray) and len(color.shape) == 3:
        if color.dtype == np.uint8:
            color = color.astype(np.int32)
        return color[:, :, 0] + 256 * color[:, :, 1] + 256 * 256 * color[:, :, 2]
    return int(color[0] + 256 * color[1] + 256 * 256 * color[2])
    
height, width = 653, 958
image = Image.new('RGB', (width, height), 'white')
image_processor = DetrImageProcessor.from_pretrained('facebook/detr-resnet-50')
image_processor.size = \
{
    "longest_edge": 640,
    "shortest_edge": 640
}
```

Before commit
```
# prepare inputs for the model
inputs = image_processor(images=image, return_tensors="pt")
print(inputs['pixel_values'].shape)
torch.Size([1, 3, 436, 639])
```

After commit
```
# prepare inputs for the model
inputs = image_processor(images=image, return_tensors="pt")
print(inputs['pixel_values'].shape)
torch.Size([1, 3, 436, 640])
```

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [X] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by SangbumChoi** [comment]
Additional script
```
height, width = 653, 958

for i in range(640,660):
    image = Image.new('RGB', (width, i), 'white')
    
    print(image.size)
    
    image_processor = DetrImageProcessor.from_pretrained('facebook/detr-resnet-50')
    image_processor.size = \
    {
        "longest_edge": 640,
        "shortest_edge": 640
    }
    
    # prepare inputs for the model
    inputs = image_processor(images=image, return_tensors="pt")
    print(inputs['pixel_values'].shape)
```

```
(958, 640)
torch.Size([1, 3, 428, 640])
(958, 641)
torch.Size([1, 3, 428, 640])
(958, 642)
torch.Size([1, 3, 429, 640])
(958, 643)
torch.Size([1, 3, 430, 640])
(958, 644)
torch.Size([1, 3, 430, 640])
(958, 645)
torch.Size([1, 3, 431, 640])
(958, 646)
torch.Size([1, 3, 432, 640])
(958, 647)
torch.Size([1, 3, 432, 640])
(958, 648)
torch.Size([1, 3, 433, 640])
(958, 649)
torch.Size([1, 3, 434, 640])
(958, 650)
torch.Size([1, 3, 434, 640])
(958, 651)
torch.Size([1, 3, 435, 640])
(958, 652)
torch.Size([1, 3, 436, 640])
(958, 653)
torch.Size([1, 3, 436, 640])
(958, 654)
torch.Size([1, 3, 437, 640])
(958, 655)
torch.Size([1, 3, 438, 640])
(958, 656)
torch.Size([1, 3, 438, 640])
(958, 657)
torch.Size([1, 3, 439, 640])
(958, 658)
torch.Size([1, 3, 440, 640])
(958, 659)
torch.Size([1, 3, 440, 640])
```

**Comment by SangbumChoi** [comment]
https://github.com/huggingface/transformers/blob/fce78fd0e917312da36cea4d352896a8f6ec9cdc/src/transformers/models/yolos/image_processing_yolos.py#L104

We can consider merging both all-in-one

**Review by amyeroberts — COMMENTED** [review]
Thanks for fixing! 

Could you add a test, checking both the upper and lower bounds, which fail on main and pass here? 

cc @qubvel

**Comment by SangbumChoi** [comment]
I will update the yolos and the test function and ping again.

**Comment by SangbumChoi** [comment]
@qubvel @amyeroberts I added the screenshot which fails at the main branch and success in here.

For the record, I tried to make yolos consistent to all the other function. However, it turns out it needs to remove `#Copied from line` which I would like to maintain. As a result I just changed it with appropriate format.

I just added test on the detr but if it seems good I could add it to all the related models.

Screenshot 2024-05-23 at 10 18 59 PM

**Review by amyeroberts — COMMENTED** [review]
Thanks for working on this! Overall looks good to me. It would be good to add some tests to make sure the behaviour is as expected for specific cases eg. when max_size is set or not; height < width; width < height; height == width; height == size etc.

**Comment by SangbumChoi** [comment]
I have added the 3 more cases which is total 5 cases. Note that max_size should be always set in the situation of get_size_with_aspect_ratio! Again I just added test on the detr but if it seems good I could add it to all the related models :)

**Comment by SangbumChoi** [comment]
@amyeroberts Hi amy, since recent merge has deprecated DETA. I also removed in here.

**Comment by SangbumChoi** [comment]
@amyeroberts Could you rerun the CI?

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
