### PR TITLE
LayoutXLMProcessor: Enforce using "return_overflowing_tokens" with "return_offsets_mapping"

### LINKED ISSUE #18726: KeyError 'overflow_to_sample_mapping' when using LayoutXLM with regular Tokenizer + return_overflowing_tokens
### System Info

(Running from Colab)
- `transformers` version: 4.21.1
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Tensorflow version (GPU?): 2.8.2 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes, but not relevant here
- Using distributed or parallel set-up in script?: No

### Who can help?

- Introduced when adding [LayoutLMv3](https://github.com/huggingface/transformers/pull/17060) @NielsRogge , Tokenizer related @SaulLu

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

View this short notebook on Colab: https://colab.research.google.com/drive/1ETpz8UP42r7HjRg4VUkC7L8ou10qY3bQ?usp=sharing

### Expected behavior

Expected:
Processor extracts features from and tokenizes the input successfully.

Output:
```
---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

[<ipython-input-6-2f428d9c1568>](https://localhost:8080/#) in <module>
----> 1 encoded = processor(image, words, boxes=boxes, word_labels=word_labels, **processor_kwargs)

[/usr/local/lib/python3.7/dist-packages/transformers/models/layoutxlm/processing_layoutxlm.py](https://localhost:8080/#) in __call__(self, images, text, text_pair, boxes, word_labels, add_special_tokens, padding, truncation, max_length, stride, pad_to_multiple_of, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose, return_tensors, **kwargs)
    124         images = features.pop("pixel_values")
    125         if return_overflowing_tokens is True:
--> 126             images = self.get_overflowing_images(images, encoded_inputs["overflow_to_sample_mapping"])
    127         encoded_inputs["image"] = images
    128 

[/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py](https://localhost:8080/#) in __getitem__(self, item)
    234         """
    235         if isinstance(item, str):
--> 236             return self.data[item]
    237         elif self._encodings is not None:
    238             return self._encodings[item]

KeyError: 'overflow_to_sample_mapping'
```

### PR DESCRIPTION
**Pull request by anthony2261**
# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/18726

Code to reproduce the error: https://colab.research.google.com/drive/1ETpz8UP42r7HjRg4VUkC7L8ou10qY3bQ?usp=sharing

Specific combination that caused the error: `LayoutXLMProcessor` with `use_fast=False`, `return_overflowing_tokens=True` and `return_offsets_mapping=False`

## Who can review?

@NielsRogge

### CODE REVIEW

**Comment by NielsRogge** [comment]
Thanks, although it doesn't include the same changes as #17092, could you add those?

**Comment by anthony2261** [comment]
> Thanks, although it doesn't include the same changes as #17092, could you add those?

The additional changes in the other PR were already present, I added the missing ones, see the pictures below
This PR:
image

The other PR:
image

**Comment by NielsRogge** [comment]
Oh thanks, just realized I added that myself when adding LayoutLMv3. Thanks! I'll add another reviewer before merging

**Comment by anthony2261** [comment]
Btw, one issue I have with this is that if we're using the processor with `use_fast=False`, we won't be allowed to process data with `return_overflowing_tokens=True`, because this will force us to set `return_offsets_mapping=True`, and doing that will raise this error:

```
NotImplementedError: return_offset_mapping is not available when using Python tokenizers.
To use this feature, change your tokenizer to one deriving from transformers.PreTrainedTokenizerFast.
More information on available tokenizers at https://github.com/huggingface/transformers/pull/2674
````

I was able to get 1-to-1 token mappings with the non-fast tokenizer but in a very hacky way. If I find a better way, I'll suggest doing that to support `return_overflowing_tokens` with regular tokenizers.

**Review by LysandreJik — APPROVED** [review]
Yes, this looks good to me! Thank you, @anthony2261!

**Pull request merged**
