### PR TITLE
Add `power` argument for TF PolynomialDecay

### PR DESCRIPTION
**Pull request by astariul**

### CODE REVIEW

**Comment by jplu** [comment]
Thanks for the PR!!

Can you just go a bit forward and create a parameter in `training_args_tf.py` for this?

**Comment by Colanim** [comment]
How can I see where my format is wrong ?

**Comment by jplu** [comment]
Can you run in that order:
```
isort --recursive examples templates tests src utils
black --line-length 119 --target-version py35 examples templates tests src utils
```

And then push.

**Review by LysandreJik — APPROVED** [review]
LGTM!

**Comment by jplu** [comment]
Hello @Colanim!

Can you rebase on master, and I will merge once done!

**Comment by jplu** [comment]
Nice! Can you run a `make style` in order to fix the code quality test.

**Pull request merged**
