### PR TITLE
Add missing module __spec__

### LINKED ISSUE #12904: transformers.__spec__ returning None. Causing downstream import errors
## Environment info

- `transformers` version: Tried on 4.6.1(current default kaggle version)/4.8.1/4.8.2 and 4.9.1
- Platform: Colab/Kaggle/ My Local Runtime
- Python version: 3.7.11

## Information

This is causing downstream import errors, like right now I am not able to import [`lightning-flash`](https://github.com/PyTorchLightning/lightning-flash) properly as it uses `__spec__` in order to find the availability of `transformers`.
```
ValueError                                Traceback (most recent call last)
<ipython-input-3-76e523923a79> in <module>
      5 print(transformers.__version__)
      6 print(transformers.__spec__)
----> 7 from flash import Trainer
      8 #from flash.core.data.utils import download_data
      9 #from flash.text import SummarizationData, SummarizationTask

/opt/conda/lib/python3.7/site-packages/flash/__init__.py in <module>
     16 
     17 from flash.__about__ import *  # noqa: F401 F403
---> 18 from flash.core.utilities.imports import _TORCH_AVAILABLE
     19 
     20 if _TORCH_AVAILABLE:

/opt/conda/lib/python3.7/site-packages/flash/core/utilities/imports.py in <module>
     75 _PYTORCHVIDEO_AVAILABLE = _module_available("pytorchvideo")
     76 _MATPLOTLIB_AVAILABLE = _module_available("matplotlib")
---> 77 _TRANSFORMERS_AVAILABLE = _module_available("transformers")
     78 _PYSTICHE_AVAILABLE = _module_available("pystiche")
     79 _FIFTYONE_AVAILABLE = _module_available("fiftyone")

/opt/conda/lib/python3.7/site-packages/flash/core/utilities/imports.py in _module_available(module_path)
     36     """
     37     try:
---> 38         return find_spec(module_path) is not None
     39     except AttributeError:
     40         # Python 3.6

/opt/conda/lib/python3.7/importlib/util.py in find_spec(name, package)
    112         else:
    113             if spec is None:
--> 114                 raise ValueError('{}.__spec__ is None'.format(name))
    115             return spec
    116 

ValueError: transformers.__spec__ is None
```
## To reproduce

```

import transformers
print(transformers.__version__)
print(transformers.__spec__)

4.9.1
None

```

## Expected behavior

Properly defined `__spec__`

### PR DESCRIPTION
**Pull request by laurahanu**
# What does this PR do?

This PR adds a missing `__spec__` object when importing the library that would be `None` otherwise.
Fixes #12904

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks for your PR!

As you can see, this makes all the tests fail because you changed the init of `_LazyModule` without adapting all the places it's used (all the intermediates init of each model). I'm not sure whether those intermediate inits need to pass along the spec attribute or not, if they do you should add it in each one of them (don't forget the model template as well), and if they don't, you should make that argument optional.

**Comment by laurahanu** [comment]
@sgugger Thanks for looking at it! Changed the `module_spec` arg to be optional as I don't see why the other intermediate inits would need it.

**Comment by sgugger** [comment]
Great! One last thing: could you run `make style` on your branch to solve the code quality issue?

**Comment by sgugger** [comment]
Last thing caught by the CI new that the style is correct: your new test file will never be run by the CI. Since it's linked to `_LazyModule` defined in file_utils, could you move it to `test_file_utils`? Thanks a lot.

**Comment by aleSuglia** [comment]
Is this one ready to be merged and published?

**Pull request merged**
