### PR TITLE
hot fix `self.position_embeddings->self.position_embedding`

### LINKED ISSUE #33929: PaliGemma (and probably SigLIP) inference broken in latest transformers version
> This seems like a breaking change. When I run this model with `transformers==4.44.2`, things work fine. However, when running with `transformers==4.25.1`, it fails with this error:
> 
> ```
> 
> ...
> 
>     num_positions = self.position_embeddings.shape[1]
> 
>   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1687, in __getattr__
> 
>     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
> 
> AttributeError: 'SiglipVisionEmbeddings' object has no attribute 'position_embeddings'. Did you mean: 'position_embedding'?
> 
> ``` 

 _Originally posted by @mranzinger in [c6d2848](https://github.com/huggingface/transformers/commit/c6d2848a23aba42404784ba52e421ae7b8c68eda#r147546116)_

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Fixes #33929

### CODE REVIEW

**Comment by mranzinger** [comment]
I think this is still broken. `self.position_embedding` is of type `nn.Embedding`, which means it doesn't have a `.shape` variable.

I think you want to bring back
```
position_embeddings = self.position_embedding.weight.unsqueeze(0)
```

**Comment by ArthurZucker** [comment]
🫠 yep

**Comment by ArthurZucker** [comment]
Or just `  num_positions = self.position_embedding.weight.shape[1]`

**Comment by ArthurZucker** [comment]
Opening a new PR

**Pull request merged**
