### PR TITLE
[NarrowBERT] Add NarrowBERT to HF

### PR DESCRIPTION
**Pull request by lihaoxin2020**
# What does this PR do?

Add implementation of NarrowBERT. 

- original repo: https://github.com/lihaoxin2020/narrowbert
- paper: https://arxiv.org/abs/2301.04761v2

## Who can review?

- text models: @ArthurZucker and @younesbelkada

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Hey! Thanks for wanting to contribute I would recommend you to put the model on the hub following [this tutorial](https://huggingface.co/docs/transformers/custom_models) to make it easily available 🤗

**Comment by lihaoxin2020** [comment]
Hi Arthur. With the last commit i think I've passed all tests i can see. please let me know anything i missed. Thanks!

**Comment by lihaoxin2020** [comment]
Hi. I've uploaded the [model](https://huggingface.co/lihaoxin2020/narrowbert-sparse_attn-uncased) (i'll update model readme soon) and clear all tests i can see. It's been a while since I poked last time. Could you check in and make sure everything looks right? 
Let me know anything I should improve. Thanks! @ArthurZucker @younesbelkada

**Comment by ArthurZucker** [comment]
Hey! If the model is on the hub then we should close this PR no? 🤗

**Comment by lihaoxin2020** [comment]
Sorry I'm confused. I did add the model weights to be hub, but I'm also adding this model implementation to the transformers library. I suppose you need to review the RP and approve so that it can be merged? 

I've marked this PR as ready for review so you should be able to review and comment/approve. 
Let me know if there's anything I misunderstood. I'm new on open source project.

**Pull request closed without merging**
