### PR TITLE
Add Italian translation for `add_new_model.mdx`

### PR DESCRIPTION
**Pull request by Steboss89**
# What does this PR do?

Italian translation of `add_new_model.mdx` 
Related to issue: #17459 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. 
https://github.com/huggingface/transformers/issues/17459
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@mfumanelli  @nickprock

### CODE REVIEW

**Comment by nickprock** [comment]
Hi @Steboss89 , is a very long document well done! At the moment I read until the line 339.
It's ok but:
row 75: esssere --> essere
row 91: Similmente al modello --> Analogamente al modello

And the phrase "I files del modello devono esssere il più self-contained possibile cosicché quando leggi il codice di uno specifico modello, idealmente, 
avresti da vedere solo il corrispettivo file `modeling_....py`." is unclear.

**Comment by omarespejel** [comment]
Hey @Steboss89! Thank you for your translation! And thank you, @nickprock for your kind review 🙏. 

@Steboss89, additionally to what @nickprock mentioned, to pass the quality tests, make sure you run `make quality` on the main page of your directory. [Here are the instructions](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md).

**Comment by sgugger** [comment]
It's actually `make style` ;-)

**Comment by nickprock** [comment]
Hi @Steboss89.

row 426: arhcitettura --> architettura 
row 446: che `init()` di tutte le componenti funziona correttamente. --> che `init()` di tutte le componenti funzioni correttamente.
row 454: Di solito é abbastanza fare una copia di uno script gia esistente e adattarlo al vostro caso. --> Di solito basta fare una copia di uno script gia esistente e adattarlo al vostro caso.
row 628: dobbiamo assicurarci che il vostro lavoro sia correttamente testato --> bisogna assicurarsi che il vostro lavoro sia correttamente testato
row 648: `BrandNewBertModelTester`/`BrandNewBertModelTest`
row 714: ttuto --> tutto
row 726: A volte capita che mancano delle informazioni --> A volte capita che manchino delle informazioni

**Comment by Steboss89** [comment]
Sorry for not coming back with corrections and tests earlier
I'll get through the quality checks as well as the corrections suggested 
Thanks a million @nickprock @sgugger and @omarespejel

**Comment by Steboss89** [comment]
Hey @nickprock  sorry again for such a long delay. Here is the corrected version of the documentation.

@sgugger and @omarespejel  I can see from the quality check that these files: 
```
['src/transformers/benchmark/benchmark_utils.py', 'src/transformers/testing_utils.py', 'src/transformers/trainer_utils.py', 'src/transformers/modelcard.py', 'src/transformers/utils/notebook.py', 'src/transformers/models/auto/auto_factory.py', 'src/transformers/models/transfo_xl/modeling_transfo_xl.py', 'src/transformers/models/xlm/tokenization_xlm.py', 'src/transformers/models/tapex/tokenization_tapex.py', 'src/transformers/models/perceiver/modeling_perceiver.py', 'src/transformers/models/flaubert/tokenization_flaubert.py', 'src/transformers/models/fsmt/tokenization_fsmt.py', 'src/transformers/generation_utils.py', 'src/transformers/generation_flax_utils.py', 'src/transformers/generation_tf_utils.py', 'src/transformers/trainer_pt_utils.py']
```
needs restyle. How can I fix this? Thanks

**Comment by Steboss89** [comment]
@sgugger  Thanks very much 
I'll rebase my branch with current main :)

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
