### PR TITLE
add importlib_metadata as dependency as it is required for py<3.8

### PR DESCRIPTION
**Pull request by cdeepali**
# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/11399

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by LysandreJik** [comment]
Shouldn't this only be installed for python versions inferior to 3.8?

**Comment by cdeepali** [comment]
@LysandreJik, thanks for reviewing my PR.

I think at the moment, we cannot use selectors with `noarch` python packages. Please see warning at - https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=preprocess-selectors#architecture-independent-packages.

**Comment by LysandreJik** [comment]
I see! Let's go with it then. Thanks for the fix!

**Review by LysandreJik — APPROVED** [review]

**Comment by LysandreJik** [comment]
Could you open a PR against the `master` branch so that we can also apply that fix for future conda releases?

**Comment by LysandreJik** [comment]
Also, are you savvy about `conda`? We're having an issue with our recent version releases: [failing suite](https://github.com/huggingface/transformers/runs/2334821335?check_suite_focus=true), do you have an idea of what might be the conflict happening here?

**Comment by cdeepali** [comment]
Thanks @LysandreJik for merging this one. Yes I will open a PR against master too.

**Comment by cdeepali** [comment]
Added PR https://github.com/huggingface/transformers/pull/11591 for master branch.

**Comment by cdeepali** [comment]
> Also, are you savvy about `conda`? We're having an issue with our recent version releases: [failing suite](https://github.com/huggingface/transformers/runs/2334821335?check_suite_focus=true), do you have an idea of what might be the conflict happening here?

I think this is failing because `python` version in the build env is `3.9` and we do not have `tokenizers` for `py39` on `HuggingFace` channel. 
```
$ conda search tokenizers=0.10.2 -c HuggingFace
Loading channels: done
# Name                       Version           Build  Channel
tokenizers                    0.10.2          py35_0  HuggingFace
tokenizers                    0.10.2          py36_0  HuggingFace
tokenizers                    0.10.2          py37_0  HuggingFace
tokenizers                    0.10.2          py38_0  HuggingFace
```
Looks like anaconda upload failed for tokenizers 3.9 - https://github.com/huggingface/tokenizers/runs/2272898351#step:8:17

I was able to build transformers locally with py38.

**Comment by LysandreJik** [comment]
Ah, I thought we were already building on 3.8, that's my bad. Thanks for your help!

**Pull request merged**
