### PR TITLE
Translation italian: multilingual.mdx

### PR DESCRIPTION
**Pull request by nickprock**
# What does this PR do?

* added multilingual.mdx
* updated _toctree.yml

See issue: [#17459](https://github.com/huggingface/transformers/issues/17459)

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [X] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [X] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@omarespejel @sgugger

### CODE REVIEW

**Comment by nickprock** [comment]
Thanks @mfumanelli I will try ti fix it tomorrow.

**Comment by nickprock** [comment]
Hi @mfumanelli, how would you translate "Masked Language Modeling"? I would leave it in English, "Modello di linguaggio mascherato" doesn't sounds good for me.
Thanks

**Comment by mfumanelli** [comment]
Yes @nickprock, maybe you can write only the first time you mention it "Modello di linguaggio mascherato (Masked Language Model, in inglese)", and from then on call it by its English name. What do you think?

**Comment by nickprock** [comment]
I agree

**Comment by nickprock** [comment]
I fixed and I'm waiting for the review

**Comment by sgugger** [comment]
cc @omarespejel

**Review by sgugger — APPROVED** [review]
Same as #17600 again. Thanks a lot!

**Pull request merged**
