### PR TITLE
supporting different position embeddings

### PR DESCRIPTION
**Pull request by michalozeryflato**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by zhangjunyi111 — COMMENTED** [review]
Can you write some code comment? It is diffcult to understand

**Review by ArthurZucker — COMMENTED** [review]
Hey! Thanks for wanting to contribute! Unfortunately goes a bit against the philosophy of transformers! We try our best not to be a toolbox but facilitates others in building on top of transformers! 🤗 This kind of change will not be accepted 😢

**Comment by michalozeryflato** [comment]
@ArthurZucker @zhangjunyi111 I forked transformers for investigating different positional embeddings in a bioinformatics study.  I created the PR to highlight code changes to my colleagues. I did not intend to suggest merging my code changes into transformers.  I changed the PR to a draft mode. Let me know if I need to delete it.

**Comment by michalozeryflato** [comment]
Closing this PR - was created by mistake

**Pull request closed without merging**
