### PR TITLE
Tf qa pipelines test

### PR DESCRIPTION
**Pull request by mfuntowicz**

### CODE REVIEW

**Comment by LysandreJik** [comment]
@julien-c the TF_QA pipeline test currently fails with a segmentation error, and no way to debug it. We think it might be hardware related, hence the reduction in concurrency.

**Comment by julien-c** [comment]
I think you inadvertently re-added `run_all_tests_torch_and_tf` (which should not be here anymore)

**Comment by julien-c** [comment]
Maybe just mark the flaky test as `@slow`, and we'll see if it works more reliably on our own CI?

**Comment by LysandreJik** [comment]
oops, indeed, my bad. Alright, that works as well.

**Pull request closed without merging**
