### PR TITLE
Add minor doc-string change to include hp_name param in hyperparameter_search

### PR DESCRIPTION
**Pull request by constantin-huetterer**
This is a very minor change. It seems like one of the parameters of the hyperparameter_search method hasn't been documented yet. :slightly_smiling_face:

### CODE REVIEW

**Comment by constantin-huetterer** [comment]
Just noticed, that the kwargs- argument is also not displayed correctly. Probably because of the missing typing-information:
image

**Comment by constantin-huetterer** [comment]
Better, but still parsing issues. Maybe because of the missing white-space. 
image

**Comment by constantin-huetterer** [comment]
Yes, that did the trick. Now it looks alright. 

image

**Review by LysandreJik — APPROVED** [review]
This looks good to me! Thank you, @constantin-huetterer!

**Pull request merged**
