### PR TITLE
Fix optuna ddp hp search

### LINKED ISSUE #27487: ERROR in run_hp_search_optuna when trying to use multi-GPU
### System Info

- transformers version: 4.28.1
- Platform: Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.9.16
- Huggingface_hub version: 0.14.1
- Safetensors version: not installed
- PyTorch version (GPU?): 1.13.1 (False)

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The problem appears when using `run_hp_search_optuna` method from transformers/integrations.py . This method is called when trying to perform an hyperparameter search with the `Trainer.hyperparameter_search` method:

```python
best_trial = trainer.hyperparameter_search(
     direction='maximize',
     backend='optuna',
     hp_space=optuna_hp_space,
     n_trials=10,
)
```

The error obtained is the next one:

`Traceback (most recent call last):
  File "/mnt/beegfs/sstoia/proyectos/LLM_finetuning_stratified_multiclass_optuna.py", line 266, in <module>
    best_trial = trainer.hyperparameter_search(
  File "/mnt/beegfs/sstoia/.conda/envs/env/lib/python3.9/site-packages/transformers/trainer.py", line 2592, in hyperparameter_search
    best_run = backend_dict[backend](self, n_trials, direction, **kwargs)
  File "/mnt/beegfs/sstoia/.conda/envs/env/lib/python3.9/site-packages/transformers/integrations.py", line 218, in run_hp_search_optuna
    args = pickle.loads(bytes(args_main_rank))
_pickle.UnpicklingError: pickle data was truncated`

### Expected behavior

It should work, as the same function without multi-GPU works fine. I guess the problem comes from a parallelization error, as both GPUs may write on the same file.

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR do ? 

Fixes https://github.com/huggingface/transformers/issues/27487
This PR fixes an issue with optuna hp search when using DDP. The issue was that we didn't parsed pass the correct item to `pickle.loads` when we perform boardcasting with torch. cc @sywangyi as you were the one who integrated it ! 
The following test is passing with ddp with this PR: `test_trainer.py::TrainerHyperParameterOptunaIntegrationTest:test_hyperparameter_search`

Otherwise, we were getting the following traceback: 

```
[rank1]: Traceback (most recent call last):
[rank1]:   File "test_local.py", line 83, in <module>
[rank1]:     trainer.hyperparameter_search(direction="minimize", hp_space=hp_space, hp_name=hp_name, n_trials=4)
[rank1]:   File "/home/marc/transformers/src/transformers/trainer.py", line 3420, in hyperparameter_search
[rank1]:     best_run = backend_obj.run(self, n_trials, direction, **kwargs)
[rank1]:   File "/home/marc/transformers/src/transformers/hyperparameter_search.py", line 72, in run
[rank1]:     return run_hp_search_optuna(trainer, n_trials, direction, **kwargs)
[rank1]:   File "/home/marc/transformers/src/transformers/integrations/integration_utils.py", line 275, in run_hp_search_optuna
[rank1]:     args = pickle.loads(bytes(args_main_rank))
[rank1]: _pickle.UnpicklingError: pickle data was truncated
```

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Awesome 🤩

**Review by ArthurZucker — APPROVED** [review]
🦄 pickl.load is still a thing? Have not check but do we have a warning somewhere about unsafe loading? 🤗 (that happens in this function)

**Comment by muellerzr** [comment]
@ArthurZucker it's because it's the whole `TrainingArgs` object. Fairly certain we can't safetensors a general object..?

**Comment by SunMarc** [comment]
I think that's still a thing when we want to perform broadcasting:
```
torch.distributed.broadcast_object_list(object_list, src=0, group=None, device=None)[[source]](https://pytorch.org/docs/stable/_modules/torch/distributed/distributed_c10d.html#broadcast_object_list)
Broadcasts picklable objects in object_list to the whole group.

Similar to [broadcast()](https://pytorch.org/docs/stable/distributed.html#torch.distributed.broadcast), but Python objects can be passed in. Note that all objects in object_list must be picklable in order to be broadcasted.
```

**Pull request merged**
