### PR TITLE
Fix ONNX tests for ONNX Runtime v1.13.1

### PR DESCRIPTION
**Pull request by lewtun**
# What does this PR do?

Fixes the slow tests for ONNX in `test_onnx.py` which were failing due `input_qType` being renamed by `activation_qType` in `onnxruntime` v1.13.1

With this fix, the follow passes:

```
RUN_SLOW=1 pytest tests/onnx/test_onnx.py
```

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thank you @lewtun ! They don't have a breaking change section on the release page 😢

**Review by sgugger — COMMENTED** [review]
Does the new name work with the minimum version of ONNX pinned?

**Comment by lewtun** [comment]
> Does the new name work with the minimum version of ONNX pinned?

Are you referring to the version we list in `setup.py` or somewhere else? In `setup.py` we have `onnxruntime>=1.4.0` so users with a pre-existing installation of ONNX Runtime would have to upgrade to `v1.13.1`.

An alternative is to have an if/else statement that checks the `onnxruntime` version to guarantee backwards compatibility - I'll implement that instead :)

**Comment by sgugger** [comment]
> An alternative is to have an if/else statement that checks the onnxruntime version to guarantee backwards compatibility - I'll implement that instead :)

Yes please!

**Comment by lewtun** [comment]
Backwards compatibility added in https://github.com/huggingface/transformers/pull/19950/commits/01ccbea13800e6912c1e34cbece4311cd2b6b420 :)

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Pull request merged**
