### PR TITLE
Fix the deprecation warning of _torch_pytree._register_pytree_node

### PR DESCRIPTION
**Pull request by cyyever**
# What does this PR do?
Fix a deprecation warning triggered by latest PyTorch:
```
UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
```

## Before submitting
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Hey! Could you share the warning and make sure this is backward compatible? 😉

**Review by ArthurZucker — APPROVED** [review]
LGTM let's make sure you rebase on main and the issue linked are fixed by this! 🤗

**Comment by cyyever** [comment]
Rebase again.

**Comment by ArthurZucker** [comment]
you also need to run `make style` and have the ruff package `pip install ruff==0.1.5`

**Comment by cyyever** [comment]
> you also need to run `make style` and have the ruff package `pip install ruff==0.1.5`

`make style` formats 
```
	modified:   src/transformers/models/bloom/modeling_bloom.py
	modified:   src/transformers/models/fuyu/image_processing_fuyu.py
	modified:   src/transformers/models/mpt/modeling_mpt.py
```
which are unrelated to this PR. Is it permitted to submit such changes?

**Comment by ArthurZucker** [comment]
They should not be modified no. No big deal, no I think rebasing on main might help as well! Otherwise I can checkout your PR and push the styling . Also `pip uninstall black` could help

**Comment by ArthurZucker** [comment]
No these files should not be modified 😓

**Comment by ArthurZucker** [comment]
Thank you!

**Pull request merged**
