### PR TITLE
Fix M4T weights tying

### PR DESCRIPTION
**Pull request by ylacombe**
# What does this PR do?

Following some failing tests [here](https://github.com/huggingface/transformers/actions/runs/6806630933/job/18508287020), I've pinpointed the bug to a tying weight issue !  This fixes the issue

cc @ydshieh, @LysandreJik  and @amyeroberts 

Also cc @Narsil who had fix a related seamlessM4t issue recently

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Changes LGTM - thanks for fixing! 

Would like a second review from @LysandreJik before merging as he knows the safetensors logic more than me

**Comment by Narsil** [comment]
This shouldn't be needed, the weights should already be tied at init time.

Edit: I looked a bit more closely:

- `no_init_weights` means all tensors are initialized as meta tensors (all shared with basically a null pointer for tensor).
- Tensors are loaded where they can, NOT updating the tied weights (since information is lost view device="meta".
- `tie_weights` is called here (currently doing nothing).
- Then things crash in `dispatch_model` (Something tries to attach some data to those still meta tensors).

With the fix, `tie_weights` reaffects the missing tensors.
Something could be a bit off though, since if this shared was actually offloaded (so really kept onto disk for instance) my understanding is that it would still be `meta` at step 2, and other kind of crashes would still happen, no ?

**Comment by ylacombe** [comment]
> no_init_weights means all tensors are initialized as meta tensors (all shared with basically a null pointer for tensor).
Tensors are loaded where they can, NOT updating the tied weights (since information is lost view device="meta".
tie_weights is called here (currently doing nothing).
Then things crash in dispatch_model (Something tries to attach some data to those still meta tensors).
With the fix, tie_weights reaffects the missing tensors.

This is exactly what happens here!

> Something could be a bit off though, since if this shared was actually offloaded (so really kept onto disk for instance) my understanding is that it would still be meta at step 2, and other kind of crashes would still happen, no ?

Not sure to have a response here, what kind of crashes could happen ?

**Comment by Narsil** [comment]
It's just information flow, here we're good only because the shared tensor is actually loaded, but with a fully offloaded to disk model it might not, right ?

**Comment by ylacombe** [comment]
Oh right, it could happen indeed. But it could happen to every model right ? because `model.tie_weights` happens [here](https://github.com/ylacombe/transformers/blob/1432fae1ee2ae621d1e88bcf70741a74ed4c17ae/src/transformers/modeling_utils.py#L3502) anyways ?

**Comment by ylacombe** [comment]
Gentle ping here to ask for a review @LysandreJik ! :hugs:

**Review by LysandreJik — APPROVED** [review]
Thank you @ylacombe

**Pull request merged**
