### PR TITLE
removing XLMConfig inheritance from FlaubertConfig

### PR DESCRIPTION
**Pull request by D3xter1922**
# What does this PR do?
related to  #19303
Removes `XLMConfig` dependency from `FlaubertConfig`

the `__init__` from `FlaubertConfig` differs from `XLMConfig` in the following ways:

- `pre_norm` and `layerdrop` are specific to `FlaubertConfig`. So, I have not added and `#Copied from ...`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@sgugger

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Looking good! Just make sure to run `make style` on your branch to fix the styling issue and this should be good to merge!

**Comment by sgugger** [comment]
Can you just put the PR as ready for review and remove WIP from the title? I can't merge draft PRs :-)

**Comment by D3xter1922** [comment]
> Can you just put the PR as ready for review and remove WIP from the title? I can't merge draft PRs :-)

Done. Thanks:)

**Comment by sgugger** [comment]
Thanks for your contribution!

**Pull request merged**
