### PR TITLE
improve _get_is_as_tensor_fns

### PR DESCRIPTION
**Pull request by zrr1999**
# What does this PR do?

When using VivitImageProcessor, there will be a warning for _get_is_as_tensor_fns,

```
/home/zrr/workspace/emotion-recognition-project/.venv/lib/python3.11/site-packages/transformers/feature_extraction_utils.py
:142: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list 
to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at 
../torch/csrc/utils/tensor_new.cpp:278.)
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks!

**Comment by amyeroberts** [comment]
@zrr1999 Could you run `make fixup` to resolve the quality checks?

**Comment by zrr1999** [comment]
Okay, I just fixed it.

**Review by amyeroberts — APPROVED** [review]
Thanks!

**Pull request merged**
