### PR TITLE
fix warning trigger for embed_positions when loading xglm

### LINKED ISSUE #25797: Loading XGLM triggers warning "Some weights of .. were not initialized from" for a module with no params
### System Info

- `transformers` version: 4.32.0
- Platform: Linux-5.15.0-41-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: 0.20.3
- Accelerate config:    not found
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@ArthurZucker @younesbelkada 
~~But probably a general issue in the `PretrainedModel` class.~~

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained('facebook/xglm-564M')
# Some weights of XGLMForCausalLM were not initialized from the model checkpoint 
# at facebook/xglm-564M and are newly initialized: ['model.embed_positions.weights']
# You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

### Expected behavior

The warning should not be triggered.

The positional embedding for XGLM uses `XGLMSinusoidalPositionalEmbedding` which does not have actual trainable parameters. My guess is that since there is no parameters, the key is not actually stored in the checkpoint and triggers the warning. This issue might exist in other models that similarly have `nn.Module` with no trainable parameters.

### PR DESCRIPTION
**Pull request by MattYoon**
# What does this PR do?

Fixes #25797 

Warning no longer triggers when loading XGLM from the hub. I've followed @younesbelkada 's suggestion of making the problematic module non-persistent.

```python
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained('facebook/xglm-564M')
# no warning
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@younesbelkada @ArthurZucker 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Hi @MattYoon 
Thanks a lot for the PR ! A test that checks conversion between tensorflow and pytorch model is failing. I think we can fix it by adding a `_keys_to_ignore_on_load_missing` in the TF XGLM modeling file as follows: https://github.com/huggingface/transformers/blob/cb91ec67b54c1a8a9a24825165161c90fe7c0e51/src/transformers/models/gptj/modeling_tf_gptj.py#L804 Let us know if you have some questions ! 🙏 cc also @Rocketknight1 how do we properly deal with non-persistent tensors in TF?

**Comment by Rocketknight1** [comment]
@younesbelkada Good question! There is no `register_buffer` method in TF. There are two replacements you can use for it, depending on what the variable is actually doing:

1) If the variable needs to be saved/loaded with the model, but you just don't want the optimizer to train it, then create it with `self.add_weight(trainable=False)`. This is similar to `self.register_buffer(persistent=True)`
2) If the weights don't need to be saved, and are just created as a performance optimization to avoid recomputing them in every iteration, this is similar to `self.register_buffer(persistent=False)`. In this case, you can create them in the layer `__init__()` or `build()` method as a `tf.constant`. They will only be computed once, and marking them as `tf.constant` lets the compiler do constant optimizations in the graph. If you do it this way then TF won't really treat them like a 'weight' at all, so you'll probably have to add them to `_keys_to_ignore_on_load_unexpected`.

Let me know if you need my help writing a PR for any of this!

**Comment by MattYoon** [comment]
Hi, @younesbelkada. Thanks for guiding me through the PR! To be frank, I'm not familiar enough on either TF or Transformers to complete this PR. I'm worried that me attempting to fix this issue will cause some other problems and merging this PR will take way longer than necessary. 

The issue seems like a very simple fix for someone familiar with the internals of Transformers. Can you or someone else close this PR and take the torch? Sorry I couldn't be much help.

**Comment by Rocketknight1** [comment]
@MattYoon You don't need to close it! If you allow edits from maintainers, I can push the relevant change to your branch. It should only be one line in the TF code.

**Comment by MattYoon** [comment]
Yes that sounds great! I believe "allow edits from maintainers" is active for this PR.

**Comment by Rocketknight1** [comment]
@MattYoon Done! I also fixed some spelling in the TF module while I was there.

cc @younesbelkada too

**Review by younesbelkada — APPROVED** [review]
Thanks for your great contribution @MattYoon and thanks a lot for the help @Rocketknight1 !

**Comment by Rocketknight1** [comment]
cc @amyeroberts for core maintainer review!

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
