### PR TITLE
 Add sdpa for Vivit

### PR DESCRIPTION
**Pull request by RUFFY-369**
# What does this PR do?

Towards #28005 

Adds sdpa for the ViViT model.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@amyeroberts

### CODE REVIEW

**Comment by RUFFY-369** [comment]
@amyeroberts All green 🟢 :smiley:

**Review by amyeroberts — COMMENTED** [review]
Thanks for adding! 

Two things before merge: 
* Running the slow tests for the model. Could you push an empty commit with the message `[run_slow] vivit`?
* Adding info and benchmarks to the model's doc page. A good example is [here](https://huggingface.co/docs/transformers/v4.44.2/en/model_doc/gpt_neox#using-scaled-dot-product-attention-sdpa). Benchmarking scripts from @fxmarty for [training](https://gist.github.com/fxmarty/7e75cc3942d6974e4849093ebea0a331) and [inference](https://gist.github.com/fxmarty/5113e4304fbdd38c9c3702ce44683f6a).

**Review by vignesh1507 — APPROVED** [review]
looks good to me, appreciate the effort @RUFFY-369

**Comment by RUFFY-369** [comment]
> Hi @amyeroberts , I think in the `ViViT` model, originally `interpolate_pos_encoding` method [here](https://github.com/huggingface/transformers/blob/4196590aa0fe6ed735b68e126c2125a5d806acb7/src/transformers/models/vivit/modeling_vivit.py#L110) hasn't been correctly implemented and has just been copied from `ViT` because I made a commit in this current PR regarding `patch_size` [here](https://github.com/huggingface/transformers/pull/33757/commits/9c46bf2d4df7137a686dc8b55a58ee4280fc1c61) as `patch_size` itself wasn't declared in the method. I gave benefit of doubt to the work done during the port of this model and just fixed it. But when I tested the slow tests with `RUN_SLOW`, `test_inference_interpolate_pos_encoding` failed because the implementation hasn't been done properly. So, should I raise an issue separately or fix it here.
> 
> One thing can be that apart from the `test_inference_interpolate_pos_encoding` slow test rest can tested by `[run_slow] vivit` commit message and I will push the training and inference benchmark too just in some time. And when this PR gets merged, I will open a separate issue for `test_inference_interpolate_pos_encoding` test fix.
> 
> Or the other thing can be that I fix it here in this PR.
> 
> Please suggest what works well for you?!

Update: This [commit](https://github.com/huggingface/transformers/pull/33757/commits/9c46bf2d4df7137a686dc8b55a58ee4280fc1c61) was enough to fix the interpolate method and the only thing required is a nit in `test_inference_interpolate_pos_encoding` for it to pass, basically a correction in the input being passed. Right now, I'm keeping that nit change in hold because I need a confirmation from your side that to fix `test_inference_interpolate_pos_encoding` failure in this issue or simply open a separate issue.

And regarding this PR, 

> Thanks for adding!
> 
> Two things before merge:
> 
> * Running the slow tests for the model. Could you push an empty commit with the message `[run_slow] vivit`?
> * Adding info and benchmarks to the model's doc page. A good example is [here](https://huggingface.co/docs/transformers/v4.44.2/en/model_doc/gpt_neox#using-scaled-dot-product-attention-sdpa). Benchmarking scripts from @fxmarty for [training](https://gist.github.com/fxmarty/7e75cc3942d6974e4849093ebea0a331) and [inference](https://gist.github.com/fxmarty/5113e4304fbdd38c9c3702ce44683f6a).

Both of the things asked has been completed and pushed. So, this PR is ready for merge.

**Comment by RUFFY-369** [comment]
Hi @amyeroberts , I just created a separate PR where `interpolate_pos_encoding` for ViViT has been fixed, fixing the slow test with it. 
Also, your suggestions have already been addressed for this PR so, its ready to be merged.

Please review both of them when you get the time.
Thank you :smile:

**Comment by RUFFY-369** [comment]
@amyeroberts Can you please add `run_slow` label here as well so that the empty commit can work.
Thanks

**Comment by amyeroberts** [comment]
@RUFFY-369 You should be able to add the label yourself, I think. Could you try? It would be useful to know if external collaborators can or can't add this, as we'd like to make this so that contributors can do as much as possible independently

**Comment by RUFFY-369** [comment]
@amyeroberts No, I can't. On my side I don't have any gear/settings button near label:
Screenshot from 2024-09-30 18-23-20

Usually if I can add the label, I would see something like this:

Screenshot from 2024-09-30 18-24-06

So, yes, I guess external collaborators can't add this

**Comment by amyeroberts** [comment]
@RUFFY-369 OK, thanks for checking! @ydshieh This means the message for the slow model tests bot might need to be changed as contributors can't add the label as instructed

**Comment by amyeroberts** [comment]
@RUFFY-369 I've added the label. Could you push another `[run-slow] vivit` commit to trigger the tests?

**Comment by RUFFY-369** [comment]
> @RUFFY-369 I've added the label. Could you push another `[run-slow] vivit` commit to trigger the tests?

@amyeroberts Done :+1:

**Comment by RUFFY-369** [comment]
Failing tests are unrelated

**Comment by amyeroberts** [comment]
@RUFFY-369 Could you rebase? A fix has been merged in

**Comment by RUFFY-369** [comment]
> @RUFFY-369 Could you rebase? A fix has been merged in

@amyeroberts Done

**Review by amyeroberts — COMMENTED** [review]
Thanks for adding @RUFFY-369! 

The only thing missing is a fallback for when output_attentions are passed e.g. [like here](https://github.com/huggingface/transformers/blob/e7c8af7f338eab42bd6615f77da5b69094b4836e/src/transformers/models/distilbert/modeling_distilbert.py#L364)


cc @qubvel

**Comment by RUFFY-369** [comment]
@amyeroberts Fallback has been added for `output_attentions`

Cheers!

**Comment by RUFFY-369** [comment]
All green, slow tests are left to trigger

**Comment by RUFFY-369** [comment]
soft ping @amyeroberts 
Thank you

**Review by qubvel — APPROVED** [review]
Thanks, looks good to me! cc @ArthurZucker for final review

**Comment by RUFFY-369** [comment]
soft ping @ArthurZucker 
Thank you :smile:

**Review by ArthurZucker — APPROVED** [review]
LGTM thanks for the details documentation update!

**Comment by ArthurZucker** [comment]
🤗

**Pull request merged**
