### PR TITLE
Add `push_to_hub( )`  to pipeline 

### LINKED ISSUE #28857: add `push_to_hub( )` method when working with pipelines
### Feature request

it will be good to addition to the library to add a `push_to_hub( )` method when working with the pipeline method.

### Motivation

I have just finished up a blogpost about creating custom architectures, but i couldn't help but notice that when working with ` AutoConfig` or `AutoModelForxxx` or `PreTrainedModel`  have a `push_to_hub( )` methods alllowing them to easily be updated on the hub.
unfortunately, this isn't the case for the pipeline method, I found a possible work around by cloning the repo then using `save_pretrained( )` then pushing the changes, but this not optimised and takes lots of time especially when working with really large language models
check the documentation : 
https://huggingface.co/blog/not-lain/custom-architectures-with-huggingface#push-to-hub-%F0%9F%A4%97
<hr>

image
**VS**
image

### Your contribution

yes, I can help out with a PR

### PR DESCRIPTION
**Pull request by not-lain**
# What does this PR do?
this will add a push_to_hub( ) method when working with pipelines. 
this is a fix for #28857 allowing for easier way to push custom pipelines to huggingface

Fixes #28857 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@Narsil @Rocketknight1 @ArthurZucker  

I have also added a notebook showcasing how to use the new method : https://colab.research.google.com/drive/1yCET-FdkI4kHK1B-VUrrM7sKHMO3LkOg?usp=sharing

all that is missing is to fix the docstring and maybe add more tests to figure out what else that needs to be fixed

### CODE REVIEW

**Comment by not-lain** [comment]
the docstring will need more cleaning, I'll leave it to another pull request since it does not affect the workflow

image

**Comment by not-lain** [comment]
cc @ArthurZucker can I ask for a review on this one ?

**Review by ArthurZucker — COMMENTED** [review]
Thanks for opening a PR!
We usually wait and see if the feature is actually requested a lot by the community or not. In the current state I don't really think it makes sense to support this. (Not sure about the use cases?) 
Each pipeline need all the elements to be from the same model + from_pretrained is not the current API !

**Comment by not-lain** [comment]
@ArthurZucker what i ment is that i couldn't fix the docstring since we are inhering from PushToHubMixin, there are some ways around this, so i will leave the final decision to you.

as for the pipeline, this pull request will only add a `pipe.push_to_hub( )` method to it, allowing people to push their custom pipeline codes easily to the hub, refer to the colab notebook mentioned above

**Comment by not-lain** [comment]
this pull request does **NOT** add a `pipeline.from_pretrained( )`, but I wanted to highlight what other things that need fixing

**Comment by not-lain** [comment]
fixed the docstring
image

**Comment by not-lain** [comment]
is the main branch broken ? I really am lost, would love to get a feedback on this, sorry for pushing multiple times i really wanted to fix the docstring ,  7543177c9b4fcef4cb87b905815a0b709bb255a1 and ea93bae96c47919f216f0443f3b28e2e78137937 are literally identical.

**Comment by not-lain** [comment]
@ArthurZucker sorry for always bothering you, I really hope you are having a wonderful day ✨

as far as the [docs](https://moon-ci-docs.huggingface.co/docs/transformers/pr_28870/en/main_classes/pipelines) go everything is pretty much the same as the main branch.
the only change is that we added a `push_to_hub` method.
as far as the method goes, It's pretty much working for now, I already used it multiple times to push my custom pipelines to the hub, check a commit i made using this version [here](https://huggingface.co/not-lain/CustomCodeForRMBG/commit/c40df9ae88862aaf48d61bd3eec8aea3b618def6).

as for the documentation, only and only [this section of the documentation](https://moon-ci-docs.huggingface.co/docs/transformers/pr_28870/en/main_classes/pipelines#transformers.Pipeline.push_to_hub)  is misleading a little bit.

Personally I really think that the dosctring should be fixed in a different pull request, since this feature is really important. 
Do let me know of what you think. 

apologies again for the tag, but I really need a takeout about this pull request since I need to test the stability for this in regards to issue #28907.

**Review by ArthurZucker — COMMENTED** [review]
Alright If I understand correctly, this is mostly to allow pushing custom pipeline registeries to the hub? 
If so we would need to add some tests show that this indeed works and the pipeline can be loaded effectively.

**Comment by not-lain** [comment]
hello @ArthurZucker I have come to realise that I cannot add tests for this pull request, the reason behind this is I cannot and I do not intend to expose my token, I do not also know at which repo I should test push to. Due to lack of these information I will not be able to further assist you futher.
If you have any tests, you wish to add please let the team at huggingface handle them.
the only thing I can provide you with is a code example using this pull request 
https://colab.research.google.com/drive/1yCET-FdkI4kHK1B-VUrrM7sKHMO3LkOg?usp=sharing

**Comment by ArthurZucker** [comment]
No worries for the test, I'll handle this pard. Sorry I did not have time to take a clear look at all of this. But sounds like a nice feature addition

**Comment by not-lain** [comment]
@ArthurZucker that would be much appreciated, you can check the new pull request at #29172 any help is appreciated

**Pull request closed without merging**
