### PR TITLE
Fix ViT hybrid model type in model config

### LINKED ISSUE #29862: Incorrect model_type for ViTHybridModel
### System Info

transformers==4.39.1

### Who can help?

@amyeroberts

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import VisionEncoderDecoderModel, BertConfig, BertGenerationDecoder, ViTHybridConfig, \
    ViTHybridModel

decoder = BertGenerationDecoder(BertConfig())
encoder = ViTHybridModel(ViTHybridConfig())
model = VisionEncoderDecoderModel(encoder=encoder, decoder=decoder)
```

Yields

```
Traceback (most recent call last):
  File "/home/jb/Documents/vilmedic/x.py", line 6, in <module>
    model = VisionEncoderDecoderModel(encoder=encoder, decoder=decoder)
  File "/home/jb/miniconda3/envs/vilmedic/lib/python3.8/site-packages/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 173, in __init__
    config = VisionEncoderDecoderConfig.from_encoder_decoder_configs(encoder.config, decoder.config)
  File "/home/jb/miniconda3/envs/vilmedic/lib/python3.8/site-packages/transformers/models/vision_encoder_decoder/configuration_vision_encoder_decoder.py", line 115, in from_encoder_decoder_configs
    return cls(encoder=encoder_config.to_dict(), decoder=decoder_config.to_dict(), **kwargs)
  File "/home/jb/miniconda3/envs/vilmedic/lib/python3.8/site-packages/transformers/models/vision_encoder_decoder/configuration_vision_encoder_decoder.py", line 96, in __init__
    self.encoder = AutoConfig.for_model(encoder_model_type, **encoder_config)
  File "/home/jb/miniconda3/envs/vilmedic/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 1033, in for_model
    raise ValueError(
ValueError: Unrecognized model identifier: vit-hybrid. Should contain one of albert, align, [..]
Process finished with exit code 1
```

Problem:
https://github.com/huggingface/transformers/blob/v4.39.1/src/transformers/models/vit_hybrid/configuration_vit_hybrid.py#L102
is `model_type = "vit-hybrid"`
When all the mappings are:
```
[..]
("vit", "ViTConfig"),
("vit_hybrid", "ViTHybridConfig"),
("vit_mae", "ViTMAEConfig"),
[..]
```

Hence, model_type should be `vit_hybrid`

JB

### Expected behavior

Correct init of VisionEncoderDecoderModel

### PR DESCRIPTION
**Pull request by kshitij98**
# What does this PR do?

Fixes #29862 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case: _#29862_ 
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation). -_Not applicable_
- [ ] Did you write any new necessary tests? -_Not required, trivial change_

## Testing

I am unable to run pytests as they keep crashing without any of the changes as well, I have attached the logs below. Probably something still missing in the developer workflow I've setup.

Otherwise, I have tested the code changes by instantiating the model, that works fine now.

```
>>> from transformers import VisionEncoderDecoderModel, BertConfig, BertGenerationDecoder, ViTHybridConfig, \
...     ViTHybridModel
>>> decoder = BertGenerationDecoder(BertConfig())
>>> encoder = ViTHybridModel(ViTHybridConfig())
>>> model = VisionEncoderDecoderModel(encoder=encoder, decoder=decoder)
>>>
>>> model
VisionEncoderDecoderModel(
  (encoder): ViTHybridModel(
    ...
  )
  (decoder): BertGenerationDecoder(
    ...
  )
)
```

## Environment details

- `transformers` version: 4.40.0.dev0
- Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.22.1
- Safetensors version: 0.4.2
- Accelerate version: 0.28.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- Tensorflow version (GPU?): 2.15.1 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.0 (cpu)
- Jax version: 0.4.13
- JaxLib version: 0.4.13
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

## Who can review?

@amyeroberts @jbdel

## Error logs

```console
(.env) ➜  transformers git:(vit-hybrid-model-type) python3 -m pytest -n auto --dist=loadfile -s -v ./tests/models/vit_hybrid
2024-03-27 20:32:53.338348: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-27 20:32:53.338491: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-27 20:32:53.350148: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-27 20:32:54.758693: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
=================================================================== test session starts ====================================================================
platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0 -- /home/kshitij/github/kshitij98/transformers/.env/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/kshitij/github/kshitij98/transformers/.hypothesis/examples'))
rootdir: /home/kshitij/github/kshitij98/transformers
configfile: pyproject.toml
plugins: hypothesis-6.99.13, xdist-3.5.0, picked-0.5.0, timeout-2.3.1, dash-2.16.1
initialized: 4/4 workers[1]    1408 killed     python3 -m pytest -n auto --dist=loadfile -s -v ./tests/models/vit_hybrid



(.env) ➜  transformers git:(vit-hybrid-model-type) python3 -m pytest -n 1 --dist=loadfile -s -v ./tests/models/vit_hybrid
2024-03-27 20:35:47.976887: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-27 20:35:47.977047: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-27 20:35:47.979643: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-27 20:35:49.492979: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
=================================================================== test session starts ====================================================================platform linux -- Python 3.10.12, pytest-7.4.4, pluggy-1.4.0 -- /home/kshitij/github/kshitij98/transformers/.env/bin/python3
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/kshitij/github/kshitij98/transformers/.hypothesis/examples'))
rootdir: /home/kshitij/github/kshitij98/transformers
configfile: pyproject.toml
plugins: hypothesis-6.99.13, xdist-3.5.0, picked-0.5.0, timeout-2.3.1, dash-2.16.1
initialized: 1/1 worker2024-03-27 20:35:55.466678: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-27 20:35:55.466743: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-27 20:35:55.467575: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-27 20:35:56.290601: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
1 worker [109 items]
scheduling tests via LoadFileScheduling

tests/models/vit_hybrid/test_modeling_vit_hybrid.py::ViTHybridModelTest::test_attention_outputs
[gw0] node down: Not properly terminated
[gw0] FAILED tests/models/vit_hybrid/test_modeling_vit_hybrid.py::ViTHybridModelTest::test_attention_outputs

replacing crashed worker gw0
```

### CODE REVIEW

**Comment by ArthurZucker** [comment]
cc @amyeroberts

**Review by amyeroberts — COMMENTED** [review]
Thanks for fixing @kshitij98! 

We need to make sure this is backwards compatible when loading existing configs too. 

Could you run the following and confirm it still works:

```
from transformers import AutoModel

model = AutoModel.from_pretrained("google/vit-hybrid-base-bit-384")
```

and the slow model tests:

`RUN_SLOW=1 pytest tests/models/vit_hybrid/`

**Comment by kshitij98** [comment]
Thanks for the review @amyeroberts, loading the pretrained model was failing, and is currently failing in prod as well with the error: 
image


because the pretrained model has `vit-hybrid` instead of `vit_hybrid` in the config. So I've updated all instances to `vit-hybrid` instead.

---

For testing, I've checked both initialisations now work.

```python
>>> from transformers import VisionEncoderDecoderModel, BertConfig, BertGenerationDecoder, ViTHybridConfig, \
...     ViTHybridModel
>>> decoder = BertGenerationDecoder(BertConfig())
>>> encoder = ViTHybridModel(ViTHybridConfig())
>>> model = VisionEncoderDecoderModel(encoder=encoder, decoder=decoder)
>>>
>>> model
VisionEncoderDecoderModel(
  (encoder): ViTHybridModel(
    ...
  )
  (decoder): BertGenerationDecoder(
    ...
  )
)
```

```python
>>> from transformers import AutoModel
>>> model = AutoModel.from_pretrained("google/vit-hybrid-base-bit-384")
Some weights of ViTHybridModel were not initialized from the model checkpoint at google/vit-hybrid-base-bit-384 and are newly initialized: ['vit.pooler.dense.bias', 'vit.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

>>> model
ViTHybridModel(
    ...
)
```

---

I have executed pytests on [Colab](https://colab.research.google.com/drive/1pDzL0STrA91h0K76MCqDScaUHLZY5yXt#scrollTo=nKOrm6xJMoQ1&line=1&uniqifier=1), and it looks good to me though some tests got skipped.

===================== 64 passed, 45 skipped, 28 warnings in 123.58s (0:02:03) ======================

**Comment by amyeroberts** [comment]
Hi @kshitij98, thanks for digging into this! 

This is going to be quite tricky to resolve to make sure everything is backwards compatible. We're going to deprecate the vit hybrid model soon, as it has a relatively small number of downloads. In this case, I'd suggest we park this change and don't worry about trying to make this work.

**Pull request closed without merging**
