### PR TITLE
Adding optimizations block from ONNXRuntime.

### PR DESCRIPTION
**Pull request by mfuntowicz**
cc @EmmaNingMS

### CODE REVIEW

**Comment by mfuntowicz** [comment]
cc @tianleiwu

**Review by LysandreJik — APPROVED** [review]
Cool! Do we want to have `use_external_format` on by default, as it was done previously? Does it run slower when using `use_external_format`?

**Comment by mfuntowicz** [comment]
use_external_data_format has some side-effect we'd like to mitigate here, I set to False by default and let the possibility for the user to override through CLI args.

**Review by EmmaNingMS — APPROVED** [review]
LGTM

**Review by tianleiwu — APPROVED** [review]
Looks Good.

**Pull request merged**
