### PR TITLE
[Time Series Transformer] Add doc tests

### PR DESCRIPTION
**Pull request by NielsRogge**
# What does this PR do?

This PR improves the code snippets in the docs of Time Series Transformer and makes sure they are tested.

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thank you @NielsRogge , I will earn more when using this to predict stock price.

**Comment by kashif** [comment]
LGTM! thanks!

**Comment by kashif** [comment]
@ydshieh always better to learn more than earn more

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Comment by kashif** [comment]
@NielsRogge for generation you can also use the other test batch if you like

**Pull request merged**
