### PR TITLE
Fix failing conversion

### PR DESCRIPTION
**Pull request by LysandreJik**
The usage of the conversion Space was not working since it was upgraded to use gradio 4.36.

This is fixed and using the new approach used in Gradio.

Also a test should have been raised but wasn't visible as it was in a subTest; it should now be visible.

### CODE REVIEW

**Review by osanseviero — COMMENTED** [review]
cc @abidlabs @pngwn 

(should this be using `gradio_client` for simplicity?

**Comment by abidlabs** [comment]
Yes thanks for flagging @osanseviero. Although you'd need to add `gradio_client` as a dependency, it would be much cleaner (and more future-proof) to use the Gradio Client. The Client is pretty lightweight: https://github.com/gradio-app/gradio/blob/main/client/python/requirements.txt, so lmk if you'd like to go down that approach and can open up a PR

**Review by ArthurZucker — APPROVED** [review]
Looks simpler! 🤗

**Comment by LysandreJik** [comment]
Unfortunately we're extremely strict in the required dependencies for `transformers` so we won't be able to add `gradio_client` at this time

**Comment by LysandreJik** [comment]
And in terms of future-proof, I mostly need to stay more up to date with the gradio updates to the `safetensors/convert` Space so as to not miss an update! Thanks

**Pull request merged**
