### PR TITLE
[multiple models] skip saving/loading deterministic state_dict keys

### LINKED ISSUE #7296: Marian/MBart should not save static position embeddings
Add
```
    keys_to_never_save = [
        "model.encoder.embed_positions.weight",
        "model.decoder.embed_positions.weight",
    ]
```

Probably also applies to XLM, T5 (I think) and a few others.

### PR DESCRIPTION
**Pull request by stas00**
Implementing https://github.com/huggingface/transformers/issues/7296

* [x] make testing save/load of `keys_to_never_save` a common test by moving it from `fsmt` modeling test
* [x] implement skipping for all models with static positional embeddings: mbart, pegasus, marian (fsmt had this feature in first place)

Fixes: #7296

@LysandreJik, @sshleifer, @sgugger

### CODE REVIEW

**Comment by stas00** [comment]
OK, so how would you recommend we run a specific common test for a model whose test module isn't running common tests at all? Please have a look at the workaround I found for `mbart` https://github.com/huggingface/transformers/pull/7878/commits/50414cc48ee9f2f4f2d2f527f134aae4d847bac3 - I basically made a very stripped down `ModelTester` and then used a hack to run the common test via:
```
    def test_save_load_keys_to_never_save(self):
        ModelTesterMixin.test_save_load_keys_to_never_save(self)
```
Is this any good, or would you recommend a different approach - the idea is not to copy the same test to each test module.

**Comment by sshleifer** [comment]
I like how you did it.
Adding @LysandreJik and @sgugger to see if they agree before you do it 5 times.

**Review by sgugger — APPROVED** [review]
I agree that the way you added the test for MBart (I imagine you double-checked the test was indeed executed? It's one of those instances where I see it should work but can't help to doubt it ;-) ) and I like this PR in general, thanks for working on this and feel free to continue with other models

**Review by LysandreJik — APPROVED** [review]
This is cool and great approach for the mBART model!

**Comment by stas00** [comment]
> I imagine you double-checked the test was indeed executed.

Yes. 

Indeed, my initial test that I wrote for fsmt wasn't executing, since I renamed the keys in the code and forgot the test and the test was no-op if it didn't find the right keys. So some print()s helped to verify it indeed worked in this new incarnation.

**Comment by stas00** [comment]
I think  `test_save_load_missing_keys` should be handled separately since it can add a significant overhead if run by all models, since I noticed tf models are **very** slow at save/load tests.. I removed it from common tests for now - back to just fsmt - will do a separate PR about it.

**Comment by stas00** [comment]
Anybody with a good knowledge of XLM? @sshleifer suggested to add xlm to this PR, but I'm not sure whether it's safe to not save `self.position_embeddings`, since as you can see here:
https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_xlm.py#L439
the deterministic non-trained weights happen only if `config.sinusoidal_embeddings` is True. Otherwise it gets trained like any other embed layer.

Which leaves just: `position_ids` which is tiny a set of 512-2048 floats, which is not worth bothering for IMHO.

**Comment by stas00** [comment]
wrt t5 - I don't see anything positional or deterministic for that matter, but this is quite a different model - are there any state_dict keys here that would be a good candidate for not saving?

**Comment by stas00** [comment]
I implemented this for: mbart, pegasus, marian - all subclasses of `BartForConditionalGeneration` w/ `static_position_embeddings=True`.

I don't suppose we can implement this for Bart since its conditional.

**Review by sgugger — APPROVED** [review]
LGTM and this has been pre-approved so I will merge. If we discover some missing models, we can add them in another PR.
Thanks a lot  stas!

**Pull request merged**
