### PR TITLE
Spanish docs - Fix nits and wording

### PR DESCRIPTION
**Pull request by omarespejel**
# What does this PR do?
Fix wording and nits in the merged Spanish documentation.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

### CODE REVIEW

**Comment by omarespejel** [comment]
@sgugger links to current docs that don't exist (eg `./main_classes/pipelines`) don't work. Do you think it would be worth linking them to the English docs while the Spanish versions become available? Or should we wait?

fyi @osanseviero

**Comment by sgugger** [comment]
I had been told that links to page that don't exist in one language would be automatically resolved to the English version, cc @mishig25

**Comment by omarespejel** [comment]
Currently, the links lead to an error if the doc is not yet translated. For example, this fragment in [`autoclass_tutorial`](https://huggingface.co/docs/transformers/main/es/autoclass_tutorial) leads a to an error for not having [model_doc/auto.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_doc/auto.mdx)
 translated yet.
> Finalmente, las clases AutoModelFor te permiten cargar un modelo preentrenado para una tarea dada (revisa [aquí](https://huggingface.co/docs/transformers/main/es/model_doc/auto) para conocer la lista completa de tareas disponibles).

Please let me know if any help is required.

**Comment by omarespejel** [comment]
This PR fixes some wording and format in the Spanish docs. It would be ready to merge IMO.

I will open an issue regarding the problem with the links.

**Review by sgugger — APPROVED** [review]

**Comment by sgugger** [comment]
Thanks for fixing!

**Pull request merged**
