### PR TITLE
[FIX] not training when epoch is small

### LINKED ISSUE #2995: No optimizer steps when gradient_accumulation_steps smaller than epoch_iterator length
# 🐛 Bug

## Information

Model I am using (Bert, XLNet ...): Doesn't matter.

Language I am using the model on (English, Chinese ...): Doesn't matter.

The problem arises when using:
* [x] the official example scripts
* [ ] my own modified scripts

The tasks I am working on is:
* [x] an official GLUE/SQUaD task: Any of the tasks.
* [ ] my own task or dataset

## To reproduce

1. Run `run_glue.py` where number of batches for each epoch is smaller than gradient_accumulation_steps.

In https://github.com/huggingface/transformers/blob/8194df8e0cff8e5866ec2bcbda34e3892f10eb39/examples/run_glue.py#L233

`step` is at most `len(train_dataloader)/batch_size`. If the latter is small, then we would never enter the if condition and never call `optimizer.step()` and so on.

I know it's the user responsibility to be aware of this, but this can be easily solved by by altering the condition to be:
```
if (step + 1) % args.gradient_accumulation_steps == 0 or ((step + 1) < args.gradient_accumulation_steps and (step + 1) == len(epoch_iterator)):
```

Should I create a small PR?

### PR DESCRIPTION
**Pull request by mataney**
Closes https://github.com/huggingface/transformers/issues/2995

Solving bug where for small epochs and large gradient_accumulation_steps we never train.
Explained further here: https://github.com/huggingface/transformers/issues/2995

### CODE REVIEW

**Comment by LysandreJik** [comment]
Cool, thanks @mataney! Do you mind running `make style` at the root of the repository to reformat the file according to `black` and `isort`, as indicated in our [contributing guidelines](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests)?

This is so the `check_code_quality` passes.

**Comment by mataney** [comment]
@LysandreJik Thanks for your reply.

Recommited with the black formatting.
It is now failing because something else. Do you think you can rerun the tests? I believe it has something to do with the Indeterminism of the tests.

**Comment by mataney** [comment]
Can I have your help here @LysandreJik

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks @mataney 

Indeed the failing test is not due to your modifications

**Pull request merged**
