### PR TITLE
Add model summary

### PR DESCRIPTION
**Pull request by sgugger**
This PR adds a high-level summary of all the models in the documentation.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Looks great :-)

**Review by patrickvonplaten — APPROVED** [review]

**Review by sshleifer — APPROVED** [review]
LGTM
I would add back and forth links with `pretrained_models.rst`

**Comment by sgugger** [comment]
Eh, forgot to finish my sentence linking to the pretrained models doc page at the beginning. No sure if I can link to part of the tables however, does restructured text can support that?

**Comment by sshleifer** [comment]
I doubt it. One link is OK I think

**Pull request merged**
