### PR TITLE
Translated ```text_generation.md``` to Korean

### LINKED ISSUE #20179: Tranformers documentation translation to Korean
Hi!

Let's bring the documentation to all the Korean-speaking community :)

Who would want to translate? Please follow the 🤗 [TRANSLATING guide](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md). Here is a list of the files ready for translation. Let us know in this issue if you'd like to translate any, and we'll add your name to the list.

Some notes:

* Please translate using an informal tone (imagine you are talking with a friend about transformers 🤗).
* Please translate in a gender-neutral way.
* Add your translations to the folder called ja inside the [source folder](https://github.com/huggingface/transformers/tree/main/docs/source).
* Register your translation in ja/_toctree.yml; please follow the order of the [English version](https://github.com/huggingface/transformers/blob/main/docs/source/en/_toctree.yml).
* Once you're finished, open a pull request and tag this issue by including #issue-number in the description, where issue-number is the number of this issue. Please ping @omarespejel and @sgugger _(who should be here?)_ for review.
* 🙋 If you'd like others to help you with the translation, you can also post in the 🤗 [forums](https://discuss.huggingface.co/).

## Get Started section

- [ ] [index.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/index.mdx)
- [ ] [quicktour.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/quicktour.mdx).
- [ ] [installation.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/installation.mdx).

## Tutorial section
- [ ] [pipeline_tutorial.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/pipeline_tutorial.mdx)
- [ ]  [autoclass_tutorial.mdx](https://github.com/huggingface/transformers/blob/master/docs/source/autoclass_tutorial.mdx)
- [ ]  [preprocessing.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/preprocessing.mdx)
- [ ]  [training.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/training.mdx)
- [ ]  [accelerate.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/accelerate.mdx)
- [ ]  [model_sharing.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/model_sharing.mdx)
- [ ]  [multilingual.mdx](https://github.com/huggingface/transformers/blob/main/docs/source/en/multilingual.mdx)

### PR DESCRIPTION
**Pull request by zayunsna**
# What does this PR do?
Hi all!
PR : translating ```text_generation.md``` file and add creating the parent folder ```main_classes```.
Thank you for reviewing this translating results!

Part of #20179 

## Before reviewing

- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. [[lowercased-header]])
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)
## Who can review?

As followed the guide, I would like to give a review request to @ArthurZucker, @sgugger, @eunseojo.
and also send the review request to Team PseudoLab just in case. @0525hhgus, @kihoon71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo.

## Before submitting

- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x]  Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
 Pull Request section?
- [ ]  Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
 to it if that's the case.
- [x]  Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ]  Did you write any new necessary tests?

### CODE REVIEW

**Comment by wonhyeongseo** [comment]
Hello @zayunsna , before I give a thorough review, may you please change "Fixes #20197" to "Part of #20197"?

If unchanged, it will close the issue with the merge of this PR. Thank you.

**Comment by zayunsna** [comment]
> Hello @zayunsna , before I give a thorough review, may you please change "Fixes #20197" to "Part of #20197"?
> 
> If unchanged, it will close the issue with the merge of this PR. Thank you.

It corrected!

**Comment by zayunsna** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. If you think this still needs to be addressed please comment on this thread.
> 
> Please note that issues that do not follow the [contributing guidelines](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md) are likely to be ignored.

Still waiting for the review. I hope to get comments or further process.

**Review by ArthurZucker — COMMENTED** [review]
Hey! Thanks for opening the PR and continuing the translation 🔥 
There was a pretty big change in the text generation documentation which does not match this one anymore. Would you mind updating ? 😓 sorry for this

**Comment by zayunsna** [comment]
> Hey! Thanks for opening the PR and continuing the translation 🔥 There was a pretty big change in the text generation documentation which does not match this one anymore. Would you mind updating ? 😓 sorry for this

No worries! 
I'll have a look at the changed item! 
I just quickly glanced at the material but it seems there needs to be a detailed comparison of what was updated.
Thank you for letting me know!
Let's keep in touch!

**Comment by gabrielwithappy** [comment]
Dear @zayunsna 
I will review it together! 🙂
Wecl can discuss about translation on the huggingface discord 한국어 channel.
https://discord.com/channels/879548962464493619/1105153909552586812

**Comment by zayunsna** [comment]
@ArthurZucker, Hi :)  I have a look at a new update of 'transformer'.
So from now, this PR contains the updated item as same as the main repo.
I hope this is what you want!

**Comment by gabrielwithappy** [comment]
@zayunsna 
good to hear.
As we dicuss, forked repo need to be synced before pusing the  PR.
And  I recommend  u to make a branch in your forked repo.
[Transformer] - [Forked Transformer] :: PR branch

**Pull request closed without merging**
