### PR TITLE
Add beam search visualizer to the doc

### PR DESCRIPTION
**Pull request by aymeric-roucher**
# What does this PR do?

Add this [visualization tool for beam-search](https://huggingface.co/spaces/m-ric/beam_search_visualizer) to the documentation.

## Who can review?
@gante

### CODE REVIEW

**Comment by aymeric-roucher** [comment]
@gante I've added a reference were you pointed, and a shorter one in the intro where beam-search was described. If you prefer we can remove the shortest.

**Review by ArthurZucker — APPROVED** [review]
I would even add a screen / gif of what it looks like! Great work over there! 🤗

**Comment by aymeric-roucher** [comment]
Thanks a lot @ArthurZucker ! PR to add an image to the doc dataset open here: https://huggingface.co/datasets/huggingface/documentation-images/discussions/305

**Review by gante — APPROVED** [review]
🔥 

@aymeric-roucher I'm assuming you want to expand the current PR to include the image added [here](https://huggingface.co/datasets/huggingface/documentation-images/discussions/305/files)?

**Comment by aymeric-roucher** [comment]
@gante I just amended the commit to include the image!

**Comment by aymeric-roucher** [comment]
It's ok to merge on my side @gante !

**Pull request merged**
