### PR TITLE
make `p_mask` a numpy array before passing to `select_starts_ends`

### PR DESCRIPTION
**Pull request by faaany**
# What does this PR do?
The multimodal example in [this](https://huggingface.co/docs/transformers/en/pipeline_tutorial#multimodal-pipeline) tutorial fails
```bash
from transformers import pipeline

vqa = pipeline(model="impira/layoutlm-document-qa")
output = vqa(
    image="https://huggingface.co/spaces/impira/docquery/resolve/2359223c1837a7587402bda0f2643382a6eefeab/invoice.png",
    question="What is the invoice number?",
)
output[0]["score"] = round(output[0]["score"], 3)
print(output)
```
```bash
Traceback (most recent call last):
  File "/workspace/DOC/tutorials.py", line 4, in <module>
    output = vqa(
  File "/workspace/transformers/src/transformers/pipelines/document_question_answering.py", line 271, in __call__
    return super().__call__(inputs, **kwargs)
  File "/workspace/transformers/src/transformers/pipelines/base.py", line 1247, in __call__
    return next(
  File "/workspace/transformers/src/transformers/pipelines/pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
  File "/workspace/transformers/src/transformers/pipelines/document_question_answering.py", line 448, in postprocess
    answers = self.postprocess_extractive_qa(model_outputs, top_k=top_k, **kwargs)
  File "/workspace/transformers/src/transformers/pipelines/document_question_answering.py", line 477, in postprocess_extractive_qa
    starts, ends, scores, min_null_score = select_starts_ends(
  File "/workspace/transformers/src/transformers/pipelines/question_answering.py", line 121, in select_starts_ends
    undesired_tokens = np.abs(p_mask.numpy() - 1)
AttributeError: 'list' object has no attribute 'numpy'

```
This PR fixes this.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Hi @faaany, thanks for digging into this! 

Instead of needing to do `np.array` conversions, we could instead construct a [numpy array directly here](https://github.com/huggingface/transformers/blob/fe008d6ebea1f5770b740991daeefd9322fa434a/src/transformers/pipelines/document_question_answering.py#L381) and just remove the `.numpy` cast

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by amyeroberts** [comment]
@faaany Could you rebase on main to include upstream changes? This should resolve the failing quality tests. 

There's some failing pipeline tests related to this change which will need to be resolved before we can merged.

**Comment by faaany** [comment]
> @faaany Could you rebase on main to include upstream changes? This should resolve the failing quality tests.
> 
> There's some failing pipeline tests related to this change which will need to be resolved before we can merged.

done

**Comment by amyeroberts** [comment]
Thanks again, @faaany!

**Pull request merged**
