### PR TITLE
FIX [`Generation`] Fix some issues when running the MaxLength criteria on CPU

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

Hey @zucchini-nlp @gante

In TRL we do have a class that call `generate` with `MaxLengthCriteria` and running the CI on main seems to cause some issues after https://github.com/huggingface/transformers/pull/29116 😱 
Not sure how to repro apart from running the failing CI and I did not flagged anything alarming outside my CI but to be on the safe zone I propose to init the `torch.full` tensor in bool directly, I assume it's fine according to the type hint

Here is the traceback:
```bash
self = [<transformers.generation.stopping_criteria.MaxLengthCriteria object at 0x7f652ccf8810>]
input_ids = tensor([[31373,   995, 19277],
        [31373,   995, 27455],
        [31373,   995,  4562],
        [31373,   995, 26964]])
scores = None, kwargs = {}, is_done = tensor([False, False, False, False])
criteria = <transformers.generation.stopping_criteria.MaxLengthCriteria object at 0x7f652ccf8810>

    @add_start_docstrings(STOPPING_CRITERIA_INPUTS_DOCSTRING)
    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, **kwargs) -> torch.BoolTensor:
        is_done = torch.full((input_ids.shape[0],), False, device=input_ids.device)
        for criteria in self:
>           is_done = is_done | criteria(input_ids, scores, **kwargs)
E           RuntimeError: "bitwise_or_cpu" not implemented for 'Float'
```

https://github.com/huggingface/trl/actions/runs/8058401333/job/22011132917

### CODE REVIEW

**Comment by younesbelkada** [comment]
cc @zucchini-nlp @gante what do you think about these changes ? 🙏

**Comment by zucchini-nlp** [comment]
Okay for me, but it's weird that max_length criteria was returning a float tensor

**Comment by younesbelkada** [comment]
@zucchini-nlp `torch.full(xxx)` returns a float tensor by default unless you don't explicitly cast it or init the tensor with the desired dtype. The thing I am not sure about is that why it didn't get flagged on other tests

**Review by gante — APPROVED** [review]
Perfect, thank you for having a look at the issue 🤗

**Review by ArthurZucker — APPROVED** [review]

**Pull request merged**
