### PR TITLE
fix test whisper with new max length

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
Fixes pipeline test after `max_length` update 
@ydshieh

### CODE REVIEW

**Comment by ydshieh** [comment]
Could you link the Hub PR that is related?

**Comment by ydshieh** [comment]
It seems the checkpoint involved is `openai/whisper-tiny.en` which is also used in other test methods. Could you confirm the other tests also pass after that Hub PR?

**Comment by ArthurZucker** [comment]
The `pytorch` tests all pass, 3 `TF` tests fails for now. 
Only the `config.max_length` was changed so should not have a lot of impact.

**Review by ydshieh — APPROVED** [review]
Thanks!

**Pull request merged**
