### PR TITLE
Add a job to test doc building (for realsies this time)

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

This PR takes over from #14645 to do it properly this time, meaning:
- we don't rely on secrets anymore which doesn't work for pull-request
- we don't need the secrets as we are not pushing anywhere
- we actually checkout the content after the PR merge, and not just master 🤦

### CODE REVIEW

**Comment by LysandreJik** [comment]
Just rebased on `master` ans force-pushed.

**Comment by LysandreJik** [comment]
Checking that it fails as it's missing the `kenlm` dependency, which I will add right after I confirm it fails.

**Review by LysandreJik — APPROVED** [review]
Actually it seems that there's no need for it, so merging like that. Thanks a lot for your work @sgugger, will monitor the next few PRs to ensure everything works correctly.

**Comment by sgugger** [comment]
Yes the object and its docstings exist whether or not `kenlm` is installed.

**Pull request merged**
