### PR TITLE
Deprecate quanto and switch to optimum-quanto

### PR DESCRIPTION
**Pull request by MekkCyber**
# What does this PR do?
Deprecates the use of `is_quanto_available` after switching to `optimum-quanto` package instead

## Who can review ?
@SunMarc

### CODE REVIEW

**Review by SunMarc — APPROVED** [review]
Nice cleanup !

**Comment by SunMarc** [comment]
To merge a bit before the release

**Review by ruidazeng — APPROVED** [review]

**Review by ArthurZucker — APPROVED** [review]
release is soon

**Comment by ArthurZucker** [comment]
can you resolve the conflicts please?

**Pull request merged**
