### PR TITLE
Fix compatibility with 1.12

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

Fixes the scatter tests by installing torch_scatter wheels for PyTorch 1.12.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
We'll need a fix for all Wav2Vec2-like models it seems. Opened an issue here: https://github.com/pytorch/pytorch/issues/80569

**Comment by LysandreJik** [comment]
Should this be merged or closed @sgugger?

**Comment by sgugger** [comment]
We're still not supporting PyTorch 1.12, so this shouldn't be closed.

**Comment by ydshieh** [comment]
Good news: we can go for `torch 1.12.1`. But FYI:

`https://pytorch-geometric.com/whl/torch-1.12.1+cpu.html` page doesn't exist, so I keep it as `1.12.0`

**Review by sgugger — COMMENTED** [review]
LGTM, just added the `!=0.12.0` in the versions for torch.

**Review by LysandreJik — APPROVED** [review]
Yes, LGTM! Thanks @sgugger and @ydshieh

**Pull request merged**
