### PR TITLE
Created SECURITY.md

### PR DESCRIPTION
**Pull request by shettyvarshaa**
Created a Security Policy to enhance community profile of the repository and to prevent potential vulnerabilities

# What does this PR do?

Fixes #24627

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

Issue raised in the [forum](https://discuss.huggingface.co/t/security-policy/59844)

## Who can review?

CC : @stevhliu

### CODE REVIEW

**Review by stevhliu — COMMENTED** [review]
Instead of creating a new security doc (the first section looks like its copied from `CONTRIBUTING.MD`), I think we can just add a Security section in `CONTRIBUTING.MD`.

WDYT @ArthurZucker?

**Comment by shettyvarshaa** [comment]
Yes, I thought of adding handling bug into security policy which is also mentioned in contributing.md, but creating security doc will complete your community profile to meet the standards

[Screenshot of this repo's current community profile](https://github.com/huggingface/transformers/assets/112955692/869974bf-6dac-4e5c-8422-f52cd316ef71)

**Comment by ArthurZucker** [comment]
No strong opinion, but will ask internally to have guidance regarding the bounty hunting program rather than bug fixed in this!

**Comment by ArthurZucker** [comment]
https://github.com/huggingface/transformers/commit/15cd096288d369eb8b190432c04a588198d191a5 fixes this 😉  thanks for the tip 🤗

**Pull request closed without merging**
