### PR TITLE
Expose AutoModelForMaskGeneration

### PR DESCRIPTION
**Pull request by fxmarty**
As per title, with this PR `from transformers import AutoModelForMaskGeneration` works.

An alternative could be to remove `AutoModelForMaskGeneration` (as `AutoModel` already does the job), but currently for sam Hub metadata it is `AutoModelForMaskGeneration` that is used and not `AutoModel`: https://huggingface.co/datasets/huggingface/transformers-metadata/blob/main/pipeline_tags.json#L576

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Will defer to @ArthurZucker and @younesbelkada  here as I don't know why they didn't expose it in the first place.

**Review by ArthurZucker — APPROVED** [review]
I think we kept `AutoModel` for simplicity as we did with clap (also since it is the only model + the model is `SamModel` not `SamForMaskGeneration`. But fine with me!

**Comment by fxmarty** [comment]
Either way is fine for me - it's just to have consistency between the transformers Hub metadata and transformers. An either fix would be to just change the metadata, and remove the `AutoModelForMaskGeneration`.

**Comment by sgugger** [comment]
So which one do you want @ArthurZucker ? I'm fine either way.

**Comment by ArthurZucker** [comment]
Let's go with `AutoModelForMaskGeneration` 😉

**Pull request merged**
