### PR TITLE
Fix git model for generate with beam search.

### LINKED ISSUE #21070: GIT does not work with beam search
### System Info

- `transformers` version: 4.26.0.dev0
- Platform: Linux-5.4.143.bsk.7-amd64-x86_64-with-glibc2.31
- Python version: 3.9.2
- Huggingface_hub version: 0.11.1
- PyTorch version (GPU?): 1.13.1 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: YES
- Using distributed or parallel set-up in script?: NO

### Who can help?

@gante @ArthurZucker @younesbelkada 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Take the script from official doc (https://huggingface.co/docs/transformers/main/model_doc/git#transformers.GitForCausalLM)

Add `num_beams=3`. Git model will report error.

```python
from transformers import AutoProcessor, AutoModelForCausalLM
import requests
from PIL import Image

processor = AutoProcessor.from_pretrained("microsoft/git-base-coco")
model = AutoModelForCausalLM.from_pretrained("microsoft/git-base-coco")

url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)

pixel_values = processor(images=image, return_tensors="pt").pixel_values

generated_ids = model.generate(pixel_values=pixel_values, max_length=50, num_beams=3)
generated_caption = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
print(generated_caption)
```

### Expected behavior

GIT model should work with beam search.

### PR DESCRIPTION
**Pull request by PeterL1n**
# What does this PR do?

Fixes #21070

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @younesbelkada @gante

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Hey, there seems to be an issue with the Circle CI. Will ping @sgugger for this. 
Otherwise looks good, but can you add the error you are getting on your issue?

**Comment by sgugger** [comment]
It seems there is an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

**Comment by sgugger** [comment]
Thanks! Can you now run `make style` to fix the test failure you see on the CI?

**Review by gante — COMMENTED** [review]
The fix makes total sense 👍 

The problem shouldn't have appeared in the first place, we should have added a beam search test (which would have quickly raised the issue). Can you please add a beam search test to this PR, to ensure we don't regress? (e.g. a test like [this one](https://github.com/huggingface/transformers/blob/05b8e25fffd61feecb21928578ad39e63af21b4f/tests/models/git/test_modeling_git.py#L419), but with beam search)

**Review by NielsRogge — APPROVED** [review]
Thanks a lot for fixing! 

This might also fix #21087. We should probably also add a test for batched generation.

If possible, could you add such a test? Otherwise, I can do it.

**Comment by PeterL1n** [comment]
@NielsRogge Please help adding the test. I am having limited capacity here.

**Review by gante — APPROVED** [review]
👍

**Review by sgugger — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
