### PR TITLE
Add RemBERT ONNX config

### PR DESCRIPTION
**Pull request by hchings**
# What does this PR do?
Add RemBERT ONNX config  (part of https://github.com/huggingface/transformers/issues/16308)

The max absolute difference between reference model and ONNX exported model is around `2e-05` in testings. I learned from other PRs that this discrepancy is within an acceptable range so I loosen the default atol. 

Slow tests are passed (`RUN_SLOW=1 pytest tests/onnx/test_onnx_v2.py -k "rembert"`).

I'm new to contributing to Transformers. If anyone can help me understand what is lacking, it would be appreciated!

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@lewtun & @ChainYo for ONNX and @Iwontbecreative for RemBERT.

### CODE REVIEW

**Review by chainyo — CHANGES_REQUESTED** [review]
Hi @hchings, the PR looks excellent! Did you try to run tests locally?

```
RUN_SLOW=1 pytest tests/onnx/test_onnx_v2.py -k "rembert"
```

Could you also remove the `Fixes #...` before the link to the ONNX issue to avoid an auto-close from GitHub? Thanks a lot for your contribution!

**Comment by hchings** [comment]
> Hi @hchings, the PR looks excellent! Did you try to run tests locally?
> 
> ```
> RUN_SLOW=1 pytest tests/onnx/test_onnx_v2.py -k "rembert"
> ```
> 
> Could you also remove the `Fixes #...` before the link to the ONNX issue to avoid an auto-close from GitHub? Thanks a lot for your contribution!

Yes, slow tests are passed for PyTorch locally. Should we add TensorFlow tests as well? My understanding is TF tests are needed only when TF has parity with PyTorch implementations. But correct me if I'm wrong.

**Review by chainyo — APPROVED** [review]
Ok looks good. Let's see wait on @lewtun.

**Review by sgugger — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
