### PR TITLE
Update docs to explain disabling callbacks using report_to

### LINKED ISSUE #26036: Option to disable CodeCarbon
### Feature request

- Allow disabling of CodeCarbon reporting, even when it's installed

### Motivation

I'm running code using the Trainer class across several nodes in an HPC environment using SLURM. It seems to automatically [use the CodeCarbon callback](https://huggingface.co/docs/transformers/v4.33.0/en/main_classes/callback#transformers.integrations.CodeCarbonCallback), but unfortunately doesn't work correctly in my multi-node environment and floods my log files with hundreds of distracting messages (mentioned earlier in https://github.com/mlco2/codecarbon/issues/252).

image

### Your contribution

I'd be happy to contribute and/or open a PR, given some guidance about where to start.

### PR DESCRIPTION
**Pull request by bgub**
# What does this PR do?

Fixes #26036. I added clarification to the Callback documentation page explaining how to "turn off" default callbacks using `TrainerArguments.report_to`.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
    - https://github.com/huggingface/transformers/issues/26036#issuecomment-1717603016
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerzr @pacman100

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Thanks looks good to me

**Review by muellerzr — APPROVED** [review]
Thanks! This is great!

As part of this, can we update https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L2385-L2388 to basically be a repeat of https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L522-L526? Otherwise LG2M as well :)

**Comment by nebrelbug** [comment]
@muellerzr sure! Just pushed that change.

**Review by muellerzr — APPROVED** [review]
Phenomenal! Good to go on my side then

**Pull request merged**
