### PR TITLE
Renamed `nlp` variables #9455

### PR DESCRIPTION
**Pull request by terrenceedmonds**
* Give better names to pipeline variables named nlp

* This was desired because nlp was not a descriptive variable name 

Fixes # 9455

@Narsil , @sgugger

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks a lot for tackling this. I think I slightly prefer `unmasker` over `unmask` if you want to do the replace, but I can live with `unmask` if you feel strongly about it.

One thing before we can merge, could you solve the conflicts with the two files that were changed since then (this will also fix the failing tests) and run `make style` to make sure the code-formatting is done properly?

**Comment by terrenceedmonds** [comment]
I can change `unmask` to `unmasker`. And I'll go back and take care of the merge conflicts and `make style` .

**Comment by sgugger** [comment]
I think your rebase went wrong as the diff as suddenly become unreadable. Could you close this PR and open a new one from your branch? Don't hesitate to tag me on it.

**Comment by sgugger** [comment]
Hi @terrenceedmonds I don't think you ever opened a new clean PR from your branch (might need a new rebase first since it's been a while). You had done all the work for this issue so it would be great to merge it!

**Pull request closed without merging**
