### PR TITLE
Fix PPLM

### PR DESCRIPTION
**Pull request by chutaklee**
# What does this PR do?

API changes break PPLM example, this PR should fix it. However I haven't test it on 'run_pplm_discrim_train.py'.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

### CODE REVIEW

**Comment by LysandreJik** [comment]
PPLM is unfortunately not maintained anymore. The fix would be to pin the `transformers` version in the PPLM README.

**Comment by julien-c** [comment]
pinging @w4nderlust and @mimosavvy just in case

**Comment by w4nderlust** [comment]
This looks good to me, I believe the return of dict (very welcome change by the way) from the model should be the only thing breaking the pplm code, right?

**Comment by chutaklee** [comment]
> This looks good to me, I believe the return of dict (very welcome change by the way) from the model should be the only thing breaking the pplm code, right?

Yeah and the named argument of model `past_key_values`. I have no issue running the provided example command in [here]( https://github.com/huggingface/transformers/tree/master/examples/text-generation/pplm) and `python run_pplm_discrim_train.py --dataset SST --epochs 1 --batch_size 8`.

**Review by patrickvonplaten — APPROVED** [review]
Thanks a lot!

**Comment by patrickvonplaten** [comment]
Can you run `make style` to  fix the code quality check? Then we should be good for merge :-)

**Comment by w4nderlust** [comment]
Much appreciated!

**Pull request merged**
