### PR TITLE
Fixed inconsistency in several fast tokenizers

### LINKED ISSUE #26123: Inconsistency in BertFastTokenizer
### System Info

- `transformers` version: 4.31.0
- Platform: Linux-4.18.0-425.19.2.el8_7.x86_64-x86_64-with-glibc2.2.5
- Python version: 3.8.6
- Huggingface_hub version: 0.16.4
- Safetensors version: 0.3.1
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- Tensorflow version (GPU?): 2.12.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?:  No

### Who can help?

@ArthurZucker

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Program to reproduce:

from transformers import BertTokenizer, BertTokenizerFast

A = [1, 2, 3]
B = []

tokenizer = BertTokenizer.from_pretrained("prajjwal1/bert-tiny")
fast_tokenizer = BertTokenizerFast.from_pretrained("prajjwal1/bert-tiny")

X = tokenizer.build_inputs_with_special_tokens(A, B)
Y = fast_tokenizer.build_inputs_with_special_tokens(A, B)

print(X) --> [101, 1, 2, 3, 102, 102]
print(Y) --> [101, 1, 2, 3, 102]

### Expected behavior

X == Y

### PR DESCRIPTION
**Pull request by Towdo**
Fixed case where behavior of BertTokenizer and BertTokenizerFast is different.
An empty list will be evaluated to `False` but not to `is None`.

(I mistakenly closed my first merge request)

Fixes #26123

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Thanks a lot for these changes! Let's add a small test in the test_tokenization_common 😉

**Comment by Towdo** [comment]
> Thanks a lot for these changes! Let's add a small test in the test_tokenization_common 😉

I changed the test_build_inputs_with_special_tokens to test this edge case :)

**Comment by ArthurZucker** [comment]
Thanks 😉

**Review by ArthurZucker — APPROVED** [review]
Very good thanks, I would just like 1 hard coded expected value, otherwise if both are broken we are not testing anything! Thanks for the fix

**Comment by Towdo** [comment]
> Very good thanks, I would just like 1 hard coded expected value, otherwise if both are broken we are not testing anything! Thanks for the fix

Can you give me some guidance on how to do this?
Because the behaviour differs from tokenizer to tokenizer, I can't/shouldn't do it in test_tokenization_common, right?
So instead I hard code one test in each test_tokenization_<tokenizer>?

**Comment by ArthurZucker** [comment]
Oups my bad on this one! 
It's alright like this 😉 I'll merge

**Pull request merged**
