### PR TITLE
Make sure code blocks are indented with four spaces

### PR DESCRIPTION
**Pull request by sgugger**
# What does this PR do?

In the documentation, many code blocks are indented with two or three spaces instead of 4. This PR enforces the use of 4 by:
- replacing indents of less than 4 by 4 in `make style`/`make fixup`
- checking there is no indent less than 4 in code blocks during `make quality`

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
You really do make scripts for everything :)

**Review by stas00 — APPROVED** [review]
Awesome work, @sgugger!

Though it's missing a lot of cases, e.g. `docs/source/main_classes/trainer.rst` has a ton of indent=3 cases that it missed. e.g. deepspeed's Installation section, but many more 

```

To make a local build for DeepSpeed:

.. code-block:: bash

   git clone https://github.com/microsoft/DeepSpeed/
   cd DeepSpeed
   rm -rf build
   TORCH_CUDA_ARCH_LIST="6.1;8.6" DS_BUILD_OPS=1 pip install . \
   --global-option="build_ext" --global-option="-j8" --no-cache -v \
   --disable-pip-version-check 2>&1 | tee build.log

```

**Comment by sgugger** [comment]
Ah, I don't match the `.. code-block:: xxx`, thanks for pointing that out!

**Comment by stas00** [comment]
OK, the next problem is the one I was concerned about in the first place (which is why i didn't offer a perl one liner). Your fixing code isn't shifting the whole block, but only the outside lines.

**Comment by sgugger** [comment]
That's too hard to fix and will result in other problems (what about bash commands that have different indents with the \?). So I will remove the automatic fix and just put a hard error the user will have to manually fix.

**Comment by stas00** [comment]
> That's too hard to fix and will result in other problems (what about bash commands that have different indents with the ?). 

Bash has no indentation issues. Only python does AFAIK.

I think it's about finding the difference in the required whitespace, and applying this change to the whole block should make it work.

> So I will remove the automatic fix and just put a hard error the user will have to manually fix.

Sure, that would work just fine.

Thank you.

**Comment by sgugger** [comment]
Ok, I have something that can do the whole block, but since this PR already badly treated some parts, I need to go back from a fresh master, so closing this one.

**Pull request closed without merging**
