### PR TITLE
Add AzureML in integrations via dedicated callback 

### PR DESCRIPTION
**Pull request by davidefiocco**
# What does this PR do?

I propose this PR to allow transformers to call AzureML logging using https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.run(class)?view=azure-ml-py

The intended behaviour is to enable `transformers` users to track metrics in the AzureML UI in this fashion

image

Contributors to https://github.com/microsoft/AzureML-BERT and folks @microsoft may well come up with a better implementation though!

I am glad to improve the following if reviewers like the idea, and update docs and tests if needed.
@reviewers feel free to add any suggestions as my contributions to transformers have been very limited so far :)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Yes, check for detais https://discuss.huggingface.co/t/how-to-integrate-an-azuremlcallback-for-logging-in-azure/1713/4
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@julien-c is aware of this and @sgugger participated in the thread on forums above and implemented callbacks with https://github.com/huggingface/transformers/pull/7596

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Looks great!
There is just a conflict to solve (probably with MLFlow merged this morning) and the CI tools to make happy (your import might need some comment to be ignored by black/isort).

**Comment by davidefiocco** [comment]
Code changes pass tests @sgugger ! Thanks @alvarobartt for having a look at those also.

I guess I need to take care of  docs/source/main_classes/callback.rst as well to complete the checklist though?

**Review by alvarobartt — APPROVED** [review]
Everything keeps the standards and passes all the checks (black, isort) 👍🏻

**Comment by sgugger** [comment]
Yes, if you could add a line to the rst file, that would be great!

**Comment by sgugger** [comment]
You might need to rebase to have the latest script for doc formatting, which should do everything to make the CI happy with just `make style`. Let me know if you need help.

**Comment by davidefiocco** [comment]
Sorry for the somewhat messy hacktoberfest @sgugger ! 
I wasn't so aware of rst idiosyncrasies so I struggled a bit. Should be in order now!

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks!

As you mention hacktoberfest, we had not thought of adding the label but we just did. I hope this PR will be counted towards your goal!

**Pull request merged**
