### PR TITLE
added farsi lang

### PR DESCRIPTION
**Pull request by mzamini92**
# What does this PR do?

Added Farsi (fa) to the docs. I have translated `_toctree.yml` and `accelerate.mdx` and `add_new_pipeline.mdx`. the rest also will be translated soon. I will make this pull request so others also can contribute and make this process faster. 

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@sgugger

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Please only add the translated file in the new folder.

**Comment by mzamini92** [comment]
> Please only add the translated file in the new folder.

only the translated files are now in fa folder. the rest have been removed.

**Review by sgugger — COMMENTED** [review]
Thanks a lot! One last comment on the `add_new_model` file.

**Comment by mzamini92** [comment]
> Thanks a lot! One last comment on the `add_new_model` file.

@sgugger I'm sorry I didn't quite get what you mean? can you please tell me more to do it right away? appreciate it.

**Comment by sgugger** [comment]
You have translated half the file only. Maybe leave it out of this PR and add it in a new PR when you're fully done?

**Pull request closed without merging**
