### PR TITLE
fix the deepspeed tests

### PR DESCRIPTION
**Pull request by pacman100**
# What does this PR do?
1. Post the https://github.com/huggingface/transformers/pull/25863, a test needs fixing. This PR does that

### CODE REVIEW

**Review by lawchingman — APPROVED** [review]

**Review by muellerzr — APPROVED** [review]
Thanks! Makes sense since this now works. cc @amyeroberts :)

**Comment by amyeroberts** [comment]
Change itself look OK. 

Just for my own understanding, does this mean the trainer is changing variables - `a` in this instance - in its local scope, even if not explicitly passed to the trainer or set in any config?

**Comment by pacman100** [comment]
> Just for my own understanding, does this mean the trainer is changing variables - a in this instance - in its local scope, even if not explicitly passed to the trainer or set in any config?

The default value of the parameter is 0 and post the training the value should change, the latest commit makes it explicit.

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
