### PR TITLE
clean up PT <=> TF conversion

### PR DESCRIPTION
**Pull request by thomwolf**
Cleaning up PT <=> TF conversion method.

cc @VictorSanh

### CODE REVIEW

**Comment by VictorSanh** [comment]
Cool!

**Comment by sivakumarch** [comment]
@thomwolf and @VictorSanh - could you please look into #2088 (PT to TF)? tagging you guys in this thread as it seems relevant, please let me know otherwise. 

Thanks

**Comment by thomwolf** [comment]
This thread is not relevant but I'll give a look at your issue soon.

**Comment by sivakumarch** [comment]
thanks!

**Pull request merged**
