### PR TITLE
revert temporary addition to test next version of CLIPTokenizerFast

### PR DESCRIPTION
**Pull request by SaulLu**
# What does this PR do?

This PR aims to change the repository used to test `CLIPTokenizerFast`.

As part of the `CLIPTokenizerFast` bug fix in this PR #15067, instead of testing the tokenizer of the repo [openai/clip-vit-base-patch32](https://huggingface.co/openai/clip-vit-base-patch32) we had made a temporary change to test the one in [SaulLu/clip-vit-base-patch32](https://huggingface.co/SaulLu/clip-vit-base-patch32) that had the new version of the `tokenizer.json` file. 

As discussed, the `tokenizer.json` file should be transferred from the [SaulLu/clip-vit-base-patch32](https://huggingface.co/SaulLu/clip-vit-base-patch32) repo to the [openai/clip-vit-base-patch32](https://huggingface.co/openai/clip-vit-base-patch32) repo. Once this is done the testing of this PR should pass.

For the record, it was discussed to introduce file versioning and therefore to add a versioned file `tokenizer_vxxx.json` in the [openai/clip-vit-base-patch32](https://huggingface.co/openai/clip-vit-base-patch32)  repo. Following the last exchanges this solution has been put aside because 1) the fast version of the tokenizer is not used in `CLIPFeatureExtractor` and 2) it is a bug fix.

**Edit:** the new `ŧokenizer.json` have been added to [openai/clip-vit-base-patch32](https://huggingface.co/openai/clip-vit-base-patch32)  and now all the tests pass! 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by patil-suraj — APPROVED** [review]
Thanks a lot for taking care of this, LGTM!

**Review by sgugger — APPROVED** [review]
Good to merge when ready!

**Comment by patil-suraj** [comment]
@SaulLu We should also update this for other CLIP checkpoints too, no ?
https://huggingface.co/openai/clip-vit-base-patch16
https://huggingface.co/openai/clip-vit-large-patch14

**Comment by SaulLu** [comment]
Yes! I think we need to check all the tokenizer that are supposed to be of `ClipTokenizer` type on the Hub too

**Comment by SaulLu** [comment]
@patil-suraj , I've added the new `tokenizer.json` file to https://huggingface.co/openai/clip-vit-base-patch16 and to https://huggingface.co/openai/clip-vit-large-patch14 :slightly_smiling_face:

**Comment by patil-suraj** [comment]
Thanks a lot @SaulLu !

**Pull request merged**
