### PR TITLE
Fix offload disk for loading derivated model checkpoint into base model

### LINKED ISSUE #27199: Failed to load Llama2 with customized device_map
### System Info

- Huggingface_hub version: 0.17.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.0
- Accelerate config:    not found
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Tensorflow version (GPU?): 2.13.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@ArthurZucker;  @younesbelkada

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Load Llama2 on a PC with 4060(8GB) and 32GB RAM
2. Passing device_map to AutoModel.from_pretrained()
3. Using "auto" and GPU memory + RAM is not enough, or just manually locating some layers on the disk
4. Receive the following info:
```
 "E:\anaconda\envs\transformers\lib\site-packages\transformers\modeling_utils.py", line 3633, in _load_pretrained_model
    offload_index = {
  File "E:\anaconda\envs\transformers\lib\site-packages\transformers\modeling_utils.py", line 3636, in <dictcomp>
    if param_device_map[p] == "disk"
  KeyError: 'lm_head.weight'
```

I have checked it and found there were no items in para_device_map, which is created by `expand_device_map()` in line 3621.
```
def expand_device_map(device_map, param_names):
    """
    Expand a device map to return the correspondance parameter name to device.
    """
    new_device_map = {}
    for module, device in device_map.items():
        new_device_map.update({p: device for p in param_names if p == module or p.startswith(f"{module}.")})
    return new_device_map
```
**The key is that the update func failed to extract p and device:** All the param_names have "model" as prefix and the lm_head was not included.
```
device_map:
{'embed_tokens': 'cpu', 'layers.0': 0, 'layers.1': 0, 'layers.2': 0, 'layers.3': 0, 'layers.4': 'cpu', 'layers.5': 'cpu', 'layers.6': 'cpu', 'layers.7': 'cpu', 'layers.8': 'cpu', 'layers.9': 'cpu', 'layers.10': 'cpu', 'layers.11': 'cpu', 'layers.12': 'cpu', 'layers.13': 'cpu', 'layers.14': 'cpu', 'layers.15': 'cpu', 'layers.16': 'cpu', 'layers.17': 'cpu', 'layers.18': 'cpu', 'layers.19': 'cpu', 'layers.20': 'cpu', 'layers.21': 'cpu', 'layers.22': 'cpu', 'layers.23': 'cpu', 'layers.24': 'cpu', 'layers.25': 'disk', 'layers.26': 'disk', 'layers.27': 'disk', 'layers.28': 'disk', 'layers.29': 'disk', 'layers.30': 'disk', 'layers.31': 'disk', 'norm': 'cpu'}

para_names:
['lm_head.weight', 'model.embed_tokens.weight', 'model.layers.0.input_layernorm.weight', 'model.layers.0.mlp.down_proj.weight', 'model.layers.0.mlp.gate_proj.weight', 'model.layers.0.mlp.up_proj.weight', 'model.layers.0.post_attention_layernorm.weight', 'model.layers.0.self_attn.k_proj.weight', 'model.layers.0.self_attn.o_proj.weight', 'model.layers.0.self_attn.q_proj.weight', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.v_proj.weight', ...}
```

### Expected behavior

I wonder if there are some methods to avoid it

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR
This PR fixes #27199. It was not possible load weights from a derived model into the base model when we are offloading parameters to the disk +  safetensors. The issue was that we were not able to create the right `offload_index` because the weights didn't match. 

Example : 

```py
from transformers import AutoModel
device_map = {'embed_tokens': 0, 'layers.0': "disk", 'layers.1': 0, 'layers.2': 0, 'layers.3': 0, 'layers.4': 0, 'layers.5': 0, 'layers.6': 0, 'layers.7': 1, 'layers.8': 1, 'layers.9': 1, 'layers.10': 1, 'layers.11': 1, 'layers.12': 1, 'layers.13': 1, 'layers.14': 1, 'layers.15': 1, 'layers.16': 2, 'layers.17': 2, 'layers.18': 2, 'layers.19': 2, 'layers.20': 2, 'layers.21': 2, 'layers.22': 2, 'layers.23': 2, 'layers.24': 2, 'layers.25': 3, 'layers.26': 3, 'layers.27': 3, 'layers.28': 3, 'layers.29': 3, 'layers.30': 3, 'layers.31': 3, 'norm': 3}
model = AutoModel.from_pretrained("meta-llama/Llama-2-7b-hf", device_map = device_map, use_safetensors=True)
```

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Thanks for adding this! 

Could you add relevant tests which would have failed without this PR and now pass?

**Comment by SunMarc** [comment]
Thanks for the review @amyeroberts ! Any idea where I should add this test ? I don't think we want to test this for all our models but maybe just for one ?

**Comment by amyeroberts** [comment]
@SunMarc Agreed - just for one model should be enough. I'd suggest putting them in [test_modeling_utils.py](https://github.com/huggingface/transformers/blob/88832c01c8a962b653874c4ce4ed8df5783ac5cd/tests/test_modeling_utils.py#L4)

**Review by amyeroberts — APPROVED** [review]
Thanks for adding!

**Pull request merged**
