### PR TITLE
Generate: post-generate config doctest fix

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

Fixes doctests that were broken as a result of the `generation_config` PR merge.

Note: the failing pipeline test was fixing by adding a missing field to `gpt2`'s `generate_config.json` (which was created before these recent `generation_config` changes). See [this hub commit](https://huggingface.co/gpt2/commit/e7da7f221d5bf496a48136c0cd264e630fe9fcc8).

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
I am new to this generation config game, but it looks reasonable to me. Thank you @gante

**Comment by ydshieh** [comment]
Just a question, so if users do things in the old way like

```
model.config.pad_token_id = model.config.eos_token_id
```
they might get different results before/after the generation config PR ..?

**Comment by gante** [comment]
> Just a question, so if users do things in the old way like
> 
> ```
> model.config.pad_token_id = model.config.eos_token_id
> ```
> 
> they might get different results before/after the generation config PR ..?

`generate()` supports control from ad hoc model config changes (it has an extra check and handles differences [here](https://github.com/huggingface/transformers/blob/26dd041c6e45379141302e2d293ab4cd9cf805d4/src/transformers/generation/utils.py#L1131)). It is deprecated and will be removed soon.

Individual generation methods do not have this check, so they are not supporting control from ad hoc model config changes. The doctests in `main` are failing for this reason. It means that fixing the doctests can be done in two ways:
1. Add the same check to all individual generation methods
2. [current implementation in the PR] Change the doctest itself

I decided to follow 2. since we are deprecating it soon anyways AND calling the methods directly is an advanced feature (users should not be relying on side effects on the model config to support advanced functionality, it's a recipe for disaster 👀 ). 

WDYT? (cc @sgugger)

**Review by LysandreJik — APPROVED** [review]
Thank you!

**Comment by sgugger** [comment]
Agreed with option 2!

**Pull request merged**
