### PR TITLE
Fix the behaviour of DefaultArgumentHandler (removing it).

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

This PR will attempt to fix some clearly wrong error message in what I think should be
valid calls.

The decision to remove `DefaultArgumentHandler` comes from the fact that the real usage actually lied for only QuestionAnswering and ZeroShot which already have their own handler.

Having real python handle arguments and errors seems way more predictable and remove `*args` from function
signatures makes code more readable I think. We need to be very careful though as arguments number need to be in sync
otherwise errors can happen (This is due to mix of positional arguments, named positional arguments and generic keyword arguments being used together).

For the reader, the call order of functions is something like

```python
SpecificPipeline.__call__(myargument1, myargument2, **kwargs)
# Which calls
Pipeline.__call__(*args, **kwargs)
# Which in turn calls
SpecificPipeline._parse_and_tokenize(my_argument1, my_argument2, **kwargs)
```

Smaller changes for QoL where I tried to normalize inputs as early on as possible in the call stack (i.e SpecificPipeline.__call__) so we don't have to do it over and over.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to the it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors which may be interested in your PR.

@mfuntowicz 
@sgugger

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Thanks @Narsil, I think this makes the code clearer as well. Do you have an example of an error and what would be the stacktrace before and after the change? Thanks!

**Comment by Narsil** [comment]
Sure:

```python
from transformers import pipeline

pipe = pipeline(task='fill-mask', model='bert-base-uncased')
pipe("I am a real [MASK]", targets=["superhero", "legend"])
# [{'sequence': '[CLS] i am a real superhero [SEP]',
#  'score': 1.21390044682812e-07,
#  'token': 16251,
#  'token_str': 'superhero'},
# {'sequence': '[CLS] i am a real legend [SEP]',
#  'score': 4.292454747201191e-08,
#  'token': 5722,
#  'token_str': 'legend'}]

pipe("I am a real [MASK]", otherarg=True)
ValueError                                Traceback (most recent call last)
<ipython-input-13-4784fa412984> in <module>
----> 1 pipe("I am a real [MASK]", otherarg=True)

~/.pyenv/versions/3.8.5/lib/python3.8/site-packages/transformers/pipelines.py in __call__(self, targets, *args, **kwargs)
   1201             - **token** (:obj:`str`) -- The predicted token (to replace the masked one).
   1202         """
-> 1203         inputs = self._parse_and_tokenize(*args, **kwargs)
   1204         outputs = self._forward(inputs, return_tensors=True)
   1205 

~/.pyenv/versions/3.8.5/lib/python3.8/site-packages/transformers/pipelines.py in _parse_and_tokenize(self, padding, add_special_tokens, *args, **kwargs)
    625         """
    626         # Parse arguments
--> 627         inputs = self._args_parser(*args, **kwargs)
    628         inputs = self.tokenizer(
    629             inputs,

~/.pyenv/versions/3.8.5/lib/python3.8/site-packages/transformers/pipelines.py in __call__(self, *args, **kwargs)
    179     def __call__(self, *args, **kwargs):
    180         if len(kwargs) > 0 and len(args) > 0:
--> 181             raise ValueError("Pipeline cannot handle mixed args and kwargs")
    182 
    183         if len(kwargs) > 0:

ValueError: Pipeline cannot handle mixed args and kwargs

```

**Comment by Narsil** [comment]
Should I merge ?

**Review by thomwolf — APPROVED** [review]
Nice!

Soon we should start splitting the `pipeline.py` file in several files imo (maybe when we change the internal organization to add a level of directories).

**Comment by Narsil** [comment]
I could start that.

**Comment by thomwolf** [comment]
(not in this PR :)

**Pull request merged**
