### PR TITLE
Add type hints for GPTNeo PyTorch

### PR DESCRIPTION
**Pull request by Tegzes**
Adding type hints for forward methods in user-facing class for GPTNeo (PyTorch) as mentioned in #16059  

@Rocketknight1

### CODE REVIEW

**Review by patil-suraj — APPROVED** [review]
Thanks for adding these type hints !

**Comment by patil-suraj** [comment]
If you run `make style` from the root of the repo and push again then it should fix the failing the tests.

**Comment by patil-suraj** [comment]
@Tegzes if you change the type for `past_key_values` from `List` to `Tuple` we should be good to merge :)

**Comment by Tegzes** [comment]
Awesome, I'm making the changes right now

**Pull request merged**
