### PR TITLE
fix: typo spelling grammar

### PR DESCRIPTION
**Pull request by slowy07**
# What does this PR do?
fix typo spelling grammar, and replace to correct words with reference from [merriam webster](merriam-webster.com) and [wiktionary](https://www.wiktionary.org/)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

 If you know how to use git blame, that is the easiest way, otherwise, here is a rough guide of **who to tag**.
 Please tag fewer than 3 people.

Documentation: @sgugger

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks a lot!

**Comment by LysandreJik** [comment]
Could you run `make fixup` at the root of your `transformers` clone to fix the code quality issues? Thank you!

**Comment by slowy07** [comment]
thanks sir @LysandreJik , how can i do ??

**Comment by LysandreJik** [comment]
I guess you have clones `transformers` the following way:
```
git clone https://github.com/huggingface/transformers
```
You can `cd` in the directory:
```
cd transformers
```
install the code quality tools:
```
pip install -e ".[quality]"
```
and run the command:
```
make fixup
```

If there's an error it can solve by itself, it will do so; if an error cannot be solved programmatically, it will tell you so :)

Afterwards, you can commit the changes and push to your branch, the code quality issues should be fixed!

**Comment by slowy07** [comment]
make fixup and push on commit [c233be1](https://github.com/huggingface/transformers/pull/13212/commits/c233be17db7ecce48b54f1eb71070a1dee39d342)

**Review by sgugger — APPROVED** [review]
Thanks a lot for all the fixes!

**Comment by slowy07** [comment]
thank you sir @sgugger

**Pull request merged**
