### PR TITLE
Fix SpeechT5 `decoder_attention_mask` shape

### LINKED ISSUE #26598: [SpeechT5] Attention mask not changed according to decoder inputs
### System Info

- `transformers` version: 4.33.3
- Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.10
- Python version: 3.8.8
- Huggingface_hub version: 0.17.3
- Safetensors version: 0.3.3
- Accelerate version: not installed
- Accelerate config: not found
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sanchit-gandhi

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

The decoder inputs are changed to be shifted right by one, and interleaved by the reduction factor.
However, the attention mask to the decoder remains the same, which if we use a reduction_factor != 1 will result in a shape missmatch.

You can check the line I am referring to here:
https://github.com/huggingface/transformers/blob/2f3ea08a077ba3133fa8a604b22436cad250b055/src/transformers/models/speecht5/modeling_speecht5.py#L2733

### Expected behavior

The attention mask should have the same changes applied as the decoder input, resulting in the same shape, I believe.

### PR DESCRIPTION
**Pull request by ylacombe**
# What does this PR do?

 #26598 rightfully raised a warning when passing labels to `SpeechT5`. When it happens, a reduction factor is applied to the `labels` but not to the `decoder_attention_mask` that comes with it, resulting in a mismatch.

Fixes #26598

cc @amyeroberts @sanchit-gandhi

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing! 

Can you run the slow tests for the model to confirm everything passes before merging?

**Comment by ylacombe** [comment]
After running the slow tests, we have these two failing tests:
```
FAILED tests/models/speecht5/test_modeling_speecht5.py::SpeechT5ForTextToSpeechIntegrationTests::test_batch_generation - AssertionError: torch.Size([3, 264, 80]) != (3, 262, 80)
FAILED tests/models/speecht5/test_modeling_speecht5.py::SpeechT5ForTextToSpeechIntegrationTests::test_generation - AssertionError: torch.Size([226, 80]) != (230, 80)
```
This is most likely related to #25943, as the current PR only impacts output when `labels` are passed.

I'll deep dive into it

**Comment by amyeroberts** [comment]
@ylacombe Thanks for checking and reporting back!

**Review by sanchit-gandhi — APPROVED** [review]
Thanks for fixing! Should we add a test to confirm the downsampling is performed correctly now? (i.e. one forward pass with the reduction factor and an attention mask should suffice)

**Comment by sanchit-gandhi** [comment]
Would be great to finish this one and close https://github.com/huggingface/transformers/issues/26598!

**Comment by ylacombe** [comment]
Sorry for the long delay, I've added additional tests to make sure the forward pass works when passing `labels` and the attention mask !

The failed tests mentioned [here](https://github.com/huggingface/transformers/pull/28071#issuecomment-1858065107) now pass btw!

Could I have a final last check on the added tests ?

**Review by amyeroberts — APPROVED** [review]
Amazing - thanks for fixing!

**Pull request merged**
