### PR TITLE
[WIP] Add classification head for T5 and MT5

### PR DESCRIPTION
**Pull request by PhilipMay**
This is an experiment to add a classification head for T5 and MT5 models.
It uses the `T5EncoderModel` and `MT5EncoderModel` without the decoder part.

### CODE REVIEW

**Comment by PhilipMay** [comment]
@LysandreJik or @sgugger 
I am trying to add a classification head on top of the T5 and MT5 encoder models.
It works but the performance (metric) of my downstream tasks is very low compared to other models.
Could you maybe do a very quick code review on this PR please?

Maybe you find obvious bugs. 

Is the initialization maybe wrong for example?

I am adding a `SequenceSummary` head like XLNet is doing.
This has different values for `summary_type`.
I tried everything: `first`, `last`, `cls_index`. Noting realy works good.

**Comment by PhilipMay** [comment]
PS: T5 and MT5 do not have these `<s>` or `[CLS]` token...

**Comment by PhilipMay** [comment]
Hi @LysandreJik or @sgugger ,
I would be super happy if you could maybe give me some pointers here.

**Comment by sgugger** [comment]
Maybe @patrickvonplaten will have some ideas, but maybe it's just that those types of models are not really good for sequence classification.

**Comment by PhilipMay** [comment]
I think the tests fail because it does not manage to install some pip packages. Maybe fasttext....

**Comment by patrickvonplaten** [comment]
Hmm, T5 was really made so that every task (including classification tasks) are framed as a text2text task. I don't really see why one would use T5 over BERT for a "Encoder-only" classification task...Could you give a bit more detail on the motivation of this PR? :-) @PhilipMay

**Pull request closed without merging**
