### PR TITLE
Add Mamba2

### LINKED ISSUE #31204: Add Mamba2
### Feature request

Support of a new version of the mamba architecture. See paper @ https://arxiv.org/abs/2405.21060. Base code has been released in their repo https://github.com/state-spaces/mamba.

### Motivation

It's still very competitive in NLP (according to the benchmarks) but also a good chunk faster due to new parallelism mechanisms.

### Your contribution

Not sure, I could look into it but it's definitely a bigger undertaking :)

### PR DESCRIPTION
**Pull request by zzhhjjj**
# What does this PR do?

Fixes #31204  (issue)

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @ArthurZucker

**Comment by vasqu** [comment]
This doesn't look like `Mamba2` at all, just a copy-paste of `Jamba`. Is it meant to be a placeholder for now?

One can easily see it as mamba2 doesn't use attention (except for some ablation studies) and the core (trition) functions `mamba_chunk_scan_combined` and `mamba_split_conv1d_scan_combined` are not even imported. Not to be rude but what's the purpose behind this PR? :sweat_smile:

**Comment by Adibvafa** [comment]
@vasqu I agree. Do you wanna work on a PR together?

**Comment by vasqu** [comment]
@Adibvafa look into the issue #31204 , you can help me there or I can help here / a different PR if this is not being continued.

**Comment by ArthurZucker** [comment]
Feel free to open a PR and maybe leverage the new diff conversion! #30868

**Pull request closed without merging**
