### PR TITLE
Add model card creation snippet to example scripts

### PR DESCRIPTION
**Pull request by gchhablani**
# What does this PR do?

This PR adds model card creation in case the `push_to_hub` argument is not used.

@patrickvonplaten

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Looks good to me - thanks for the PR!

**Review by patrickvonplaten — APPROVED** [review]

**Review by sgugger — COMMENTED** [review]
That seems useful! Would you mind applying the same modification to all other examples using the `Trainer`? Thanks a lot!

**Review by sgugger — APPROVED** [review]

**Comment by gchhablani** [comment]
@sgugger Does this look fine? I went over the scripts in `pytorch` examples.

**Comment by sgugger** [comment]
That's great! Can you just run `make style` on your branch to take care of the quality issue?

**Review by patrickvonplaten — APPROVED** [review]
Thanks a lot @gchhablani !

**Pull request merged**
