### PR TITLE
[i18n-HI] Translated accelerate page to Hindi

### PR DESCRIPTION
**Pull request by karthik-script**
# What does this PR do?

Translated accelerate page to Hindi and updated the `_toctree.yml` file

Fixes # (issue) https://github.com/huggingface/transformers/issues/34441

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc:  @stevhliu  and @MKhalusova

### CODE REVIEW

**Comment by karthik-script** [comment]
Upon the successful implementation of this PR, I intend to increase my translation efforts. Thank you for your support.

**Review by stevhliu — COMMENTED** [review]
LGTM, thanks for your translation!

You'll also need to find someone who can review the translated content since I can't read Hindi! https://github.com/huggingface/transformers/issues/26787 is a good place to see if other community members are interested :)

**Review by kbdharun — COMMENTED** [review]
Thanks for your contribution, chiming in from https://github.com/tldr-pages/tldr/pull/14452. As a translator myself, I have a few technical suggestions for this page.

---

>You'll also need to find someone who can review the translated content since I can't read Hindi! https://github.com/huggingface/transformers/issues/26787 is a good place to see if other community members are interested :)

Hi, I have gone through the page. Overall it looks fine, I have made a few technical suggestions after this the PR should be GTG.

> [!NOTE]
> While I can read and understand Hindi, I am not a native speaker so feel free to get a second review if required.

**Review by kbdharun — APPROVED** [review]
LGTM

**Review by stevhliu — APPROVED** [review]
Great job and thanks again!

**Pull request merged**
