### PR TITLE
fix get_scheduler when name is warmup_stable_decay

### LINKED ISSUE #31085: get_wsd_schedule gets passed num_training_steps because not handled
getting:
```
TypeError: get_wsd_schedule() got an unexpected keyword argument 'num_training_steps'
```
because there's not a handling of ```WARMUP_STABLE_DECAY```, get_wsd_schedule gets passed default params.

https://github.com/huggingface/transformers/blob/a3c7b59e31710f76492146db1d87ba77e3ae265d/src/transformers/optimization.py#L547

### PR DESCRIPTION
**Pull request by zspo**
# What does this PR do?

fix #31085

I also add some cases for test.
iShot_2024-05-30_10 52 20

iShot_2024-05-30_10 52 52

@ArthurZucker and @amyeroberts

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing! 

LGTM, but would be good to have a second look from @SunMarc to confirm this is as expected

**Review by SunMarc — APPROVED** [review]
Make sense ! Thanks for fixing @zspo !

**Comment by MostHumble** [comment]
@SunMarc  this means that you'd have to pass, num_warmup_steps=num_warmup_steps, AND scheduler_specific_kwargs = {num_stable_steps,  num_decay_steps, num_cycles, min_lr_ratio} as they're required params, this can be confusing as all of them are specific to that scheduler

**Comment by zspo** [comment]
> @SunMarc this means that you'd have to pass, num_warmup_steps=num_warmup_steps, AND scheduler_specific_kwargs = {num_stable_steps, num_decay_steps, num_cycles, min_lr_ratio} as they're required params, this can be confusing as all of them are specific to that scheduler, I'm not sure why scheduler_specific_kwargs exists

I considered whether to put `num_warmup_steps` in `scheduler_specific_kwargs`. But this parameter appears in the function `get_scheduler` explicitly.

**Comment by SunMarc** [comment]
`scheduler_specific_kwargs` exists so that we don't have a `get_scheduler` with too many args + that are specific to only a few schedulers.

**Comment by MostHumble** [comment]
I see so it's juste two different styles clashing, thanks.

**Pull request merged**
