### PR TITLE
Re: Add Japanese RoBERTa Model

### PR DESCRIPTION
**Pull request by butsugiri**
I have re-created PR as CI does not seem to trigger as expected.

The original PR is #13065

### CODE REVIEW

**Comment by butsugiri** [comment]
@LysandreJik I hope that CI runs this time.
I will soon add missing documents 😄

**Comment by LysandreJik** [comment]
Hey @butsugiri! For some reason the tests still didn't run, but I could push a branch and open a PR from my personal fork with your commits here: https://github.com/huggingface/transformers/pull/14233

This triggered the tests and ran them on your latest commit which now shows here (yay!).

**Comment by butsugiri** [comment]
@LysandreJik Thank you for your help! I close this PR.

**Comment by butsugiri** [comment]
...or should I keep this open? Sorry that I am confused 😟 

I have just added documents and made few modification to address CI errors.

**Comment by LysandreJik** [comment]
Hey @butsugiri, it seems that most of the issues in the tests could be solved with a rebase on `master`. Could you do it? I'm happy to do it too, but I'll need you to invite me to your repository so that I have commit rights.

**Comment by butsugiri** [comment]
Hi, @LysandreJik . Thanks again for your message.
I have invited you to our fork repository with `write` access.
Since I am unfamiliar with rebase command, could you do it, please? Thanks!

**Comment by LysandreJik** [comment]
Thank you for the invitation! I have just rebased on `master`, and forced pushed your branch. Let's see if the tests succeed!

**Comment by LysandreJik** [comment]
There are a few tests failing, do you manage to see the output of these tests when clicking on "Details"? I believe it's mostly due to the `fugashi` missing installation. Would you like me to take a look at that issue as well, or would you like to take a stab at it? :)

**Comment by butsugiri** [comment]
Thanks for rebasing and pushing! I confirmed that I can see the failed CIs from "Details".
Regarding the missing `fugashi` installation: do you have any ideas for solving this issue?
If I understood correctly, it seems that similar JapaneseBERT Tokenizer is ignoring the test when `fugashi`  is unavailable. 
https://github.com/huggingface/transformers/blob/master/tests/test_tokenization_bert_japanese.py#L124-L127
However, I suppose that there may be a better way 🤔

**Comment by LysandreJik** [comment]
That's the favored way, and we can install fugashi in a run such as this one: https://github.com/huggingface/transformers/blob/master/.circleci/config.yml#L516

This fits perfectly, as this too is a custom tokenizer :)

**Comment by butsugiri** [comment]
I see that there is already a CI config for custom tokenizer 😄 
According to your link, pip install should be running with `ja` option, which includes the installation of `fugashi` https://github.com/huggingface/transformers/blob/master/setup.py#L234
Would you please take a look at fugashi installation failure?

**Comment by LysandreJik** [comment]
Let's see, I'm re-running the CI

**Comment by LysandreJik** [comment]
Tried to fix it here, will see: https://github.com/huggingface/transformers/pull/14233

**Comment by KoichiYasuoka** [comment]
`do_zenkaku=True` seems harmful when it is used with `[MASK]` or `<mask>` on `FillMaskPipeline`. How do you think @butsugiri ?

**Pull request closed without merging**
