### PR TITLE
[code quality] new make target that combines style and quality targets

### PR DESCRIPTION
**Pull request by stas00**
**edit**: this post has been edited to reflect the outcome of the discussion.

Any reason why we don't run `flake8` in `make style`? I find myself needing to run `make style` followed by `make quality` all the time, but I need the latter just for the last 2 checks. Since we have no control over the source code why bother with separating checking and fixing - let's just have one target that fixes and then performs the remaining checks, as we know the first two have been done already.

This PR suggests to create a new target `fixup` that combines the 2 separate fix and check functions into one efficient target, 

I will edit the docs if this change resonates with the team.

p.s. if it feels wrong to merge fixing and checking, can we add a 3rd target that is a merged one? `make best`

p.p.s. I know I can make my own alias, I love `make`!

### CODE REVIEW

**Comment by sshleifer** [comment]
I'm in favor. @sgugger @LysandreJik should this be a third target or should we just remove `make quality`?

**Comment by sgugger** [comment]
I like having a command that does the same check as the CI without changing anything so I'd leave `make quality` (basically some docstring formatting is sometimes necessary to have beautiful docs but against what black wants so `make style` can be destructive, it's not jsut styling).

I have no objection with making `make style` do the checks too so that in most cases, we can just do `make style`.

**Comment by stas00** [comment]
OK, @sgugger - I changed it to `style` and re-used the same intermediary make target so it's one source to change.

BTW, `utils/check_copies.py` takes forever to run :(

**Comment by sgugger** [comment]
Oh? On my setup it's faster than flake8 so didn't try to optimize. But I can try to make some speedups to that script (basically one regex on the whole content to check whether the for loop is necessary and quickly dimiss files with no copies). It would still open all files if that's where the slowdown comes from though.

**Comment by stas00** [comment]
It's 2-3 times slower on my machine:
```
$ time python utils/check_copies.py

real    0m26.997s
user    0m24.928s
sys     0m2.052s

$ time flake8 examples templates tests src utils

real    0m11.735s
user    1m47.922s
sys     0m1.051s
```
flake is slow, and the new script is **very** slow

**Comment by stas00** [comment]
So, I'm not sure how welcome the change to `make style` will be if it's going to be 10 times slower.

Here an alt solution with 3rd target:
```
quality_checks:
	flake8 examples templates tests src utils
	python utils/check_copies.py
	python utils/check_repo.py

quality:
	black --check examples templates tests src utils
	isort --check-only examples templates tests src utils
	${MAKE} quality_checks

# Format source code automatically and check is there are any problems left that need manual fixing

style:
	black examples templates tests src utils
	isort examples templates tests src utils

fixup: style quality_checks

```

**Comment by LysandreJik** [comment]
I don't have a very strong opinion on either adding flake8 to style or having fixup, as long as we keep make quality as a script that does not make any change itself.

**Comment by LysandreJik** [comment]
And I'm observing the same behaviour with the `utils/check_copies.py`. It takes a while now.

**Comment by sgugger** [comment]
Will speed up the `utils/check_copies.py` today. The lag might be due to the fact we have more copies to check now.

**Comment by stas00** [comment]
OK, so I went with adding a new target `fixup` that performs automatic fixes and manual checks where automation is not possible. Added documentation.

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks for taking care of it @stas00 !

**Review by sshleifer — APPROVED** [review]

**Pull request merged**
