### PR TITLE
[Docs] Remove duplicated comments

### PR DESCRIPTION
**Pull request by lorenzoverardo**
# What does this PR do?

Fixes https://github.com/huggingface/transformers/issues/29814

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] ~~Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?~~
- [ ] ~~Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.~~
- [ ] ~~Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).~~
- [ ] ~~Did you write any new necessary tests?~~

Must be a result of [this script](https://github.com/huggingface/transformers/blob/v3.5.1hotfix/utils/style_doc.py) by @sgugger, who, however, I noticed that doesn't work at the company anymore.
cc @stevhliu @MKhalusova

### CODE REVIEW

**Review by stevhliu — COMMENTED** [review]
Thanks for the fixes! I'm not sure why the tests are failing, but can you open this PR against `huggingface/main` instead of `huggingface/v3.5.1hotfix`?

**Comment by lorenzoverardo** [comment]
No worries! These files don't seem to exist on `main` as it's legacy docs, and I opened this PR against `v3.5.1hotfix` as I thought that's what the source is for https://huggingface.co/transformers/v3.5.1/index.html, but I actually just noticed that the problem still exists on later versions (>4.0.0). Do you still think I should change the target to `main`?

**Comment by stevhliu** [comment]
Ah I see! On my end, I don't see these duplicated comments any more on the latest versions of Transformers. For example, this is from v4.39.1:

Screenshot 2024-03-23 at 12 00 11 PM

**Comment by lorenzoverardo** [comment]
As far as I can tell, there are a variable number of duplicates of this kind for all versions going from v3.2.0 all the way to v4.4.2. Do you not update these seemingly legacy docs anymore or do you have some kind of backporting process I can follow perhaps?

**Comment by stevhliu** [comment]
That's a good question, and I'm not actually sure! Let me ping @ArthurZucker who can better help answer this :)

**Comment by ArthurZucker** [comment]
We don't really have anything TBH, and yeah we should delete if possible !

**Comment by lorenzoverardo** [comment]
@stevhliu what do you advise? Should these docs be updated or not? If so, how would I go about it, considering that tests are not passing for this version (due to dependency hell, it seems), and also all versions affected would ideally need to be fixed (I'm also not sure about the respective branch of each)?

**Comment by stevhliu** [comment]
I would say we don't really need to update and maintain these legacy docs anymore, and users are redirected to the newer doc versions where it is fixed and correct.

**Comment by lorenzoverardo** [comment]
Okay then, I'll close the PR 🙂

**Pull request closed without merging**
