### PR TITLE
[gh ci] less output ( --durations=50)

### PR DESCRIPTION
**Pull request by sshleifer**
Way too much output in [this](https://github.com/huggingface/transformers/pull/7989)
This will make it slightly better.
cc @stas00

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]

**Comment by stas00** [comment]
Thank you for the heads up - I will be working on all these related issues shortly - too much data indeed, but not just that.

**Comment by stas00** [comment]
I'd say remove them complete for now and also -rA - I need to experiment and see how to make this data available w/o making logs unusable.

**Comment by sshleifer** [comment]
More context on github actions:


if we can somehow catch the return value of 
bash
```
x= python -m pytest -n 1 --dist=loadfile -s examples --durations=50 | tee test_output.txt
save test_output.txt # always succeeds
sys.exit(x)
```
or something like that, we can make huge progress on the github actions issue and start making artifacts files.

The reason artifacts files broke was that even in the below code, even if line 1 raises an error, line 2 succeeds so github actions thinks the job succeeded
```bash
python -m pytest -n 1 --dist=loadfile -s examples --durations=50 | tee test_output.txt
save test_output.txt # always succeeds
```

**Comment by stas00** [comment]
oh, but we don't need any of this. I already have the first component working, see:
https://github.com/huggingface/transformers/pull/7995
see the resulting artifacts:
https://app.circleci.com/pipelines/github/huggingface/transformers/14354/workflows/1ccd616e-218f-4ae1-b413-91d2faa0e942/jobs/104363/artifacts

**Comment by sshleifer** [comment]
This is all much easier in circleci. My ask is to make it work in github actions.

**Comment by sshleifer** [comment]
`test_failures.txt` is really nice!

**Comment by stas00** [comment]
Ah, good point. let me see what other handy reports I can squeese in circle-ci and then I will move to github actions.

I'm not following your question yet, let me get to github actions and then it'll probably make sense, but yes I'm referring to that example when I said:
> In your example instead of `x = cmd` what you need to save is `$?` which is the exit status of the command.

**Pull request merged**
