### PR TITLE
Fix convert for newer megatron-lm bert model

### PR DESCRIPTION
**Pull request by yoquankara**
# What does this PR do?

Because both GPT2 and BERT share the same underlying issue of different tensor ordering, similar modifications in [convert_megatron_gpt2_checkpoint.py](https://github.com/huggingface/transformers/blob/master/src/transformers/models/megatron_gpt2/convert_megatron_gpt2_checkpoint.py) are needed to convert newer Megatron-LM BERT models.

I actually tested that this fix was necessary to fine tune Megatron-LM BERT correctly with transformers API.

## Who can review?

@LysandreJik @jdemouth

### CODE REVIEW

**Comment by yoquankara** [comment]
Code style has been fixed.

**Comment by yoquankara** [comment]
@LysandreJik @stas00 
What else should I do to make progress on this PR?

**Comment by stas00** [comment]
I suppose we just want to make sure that updated script works with:
1. the old official nvidia bert checkpoint release
2. with a model trained on the modern Meg-LM code-base

so to test for both:
1. convert to HF
2. load in HF and test it works. the definition of works could be checking that it gives the same loss? or generates the same output on Meg and HF sides

At least that's the validation process I did before proposing the GPT2 PR.

**Comment by yoquankara** [comment]
Thank you, totally make sense. I'll find time to also test the old official model and post the validation result when finished.

**Comment by stas00** [comment]
@LysandreJik - should we just merge this? As even if there are issue here it's an improvement over the original version.

**Comment by LysandreJik** [comment]
@jdemouth, could you comment on this if you have a bit of bandwidth?

Otherwise, let's go ahead and merge this next week.

**Comment by stas00** [comment]
ping

**Comment by jdemouth** [comment]
@yoquankara were you able to run tests to validate that it does not break the code for the older models?

**Comment by stas00** [comment]
I have a feeling @yoquankara has either given up on our process or is busy with work/life. 

@jdemouth, Should we merge it and deal with any potential problems if they arise?

**Comment by jdemouth** [comment]
@stas00 - I agree. I think we should merge and we'll fix things if something breaks.

**Review by stas00 — APPROVED** [review]
Thank you for bearing with us, @yoquankara

**Comment by yoquankara** [comment]
@stas00 @jdemouth 
I apologize for not being able to proceed. This was always in my mind, but I have been quite occupied by other things.
Thank you for your understanding and merging decision. I will try my best to follow up when things go better.

**Comment by stas00** [comment]
Thank you for taking the time to share your needs, @yoquankara

That is totally understandable - you had no obligation to do anything - we just wanted to know whether you wanted to continue being involved. But otherwise, we hope to see you in another PR in the future.

**Comment by kaushalshetty** [comment]
io.UnsupportedOperation: seek. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead. Getting this error while converting the BERT checkpoint

**Comment by stas00** [comment]
You probably don't realize it but your comment is not actionable, @kaushalshetty, since we have no idea what you did.

Please file a proper bug report so that we could reproduce the problem and then it'd be possible to act on it and help you with your need. Make sure to include the full traceback in your report.

Thank you!

**Comment by kaushalshetty** [comment]
I am so sorry. I understand that. My bad !
So here's what I have :
- `transformers` version:
- Platform:
- Python version:
- PyTorch version (GPU?):
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

### Who can help


## Information

Model I am using Megatron-BERT(megatron-bert-uncased-345m):

The problem arises when using:
* trying to install megatron through https://huggingface.co/nvidia/megatron-bert-uncased-345m 

The tasks I am working on is:
* to get megatron embeddings

## To reproduce

Steps to reproduce the behavior:

1. export MYDIR=$HOME
2. git clone https://github.com/huggingface/transformers.git $MYDIR/transformers
3. mkdir -p $MYDIR/nvidia/megatron-bert-uncased-345m
4. wget --content-disposition https://api.ngc.nvidia.com/v2/models/nvidia/megatron_bert_345m/versions/v0.1_uncased/zip -O $MYDIR/nvidia/megatron-bert-uncased-345m/checkpoint.zip
5. python3 $MYDIR/transformers/src/transformers/models/megatron_bert/convert_megatron_bert_checkpoint.py $MYDIR/nvidia/megatron-bert-uncased-345m/checkpoint.zip


```Traceback (most recent call last):
  File "/home/omniai-jupyter/transformers/src/transformers/models/megatron_bert/convert_megatron_bert_checkpoint.py", line 327, in <module>
    main()
  File "/home/omniai-jupyter/transformers/src/transformers/models/megatron_bert/convert_megatron_bert_checkpoint.py", line 296, in main
    input_state_dict = torch.load(pytorch_dict, map_location="cpu")
  File "/opt/omniai/software/Miniconda/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/omniai/software/Miniconda/lib/python3.6/site-packages/torch/serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/opt/omniai/software/Miniconda/lib/python3.6/site-packages/torch/serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "/opt/omniai/software/Miniconda/lib/python3.6/site-packages/torch/serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/opt/omniai/software/Miniconda/lib/python3.6/site-packages/torch/serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
io.UnsupportedOperation: seek. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.```

## Expected behavior

<!-- A clear and concise description of what you would expect to happen. -->
Expect megatron checkpoint gets converted to huggingface format.

**Comment by stas00** [comment]
That's excellent, but in the future please open a new Issue. Once a PR is merged or an Issue is closed it's very difficult to track those.

I tested your use case and it worked for me with python 3.8:

```
Extracting PyTorch state dictionary from "megatron-bert-uncased-345m/checkpoint.zip"
Converting
Saving config
Saving checkpoint to "megatron-bert-uncased-345m/pytorch_model.bin"
```

and it indeed fails with python-3.6:

```
Traceback (most recent call last):
  File "../../transformers-master/src/transformers/models/megatron_bert/convert_megatron_bert_checkpoint.py", line 327, in <module>
    main()
  File "../../transformers-master/src/transformers/models/megatron_bert/convert_megatron_bert_checkpoint.py", line 296, in main
    input_state_dict = torch.load(pytorch_dict, map_location="cpu")
  File "/home/stas/anaconda3/envs/py36-pt18/lib/python3.6/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/stas/anaconda3/envs/py36-pt18/lib/python3.6/site-packages/torch/serialization.py", line 235, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/home/stas/anaconda3/envs/py36-pt18/lib/python3.6/site-packages/torch/serialization.py", line 220, in __init__
    _check_seekable(buffer)
  File "/home/stas/anaconda3/envs/py36-pt18/lib/python3.6/site-packages/torch/serialization.py", line 311, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/stas/anaconda3/envs/py36-pt18/lib/python3.6/site-packages/torch/serialization.py", line 304, in raise_err_msg
    raise type(e)(msg)
io.UnsupportedOperation: seek. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
```

So python-3.6 doesn't like the zip file handle. So here is a quick workaround for you:

```
$ unzip megatron-bert-uncased-345m/checkpoint.zip
$ python ../../transformers-master/src/transformers/models/megatron_bert/convert_megatron_bert_checkpoint.py release/mp_rank_00/model_optim_rng.pt
Extracting PyTorch state dictionary from "release/mp_rank_00/model_optim_rng.pt"
Converting
Saving config
Saving checkpoint to "release/mp_rank_00/pytorch_model.bin"
```

I'm passing the actual checkpoint file instead of the zip file in case it wasn't clear from the command line.

@LysandreJik, @sgugger - what do we want to do here?

I propose to catch that it's python-3.6 and refuse to deal with the zipped checkpoint, asserting, asking to unzip it first?

the same will need to be done for `megatron_gpt` 

Need to check if py37 works - I need to build an env for it and check

**Comment by sgugger** [comment]
We might also start saying Transformers requires Python 3.7 or above since Python 3.6 is at the end of its life cycle.

**Comment by stas00** [comment]
oh, cool! thanks, @sgugger 

so should we just change 

https://github.com/huggingface/transformers/blob/8481ecefbd7e701bc061b321cb1695d16eac95a9/setup.py#L135

to 3.7?

@LysandreJik - is now a good time?

**Pull request merged**
