### PR TITLE
Fix `sp_model_kwargs` param missing at unpickle in `XLMRobertaTokenizer`

### PR DESCRIPTION
**Pull request by PhilipMay**
fix for #11429

### CODE REVIEW

**Comment by PhilipMay** [comment]
Hi,

is this call here even needed?

https://github.com/huggingface/transformers/blob/35cd8eed887891bee60194a95adc35b884f68f55/src/transformers/models/xlm_roberta/tokenization_xlm_roberta.py#L148

I think it is not because this:

https://github.com/huggingface/transformers/blob/35cd8eed887891bee60194a95adc35b884f68f55/src/transformers/tokenization_utils_base.py#L798-809

does not set it as an attribute.

I think `self.sp_model_kwargs = sp_model_kwargs` is needed to be able to pickle and unpickle the tokenizer.

@sgugger @LysandreJik @stefan-it

**Comment by PhilipMay** [comment]
This PR ist ready for merging from my point of view.

**Review by sgugger — APPROVED** [review]
LGTM, thanks for fixing!

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks @PhilipMay!

**Pull request merged**
