### PR TITLE
remove two deprecated function

### PR DESCRIPTION
**Pull request by ji-huazhong**
# What does this PR do?

we are now at 4.37.0.dev0, it's time to say goodbye to `torch_required` and `tf_required`

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @ydshieh

### CODE REVIEW

**Comment by ydshieh** [comment]
Hi @statelesshz Thanks a lot for this PR! Let's wait a bit the response from #25948 🙏

**Comment by xkszltl** [comment]
@ydshieh 
Thanks for the notification.

This is handled by someone else currently, so I don't hold strong opinion against it.
My understanding is if there's breaking change they'll likely to pin down version instead of patching.

However all previous points regarding API stability still holds.
It'll unavoidably break a lot of existing community code, without clear benefit.
It there's any strong benefit I missed, please state that in PR desc.

**Comment by ydshieh** [comment]
The points are valid, but I am not sure about ` break a lot of existing community code`.

Keep something in the codebase we don't use anymore is not great. Having it in a legacy dir is only worth it if that code is really used in the wild (for which I am not sure it's the case). Keep it with a warning is also not ideal - we have a lot of discussion about if to keep warnings or not etc.

I will move on - and if we eventually see it is indeed used a lot by the community, we can put it back (but in a legacy dir).

**Review by ydshieh — APPROVED** [review]
Thanks!

**Comment by xkszltl** [comment]
> Keep something in the codebase we don't use anymore is not great

Agree

> Having it in a legacy dir is only worth it if that code is really used in the wild (for which I am not sure it's the case)

`torch_required` is currently used by 704 files just on GitHub:
- https://github.com/search?q=%40torch_required&type=code

image

66 files for `tf_required`:
- https://github.com/search?q=%40tf_required&type=code

**Comment by ydshieh** [comment]
Thanks a lot for this information!

But some (if not many) of them are actually including the definitions of those 2 functions in a file in their own repository.

**Review by amyeroberts — APPROVED** [review]
Thanks for tidying up! 

Agreed that it's time to remove. 

@xkszltl the advantage of removing this code is to make it easier to manage the codebase. If we kept all the code that was ever written in the repo, then it would quickly become unmanageable. There is, of course, a balance between impact to the users and how changes are made - objects part of the public API have to be added, removed and modified with care. As @ydshieh highlights, the relative impact of removing these is small based on a public repo search and we've already taken care to go through a deprecation cycle.

**Pull request merged**
