### PR TITLE
Simplify getting the number of embedding tokens.

### PR DESCRIPTION
**Pull request by kwonmha**
Simplifies the way to get the number of embedding tokens.

Following additional discussions on PR #26024 

## Who can review?

@ArthurZucker

### CODE REVIEW

**Review by ArthurZucker — COMMENTED** [review]
Thanks for following up! Let's make sure the slow tests / related deep speed tests pass. Pinging @pacman100 for a second look !

**Review by zhangjunyi111 — COMMENTED** [review]
现在不用判断zero3启动了没有吗

**Comment by kwonmha** [comment]
@pacman100 
hello, please have a look at this PR.
It's been a while since I created this PR.

**Review by ArthurZucker — DISMISSED** [review]
Looks good to me! Let me run the slow tests

**Comment by kwonmha** [comment]
From #26112, I understood that `weight.shape[0]` always has accurate info and `num_embedding` doesn't.
But I can say that in this case, right after embedding parameter has been created, it looks OK.

Anyway, it's up to you.
Feel free to close this PR.

**Comment by pacman100** [comment]
Hello @kwonmha , yes, as per that comment, this PR doesn't look like a good fix as you are changing the code which get the embedding size post resizing of the embedding layer. Closing this PR, thank you!

**Pull request closed without merging**
