### PR TITLE
Add notebook INC quantization for text classification tasks

### PR DESCRIPTION
**Pull request by echarlaix**
Add a notebook showing how to apply Intel Neural Compressor (INC) quantization (dynamic, post-training and aware training approach) for text classification tasks.

### CODE REVIEW

**Comment by mfuntowicz** [comment]
Should we add an **Optimum** section? :)

**Comment by sgugger** [comment]
Great addition!
I have a couple of comments on the notebook. Could you share a Colab version where I could put them?

**Comment by sgugger** [comment]
(For instance the notebook does not run to completion :-/)

**Comment by echarlaix** [comment]
I shared the notebook (which now runs to completion)

**Comment by echarlaix** [comment]
Thank you for your comments @sgugger, the notebook was updated accordingly.

**Review by LysandreJik — APPROVED** [review]
Nice, this looks good! Super insightful, loved the explanation between the different types of quantization


A few comments on the notebook/optimum in general (I don't see @sgugger's comments so some may overlap):
- `tokenizer = AutoTokenizer.from_pretrained(model_checkpoint, use_fast=True)` the `use_fast` is set to `True` by default - is there a need to set it explicitly here? I'd say to force the error if a fast tokenizer is not available, but you mention that users should remove the argument if there's an error, which defeats this purpose.
- `Depending on the model you selected, you will see different keys in the dictionary returned by the cell above. They don't matter much for what we're doing here (just know they are required by the model we will instantiate later)` -> I would say that we don't need to care about what's inside the dictionary, rather than the keys don't matter much; it makes it seem like users can throw away one or two keys and it won't change much.
- Doing the following: `IncQuantizedModelForSequenceClassification.from_pretrained(output, ...)` results in a super long warning mentioning all the layers that were ignored on loading. This doesn't seem to be an issue, but warnings should really only be raised when there's an issue. We've had several issues opened because of this exact line, with users wondering if their model loaded correctly (as they should!). We implemented a `_keys_to_ignore_on_load_unexpected` which can contain regex expressions and be easily overridden to provide the keys that should not raise a warning when they're present yet not used. You can see such an example here: https://github.com/huggingface/transformers/blob/9b78b070efa4e3ebe9cd406c55723ce3d63d143c/src/transformers/models/albert/modeling_albert.py#L898
- I would add an introduction at the start mentioning what we'd like to do and how we'd like to do it.
- I would add a small summary at the end mentioning all that was done in the notebook: the quantization and the memory/compute saved along the way (why did we do it?), followed by the result (what did it cost? the 0.004 drop in accuracy)

**Comment by echarlaix** [comment]
Thanks for the detailed comments @LysandreJik. I updated the notebook accordingly and we do not set `use_fast` to `True` anymore as it's not related to quantization and could indeed be misleading. I also rephrased the ambiguous comment and added an introduction as well as a model sizes comparison between the full-precision and the quantized model. Finally concerning the loading of the quantized model warnings, it's a good point and we will modify our `IncQuantizedModel` class in order to have something clearer for the user.

**Review by mfuntowicz — APPROVED** [review]

**Comment by LysandreJik** [comment]
Then LGTM :)

**Pull request merged**
