### PR TITLE
Check config type using `type` instead of `isinstance`

### PR DESCRIPTION
**Pull request by LysandreJik**
This seems like the textbook case where using `type` should be preferred over using `isinstance`.

Thanks to @hjptriplebee for showing the way in https://github.com/huggingface/transformers/pull/6870, this PR does the same for all remaining cases.

### CODE REVIEW

**Comment by julien-c** [comment]
In that case we can even remove the for loops entirely, no?

**Comment by sgugger** [comment]
I agree with @julien-c, we can directly check if `type(config)` is in the dict.

**Comment by LysandreJik** [comment]
Done!

**Comment by julien-c** [comment]
This is faster than catching a KeyError, that's what you do it that way?

**Review by julien-c — APPROVED** [review]

**Review by sgugger — APPROVED** [review]
Great, thanks!

**Pull request merged**
