### PR TITLE
Add AraBert Model

### PR DESCRIPTION
**Pull request by jadechoghari**
Goal: Make Ai more open and accessible to all 🤗
Adding AraBert Model - the go-to model for any Arabic NLP task;
(The model is a bit similar to bert_japanese)
https://github.com/aub-mind/arabert

TODO: 
- add testing
- fix jar files problem for Farasa segmenter

Problem facing that a HF could help:
- **Jar File Requirement**: 
  The preprocessing step for some models in AraBert requires the Farasa segmenter, which depends on a jar file that needs to be manually downloaded and included. I'm not sure how fine are HF with adding a java binary file or if I could simply import the library...
`from farasa.segmenter import FarasaSegmenter`
https://github.com/MagedSaeed/farasapy/blob/master/farasa/__base.py#L233

Thanks for the support
Will tag @NielsRogge

### CODE REVIEW

**Comment by NielsRogge** [comment]
Hi,

I would recommend to follow this guide to make AraBert usable through the Transformers library: https://huggingface.co/docs/transformers/custom_models, as this is the current preferred way

**Comment by jadechoghari** [comment]
Will have a look, thanks!

**Comment by jadechoghari** [comment]
AraBert uses the same architecture as the original BERT implementation. Should I also create a configuration file for it? I noticed that there aren't any separate configuration files for BertJapanese and BertTweet, which also follow the exact BERT architecture

**Comment by NielsRogge** [comment]
Yes you can create a configuration for it, by copying the entire config

**Pull request closed without merging**
