### PR TITLE
TokenGT for graph classification

### PR DESCRIPTION
**Pull request by clefourrier**
# What does this PR do?

Adds the TokenGT model for graph classification in Transformers.

Done:
- [x] Architecture ported
- [x]  Collator (the model has no tokenizer) and preprocessing

Todo:
- [ ] Test results against original implementation, to make sure they are within precision range. Edit: exactly same results :fire: 
- [ ] Add checkpoints and make sure they load properly
- [ ] Update doc
- [ ] Update test suite
- [ ] Add model card for the checkpoints once added

## Dependencies
Cython - this could be ported to Python, but preprocessing will be considerably slower, as well as collation if preprocessing is done on the fly. 

Linked to #21079

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. (Discussed on Slack)
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Not tagging anyone for now as this is a draft.

### CODE REVIEW

**Comment by clefourrier** [comment]
@Raman-Kumar Here is a first draft to get you started!

I suggest you start by finding a checkpoint, then try to compare the execution step by step with the original model to make sure results are the same (I can provide you with the script I used for Graphormer if you need). I also added some todos in the code, which can help you get started too! Feel free to compare everything with the Graphormer PR to get an idea of the process and things to do!

**Comment by Raman-Kumar** [comment]
👏 Okay doing that ...
@clefourrier may need a little relaxed timeline

**Comment by Raman-Kumar** [comment]
👏 Okay doing that ...
@clefourrier may need a little relaxed timeline, studying a few more things

**Comment by clefourrier** [comment]
@Raman-Kumar Take the time you need, there is no urgency on my side; feel free to ping me if you need help later on!

**Comment by clefourrier** [comment]
Sorry for accidentally closing it

**Comment by clefourrier** [comment]
Closing and replacing with #21745 21745

**Pull request closed without merging**
