### PR TITLE
    Fixing a regression with `return_all_scores` introduced in #17606

### PR DESCRIPTION
**Pull request by Narsil**
Fixing a regression with `return_all_scores` introduced in #17606

    - The legacy test actually tested `return_all_scores=False` (the actual
      default) instead of `return_all_scores=True` (the actual weird case).

    This commit adds the correct legacy test and fixes it.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
 
@sgugger 

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Comment by Narsil** [comment]
PS: Failing tests seem to be linked with new `black` version so I am going to ignore them and rebase later.

**Comment by sgugger** [comment]
Mmm I see weird changes in `molideng_utils` and `gpt2` now. I think your solution is sensible.

**Comment by Narsil** [comment]
Wrong rebase on my end.

**Pull request merged**
