### PR TITLE
Actually the extra_id are from 0-99 and not from 1-100

### PR DESCRIPTION
**Pull request by orena1**
```
a = tokenizer.encode("we got a <extra_id_99>", return_tensors='pt',add_special_tokens=True)
print(a)
>tensor([[   62,   530,     3,     9, 32000]])
a = tokenizer.encode("we got a <extra_id_100>", return_tensors='pt',add_special_tokens=True)
print(a)
>tensor([[   62,   530,     3,     9,     3,     2, 25666,   834,    23,    26,
           834,  2915,  3155]])
```

### CODE REVIEW

**Comment by orena1** [comment]
@patrickvonplaten

**Review by LysandreJik — APPROVED** [review]
Indeed!

Verified with

```py
from transformers import T5Tokenizer

tokenizer = T5Tokenizer.from_pretrained("t5-base")

for i in range(101):
    print(i, f"<extra_id_{i}>" in tokenizer.get_vocab())
```

which outputs `True` for [0, 99] and `False` for 100.

**Comment by LysandreJik** [comment]
Thansk @orena1 !

**Comment by LysandreJik** [comment]
pinging @patrickvonplaten for notification

**Pull request merged**
