### PR TITLE
FEAT / Trainer: Add adamw 4bit optimizer

### PR DESCRIPTION
**Pull request by SunMarc**
# What does this PR do ? 

This PR adds the 4-bit optimizer from torchao library into HF Trainer. For now, it requires the main branch of `torchao` and torch >=2.3 (maybe we can wait a bit before merging). For those who wants to try, you can pass `optim="adamw_torch_4bit"` in `TrainingArguments`. 

Since we already have the 8-bit optimizer from bnb that works well, i'm not adding it. 

Related thread : https://x.com/marksaroufim/status/1809398186198593566

cc @muellerzr as you might be interested

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Nice! LG2M, cc @msaroufim :)

**Review by amyeroberts — APPROVED** [review]
Thanks for adding!

**Comment by SunMarc** [comment]
> There's also an AdamWFp8 btw and it's the fastest one we've found when the HW supports it https://github.com/pytorch/ao/tree/main/torchao/prototype/low_bit_optim#benchmarks

Nice ! I'll add it in a separate PR !

**Comment by msaroufim** [comment]
Heads up @SunMarc we just released torchao 0.4! https://github.com/pytorch/ao/releases/tag/v0.4.0

**Comment by SunMarc** [comment]
Nice ! I'll merge it as soon as we merge the torchao quantization PR in transformers as there is some overlap !

**Comment by fzyzcjy** [comment]
Hi, is it OK if I PR to add the 8bit counterpart? (see https://github.com/huggingface/transformers/issues/34893 for details) Thanks!

**Pull request merged**
