### PR TITLE
[docs] fix model_doc links in model summary

### PR DESCRIPTION
**Pull request by patil-suraj**
Possible fix for #5561

@sgugger

### CODE REVIEW

**Comment by sgugger** [comment]
No, this won't work across versions (if you switch to master docs for instance). The problem is in the first slash, I think removing it should be enough to make all link works.

**Comment by sgugger** [comment]
Double-checked locally, this is the right fix: `/model_doc/gpt` -> `model_doc/gpt`

**Comment by patil-suraj** [comment]
should I make these changes ? also model_doc/gpt or model_doc/gpt.html ?

**Comment by sgugger** [comment]
No need for the .html.
I can force-push on your branch or let you do the changes, your call!

**Review by sgugger — APPROVED** [review]
Thanks a lot!

**Comment by mikaelsouza** [comment]
How much time does it take to these changes be reflected in the website?

Also, can I close my issue after this fix?

@sgugger 

Thanks! :)

**Comment by sgugger** [comment]
The thing is that the bug will probably stay in the stable version of the doc forever (unless we manage to cherry-pick it somehow @LysandreJik ?). It is reflected in the [master version](https://huggingface.co/transformers/master/model_summary.html) already.

You can close your issue whenever you like :-)

**Pull request merged**
