### PR TITLE
Fix gradient checkpointing bug in gptneox

### PR DESCRIPTION
**Pull request by KMFODA**
# What does this PR do?

This PR fixes a bug that a user can encounter while using generate and models that use gradient_checkpointing.

Fixes Issue https://github.com/huggingface/transformers/issues/21737

cc @younesbelkada or @gante

### CODE REVIEW

**Review by younesbelkada — COMMENTED** [review]
Thanks a lot for your great work on this! 
You need to remove the block from [this line](https://github.com/huggingface/transformers/blob/2ea1ef909016484bee9d60c05582031464490f77/src/transformers/models/gpt_neox/modeling_gpt_neox.py#L510) as well and we should be good to go! 🚀

**Comment by KMFODA** [comment]
Apologies, hand't pushed the latest commit. All done now!

**Review by younesbelkada — APPROVED** [review]
Thanks a lot for all your work on this! Ok for me as long as all the CIs are green 🍏

**Comment by gante** [comment]
Awesome, thank you for the contribution <3

**Pull request merged**
