### PR TITLE
explain how to successfully run examples in readme and doc

### PR DESCRIPTION
**Pull request by rlouf**

### CODE REVIEW

**Comment by LysandreJik** [comment]
Cool, this is important. I feel like installing from source without cloning (e.g. using `pip install git+https://github.com/huggingface/transformers`) would put less strain on the users' set-up, is there a reason we prefer cloning (I know the aforementioned method also clones, but it puts it in a temporary folder)? This is fine as it is, I'm just curious.

**Review by LysandreJik — APPROVED** [review]

**Comment by rlouf** [comment]
That way you also cover the case of people who clone the repository to execute the examples (I would believe the majority of users), and encouraging this behavior which is a much better practice than copy/pasting.
Doing so you are absolutely sure the version of the library is the exact same as the version of the examples. This may not be true for `pip install git+https://github.com/huggingface/transformers` if the library has since changed.

**Comment by iedmrc** [comment]
> That way you also cover the case of people who clone the repository to execute the examples (I would believe the majority of users), and encourage this behavior which is a much better practice than copy/pasting.
> Doing so you are absolutely sure the version of the library is the exact same as the version of the examples. This may not be true for `pip install git+https://github.com/huggingface/transformers` if the library has since changed.

in fact, passing a branch name, a commit hash, a tag name or a git ref is possible like so:

```
[-e] git://git.example.com/MyProject.git@master#egg=MyProject
[-e] git://git.example.com/MyProject.git@v1.0#egg=MyProject
[-e] git://git.example.com/MyProject.git@da39a3ee5e6b4b0d3255bfef95601890afd80709#egg=MyProject
[-e] git://git.example.com/MyProject.git@refs/pull/123/head#egg=MyProject
```
According to https://pip.pypa.io/en/stable/reference/pip_install/#git

**Comment by julien-c** [comment]
@LysandreJik Maybe we can list both options i.e. also reference `pip install git+https://github.com/huggingface/transformers`

Also small nitpick, don't hesitate to squash commits when merging very related changes.

**Comment by rlouf** [comment]
Fair nitpick

**Pull request merged**
