### PR TITLE
Remove redundant backend checks in training_args.py

### LINKED ISSUE #28109: remove unnecessary backend related checks in training_args.py
### Feature request

[Here](https://github.com/huggingface/transformers/blob/main/src/transformers/training_args.py#L1490-L1519)

IMO these checks in transformers should be removed.

```
   if (
            self.framework == "pt"
            and is_torch_available()
            and (self.device.type != "cuda")
            and (self.device.type != "npu")
            and (self.device.type != "xpu")
            and (get_xla_device_type(self.device) != "GPU")
            and (self.fp16 or self.fp16_full_eval)
        ):
            raise ValueError(
                "FP16 Mixed precision training with AMP or APEX (`--fp16`) and FP16 half precision evaluation"
                " (`--fp16_full_eval`) can only be used on CUDA or NPU devices or certain XPU devices (with IPEX)."
            )

        if (
            self.framework == "pt"
            and is_torch_available()
            and (self.device.type != "cuda")
            and (self.device.type != "npu")
            and (self.device.type != "xpu")
            and (get_xla_device_type(self.device) != "GPU")
            and (get_xla_device_type(self.device) != "TPU")
            and (self.device.type != "cpu")
            and (self.bf16 or self.bf16_full_eval)
        ):
            raise ValueError(
                "BF16 Mixed precision training with AMP (`--bf16`) and BF16 half precision evaluation"
                " (`--bf16_full_eval`) can only be used on CUDA, XPU (with IPEX), NPU or CPU/TPU/NeuronCore devices."
            )

```

### Motivation

To make things work each vendor need to extend this `if` by putting another line of ` and (self.device.type != "my_precious_chip")`.
It makes code bloated in transformers. 

And I don't really think it's transformers' job to determine capability for backends. Just passthrough the paramters and let backend itself to determine if they can handle the dtype. They should have enough means to report a error.

### Your contribution

I'm glad to delete them if approved : -p

### PR DESCRIPTION
**Pull request by kevint324**
# What does this PR do?

Fixes  #28109

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@ArthurZucker @muellerzr

### CODE REVIEW

**Comment by muellerzr** [comment]
Thanks @kevint324! Overall this looks fine but let's fix the failing quality checks!

```bash
pip install -e .[quality]; make fixup;
```

**Comment by kevint324** [comment]
@muellerzr 
Done. After `make fixup;`  a extra import is removed.

Thanks

**Review by ArthurZucker — COMMENTED** [review]
make sure to rebase, the tests should normally be alright afterwards!

**Comment by kevint324** [comment]
I looked into the failed case and found the casue.

In my PR I removed the calls to self.device within the `if` statements which calls `_setup_devices` to do some initialization.

**Comment by kevint324** [comment]
I've no idea why [test_offline.py : test_offline_mode](https://app.circleci.com/pipelines/github/huggingface/transformers/94104/workflows/61f0aecd-d79b-4775-8030-4a8d4a7bf9e9/jobs/1235408) still fails. 

I tried it on main and it still failed. @ArthurZucker

**Comment by LysandreJik** [comment]
Failing tests are independent of the changes, merging

**Pull request merged**
