### PR TITLE
Fix onnx non-exportable inplace aten op

### PR DESCRIPTION
**Pull request by IlyasMoutawwakil**
# What does this PR do?
All of these changes were introduced in `4.46` via #33586, which broke them

### CODE REVIEW

**Comment by IlyasMoutawwakil** [comment]
@ArthurZucker

**Comment by IlyasMoutawwakil** [comment]
same as https://github.com/huggingface/transformers/pull/31696

**Review by ArthurZucker — APPROVED** [review]
Thanks!

**Comment by ArthurZucker** [comment]
Could you run make fix-copies?

**Comment by IlyasMoutawwakil** [comment]
neat ! love this command 😄

**Comment by ArthurZucker** [comment]
feel free to merge!

**Pull request merged**
