### PR TITLE
Add TF benchmark examples

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

As part of the objective to refresh TF examples, this one adds actual TF benchmarks in the examples. Also showcases the power of XLA ;)

### CODE REVIEW

**Comment by gante** [comment]
I see that this PR (https://github.com/huggingface/transformers/pull/15848) exists -- should I just delete the benchmark example instead?

**Review by Rocketknight1 — APPROVED** [review]
These are really nice results for a fairly antiquated GPU!

**Comment by Rocketknight1** [comment]
Ah, and I didn't see that we're deprecating the benchmarks either. Maybe we shouldn't merge this!

**Comment by sgugger** [comment]
Cc @patrickvonplaten

**Review by patrickvonplaten — APPROVED** [review]
Looks good!

**Comment by sgugger** [comment]
@patrickvonplaten It's inconsistent with deprecating the benchmarks, so is your approval a sign we should un-deprecate them?

**Review by patrickvonplaten — COMMENTED** [review]
Sorry I went way too quickly over this PR.

Just remembered that I added this benchmarking folder for TF. Think the results of the benchmarking tool are not super trustworthy (especially the memory part), so indeed maybe let's not merge this and also move both the `examples/{pytorch,tensorflow}/benchmarking` folders to `research_projects`? Wdyt @sgugger ?

**Comment by sgugger** [comment]
That's fine by me! :-)

**Comment by gante** [comment]
Cool -- I'm closing the PR then and will open a new one as @patrickvonplaten suggested (moving both benchmarks to the research projects).

**Pull request closed without merging**
