### PR TITLE
The backticks in the example of transformers.BigBirdPegasusConfig documentation were not in the right spot…

### PR DESCRIPTION
**Pull request by brandonbiggs**
…, causing the documentation to be displayed in a weird way. I moved the backticks a few lines down in the documentation to ensure the documentation is formatted correctly.

# What does this PR do?
Fixes the python documentation example in transformers.BigBirdPegasusConfig 

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
Documentation: @sgugger

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks a lot for fixing this! Could you just run `make style` on your branch to fix the quality issue?

**Comment by brandonbiggs** [comment]
I can make that change, but when I run `make style` it changes a couple hundred files. Is that supposed to happen?

**Comment by sgugger** [comment]
No, it probably means you do not have the right black version (22.3.0).

**Comment by brandonbiggs** [comment]
Oh yeah, I had a slightly newer version apparently. I had issues on my mac with the virtual environment. I'll get that fixed.

**Pull request closed without merging**
