### PR TITLE
Fix tests of mixed precision now that experimental is deprecated

### PR DESCRIPTION
**Pull request by Rocketknight1**

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]

**Comment by Rocketknight1** [comment]
@ydshieh I'll fix them here too!

**Comment by gante** [comment]
(@Rocketknight1 )

**Comment by ydshieh** [comment]
For push/scheduled CI, I think it is fine, as the docker image is built with

```
RUN python3 -m pip install --no-cache-dir -U torch tensorflow
```
(right ..?)

**Comment by gante** [comment]
Yes, CI should be fine :D but users with older versions (which we support) will experience errors, right? Or is it backwards compatible?

**Comment by ydshieh** [comment]
You are right! At least for `src/transformers/training_args_tf.py`.

I am not very sure what's our policy regarding the test backward compatible (regarding the change in `tests/utils/test_modeling_tf_core.py`)

**Pull request merged**
