### PR TITLE
Add dropout to WordpieceTokenizer and BPE

### PR DESCRIPTION
**Pull request by vitaliyradchenko**
We can add dropout not only to model weights but and to a tokenizer. The paper, proposed by Ivan Provilkov (2019, https://arxiv.org/pdf/1910.13267.pdf), describes all benefits from this approach and shows that it's almost always better to use dropout during tokenization. (use only for training, for inference dropout should be equal to 0)

Example:
```
import transformers
tokenizer = transformers.RobertaTokenizer.from_pretrained("roberta-base")
tokenizer.tokenize("Dropout is very important")
# default value is 0
# ['Drop', 'out', 'Ġis', 'Ġvery', 'Ġimportant']
tokenizer.tokenize("Dropout is very important", dropout=0.1)
# ['Drop', 'out', 'Ġis', 'Ġvery', 'Ġimport', 'ant']
```

### CODE REVIEW

**Comment by boy2000-007man** [comment]
Hi i notice one possible issue in your code.
you use `random.random() > dropout`.
However, according to `Docstring: random() -> x in the interval [0, 1).`
So even with droput=0, the bpe output is not deterministic.

**Comment by boy2000-007man** [comment]
Also, according to orig paper, dropout=1 should output char sequence.
but following unchanged code snippet will make it output the raw input
```python3
if not pairs:
    return token
```

**Comment by boy2000-007man** [comment]
and `self.cache` should be updated iff droput=0

**Comment by vitaliyradchenko** [comment]
> Hi i notice one possible issue in your code.
> you use `random.random() > dropout`.
> However, according to `Docstring: random() -> x in the interval [0, 1).`
> So even with droput=0, the bpe output is not deterministic.

thanks, fixed

**Comment by vitaliyradchenko** [comment]
> Also, according to orig paper, dropout=1 should output char sequence.
> but following unchanged code snippet will make it output the raw input
> 
> ```python
> if not pairs:
>     return token
> ```

fixed this too, thanks for pointing

**Comment by vitaliyradchenko** [comment]
> and `self.cache` should be updated iff droput=0

also fixed, thanks

**Comment by boy2000-007man** [comment]
> > Also, according to orig paper, dropout=1 should output char sequence.
> > but following unchanged code snippet will make it output the raw input
> > ```python
> > if not pairs:
> >     return token
> > ```
> 
> fixed this too, thanks for pointing

This issue is not really fixed, the exact corner case is all merges are dropped at the beginning, not limited to dropout=1.
I think the correct fix is replace
```python
        if dropout != 1:
            pairs = [pair for pair in get_pairs(word) if random.random() >= dropout and pair in self.bpe_ranks]
        else:
            # we should merge space byte with first token char
            new_word = []
            token_index = 0
            while token_index < len(token):
                if token[token_index] != self.byte_encoder[32]:
                    new_word.append(token[token_index])
                    token_index += 1
                else:
                    new_word.append(token[token_index : token_index + 2])
                    token_index += 2

            return " ".join(new_word)


        if not pairs:
            return token


        while True:
```
with
```python
        pairs = [pair for pair in get_pairs(word) if random.random() >= dropout and pair in self.bpe_ranks]

        while pairs:
```

**Comment by vitaliyradchenko** [comment]
> > > Also, according to orig paper, dropout=1 should output char sequence.
> > > but following unchanged code snippet will make it output the raw input
> > > ```python
> > > if not pairs:
> > >     return token
> > > ```
> > 
> > 
> > fixed this too, thanks for pointing
> 
> This issue is not really fixed, the exact corner case is all merges are dropped at the beginning, not limited to dropout=1.
> I think the correct fix is replace
> 
> ```python
>         if dropout != 1:
>             pairs = [pair for pair in get_pairs(word) if random.random() >= dropout and pair in self.bpe_ranks]
>         else:
>             # we should merge space byte with first token char
>             new_word = []
>             token_index = 0
>             while token_index < len(token):
>                 if token[token_index] != self.byte_encoder[32]:
>                     new_word.append(token[token_index])
>                     token_index += 1
>                 else:
>                     new_word.append(token[token_index : token_index + 2])
>                     token_index += 2
> 
>             return " ".join(new_word)
> 
> 
>         if not pairs:
>             return token
> 
> 
>         while True:
> ```
> 
> with
> 
> ```python
>         pairs = [pair for pair in get_pairs(word) if random.random() >= dropout and pair in self.bpe_ranks]
> 
>         while pairs:
> ```

understood your point. simplified code, thanks

**Comment by boy2000-007man** [comment]
I have one advice that replace the usage of `random.random() >= dropout` with `dropout == 0 or dropout < 1 and dropout <= random.random()`, utilizing the short-circuit operator to prevent consuming unnecessary random number. Otherwise, this side effects may cause existing result rely on `random` unrepeatable.

**Comment by kretes** [comment]
@vitaliyradchenko good idea to add this feature. are you planning to add the suggestion of @boy2000-007man https://github.com/huggingface/transformers/pull/2313#issuecomment-573192073 and re-fresh this PR so that it will finally get merged?

**Pull request closed without merging**
