### PR TITLE
Avoid dummy token in PLD to optimize performance

### PR DESCRIPTION
**Pull request by ofirzaf**
# What does this PR do?
Current PLD implementation adds a dummy token in case there is no match found in the prompt to avoid issues. In previous PR #28508 the code was fixed to handle zero candidate tokens so there is no need for the dummy token in PLD now. Not inserting this additional token can accelerate PDL on weaker HW where doing inference with the target with 2 tokens is significantly slower than doing inference with 1 token. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

@gante

### CODE REVIEW

**Review by gante — APPROVED** [review]
@ofirzaf Thank you for the optimization!

For future reference, could you share your test script (ideally paired up with the output numbers in your hardware)?

**Review by ArthurZucker — APPROVED** [review]
Looks good thanks for following up on this

**Comment by ofirzaf** [comment]
@gante I am unable to share my measurements since I am working on HW that wasn't released yet. Is it blocking the merge?

**Comment by gante** [comment]
@ofirzaf no :) I'm going to merge the PR

In any case, if you have the script to reproduce your measurements, it would be a nice addition

**Pull request merged**
