### PR TITLE
Scale loss before backward

### LINKED ISSUE #2456: Probaly mistake in `DPOTrainer` when compute/log  `grad_norm`
### System Info

- Platform: Linux-5.4.0-155-generic-x86_64-with-glibc2.35
- Python version: 3.10.8
- PyTorch version: 2.4.0
- Transformers version: 4.46.2
- Accelerate version: 1.1.1
- Accelerate config: not found
- Datasets version: 3.1.0
- HF Hub version: 0.24.6
- TRL version: 0.12.1
- bitsandbytes version: 0.44.1
- DeepSpeed version: 0.15.4
- Diffusers version: not installed
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: 1.54.3
- PEFT version: 0.13.2

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder
- [X] My own task or dataset (give details below)

### Reproduction

dpo scripte
```python
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer
import multiprocessing
from trl import (
    DPOConfig,
    DPOTrainer,
    ModelConfig,
    ScriptArguments,
    TrlParser,
    get_kbit_device_map,
    get_peft_config,
    get_quantization_config,
)
from trl.trainer.utils import SIMPLE_CHAT_TEMPLATE

if __name__ == "__main__":
    parser = TrlParser((ScriptArguments, DPOConfig, ModelConfig))
    script_args, training_args, model_config = parser.parse_args_and_config()

    torch_dtype = (
        model_config.torch_dtype
        if model_config.torch_dtype in ["auto", None]
        else getattr(torch, model_config.torch_dtype)
    )

    quantization_config = get_quantization_config(model_config)

    model_kwargs = dict(
        revision=model_config.model_revision,
        attn_implementation=model_config.attn_implementation,
        torch_dtype=torch_dtype,
        use_cache=False if training_args.gradient_checkpointing else True,
        device_map=get_kbit_device_map() if quantization_config is not None else None,
        quantization_config=quantization_config,
    )

    model = AutoModelForCausalLM.from_pretrained(
        model_config.model_name_or_path, trust_remote_code=model_config.trust_remote_code, **model_kwargs
    )

    peft_config = get_peft_config(model_config)
    if peft_config is None:
        ref_model = AutoModelForCausalLM.from_pretrained(
            model_config.model_name_or_path, trust_remote_code=model_config.trust_remote_code, **model_kwargs
        )
    else:
        ref_model = None

    tokenizer = AutoTokenizer.from_pretrained(
        model_config.model_name_or_path, trust_remote_code=model_config.trust_remote_code
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    if tokenizer.chat_template is None:
        tokenizer.chat_template = SIMPLE_CHAT_TEMPLATE
    if script_args.ignore_bias_buffers:
        model._ddp_params_and_buffers_to_ignore = [
            name for name, buffer in model.named_buffers() if buffer.dtype == torch.bool
        ]

    dataset = load_dataset(script_args.dataset_name,
                           split=script_args.dataset_train_split)
    dataset=dataset.select_columns(['prompt', 'chosen', 'rejected'])
    
    trainer = DPOTrainer(
        model,
        ref_model,
        args=training_args,
        train_dataset=dataset,
        processing_class=tokenizer,
        peft_config=peft_config,
    )

    trainer.train()

    trainer.save_model(training_args.output_dir)
```

bash script
```shell
python dpo.py --model_name_or_path AIR/Llama-3.2-1B-ultrachat200k \
    --dataset_name HuggingFaceH4/ultrafeedback_binarized \
    --output_dir test \
    --attn_implementation flash_attention_2 \
    --beta 0.05 \
    --bf16 \
    --dataset_train_split train_prefs \
    --do_train \
    --gradient_checkpointing \
    --gradient_accumulation_steps 16 \
    --learning_rate 0.00001 \
    --lr_scheduler_type cosine \
    --logging_steps 5 \
    --loss_type sigmoid \
    --max_prompt_length 512 \
    --max_length 1024 \
    --max_steps -1 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --report_to tensorboard \
    --save_strategy epoch \
    --save_total_limit 1 \
    --save_only_model \
    --torch_dtype bfloat16 \
    --warmup_ratio 0.05
```

### Expected behavior

When using `DPOTrainer` I found a unexpected behavior of `grad_norm`.
Specificlly, I keep the `global_batch_size=32` and adjust different `per_device_train_batch_size` and `gradient_accumulation_steps`, the `grad_norm` is positively correlated with `gradient_accumulation_steps`, but it wont appear in SFTTrainer. As i know, the `grad_norm` shouldnt changed so dramatically under the same `global_batch_size`

`batch_size=4`, `accmulation=8`
08e3df269403f2f9e0fa765eb966edda

`batch_size=2`, `accmulation=16`
cd6aab369f9f33b75b33eb5ff25538e5

`batch_size=1`, `accmulation=32`
b4e479c005efe92d48e19ca33c559c73

### Checklist

- [X] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [X] I have included my system information
- [X] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [X] Any traceback provided is complete

### PR DESCRIPTION
**Pull request by qgallouedec**
# What does this PR do?

Fixes https://github.com/huggingface/trl/issues/2456

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
This one feels more like the right solution. Do the slow tests pass under this? (There is one in there for grad accum)

**Review by muellerzr — APPROVED** [review]
Yes because in reality this is exactly the right solution: since we are no longer relying on accelerate to div the loss, we need to do so before `backward()` if we don't know our num items in the batch

**Review by SunMarc — APPROVED** [review]
LGTM !

**Comment by qgallouedec** [comment]
> Do the slow tests pass under this?

They pas locally. I get errors but I think they aren't related:

```
============================== short test summary info ==============================
FAILED tests/trainer/test_trainer.py::TrainerIntegrationTest::test_auto_batch_size_finder - AttributeError: 'DownloadConfig' object has no attribute 'use_auth_token'
FAILED tests/trainer/test_trainer.py::TrainerIntegrationTest::test_auto_batch_size_with_deepspeed - ModuleNotFoundError: No module named 'mpi4py'
FAILED tests/trainer/test_trainer.py::TrainerIntegrationTest::test_use_liger_kernel_patching - AssertionError: False is not true
FAILED tests/trainer/test_trainer_seq2seq.py::Seq2seqTrainerTester::test_finetune_bert2bert - TypeError: BertModel.forward() got an unexpected keyword argument 'num_items_in_batch'
======== 4 failed, 250 passed, 82 skipped, 89 warnings in 203.93s (0:03:23) =========

**Comment by qgallouedec** [comment]
@ArthurZucker @muellerzr @SunMarc I'll let you merge when you think it's good.

**Comment by ArthurZucker** [comment]
Merging! 🤗

**Comment by yzhangcs** [comment]
@qgallouedec @ArthurZucker @muellerzr
Hi, I've identified that there still exists a potential issue with the loss reporting in the Trainer class. 
The problem appears to stem from changes introduced after version 4.45.2, specifically in this line:
https://github.com/huggingface/transformers/blob/24c91f095fec4d90fa6901ef17146b4f4c21d0a3/src/transformers/trainer.py#L3703
The current implementation only divides the loss scalar when `num_items_in_batch` is `None`. However, I believe we should divide the loss scalar regardless of the `num_items_in_batch value`, as was the case in `transformers<=4.45.2`.
This change has led to an unexpected doubling of the logged loss when `gradient_accumulated_steps > 1`. 
You can observe the differences by comparing versions:
https://github.com/huggingface/transformers/compare/v4.45.2...v4.46.0.

**Comment by yzhangcs** [comment]
@qgallouedec Hello, not sure If I understand correctly, does this commit mean `gradient_accumulated_steps` will never take effect, as `num_items_in_batch` always be calculated?

**Comment by yzhangcs** [comment]
@qgallouedec Just wondering have you observed consistant hehaviors in

https://github.com/huggingface/trl/issues/2456

when switching from transformers v4.45.2 to v4.46
I think this two are quite different regarding loss with gradient accumulation.

**Comment by qgallouedec** [comment]
I think you're wrong @yzhangcs:


if I apply your modification:

```diff
- if num_items_in_batch is None:
-     loss = loss / self.args.gradient_accumulation_steps
+ loss = loss / self.args.gradient_accumulation_steps
```

and run the following script with

- `gradient_accumulation_steps = 2` and   `per_device_train_batch_size = 3`
- `gradient_accumulation_steps = 1` and   `per_device_train_batch_size = 6`

```python
import torch
from transformers import AutoModelForCausalLM, Trainer, TrainingArguments
from datasets import Dataset

num_batch = 32
gradient_accumulation_steps = 2  # or 1
per_device_train_batch_size = 3  # or 6
seq_len = 5

eff_batch_size = per_device_train_batch_size * gradient_accumulation_steps
dataset_len = num_batch * eff_batch_size

data = torch.arange(0, dataset_len * seq_len)
data = data.reshape(dataset_len, seq_len)
data = data.tolist()

model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2.5-1.5B").to("cuda")
dataset = Dataset.from_dict({"input_ids": data, "labels": data})

args = TrainingArguments(
    output_dir=f"out_bs_{batch_size}_grad_{grad_accum_steps}_before",
    per_device_train_batch_size= per_device_train_batch_size,
    gradient_accumulation_steps= gradient_accumulation_steps,
    logging_steps=2,
)

trainer = Trainer(model=model, args=args, train_dataset=dataset)

trainer.train()
```

You get the following results:

Screenshot 2024-12-26 at 12 17 02


After the suggested modification, altering the gradient accumulation steps alter the results. While before the modification, everything overlap nicely.

**Comment by yzhangcs** [comment]
@qgallouedec Hi, thank you for sharing these easy-to-run scripts! 
I successfully ran them on my machine with 4 GPUs.
The good news is that I found the loss to be consistent when varying the grad_accum and bsz. 
However, the bad news is that I noticed significant differences in the loss when switching between versions v4.45.2 and v4.47.

FYI

**For v4.45.2, everything seems fine across different settings:**

`gradient_accumulation_steps=1, per_device_train_batch_size=6` 
```
{'loss': 10.5949, 'grad_norm': 188.29049682617188, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                             
{'loss': 8.2312, 'grad_norm': 87.74673461914062, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                 
{'loss': 7.8988, 'grad_norm': 74.35655212402344, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                               
{'loss': 8.0197, 'grad_norm': 52.913124084472656, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}                                                                                                               
{'loss': 6.0704, 'grad_norm': 51.57878875732422, 'learning_rate': 2.916666666666667e-05, 'epoch': 1.25}                                                                                                                
{'loss': 5.8247, 'grad_norm': 56.05608367919922, 'learning_rate': 2.5e-05, 'epoch': 1.5}                                                                                                                               
{'loss': 5.9932, 'grad_norm': 50.10258483886719, 'learning_rate': 2.0833333333333336e-05, 'epoch': 1.75}                                                                                                               
{'loss': 5.3769, 'grad_norm': 65.85218811035156, 'learning_rate': 1.6666666666666667e-05, 'epoch': 2.0}                                                                                                                
{'loss': 4.1261, 'grad_norm': 62.63885498046875, 'learning_rate': 1.25e-05, 'epoch': 2.25}                                                                                                                             
{'loss': 3.5956, 'grad_norm': 67.01679229736328, 'learning_rate': 8.333333333333334e-06, 'epoch': 2.5}                                                                                                                 
{'loss': 3.5619, 'grad_norm': 72.61600494384766, 'learning_rate': 4.166666666666667e-06, 'epoch': 2.75}                                                                                                                
{'loss': 3.6611, 'grad_norm': 67.8575439453125, 'learning_rate': 0.0, 'epoch': 3.0}                                                                                                                                    
{'train_runtime': 56.5843, 'train_samples_per_second': 10.179, 'train_steps_per_second': 0.424, 'train_loss': 6.079538067181905, 'epoch': 3.0}                                                                         
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:55<00:00,  2.30s/it]
```
`gradient_accumulation_steps=2, per_device_train_batch_size=3` 
```
{'loss': 10.5949, 'grad_norm': 188.28981018066406, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                             
{'loss': 8.2312, 'grad_norm': 87.7468032836914, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                  
{'loss': 7.8988, 'grad_norm': 74.3565444946289, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                                
{'loss': 8.0197, 'grad_norm': 52.91275405883789, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}                                                                                                                
{'loss': 6.0704, 'grad_norm': 51.57986068725586, 'learning_rate': 2.916666666666667e-05, 'epoch': 1.25}                                                                                                                
{'loss': 5.8247, 'grad_norm': 56.05683898925781, 'learning_rate': 2.5e-05, 'epoch': 1.5}                                                                                                                               
{'loss': 5.9932, 'grad_norm': 50.103092193603516, 'learning_rate': 2.0833333333333336e-05, 'epoch': 1.75}                                                                                                              
{'loss': 5.3769, 'grad_norm': 65.85319519042969, 'learning_rate': 1.6666666666666667e-05, 'epoch': 2.0}                                                                                                                
{'loss': 4.1261, 'grad_norm': 62.63907241821289, 'learning_rate': 1.25e-05, 'epoch': 2.25}                                                                                                                             
{'loss': 3.5956, 'grad_norm': 67.01693725585938, 'learning_rate': 8.333333333333334e-06, 'epoch': 2.5}                                                                                                                 
{'loss': 3.562, 'grad_norm': 72.61691284179688, 'learning_rate': 4.166666666666667e-06, 'epoch': 2.75}                                                                                                                 
{'loss': 3.6611, 'grad_norm': 67.85787963867188, 'learning_rate': 0.0, 'epoch': 3.0}                                                                                                                                   
{'train_runtime': 62.5724, 'train_samples_per_second': 9.205, 'train_steps_per_second': 0.384, 'train_loss': 6.079543709754944, 'epoch': 3.0}                                                                          
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [01:01<00:00,  2.55s/it]
```

**When I switched to v4.47.0, the first setting remained the same as in v4.45.2:**

`gradient_accumulation_steps=1, per_device_train_batch_size=6` 
```
{'loss': 10.5949, 'grad_norm': 188.29049682617188, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                             
{'loss': 8.2312, 'grad_norm': 87.74673461914062, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                 
{'loss': 7.8988, 'grad_norm': 74.35655212402344, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                               
{'loss': 8.0197, 'grad_norm': 52.913124084472656, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}                                                                                                               
{'loss': 6.0704, 'grad_norm': 51.57878875732422, 'learning_rate': 2.916666666666667e-05, 'epoch': 1.25}                                                                                                                
{'loss': 5.8247, 'grad_norm': 56.05608367919922, 'learning_rate': 2.5e-05, 'epoch': 1.5}                                                                                                                               
{'loss': 5.9932, 'grad_norm': 50.10258483886719, 'learning_rate': 2.0833333333333336e-05, 'epoch': 1.75}                                                                                                               
{'loss': 5.3769, 'grad_norm': 65.85218811035156, 'learning_rate': 1.6666666666666667e-05, 'epoch': 2.0}                                                                                                                
{'loss': 4.1261, 'grad_norm': 62.63885498046875, 'learning_rate': 1.25e-05, 'epoch': 2.25}                                                                                                                             
{'loss': 3.5956, 'grad_norm': 67.01679229736328, 'learning_rate': 8.333333333333334e-06, 'epoch': 2.5}                                                                                                                 
{'loss': 3.5619, 'grad_norm': 72.61600494384766, 'learning_rate': 4.166666666666667e-06, 'epoch': 2.75}                                                                                                                
{'loss': 3.6611, 'grad_norm': 67.8575439453125, 'learning_rate': 0.0, 'epoch': 3.0}                                                                                                                                    
{'train_runtime': 56.4532, 'train_samples_per_second': 10.203, 'train_steps_per_second': 0.425, 'train_loss': 6.079538067181905, 'epoch': 3.0}                                                                         
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:55<00:00,  2.29s/it]
```

**However, the results changed significantly for larger gradient accumulation steps:**

`gradient_accumulation_steps=2, per_device_train_batch_size=3` 
```
{'loss': 21.1898, 'grad_norm': 376.5796203613281, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                              
{'loss': 16.4623, 'grad_norm': 175.4936065673828, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                
{'loss': 15.7976, 'grad_norm': 148.7130889892578, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                              
{'loss': 16.0394, 'grad_norm': 105.82550811767578, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}                                                                                                              
{'loss': 12.1408, 'grad_norm': 103.15972137451172, 'learning_rate': 2.916666666666667e-05, 'epoch': 1.25}                                                                                                              
{'loss': 11.6494, 'grad_norm': 112.11367797851562, 'learning_rate': 2.5e-05, 'epoch': 1.5}                                                                                                                             
{'loss': 11.9865, 'grad_norm': 100.20618438720703, 'learning_rate': 2.0833333333333336e-05, 'epoch': 1.75}                                                                                                             
{'loss': 10.7537, 'grad_norm': 131.70639038085938, 'learning_rate': 1.6666666666666667e-05, 'epoch': 2.0}                                                                                                              
{'loss': 8.2522, 'grad_norm': 125.27814483642578, 'learning_rate': 1.25e-05, 'epoch': 2.25}                                                                                                                            
{'loss': 7.1912, 'grad_norm': 134.03387451171875, 'learning_rate': 8.333333333333334e-06, 'epoch': 2.5}                                                                                                                
{'loss': 7.1239, 'grad_norm': 145.23382568359375, 'learning_rate': 4.166666666666667e-06, 'epoch': 2.75}                                                                                                               
{'loss': 7.3222, 'grad_norm': 135.71575927734375, 'learning_rate': 0.0, 'epoch': 3.0}                                                                                                                                  
{'train_runtime': 64.6658, 'train_samples_per_second': 8.907, 'train_steps_per_second': 0.371, 'train_loss': 12.159087419509888, 'epoch': 3.0}                                                                         
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [01:03<00:00,  2.63s/it]
```

, the loss remains consistent across different gradient accumulation steps. However, this behavior is quite different compared to v4.45.2.

**After upgrading to the latest v4.47.1 and higher (including your new commit), the loss is the same across different grad accum steps**
`gradient_accumulation_steps=1, per_device_train_batch_size=6` 
```
{'loss': 2.119, 'grad_norm': 37.658103942871094, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                               
{'loss': 1.6462, 'grad_norm': 17.549333572387695, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                
{'loss': 1.5798, 'grad_norm': 14.87132740020752, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                               
{'loss': 1.6039, 'grad_norm': 10.582618713378906, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}                                                                                                               
{'loss': 1.2141, 'grad_norm': 10.315776824951172, 'learning_rate': 2.916666666666667e-05, 'epoch': 1.25}                                                                                                               
{'loss': 1.1649, 'grad_norm': 11.211206436157227, 'learning_rate': 2.5e-05, 'epoch': 1.5}                                                                                                                              
{'loss': 1.1986, 'grad_norm': 10.020527839660645, 'learning_rate': 2.0833333333333336e-05, 'epoch': 1.75}                                                                                                              
{'loss': 1.0754, 'grad_norm': 13.170440673828125, 'learning_rate': 1.6666666666666667e-05, 'epoch': 2.0}                                                                                                               
{'loss': 0.8252, 'grad_norm': 12.527780532836914, 'learning_rate': 1.25e-05, 'epoch': 2.25}                                                                                                                            
{'loss': 0.7191, 'grad_norm': 13.403361320495605, 'learning_rate': 8.333333333333334e-06, 'epoch': 2.5}                                                                                                                
{'loss': 0.7124, 'grad_norm': 14.523214340209961, 'learning_rate': 4.166666666666667e-06, 'epoch': 2.75}                                                                                                               
{'loss': 0.7322, 'grad_norm': 13.57152271270752, 'learning_rate': 0.0, 'epoch': 3.0}                                                                                                                                   
{'train_runtime': 58.3558, 'train_samples_per_second': 9.87, 'train_steps_per_second': 0.411, 'train_loss': 1.2159071018298466, 'epoch': 3.0}                                                                          
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:56<00:00,  2.37s/it]
``` 
`gradient_accumulation_steps=2, per_device_train_batch_size=3` 
```
{'loss': 2.119, 'grad_norm': 37.657958984375, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                                  
{'loss': 1.6462, 'grad_norm': 17.54932403564453, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                 
{'loss': 1.5798, 'grad_norm': 14.871335983276367, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                              
{'loss': 1.6039, 'grad_norm': 10.582595825195312, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}                                                                                                               
{'loss': 1.2141, 'grad_norm': 10.315934181213379, 'learning_rate': 2.916666666666667e-05, 'epoch': 1.25}                                                                                                               
{'loss': 1.1649, 'grad_norm': 11.211311340332031, 'learning_rate': 2.5e-05, 'epoch': 1.5}                                                                                                                              
{'loss': 1.1986, 'grad_norm': 10.020581245422363, 'learning_rate': 2.0833333333333336e-05, 'epoch': 1.75}                                                                                                              
{'loss': 1.0754, 'grad_norm': 13.170597076416016, 'learning_rate': 1.6666666666666667e-05, 'epoch': 2.0}                                                                                                               
{'loss': 0.8252, 'grad_norm': 12.527819633483887, 'learning_rate': 1.25e-05, 'epoch': 2.25}                                                                                                                            
{'loss': 0.7191, 'grad_norm': 13.403372764587402, 'learning_rate': 8.333333333333334e-06, 'epoch': 2.5}                                                                                                                
{'loss': 0.7124, 'grad_norm': 14.523296356201172, 'learning_rate': 4.166666666666667e-06, 'epoch': 2.75}                                                                                                               
{'loss': 0.7322, 'grad_norm': 13.571563720703125, 'learning_rate': 0.0, 'epoch': 3.0}                                                                                                                                  
{'train_runtime': 64.584, 'train_samples_per_second': 8.919, 'train_steps_per_second': 0.372, 'train_loss': 1.2159080157677333, 'epoch': 3.0}                                                                          
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [01:03<00:00,  2.63s/it]
```

**But is quite different compared to v4.45.2**

**Comment by yzhangcs** [comment]
I'm not entirely sure where the questions are arising, so I'm diving into the details of the Trainer. I'll keep you updated as soon as I have more information.

**Comment by Doraemonzzz** [comment]
Encountered a similar issue when running the above script.
`transformers=4.47.0`:
```
{'loss': 22.5655, 'grad_norm': 495.53765869140625, 'learning_rate': 4.791666666666667e-05, 'epoch': 0.12}                                                                                                                               
{'loss': 16.8421, 'grad_norm': 284.22906494140625, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                                              
{'loss': 16.2376, 'grad_norm': 177.2020721435547, 'learning_rate': 4.375e-05, 'epoch': 0.38}                                                                                                                                            
{'loss': 15.8786, 'grad_norm': 199.05421447753906, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                                
{'loss': 16.4592, 'grad_norm': 178.1647491455078, 'learning_rate': 3.958333333333333e-05, 'epoch': 0.62}                                                                                                                                
{'loss': 15.2518, 'grad_norm': 179.19195556640625, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                                              
{'loss': 15.9623, 'grad_norm': 126.81049346923828, 'learning_rate': 3.541666666666667e-05, 'epoch': 0.88}                                                                                                                               
{'loss': 15.7668, 'grad_norm': 120.61547088623047, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}
```
`transformers=4.44.2`:
```
{'loss': 11.2828, 'grad_norm': 247.76889038085938, 'learning_rate': 4.791666666666667e-05, 'epoch': 0.12}                                                                                                                               
{'loss': 8.421, 'grad_norm': 142.11448669433594, 'learning_rate': 4.5833333333333334e-05, 'epoch': 0.25}                                                                                                                                
{'loss': 8.1188, 'grad_norm': 88.60110473632812, 'learning_rate': 4.375e-05, 'epoch': 0.38}                                                                                                                                             
{'loss': 7.9393, 'grad_norm': 99.52731323242188, 'learning_rate': 4.166666666666667e-05, 'epoch': 0.5}                                                                                                                                  
{'loss': 8.2296, 'grad_norm': 89.08261108398438, 'learning_rate': 3.958333333333333e-05, 'epoch': 0.62}                                                                                                                                 
{'loss': 7.6259, 'grad_norm': 89.5963134765625, 'learning_rate': 3.7500000000000003e-05, 'epoch': 0.75}                                                                                                                                 
{'loss': 7.9811, 'grad_norm': 63.40541458129883, 'learning_rate': 3.541666666666667e-05, 'epoch': 0.88}                                                                                                                                 
{'loss': 7.8834, 'grad_norm': 60.307289123535156, 'learning_rate': 3.3333333333333335e-05, 'epoch': 1.0}  
```

**Comment by qgallouedec** [comment]
Yes, probably related to the grad accum issue see #34198. As mentionned above, I think that everything works as expected with the dev version

**Pull request merged**
