### PR TITLE
update d_kv'annotation in mt5'configuration

### PR DESCRIPTION
**Pull request by callanwu**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@stevhliu and @MKhalusova

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by MKhalusova** [comment]
Thank you for your contribution! Please make sure that the quality checks pass - here's the [contributing guide](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md). It looks like you need to run `make style`.

**Comment by callanwu** [comment]
> Thank you for your contribution! Please make sure that the quality checks pass - here's the [contributing guide](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md). It looks like you need to run `make style`.

@MKhalusova Hi, thx for your reminder. I have passed all checks!

**Comment by callanwu** [comment]
Add reference:
https://huggingface.co/google/mt5-small/blob/main/config.json
modules output of a loaded mt5-small
```txt
T5Block(
    (layer): ModuleList(
        (0): T5LayerSelfAttention(
        (SelfAttention): T5Attention(
            (q): Linear(in_features=512, out_features=384, bias=False)
            (k): Linear(in_features=512, out_features=384, bias=False)
            (v): Linear(in_features=512, out_features=384, bias=False)
            (o): Linear(in_features=384, out_features=512, bias=False)
        )
        (layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
        )
        (1): T5LayerFF(
        (DenseReluDense): T5DenseGatedGeluDense(
            (wi_0): Linear(in_features=512, out_features=1024, bias=False)
            (wi_1): Linear(in_features=512, out_features=1024, bias=False)
            (wo): Linear(in_features=1024, out_features=512, bias=False)
            (dropout): Dropout(p=0.1, inplace=False)
        )
        (layer_norm): T5LayerNorm()
        (dropout): Dropout(p=0.1, inplace=False)
        )
    )
)
```

**Review by patrickvonplaten — APPROVED** [review]

**Comment by callanwu** [comment]
@MKhalusova @patrickvonplaten Can it be merged now? Are there any further improvements needed:)

**Comment by ArthurZucker** [comment]
Thanks @callanwu 🤗

**Pull request merged**
