### PR TITLE
exclude fsdp from delay_optimizer_creation

### LINKED ISSUE #34024: HF Trainer do not support Pytorch FSDP with FP8; ValueError: You must pass a model and an optimizer together to `accelerate.prepare()` when using TransformerEngine.
### System Info

image
acc_cfg.yml:

compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
fsdp_config:
  fsdp_activation_checkpointing: true
  fsdp_auto_wrap_policy: NO_WRAP
  fsdp_backward_prefetch: NO_PREFETCH
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: true
  fsdp_offload_params: true
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_process_ip: 0.0.0.0
main_process_port: 0
main_training_function: main
mixed_precision: fp8
fp8_config:
  amax_compute_algorithm: max
  amax_history_length: 1024
  backend: TE
  fp8_format: HYBRID
  interval: 1
  margin: 0
  override_linear_precision: false
  use_autocast_during_eval: true
num_machines: 3
num_processes: 24
rdzv_backend: etcd-v2
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

* accelerate launch --config_file acc_cfg.yml train.py $TRAINING_ARGS
* the train.py is any training script that train using transformers.Trainer
* $TRAINING_ARGS are the TrainingArguments plus some path to data
image

### Expected behavior

Train Paligemma model with FSDP and FP8.

### PR DESCRIPTION
**Pull request by eljandoubi**
# What does this PR do?

It passes the model and  the optimizer to accelerate.prepare in order to enable fp8 mixed precision, if any.

Fixes #34024 

## Who can review?

Library:

- trainer: @muellerzr and @SunMarc 

 -->

### CODE REVIEW

**Review by muellerzr — COMMENTED** [review]
Nice :) Can we add a test in `tests/test_trainer.py`? We can set env variables to configure Accelerate properly (`ACCELERATE_MIXED_PRECISION="fp8"` will auto-use TE)

**Comment by eljandoubi** [comment]
The required tests are distributed tests. We need to verify FSDP functionality with and without FP8 mixed precision. The appropriate test file might be tests/test_trainer_distributed.py, but it seems that this file does not currently support FSDP.

**Comment by eljandoubi** [comment]
Is the `test/trainer` folder included in the CI tests? Where can I check the results for `test_trainer_fsdp.py`? @muellerzr @SunMarc

**Comment by muellerzr** [comment]
@eljandoubi we can't run them on the normal CI since GPU runners are not part of PR's.

**Comment by eljandoubi** [comment]
@muellerzr Thank you for the information. I have tested the branch in my code on a multi-node, multi-GPU setup using FSDP mode, both with and without FP8 mixed precision, and it worked as expected. Please let me know if you encounter any issues on your end.

**Comment by eljandoubi** [comment]
@muellerzr Any updates regarding this PR?

**Review by muellerzr — APPROVED** [review]
Thanks! Can you do `pip install -e .[quality]` followed by `make fixup`? I'll then pull it locally to test on my 4090 system and we should be set!

**Comment by eljandoubi** [comment]
I have done `make fixup`.

**Review by ArthurZucker — APPROVED** [review]
Don't worry we'll merge as is, failing tests are unrelated!

**Pull request merged**
