### PR TITLE
Make predict() close progress bars after finishing (#17952)

### LINKED ISSUE #17952: Trainer.predict multiple progress bars
### System Info

- `transformers` version: 4.21.0.dev0
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Huggingface_hub version: 0.8.1
- PyTorch version (GPU?): 1.11.0+cu113 (False)
- Tensorflow version (GPU?): 2.8.2 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

@sgugger 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

```
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
trainer = Trainer(model)
trainer.predict([{"input_ids": torch.zeros(20).long()} for _ in range(48)])  # [6/6  00:03]
trainer.predict([{"input_ids": torch.zeros(20).long()} for _ in range(96)])  # [6/6  00:12] despite having more examples
```

### Expected behavior

Two progress bars, one of length 6 and the other of length 12.

### PR DESCRIPTION
**Pull request by neverix**
Fixes #17952 by adding an `on_predict` callback. 

## Who can review?

@sgugger

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Very clean, thanks a lot!

**Comment by neverix** [comment]
Not sure about the tests, should they be there for notebooks too? I'll go with this for now

**Comment by sgugger** [comment]
I just triggered all them by pushing a copy of your branch in the main fork of the repo, circleCI is very finnicky. Let's check everything is green!

**Comment by sgugger** [comment]
Failure is flaky, so this is good to merge, thanks again!

**Pull request merged**
