### PR TITLE
Fix windows err with checkpoint race conditions

### PR DESCRIPTION
**Pull request by muellerzr**
# What does this PR do?

Windows doesn't like python trying to open files, so makes the additional race condition check to be non-windows based

Fixes # (issue)

https://github.com/huggingface/transformers/pull/28364

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@amyeroberts

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Thanks for adding this fix! 

Only question is that doesn't this mean that the race condition this check helped resolve isn't working for windows? Is there an equivalent check that could be added instead of skipping altogether?

**Comment by muellerzr** [comment]
@amyeroberts I'm not a windows expert but after looking the only alternative would to be to use the atomic `os.replace()` since it's atomic *except* it doesn't work on folders, so there's not really a good solution here for this. 

I don't think we have too many multi-node windows users (as this seems fairly uncommon, I'd expect more UNIX-based multinode users), so it's okay for now. If a user reports an issue hopefully more users will know a windows-based solution, or we can try a hacky-workaround using `replace()` and checking for a particular file that would exist in the folder. 

Let me know if you're comfortable with this, else I can include the hack in here

**Comment by amyeroberts** [comment]
@muellerzr Sounds good to me! Thanks for looking into this 🤗

**Review by amyeroberts — APPROVED** [review]
Thanks again!

**Comment by adamkolar** [comment]
Just FYI, this is not a race condition, the error is because you're trying to call os.open() on a directory (not a file), which doesn't work in Windows. See: https://stackoverflow.com/questions/21785127/open-a-directory-on-windows-permission-denied

**Comment by amyeroberts** [comment]
@adamkolar Yep - this PR is addressing the permissions issue with Windows. The permission issue arose from a check that was introduced to handle race conditions when renaming checkpoints #28364

**Comment by adamkolar** [comment]
@amyeroberts I see, my bad

**Pull request merged**
