### PR TITLE
Refactor BartModel so that input checks are handled within enc/dec

### LINKED ISSUE #3133: BART: move boilerplate code inside encoder/decoder
# 🚀 Feature request

Could we move the boilerplate code in the `BartModel` `forward()` method inside the `forward()` methods for the encoder and decoder? That way, the encoder and decoder can be called separately as independent modules more easily.

## Motivation

Currently, there's some cleanup work that is done before calling `BartEncoder.forward()` and `BartDecoder.forward()` (looks like attention mask flipping and preparing dummy outputs). If we want to call the encoder and decoder separately from our own code (eg to use Bart as an encoder, or limit which parts are fine tuned) we currently have to re-implement this code.

If we move this logic inside the encoder and decoder, such that `BartModel.forward()` is a thin wrapper around the encoder+decoder, this kind of work would be much easier.

Example usage:
```
model = BartModel.from_pretrained(...)
inputs = tokenizer.encode('I want to classify this text.')
encoding = model.encoder(inputs)
predictions = my_classifier(encoding)
```

## Your contribution

I could put together a PR for this if you agree?

(cc @sshleifer )

### PR DESCRIPTION
**Pull request by tomhosking**
Implementing #3133 

I've left the code that creates dummy inputs and checks/filters the outputs, this could potentially also be moved to `BartEncoder` and `BartDecoder`.

### CODE REVIEW

**Comment by sshleifer** [comment]
have you checked whether this breaks `RUN_SLOW=1 pytest tests/test_modeling_bart.py`? There is some subtletly with caching+remaking the attention mask everytime.

**Comment by tomhosking** [comment]
Looks good I think?

```
========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /Users/tom/dev/transformers
plugins: xdist-1.31.0, forked-1.1.3
collected 30 items                                                                                                                                                       

tests/test_modeling_bart.py ...........s.................s                                                                                                         [100%]

============================================================================ warnings summary ============================================================================
.venv/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15
  /Users/tom/dev/transformers/.venv/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================== 28 passed, 2 skipped, 1 warning in 393.65s (0:06:33) ==========================================================
```

**Comment by sshleifer** [comment]
Awesome, LGTM. Will wait for Thomas to merge.

**Review by thomwolf — APPROVED** [review]
LGTM as well

**Pull request merged**
