### PR TITLE
[WIP] Add Grounding DINO

### LINKED ISSUE #25423: Add Grounding DINO
### Model description

Grounding DINO is a zero-shot object detection developed by IDEA-Research presented in the paper

[Grounding DINO: Marrying DINO with Grounded Pre-Training for Open-Set Object Detection](https://arxiv.org/abs/2303.05499)

The model uses a Swin transformer and BERT as image and text backbones, respectively,  a feature enhancer and a cross-modality decoder.

### Open source status

- [X] The model implementation is available
- [X] The model weights are available

### Provide useful links for the implementation

Model implementation and weights can be found in their GitHub repo: https://github.com/IDEA-Research/GroundingDINO/tree/main#luggage-checkpoints

### PR DESCRIPTION
**Pull request by EduardoPach**
# What does this PR do?

This PR adds Grounding DINO

Fixes #25423 

To-Do's:

- [x]  Port vision backbone
- [x]  Port Text backbone
- [ ]  Port Feature Enhancer
- [ ]  Port Cross-Modality Decoder

### CODE REVIEW

**Comment by sgugger** [comment]
cc @amyeroberts for information. Please let us know when your PR is ready for review!

**Comment by EduardoPach** [comment]
@amyeroberts hey, I've actually started a new branch to port the mode because in the branch from this PR I've done `add-new-model-like` and then `swin`, but talking to @NielsRogge he mentioned that starting from `deformable-detr` would be easier (which was a SUPER helpful tip btw). Should I close this PR and open yet a new one with the correct branch?

**Comment by amyeroberts** [comment]
@EduardoPach Do whatever is easiest for you in terms of code management. If you open a new PR, just make sure to link to it in a comment on this one so it can be easily tracked.

**Comment by EduardoPach** [comment]
@amyeroberts opened a new PR in https://github.com/huggingface/transformers/pull/26087 as mentioned. Should I close this one?

**Comment by amyeroberts** [comment]
@EduardoPach I can close it for you :)

**Pull request closed without merging**
