### PR TITLE
nn.Identity is not required to be compatible with PyTorch < 1.1.0 as the minimum PyTorch version we currently support is 1.10.0

### PR DESCRIPTION
**Pull request by ji-huazhong**
# What does this PR do?

As the title says.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@muellerz and @pacman100

### CODE REVIEW

**Comment by ydshieh** [comment]
I am not sure I understand. We already say goodbye to pytorch 1.9 in #24080. Could you elaborate with a bit more detail?

**Comment by statelesshz** [comment]
> I am not sure I understand. We already say goodbye to pytorch 1.9 in #24080. Could you elaborate with a bit more detail?

Apologies for the confusion. I provided incorrect information about the minimum supported version of transformers. :(
Make some changes to make things look more accurate.

**Review by ydshieh — APPROVED** [review]
Looks like `torch.nn.Identity` is available in `torch>=1.1.0` (released on `May 1, 2019`).

Thank you!

**Review by amyeroberts — APPROVED** [review]
Thanks for updating!

**Pull request merged**
