### PR TITLE
Let server decide default repo visibility

### PR DESCRIPTION
**Pull request by Wauplin**
Until now, all repos were public by default when created without passing the `private` argument. This meant that passing `private=False` or `private=None` was strictly the same. This is not the case anymore. Enterprise Hub offers organizations to set a default visibility setting for new repos. This is useful for organizations forbidding public repos for security matters. This PR mostly updates some docstrings + the default value for `hub_private_repo` in Trainer's args.

This PR doesn't create any breaking change. The real update has been done server-side when introducing the new Enterprise Hub feature. Related to https://github.com/huggingface/huggingface_hub/pull/2679.

### CODE REVIEW

**Comment by Wauplin** [comment]
Note: CI seems to be failing but I don't think it's related to this PR
```py
> python3 .circleci/parse_test_outputs.py --file tests_output.txt --fail
   1 failed because `AssertionError: 0.0002062409 not less than or equal to 0.0002 : outputs.logits` -> Difference between PyTorch and TF is 0.00020624090393539518 (>= 0.0002) for Data2VecVisionForSemanticSegmentation
   1 failed because `AssertionError: 1.9396484e-05 not less than or equal to 1e-05 : outputs.hidden_states_1` -> Difference between PyTorch and TF is 1.9396484276512638e-05 (>= 1e-05) for SwiftFormerModel
Number of failed tests: 2
```

**Review by ArthurZucker — APPROVED** [review]
Failing tests are indeed unrelated ! LGTM!

**Comment by Wauplin** [comment]
(can I let you merge it? I don't have permissions myself since failing CI)

**Comment by ArthurZucker** [comment]
Of course!

**Pull request merged**
