### PR TITLE
Fix breaking change in `onnxruntime` for ONNX quantization

### PR DESCRIPTION
**Pull request by severinsimmler**
Using `onnxruntime.quantization.quantize` has been deprecated since a while:

```
WARNING:root:onnxruntime.quantization.quantize is deprecated.
         Please use quantize_static for static quantization, quantize_dynamic for dynamic quantization.
```

and has been removed from `onnxruntime` in v1.12.0 (released 6 days ago). This breaks quantization in `transformers.convert_graph_to_onnx`.

I have migrated `onnxruntime.quantization.quantize` to `transformers.convert_graph_to_onnx.quantize` to preserve compatibility.

## Who can review?
@mfuntowicz

### CODE REVIEW

**Comment by severinsimmler** [comment]
@JingyaHuang @lewtun @michaelbenayoun Happy to implement changes if you have any suggestions 😊

**Review by lewtun — APPROVED** [review]
Thanks a lot for updating the quantization function to the new `onnxruntime` API @severinsimmler !

The code LGTM - have you checked that the slow tests pass locally on your end? You can run them with:

```
RUN_SLOW=1 pytest tests/onnx/test_onnx.py
```

If these pass, I think this can be merged.

Gently pinging @LysandreJik or @patrickvonplaten for final approval

**Comment by severinsimmler** [comment]
Thanks @lewtun :pray: All tests are passing on my machine:

image

**Review by LysandreJik — APPROVED** [review]
Sounds good, thanks for the PR @severinsimmler, and thanks for checking @lewtun!

**Pull request merged**
