### PR TITLE
[i18n-KO] Translated docs: ko: pr_checks.md to Korean

### PR DESCRIPTION
**Pull request by sronger**
# What does this PR do?

Translated the `pr_checks.md` file of the documentation to Korean.
Thank you in advance for your review. 

Part of https://github.com/huggingface/transformers/issues/20179

## Before reviewing
- [x] Check for missing / redundant translations (번역 누락/중복 검사)
- [x] Grammar Check (맞춤법 검사)
- [x] Review or Add new terms to glossary (용어 확인 및 추가)
- [x] Check Inline TOC (e.g. `[[lowercased-header]]`)
- [x] Check live-preview for gotchas (live-preview로 정상작동 확인)

## Who can review? (Initial)

@sronger, @TaeYupNoh, @kj021, @HanNayeoniee, @eenzeenee, @sim-so

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review? (Final)

### CODE REVIEW

**Review by sim-so — CHANGES_REQUESTED** [review]
첫 PR 고생 많으셨습니다! 🥳
마침 문서 번역을 위해 PR을 하고 있는 저희에게 참고가 되는 문서였어요.

특별한 오류를 발견하지 못해서 한국어 표현 위주로 리뷰를 드려보았는데요,
좋은 문장에 대한 생각은 모두 다를 수 있으니 모두 반영하지 않고 참고만 해주셔도 괜찮습니다! 😊

**Review by TaeYupNoh — COMMENTED** [review]
LGTM!

**Review by stevhliu — COMMENTED** [review]
Thanks for your translation! We've recently added a [section](https://huggingface.co/docs/transformers/main/en/pr_checks#check-copies) describing how the `check_copies` mechanism works. Would you like to translate that section as well? :)

**Comment by sronger** [comment]
Translation completed!
May you please review this PR? :)
@sgugger, @ArthurZucker, @eunseojo, @stevhliu

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
