### PR TITLE
add in layer tf clip text tokenizer

### PR DESCRIPTION
**Pull request by piEsposito**
# What does this PR do?

- Adds in layer `TFCLIPTokenizer` to enable serialization and serving it with TF Serving

Addresses first step of #19992 

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. -> https://github.com/huggingface/transformers/issues/19992
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by piEsposito** [comment]
Just need to figure out where to append `eos_token` and `bos_token` within the tokenizers.

**Comment by sgugger** [comment]
cc @Rocketknight1 so it's on your radar when the PR is ready :-)

**Comment by piEsposito** [comment]
Clip </w> formatting is too cursed, I'm thinking of jump ship and do the tokenizer from Roberta instead haha.

**Comment by piEsposito** [comment]
I was gonna jump ship, but then this absolute beast @pedrogengo came in and found a magic way to make it work. Making him a coauthor of the PR bc of that.

We are not supporting batches (yet).

**Comment by calvingiles** [comment]
Did this ever get resolved?

**Pull request closed without merging**
