### PR TITLE
TF train_step docstring

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

Small PR that elaborates on the beautiful black magic behind our TF `train_step`.

### CODE REVIEW

**Review by Rocketknight1 — APPROVED** [review]

**Comment by gante** [comment]
Tagging @sgugger to check @Rocketknight1's question above ☝️

**Comment by Rocketknight1** [comment]
Also, don't forget `make style`!

**Review by sgugger — COMMENTED** [review]
Can we break the docstring in several paragraphs? For instance at the "However" and then "This is" (but whatever you think is best works too).

**Comment by gante** [comment]
> Can we break the docstring in several paragraphs? For instance at the "However" and then "This is" (but whatever you think is best works too).

Done 👍

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
