### PR TITLE
[tests] make cuda-only tests device-agnostic  

### PR DESCRIPTION
**Pull request by faaany**
Currently this test is restricted to run on CUDA, but it can also run on other accelerators like XPU.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @ydshieh

**Comment by ydshieh** [comment]
LGTM, but is still in draft mode or ready to go?

**Review by ydshieh — APPROVED** [review]
Thanks

**Comment by ydshieh** [comment]
@Rocketknight1 Maybe we can merge once you approved?

**Comment by Rocketknight1** [comment]
This seems significant enough that it might need a core maintainer! cc @LysandreJik @ArthurZucker

**Comment by ydshieh** [comment]
I talked to ArthurZucker offline and we agree that I have some level of permissions to merge PRs like this.

**Pull request merged**
