### PR TITLE
Check link validity

### PR DESCRIPTION
**Pull request by rlouf**
We would like to make sure that every download link in the code base works. The best way to do this is to check automatically with the CI; this also prevents us from merging code with broken links.

This PR adds a small script that:

- Lists all source code files
- Extracts links with a regexp
- Performs HEAD requests to check the validity of each link
- Returns an error if at least one link is broken, along with the list of all broken links.

I also add a Circle CI workflow `repository-consistency` with a small machine that runs this script. It could be used to enforce things such as coding styles etc in the future.

For now the links are checked sequentially; if it turns out to take too long we can use `aiohttp` to run the queries concurrently.

_Edit:_ commits squashed

### CODE REVIEW

**Comment by rlouf** [comment]
It works so well the CI failed because of a broken link :)

**Review by LysandreJik — APPROVED** [review]
Very nice!!

**Comment by thomwolf** [comment]
Ok great!

Maybe in the future, we would like to ensure model files can also be loaded without but this will suffice for now (and be fast)!

merging

**Comment by rlouf** [comment]
Yes it would be great too! The only limit is the RAM available and the bandwidth on Circle CI's side. Assuming they're big enough we can download and load all files at the same time, it is easy to do. Maybe next time a related issue pops up?

**Comment by thomwolf** [comment]
Ok great, merging, thanks @rlouf

**Pull request merged**
