### PR TITLE
[testing] add timeout_decorator

### PR DESCRIPTION
**Pull request by sshleifer**
This is a simple way to make sure code doesn't get slower over time. Since it is a new dependency, I wanted to show a tiny PR before I use it more.

### CODE REVIEW

**Comment by julien-c** [comment]
Feels like it could be reimplemented in a few lines of code – do we need to add a new dependency for this?

**Comment by sshleifer** [comment]
I copy pasted it. Would love to understand more about the adding a dependency vs maintaining code tradeoff!

**Comment by patrickvonplaten** [comment]
I think that's a great addition! Trying to keep the tests short is very important I think :-)

**Review by patrickvonplaten — APPROVED** [review]

**Comment by julien-c** [comment]
This is too long to copy/paste, so I'd see two options:
- add it as a dependency to extras["testing"]
- take just the signals based implem, clean it up/distill it down to a few (10) lines of code and add it in `tests/`

**Comment by sshleifer** [comment]
I think we should do `extras['testing']` (that was my first attempt on this PR).
If we delete the `signals=False` logic, I don't think circleci will work in distributed testing mode.

**Pull request merged**
