### PR TITLE
update remaining `Pop2Piano` checkpoints

### PR DESCRIPTION
**Pull request by susnato**
# What does this PR do?

The remaining files are transferred to the original `Pop2Piano` repository on HuggingFace Hub ([PR link](https://huggingface.co/sweetcocoa/pop2piano/discussions/7)). 
This PR updates all the remaining checkpoints.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for updating!

**Comment by amyeroberts** [comment]
@susnato Am I OK to merge this - or are there other changes you'd like to push beforehand?

**Comment by susnato** [comment]
We can merge. 

I wanted to ask this - Later this week I will update the [pop2piano demo](https://huggingface.co/spaces/sweetcocoa/pop2piano) to use the `transformers` and also add some features to the space, is it a good idea to also add that at the end of the `pop2piano.md` file once it is finished, so we can showcase this model in a easier way?

**Comment by amyeroberts** [comment]
@susnato Great - yes, it'd be great to add examples for the model! For a spaces demo, this is normally added as a badge on the page e.g. like [this for XLNet](https://github.com/huggingface/transformers/blob/245dcc49ef9862a7165aec7be9c4a3299b8d06a1/docs/source/en/model_doc/xlnet.md?plain=1#L23C1-L23C1), and corresponding [doc page](https://huggingface.co/docs/transformers/v4.32.1/en/model_doc/xlnet#overview).

**Pull request merged**
