### PR TITLE
SuperPointModel -> SuperPointForKeypointDetection

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

Renames `SuperPointModel` to `SuperPointForKeypointDetection` and adds `AutoModelForKeypointDetection`. This is more in-line with our library's pattern, where `AutoModel` returns a base model and `AutoModelForXxx` will return task specific outputs. 

Originally I had requested this, as the model doesn't have an obvious task-specific head on-top. @NielsRogge highlighted the discrepancy and it was agreed offline using the task-specific class was better. 

There is currently no `SuperPointModel` class, but we can add this later if needed

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]
Thanks 😃

**Comment by amyeroberts** [comment]
cc @sbucaille As you're working on adding SuperGlue - and apologies for my previous bad advise to just use AutoModel!

**Comment by amyeroberts** [comment]
Yes, but in this case it's needed for the SuperGlue implementation

**Comment by amyeroberts** [comment]
Because we need an auto model to be used within the modeling file for SuperPoint, similar to what we do in llava

**Comment by sbucaille** [comment]
@amyeroberts I was exactly about to point the problem I would reach with SuperGlue, since it uses the outputs of models like SuperPoint (keypoints data) and not images (pixel_values). But we will be able to discuss this in the appropriate [PR](https://github.com/huggingface/transformers/pull/25697) (btw you can reopen it as I'll push new changes in the coming days). Anyway thanks for the anticipation ! :hugs:

**Pull request merged**
