### PR TITLE
Translation/italian: added pipeline_tutorial.mdx [Issue: #17459]

### PR DESCRIPTION
**Pull request by nickprock**
- added italian translation of pipeline_tutorial.mdx
- updated _toctree.yml

### CODE REVIEW

**Comment by mfumanelli** [comment]
Hi @nickprock! Thank you very much for your contribution to the 🤗 Italian documentation! 🌈
Can I ask you if you can fix a couple of things?

- "Usare uno specifico tokenizer or modello" -->  "Usare uno specifico tokenizer o modello"
- "La mansione text-generation ha un [~generation_utils.GenerationMixin.generate] metodo" --> La mansione text-generation ha un metodo [~generation_utils.GenerationMixin.generate]
- Here seeing the formatting I think there are missing quotation marks "[AutoTokenizer']. Ad esempio, carica la classe [AutoModelForCausalLM`]", I think the problem is also there in the English doc, if you can fix it for the ita one and then I will fix it for the eng version
- "Trova un [audio classification](https://huggingface.co/models?pipeline_tag=audio-classification) modello  per eseguire emotion recognition" --> "Trova un modello per la [classificazione audio](https://huggingface.co/models?pipeline_tag=audio-classification)  per eseguire un compito di riconoscimento automatico delle emozioni"

Thanks! 🚀

**Comment by nickprock** [comment]
Thanks @mfumanelli,
I correct and submit.
One question, how do you translate task? I used "compito", "mansione", "attività".

**Comment by omarespejel** [comment]
Thanks for the great PR @nickprock! And @mfumanelli for the amazing review 🚀

**Comment by mfumanelli** [comment]
Yes @nickprock, I agree with you, I also use "compito." It would be more natural for me to leave the English word "task" directly, so I also had this doubt. In my opinion, "compito", "mansione" and "attività" are actually the best words with which to translate the word "task".  🤗

btw, looks perfect to me now!

**Review by omarespejel — APPROVED** [review]

**Comment by omarespejel** [comment]
@nickprock grazie for the great PR! @mfumanelli grazie for the detailed review! 

I am learning Italian with your work! 

@sgugger LGTM :)

**Comment by nickprock** [comment]
sorry, there was a little problem.  I absentmindedly pushed my updates to the same branch.  I undo but a check fails

**Comment by sgugger** [comment]
Thanks a lot for this new translation (the failure in Build PR doc is spurious here).

**Pull request merged**
