### PR TITLE
Fix `DepthEstimationPipeline`'s docstring

### LINKED ISSUE #28729: Depth Estimation Pipeline docstrings are wrong
The docstring is a paste from the image classification pipeline it seems https://github.com/huggingface/transformers/blob/main/src/transformers/pipelines/depth_estimation.py#L54-L83 . The correct output, as per https://huggingface.co/docs/transformers/main/tasks/monocular_depth_estimation, should be a dictionary with an image and a tensor

cc @amyeroberts @ydshieh

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Fix #28729

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for the quick fix! 🔧

**Review by osanseviero — APPROVED** [review]
Thanks! 
cc @Wauplin

**Review by Wauplin — COMMENTED** [review]
Thanks @ydshieh! I think the first line should also be updated: `Assign labels to the image(s) passed as inputs.`

**Comment by ydshieh** [comment]
Thanks @Wauplin Will update it (along with `top_k` too maybe!)

**Comment by ydshieh** [comment]
FYI:

Also changed

> Assign labels to the image(s) passed as inputs.

to 

> Predict the depth(s) of the image(s) passed as inputs.

https://github.com/huggingface/transformers/pull/28733/commits/22ff25c6cec0eba56ea78646c3b88ec9f728e86a

**Pull request merged**
