### PR TITLE
[Gradient checkpoining] Update Wav2Vec scripts

### PR DESCRIPTION
**Pull request by falcaopetri**
# What does this PR do?

This PR makes the Wav2Vec scripts compatible with the changes introduced in #13657 regarding the `gradient_checkpointing` feature/argument.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@stas00, @LysandreJik, @patrickvonplaten

### CODE REVIEW

**Comment by stas00** [comment]
FYI, this is a duplicate of https://github.com/huggingface/transformers/pull/13964, but I think yours is better since mine doesn't change the flax example.

**Comment by falcaopetri** [comment]
Hi and sorry for the duplicate. I checked for similar issues but forgot to search for PRs.

Besides the missed flax example, #13964 possibly runs into this warning: [`Passing gradient_checkpointing to a config initialization is deprecated and will be removed in v5 Transformers.`](https://github.com/huggingface/transformers/blob/cde0c750af2fae6848ed3ee8be381b4f1230ecd0/src/transformers/configuration_utils.py#L339)

The present PR follows the recommendation from [Performance#Gradient Checkpointing](https://github.com/huggingface/transformers/blob/cde0c750af2fae6848ed3ee8be381b4f1230ecd0/docs/source/performance.md#gradient-checkpointing).

**Comment by stas00** [comment]
No need to be sorry, I was just pointing to maintainers that there are 2 of the kind so it's easy to deal with them at once.

Further, https://github.com/huggingface/transformers/pull/13877 moved wav2vec2 to supported examples, but for reason these examples didn't get ported.

**Comment by stas00** [comment]
@patrickvonplaten, I think we should have merged this PR instead of https://github.com/huggingface/transformers/pull/13964
as this one has additional fixes. I completely forgot that there was a better version.

But it needs to be re-based and conflict removed first.

Will you support this PR if it's synced up?

**Comment by patrickvonplaten** [comment]
Thanks for updating the scripts!

**Pull request merged**
