### PR TITLE
Support subfolder with `AutoProcessor`

### PR DESCRIPTION
**Pull request by JingyaHuang**
# What does this PR do?

Support `subfolder` option in `AutoProcessor`. Currently we are not able to load processors in subfolder, eg.

```python
from transformers import AutoProcessor

AutoProcessor.from_pretrained("sentence-transformers/clip-ViT-B-32", subfolder="0_CLIPModel", trust_remote_code=False)
```

We will get following error:

```
*** OSError: sentence-transformers/clip-ViT-B-32 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co/sentence-transformers/clip-ViT-B-32/main' for available files.
```

However I am able to load processor in subfolder with directly:

```python
import transformers

transformers.CLIPProcessor.from_pretrained.from_pretrained("sentence-transformers/clip-ViT-B-32", subfolder="0_CLIPModel", trust_remote_code=False)
```

cc. @fxmarty FYI our [`maybe_load_preprocessors`](https://github.com/huggingface/optimum/blob/037c982eee72a0c6800837a9e97e8cbefbabf08b/optimum/utils/save_utils.py#L27) is not able to store [sentence transformers clip processor](https://huggingface.co/sentence-transformers/clip-ViT-B-32/tree/main) without this.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by amyeroberts** [comment]
Hi @JingyaHuang, thanks for opening this PR! 

My understanding is that using `subfolder` was deliberately not exposed for use in the `AutoXxx` API. There's an internal discussion here: https://huggingface.slack.com/archives/C014N4749J9/p1707474720126079

Which, tbh, is a bit surprising as it works with other Auto APIs like AutoModel, so I'd be pro adding it here. @ydshieh do you know why it was added originally?

**Comment by JingyaHuang** [comment]
Thanks @amyeroberts ! Yeah it's a bit suprise, since in Optimum we store config for compiled models, and it works fine with subfolder for `AutoTokenizer` and `AutoFeatureExtractor`, until we got some issues with some CLIP checkpoints under subfolders.

**Review by ArthurZucker — COMMENTED** [review]
I don't mind having this if this removes some confusing / is expected from our usual api!

**Comment by JingyaHuang** [comment]
From optimum perspective, it would be really nice if we could enable subfolder with AutoProcessor, otherwise we might need to override it... @ArthurZucker @amyeroberts

**Comment by ydshieh** [comment]
Will take a look

**Comment by ydshieh** [comment]
Hi. First of all,

> subfolder was deliberately not exposed for use in the AutoProcessor API
this is not the case, and [the internal discussion](https://huggingface.slack.com/archives/C014N4749J9/p1707474720126079) is about that model type is not exposed publicly, not about `subfolder` not being used in `AutoProcessor`.

Looking at the two parts inside 

> config_dict, _ = ImageProcessingMixin.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)
and
> config_dict, _ = FeatureExtractionMixin.get_feature_extractor_dict(
in `AutoProcessor.from_pretrained`, the first line is called without failure (and we get `config_dict`), but the second one fails.

Looking at the definitions of these 2 methods, you will see `subfolder` is used in the body of `get_image_processor_dict` but not in `get_feature_extractor_dict` (or even in the file `src/transformers/feature_extraction_utils.py`).

So, to me, it looks like `FeatureExtractor` is created (much) earlier than `ImageProcessor` and not being updated properly. @JingyaHuang 's work in this PR is the way to go.

**Comment by ydshieh** [comment]
However, there is one thing I still think strange. Let me take a deeper look before merging this PR 🙏

**Review by amyeroberts — APPROVED** [review]
Thanks for adding!

**Pull request merged**
