### PR TITLE
fixed grammatical omissions and  fixed typos.

### PR DESCRIPTION
**Pull request by YOGENDERSS**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by YOGENDERSS** [comment]
This PR fixes a typo or improves the docs.

**Comment by YOGENDERSS** [comment]
@sgugger could you please review this sir.

**Comment by YOGENDERSS** [comment]
@codePerfectPlus sir could you please review if possible.

**Review by sgugger — COMMENTED** [review]
Thanks for your PR. It mostly changes one style we chose that is perfectly valid (pretrained is used way more than pre-trained, the last and in an enumeration is optional, and in the enumeration of models we are not doing sentences, so there is no need for verbs.

If you want to focus it on real typo fixes, happy to re-review!

**Comment by YOGENDERSS** [comment]
@sgugger could you check my one more pr. there i have found one link not working and i have made the changes.

**Pull request closed without merging**
