### PR TITLE
fix: repair depth estimation multiprocessing

### LINKED ISSUE #33288: 'DepthEstimationPipeline' object has no attribute 'image_size' when num_workers > 0
### System Info

OS: Linux (Ubuntu 22)
transformers: 4.44.2
torch: 2.3.1

### Who can help?

@Narsil 

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

See code snippet below to reproduce:

```python

from transformers import pipeline
import torch

pipe = pipeline(model="LiheYoung/depth-anything-base-hf", device=0, num_workers=1)

# To reproduce, the input needs to be an array of images, and it can just be 1 image in the array.
# A single image not placed in an array will not reproduce the issue.
pipe(["<YOUR IMAGE>"])
```

This results in:
```
File "[...]/site-packages/transformers/pipelines/depth_estimation.py", line 109, in postprocess
    predicted_depth.unsqueeze(1), size=self.image_size[::-1], mode="bicubic", align_corners=False
AttributeError: 'DepthEstimationPipeline' object has no attribute 'image_size'
```

Upon investigation, you will see that `self.image_size` is set in `preprocess()` which is executed by one of the workers while (I believe) `postprocess()` is executed on the main process. Because these 2 processes do not share the same class instance of DepthEstimationPipeline, `self.image_size` ends up never being defined in the main processes's address space. This makes the DepthEstimationPipeline only work when `preprocess()` and `postprocess()` are executed on the same process when num_workers=0.

A quick fix would be for DepthEstimationPipeline to accept an `image_size` argument which can be passed to `preprocess_params --> preprocess()`. Then the user can create a pipeline by doing
```python
pipe = pipeline(model="LiheYoung/depth-anything-base-hf", device=0, num_workers=1, image_size=(256,256))
```
for example. Of course, it's not as clean since it doesn't dynamically infer the image sizes from the user's input, but it should help. Any other ideas?

### Expected behavior

For `DepthEstimationPipeline.__call__()` to execute successfully with multiprocessing.

### PR DESCRIPTION
**Pull request by niqodea**
# What does this PR do?

Fixes #33288 by forwarding `target_size` in a way that is consistent with other pipelines.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@Rocketknight1

### CODE REVIEW

**Comment by niqodea** [comment]
Let me know if you think it could make sense to add some tests to cover the failure mode from #33288, I would gladly take care of that!

**Review by Rocketknight1 — APPROVED** [review]
Yes! Setting `self.image_size` is obviously a bad pattern, so thank you for this fix.

I'm happy to merge as-is, but if you want to write tests to ensure no regressions, I'm happy to wait for those too. Thank you for the PR either way!

**Comment by niqodea** [comment]
GTM to merge as is, I will try to add the tests in a follow-up. Thank you!

**Comment by LysandreJik** [comment]
I'd be down for the tests to be in the same PR if you have the bandwidth @niqodea :)

**Review by amyeroberts — APPROVED** [review]
Thanks for adding this!

**Comment by niqodea** [comment]
I added the test `test_multiprocess` and verified that it passes with my change and fails without it.

I had to come up with the test from scratch as I couldn't find anything similar in other places. Technically, it makes sense to add this test to all pipelines, since all of them might now or in the future contain bugs that only take place in a multiprocess setting, but maybe I would wait for the occurrence of another multiprocess-related bug somewhere else before doing so.

**Comment by niqodea** [comment]
Some questions about the outlined workflow above:

* Do I need this if the test I added is not slow?
* I cannot seem to edit this PR's labels, do I have permission?
* Since in this case I would like to test a _pipeline_, and not a model, what should I write in the commit message?

**Comment by niqodea** [comment]
Ok to merge for me too 👍

**Comment by Rocketknight1** [comment]
Nice, thank you for the PR!

**Pull request merged**
