### PR TITLE
Pin Keras for now

### PR DESCRIPTION
**Pull request by Rocketknight1**
With Keras 3 on the horizon, let's pin Keras versions to ensure things don't break until we can transition properly

### CODE REVIEW

**Review by ArthurZucker — APPROVED** [review]

**Review by ydshieh — APPROVED** [review]
Nice, thank you!

**Comment by ydshieh** [comment]
There are a few `pip install -U --upgrade-strategy eager tensorflow_probability` in `.circleci/create_circleci_config.py`. I guess we will need to pin them too. But not sure if we already know the corresponding version.

**Comment by Rocketknight1** [comment]
@ydshieh yeah, `tensorflow_probability` versions don't seem to be linked to TF versions. It also doesn't seem to use Keras much - hopefully we can leave it unpinned for now, and do a PR to pin it if it becomes a problem later!

**Comment by ydshieh** [comment]
(remark: I did see some failing before when `tensorflow_probability` complained about the TF version is not compatible with it - or vice versa 😅 )

**Pull request merged**
