### PR TITLE
Reintroduce clean_text on BertTokenizer call which was removed by mistake in #4723

### LINKED ISSUE #7665: tokenizer_bert.py not call _clean_text?
for transformers/src/transformers/tokenization_bert.py, there is a function called _clean_text.
But seems this function is not be called at all?

In google bert(https://github.com/google-research/bert/blob/master/tokenization.py) there exists a same function and that function has been called at the beginning of the tokenization.

### PR DESCRIPTION
**Pull request by mfuntowicz**
Signed-off-by: Morgan Funtowicz <funtowiczmo@gmail.com>

closes #7665

### CODE REVIEW

**Review by n1t0 — APPROVED** [review]
:ok_hand:

**Comment by stefan-it** [comment]
Do we have unit tests for that `clean_text` functionality 🤔

**Comment by mfuntowicz** [comment]
@stefan-it I'll add one, had to switch to something else in-between

**Review by LysandreJik — APPROVED** [review]
LGTM, I should have been more thorough when reviewing!

**Comment by LysandreJik** [comment]
Do you mind making the code quality and the tests pass before we merge?

**Pull request merged**
