### PR TITLE
Fix TF input for np.ndarray

### LINKED ISSUE #9248: numpy ndarray type is not allowed on process pytorch model
## Environment info

     
- `transformers` version: 4.1.1
- Platform: macOS-10.16-x86_64-i386-64bit
- Python version: 3.8.6
- PyTorch version (GPU?): 1.7.1 (False)
- Tensorflow version (GPU?): 2.3.1 (False)
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help
 tensorflow: @jplu

## Information

Model I am using (Bert, XLNet ...): Bert

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [o] my own modified scripts: (give details below)

Changed 1 line that `from_pt`'s default value from `False` to `True`((https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/modeling_tf_utils.py#L947))

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [o] my own task or dataset: (give details below)

HuggingFace: monologg/kobert

I loaded my pertained pytorch model, and an error occurred on input_processing function

## To reproduce

1. run input_processing
2. numpy ndarray is not allowed type(https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/modeling_tf_utils.py#L331)
3. So ndarray cannot be processed(https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/modeling_tf_utils.py#L354)
4. Of course there is not any proper changing for ndarray not as other types(dict, Tensor and etc)
5. Error occurred like below

```
  File "/Users/ys/dev/rasa/venv/lib/python3.8/site-packages/transformers/modeling_tf_utils.py", line 357, in input_processing
    raise ValueError(f"Data of type {type(v)} is not allowed only {allowed_types} is accepted for {k}.")
ValueError: Data of type <class 'numpy.ndarray'> is not allowed only (<class 'tensorflow.python.framework.ops.Tensor'>, <class 'bool'>, <class 'int'>, <class 'transformers.file_utils.ModelOutput'>, <class 'tuple'>, <class 'list'>, <class 'dict'>) is accepted for attention_mask.
```

## Expected behavior

Train success!

### PR DESCRIPTION
**Pull request by jplu**
# What does this PR do?

This PR allows `np.ndarray` datatype as input of the models.

# Fixes
#9248

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
I'm not sure we want that...why would one input an `nd.array` instead of ` tf.tensor`?

**Comment by patrickvonplaten** [comment]
I commented on the corresponding issue, I don't fully understand what's going on there in the error

**Comment by jplu** [comment]
This is on purpose because all the methods of a Keras Model allow to have `np.ndarray` as input. You can check for example `fit`, `predict` or `eval` here https://www.tensorflow.org/api_docs/python/tf/keras/Model. They all take a numpy array as possible input

**Comment by patrickvonplaten** [comment]
Okey, I see. I still don't think we should provide this feature, just because keras has some automatic conversion internally. Is there a use case where one cannot forward a TF tensor and has to forward a `nd.array`? The general philosophy of the lib is to "not add too many magic functions" and allowing `nd.arrays` as inputs for TF seems like opening the door for lots of future issues to me. Let's see what @sgugger @LysandreJik think about it

**Comment by jplu** [comment]
On my side I would prefer to keep as much compliancy as possible with TF. But if everyone are not confident because of this Keras magic, I'm ok to do not provide it :)

**Comment by sgugger** [comment]
The TF models do not accept numpy arrays inputs, so this would allow bad inputs to be passed to TF models. I think we should stick with inputs accepted by TF models only.

**Comment by jplu** [comment]
The TF models allow to have numpy arrays as inputs (if we had the `np.ndarray` type). As example:
```python
from transformers import TFBertForSequenceClassification, BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
inputs = tokenizer("Hello", return_tensors="np")
model = TFBertForSequenceClassification.from_pretrained("bert-base-cased")
model(inputs)
```
Gives:
```
TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.08065815, 0.58226204]], dtype=float32)>, hidden_states=None, attentions=None)
```

Keras layers are by default compliant with numpy arrays.

**Comment by sgugger** [comment]
Ah my bad, I tried but forgot to checkout the PR before :facepalm:
If TF models do accept those inputs then, I have no strong objection.

**Review by LysandreJik — COMMENTED** [review]
I think this would be a very welcome change, but we should test it before just adding it to the `allowed_types`

**Comment by jplu** [comment]
@LysandreJik you mean adding a test in `test_modeling_tf_common` with numpy array as input for each model?

**Comment by LysandreJik** [comment]
Yes, for example !

**Comment by jplu** [comment]
There is a now a new test to be sure that the models can be properly executed with numpy inputs.

**Review by LysandreJik — APPROVED** [review]
Great, LGTM! Thanks @jplu.

**Comment by jplu** [comment]
Does it looks ok to be merged?

**Pull request merged**
