### PR TITLE
Update the TF pin for 2.15

### PR DESCRIPTION
**Pull request by Rocketknight1**
This PR updates the TF pin to allow TF 2.15. Leaving it as a draft for now while I make sure this doesn't break anything!

### CODE REVIEW

**Comment by Rocketknight1** [comment]
Seems to work locally! Marking this as ready for review.

**Review by amyeroberts — APPROVED** [review]
LGTM - thanks for adding! 

Let's get a second 👍  from @ydshieh before merging

**Review by ydshieh — APPROVED** [review]
Good for me. But I want to point out (so you can decide if to check it) that our CI currently use `2.13.1` on `main` or even on this PR:

```
tensorflow==2.13.1
```
I think there is some dependency that causes we can't use the latest TF even if we allow it in `setup.py`.

See https://app.circleci.com/pipelines/github/huggingface/transformers/78451/workflows/2472ff62-4b68-47fb-b5fa-ab02af9d445c/jobs/1000618

**Comment by Rocketknight1** [comment]
@ydshieh I didn't know that! It seems to be caused by one of the dependencies being slightly behind - 2.14 is the most recent version, and 2.15 is in RC.

I'm not sure what to do about it, though. Since local tests pass, though, we can probably assume that 2.15 is okay?

**Pull request merged**
