### PR TITLE
Skip some slow tests for doctesting in PRs (Circle)CI

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

For doctest: each`.md` file is seen as a single test by pytest, and some takes more time (say `task_summary.md`) than others.
Let's allow a 5 minute timeout per test. 

For the job step, it still has the total 1200s timeout.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Can you please refresh my memory. Are those run on GitHub actions or circleCI? If Circle CI let's use a smaller timeout :-)

**Comment by ydshieh** [comment]
Hi!

- This file `.circleci/create_circleci_config.py` is running on CircleCI. See #23245
- If we don't accept the change is this PR: we can simply skip some (doc) test file that takes longer time to run)

- This PR addresses the timeout issue (the per test timeout, not the global 1200 seconds), which is motivated by #23318.
  -Usually I will try to respect the 120s  timeout (per test). But **since in this doctests on CircleCI (where we have 1200s global timeout), I think overall it's fine (?)**

**Comment by sgugger** [comment]
Can we skip the longest tests? We are trying to rationalize the costs of circleCI so want to make sure we don't run something too beefy on it, especially since all those tests are run on GPU nightly.

**Comment by ydshieh** [comment]
> Can we skip the longest tests? 

Sure! We will need to have two list: the exiting `utils/documentation_tests` and a new `slow_doctest_to_ignore`.

(I am not sure how to mark some doctest file as slow doctest as we have done for usual tests)

**Comment by sgugger** [comment]
That works for me!

**Comment by amyeroberts** [comment]
Me too!

**Comment by ydshieh** [comment]
The latest version should skip the slow doctests.

(I don't really run the full doctest on CircleCI to get all of them: we just update the list if we see some files being slow by doctest)

**Review by sgugger — APPROVED** [review]

**Pull request merged**
