### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by novice03**
# What does this PR do?

Fixes some suggestions not addressed in [this](https://github.com/huggingface/transformers/pull/15085/) pull request.

I've fixed the typo and unnecessary imports, but running `make style` may not allow some parts of the code to stay in the same line.

## Who can review?

@sgugger

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks a lot!
Make sure to run `make style` on your branch to fix the quality to check.

**Comment by novice03** [comment]
Hello, the `check_code_quality` fails now. Running `make style` will revert all the changes I made to the modeling file, so some parts of the code will not stay in the same line.

**Comment by novice03** [comment]
In the previous commit, I removed trailing commas and put the code in the same line, but the check still fails. In the next commit, I'll run `make style`.

**Comment by sgugger** [comment]
Thanks again!

**Pull request merged**
