### PR TITLE
docs: ko: complete `_toctree.yml`

### PR DESCRIPTION
**Pull request by wonhyeongseo**
# What does this PR do?
From our first week in localizing the documentation, we came across issues and git conflicts with `_toctree.yml`.

This PR updates the `_toctree.yml` file for translations, making it easier for translators to locate the correct files to translate without worrying about the yaml formatting. Each document title now has `(<in translation phrase>)` added in front of it and the "local" key has been changed to `in_translation`.

Translators can now use this scaffold by following these steps:
1. Edit the `local` value by copy & pasting directly from the same line number in `en/_toctree.yml`.
2. Edit the `title` value by replacing the `(<in translation phrase>) <english title>` with the translated title of each document.
3. That's it!

By using this updated scaffold, translators will be able to easily identify the correct files to translate, minimizing the time spent on formatting and file location issues. We hope that this will streamline the translation process and make it more accessible to our community.

Initial language starters can recreate this scaffold by following these steps:
1. Copy the `_toctree.yml` file from the `en` folder.
2. Paste it into the corresponding language folder (e.g., `ko`, `fr`, `de`).
3. Create a temporary `in_translation.mdx` file in the desired language.
4. Find & Replace `local: .*` with `local: in_translation`.
5. Find & Replace `title:` with `title: (<in translation phrase>)` where the phrase is preferrably in the desired language. For example, in Korean the phrase is "번역중"

By taking the initial time to create this scaffold for your language, you will greatly reduce fellow language speakers' yaml formatting issues in the long run.

Part of https://github.com/huggingface/transformers/issues/20179

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
Team HuggingFace: @sgugger, @ArthurZucker, @eunseojo May you please review this PR?

Team PseudoLab: @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy, @HanNayeoniee, @wonhyeongseo, @jungnerd May you please review this PR?

### CODE REVIEW

**Comment by wonhyeongseo** [comment]
Here's the preview screenshot:




Yellow highlighted items are complete. Hence, they do not have `(번역중)` in front of them. Hope this new approach will help my colleagues. 

May you please merge this, Mr. @sgugger ? Thank you so much for your support 🙏💕

**Comment by gabrielwithappy** [comment]
I think this PR is a good idea to avoid wrong depth mistakes or yaml syntax errors

**Review by gabrielwithappy — APPROVED** [review]
It looks good to me.
I think this PR will help to avoid wrong depth mistakes or yaml syntax errors

**Review by gabrielwithappy — APPROVED** [review]
deleted duplicated comment

**Review by gabrielwithappy — APPROVED** [review]
deleted duplicated comment.

**Review by gabrielwithappy — COMMENTED** [review]
deleted duplicated comment.

**Review by sgugger — APPROVED** [review]
Makes sense, thanks!

**Pull request merged**
