### PR TITLE
[Issue template] need to update/extend who to tag

### PR DESCRIPTION
**Pull request by stas00**
This PR 

* [x] adds an entry for what to do what to do when someone has model hub issues - thank you, @julien-c!

TODO/Input needed:

* [ ] need to update who to tag for `tensorflow` Issues

@LysandreJik

### CODE REVIEW

**Comment by julien-c** [comment]
For broken models you would just tag the model author(s) – we'll add a feature to the model hub to tag someone in a conversation thread, but in the meantime you can use the Forum to ping them

**Comment by stas00** [comment]
That's a great idea to tag the model author - how would a user know the model author corresponding forum username?

**Comment by julien-c** [comment]
We use SSO so one's username on Forum is guaranteed to be one's username on hf.co

**Comment by stas00** [comment]
Ah, that's perfect then! Thank you!

**Review by LysandreJik — APPROVED** [review]
You can just put me for the TensorFlow issues for now, and I'll dispatch accordingly. Thanks!

**Pull request merged**
