### PR TITLE
Add aws studio notebooks

### PR DESCRIPTION
**Pull request by mishig25**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sgugger** [comment]
I can't check the result, do you have any way of adding a screenshot of what it will give?

**Comment by mishig25** [comment]
It will look like this (also, github renders it almost identically [here](https://github.com/huggingface/transformers/blob/cb5ef2e0ae27f09f2427aad155a119a2b22433e6/notebooks/README.md))
Screenshot 2022-02-11 at 09 42 07

**Review by sgugger — APPROVED** [review]
Thanks! Can you just rebase on master to make sure the styling issue doesn't come from this PR?

**Comment by mishig25** [comment]
Rebased it 🙂

**Comment by sgugger** [comment]
Thanks, all good!

**Pull request merged**
