### PR TITLE
[Jax Slow Circle CI] Don't close PR

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Thanks for the tip @stas00 ! 

I'll push to the PR every 24h to have a background circle ci test - eventually we should think about a better solution here

**Comment by stas00** [comment]
You can crontab an empty git push, e.g.:
```
cd transformers-flax-cron
git commit --allow-empty -m "Trigger CI"
git push
```

**Comment by patrickvonplaten** [comment]
I also need to pull from master regularly - otherwise the tests are always run on the same code no?

**Comment by stas00** [comment]
Heh, yes of course! That was a blunder suggestion on my part since after rebasing you will always have something to push and if there is nothing to push then there is nothing test in any case.

**Pull request closed without merging**
