### PR TITLE
Fix video batching to videollava

### PR DESCRIPTION
**Pull request by merveenoyan**
cc @zucchini-nlp works with no problems

### CODE REVIEW

**Review by zucchini-nlp — APPROVED** [review]
Thanks ❤️ 

Can we activate tests, it is being skipped now for PIL inputs?

**Comment by merveenoyan** [comment]
@zucchini-nlp one thing confused me, you are passing numpy tests but don't pass `numpify=True` when creating dummy inputs (also they pass the assertion of being numpy arrays) I couldn't make any change to the numpy test to make it for PIL

**Comment by zucchini-nlp** [comment]
Yes, I made bad decision when constructing tests tailoring only for torch and numpy. This one has better dummy video preparation, can copy from it maybe
 
https://github.com/huggingface/transformers/blob/3aefb4ec7f957f9561a410eabc6f9d57b2f0384f/tests/models/llava_next_video/test_image_processing_llava_next_video.py#L99-L124

**Review by zucchini-nlp — APPROVED** [review]
Great, thanks!

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing! 

FWIW - I think the current "numpify" and "torchify" logic is pretty bad and repeated everywhere. We should look into making this clearer and consolidate in the future!

**Comment by royvelich** [comment]
@zucchini-nlp 
Where can I find an example of can I batch videos in video-lava?

**Pull request merged**
