### PR TITLE
Add FlaxWhisperForAudioClassification model

### PR DESCRIPTION
**Pull request by raghavanone**

### CODE REVIEW

**Review by sanchit-gandhi — APPROVED** [review]
Super @raghavanone! Thanks for making the changes based on the previous reviews at  #21894 - this looks good for a final review!

**Review by sgugger — APPROVED** [review]
Thanks a lot for your work on this!

**Comment by sgugger** [comment]
This actually broke a lot of tests on Flax Whisper, so reverting. Can you re-open the PR and rebase on main so we can see what went wrong?

**Comment by raghavanone** [comment]
@sanchit-gandhi Request you to open this PR.

**Pull request merged**
