### PR TITLE
Add Multiple Choice Pytorch Example for Hellaswag

### PR DESCRIPTION
**Pull request by prajjwal1**
# What does this PR do?

Fixes # (issue)
Added example for `hellaswag` dataset. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
The goal of the examples is to provide examples, we can't have something that will match every datasets in the world, or one example per dataset in the world.

Therefore, you should definitely share your example in a personal repo and we can link to it in the community apge of our documentation, but we won't add this to the list of maintained examples.

**Comment by sgugger** [comment]
I'm fine with switching datasets, if you want to amend your PR in that sense :-)

**Comment by prajjwal1** [comment]
I've replaced `swag` with `hellaswag` to switch these datasets.

**Review by sgugger — COMMENTED** [review]
When I said I was fine with switching the dataset, I meant it with as little changes as possible in the existing script. It shouldn't be such a rewrite of the examples, just adapting the parts in the preprocessing that need to change.

**Pull request closed without merging**
