### PR TITLE
Accelerate support added to Object Detection & Segmentation Models

### LINKED ISSUE #28309: Leverage Accelerate for object detection/segmentation models
### Feature request

Currently there are 6 object detection models which don't support multi-GPU training out-of-the-box. The distributed code was explicitly left out of the modeling code as they wouldn't be compatible with the Trainer API. Refer to [these lines of code](https://github.com/huggingface/transformers/blob/502a10a6f89b2919444aba68cd0def51d5ba618c/src/transformers/models/detr/modeling_detr.py#L2207-L2210) as an example.

However, now that the Trainer class uses 🤗 [Accelerate](https://huggingface.co/docs/accelerate/index) behind the scenes, we can include it now by leveraging the following code:
```
from accelerate import PartialState
from accelerate.utils import reduce

# Check that we have initialized the distributed state
world_size = 1
if PartialState._shared_state != {}:
    num_boxes = reduce(num_boxes)
    world_size = PartialState().num_processes
```

See this commit as an example: https://github.com/huggingface/transformers/pull/27990/commits/526a8b0801d075ad5f99e87fbfc5de49ea347a9a.

I'll add a list here with models to be fixed:

- [ ] DETR
- [ ] Conditional DETR
- [ ] Deformable DETR
- [ ] YOLOS
- [ ] Table Transformer
- [ ] DETA

Additionally, there are 3 segmentation models which require a similar update:

- [ ] MaskFormer
- [ ] Mask2Former
- [ ] OneFormer.

For these, the `get_num_masks` function requires an update similar to what is present in the [original repository](https://github.com/facebookresearch/MaskFormer/blob/da3e60d85fdeedcb31476b5edd7d328826ce56cc/mask_former/modeling/criterion.py#L169), using Accelerate.

### Motivation

Would be great to support multi-GPU training of these models leveraging Accelerate

### Your contribution

I can do this but this is a perfect opportunity for a first open-source contribution

### PR DESCRIPTION
**Pull request by sam99dave**
# What does this PR do?

Fixes #28309

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@NielsRogge

### CODE REVIEW

**Comment by ArthurZucker** [comment]
Hey @sam99dave were you waiting for a review?

**Comment by sam99dave** [comment]
Yeah, I was waiting for one. Not sure if these required changes had already been merged by another PR. There was another PR for this which was being reviewed I think.

Pls, let me know on this.

**Comment by ArthurZucker** [comment]
Seems like #28312 was already approved, but is getting stale. I'll post a message there

**Comment by amyeroberts** [comment]
@sam99dave Thanks for opening this PR and contributing to improving our models! 

As #28312 was merged in, I'm going to close this PR

**Pull request closed without merging**
