### PR TITLE
FSDP grad accum fix

### PR DESCRIPTION
**Pull request by winglian**
# What does this PR do? 

https://github.com/huggingface/transformers/commit/8c62a92b3c3fea13652ef5d292a7863138410c59#diff-ed55888e6665791fe92cc8fc0c499da54f4ace6738551cd9a2591881cda076deL2473-R2480 seems to have broken FSDP training as we need to wrap the train step in no_sync on every step except the last step in the gradient accumulation batch. Without this, during the optimizer.step(), I get the error: 
```
RuntimeError: Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32/64 notwithstanding
```

this wasn't caught by the fsdp tests since gradient accumulation wasn't part of those tests, so I also added tests for that as well.

see https://muellerzr.github.io/blog/gradient_accumulation.html#what-is-the-right-way-then

Screenshot 2024-11-07 at 12 17 36 PM

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by winglian** [comment]
@ArthurZucker @muellerzr for review

**Review by muellerzr — APPROVED** [review]
Thanks for catching this!

**Comment by winglian** [comment]
is it possible to also trigger the slow tests for this PR too to make sure the new test passes?

**Review by SunMarc — APPROVED** [review]
Make sense ! Thanks for fixing !

**Review by ydshieh — APPROVED** [review]
Thank you.

Newly added tests are passing (in this PR) and failed on `main`. So it does its job.

The change in `trainer` seems reasonable to me too.

**Review by ArthurZucker — APPROVED** [review]
Sorry for being late on this, thanks 🤗 will patch

**Pull request merged**
