### PR TITLE
Add model parallelism to CodeGen

### PR DESCRIPTION
**Pull request by LostBenjamin**
This PR adds model parallelisim to the CodeGen model. I have been using this since August.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Thanks for your PR but this code for model parallelism is deprecated and will be removed from other code files. To use parallelism, please load the model with `device_map="auto"`.

**Comment by LostBenjamin** [comment]
ok, I did not know that. Thanks for the info!

Does `device_map="auto"` also work for CodeGen?

**Comment by sgugger** [comment]
Yes, it's supported (at least on the main branch)!

**Comment by shunzh** [comment]
> Thanks for your PR but this code for model parallelism is deprecated and will be removed from other code files. To use parallelism, please load the model with `device_map="auto"`.

I'm a bit confused about model parallelism in Huggingface. I'm trying to fine-tune a CodeGen model using Huggingface Trainer. Is loading the model with `device_map="auto"` the right way to enable model parallelism?

From what I read [here](https://huggingface.co/docs/transformers/v4.28.1/perf_train_gpu_many#naive-model-parallelism-vertical-and-pipeline-parallelism), model parallelism is only supported by GPT2 and T5.

**Pull request closed without merging**
