### PR TITLE
Add links to the Hub

### PR DESCRIPTION
**Pull request by LysandreJik**
Adds a few additional links to the Hub. If there are ideas to do this even deeper, would love to incorporate them in this PR.
I would love loved to share initial collections as well but I have to check if I can embed collection visualisation in the doc page + it's not relevant for quite a few architecures.

### CODE REVIEW

**Review by MKhalusova — APPROVED** [review]
Thank you for adding these! There were a couple of model docs that already had a similar link to checkpoint, can you please remove the duplicates? Otherwise, LGTM!

**Review by julien-c — COMMENTED** [review]
i remember we had some badges like those ones:

image


(on https://huggingface.co/docs/transformers/v4.34.0/en/model_doc/xlm for instance)

But looks like those were added manually?

**Comment by stevhliu** [comment]
I think with the badges (but rename it to All model _checkpoints_ instead of All model pages) it is more visible than the text which doesn't stand out as much.

**Comment by NielsRogge** [comment]
Great idea, however is this currently hardcoded? Would be great to add it to the CookieCutter so that new models have this as well. Also more a fan of the badge for visibility.

**Comment by LysandreJik** [comment]
Begone bot, I still want to get to this

**Review by stevhliu — APPROVED** [review]
LGTM! One minor nit is I think it'd be even clearer/precise if the badge was named "All model checkpoints" instead of "All model pages".

**Pull request closed without merging**
