### PR TITLE
Added type hints for `Graphormer` pytorch version

### PR DESCRIPTION
**Pull request by dewasahu2003**
@Rocketknight1  👋
- I added type hint for `graphormer` pytorch 
- checked formatting with black and ruff

if some checks on ci/cd do not, please do comment and correct

### CODE REVIEW

**Comment by dewasahu2003** [comment]
@Rocketknight1 Hi 👋
- `Union[torch.Tensor, torch.LongTensor]` is used because the file had a lot of `nn.embedding` instances which expects either IntTensor or LongTensor
- so to avoid any confusion 😕 i used that
- [nn.embedding docs](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html#torch.nn.Embedding)

image

*if still changes are required i would be happy to make it*🙂

**Comment by Rocketknight1** [comment]
Hi @dewasahu2003, I think in most cases we just annotate those types as `LongTensor`! Your version is probably more correct, but for simplicity just `LongTensor` is fine, since that's what people usually use.

**Comment by dewasahu2003** [comment]
@Rocketknight1 Hi 👋 
- if LongTensor is  preferred then i would make changes along
- that would help the code to be 🤒 bloat free

**Review by Rocketknight1 — APPROVED** [review]
This looks good to me now! Are you ready for me to merge it?

**Comment by Rocketknight1** [comment]
Done. Thanks for the PR, we really appreciate it!

**Pull request merged**
