### PR TITLE
Nit about `model_accepts_loss_kwargs` for loss

### PR DESCRIPTION
**Pull request by ArthurZucker**
# What does this PR do?
There was a typo in #34915, as tests were passing, did not pay attention to it. Thanks to @techkang for reporting

### CODE REVIEW

**Comment by ArthurZucker** [comment]
```python
from transformers import Wav2Vec2Model
import inspect

sif = inspect.signature(Wav2Vec2Model.forward)
any(k.kind == inspect.Parameter.VAR_KEYWORD for k in sif.parameters.values())
```
Returns false. But when in the example torch, you have unwrapped_model.forward seems to have loss_kwargs
cc @muellerzr

**Comment by techkang** [comment]
This PR still confuses me as I mentioned in previes PR.
There are two ways to use `num_items_in_batch` to fix GA loss issue.
1. Use `num_items_in_batch` in loss function defined by model. In this case, `model_accepts_loss_kwargs` is `True`.
2. The model doesn't have loss function or user has self-defined loss function, which is `compute_loss_func`.
However, this PR will make the second method invalid.

**Comment by ArthurZucker** [comment]
Hey! 
> Use num_items_in_batch in loss function defined by model. In this case, model_accepts_loss_kwargs is True.

No, `model_accepts_loss_kwargs` only depends on the `forward_pass` of the model, not the los function defined by the model. If the model accepts kwargs, we are gonna pass `num_items_in_batch`. Else we cannot. 

> The model doesn't have loss function or user has self-defined loss function, which is compute_loss_func.
However, this PR will make the second method invalid.

Even if user has a self defined loss function, if the `forward` pass does not support `num_items_in_batch`, we ought not to pass kwargs. I might be confusing with the trainer's  `compute_loss_func`, and in that case will leave @muellerzr have a look

**Comment by muellerzr** [comment]
@ArthurZucker I disagree with 2, it was explicitly designed that way to catch this in case the model doesn't have this figured out yet and the user can/should manually do it themselves instead

**Pull request closed without merging**
