### PR TITLE
Add BioGptForSequenceClassification

### LINKED ISSUE #21530: BioGPTForSequenceClassification
### Feature request

It would be nice to have this available.

### Motivation

I'm studying some biomedical classification datasets and I would like to try BioGPT with them.

### Your contribution

I could send a PR if you want. I guess it shouldn't be too hard, I could look at another model trained with Casual LM and implement `BioGPTForSequenceClassification` like that one, am I right?

### PR DESCRIPTION
**Pull request by GuillemGSubies**
# What does this PR do?

Fixes #21530

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

@NielsRogge

### CODE REVIEW

**Comment by GuillemGSubies** [comment]
Hey @NielsRogge I don't understand why the tests are failing, looks like it fails when importing the model?


(BTW I ping you because we talked in the issue, should I ping someone else?)

**Comment by NielsRogge** [comment]
Hi, it seems the CI didn't run properly. Could you push an empty commit to trigger it?

**Comment by sgugger** [comment]
What Niels forgot to say is that there seems to be an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-) and then push some commit to your PR?

**Comment by GuillemGSubies** [comment]
> What Niels forgot to say is that there seems to be an issue with your CircleCI permissions, the tests won't run. Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-) and then push some commit to your PR?

I tried but it didn't work 😖

**Comment by upjabir** [comment]
@GuillemGSubies If the issue is still open, i would like to contribute it

**Comment by GuillemGSubies** [comment]
@upjabir I don't understand why the pipelines fail, you have any idea? Otherwise you can open another PR and I'll close this one

**Comment by upjabir** [comment]
@GuillemGSubies currently I don't have any idea about the issue. But let me try it, so I can get a clear picture

**Pull request closed without merging**
