### PR TITLE
Remove chameleon from CausalLM

### PR DESCRIPTION
**Pull request by merveenoyan**
as discussed internally @NielsRogge 
opened PRs to chameleon repos too

### CODE REVIEW

**Review by NielsRogge — APPROVED** [review]
Thanks! cc @zucchini-nlp

**Comment by merveenoyan** [comment]
wait I have to remove from other places I missed consistency checks

**Comment by merveenoyan** [comment]
@NielsRogge should I just add it [here](https://github.com/huggingface/transformers/blob/9e4ba843b72da9c3cea785feb85bd52047ede3a3/src/transformers/models/auto/modeling_auto.py#L701) instead

**Comment by NielsRogge** [comment]
Yes it would need to be added [here](https://github.com/huggingface/transformers/blob/765732e92c17a17682a5efd4aa4323e5ab01fe07/utils/check_repo.py#L157).

**Pull request closed without merging**
