### PR TITLE
FlaubertForTokenClassification 

### PR DESCRIPTION
**Pull request by stas00**
implement FlaubertForTokenClassification as a subclass of XLMForTokenClassification.

Based on an item from https://github.com/huggingface/transformers/projects/17

### CODE REVIEW

**Comment by sgugger** [comment]
Thanks! Can you also add the model to the common tests (by adding it to the [all_model_classes](https://github.com/huggingface/transformers/blob/b2747af5434e5a5d8ab1d7e2789699d20d7a4ab8/tests/test_modeling_flaubert.py#L316)) and in the [documentation file](https://github.com/huggingface/transformers/blob/master/docs/source/model_doc/flaubert.rst)?

This looks great to me otherwise.

**Comment by stas00** [comment]
> Can you also add the model to the common tests (by adding it to the [all_model_classes](https://github.com/huggingface/transformers/blob/b2747af5434e5a5d8ab1d7e2789699d20d7a4ab8/tests/test_modeling_flaubert.py#L316))

I tried that originally, but they don't support *TokenClassification - its outputs are different, so most tests break. Note that `XLMForTokenClassification` isn't being tested in the common tests. This PR was really monkeyseemonkeydo. Perhaps merging this and then work on `XLMForTokenClassification` common tests first? and then the subclass will be easy.

will add to the docs shortly.

**Comment by stas00** [comment]
I think there is a bug in `XLMForTokenClassification` - if I do this fix:
```
--- a/src/transformers/modeling_xlm.py
+++ b/src/transformers/modeling_xlm.py
@@ -1079,7 +1079,7 @@ class XLMForTokenClassification(XLMPreTrainedModel):
         sequence_output = self.dropout(sequence_output)
         logits = self.classifier(sequence_output)

-        outputs = (logits,) + outputs[2:]  # add hidden states and attention if they are here
+        outputs = (logits,) + outputs[1:]  # add hidden states and attention if they are here
         if labels is not None:
             loss_fct = CrossEntropyLoss()
             # Only keep active parts of the loss
```
I can now add `XLMForTokenClassification` to `all_model_classes` - and 99% of it now passes.

It looks like that line of code was copied from `BertForTokenClassification`, but for XLM it appears to need to be `outputs[1:]`

**Comment by stas00** [comment]
Oh, my fork was outdated - I see you have just fixed this bug. OK, adding FlaubertForTokenClassification to all_model_classes should work now.

**Review by sgugger — APPROVED** [review]
Yes, `XLMForTokenClassification` was recently fixed (that's why we need to have the models tests in the common tested before merging the PR that adds them ;-) ). Thanks for the changes!

@LysandreJik , @patrickvonplaten this is ready for second review/merge.

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
