### PR TITLE
Interpolate pos encode for altclip

### LINKED ISSUE #30579: Community contribution: enable dynamic resolution input for more vision models.
### Feature request

Some of our models interpolate its positional embeddings, enabling pretrained checkpoints to be used on different input resolutions. For example, [here in ViT](https://github.com/huggingface/transformers/blob/75bbfd5b2237b7e35a9265731ecf63022579e7e2/src/transformers/models/vit/modeling_vit.py#L79). 

- [ ] [altclip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/altclip/modeling_altclip.py)
- [ ] [beit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/beit/modeling_beit.py)
- [ ] [blip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/blip/modeling_blip.py)
- [ ] [blip_2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/blip_2/modeling_blip_2.py)
- [ ] [bridgetower](https://github.com/huggingface/transformers/blob/main/src/transformers/models/bridgetower/modeling_bridgetower.py)
- [ ] [chinese_clip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/chinese_clip/modeling_chinese_clip.py)
- [ ] [clip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/clip/modeling_clip.py)
- [ ] [conditional_detr](https://github.com/huggingface/transformers/blob/main/src/transformers/models/conditional_detr/modeling_conditional_detr.py)
- [ ] [data2vec](https://github.com/huggingface/transformers/blob/main/src/transformers/models/data2vec/modeling_data2vec_vision.py)
- [ ] [deformable_detr](https://github.com/huggingface/transformers/blob/main/src/transformers/models/deformable_detr/modeling_deformable_detr.py)
- [ ] [deit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/deit/modeling_deit.py)
- [ ] [detr](https://github.com/huggingface/transformers/blob/main/src/transformers/models/detr/modeling_detr.py)
- [ ] [donut](https://github.com/huggingface/transformers/blob/main/src/transformers/models/donut/modeling_donut_swin.py)
- [ ] [git](https://github.com/huggingface/transformers/blob/main/src/transformers/models/git/modeling_git.py)
- [ ] [grounding_dino](https://github.com/huggingface/transformers/blob/main/src/transformers/models/grounding_dino/modeling_grounding_dino.py)
- [ ] [idefics2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/idefics2/modeling_idefics2.py)
- [ ] [kosmos2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/kosmos2/modeling_kosmos2.py)
- [ ] [maskformer swin](https://github.com/huggingface/transformers/blob/main/src/transformers/models/maskformer/modeling_maskformer_swin.py)
- [ ] [owlv2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/owlv2/modeling_owlv2.py)
- [ ] [owlvit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/owlvit/modeling_owlvit.py)
- [ ] [perceiver](https://github.com/huggingface/transformers/blob/main/src/transformers/models/perceiver/modeling_perceiver.py)
- [ ] [siglip](https://github.com/huggingface/transformers/blob/main/src/transformers/models/siglip/modeling_siglip.py)
- [ ] [swin](https://github.com/huggingface/transformers/blob/main/src/transformers/models/swin/modeling_swin.py)
- [ ] [swin2sr](https://github.com/huggingface/transformers/blob/main/src/transformers/models/swin2sr/modeling_swin2sr.py)
- [ ] [swinv2](https://github.com/huggingface/transformers/blob/main/src/transformers/models/swinv2/modeling_swinv2.py)
- [ ] [table_transformer](https://github.com/huggingface/transformers/blob/main/src/transformers/models/table_transformer/modeling_table_transformer.py)
- [ ] [tvp](https://github.com/huggingface/transformers/blob/main/src/transformers/models/tvp/modeling_tvp.py)
- [ ] [vit_mae](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vit_mae/modeling_vit_mae.py)
- [ ] [vivit](https://github.com/huggingface/transformers/blob/main/src/transformers/models/vivit/modeling_vivit.py)

### Motivation

Let's add this to more models, to leverage existing checkpoints for new cases! 

### Your contribution

For anyone who would like to contribute, please comment on the issue, claiming a model you'd like to work on and share a link to the PR. 

Each PR should: 
* Add an `interpolate_pos_encoding` method
* Add a test showing the model can correctly interpolate an input image of a different size

There was a PR opened to add this to CLIP models, which is now inactive, but useful for reference of the changes to make: https://github.com/huggingface/transformers/pull/27457

Once the PR is ready, you can ping me for review 🤗

### PR DESCRIPTION
**Pull request by bhuvanmdev**
# What does this PR do?

Adds **interpolate_pos_encode** and **a test case** for the said feature for the model altclip.

Fixes #30579 (altclip)

## Who can review?

@amyeroberts

### CODE REVIEW

**Comment by bhuvanmdev** [comment]
This is my first open-source contribution, so any type of suggestions are appreciated :)

**Comment by amyeroberts** [comment]
Hi @bhuvanmdev, thanks for working on this! 

I must apologies for the making the issue clear when I first created it. Models which are linked through `# Copied from` statements should be modified together i.e. CLIP should changed and then realted models like altclip included in this change. 

As there's other PRs open to add this feature to CLIP, those will take precedence over this PR. Apologies for the time that you've already spent adding it to this model.

**Comment by bhuvanmdev** [comment]
I did get to understand the architecture behind CLIP like models a bit better :), so it was'nt a waste of time. 
Then in that case, should I just close this PR?

**Comment by amyeroberts** [comment]
> Then in that case, should I just close this PR?

Yes, let's close this PR. Thanks again for working on this and contributing to improving the library

**Pull request closed without merging**
