### PR TITLE
Make convert_to_onnx runable as script again

### PR DESCRIPTION
**Pull request by mcernusca**
Fix `convert_graph_to_onnx.py` script crash by replacing relative import.

# What does this PR do?

Fixes `python transformers/convert_graph_to_onnx.py` crash with error `Error while converting the model: attempted relative import with no known parent package` . I found this was previously fixed in #10857 and regressed. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for the fix!

**Comment by sgugger** [comment]
It seems there is an issue with your CircleCI permissions, the tests won't run.
Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

**Comment by mcernusca** [comment]
> It seems there is an issue with your CircleCI permissions, the tests won't run. Could you try refreshing your permissions as shown [here](https://support.circleci.com/hc/en-us/articles/360048210711-How-to-Refresh-User-Permissions-)?

Thanks, CircleCi now supposedly has access to all my repositories now but I'm not sure how to re-trigger the tests. Sorry if I'm missing something obvious.

**Comment by sgugger** [comment]
You can try an empty commit (`git commit -m "Trigger CI" --allow-empty`)

**Pull request merged**
