### PR TITLE
Check for mapping/dict in distributed_concat function

### PR DESCRIPTION
**Pull request by prajwal967**
# What does this PR do?
* Feature request for checking if input to the distributed_concat function is of type Mapping/Dict.
* The [distributed_concat](https://github.com/huggingface/transformers/blob/b9af152efb748b1bff8f6fe0130e62ebb8e11a53/src/transformers/trainer_pt_utils.py#L188) function currently checks for the List/Tuple type, but does not check for the Mapping/Dict type.
* The [nested_xla_mesh_reduce](https://github.com/huggingface/transformers/blob/b9af152efb748b1bff8f6fe0130e62ebb8e11a53/src/transformers/trainer_pt_utils.py#L171) & [smp_gather](https://github.com/huggingface/transformers/blob/b9af152efb748b1bff8f6fe0130e62ebb8e11a53/src/transformers/trainer_pt_utils.py#L1084) functions have an IF statement to check if the input is of type Mapping/Dict and then iterates over the items.

Fixes # (issue): https://github.com/huggingface/transformers/issues/21497

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section? **Yes**
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case. **Yes**. Link: https://github.com/huggingface/transformers/issues/21497
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? **No**

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sgugger, @stas00

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for adding this!

**Review by stas00 — APPROVED** [review]
That's an awesome addition, thank you, @prajwal967

**Comment by stas00** [comment]
Looks like `src/accelerate/utils/memory.py` is the new location of `find_executable_batch_size` - backcompat breakage in accelerate?

**Comment by sgugger** [comment]
This is fixed in #21501

**Pull request merged**
