### PR TITLE
Rename Phi-3 rope scaling type

### PR DESCRIPTION
**Pull request by garg-amit**
# What does this PR do?

The naming around rope scaling type is confusing. Making correction to give the correct name reference and acknowledge the source of the method.
https://arxiv.org/abs/2402.13753

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by jiazhan-msft — APPROVED** [review]

**Comment by amyeroberts** [comment]
cc @ArthurZucker @gante

**Review by gante — APPROVED** [review]
@garg-amit LGTM, thank you for the PR :)

**Comment by gante** [comment]
@ArthurZucker in practice, this PR removes `yarn` from phi-3. 

I couldn't find phi-3 models on the hub using `yarn` and, since `longrope` is meant to be an upgrade to `yarn`, I think we can save ourselves some future maintenance with this PR :)

**Review by ArthurZucker — COMMENTED** [review]
Sure, I would rather we do a deprecation cycle ! 😉

**Comment by garg-amit** [comment]
Thanks @gante @ArthurZucker! When can we expect these changes to be merged?

**Comment by ArthurZucker** [comment]
Hey! Just waiting for you to update by doing a deprecation cycle! As the class was kind of public, we want to make sure we don't do a breaking change

**Review by Khaliq88 — APPROVED** [review]

**Comment by garg-amit** [comment]
@ArthurZucker I've added deprecation warnings to both classes, i.e., `Phi3SuScaledRotaryEmbedding` and `Phi3YarnScaledRotaryEmbedding`.

**Comment by shreyaspimpalgaonkar** [comment]
Hi, eagerly waiting for this to merge. Thank you!

**Review by ArthurZucker — APPROVED** [review]
Thanks for fixing

**Pull request merged**
