### PR TITLE
implementing tflxmertmodel integration test

### PR DESCRIPTION
**Pull request by sadakmed**
# What does this PR do?
this PR implement an integration test for TFLxmertmodel as requested in #9954  

@LysandreJik

### CODE REVIEW

**Comment by sadakmed** [comment]
@LysandreJik

**Comment by sadakmed** [comment]
what about this one

**Comment by sadakmed** [comment]
Hi @LysandreJik  what about this one

**Comment by LysandreJik** [comment]
Sure! It seems there is no branch linked to this PR, however. The changes are still visible here https://github.com/huggingface/transformers/pull/10052/files but I am unable to reopen.

**Pull request closed without merging**
