### PR TITLE
docs: fix 404 link

### PR DESCRIPTION
**Pull request by panpan0000**
# What does this PR do?

ISSUE:
when you go to doc : https://huggingface.co/docs/transformers/main/en/main_classes/trainer#specific-gpus-selection
image

the link is 404 due to URL is case sentitive.
image

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for fixing!

**Comment by panpan0000** [comment]
@amyeroberts , Many thanks to your kindly review and help.

the check was unsuccessful.
image

detail log as below
image
but even I ran `make quality` on main head 06343b06335a1f8417bd32d3ffc7cf2cca9a24ac ,  it failed 
```
Oh no! 💥 💔 💥
3 files would be reformatted, 2678 files would be left unchanged.
```

 or run on my PR with command  `doc-builder style src/transformers docs/source --max_len 119 --check_only --path_to_docs docs/source`, it was succesful.

**Comment by amyeroberts** [comment]
@panpan0000 Unfortunately we had some package dependency nightmares this week. The fix was pushed to main - I can see you've rebased to get the updates and it's all working now ❤️ 

Thank you for your patience and for looking into the issue. Once the final build PR documentation run has finished we can merge :)

**Comment by panpan0000** [comment]
awesome @amyeroberts , nice community here!

**Pull request merged**
