### PR TITLE
Minor documentation revisions from copyediting

### PR DESCRIPTION
**Pull request by connorbrinton**
# What does this PR do?

Minor changes to the documentation to correct typos and improve readability. I noticed these typos while reading through the docs to familiarize myself with the library for a project, and thought it would be nice to make a PR for them 😊

I've already tested building the docs from these changes, and all changes seem to have taken effect properly 👍 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests), Pull Request section?

## Who can review?

@sgugger would you mind reviewing this PR? I'm happy to make any changes (or remove any changes) you want 🙂

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks a lot for all those fixes!

**Comment by sgugger** [comment]
Looks like you need to run `make style` on your branch to fix the formatting of the doc files. Let me know if you run into any trouble doing that.

**Comment by connorbrinton** [comment]
Thanks @sgugger 😄 I was able to run `make style` successfully (and update `preprocessing.rst` with the changes), but it looks like the `check_code_quality` check ran out of memory this time 😅 

Screen Shot 2020-12-23 at 9 33 15 AM

I tried rerunning it, but it seems like I don't have permission. Could you try rerunning it?

I'm also happy to bump the `resource_class` for the check from `medium` to `medium+` if that would be helpful 🙂

**Comment by sgugger** [comment]
Yes it was just a spurious failure. Thanks!

**Pull request merged**
