### PR TITLE
fix(dvclive): pass fake dataset to avoid exception in trainer init

### PR DESCRIPTION
**Pull request by shcheklein**
Fixes these failing tests https://github.com/iterative/dvclive/actions/runs/11545815176/job/32134865977?pr=846 downstream.

The cause is this change: https://github.com/huggingface/transformers/pull/33743 which made `trainer` ctr a bit more strict.

I see that `WandbCallback` is also using the same technique (initializing fake trainer). @parambharat could you check if we need to add a similar fix there.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
cc @SunMarc @jackyjinjing for the original PR!

**Review by SunMarc — APPROVED** [review]
Thanks for fixing ! To fix the CI, please rebase the PR on main

**Comment by shcheklein** [comment]
@SunMarc done, rebased

**Review by LysandreJik — APPROVED** [review]
Thank you!

**Pull request merged**
