### PR TITLE
Llama: retrocompatibility support for inner layers

### PR DESCRIPTION
**Pull request by gante**
# What does this PR do?

### CODE REVIEW

**Comment by gante** [comment]
(It seems like it is no longer needed, closing)

**Comment by Adam1679** [comment]
@gante hi, i also got the error "None type is not subscribable " in apply_rotary_pos_emb. Why is it no longer need? Why not merge it?

**Comment by gante** [comment]
Hi @Adam1679 -- have you followed the conversation in [this issue](https://github.com/huggingface/transformers/issues/22407)? It explains the rationale behind the change 🤗

**Comment by Adam1679** [comment]
@gante yes. but i encountered the same issee without using GPTQ-for-LLaMA package.

**Comment by gante** [comment]
@Adam1679 then one of the two things is happening:
1. You are using exclusively hugging face libraries -- ensure you have the latest versions and, if the error persists, please an issue with a short snippet that reproduces the issue
2. You are using external libraries -- request their owners to update the transformers version and/or update their internal code

**Pull request closed without merging**
