### PR TITLE
fix resume_from_checkpoint bug

### PR DESCRIPTION
**Pull request by Jintao-Huang**
# What does this PR do?

Fixes bug: 
When `resume_from_checkpoint` is set to True, the `state` is imported, which includes `self.state.best_model_checkpoint`. If the best model is still the one corresponding to the model in the resume_from_checkpoint directory when saving the model during training, an exception will be raised at `best_model_index = checkpoints_sorted.index(str(Path(self.state.best_model_checkpoint)))`: 
ValueError: '/path/to/checkpoint-100' is not in list.

Fixes issue(https://github.com/huggingface/transformers/issues/22172)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

- trainer: @muellerzr and @pacman100

### CODE REVIEW

**Review by muellerzr — APPROVED** [review]
Thanks! The solution makes sense to me.

**Comment by Jintao-Huang** [comment]
Hello, it seems that citest has encountered a timeout error. It doesn't seem to be an error on my end. Can you help me take a look, please?

**Comment by muellerzr** [comment]
Hi, any chance you can rebuild/rebase from main? I think that will fix your failing tests. Thanks!

**Review by ArthurZucker — APPROVED** [review]
Thanks 😉

**Pull request merged**
