### PR TITLE
Fix: `num_logits_to_keep` in composite models

### PR DESCRIPTION
**Pull request by zucchini-nlp**
# What does this PR do?

Fixes issue from https://github.com/huggingface/transformers/pull/33164#issuecomment-2315111463. 

We cannot assume that the model will have `num_logits_to_keep` in its forward, because an LM can be used as backbone in composite models. So the current PR sets `num_logits_to_keep` to None by default and adds it as a kwarg only when it is explicitly set to an integer by users

Plus, updated VLMs accordingly with `num_logits_to_keep`. Other VLMs like BLIP don't need this arg because they delegate the whole generation process to the LM.

cc @merveenoyan

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Understood, thanks @zucchini-nlp!

**Comment by LysandreJik** [comment]
Would it be possible to add a test to ensure no regression on the issue https://github.com/huggingface/transformers/pull/33164#issuecomment-2315111463 ?

**Comment by zucchini-nlp** [comment]
Oh, also cc @gante for generation :)

**Comment by zucchini-nlp** [comment]
@LysandreJik yes, I am working on enabling generation tests on all VLMs. That should be 2-3 PRs away, after we fix some issues after the latest refactoring on VLM processing code

We've overlooked many issues on VLM side due to the absence of fast generation tests and slow tests are usually not ran if modeling code is unchanged.

**Pull request merged**
