### PR TITLE
Add on_optimizer_step to callback options

### LINKED ISSUE #31033: Add per-parameter gradient logging (and before optimizer step callback)
### Feature request

I wish to log (in wandb) the norm of the gradient of each parameter in my transformer. Currently, supplying a max grad norm value will automatically log the gradient norm for the whole model, but there is no way to do this per named parameter.

Specifically, this is impossible even with a callback as on_step_begin is called before loss is computed and on_step_end is called after the optimizer zeroes the gradients. My requests are then as follows:

1. Add an option for per parameter gradient logging
2. Add a before optimizer step (akin to lightning) callback in the trainer

`                  model.zero_grad()
                    self.state.global_step += 1
                    self.state.epoch = epoch + (step + 1 + steps_skipped) / steps_in_epoch
                    self.control = self.callback_handler.on_step_end(args, self.state, self.control) // This is too late!
`

### Motivation

I would like to monitor the properties of the gradients through callbacks, and I believe huggingface should add flexibility for this feature. As it stands, the current callback setup does not allow for this. 

### Your contribution

I can work on this, once I am given the green light.

### PR DESCRIPTION
**Pull request by dhruvbpai**
# Add on_optimizer_step callback option in TrainerCallbacks

Aside: This is my first open source pull request, so any feedback would be much appreciated!

The test `tests/trainer/test_trainer_callback.py` has been modified appropriately to invoke the new callback method.

Fixes #31033  (issue)

## Reviewers
As tagged in initial issue - @muellerzr @younesbelkada

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
This looks great to me thanks !

**Review by muellerzr — APPROVED** [review]
Makes sense to me as well! Nice job. cc @amyeroberts for final review

**Review by LysandreJik — APPROVED** [review]
Awesome, LGTM! Thanks a lot :hugs:

**Comment by PangziZhang523** [comment]
Hello, thank you for your contribution. I used on_optimizer_step to print the gradient, and all the printed values ​​were None, but the final grad_norm had a value. Why is that?

**Comment by colmon46** [comment]
> Hello, thank you for your contribution. I used on_optimizer_step to print the gradient, and all the printed values ​​were None, but the final grad_norm had a value. Why is that?

Same question with @PangziZhang523 . Do you know how to fix this problem plz?

**Comment by Arunprakash-A** [comment]
It is working fine for me.

**Comment by YeLuoSuiYou** [comment]
> > Hello, thank you for your contribution. I used on_optimizer_step to print the gradient, and all the printed values ​​were None, but the final grad_norm had a value. Why is that?
> 
> Same question with @PangziZhang523 . Do you know how to fix this problem plz?

Hi @colmon46, if we use deepspeed or FSDP, we should use self.model_wrapped to get gradient of every layers, but do you know how can we get self.model_wrap in callbacks, 3ku

**Comment by Gaoyg** [comment]
> > Hello, thank you for your contribution. I used on_optimizer_step to print the gradient, and all the printed values ​​were None, but the final grad_norm had a value. Why is that?
> 
> Same question with @PangziZhang523 . Do you know how to fix this problem plz?

Same question. Is there a solution already? thx~

**Pull request merged**
