### PR TITLE
Fix smart check

### LINKED ISSUE #25944: #25871 slows down non-CPU runs
See https://github.com/huggingface/transformers/pull/25871#issuecomment-1704067642

(copy paste)

Using `repr` [here](https://github.com/huggingface/transformers/blob/0afa5071bd84e44301750fdc594e33db102cf374/src/transformers/utils/generic.py#L79) significantly slows down non-CPU runs (-33% on HPU, probably similar numbers on GPU). Which makes sense as `repr` copies data from the device to the host.
Could we rely on `type(x)` instead?

Here is a code snippet to measure it:
```py
import time
import torch

cpu_tensor = torch.ones(512, 512, device="cpu")
gpu_tensor = torch.ones(512, 512, device="cuda")

n = 100

t0 = time.perf_counter()
for i in range(n):
    _ = repr(cpu_tensor)
t1 = time.perf_counter()
for i in range(n):
    _ = repr(gpu_tensor)
t2 = time.perf_counter()

print("CPU time:", t1-t0)
print("GPU time:", t2-t1)
```

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Fix #25944

### CODE REVIEW

**Review by regisss — APPROVED** [review]
LGTM! Thanks @ydshieh :slightly_smiling_face:

**Comment by ydshieh** [comment]
Going to merge as not to block the release.

**Comment by ydshieh** [comment]
(once #25963 is merged)

**Review by LysandreJik — APPROVED** [review]

**Review by ArthurZucker — APPROVED** [review]
Looks good to me! As long as the performances are following 😉

**Pull request merged**
