### PR TITLE
Fix reproducible tests in Trainer

### PR DESCRIPTION
**Pull request by sgugger**
This fixes the tests that were using hardcoded values for reproducible training by testing instead the training yields the same result as one run with the same seed during setup. As a result, it can also run in a multigpu-environment (which is why I removed the decorator).

I also fixed the batch size to count the number of steps, which should also fix those tests for multigpu-environent. @stas00, when you get a chance to run the tests on that file, it would be great to know if the fix worked as intended.

### CODE REVIEW

**Comment by stas00** [comment]
with both gpus seen:

```
pytest tests/test_trainer.py
Test session starts (platform: linux, Python 3.8.5, pytest 6.0.1, pytest-sugar 0.9.4)
Using --randomly-seed=3075405078
rootdir: /mnt/nvme1/code/huggingface/transformers-master
plugins: xdist-2.1.0, forked-1.3.0, hydra-core-1.0.0, pspec-0.0.4, sugar-0.9.4, randomly-3.4.1, cov-2.10.1, flakefinder-1.0.0
collecting ... 
 tests/test_trainer.py ✓✓✓✓✓                                                                                                            45% ████▋     

――――――――――――――――――――――――――――――――――――――――――――――― TrainerIntegrationTest.test_train_and_eval_dataloaders ―――――――――――――――――――――――――――――――――――――――――――――――

self = <tests.test_trainer.TrainerIntegrationTest testMethod=test_train_and_eval_dataloaders>

    def test_train_and_eval_dataloaders(self):
        trainer = get_regression_trainer(learning_rate=0.1, per_device_train_batch_size=16)
>       self.assertEqual(trainer.get_train_dataloader().batch_size, 16)
E       AssertionError: 32 != 16

tests/test_trainer.py:144: AssertionError
```

**Comment by sgugger** [comment]
Could you retest now?

**Comment by stas00** [comment]
Success!

**Comment by sgugger** [comment]
Thanks for checking @stas00 !

**Review by LysandreJik — APPROVED** [review]
Great, thanks a lot!

**Pull request merged**
