### PR TITLE
[vulnerability] dep fix

### PR DESCRIPTION
**Pull request by stas00**
Fixes https://github.com/huggingface/transformers/security/dependabot/examples/research_projects/lxmert/requirements.txt/Pygments/open

@LysandreJik

### CODE REVIEW

**Review by LysandreJik — APPROVED** [review]
Heh, I didn't see @dependabot open a PR for that, weird! Thanks a lot for offering a PR once again @stas00!

**Comment by stas00** [comment]
Oh, is this process somehow automated and I didn't know about it? All I see is the file which it complains about and no suggestion to automate the fix.

**Comment by LysandreJik** [comment]
Yeah, but usually it's not as good as your suggestion as it offers `==` while you offer `>=`.

I think I mentioned it here: https://github.com/huggingface/transformers/pull/10817

But thank you nonetheless, these are helpful!

**Comment by stas00** [comment]
Hmm, I have been copying exactly what the vulnerability bot suggested - which is always `>=` - so it's probably the dependabot that could use a bit of an update to match the vulnerability report.

But it's good to know that this is already automated, I will know not to make a PR next time.

**Pull request merged**
