### PR TITLE
Fix failing windows

### PR DESCRIPTION
**Pull request by LysandreJik**
Fixes an encoding issue on Windows following the merge of the import structure refactor

### CODE REVIEW

**Comment by LysandreJik** [comment]
verified here that it was fixing what it intends to fix: https://github.com/huggingface/trl/pull/2051

**Comment by LysandreJik** [comment]
Merging with offline approval from @ArthurZucker

**Comment by tqangxl** [comment]
> Fixes an encoding issue on Windows following the merge of the import structure refactor
release new ver.？

**Comment by LysandreJik** [comment]
@tqangxl, the merge of the import structure was not in a release, so expediting this fix in a release doesn't necessarily make sense.

**Pull request merged**
