### PR TITLE
Better regex expression for extracting language code in tokenization_marian.py

### PR DESCRIPTION
**Pull request by soumya-ch**
# Better regex expression for extracting language code in tokenization_marian.py

In `tokenization_marian.py`, the regex `>>.+<<` is used to extract the language token from the sentences leading to the following incorrect tokenization.

```
Example Sentence:
>>hin<< We use cout<< function to print a line in C++.

Current Tokenizer gives:
['<unk>', '▁function', '▁to', '▁print', '▁a', '▁line', '▁in', '▁C', '++', '.', '</s>']

Expected Tokenization:
['>>hin<<', '▁We', '▁use', '▁c', 'out', '<', '<', '▁function', '▁to', '▁print', '▁a', '▁line', '▁in', '▁C', '++', '.', '</s>']
```

This pull request changes the regex to `>>.{3}<<|>>.{3}\_.{4}<<` which covers the 194 language tags in the en-mul model.

@sshleifer

### CODE REVIEW

**Review by sshleifer — COMMENTED** [review]
Great Catch!

Does this cover 2 character language codes, like those required for `'Helsinki-NLP/opus-mt-en-ROMANCE'`, e.g.
```python
src_text = [ '>>fr<< this is a sentence in english that we want to translate to french', '>>pt<< This should go to portuguese', '>>es<< And this to Spanish']
```

Would you be willing to add a test that covers many types of language codes including those that are currently breaking?

**Comment by sshleifer** [comment]
cc @patrickvonplaten

**Comment by soumyac1999** [comment]
No, 2 character language codes are not covered. However `>>.{2}<<|>>.{3}<<|>>.{3}\_.{4}<<` can be used.

I can try writing tests. Is these somewhere where I could find an exhaustive set of language codes? I had written the regex to cover the 194 language code in `'Helsinki-NLP/opus-mt-en-mul'`.

```python
```

**Comment by soumyac1999** [comment]
No, 2 character language codes are not covered. However `>>.{2}<<|>>.{3}<<|>>.{3}\_.{4}<<` can be used.

I can try writing tests. Is these somewhere where I could find an exhaustive set of language codes? I had written the regex to cover the 194 language code in `'Helsinki-NLP/opus-mt-en-mul'`.

```pythondef test_language_codes(self):
        tok = MarianTokenizer.from_pretrained(f"{ORG_NAME}opus-mt-en-mul")
        batch = tok.prepare_seq2seq_batch([">>hin<< I am a small frog", ">>zlm_Latn<< I am a small frog", "">>fr<< I am a small frog"], return_tensors=FRAMEWORK)
        self.assertIsInstance(batch, BatchEncoding)
        self.assertEqual(batch.input_ids.shape, (2, 512))
```

**Comment by sshleifer** [comment]
> Is there somewhere where I could find an exhaustive set of language codes?
Not easily.

Your new regex + test should work.

**Pull request closed without merging**
