### PR TITLE
Respect the config's attn_implementation if set

### LINKED ISSUE #32082: kwargs pop "attn_implement" twice in modeling_utils.py and configuration_utils.py when use AutoConfig/AutoModel
### System Info
Pop “attn_implement” twice from modeling_utils.py and configuration_utils.py causes a bug in which attn_cls selection is affected.

image

### Who can help?

_No response_

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

    config = AutoConfig.from_pretrained(
        "deepseek-ai/deepseek-moe-16b-base",
        hidden_size=32,
        intermediate_size=32,
        num_hidden_layers=2,
        num_attention_heads=8,
        # vocab_size=2000,
        first_k_dense_replace=1,
        attn_implementation="flash_attention_2",
        torch_dtype="float16",
        n_routed_experts=8,
        trust_remote_code=True,
    )
    model = transformers.AutoModel.from_config(config, trust_remote_code=True)

### Expected behavior
Set the implementation of attention to flash attention instead of sdpa

### PR DESCRIPTION
**Pull request by amyeroberts**
# What does this PR do?

At the moment - if a user sets the attn_implementatation within a config, and then creates a model using `from_config`, the attention implementation isn't respected. 

For example, in the following, SDPA would be selected for the model: 

```py
from transformers import AutoConfig, AutoModel

checkpoint = "bert-base-uncased"
config = AutoConfig.from_pretrained(checkpoint, attn_implementation="eager")
model = AutoModel.from_config(config)
print(model.config._attn_implementation)
```

This PR:
* Ensures `attn_implementation` is respected if set in the config
* Ensures `attn_implementation` can be overridden in the `from_config` call
* Ensures previous `attn_implementation` setting in `from_config` remains if not set in config intially
* Adds test for the above

We have to use `_attn_implementation_internal` as this tells us if this has actually been set by the user. Otherwise `_attn_implementation` will return `"eager"` both if this has been specified by the user and if nothing is set

Fixes #32082

### CODE REVIEW

**Comment by amyeroberts** [comment]
cc @zucchini-nlp as this might relate to your current work on attn_implemenation and the configs

**Comment by zucchini-nlp** [comment]
Interesting, thanks for letting know! One more case to take care of :)

**Review by ArthurZucker — APPROVED** [review]
👍🏻 nice tests, and makes sense. 
If someone saved the `attn_implementation` in the `config.json` I suppose it would be propagated (config.form_pretrained(), model.from_config) but it's logical IMO!

**Comment by amyeroberts** [comment]
> If someone saved the attn_implementation in the config.json I suppose it would be propagated (config.form_pretrained(), model.from_config) but it's logical IMO!

@ArthurZucker True! I think this only happens if someone manually edits the config file though, as we don't save a config's attn_implementation out automatically. In this case, as it's pretty intentional by the user, I think it should be OK

```py
In [1]: from transformers import AutoConfig

In [2]: config = AutoConfig.from_pretrained('bert-base-uncased')

In [3]: config = AutoConfig.from_pretrained('bert-base-uncased', attn_implementation="flash_attention_2")

In [4]: config._attn_implementation
Out[4]: 'flash_attention_2'

In [5]: config.save_pretrained("/Users/amyroberts/Desktop/test_attn_config")

In [6]: config = AutoConfig.from_pretrained("/Users/amyroberts/Desktop/test_attn_config")

In [7]: config._attn_implementation
Out[7]: 'eager'
```

**Pull request merged**
