### PR TITLE
Fixed KeyError for Mistral

### PR DESCRIPTION
**Pull request by MatteoRaso**
# What does this PR do?

Fixes KeyError for Mistral. convert_mistral_weights_to_hf.py checks for the key "ragged_attention", but the HF release of mistral uses "sliding_window" instead.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by LysandreJik — COMMENTED** [review]
WDYT @ArthurZucker ?

**Review by ArthurZucker — APPROVED** [review]
Hey! Seems like you are right if I download the mistral checkpoint the content of the params.json is:
```python 
{
    "dim": 4096,
    "n_layers": 32,
    "head_dim": 128,
    "hidden_dim": 14336,
    "n_heads": 32,
    "n_kv_heads": 8,
    "norm_eps": 1e-05,
    "sliding_window": 4096,
    "vocab_size": 32000
}
```
thanks for the catch let's remove the try catch and only look for the correct parameter

**Comment by MatteoRaso** [comment]
Ok, I changed it. The reason why I put a try catch was in case there were mistral checkpoints that actually did use "ragged_attention". Is it possible that the torrent release and the HF release are slightly different? That might explain how this happened.

**Comment by ArthurZucker** [comment]
I am not really sure I try downloading from the link they share in their repo: https://github.com/mistralai/mistral-src#download-the-model. Would you mind checking to make sure the publicly shared checkpoints all use sliding window? 🤗

**Comment by MatteoRaso** [comment]
I just downloaded the torrent checkpoint, and it also uses "sliding_window". Between that, HF, and Github, I'm pretty sure that's all the releases.

------- Original Message -------

**Comment by ArthurZucker** [comment]
Cool let's merge then!

**Pull request merged**
