### PR TITLE
docs: rewrite some document

### PR DESCRIPTION
**Pull request by pphuc25**
Just doing some documents for easier to read
I would like to cc @MKhalusova to review my code.

### CODE REVIEW

**Comment by pphuc25** [comment]
@MKhalusova can you help explain why my code fail the test case, this seem like no problem with my view.

**Comment by MKhalusova** [comment]
Can you provide more context on what this PR is trying to achieve? 
Also, I may not be the right person to ping for a review.

**Comment by pphuc25** [comment]
I do document, there's something like missing punctuation so I add it, and also add new extension code to reduce reduntant, but this fails so at now I return extension to origin

**Comment by pphuc25** [comment]
I would like cc @amyeroberts to review my code

**Pull request closed without merging**
