### PR TITLE
Use protobuf 4

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

I move forward to generate the new `src/transformers/utils/sentencepiece_model_pb2.py` using the protocol buffer compiler. No test failure but have a quality check fails. I can probably removed the undefined part `_TRAINERSPEC` which doesn't seem used.

### CODE REVIEW

**Comment by ydshieh** [comment]
I have checked to make sure `protobuf==4.23.3` is installed and used in the CI.

**Comment by ydshieh** [comment]
@Narsil mentioned we should keep the old/new version files, and determine which one to use (by the protobuf version numbers?).

Let me know more details about this please.

**Review by sgugger — COMMENTED** [review]
I think we might need to keep the old one in case the user has an older version of protobuf, otherwise the conversion won't work. And then dynamically add either the old protobuf stuff or the new one depending on the version detected.

**Review by sgugger — APPROVED** [review]
Works for me!

**Comment by ydshieh** [comment]
Will merge once the CI for protobuf 4 a nd protobuf 3 both green.

Don't hesitate to leave comments later if any @Narsil 🙏

**Comment by Narsil** [comment]
Great PR. I hope this doesn't have any unforeseen consequence (I don't know what are the breaking changes between protobuf 3 and 4)

**Comment by ydshieh** [comment]
> I don't know what are the breaking changes between protobuf 3 and 4

Yeah, me neither. I just rely on our CI 🤞

**Comment by fxmarty** [comment]
@ydshieh I'm now getting

```
  File "/home/fxmarty/hf_internship/transformers/src/transformers/utils/sentencepiece_model_pb2_new.py", line 16, in <module>
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
TypeError: Couldn't build proto file into descriptor pool: Invalid default '0.9995' for field sentencepiece.TrainerSpec.character_coverage of type 2
```

with protobuf=4.23.4 & transformers main when doing `from transformers.utils import sentencepiece_model_pb2_new`. Any idea?

**Comment by ydshieh** [comment]
Hi again

@fxmarty `4.23.4` works for me.




```
(py39) λ pip show protobuf
Name: protobuf
Version: 4.23.4

Python 3.9.13 (main, Oct 13 2022, 21:23:06) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers.utils import sentencepiece_model_pb2
>>> from transformers.utils import sentencepiece_model_pb2_new
>>>
```

**Comment by ydshieh** [comment]
Hmm, it fails on Ubuntu machine. Let me check.

**Comment by ydshieh** [comment]
Hm, there is something wrong and I am looking deeper.

**Comment by ArthurZucker** [comment]
Comes from #24690

**Comment by ydshieh** [comment]
@fxmarty We are not able to reproduce the situation you have. Could you specify your transformers commit that is installed? Thanks.

(The above discussion is another story)

**Comment by fxmarty** [comment]
@ydshieh It appears I can't reproduce anymore the issue I had. Must have messed something up in my install that I fixed since then.

**Comment by fxmarty** [comment]
@ydshieh Oh, actually I have this issue only running in my scripting IDE pyzo, but not in a terminal. The same python env is used so quite weird.

**Comment by fxmarty** [comment]
@ArthurZucker @ydshieh What is the relationship between `sentencepiece_model_pb2.py` and `sentencepiece_model_pb2_new.py`? The error I get seem to be related to the type of `TrainerSpec.character_coverage`, that is defined in `sentencepiece_model_pb2.py`.

**Comment by ydshieh** [comment]
Hi @fxmarty 

That file is being generated by protobuf compile. I don't have the courage to read it ...

When I enable the support to use protobuf v4, I ran the whole CI (non-slow), and no failed test.

Could you show us your usage (related to protobuf) that produce some failures - maybe I can help ?

**Pull request merged**
