### PR TITLE
Translate docs into Arabic issue-number #32435

### PR DESCRIPTION
**Pull request by AhmedAlmaghz**
# What does this PR do?
Translate docs into Arabic issue-number #32435
@stevhliu and @MKhalusova

### CODE REVIEW

**Comment by stevhliu** [comment]
Hi! 

It is extremely difficult to review 400+ file changes. For translations, you should work on translating one file at a time, get it reviewed by a native Arabic speaker, and then move on to the next document. Translations should also be done manually to ensure nothing gets lost in translation, which can sometimes happen when using machine translation programs/apps.

I noticed you opened similar PRs in the Diffusers/Datasets repositories. The same comment here applies to those PRs as well.

- https://github.com/huggingface/diffusers/pull/9121
- https://github.com/huggingface/datasets/pull/7094

I'd suggest closing these PRs and then opening just one PR focused on translating one document. Thanks! 🤗

**Comment by AhmedAlmaghz** [comment]
I have been working on the translation for more than two months and I manually translate each file and now that I have finished I have uploaded the translation to you.
@stevhliu

**Comment by amyeroberts** [comment]
Hi @AhmedAlmaghz, thank you for dedicating so much time in translating the docs! 

It's simply just not feasible for someone to review a PR of this size. For context, the general rule for PRs is that there shouldn't be more than 400 lines of diff for the reviewer. Here there's 61k. You should be able to separate out the file commits into their own PRs, which can then be reviewed.

**Comment by abodacs** [comment]
@AhmedAlmaghz 
Thanks for the great work.

I will be happy to review small PRs, you did what I procrastinating for a long time. 
You can cherry-pick commit/s into separate branches, open a PR, and mention me for reviewing.

Thank you again for the hard work and great addition to the Arabic community (جزاء الله خيرأ)

**Pull request closed without merging**
