### PR TITLE
Adding doctest for `object-detection` pipeline.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — COMMENTED** [review]
Same comments as on the other PRs :-)

**Review by alaradirik — APPROVED** [review]
I still think the `candidate_labels` argument/naming is not very aligned with zero-shot object detection but the PR looks good to me otherwise.

**Review by sgugger — APPROVED** [review]

**Comment by alaradirik** [comment]
> Here it's just an alias. I'm really not sure I understand how it could be a bad name.
> 
> Happy to hear your thoughts on why you think it fits better.

@Narsil my main concern is that zero-shot-classification pipeline selects one of the `candidate_labels` to assign a final class / label to the image, whereas zero-shot-object-detection queries the image for each query and might find instances of all query objects. It'd be less confusing to users if we add a better docstring example -> using an image where both candidate_labels=["head", "bird"] are detected instead of just "bird".

**Comment by Narsil** [comment]
> @Narsil my main concern is that zero-shot-classification pipeline selects one of the candidate_labels to assign a final class / label to the image, whereas zero-shot-object-detection queries the image for each query and might find instances of all query objects. It'd be less confusing to users if we add a better docstring example -> using an image where both candidate_labels=["head", "bird"] are detected instead of just "bird".

Oh, but no, `zero-shot-classification` does multi label classification actually. The default is to normalize scores across labels, but it's not mandatory, by default the models can handle multiple label just fine (results tend to be more noisy though).

https://huggingface.co/facebook/bart-large-mnli?candidateLabels=space+%26+cosmos%2C+scientific+discovery%2C+microbiology%2C+robots%2C+archeology&multiClass=true&text=A+new+model+offers+an+explanation+for+how+the+Galilean+satellites+formed+around+the+solar+system%E2%80%99s+largest+world.+Konstantin+Batygin+did+not+set+out+to+solve+one+of+the+solar+system%E2%80%99s+most+puzzling+mysteries+when+he+went+for+a+run+up+a+hill+in+Nice%2C+France.+Dr.+Batygin%2C+a+Caltech+researcher%2C+best+known+for+his+contributions+to+the+search+for+the+solar+system%E2%80%99s+missing+%E2%80%9CPlanet+Nine%2C%E2%80%9D+spotted+a+beer+bottle.+At+a+steep%2C+20+degree+grade%2C+he+wondered+why+it+wasn%E2%80%99t+rolling+down+the+hill.+He+realized+there+was+a+breeze+at+his+back+holding+the+bottle+in+place.+Then+he+had+a+thought+that+would+only+pop+into+the+mind+of+a+theoretical+astrophysicist%3A+%E2%80%9COh%21+This+is+how+Europa+formed.%E2%80%9D+Europa+is+one+of+Jupiter%E2%80%99s+four+large+Galilean+moons.+And+in+a+paper+published+Monday+in+the+Astrophysical+Journal%2C+Dr.+Batygin+and+a+co-author%2C+Alessandro+Morbidelli%2C+a+planetary+scientist+at+the+C%C3%B4te+d%E2%80%99Azur+Observatory+in+France%2C+present+a+theory+explaining+how+some+moons+form+around+gas+giants+like+Jupiter+and+Saturn%2C+suggesting+that+millimeter-sized+grains+of+hail+produced+during+the+solar+system%E2%80%99s+formation+became+trapped+around+these+massive+worlds%2C+taking+shape+one+at+a+time+into+the+potentially+habitable+moons+we+know+today.

**Pull request merged**
