### PR TITLE
Remove pytorch codes in Class TFXLNetMainLayer

### PR DESCRIPTION
**Pull request by ZhuBaohe**
This PR removes pytorch codes in Class TFXLNetMainLayer.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Sorry I don't really understand how this PR removes pytorch code in `TFXLNetMainLayer` - can you explain a bit more in-detail?

**Comment by ZhuBaohe** [comment]
@patrickvonplaten  
The codes in file modeling_tf_xlnet.py  is the XLNet Model of tensorflow implementation. So the parameter **head_mask**  should have a type of tf.Tensor or Numpy array (see Line 780 ).
But in  Line 642-652, the parameter **head_mask** uses the methods of the pytorch, such as "expand" or "unsqueeze" which can't apply to tf.Tensor or Numpy array. Indeed, these codes are copied from modeling_xlnet.py incorrectly and should be removed.

**Comment by patrickvonplaten** [comment]
Perfect thanks a lot! 

@LysandreJik  - the RUN_SLOW=1 tests all poss for TFXLNetMainLayer.

Good to merge for me!

**Review by LysandreJik — APPROVED** [review]
LGTM, thanks @ZhuBaohe

**Pull request merged**
