### PR TITLE
[WIP] Hivemind Integration

### PR DESCRIPTION
**Pull request by chavinlo**
# What does this PR do?

This PR (will) add integration for hivemind (https://github.com/learning-at-home/hivemind), a PyTorch library for decentralized deep learning across the Internet.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by chavinlo** [comment]
The idea is to allow for an "infinite run" with hivemind where users can join using the hivemind DHT.
The DHT will have to be initialized before initiating the trainingarguments so that the user can mess with it more freely, then the optimizer kwargs will just be passed on internally.

Most of the changes are related to `max_steps`. Although hivemind should be able to work with it, I think it would be better to not use it to let it scale freely.

Right now I am having some issues with `steps_trained_in_current_epoch`, the tqdm progress bar, and wandb being enabled out of nowhere.

Some feedback would be nice.

**Review by sgugger — COMMENTED** [review]
Thanks for your PR! This rewrites a lot of the `Trainer` internals, so maybe it should be better to define a `Trainer` subclass hosted on the `hivemind` side?

**Comment by chavinlo** [comment]
> Thanks for your PR! This rewrites a lot of the `Trainer` internals, so maybe it should be better to define a `Trainer` subclass hosted on the `hivemind` side?

I was thinking of that too but then what would happen with the sub trainers? (Seq2Seq for example) I have no problem with that though.

**Comment by chavinlo** [comment]
> Right now I am having some issues with steps_trained_in_current_epoch, the tqdm progress bar, and wandb being enabled out of nowhere. However, it seems it can run some steps, it just doesn't reports it (wandb or progress bar)

@sgugger

**Comment by chavinlo** [comment]
Will reopen this once I believe it's good enough and has a clean integration.
For now I will just use it internally

**Pull request closed without merging**
