### PR TITLE
fix plbart doctest

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

We need to update the expect output in doc example after PR #19980

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for fixing!

**Comment by soma2000-lang** [comment]
@ydshieh @sgugger I just want to know how this PR works and why was the doctests failing earlier? Thanks in advance!

**Comment by ydshieh** [comment]
As the PR description mentioned, PR #19980 changed `PLBartTokenizer`, and some expected outputs in the tests have to be updated.

**Comment by soma2000-lang** [comment]
@ydshieh got it. Thanks!

**Pull request merged**
