### PR TITLE
Warn if debug requested without TPU fixes (#6308)

### PR DESCRIPTION
**Pull request by dmlap**
Check whether a PyTorch compatible TPU is available before attempting to print TPU metrics after training has completed. This way, users who apply `--debug` without reading the documentation aren't suprised by a stacktrace.

### CODE REVIEW

**Comment by dmlap** [comment]
The CircleCI failures look like a pre-existing line length violation in `trainer.py` and a checksum mismatch downloading transformers itself for `run_tests_torch`. I don't believe either are related to my change – I was able to run the examples test suite locally and everything passed. I'd be happy to fix the line length issue, if that helps. I think it would take me awhile to figure out what's going on with the checksum mismatch.

**Comment by LysandreJik** [comment]
Hi! There was an issue with the style in your PR, I pushed the fix. Will merge once all the tests are green!

**Comment by LysandreJik** [comment]
Thanks for your contribution :)

**Comment by dmlap** [comment]
No problem! Thanks for the style-fixup, @LysandreJik.

**Pull request merged**
