### PR TITLE
make SpeechT5 doc examples deterministic

### PR DESCRIPTION
**Pull request by hollance**
# What does this PR do?

Fixes an issue with the doc examples for SpeechT5. Due to the dropout layer being used in inference mode, the predicted sequence length is not always the same, which causes the doc tests to fail. Setting the seed fixes this.

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by ydshieh** [comment]
Thank you @hollance . Before I could merge, could you change the docstrings that contain(s)

```
dataset = load_dataset(...) 
```
to 
```
dataset = load_dataset(...)   # doctest: +IGNORE_RESULT
```

🙏 Thank you.

**Comment by hollance** [comment]
@ydshieh If I do this, `make fixup` will wrap this code like so:

```python
        >>> dataset = load_dataset(
        ...     "hf-internal-testing/librispeech_asr_demo", "clean", split="validation"
        ... )  # doctest: +IGNORE_RESULT
```

Is that OK?

**Comment by ydshieh** [comment]
> @ydshieh If I do this, `make fixup` will wrap this code like so:
> 
> ```python
>         >>> dataset = load_dataset(
>         ...     "hf-internal-testing/librispeech_asr_demo", "clean", split="validation"
>         ... )  # doctest: +IGNORE_RESULT
> ```
> 
> Is that OK?

totally OK :-)

**Review by ydshieh — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
