### PR TITLE
Fix eval accumulation when `accelerate` > 0.20.3

### PR DESCRIPTION
**Pull request by sam-scale**
As mentioned in: https://github.com/huggingface/transformers/issues/25641

Eval accumulation will never happen with `accelerate > 0.20.3`, so this change ensures that `sync_gradients` is ignored if accelerate is > 0.20.3

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by amyeroberts — APPROVED** [review]
Thanks for this fix! 

Looks OK to me cc @muellerzr for a second opinion before merging

**Comment by sam-scale** [comment]
@muellerzr any thoughts :)

**Review by muellerzr — APPROVED** [review]
Solution looks good to me as well. Thanks for the fix!

**Comment by sam-scale** [comment]
Thanks! @amyeroberts @muellerzr is there any way to track when this fix will get added to a release?

**Pull request merged**
