### PR TITLE
Use `-v` for `pytest` on CircleCI 

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

So we get info about which process run which tests

> [gw4] [ 99%] PASSED tests/models/kosmos2/test_processor_kosmos2.py::Kosmos2ProcessorTest::test_model_input_names 
tests/models/kosmos2/test_processor_kosmos2.py::Kosmos2ProcessorTest::test_processor 
[gw3] [ 99%] PASSED tests/models/pix2struct/test_processor_pix2struct.py::Pix2StructProcessorTest::test_model_input_names 
tests/models/pix2struct/test_processor_pix2struct.py::Pix2StructProcessorTest::test_processor 
[gw0] [ 99%] PASSED tests/models/bloom/test_tokenization_bloom.py::BloomTokenizationTest::test_training_new_tokenizer 

Full CI will produce ~100K lines. The output is also saved and uploaded as artifact.

### CODE REVIEW

**Comment by ydshieh** [comment]
Example run

https://app.circleci.com/pipelines/github/huggingface/transformers/83697/workflows/6b7bf7c2-cf98-474c-a3dd-3eea4cfa0cfa

**Comment by amyeroberts** [comment]
For context for anyone coming cold to this PR - the motivation for introducing this is to enable retrieving which tests were run on which process to help when debugging.

Recently we had an issue with flaky tests, because some tests were affecting other tests. For example, the global logger state - which was resolved in #28638. Failures like these only happen sporadically because the interacting tests aren't always in the same process. 

Having the outputs means we can easily narrow down the culprit tests to a subset of size `1 / pytest_num_workers`.

**Review by amyeroberts — APPROVED** [review]
Beautiful ❤️ Thanks for adding and testing this!

**Comment by ydshieh** [comment]
I guess it's still not (super) easy to achieve re-run the subset of tests that were run in a process (grabbed from log). For example, we might get 20000 test names. It won't work if we concatenate those many test names and paste that long line to the terminal to run the test. 

We can have some utility to grab the folders (their name) seen by a process. This is more realistic, but not urgent task. I could work on this later.

**Pull request merged**
