### PR TITLE
Typo in `modeling_clip.ClipVisionTransformer`

### PR DESCRIPTION
**Pull request by AdityaKane2001**
Fixed a typo in `modeling_clip.py`.

### CODE REVIEW

**Review by amyeroberts — COMMENTED** [review]
Hi @AdityaKane2001, thanks for opening this PR!

Unfortunately, we can't change the layer names like this, as it affects the state dict, will mean previous checkpoints won't be correctly loaded in and is therefore a breaking change.

**Comment by AdityaKane2001** [comment]
@amyeroberts 

Yes, I realized that when I tried to incorporate the change in my fork. Maybe the maintainers might have to do this, but what would be a solution in this case? Apart from the brute-force one, i.e. changing names in _all_ hosted clip weights.

**Comment by amyeroberts** [comment]
@AdityaKane2001 It's not something that we're going to try to fix. It's a bit annoying but effectively not consequential. The solution is to put up with the original spelling :)

**Comment by AdityaKane2001** [comment]
Gotcha. Closing the PR.

**Pull request closed without merging**
