### PR TITLE
[WIP] Add MMBT Model to Transformers Repo

### PR DESCRIPTION
**Pull request by suvrat96**
Implements the MMBT Model from Supervised Multimodal Bitransformers for Classifying Images and Text by Douwe Kiela, Suvrat Bhooshan, Hamed Firooz, Davide Testuggine (https://arxiv.org/abs/1909.02950) (https://github.com/facebookresearch/mmbt/)

Adds run_mmimdb.py to show example training run on MM-IMDb dataset (http://lisi1.unal.edu.co/mmimdb/)

### CODE REVIEW

**Comment by LysandreJik** [comment]
Hi! This is great, thank you for adding this. There's a few things I'll need to change before merging:

- I'll complete the documentation so that it is visible on our huggingface.co/transformers and not only in the source code.
- I'll add some tests
- I'll move the scripts to a folder inside examples, e.g. `examples/mmbt/*`, as it was done with PPLM/Distillation/summarization.

I'll push directly on your fork if that's okay!

**Comment by suvrat96** [comment]
That sounds great. Thank you!

**Comment by LysandreJik** [comment]
I'm trying to run  the `run_mmimdb.py` script, could you tell me where to download the dataset? The link you've provided downloads a .tar that contains a `split.json` as well as training/evaluation data, but no `dev.jsonl` or `train.jsonl` as specified in the `load_examples` method.

**Comment by thomwolf** [comment]
Ok merging, for now, to have the code in the codebase cleanup.
Let's not forget to add:
- documentation
- tests
- pretrained model weights
later so that people can really use the model.

**Comment by SeaOfOcean** [comment]
> I'm trying to run the `run_mmimdb.py` script, could you tell me where to download the dataset? The link you've provided downloads a .tar that contains a `split.json` as well as training/evaluation data, but no `dev.jsonl` or `train.jsonl` as specified in the `load_examples` method.
where is the `dev.jsonl` or `train.jsonl`

**Comment by SeaOfOcean** [comment]
where is the `dev.jsonl` or `train.jsonl`?

**Pull request merged**
