### PR TITLE
Clean up staging tmp checkpoint directory

### PR DESCRIPTION
**Pull request by woshiyyya**
# What does this PR do?

In PR #28364 , it changed the checkpoint folder renaming logic, which makes only local_rank_0 workers or global_rank_0 worker to rename the checkpoint dir from `tmp-checkpoint-*` to `checkpoint-*`. It will be a noop on other ranks.

When we have multiple nodes, and if you save on global rank 0 only, the tmp checkpoint dir on other nodes might not get cleaned up on. This PR checks and deletes those tmp directories.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by woshiyyya** [comment]
cc @sgugger @pacman100 @muellerzr

**Comment by amyeroberts** [comment]
@pacman100 Is pinging me for review here a signal that you approve of these changes and it's ready for final review?

**Comment by woshiyyya** [comment]
Any updates on this?

**Comment by amyeroberts** [comment]
@pacman100 Requested review from you to confirm this fix is in line with expected trainer behaviour. Once you've approved I can do the final maintainer review

**Review by pacman100 — APPROVED** [review]
Thank you @woshiyyya for the fix, makes sense!

**Review by amyeroberts — APPROVED** [review]
Thanks for adding this fix!

**Comment by FKyms** [comment]
Does this pr work when multi node using deferent storage system?  If multi nodes use the same file system, this pr seems useless and involves new problem: non global rank0 may rmtree the tmp-checkpoint dir before global rank0 rename

**Comment by renhouxing** [comment]
> Does this pr work when multi node using deferent storage system? If multi nodes use the same file system, this pr seems useless and involves new problem: non global rank0 may rmtree the tmp-checkpoint dir before global rank0 rename

Yes, I have encountered this problem: non global rank0 rmtree the tmp-checkpoint dir before global rank0 rename

**Comment by sinamoeini** [comment]
I am getting an error because of this PR. all the local zero processes try to delete the same dir that is on shared file system between the nodes

**Comment by linhdvu14** [comment]
I'm running into the same issue as @sinamoeini. Kindly help to review @woshiyyya.

**Comment by woshiyyya** [comment]
Got it. It could be a problem when using a shared file system. 

Let's revert this PR? https://github.com/huggingface/transformers/pull/29336 cc @amyeroberts @pacman100

**Comment by sinamoeini** [comment]
so I replaced [https://github.com/huggingface/transformers/blob/v4.38.0/src/transformers/trainer.py#L2552](this line) with 

```
elif self.is_local_process_zero() and self.args.save_on_each_node:
```
and it worked. Not sure if it will cause issue with other setups.

**Comment by passionate11** [comment]
I had the same problem, when using a shared filesystem I would delete the same file repeatedly and get an error, and since the environment was pre-installed I couldn't modify the source code in the trainer.

**Comment by passionate11** [comment]
Downgrading the transformers version to 4.37.0 avoids the problem

**Comment by muellerzr** [comment]
This has been completely reverted by now, the latest transformers install should fix it

**Pull request merged**
