### PR TITLE
Update bug-report.md

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

Small update to have a clearer distinction between @patil-suraj and @patrickvonplaten responsability in Transformers. 
Also added some new models.

@patil-suraj @LysandreJik @sgugger - is that ok for you?

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/master/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/master/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/master/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Also @Narsil, 

I've put you under generate now as well - is this ok? Think you know the method pretty well by now :-)

**Review by LysandreJik — APPROVED** [review]
Yes, that's perfect for me

**Comment by Narsil** [comment]
@patrickvonplaten I am ok with that !

**Review by sgugger — APPROVED** [review]
LGTM!

**Pull request merged**
