### PR TITLE
Add TFViTModel

### PR DESCRIPTION
**Pull request by ydshieh**
# What does this PR do?

Add `TFViTModel`. This is also a prerequisite task before we can add `TFVisionEncoderDecoderModel` as a continuation of `FlaxVisionEncoderDecoderModel` (#13359)

### CODE REVIEW

**Comment by LysandreJik** [comment]
Looking forward to it @ydshieh! Let us know if you need anything to push this to the finish line.

**Review by LysandreJik — COMMENTED** [review]
Thanks a lot for your work on this @ydshieh, this is great!

It would be really nice to have @Rocketknight1 review this, but he'll be slightly busy in the next few days - will review as soon as possible, thank you!

**Comment by Rocketknight1** [comment]
@sgugger suggests that Torch and TF core ops are usually very similar, so a possible culprit is the third-party libraries like torch scatter and TF probability. If you want, you can try to investigate to find the single op that has differing outputs between the two libraries. However, I don't think it's totally necessary since the outputs are mostly very close, so if you're not interested we can probably merge as-is. Up to you!

**Review by Rocketknight1 — APPROVED** [review]

**Comment by Rocketknight1** [comment]
That's perfect, yes. Thanks for your contributions, there's no rush with finishing this PR!

**Comment by ydshieh** [comment]
@Rocketknight1 I have successfully made conv2D weight loading PT <-> TF using their own native shape, and therefore there is no need to transpose the conv. kernel in `TFPatchEmbeddings`.

If this new change is OK for Hugging Face, I will clean up this block

https://github.com/huggingface/transformers/blob/69900345c668defbb34c9071eee6c90d722c7e6e/src/transformers/models/vit/modeling_tf_vit.py#L202-L205

It might be a good idea for a second person to double check the change added to `modeling_tf_pytorch_utils.py`.

Thanks :)

**Comment by ydshieh** [comment]
Use tf.keras.layers.Conv2D instead of tf.nn.conv2d, and it works well with PT/TF weight loading.

**Comment by ydshieh** [comment]
Hi @Rocketknight1 

I saw that heuristic, but felt a bit implicit for using 4D + kernel => Conv2D.
However, it's probably we won't have 4D dense layers, at least not soon, so I am OK to try it :)

`_get_tf_conv2d_kernel_names` is more explicit, but I agree that things might get complicated if we have new different kinds of layers requiring special treatment in this way.

**Comment by Rocketknight1** [comment]
@ydshieh I agree that the heuristic feels a bit dangerous, but we have plenty of tests, so we should notice if it causes any problems!

**Comment by ydshieh** [comment]
I moved the logic of conv2D layer detection into `convert_tf_weight_name_to_pt_weight_name`.
(I found the same check is done for flax <-> pt)

**Review by patrickvonplaten — APPROVED** [review]

**Review by sgugger — APPROVED** [review]
Thanks a lot for your PR, this looks great! I just left a few formatting nits.

**Comment by LysandreJik** [comment]
Hi @ydshieh, I believe most of the errors here are unrelated to your PR: they're related to a recent change in `datasets`. For audio datasets, it now takes care of the audio decoding, but means that you'll need to have `librosa` installed in order to do so. 

We updated our tests to reflect this change, but since your PR has not been rebased on `master` for a while, it doesn't use the updated code. Rebasing on `master` would probably clear all of these issues :)

**Comment by ydshieh** [comment]
@LysandreJik Thanks!

After rebasing on master, there is an issue I need to address (I think this is a recent test @patrickvonplaten added).

```
FAILED tests/test_modeling_vit.py::ViTModelTest::test_pt_tf_model_equivalence
```

**Comment by ydshieh** [comment]
@patrickvonplaten Would be great if you can check (when you have time) the modification done in `test_modeling_common.py` in https://github.com/huggingface/transformers/pull/13778/commits/0e546f6b1e2de5877ffd5c84e71d8d4de178d440

This is necessary to fix the issue appeared previously

```
>   ???
E   tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Conv2D as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Conv2D]
```

**Comment by ydshieh** [comment]
After rebase on master, it's green again :-)

**Comment by sgugger** [comment]
Thanks again for all your work on this!

**Comment by ydshieh** [comment]
@sgugger There is no tf checkpoint for ViT. The test uses from_pt=True, but usage examples in model script don't specify this currently.

I can upload a checkpoint and mâle necessary changes in another PR. But maybe it's better to have TF checkpoint under HF rather than under my repo.

Sorry about this.

**Comment by sgugger** [comment]
We will update TF checkpoints in the repos, then you can make another PR to adapt the tests :-)

**Pull request merged**
