### PR TITLE
[OWL VIT] make daily CI happy

### PR DESCRIPTION
**Pull request by younesbelkada**
# What does this PR do?

Fixes a slow test for OWLViT while trying to integrate `accelerate` support for this model! 

cc @ydshieh @alaradirik 

Slow test that was failing: `tests/models/owlvit/test_modeling_owlvit.py::OwlViTModelIntegrationTest::test_inference_one_shot_object_detection`

all slow tests pass!

### CODE REVIEW

**Review by alaradirik — APPROVED** [review]
Thank you, LGTM!

**Review by ydshieh — APPROVED** [review]
LGTM, but could you link the failed test in your PR description, please?

Also, without this change, would the test fail on GPU? (not with accelerate)

**Comment by younesbelkada** [comment]
Thanks @ydshieh , just updated the description! 
Yes without this change, the test would fail on GPU (`accelerate` tests excluded)

**Review by sgugger — APPROVED** [review]
Thnaks for fixing!

**Pull request merged**
