### PR TITLE
Fix seamless TTS generate

### LINKED ISSUE #34811: `SeamlessM4TForTextToSpeech.generate` not working if `generation_config` is passed
For `SeamlessM4TForTextToSpeech` with checkpoint ` "facebook/hf-seamless-m4t-medium"`, 

> model.generate(**model_inputs, tgt_lang="eng", generation_config=model.generation_config)

will fail with index error.

If not passing `generation_config` argument, it could run without error.

### Reproduction

```python
from transformers import AutoProcessor, SeamlessM4TForTextToSpeech

ckpt = "facebook/hf-seamless-m4t-medium"

processor = AutoProcessor.from_pretrained(ckpt)
model = SeamlessM4TForTextToSpeech.from_pretrained(ckpt)

model_inputs = processor(["This is a test"], return_tensors="pt")

# This works
outputs = model.generate(**model_inputs, tgt_lang="eng")
print(outputs)

# Index error
outputs2 = model.generate(**model_inputs, tgt_lang="eng", generation_config=model.generation_config)
print(outputs2)
```

### Expected behavior

Should not fail if `generation_config` is passed.

### PR DESCRIPTION
**Pull request by ylacombe**
Fix #34811

cc @ydshieh

### CODE REVIEW

**Review by ydshieh — APPROVED** [review]
Thank you!

(a comment would be appreciated even if just a few words 🙏 )

**Comment by ydshieh** [comment]
let me check with the pipeline test - it's where I found this issue.

**Comment by ydshieh** [comment]
it works now! Could you remove 2 lines below: `# TODO` and `@run_test_using_subprocess` before merge? Thanks

```
    # TODO: @ylacombe: `SeamlessM4TForTextToSpeech.generate` has issue with `generation_config`. See issue #34811
    @slow
    @require_torch
    @run_test_using_subprocess
    def test_medium_seamless_m4t_pt(self):
```

**Review by ruidazeng — APPROVED** [review]
LGTM

**Comment by ylacombe** [comment]
I've remove the TODO!

**Comment by ydshieh** [comment]
You can ignore 

> tests/models/seamless_m4t_v2/test_modeling_seamless_m4t_v2.py::SeamlessM4Tv2ModelWithSpeechInputTest::test_retain_grad_hidden_states_attentions

failing on multi-gpu runner.

**Pull request merged**
