### PR TITLE
This PR contains additional changes for #33143

### PR DESCRIPTION
**Pull request by aroun-coumar**
# What does this PR do?

Fixes # (issue)

#32560 
## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#create-a-pull-request),
      Pull Request section?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### Tests Done:

Uploaded sample modelcards post fix

[Adam modelcard](https://huggingface.co/Aroun-coumar/Final_adam_modelcard)
[SGD modelcard](https://huggingface.co/Aroun-coumar/Final_sgd_modelcard)

### CODE REVIEW

**Review by SunMarc — APPROVED** [review]
LGTM ! Thanks for updating this @aroun-coumar ! Could you just update the PR description with all the details of the PR + the tests you did ?

**Review by LysandreJik — APPROVED** [review]
Awesome, thank you!

**Comment by aroun-coumar** [comment]
Hey @SunMarc @LysandreJik  i have updated the PR description

But my tests dont pass no matter what (I'm new to CircleCI)

Can you please point me out the problem please so that i can rectify

Thnaks!

**Comment by SunMarc** [comment]
Can you try to rebase on main ?

**Comment by aroun-coumar** [comment]
> Can you try to rebase on main ?

Hey thanks a lot all of them passed

**Pull request merged**
