### PR TITLE
make `LlamaDynamicNTKScalingRotaryEmbedding` work correctly

### LINKED ISSUE #27226: Current implementation for `DynamicNTKScalingRotaryEmbedding` in modeling_llama.py does not update cos, sin correctly.
`DynamicNTKScalingRotaryEmbedding` is originally designed to update `base` and `inv_freq` with dynamic_length (seq_len / self.max_position_embeddings) for every input sequence. However, current implementation only updates `base` and `inv_freq` only when `seq_len > self.max_seq_len_cached`.

```python
class LlamaRotaryEmbedding(nn.Module):
    def __init__(self, dim, max_position_embeddings=2048, base=10000, device=None):
        super().__init__()

        self.dim = dim
        self.max_position_embeddings = max_position_embeddings
        self.base = base
        inv_freq = 1.0 / (self.base ** (torch.arange(0, self.dim, 2).float().to(device) / self.dim))
        self.register_buffer("inv_freq", inv_freq, persistent=False)

        # Build here to make `torch.jit.trace` work.
        self._set_cos_sin_cache(
            seq_len=max_position_embeddings, device=self.inv_freq.device, dtype=torch.get_default_dtype()
        )

    def _set_cos_sin_cache(self, seq_len, device, dtype):
        self.max_seq_len_cached = seq_len
        t = torch.arange(self.max_seq_len_cached, device=device, dtype=self.inv_freq.dtype)

        freqs = torch.einsum("i,j->ij", t, self.inv_freq)
        # Different from paper, but it uses a different permutation in order to obtain the same calculation
        emb = torch.cat((freqs, freqs), dim=-1)
        self.register_buffer("cos_cached", emb.cos().to(dtype), persistent=False)
        self.register_buffer("sin_cached", emb.sin().to(dtype), persistent=False)

    def forward(self, x, seq_len=None):
        # x: [bs, num_attention_heads, seq_len, head_size]
        if seq_len > self.max_seq_len_cached:
            self._set_cos_sin_cache(seq_len=seq_len, device=x.device, dtype=x.dtype)

        return (
            self.cos_cached[:seq_len].to(dtype=x.dtype),
            self.sin_cached[:seq_len].to(dtype=x.dtype),
        )


class LlamaDynamicNTKScalingRotaryEmbedding(LlamaRotaryEmbedding):
    """LlamaRotaryEmbedding extended with Dynamic NTK scaling. Credits to the Reddit users /u/bloc97 and /u/emozilla"""

    def __init__(self, dim, max_position_embeddings=2048, base=10000, device=None, scaling_factor=1.0):
        self.scaling_factor = scaling_factor
        super().__init__(dim, max_position_embeddings, base, device)

    def _set_cos_sin_cache(self, seq_len, device, dtype):
        self.max_seq_len_cached = seq_len

        if seq_len > self.max_position_embeddings:
            base = self.base * (
                (self.scaling_factor * seq_len / self.max_position_embeddings) - (self.scaling_factor - 1)
            ) ** (self.dim / (self.dim - 2))
            inv_freq = 1.0 / (base ** (torch.arange(0, self.dim, 2).float().to(device) / self.dim))
            self.register_buffer("inv_freq", inv_freq, persistent=False)

        t = torch.arange(self.max_seq_len_cached, device=device, dtype=self.inv_freq.dtype)

        freqs = torch.einsum("i,j->ij", t, self.inv_freq)
        # Different from paper, but it uses a different permutation in order to obtain the same calculation
        emb = torch.cat((freqs, freqs), dim=-1)
        self.register_buffer("cos_cached", emb.cos().to(dtype), persistent=False)
        self.register_buffer("sin_cached", emb.sin().to(dtype), persistent=False)
```

Thus, it needs to be fixed like the following:
```python
class LlamaDynamicNTKScalingRotaryEmbedding(LlamaRotaryEmbedding):
    """LlamaRotaryEmbedding extended with Dynamic NTK scaling. Credits to the Reddit users /u/bloc97 and /u/emozilla"""

    def __init__(self, dim, max_position_embeddings=2048, base=10000, device=None, scaling_factor=1.0):
        self.scaling_factor = scaling_factor
        super().__init__(dim, max_position_embeddings, base, device)

    def forward(self, x, seq_len=None):
        if seq_len <= self.max_position_embeddings:
            dynamic = 1.0
        else:
            dynamic = seq_len / self.max_position_embeddings
        base = self.base * (
            (self.scaling_factor * dynamic) - (self.scaling_factor - 1)
        ) ** (self.dim / (self.dim - 2))
        inv_freq = 1.0 / (base ** (torch.arange(0, self.dim, 2).float().to(x.device) / self.dim))
        t = torch.arange(seq_len, device=x.device, dtype=inv_freq.dtype)
        freqs = torch.einsum("i,j->ij", t, inv_freq)
        emb = torch.cat((freqs, freqs), dim=-1)
        cos, sin = emb.cos(), emb.sin()
        return cos[:seq_len].to(dtype=x.dtype), sin[:seq_len].to(dtype=x.dtype)
```
to: @ArthurZucker @younesbelkada 

### Expected behavior
When using DynamicNTK for llama, cos and sin would be updated correctly.

### PR DESCRIPTION
**Pull request by bzantium**
Fixes #27226 
to: @ArthurZucker, @younesbelkada

### CODE REVIEW

**Comment by hyunwoongko** [comment]
Great PR @bzantium!
I also tested RoPE scaling and realized the cache related code of it was wrong before.
looks much more better in this version.

**Comment by amyeroberts** [comment]
cc @gante

**Comment by gante** [comment]
Hi @bzantium @hyunwoongko 👋 

There has been more than one issue raised regarding DynamicNTK as implemented by the authors and here in `transformers`:
1 - When `use_cache=True`, `past_key_values` is not using the right rotation for sequence lengths larger than the original model length -- https://github.com/huggingface/transformers/issues/25104
2 - [The one this PR addresses] When increasing then decreasing the sequence length, the base is not scaled back -- https://github.com/huggingface/transformers/pull/27033

There are solutions to both problems, but in both cases, they massively decrease the inference speed, which makes it a net negative change. I suspect this PR suffers from the same slowdowns as in https://github.com/huggingface/transformers/pull/27033 -- feel free to use the same test script as in there, taking [this comment](https://github.com/huggingface/transformers/pull/27033#issuecomment-1782738869) into consideration.

If the results are positive, I'd be happy to merge.

**Comment by bzantium** [comment]
Thanks for the comment @gante!
Even though this PR would be slower than current code, the results are very different. I tested with `scaling_type=dynamic, scaling_factor=1` on the [longchat](https://github.com/DachengLi1/LongChat). The results are following:

lines | 50 | 100 | 200 | 300 | 400 | 500 | 600 | 680
-- | -- | -- | -- | -- | -- | -- | -- | --
original | 42 | 6 | 14 | 10 | 4 | 0 | 0 | 0
This PR | 98 | 100 | 38 | 12 | 6 | 4 | 2 | 0

Since this PR code resulted in far better performance, I think it should be fixed.

**Comment by gante** [comment]
Hey @bzantium 

As I've written above, I will only consider merging after showing conclusive results that the change is a net positive -- with perplexity plots and execution time measurements. So far, you've only shown results in line with https://github.com/huggingface/transformers/pull/27033

**Pull request closed without merging**
