### PR TITLE
Exclude Databricks from notebook env only if the runtime is below 11.0

### PR DESCRIPTION
**Pull request by davidheryanto**
# What does this PR do?

This PR adds additional check to `is_in_notebook()` to return `False` in Databricks only if the Databricks Runtime is below 11.0. In Databricks Runtime 11.0 and above, IPython kernel is the default Python execution engine. Therefore it should be more compatible with Jupyter notebook https://docs.databricks.com/notebooks/ipython-kernel.html

https://github.com/huggingface/transformers/issues/17406#issuecomment-1172510084

## Additional Info

In Databricks Runtime 10.5 and earlier this is what the evaluation HTML output used to be. Therefore, we need to disable the notebook env. 
image

In Databricks Runtime 11.0 with the default IPython kernel, the output looks similar to that in Jupyter notebook. Therefore, I believe we no longer need to disable the notebook env.
image

What does the value of `DATABRICKS_RUNTIME_VERSION` environment look like in Databricks notebook?
image

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Thanks for the fix!

**Comment by sgugger** [comment]
Arg, our CI wasn't triggered properly. Could you try pushing an empty commit?

**Comment by davidheryanto** [comment]
Sure. I pushed a dummy commit removing a full stop in the comment.

**Comment by sgugger** [comment]
Didn't work again, there should be more tests spawning. You can do empty commits with `--allow-empty` to avoid having to do a real change. Can you try a couple of times to see if the test suite starts (there should be 18 checks total)?

**Comment by davidheryanto** [comment]
Hmm still not sure why the CircleCI tests are skipped haha

**Comment by sgugger** [comment]
Okay managed to trigger it by pushing your branch inside the main fork of the repo. Let's just check all is green before merging, thanks for your patience!

**Comment by davidheryanto** [comment]
Thank you. Appreciate the quick feedback

**Pull request merged**
