### PR TITLE
Misfiring tf warnings

### PR DESCRIPTION
**Pull request by Rocketknight1**
One last misfiring TF warning switched to `tf.print`.

### CODE REVIEW

**Comment by Rocketknight1** [comment]
I think this is the last misfiring warning (this one is usually triggered in Seq2Seq models). I'm a little worried that there's some use-case where this will actually cause console spam instead, but I think it's safe.

**Comment by Rocketknight1** [comment]
Aaa, wait! In some examples this is actually much worse. I believe the warning isn't even correct/necessary anymore, though - I'm doing some testing to see if it even makes sense with modern TF.

**Comment by Rocketknight1** [comment]
After testing, I don't think this warning even makes sense anymore - I had no problems changing the values of these arguments at call-time instead of model initialization. I presume this dates from a time when TensorFlow had much more trouble with function retracing.

**Review by gante — APPROVED** [review]
LGTM

**Review by sgugger — APPROVED** [review]
Thanks!

**Pull request merged**
