### PR TITLE
docs: ko: sagemaker.mdx

### PR DESCRIPTION
**Pull request by jungnerd**
# What does this PR do?

Part of  #20179 (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/transformers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests),
      Pull Request section?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link
      to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/transformers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@wonhyeongseo, @HanNayeoniee, @0525hhgus, @KIHOON71, @sim-so, @gabrielwithappy
Team Pseudo-Lab, please review this PR.

### CODE REVIEW

**Comment by wonhyeongseo** [comment]
Also please mention @HanNayeoniee instead of your id(@jungnerd) for requesting review on the last 2 lines of your main PR message. Thank you.

**Comment by jungnerd** [comment]
> Also please mention @HanNayeoniee instead of your id(@jungnerd) for requesting review on the last 2 lines of your main PR message. Thank you.
> 
> Edit: or just add her 😄 your choice really. Thank you so much for participating on Saturday's meeting.

Thanks for telling me. I've fixed the commit.🤭

**Comment by wonhyeongseo** [comment]
We should also update `_toctree.yml`, and I can help with this anytime. Please feel free to ping me on KakaoTalk. 🙌

**Review by sgugger — APPROVED** [review]
Thanks for your contibution!

**Comment by HanNayeoniee** [comment]
Great work! First PR of Pseudo-lab team!
I think [WIP] tag needs to be removed since it's been merged.

**Pull request merged**
